### ISSUE TITLE
Initiate VANotify Veteran User Research

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/notification-api#10]
- [x] Create user journey mural
- [x] Create research plan and add to github
- [x] Create discussion guide and add to github
- [x] Schedule research plan review to initiate scheduling

**Comment by toddstanich** [comment]
Research folder with WIP plan and discussion guide - https://github.com/department-of-veterans-affairs/vanotify-team/tree/master/research

**Comment by toddstanich** [comment]
Research plan submitted to recruiting on 7/14
