### ISSUE TITLE
Lambda for Inbound SMS

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#1003]
## Goal

Write Pinpoint inbound sms messages to inbound_sms table

## Checklist

- [ ] Verify that Lambda can connect to db during initialization of lambda
- [ ] Verify that payload coming into lambda comes from SQS
- [ ] Verify structure of payload to match a Pinpoint message
- [ ] Write message to inbound_sms table 
- [ ] If there is a failure at any point during processing, have the lambda throw an error so message gets replayed OR gets dropped to dead letter queue
- [ ] if everything succeeds return 200.

**Comment by trevor2718** [comment]
Waiting for review.

**Comment by npmartin-oddball** [comment]
Closing.
