### ISSUE TITLE
Update notify two way sms handling lambda API to manage opt outs

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1008]
https://github.com/department-of-veterans-affairs/notification-api/pull/994/files/44773a69b312d5b1f4f07b1f6c27b47eef710459#r1046417836

Notify Two Way SMS currently lets AWS handle opt out unless a business line wants to explicitly handle it.  To be consistent about onboarding, it may be worth it to have all opt outs be part of self managed and if the business line doesn't want to do it, then we can do it on their behalf.  

The code in API is currently commented out with a **NOTE** decorator.

**Comment by k-macmillan** [comment]
Needs a lot of detail. Still an issue, keeping.
