### ISSUE TITLE
Create S3 bucket for VA logo

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#101]
To include VA branding in our email templates, we need to create an S3 bucket and store the VA logo in it.

The same bucket will be used for services to upload their own logos.

- [x] Use terraform to create an S3 bucket (for each environment)
- [x] Use terraform to put the VA logo in that S3 bucket
- [x] Make VA logo publicly accessible
- [x] Make bucket private

**Comment by ffafara-tw** [comment]
There seems to have been an issue where terraform was not properly applying ACL on an already created object.

Recreating s3 object did the trick.
