### ISSUE TITLE
Standard Lambda Package To Handle Reusable Processes

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1010]
## Value Statement
**As** an engineer
**I want to** not repeat past work or copy/paste from past work
**So that** I can effectively develop new features

We would like a tool that can help ensure consistency, expedience, and confidence regarding new lambda creation. Many lambdas share common problems:
- Need to get data from SSM
- Need to connect to the database
- Need to make requests
- Need to push to SQS
- etc.

## Acceptance Criteria

**GIVEN** Lambda work is required
**WHEN** doing common operations (ssm params, db queries, post requests, etc.)
**THEN** we instead use the common package

## Checklist

- [ ] Package setup as  a lambda layer
- [ ] SSM lookup (maintains/refreshes the connection)
- [ ] Able to handle db connections
- [ ] Able to push to SQS

## Constraints
- Each functionality is self-contained
- Each functionality is only called if used in the lambda (necessary due to infra permission requirements)
- Exists as a module we import e.g `from notify_common import db`

## Additional Info/Resources

-

## Out of Scope

- 

## Open Questions

-

**Comment by npmartin-oddball** [comment]
Actively working on this. Doesn't need to be a standalone ticket.
