### ISSUE TITLE
BUG: 2-Way SMS null URI should not go to retry queue

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1011]
Bug
## Description
_**Required.** Describe the problem._
As an SMS client not using VA.gov/VA Profile to manage notification preferences
I want to manage my own opt-outs
So that I can update the Veteran's preference in my system

For inbound numbers, it is possible using the API to set self_managed to be true but the url_endpoint to be null. However, if a client is self managed we must send the SMS responses to them, which means the URL field should not be blank.

## Steps to Reproduce
_**Required.** Provide information on what steps you are aware of that produce this undesired outcome.._

- Add a number to inbound numbers {{notification-api-url}}/inbound-number using postman (example body below)
```
{
    "number": "+15738792361",
    "provider": "pinpoint",
    "self_managed": true,
    "url_endpoint": null
}
```
- Assign the inbound number to an existing or new sender if not yet created
```
    {
        "inbound_number_id": <inbound id from what you created above>,
        "rate_limit": null,
        "rate_limit_interval": null,
        "service_id": "<applicable service>",
        "sms_sender": "+15738792361",
        "sms_sender_specifics": null
    }
```
- In Pinpoint, navigate to the phone number and update the setting to be self managed and assign the applicable SNS topic for 2 way messaging to be enabled. See more here: https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Inbound.md
- Text the phone number to trigger an inbound response
- See that message goes to retry queue

## Workaround
_Is there something we can do to work around this issue in the meantime? Leave blank if n/a._
This error will continue to retry until the end of the series.

## Impact/Urgency
_**Required.** Describe the impact this bug has on our system, clients, and/or team._

- This is a configuration error so theoretically it should be caught during setup

## Expected Behavior
_**Required.** Describe the desired outcome if this were functioning as expected. Include a checklist if applicable._

- Configuration errors that will never succeed, like this missing URL, should not retry but instead go to deadletter queue
- We should not be able to misconfigure this via the inbound-numbers endpoint

- [ ] ?

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
_If applicable, include extra information to assist with troubleshooting, like screenshots, log snippets, links to applicable code files, and/or articles/websites that have relevant info on the issue. Leave blank if n/a._

**Comment by mjones-oddball** [comment]
@jakehova @kalbfled I recall you two worked on the inbound/2 way process. Can you help fill out the expected behavior section/checklist?
CC @tabinda-syed @k-macmillan

**Comment by tabinda-syed** [comment]
@jakehova @kalbfled Could one or the two of you please fill out any remaining items for the Expected Behavior checklist by Tuesday 3/14?

**Comment by k-macmillan** [comment]
To update at a later time. Keeping.

**Comment by npmartin-oddball** [comment]
Closing for now. Will address when working with enp-api.
