### ISSUE TITLE
Notify Incoming SMS Lambda - Altered SSL Context

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1012]
## Value Statement

The lambda currently has `verify=False` setup due to the way requests sets up TLS. We likely need a refined SSL context to allow intranet -> internet. 

## Acceptance Criteria

**GIVEN** The notify incoming sms lambda triggers
**WHEN** making `POST` requests to endpoints
**THEN** those `POST` requests will be secured

## Checklist

- [ ] Options understood
- [ ] Method of setting SSL context decided on
- [ ] Documentation updated for clients (Services)
- [ ] Implemented
- [ ] Works within the VA Network
- [ ] Works outside the VA Network

## Assumptions

- This is possible through some combination of SSL settings (there are many)

## Additional Info/Resources

- [SSL](https://docs.python.org/3.8/library/ssl.html) module
- [Requests](https://requests.readthedocs.io/en/latest/user/advanced/#client-side-certificates) module

**Comment by k-macmillan** [comment]
Still an issue, keeping.

**Comment by npmartin-oddball** [comment]
Closing. Will work on this when working on enp-api.
