### ISSUE TITLE
Remove the "two-way-lambda" and Associated Code

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1013]
## Issue
We have switched all two-way SMS to a standard model but the past model is still in our codebase and needs to be removed. Identify the different aspects and remove them. More details to come...

Edit: the following added by Cris 11/08/2024
The original two way lambda that this ticket refers to is actually still being invoked in prod.  [Direct link to Datadog](https://vanotify.ddog-gov.com/logs?query=host%3A%22arn%3Aaws-us-gov%3Alambda%3Aus-gov-west-1%3A171875617347%3Afunction%3Aproject-prod-two-way-sms-lambda%22%20source%3Alambda&agg_m=count&agg_m_source=base&agg_q=status%2Cservice&agg_q_source=base%2Cbase&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&sort_m=%2C&sort_m_source=%2C&sort_t=%2C&storage=hot&stream_sort=desc&top_n=10%2C10&top_o=top%2Ctop&viz=pattern&x_missing=true%2Ctrue&from_ts=1729537239543&to_ts=1729808941250&live=false) logs for Oct 21-24, 2024.

We need to determine why this is still in use if we believe we changed all of this, who is invoking it, and a path to resolution.

Notes:

- project-{{env}}-notify-incoming-sms-lambda is the lambda that was supposed to replace this lambda. Uses `two_way_sms_v2.py`
- project-{{env}}-two-way-sms-lambda is supposed to be decommissioned based on new lambda (above) but is still in use. Uses `two_way_sms_lambda.py`
- Ticket needs to be updated with the new story template.

## Checklist

- [ ] Components removed

## Assumptions

- An associated infra ticket will remove the related infrastructure

**Comment by npmartin-oddball** [comment]
Keeping. Changes Requested label stays as ticket needs to be expanded.

**Comment by npmartin-oddball** [comment]
Scratch that. Closing. Will work on this when working on enp-api.
