### ISSUE TITLE
Modify lambda packaging for requests layer creation

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1017]
This is a companion ticket for [vanotify-infra 480](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/480), which will create a lambda layer for the "requests" Python package.

- [x] Modify [lambda-functions.yml](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/lambda-functions.yml) so it doesn't package `requests` for affected lambdas:

```bash
...notification-api$ grep -l requests lambda_functions/*/requirements-lambda.txt
lambda_functions/two_way_sms/requirements-lambda.txt
lambda_functions/vetext_incoming_forwarder_lambda/requirements-lambda.txt
```

Contrary to the verbiage of the infra ticket, do not remove requirements-lambda.txt files, which are still desirable for documentation.

**Comment by kalbfled** [comment]
I have made my first round of changes for this. I am waiting for infra dev to become available for me to deploy and test.

**Comment by kalbfled** [comment]
Work is complete (assuming no PR change requests).  This will be merged after 12/21 due to the upcoming release.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1017?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @k-macmillan @kalbfled @ldraney @trevor2718
