### ISSUE TITLE
Billing: Populating sender_id in the notification object for SMS

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1021]
## Issue
During work on [#971](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/971) it was discovered that the notification object doesn't contain anything tying it back to the sms sender (e.g. what phone number the message was sent from). sent_by exists, but contains the provider name (e.g. pinpoint), which isn't what we want.

As VA Notify
I want to track billing data by sms sender
So that I can calculate the appropriate messaging costs for the Franchise Fund monthly

When an SMS notification is sent
And the notification object is created
Then the notification object should include the sms_sender_id

There's 2 methods that a client can use to send an sms notification. They can include the sms_sender_id directly in the request, or send the request without it - which requires there to be a default sms_sender on their service. In both cases we need to make sure the notification object is updated with the sms_sender_id.

## Checklist
- [x] Update models.py
    - [x] Add a new field `sms_sender_id` to the table `notifications`. This value correlates to the `sms_senders.id` UUID.
- [x] Update the [serialize](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/models.py#L1549) method to include the new field
- [x] Update the[ open api swagger documentation](https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml) and postman collection for /v2/notifications/{{notification-id}}
- [x] Validations
    - [x] When you send an sms notification via `/v2/notifications/sms` with sms_sender_id in the request body the notification object is updated with the sms_sender_id. You can use `/v2/notifications/{{notification-id}}` to confirm.
    - [x] When you send an sms notification via `/v2/notifications/sms` without including sms_sender_id in the request body the notification object is updated with the sms_sender_id. You can use `/v2/notifications/{{notification-id}}` to confirm.
- [x] QA

## Additional Information
sms_sender_id [lookup](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/v2/notifications/post_notifications.py#L422):
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/ab0647ea-2745-4ab2-88af-a8c4e11e5864)
Database Update call:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/311a4edf-ed5f-47de-88d7-e83f5fb82dce)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1021?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @k-macmillan @kalbfled @ldraney @trevor2718

**Comment by mjones-oddball** [comment]
@cris-oddball FYI this is one ticket in the billing work that will have to be done post-12/21 - we will discuss more in refinement next week. We can strategize on how we will address QAing it after the new year.

**Comment by kalbfled** [comment]
The openapi spec already includes sms_sender_id.  [Here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml#L1083) is one instance in openapi, and [here](https://github.com/department-of-veterans-affairs/notification-api/blame/master/scripts/postman/notification-api.postman_collection.json) is one instance in the Postman collection.

**Comment by kalbfled** [comment]
I have been working on this ticket for a week, and it's still in progress.  I have all unit tests passing for GET requests, and I'm still working on POST requests.  I recommend re-pointing to an 8.

**Comment by kalbfled** [comment]
I'm down to one [failing user flow test](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3844220629/jobs/6547467808).

**Comment by kalbfled** [comment]
@cris-oddball My thoughts on QA for this ticket:

## V2 requests made using a recipient's phone number

- [ ] POST /v2/notifications/sms with no sms_sender_id elicits a 4xx response
- [ ] POST /v2/notifications/sms with a valid sms_sender_id elicits a 201 response that includes the new notification's ID
- [ ] GET /v2/notifications/{previous response ID} response includes the sms_sender_id provided in the POST data
- [ ] POST /v2/notifications/sms with a null sms_sender_id for a service that has a default sms_sender_id elicits a 201 response that includes the new notification's ID
- [ ] Test GET response as before
- [ ] POST /v2/notifications/sms with a null sms_sender_id for a service that does not have a default sms_sender_id elicits a 4xx response

## V2 requests made using a recipient_id

- [ ] All the previous tests also work using recipient_id instead of phone_number

## V1 requests (Optional?)

The V1 route /notifications/sms is not part of our OpenAPI or Swagger specifications, but it's still in the code.  I had to update it along with V2 to get all the unit tests to pass.

- [ ] V1 functionality for creating an SMS notification works the same as the V2 functionality

This begs the question, "What is the difference between V1 and V2?"  I don't know.

**Comment by cris-oddball** [comment]
QA PASSED

Noting that some of the VA Profile IDs are messed up and it wasn't until late in testing that I found IDs that could actually be delivered to, but the responses still contained all of the correct data.

[ ] POST /sms with phone number and a valid sms_sender_id returns 201
[ ] GET v2/notifications returns that sms_sender_id in response ("sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4")

[ ] POST /sms with phone number and a null sms_sender_id returns 201
[ ] GET v2/notifications returns service's sms_sender_id in response "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4",

[ ] POST /sms with phone number and a no sms_sender_id returns 201
[ ] GET v2/notifications returns service's sms_sender_id in response "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4",

For these, set sms_sender_id to the second one in the list
[ ] POST /sms with recipient_identifier BIRLSID and a valid sms_sender_id returns 201
[ ] GET v2/notifications returns that sms_sender_id in response. "sms_sender_id": "e0a5e00a-1d99-4004-98b8-e50d47af05da", also noting "status": "temporary-failure",

[ ] POST /sms with recipient_identifier BIRLSID and a null sms_sender_id returns 201
[ ] GET v2/notifications returns service's sms_sender_id in response. "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4", also noting "status": "temporary-failure"

[ ] POST /sms with recipient_identifier BIRLSID and no sms_sender_id returns 201
[ ] GET v2/notifications returns service's sms_sender_id in response. "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4", , also noting "status": "sent" for 15 minutes

[ ] POST /sms with recipient_identifier VAPROFILEID and a valid sms_sender_id returns 201
[ ] GET v2/notifications returns that sms_sender_id in response. "sms_sender_id": "e0a5e00a-1d99-4004-98b8-e50d47af05da", notification id 860f69dc-0423-41b4-8447-74e83b24b848 noting "status": "sent" for 15 minutes

[ ] POST /sms with recipient_identifier VAPROFILEID and a null sms_sender_id returns 201
[ ] GET v2/notifications returns service's sms_sender_id in response. "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4", notification id ae96f20c-991d-4fa8-aea7-173b2373e73e, noting "status": "temporary-failure",

[ ] POST /sms with recipient_identifier VAPROFILEID and no sms_sender_id returns 201
[ ] GET v2/notifications returns service's sms_sender_id in response. "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4",. Notification ID 6a7d1a22-c7c7-47ad-85ca-16cdce6f9ed8. "status": "temporary-failure",

[ ] POST /sms with recipient_identifier ICN and a valid sms_sender_id returns 201
[ ] GET v2/notifications returns that sms_sender_id in response. "sms_sender_id": "e0a5e00a-1d99-4004-98b8-e50d47af05da",. Notification ID 9e2547a3-3a91-44a3-aa6f-60e9dc893114.  status": "temporary-failure",
Retry:
ICN 1012845074V891241, Notification ID 4f086f9a-d101-4f8d-97eb-9037f16b1b19, "sms_sender_id": "e0a5e00a-1d99-4004-98b8-e50d47af05da", "status": "delivered",

[ ] POST /sms with recipient_identifier ICN and a null sms_sender_id returns 201
[ ] GET v2/notifications returns service's sms_sender_id in response. "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4". Notification ID 8a928d56-28b3-4312-9ccc-851964443d8e.

[ ] POST /sms with recipient_identifier ICN and no sms_sender_id returns 201
[ ] GET v2/notifications returns service's sms_sender_id in response. "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4". Notification ID 24bf7d95-b60a-4f6d-8ecd-47c7bca6d2a0.

[ ] Service with NO default sms_provider_id returns 4xx on POST /sms
{
    "errors": [
        {
            "error": "BadRequestError",
            "message": "You must supply a value for sms_sender_id, or the service must have a default."
        }
    ],
    "status_code": 400
}

[ ] v1 notifications route returned 200 and "sms_sender_id": "286d6176-adbe-7ea7-ba26-b7606ee5e2a4",
