### ISSUE TITLE
Billing: Update nightly billing upload with sender_id and sender

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1022]
# Description
During work on #971 it was discovered that the notification object doesn't contain anything tying it back to the sms sender (e.g. what phone number the message was sent from). sent_by exists, but contains the provider name (e.g. pinpoint), which isn't what we want.

As VA Notify
I want to track billing data by sms sender
So that I can calculate the appropriate messaging costs for the Franchise Fund monthly

When billing data is aggregated daily in `fetch_nightly_billing_counts`
Then sender_id and sender should be populated
And data should be grouped by sender in addition to date, template_id, and billing_code

- [x] Update `fetch_nightly_billing_counts` in https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/dao/fact_billing_dao.py:
    - [x] lookup and populate sender_id from notifications.sms_sender_id
    - [x] lookup and populate sender (ServiceSmsSender.sms_sender) by the sender_id = ServiceSmsSender.id
- [x] Validation
    - [x] the CSV uploaded to S3 has sender_id and sender populated as expected
    - [x] the data in BigQuery contains the sender_id and sender for new uploads (day forward)
- [ ] QA

# Additional Info
The code is basically written, but is currently commented out. Check `TODO #1022` comments. It's just waiting on 1021 to be completed.

**Comment by mjones-oddball** [comment]
@cris-oddball FYI billing part 2 ticket 2 (blocked by #1021) - will discuss more in refinement

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1022?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @k-macmillan @kalbfled @ldraney @trevor2718

**Comment by kalbfled** [comment]
I texted myself with the API dev deployment.  Tomorrow, I will verify the stats reflect this.

**Comment by kalbfled** [comment]
I texted myself with the API dev deployment. Tomorrow, I will verify the stats reflect this.

**Comment by kalbfled** [comment]
I attempted to deploy the 1022 branch tonight, but I encountered a [Twistlock failure](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3889596083/jobs/6638019265).

**Comment by kalbfled** [comment]
Stats generation doesn't seem to be working.  I sent myself a text message a couple of nights ago, and I don't see it in Big Query for dev.  In fact, I don't see anything for dev newer than December 18th.

```sql
notification_api=> select created_at, id, service_id from notifications where "to"='<my number>' order by created_at desc limit 1;
         created_at         |                  id                  |              service_id
----------------------------+--------------------------------------+--------------------------------------
 2023-01-10 15:24:22.344754 | 781d7f6e-40dc-442a-a37a-35d13af55ace | d6aa2c68-a2d9-4437-ab19-3ae8eb202553
```

**Comment by cris-oddball** [comment]
@kalbfled Given that the log is full of errors, might be a reasonable place to start.

One log example
https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fproject-dev-nightly-billing-stats-upload-lambda/log-events/2023$252F01$252F12$252F$255B$2524LATEST$255D544fd13c19d44bd7804aa61d683d0b04

One error example showing that it is trying to parse UUIDs as INT64.
```
[ERROR] BadRequest: 400 Error while reading data, error message: Could not parse '55b097e9-f084-4b66-a616-23345c0f1178' as INT64 for field count (position 8) starting at location 105  with message 'Unable to parse'
Traceback (most recent call last):
  File "/var/task/nightly_billing_stats_upload_lambda.py", line 92, in lambda_handler
    add_updated_rows_for_date(bigquery_client, table_id, nightly_stats)
  File "/var/task/nightly_billing_stats_upload_lambda.py", line 64, in add_updated_rows_for_date
    bigquery_client.load_table_from_file(
  File "/var/task/google/cloud/bigquery/job/base.py", line 727, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/var/task/google/api_core/future/polling.py", line 261, in result
    raise self._exception
```

**Comment by kalbfled** [comment]
Thank you.  I will take a look at that.  I'm moving the ticket back to "to do" since this seems to require more work.

**Comment by EvanParish** [comment]
There was one place where the code wasn't changed yet. I've corrected that and we are now getting data in BigQuery. 👍 It looks like the `sender` and `sender_id` are still not being populated however. 👎 I'll keep looking into this to see what might be causing that.

![image](https://user-images.githubusercontent.com/104009494/212423386-27ed02d7-eec0-456d-a730-77950a599934.png)

**Comment by Eallan919** [comment]
Moved ownership to Evan.

**Comment by Eallan919** [comment]
Em set up working session for team today!

**Comment by EvanParish** [comment]
During the working session today with the engineering team, we ran the query on the database and retrieved the expected data. We didn't see any reason for the information to be missing. The code was behind master, so it has been rebased. Some test sms messages were sent and the code will be deployed tonight. I'll double check the information that comes through in the morning.

**Comment by Eallan919** [comment]
Update: It works!!!!

**Comment by cris-oddball** [comment]
Sending this all the way to staging for testing with the certificate release.

**Comment by cris-oddball** [comment]
Send a number of sms messages all using phone numbers on both stg and perf. Will check Big Query in the morning. Will also do some recipient ID testing tomorrow to check on Monday.

**Comment by cris-oddball** [comment]
**QA PASSES**

Results for [Perf](https://docs.google.com/spreadsheets/d/1tvFxZfMofx-WJS2xwXoRnzjeYrM010km1Ru3boYW0ZE/edit?usp=sharing)
- Matches the test sends from yesterday
- Populates sms_sender and sender_id for the past 4 days

Results for [Staging](https://docs.google.com/spreadsheets/d/1BDsJ-6_HijtSw7vp8Sshieqx99kV6Vr_ngmadJdlpcY/edit?usp=sharing)
- Matches the test sends from yesterday
- Populates sms_sender and sender_id for the past 4 days
