### ISSUE TITLE
Setup 'From', 'Reply to', name for the 526EZ email 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#103]
**Acceptance Criteria:**
1. Default 'From' email address - 
- The appropriate From email address needs to be included 'notifications@messages.va.gov' 

2. No default email address for 'Reply to'
- The appropriate Reply to email must be included 'donotreply@messages.va.gov'
- Add content in the footer to indicate not to respond using reply   

3. Name for the email address 
- The appropriate name must display for the email 'U.S. Department of Veterans Affairs' 

**Assumptions:** 
- This story requires the GovDelivery account setup to be complete

**Notes:**
- From email address is 'notifications@messages.va.gov'. Changed from previous email address 'notify@messages.va.gov'
- Validation for this card must include replying to the do no reply email address 
- After dev analysis move to blocked until GovDelivery account setup is complete

** Final content for the do not reply auto response: (Setup was done with Granicus)**

Subject line: This message has been sent to a mailbox that isn’t monitored

This mailbox isn’t checked by anyone. Messages sent to this address won’t get a reply. If you need to reach someone, please use the contact information below.

If you’re a Veteran in crisis and need immediate help, please call 800-273-8255 and press 1. Or visit www.veteranscrisisline.net.

If you have questions or need more information about your benefits, please visit VA.gov or call us at 844-698-2311 (TTY:711).

**Comment by marisahoenig** [comment]
Blocked because of granicus contract. Currently being worked on (convo today!)

**Comment by anushyaprasad** [comment]
We now have the contract and Granicus is working on creating our staging and prod environments. Can we please pick this up next?
