### ISSUE TITLE
BUG: Twilio callback url is pointing to internal notification.va.gov address

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1034]
When our twilio client is used to initiate an SMS send, it includes a callback URL for delivery status.  That callback URL is used by Twilio to deliver delivery statuses for that particular message. 

The issue is that the callback URL that is being used uses our notifications.va.gov address, which is not accessible to public internet.  This is result in 500 errors in Twilio for EVERY SMS request that goes through Notify that uses Twilio.  

We need to: 
- [x] in the short term, remove that callback url from being associated with the Twilio Client send, 
  * easiest way to do this may be to change __init__.py line 119 to set callback_notify_url_host to None

The URL code for the twilio client is in: 
* initialization of Twilio Client: app/__init__.py line 119
  * ```
    twilio_sms_client.init_app(
        logger=application.logger,
        callback_notify_url_host=application.config["API_HOST_NAME"]
    )
    ```
* assignment of callback URL: app/clients/sms/twilio/py line 33
* inclusion of callback URL in request: app/clients/sms/twilio/py line 52

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1034?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @k-macmillan @kalbfled @ldraney @ianperera
