### ISSUE TITLE
Implement bandit & python-safety to secure VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#104]
# Value Statement
As a developer I want to utilize ~Hawkeye~ bandit and python-safety to identify any security related concerns.

# Acceptance Criteria
*1. No security related concerns*
Given I am deploying VANotify 
When I run the pipeline
Then the job successfully completes 

*2. Security related concerns identified*
Given I am deploying VANotify 
When I run the pipeline
Then the job fails along with displaying the security related concern(/s)

# Checklist
- [ ] ~Configure Hawkeye in  `.hawkeyerc` file  ([instructions](https://github.com/hawkeyesec/scanner-cli#configuration-files-recommended)~
- [ ] ~Add these modules:~
    - [ ] ~python-bandit: Scans for common security issues in Python code with bandit.~
    - [ ] ~python-piprot: Scans python dependencies for out of date packages with piprot~
    - [ ] ~python-safety: Checks python dependencies for known security vulnerabilities with the safety tool.~

After looking into the implementation, we (Filip & Marisa) decided to instead install bandit and python-safety on their own. When we tested using the Hawkeye docker image, python-bandit was an older version of Python, and python-piprot is not maintained. We think there will be more value in implementing bandit separately.

- [x] bandit - common security issues
- [x] python-safety - python dependencies for known security vulnerabilities

- [x] Integrated into CI using Docker ([Docker instructions](https://github.com/hawkeyesec/scanner-cli#docker-recommended))

# Resources
- [Hawkeye Scanner CLI](https://github.com/hawkeyesec/scanner-cli)
- [Modules in Hawkeye](https://github.com/ineffyble/hawkeye#modules) - explains how Hawkeye modules work and which modules we will have (generic + python + any others we want)
- Bandit: https://pypi.org/project/bandit/#description

# Notes
- This card includes the implementation of Bandit as #125 was deprecated  
- During Dev Analysis we need to list what specific security function is covered: common security issues, python dependencies, security vulnerabilities (modules listed in checklist)
- Please review the respective [ADR](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/documents/adr/0005-select-tools-to-secure-VANotify.md) for detailed information

# Assumptions
- This involves completing the work identified after the Spike #99 is complete
- Ling's matrix and recommendations documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1wmWVBbnpzYUcEiNc3lQjwNUhOhxSQtB-WZTc3dDUyKI/edit#gid=0) 
- Discuss where in the pipeline we want to put these security checks, example: is it called from Terraform (this must be finalized in Dev Analysis)
- After Dev Analysis or as a part of the kickoff this card will be estimated 
- Rules used for scanning can be adjusted as part of the implementation 

# Out of Scope
- Adding monitoring and alerts for this is not in scope 
- When the tool is successfully implemented, this information must be provided for documentation in the ATO. This will be a separate task not in scope for this card

# Open Questions
- Do we want Hawkeye and Bandit to be implemented only in our pipeline or also as pre-commit hooks?
    - pipeline only for now (see how long it would take as precommit hook - followup story)
- Should the Hawkeye scan be a separate job in the pipeline, maybe after `test`? For now, should this be in TW AWS terraform or VA AWS  (or both?)?
    - happens in build, not deploy - which is only in one
- Just to confirm, if any of the checks fail, the job should fail? yes
- where to put in pipeline & parallelize - parallel with unit tests then build final docker image? then push to ECR

**Comment by marisahoenig** [comment]
Fixed dependencies in utils. Checked upstream at CDS Notify, and they did the same upgrades. They upgraded Bleach to 3.1.4 (I did 3.1.5 since it's the newest and was a minor change) and pyyaml to 5.3.1

**Comment by marisahoenig** [comment]
Desk check passed & moved directly to sign off since there's nothing to test that wasn't shown in the desk check.

I am following up on the commercial account of pyup and possibly adding a precommit hook for bandit, but these will be separate cards if we decide to implement them.
