### ISSUE TITLE
Update SMS API validation exceeding character limit behavior

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1041]
## Current Behavior
Currently, if a client (VEText, BVA, VA Insurance) sends an SMS API request with a character limit exceeding 4 segments (612 characters), the request fails and logs "Content for template has a character count greater than the limit of 612".

Prior to the migration, these messages would have successfully sent to Veterans. The impact is that notifications are failing to send to Veterans due to the length of the message.

## Expected Behavior
When a client sends an sms request via `{{notification-api-url}}/v2/notifications/sms`
and the character limit of the message is greater than 612
then we should log this as a warning
and send a 201 response back to the client

## Request

- [x] Update the logic so it does not raise an exception when the sms char count is > 612
- [x] Update our logging to include this message as a warning

## Validation

- [x] Using the API send an SMS request that contains more than 612 characters via {{notification-api-url}}/v2/notifications/sms and confirm this request receives a successful response
- [x] QA

## Additional Information
There are many places that utilize `SMS_CHAR_COUNT_LIMIT`:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/9a158fe3-2c1b-4a8d-ae8d-47da049af0b9)

Location of raised error:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/a4d98561-fac4-4333-a4a4-aa967ac223ce)

**Comment by kalbfled** [comment]
I think I'm mostly finished with this ticket.  I need to figure out the correct way to mock, or otherwise verify, the warning log output.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1041?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @k-macmillan @kalbfled @ldraney @ianperera

**Comment by kalbfled** [comment]
Per our conversation in today's Planning meeting, it might be adequate manually to verify that a logging message occurred if verifying that behavior in a unit test becomes a rabbit hole.

**Comment by ianperera** [comment]
as per the @kalbfled comment, I have done some research and found serval approaches to get logging done for unit testing. I will be completing this ticket today.

**Comment by k-macmillan** [comment]
Warning appearing in the logs and showing the SMS was still created. Also received the text.
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/cfdc0c84-51da-41c1-a364-2a06c0643670)

**Comment by cris-oddball** [comment]
**QA PASSES**

- [ ] Sending an sms where char count is under 612, should receive a 201, message is delivered
- [ ] Sending an sms using a personalized template where the personalization exceeds 612, should receive a 201, message is delivered, and warning message in logs that char limit is exceeded.
Logs:
```
{
    "name": "app",
    "levelname": "WARNING",
    "message": "The personalized message length is 613, which exceeds the 4 segments length of 612.",
    "pathname": "/app/app/notifications/validators.py",
    "lineno": 163,
    "time": "2023-01-13T19:12:18",
    "requestId": null,
    "application": "app",
    "logType": "application"
}
```
```
WARNING 2023-01-13 19:12:18,193 /app/app/notifications/validators.py:163: The personalized message length is 613, which exceeds the 4 segments length of 612.
```
