### ISSUE TITLE
utils.py import statements inside functions

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1044]
### User Story(ies)
**As a** developer,
**I want** to avoid circular dependencies
**So that** the code is cleaner and less prone to break upon revision.

### Additional Info and Resources

N/A

## Engineering Checklist

The file [app/utils.py](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/utils.py) contains import statements inside functions.

- [ ] Determine if this is necessary to avoid circular dependency errors.
- [ ] Determine if there is a better way to structure the code.  If so, refactor.
- [ ] Delete the TODO comment at the top of the file.

## Acceptance Criteria
_**Required**_
- e.g. when I send an email using an identifier, we retrieve the user’s email address in VA Profile and successfully deliver the email to that recipient

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by k-macmillan** [comment]
Not going to be worked.
