### ISSUE TITLE
Billing: Populating cost and total message parts in the notification object for SMS

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1049]
## Issue
Cost is calculated by SMS outbound rates per short code or 10DLC and is done by message part (aka segment). In order to accurately assess cost we need more information. During a call with Amazon recently, we discovered that the event streaming we use to retrieve message status also contains the cost and total number of message parts (segments).

As VA Notify
I want to aggregate costs of outbound SMS messages
So that I can calculate the appropriate messaging costs for the Franchise Fund monthly

When an SMS notification is sent
And Pinpoint streams an event to us
Then the notification object should include the cost and total message parts

See meeting with Amazon and notes on meeting in this [google folder](https://drive.google.com/drive/folders/1rw-cmyalcDVoBan2iTdXC6OAcccLRyo0?usp=sharing)

## Checklist
- [x] Identify the fields containing message cost and message parts
- [x] Update models.py
    - [x] Add a new field to represent the cost in table `notifications`: `cost_in_millicents`
    - [x] Add a new field to represent the total number of message parts in table `notifications`: `segments_count`
- [x] Update the [serialize](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/models.py#L1549) method to include the new fields
- [x] Update unit tests
- [x] Update the[ open api swagger documentation](https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml) for /v2/notifications/{{notification-id}} 
- [x] Validations
    - [x] When you send an sms notification via `/v2/notifications/sms` the notification object is updated with the cost and total message parts (please note there may be a slight delay from time of send to when Pinpoint sends back the status event). You can use `/v2/notifications/{{notification-id}}` to confirm.
- [x] QA

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1049?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @k-macmillan @kalbfled @ldraney @ianperera

**Comment by kalbfled** [comment]
I discussed this with Jacob.  My understanding is that AWS Pinpoint is configured to dump data into an AWS Kinesis "event stream," and the data eventually makes its way to notification-api as a celery task created by a lambda function.  I need to inspect this data to determine its format so I can capture it in our database(s).

**Comment by kalbfled** [comment]
I think I'm hard-blocked on this task now.  I need to be able to deploy my branch, which contains a migration and logging changes to be able to see the callback data coming from AWS, but I'm getting a Twistlock failure and a migration failure when I try to deploy the branch.  I rebooted the Twistlock container, but that didn't fix it.  I created a "no-twistlock" branch that removes Twistlock from the workflow, but the migration still failed with a useless error output.  My migration works locally with containers.  I deployed infra master before trying any of this.

**Comment by cris-oddball** [comment]
@kalbfled I re-ignored the twistlock entries that were causing twistlock to fail. I also wrote and posted in the team channel a document in our teams repo describing how to handle twistlock scans that fail. I'll boot up a meeting so that we all get on the same page, because just bypassing twistlock in github actions is not the solution. cc/ @k-macmillan

**Comment by Eallan919** [comment]
Error: https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3935157120/jobs/6730629355

Need some pairing to troubleshoot! 

@k-macmillan reviewed and still at WTB phase. 
Suggestion: break up changes and troubleshoot 1 by 1

**Comment by Eallan919** [comment]
Em to add this to rubber duck session for today

**Comment by kalbfled** [comment]
I successfully migrated the database and deployed the branch.  I need to provide server defaults for the new columns.  (Doh!)

**Comment by mjones-oddball** [comment]
Confirmed that the open api docs needs to be updated (new fields available in the body returned by the status endpoint)

**Comment by Eallan919** [comment]
waiting on second code review
@EvanParish on the case!
Dave and Cris to sync once evan is done. Dave to ping channel when ready. Em  to schedule sync

**Comment by kalbfled** [comment]
@cris-oddball The new columns I added are `segments_count` (integer) and `cost_in_millicents` (float).  The logging I added to see what AWS is sending us looks like this:
```
2023-01-20T01:35:40 delivery delivery INFO no-request-id "Processing Pinpoint result. | reference=4a131e8e-4a97-4139-b2aa-f896d7fc81f3 | event_type=_SMS.SUCCESS | record_status=DELIVERED | number_of_message_parts=1 | price_in_millicents_usd=645.0" [in /app/app/celery/process_pinpoint_receipt_tasks.py:88]
```
This line comes from [this](https://us-gov-west-1.console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/dev-notification-api-log-group/log-events/ecs$252Fnotification-celery$252Fd3212467796f4521b9ab93369add64b4$3Fstart$3D1674178540239$26refEventId$3D37335429044947961420712321086302451802568582322134319105) log file.  The code that generates it is [here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/process_pinpoint_receipt_tasks.py#L88).

**Comment by cris-oddball** [comment]
**QA PASSES**

- [ ] Happy Path with short sms and default sms sender
Yes - default sms sender should be `fccd9e82-f08f-4764-a49b-be367645d47a` | +18334981539
notification_id is `615039b5-a807-48cf-a4be-f14698746208`
Yes - sms was received, fields were populated when status was sent, fields remained populated when status was delivered

Yes - fields from notification response
```
"cost_in_millicents": 831.0,
"segments_count": 1,
"provider_reference": "ucdf09tla1dlvc1lvi3smv66ei97dbmo79mfdlg0",
```

Yes - logs
```
[2023-01-23 18:33:49,956: INFO/ForkPoolWorker-4] Processing Pinpoint result. | reference=ucdf09tla1dlvc1lvi3smv66ei97dbmo79mfdlg0 | event_type=_SMS.BUFFERED | record_status=SUCCESSFUL | number_of_message_parts=1 | price_in_millicents_usd=831.0
```
```
{
    "name": "delivery",
    "levelname": "INFO",
    "message": "Processing Pinpoint result. | reference=ucdf09tla1dlvc1lvi3smv66ei97dbmo79mfdlg0 | event_type=_SMS.SUCCESS | record_status=DELIVERED | number_of_message_parts=1 | price_in_millicents_usd=831.0",
    "pathname": "/app/app/celery/process_pinpoint_receipt_tasks.py",
    "lineno": 88,
    "time": "2023-01-23T18:33:51",
    "requestId": "no-request-id",
    "application": "delivery",
    "logType": "application"
}
```

- [ ] Happy Path with short sms and secondary sms sender
secondary sms_sender is `b6288085-824f-4ee5-864e-8f2db5d7d0c9` | 18106208437
notification_id is `4a1d400f-5c86-45be-be5b-ebdde014b3aa`
Yes - sms was received, fields were populated when status was sent, fields remained populated when status was delivered

Yes - fields from notification response
```
"cost_in_millicents": 847.0,
"segments_count": 1,
"provider_reference": "b959k2bj5b464u9pd8f1haggk97faoqjjb65duo0",
```

Yes - logs
```
{
    "name": "delivery",
    "levelname": "INFO",
    "message": "Processing Pinpoint result. | reference=b959k2bj5b464u9pd8f1haggk97faoqjjb65duo0 | event_type=_SMS.SUCCESS | record_status=DELIVERED | number_of_message_parts=1 | price_in_millicents_usd=847.0",
    "pathname": "/app/app/celery/process_pinpoint_receipt_tasks.py",
    "lineno": 88,
    "time": "2023-01-23T18:40:07",
    "requestId": "no-request-id",
    "application": "delivery",
    "logType": "application"
}
```
```
[2023-01-23 18:40:07,581: INFO/ForkPoolWorker-4] Processing Pinpoint result. | reference=b959k2bj5b464u9pd8f1haggk97faoqjjb65duo0 | event_type=_SMS.SUCCESS | record_status=DELIVERED | number_of_message_parts=1 | price_in_millicents_usd=847.0
```

- [ ] Happy Path with long sms (should be 4 segments) and default sms sender
notification_id is `3a1d492a-8dc8-4114-9d2a-42a8600e0681`
Yes - sms was received, fields were populated when status was sent, fields remained populated when status was delivered

Yes - fields from notification response
```
"cost_in_millicents": 3324.0,
"segments_count": 4,
"provider_reference": "703aifs5t7t0caa277go3tafvk5ie456jr455180",
```

Yes - logs
```
{
    "name": "delivery",
    "levelname": "INFO",
    "message": "Processing Pinpoint result. | reference=703aifs5t7t0caa277go3tafvk5ie456jr455180 | event_type=_SMS.BUFFERED | record_status=SUCCESSFUL | number_of_message_parts=4 | price_in_millicents_usd=3324.0",
    "pathname": "/app/app/celery/process_pinpoint_receipt_tasks.py",
    "lineno": 88,
    "time": "2023-01-23T18:50:30",
    "requestId": "no-request-id",
    "application": "delivery",
    "logType": "application"
}
```
```
[2023-01-23 18:50:30,750: INFO/ForkPoolWorker-4] Processing Pinpoint result. | reference=703aifs5t7t0caa277go3tafvk5ie456jr455180 | event_type=_SMS.BUFFERED | record_status=SUCCESSFUL | number_of_message_parts=4 | price_in_millicents_usd=3324.0
```

- [ ] Happy Path with long sms (should be 4 segments) and secondary sms sender
notification_id is 7c840cae-ac02-4057-86a0-fe68f065f4bd
Yes - delayed receipt to my phone but fields were populated when status was sent, fields remained populated when status was delivered (?)

Yes - fields from notification response
```
"provider_reference": "gfvsqokhmmor0tok1fjqvua3u40vcheke0jbpf00",
"cost_in_millicents": 3388.0,
"segments_count": 4,
```

Yes - logs
```
{
    "name": "delivery",
    "levelname": "INFO",
    "message": "Processing Pinpoint result. | reference=gfvsqokhmmor0tok1fjqvua3u40vcheke0jbpf00 | event_type=_SMS.SUCCESS | record_status=DELIVERED | number_of_message_parts=4 | price_in_millicents_usd=3388.0",
    "pathname": "/app/app/celery/process_pinpoint_receipt_tasks.py",
    "lineno": 88,
    "time": "2023-01-23T18:44:39",
    "requestId": "no-request-id",
    "application": "delivery",
    "logType": "application"
}
```
```
[2023-01-23 18:44:39,655: INFO/ForkPoolWorker-4] Processing Pinpoint result. | reference=gfvsqokhmmor0tok1fjqvua3u40vcheke0jbpf00 | event_type=_SMS.SUCCESS | record_status=DELIVERED | number_of_message_parts=4 | price_in_millicents_usd=3388.0
```

- [ ] Happy path with email > should return 0 for `cost_in_millicents` (float) and `total segments_count`
notification_id is 3d2494a0-d6d5-472b-ac8d-6ffc6fb9e496

Yes - fields from notification response
```
"cost_in_millicents": 0.0,
"segments_count": 0,
"provider_reference": "010a0185dffa9156-3ace9fea-5fef-4b34-9249-1146689ece3a-000000",
```

- [ ] do not test with recipient identifiers (as per melanie)
- [ ] no negative testing available
