### ISSUE TITLE
SPIKE Design options for exposing API to accept file

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#105]
The purpose of this spike would be to research and document two or three feasible design options for VANotify to accept file

- [ ] Review details and volume for the VANotify - FAS integration (VBA Comp Payment Notification) 
- [ ] Document some design options that are feasible
- [ ] Discuss and document the design recommendation within our team
 
Timebox - 3 Days

**Notes:**
- Implementation of the design will be done in a different card
- Involve multi part file uploads, stream to directly to S3 to not consume memory 
- Explore if it would be possible to validate structure of the file

**Comment by miabecker** [comment]
Relevant to DBA Comp and Pen use-case.

**Comment by miabecker** [comment]
No longer relevant.
