### ISSUE TITLE
Github build action deprecation warnings

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1051]
### User Story(ies)
**As a** developer,
**I want** not to see Github Action deprecation warnings when I deploy
**So that** our DevOps environment doesn't suddenly stop working as intended.

### Additional Info and Resources

When deploying to the development environment, I observed multiple warnings that Node.js 12 actions and the "set-output" command are deprecated.  See the summary [here](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3880232307).

## Engineering Checklist

- [ ] Node.js errors cleared
- [ ] set-output errors cleared

## Acceptance Criteria

- [ ] A deployment succeeds with no warning messages

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by ldraney** [comment]
@k-macmillan found [this comment from the aws-actions repo](https://github.com/aws-actions/configure-aws-credentials/issues/521#issuecomment-1284365838); a static version tag will be producing these errors, so I'll check through our chagnes from ticket ____  and look for other minor version tags.

**Comment by cris-oddball** [comment]
This may be a non-issue, I haven't seen these notices in a while and a screenshot would have been more helpful than a link to a now-expired workflow run. Closing - if we see more of these, we can create new tickets.
