### ISSUE TITLE
Reduce Timeout for Service Callbacks

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1054]
## Issue
Service Callbacks are 60 seconds. That means the service has 60 seconds to acknowledge the connection and another 60 seconds to send a byte (not even the whole message).

Change the timeout to the standard timeout we use: `(3.05, 1)` to allow 3.05 seconds to connect, and at most 1 second per byte. Also noticed that some exceptions may not be caught with the code that is currently there. Add catches if necessary.

## Checklist

- [ ] Timeout changed
- [ ] Generic exception catch added
- [ ] Code comments, docstrings, and annotations added (leave it better than you found it)
- [ ] Update openAPI if it mentions the timeout
- [ ] logging updated
- [ ] Talked to QA after reading the description

## Assumptions

- No functionality is changing, this is simply an adjustment to how long we are willing to wait.

## Additional Info/Resources
Code:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/769bebbf-982b-4ca5-b055-c2e06659a446)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1054?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney

**Comment by k-macmillan** [comment]
This task has been accomplished.
