### ISSUE TITLE
Update Prod and Perf CPU & Memory

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1056]
## Value Statement

CPU and Memory were updated in Perf to verify it would resolve our computational issues but it was never applied to the prod tasks. Update the Prod and Perf tasks to use 1024 CPU and 4096 memory

## Checklist
- [x] CPU changed in Prod and Perf task definitions
- [x] Memory changed in Prod and Perf task definitions

## Out of Scope

- Deploying to Prod before closing this task

**Comment by mjones-oddball** [comment]
Cris will have to QA with the deployment. Keeping tag on this as a reminder and so Cris has time to plan.

**Comment by EvanParish** [comment]
Created new ticket [1080](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1080) to address security vulnerability found in safety scan.

**Comment by Eallan919** [comment]
twistlock issues are blocking.

**Comment by Eallan919** [comment]
Cris and Evan to sync
