### ISSUE TITLE
STAGING/PERF: VA Profile Sync Certificate Update

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1061]
### 1/17/23: 
VA Profile Test team [reported ](https://dsva.slack.com/archives/C010R6AUPHT/p1673975418569299)that they stopped receiving the PUT request back from VA Notify after the preference update is successfully sent to VA Notify.

Kyle spoke with John, giang.nguyen1@va.gov, who has been managing certificate updates and received new certificates via email specifically for the status that we send back to VA Profile after we've done something with the permission info.

## The Solution

The problem is that the lambda execution environment no longer has the necessary VA CA certificates to verify Profile's server's certificate.  The lambda function code needs an update to use the new lambda layer created as part of [vanotify-infra#497](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/497).

- [x] Deploy changes for [vanotify-infra#497](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/497)
- [ ] Modify the lambda function to use the new infra changes
- [ ] Manually test the changes in AWS Lambda console
- [ ] Do a pre-release to get the updates into perf and staging
- [ ] Validate that the PUT connection is working again in perf
- [ ] Validate that the PUT connection is working again in staging

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1061?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @kalbfled @ldraney

**Comment by mjones-oddball** [comment]
@k-macmillan I brought this up at refinement and @kalbfled has some concerns with the certificate update plan. He thought the method you described would only fix the post, not the put. We need to sync when you're better/available to work through what is needed, estimate, and schedule the change.

**Comment by Eallan919** [comment]
VA Profile rolled their cert change back because their tests failing delayed their deployment. They are pushing us to provide an ETA on when we can fix and update Staging. Dave mentioned yesterday the change may be more complex than updating files because the root cert changed.

**Comment by mjones-oddball** [comment]
@kalbfled when you are done and this is in staging please update the request portion of the description with the work done.

**Comment by Eallan919** [comment]
Pushed to staging and perf. Still need code reviews but we gucci!
