### ISSUE TITLE
Upgrade SQLAlchemy to v2

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1068]
## User Story
As a VA Notify Engineer
I want to upgrade SQLAlchemy to the latest version
So that I can maintain a modern platform and receive the latest functionality and security patches

- [ ] discuss ticket with QA when work is understood

## Additional Info
We are using SQLAlchemy <2.0.  SQLAlchemy v2.0.0 was release on 1/26, and we should upgrade.

## Checklist

- [ ] In requirements-app.txt, upgrade SQLAlchemy to `SQLAlchemy~=2.0.0` (or newer, if available)
- [ ] In Makefile, remove the exception (-i flag) from the "safety check" command
- [ ] Fix all emergent build, runtime, and unit test errors
- [ ] Update requirement.txt using the procedure in README.md

## Acceptance Criteria
- [ ] SQLAlchemy is upgraded to the latest version 2.x
- [ ] unit tests pass
- [ ] If necessary, tickets are created for additional work discovered during the course of this upgrade.

## QA Considerations
- [ ] some dependency on convo with developer when work begins
- [ ] regression and JSON models in particular must pass

**Comment by Eallan919** [comment]
We discussed during our Celery and Flask update that we would like to eventually upgrade to Alchemy 2.0 but since it is SOOOO new right now, we want to wait until all the kinks are sorted out. Looking to tackle this MAYBE Q2!

**Comment by mjones-oddball** [comment]
@kalbfled Is there something you can link to regarding the known vulnerability?

**Comment by mjones-oddball** [comment]
@cris-oddball @k-macmillan for your review

**Comment by cris-oddball** [comment]
@kalbfled This ticket will require some degree of validation, the AC "SQLAlchemy is upgraded to the latest version 2.x" is not really sufficient. I would image we would want to ensure that all API routes we care about return a proper JSON response and the expected properties? Can you flesh that AC out a little more?

**Comment by mjones-oddball** [comment]
@kalbfled Please see the last comment and update the ticket CC @tabinda-syed

**Comment by cris-oddball** [comment]
@mjones-oddball 1225 duplicates this one

**Comment by cris-oddball** [comment]
I'm closing this as a duplicate in favor of the newer #1225 which has already been refined.
