### ISSUE TITLE
Update Incoming SMS Lambda to pull authentication requirements from db

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1070]
Right now, the incoming sms lambda (the lambda that looks up a number in inbound_numbers and sends an incoming SMS to that URL) uses basic authentication with VeText's token.  We need to update this so that the type of authentication and also the token itself are both pulled dynamically from the db.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1070?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney

**Comment by mjones-oddball** [comment]
Engineering is going to discuss at the next process improvement meeting and determine if a spike is needed or come to a conclusion and update this ticket.

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1070?planning-poker) with Zenhub @justaskdavidb2

**Comment by tabinda-syed** [comment]
Blocker Internal:  Per Jacob, the other tickets dealing with Incoming SMS will need to be addressed before we can pick up this ticket.

**Comment by k-macmillan** [comment]
Keeping, needs clarity.

**Comment by npmartin-oddball** [comment]
Closing for now. Will address when working with enp-api.
