### ISSUE TITLE
Configure Rx Shipment and BVA Hearing for PRODUCTION Incoming SMS Webhook

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1072]
VeText has two use cases that are ready to have their inbound messages forwarded from pinpoint to the designated VeText endpoint.  

**PRODUCTION**
- [x] Use Postman to Create (or Update if the numbers exist) Inbound Number record for VeText service for 53941 and +12029517856
```
{
    "number": "53941",
    "provider": "pinpoint",
    "self_managed": false, 
    "service_id": "a57c326a-2c37-4cdf-a2b7-a261bd5909b1",
    "url_endpoint": "https://alb.sms.vetext.va.gov/api/vetext/pub/inbound-message/aws"
}

{
    "number": "+12029517856",
    "provider": "pinpoint",
    "self_managed": false, 
    "service_id": "a57c326a-2c37-4cdf-a2b7-a261bd5909b1",
    "url_endpoint": "https://alb.sms.vetext.va.gov/api/vetext/pub/inbound-message/aws"
}
```
- [x] Update Pinpoint record for 53941 and +12029517856 to use SNS topic: prod-notify-incoming-sms
- [x] Confirm with Rob Durkin that he is seeing traffic come through in production as expected for these 2 numbers

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1072?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney

**Comment by mjones-oddball** [comment]
Updated URL based on Rob's response: https://alb.api.vetext.va.gov/api/vetext/pub/inbound-message/aws

Jacob messaged Rob asking for him to validate post-change here:https://dsva.slack.com/archives/G01F8045K88/p1675445466377159?thread_ts=1675103118.230739&cid=G01F8045K88

**Comment by mjones-oddball** [comment]
Rob reported that he was not seeing inbound messages come through, though Jacob saw a 200 at the alb, so I reverted these to use the old SNS topic pending investigation.

**Comment by mjones-oddball** [comment]
Increasing from a 1 to a 3 pt ticket because this is rolling over to a new sprint and there has been back and forth with Rob to get this working

**Comment by mjones-oddball** [comment]
@jakehova can you please add some updates here

**Comment by jakehova** [comment]
Confirmed this with Rob this morning: https://dsva.slack.com/archives/G01F8045K88/p1675786061052309?thread_ts=1675103118.230739&cid=G01F8045K88

We have now confirmed it working for both numbers.
