### ISSUE TITLE
[Twilio]SMS Delivery Status API Integration - Lambda Task

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1074]
## Issue
We need to take in delivery status updates from various providers (pinpoint, twilio, cisco, etc.). This lambda will be the first processing of one of those incoming messages. 

Prior work detailed the [delivery status path](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Delivery-Status.md) that shows what needs to be done when a delivery status is received.

We want to simplify the architecture by eliminating provider-specific infrastructure.  Infrastructure will be built to handle two paths:
- Internal (pinpoint)
- External (twilio, cisco, etc.)

This ticket implements the code for the infrastructure created in ticket [519](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/519) and will identify the path (internal/external) and then validate the provider's schema. Unknown schema from the ALB will be rejected. With a 4xx schema not recognized. 

The code should expect ALB or SNS but this ticket will only focus on handling the ALB related code, and specifically, the twilio provider. This scopes the work and will finish Twilio integration quicker.

## Checklist/Acceptance Criteria
- [x] Code for Lambda {env}-delivery-status-processor
  - [x] determine source of delivery status (twilio, ~pinpoint, cisco~)
  - [x] Ensure this is part of the enqueued object
  - [x] enqueue to celery queue mentioned above
    - [x] On failure to enqueue, move to deadletter
    - [x] On schema validation, move to deadletter
  - [x] Use "delivery-status-result-tasks" as the queue name
- [x] Include the entire payload from the provider
- [x] Plan to handle response expected from ALB or SNS depending on where it came from
  - [x] Handle ALB responses only for this ticket

## QA
Test using the AWS Lambda test console. Save these tests for re-usability.
~~- [ ] Objects from SNS (good, bad, etc.)~~
~~- [ ] Good json object~~
~~- [ ] Bad json object[s]~~
- [x] Objects from ALB
  - [x] Good json object (from each provider)
  - [x] Bad json object[s]
- [x] Ensure enqueue to queue listed above
- [x] Ensure enqueue to dead letter queue

## Acceptance Criteria
- [x] Can send request to ALB endpoint
- [x] Request from ~~pinpoint and~~ twilio gets to Routing Lambda
- [x] Request from Routing Lambda to Delivery Status SQS (celery queue)
- [x] Celery Task gets created properly with proper information (encoded twilio delivery status object and celery task name of process-delivery-status-result)

**Comment by mjones-oddball** [comment]
@jakehova Can you let me know when the description is updated to account for logic related to https://github.com/department-of-veterans-affairs/notification-api/issues/1076

**Comment by mjones-oddball** [comment]
Removed points on this ticket - previously a 5, as we are revising the work.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1074?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney

**Comment by Eallan919** [comment]
@cris-oddball @k-macmillan @jakehova perhaps a sync might help- sprint planning is tomorrow

**Comment by k-macmillan** [comment]
Updated with clearer instructions. @cris-oddball  please adjust the QA section as you see fit.

**Comment by cris-oddball** [comment]
@k-macmillan excellent update - makes it really clear. I didn't have to add much, ty.

**Comment by jakehova** [comment]
[Draft PR](https://github.com/department-of-veterans-affairs/notification-api/pull/1113) has been created.  I am writing unit tests for it now and hope to have those done today so that we can test the whole thing through on Friday.

**Comment by jakehova** [comment]
This code has been deployed in dev along with unit tests.  Kyle, Baldwin, and I tested it on Friday and saw messages go through the complete process.  It is currently in PR status. awaiting approval.  

Baldwin and I will meet with Cris to go over QA today (3/6) to get this moved along.

**Comment by cris-oddball** [comment]
@jakehova Please check off the boxes in the description under QA and Acceptance Criteria when you validate this ticket.

**Comment by jakehova** [comment]
Due to the high priority nature of the Twilio changes, the SNS code is not being tested in this release.  This ticket only focuses on Twilio from the ALB.
