### ISSUE TITLE
Hotfix: Update Notify-Incoming-SMS-Lambda to be generic with authorization header

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1075]
The lambda currently includes the VeText Basic Auth Token in the authorization header.  This was a quick fix that was included to get two way working with vetext.  

The hotfix for this is to check the service_id that is returned from the query before including the authorization header.  If it's the VeText service id, then include the basic auth header (as the code is today), otherwise remove the authorization header from the request.

**Comment by k-macmillan** [comment]
No longer relevant.
