### ISSUE TITLE
Twilio SMS Delivery Status - Add DB Column: include_provider_payload (boolean) to Callbacks  

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1076]
As VA Notify
I want to manage this new callback feature per client
So that we are flexible to our clients' needs and system requirements

Callbacks define the process of sending a HTTP request to webhook to a business line when a delivery status is received by the Notify platform.  

Currently, the body of that HTTP request is a general notification object.  

We providing an option to include the provider's original delivery status object in the callback request.    

To do this, the db needs a new column that indicates whether or not to include that original delivery status object.  

- [x] Add new boolean column 'include_provider_payload ' to service_callback table that has a default "false" value. 
- [x] Update the callback endpoint  so we can update this field at time of creation or update, the POST `{{notification-api-url}}/service/{{service-id}}/callback` payload contains the property `include_provider_payload` with a boolean value, default is `false`.
- [x] Update the callback GET `{{notification-api-url}}/service/{{service-id}}/callback` response such that it has the property `include_provider_payload`
- [x] Update openAPI docs: https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml
- [x] Unit tests?
- [ ] QA

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1076?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney

**Comment by mjones-oddball** [comment]
@k-macmillan @jakehova I think this ticket is missing checkboxes related to updating the callback endpoint for the new field and API docs right?

**Comment by mjones-oddball** [comment]
Maybe this needs to be pointed higher?

**Comment by cris-oddball** [comment]
> @k-macmillan @jakehova I think this ticket is missing checkboxes related to updating the callback endpoint for the new field, API docs, and updating callback setup documentation right? CC @cris-oddball

I thought we were breaking that work out into another ticket and that this ticket is just adding a column to the DB with default value of false and then looking at the DB to see that this was done? @mjones-oddball

**Comment by mjones-oddball** [comment]
Conclusion from thread in [slack](https://oddball.slack.com/archives/C034496E4AU/p1675803261871589). We should add technical requirements here to address updating our callback endpoint to manage this new field. 

"Okay, I briefly looked at the endpoint. I think it could be updated within this ticket and it'd add a day at most. Unit tests need updated, schema needs updated."

**Comment by mjones-oddball** [comment]
@EvanParish It looks like the description didn't get updated based on our latest discussion so I tried to add some content - apologies for the surprise change! Since this is a new field in the callback object we need to update our endpoint for callbacks to be able to set/update this value. If you have any questions please touch base with @jakehova or @k-macmillan to confirm technical requirements.
CC @tabinda-syed

**Comment by Eallan919** [comment]
Evan to share error in engineering channel so team can address

**Comment by EvanParish** [comment]
The team pointed out a couple things wrong with my migration and I managed to get everything working locally. The next step is testing in the Dev environment to make sure it's working properly. 

A fun little piece of info we learned yesterday is that the migration name cannot be more than 32 characters long. (mine was 33...)

I have also reached out to @cris-oddball and @k-macmillan about testing this change. Kyle pointed out this list of things that should be checked with this change.
- `include_provider_payload` = False on an existing service
- `include_provider_payload` Can be set to true \ false through the API
- Docs look good for the endpoint

**Comment by tabinda-syed** [comment]
Evan is almost done with the changes. PR out.

**Comment by cris-oddball** [comment]
QA IN PROGRESS

- [ ] POST `{{notification-api-url}}/service/{{service-id}}/callback` payload contains the property `include_provider_payload` with a boolean value, default is false.
NOTE: there are a few variants of the payload body. The one tested was for DeliveryStatus
- [ ] GET `{{notification-api-url}}/service/{{service-id}}/callback` returns that callback with the property `include_provider_payload` set to False
- [ ] POST `{{notification-api-url}}/service/{{service-id}}/callback` payload updating `include_provider_payload` to True results in that value being set to True
- [ ] GET `{{notification-api-url}}/service/{{service-id}}/callback` returns that callback with the property `include_provider_payload` set to True
- [ ] POST `{{notification-api-url}}/service/{{service-id}}/callback` payload contains the property `include_provider_payload` set to True
- [ ] GET `{{notification-api-url}}/service/{{service-id}}/callback` returns that callback with the property `include_provider_payload` set to True
- [ ] Swagger is updated to reflect the new property

**Comment by cris-oddball** [comment]
Closing this ticket with some thoughts... @mjones-oddball @k-macmillan @EvanParish :

1. When trying to add a second callback with the property `"callback_channel": "webhook",` I received a 500 Internal Server error
```
{
    "message": "Internal server error",
    "result": "error"
}
```
Evan says this is because we can only have one type of callback_channel per service (webhook or queue).  Can we spin up a small ticket that will return a better response with an appropriate error message?

2. Longer term, I feel like this route is overloaded.  Swagger shows two different possible payloads for this route, one which that has a required property that the other doesn't. Philosophically, this should be two routes. Either that or swagger is written incorrectly. Perhaps we could discuss refactoring this to make separation of concerns more clear.

**Comment by EvanParish** [comment]
@cris-oddball Just a quick clarification on this. I believe a service can have one callback of each channel type (webhook or queue), so a service can have two callbacks total.
