### ISSUE TITLE
Vulnerability: PYPDF2 version update

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1080]
# Description
Our safety check caught a vulnerability for the package pypdf2

# Checklist
- [x] update the pypdf2 version to `>=2.10.6`
- [x] remove the vulnerability being ignored in the `Makefile`

# Additional Info
Vulnerability printout
```
-> Vulnerability found in pypdf2 version 1.28.6
   Vulnerability ID: 52548
   Affected spec: <2.10.6
   ADVISORY: Pypdf2 2.10.6 fixes a potential DoS
   vulnerability.https://github.com/py-pdf/pypdf/pull/1331
   PVE-2022-52548
   For more information, please visit https://pyup.io/v/52548/f17
```

**Comment by kalbfled** [comment]
Routine upgrades addressed this.  `PyPDF2==3.0.1` is the current specification in requirements.txt.
