### ISSUE TITLE
API - Remove User Flows for Perf in 'Deploy to Dev 'action

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1082]
## Value Statement

**As** a VANotify engineer
**I want to** be able to use `Deploy to Dev` to push code into Perf, under special circumstance and with permission
**So that** I can deploy code without experiencing User Flows errors into Perf

## Description
`Deploy to Dev ` should be configured to not run User Flows if the environment to deploy to is the Perf environment. It presently does not run User Flows in staging or prod.

Currently, the GitHub `Deploy to Dev` action can be used to push code into perf, staging or prod. The usual flow for this it to cut a tag to send code to perf, publish a pre-release to send it to staging, publish a release to send it to prod. 

On special occasions, it may be necessary to deploy code outside of these parameters using `Deploy to Dev` and with permission. However, that action runs User Flows when deploying to the Perf environment. 

The Perf environment does not have a service that User Flows looks for in `notification-api/lambda_functions/user_flows/test_retrieve_everything.py` line 55:
```
if service['name'] == "User Flows Test Service":
```
Unable to find such a service, the tests will fail in a cascade since the tests all use that service in the API calls.

Also, there is a permission error raised (sensitive data snipped)
```
E           botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the GetParameter operation: User: <snipped> is not authorized to perform: ssm:GetParameter on resource: <snipped> because no identity-based policy allows the ssm:GetParameter action
botocore/client.py:960: ClientError
====================== 1 passed, 9 error in 14.72 seconds ======================
END RequestId: 63216740-252c-4af5-9e9e-e49b1432b414
REPORT RequestId: 63216740-252c-4af5-9e9e-e49b1432b414	Duration: 17103.20 ms	Billed Duration: 17104 ms	Memory Size: 128 MB	Max Memory Used: 93 MB	Init Duration: 271.90 ms	
User Flows Tests Exit Code: 1
Error: Process completed with exit code 1.
```

Last, User Flows is slated to be replaced with the new QA Automation suite, so fixing it is not advised, especially since the standard means to deploy to Perf does not use User Flows.

The code for this is in  `notification-api/.github/workflows/dev_deploy.yml `, starting line 78. Change line 80 from
```
 if: ${{ inputs.environment }} == "dev" || ${{ inputs.environment }} == "perf"
```
to
```
if: ${{ inputs.environment }} == "dev"
```

More code for this is in  `notification-api/.github/workflows/user_flows.yml `, starting line 9. Change line 12 from 
```
if: ${{ inputs.environment }} == "dev" || ${{ inputs.environment }} == "perf"
```
to 
```
if: ${{ inputs.environment }} == "dev"
```

## Acceptance Criteria

**GIVEN** I want to deploy to perf under special circumstances
**WHEN** I deploy the code using the `Deploy to Dev` action
**THEN** It does not run User Flows in perf

## Checklist

-   [x] Update `dev_deploy.yml `
-   [x] Update `user_flows.yml `
-   [x] Test Deploy to Dev push to perf, validate that User Flows does not run
-   [x] QA

## Assumptions
User Flows will be shortly replaced shortly with the QA Automation suite so should not be 'fixed', especially given the level of effort needed to create a configure a service in Perf that User Flows is looking for, with sms and email senders, sms and email templates, a User ID, etc.

## Cross Functional Checklist

Documentation:

-   [ ] Update `vanotify-team` documentation

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1082?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1082?planning-poker) with Zenhub @justaskdavidb2

**Comment by tabinda-syed** [comment]
@k-macmillan Reminder to discuss a "Deploy to Perf" process improvement during the Eng team meeting - an offshoot conversation from this ticket.

cc. @mjones-oddball @cris-oddball

**Comment by cris-oddball** [comment]
@mjones-oddball that works for me, sorry for the delay in responding.

**Comment by ldraney** [comment]
So, [if statements in github actions have been having issues defaulting to true for three years now](https://github.com/actions/runner/issues/1173).  There are workarounds, but as a disclaimer the actions are clearly not working as they should.
