### ISSUE TITLE
QA: Validate VA Profile Opt-in/Opt-out Lambda

### ISSUE THREAD

**Issue by tabinda-syed** [department-of-veterans-affairs/notification-api#1086]
VAProfile updated their certificate last week. We had to deploy utils and the lambda layer to PROD. Validated that this works in non-production environment but there now seems to be an issue.

- [x] Validate Prod POST route with QA URL parameter `?integration_test`, which uses the QA private/public key pair. `https://api.notifications.va.gov/vaprofile/optinout?integration_test=true` and generated bearer token.

**Comment by tabinda-syed** [comment]
We'll create a new ticket to document next steps (i.e., new effort scope) if the test fails.

**Comment by cris-oddball** [comment]
**QA PASSES**

Steps:
- [ ] Obtain a known good bearer token using Dave's script
- [ ]Start dev-bastion-host EC2 instance
- [ ] Log into instance via AWS Console Session Manager (needed to restart the bastion host twice to get a prompt, known issue)
- [ ] To make sure we can access the route, issue a POST request without an Auth header. 

```
curl -H "Accept: application/json" -H "Content-type: application/json" -H "Accept-Encoding: gzip,deflate" -H "Accept: text/plain, application/json, application/*+json, */*" -X POST -d '{"txAuditId": "c091cfdf-5744-4a7e-b482-ee614d7dde61","bios": [{"createDate":"2022-08-03T18:11:36Z","updateDate": "2022-10-20T02:00:12Z","txAuditId": "c091cfdf-5744-4a7e-b482-ee614d7dde61","sourceDate":"2022-10-25T02:00:12Z","vaProfileId":7105,"communicationChannelId":1,"communicationItemId": 5,"allowed": false}]}' https://api.notifications.va.gov/vaprofile/optinout?integration_test=true -w "\n" -v
```

Able to access route from bastion host; received 401
```
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
* We are completely uploaded and fine
< HTTP/2 401
< server: awselb/2.0
< date: Mon, 13 Feb 2023 17:30:03 GMT
< content-type: application/octet-stream
< content-length: 0
```

- [ ] HAPPY PATH Request body "bios" attribute is a list of one element, and everything should be valid. Should receive --> POST response 200; PUT request COMPLETED_SUCCESS. PUT response 200.
Payload with sensitive data removed
```
curl -H "Authorization: Bearer <snipped>" -H "Accept: application/json" -H "Content-type: application/json" -H "Accept-Encoding: gzip,deflate" -H "Accept: text/plain, application/json, application/*+json, */*" -X POST -d '{"txAuditId": "c091cfdf-5744-4a7e-b482-ee614d7dde61","bios": [{"createDate":"2022-08-03T18:11:36Z","updateDate": "2022-10-20T02:00:12Z","txAuditId": "c091cfdf-5744-4a7e-b482-ee614d7dde61","sourceDate":"2022-10-29T02:00:12Z","vaProfileId":7105,"communicationChannelId":1,"communicationItemId": 5,"allowed": false}]}' https://api.notifications.va.gov/vaprofile/optinout?integration_test=true&my_id=20 -w "\n" 
```

Received 200 response
```
{"put_body": {"dateTime": "2022-10-29T02:00:12Z", "status": "COMPLETED_SUCCESS"}}
```
