### ISSUE TITLE
Delivery Status Processing

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1092]
There is a common process flow detailed in the [delivery status spike](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Delivery-Status.md) that shows what needs to get done when a delivery status is received.  

We want to simplify the architecture by eliminating provider specific infrastructure as much as possible.  This ticket implements the code for the infrastructure created in ticket [519](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/519).  

* Code for Lambda {env}-delivery-status-processor
	* determine source of delivery status (twilio, pinpoint, cisco)
	* generate "CELERY TASK OBJECT" mentioned above using source delivery status object and provider (twilio, pinpoint, cisco)
	* generate celery task 
	* enqueue celery task 
	* move original message to dead letter queue if anything fails
	* Use "process-delivery-status-result" as task attribute name

# Moved to other tickets
* Update ECS code
	* Create method in "process-pinpoint-receipt-tasks.py" that is decorated with:
	```
	@notify_celery.task(bind=True, name="process-delivery-status-result", max_retries=5, default_retry_delay=300)
	```
	* Copy code in "process-pinpoint-result" task method to this new method	
	* Update Twilio Client with methods for:
	  * Validating a delivery status schema 
	  * Converting a twilio delivery status to notification platform status
	* Update "get_notification_status" method to accept a provider and error code
	* Make get_notification_status return a Notify Platform status based on a decision tree that considers provider in how to handle the record_status

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1092?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney

**Comment by tabinda-syed** [comment]
@jakehova Please consider revising the bullet points to a checklist. Also, are there any acceptance criteria or QA considerations that we may be able to go ahead and add? 

Lastly, just a minor note, consider renaming the "Moved to other tickets" section to "Out of scope" (thank you for calling those out so clearly, btw!) and then indicate in the body that those have moved to other tickets.

**Comment by tabinda-syed** [comment]
Closing this ticket based on the following notes from Kyle:

- 1092 (this ticket) was broken apart into 1073, 1074, 1095. It can be closed.
- 1074 is what 1092 (this ticket) had in the upper section.

FYI @mjones-oddball
