### ISSUE TITLE
Delivery Status - Celery SQS Addition

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1096]
## User Story
As a client sending notifications to Veterans
I want to receive status updates on my notifications
So that I can consistently monitor notification successes and failures

## Issue
We need celery to setup an SQS queue to handle incoming delivery statuses. 

- Queue name: `delivery-status-result-tasks`
- Task name: `process-delivery-status-result`

The queue needs to be added to the `QueueNames` class as a class member. It also needs to be added to the return from `all_queues()` so it can be setup using `CELERY_SETTINGS` (handled automagically as long as it's in the `all_queues()` return). Lastly, it needs to have the file added to the import section of `CELERY_SETTINGS`.

If the file does not already exist that will handle this, create it: `app/celery/process_delivery_status_result_tasks.py`
Inside, create one method with the decorator and method:

```python

@notify_celery.task(bind=True, name="process-delivery-status-result", max_retries=48, default_retry_delay=300)
def process_delivery_status(self, event: CeleryEvent) -> bool:
    logger.info('processing delivery status: %s', event)
    return True
```

## Acceptance Criteria

- [x] The queue is made when deploying to dev
- [x] The queue triggers the ECS code (visible output in cloudwatch logs)
- [x] Provide QA a JSON body to test
- [x] QA (to be filled in by QA)
  - [x] Kyle tested in AWS since we had no access, sent base64 encoded message directly into the queue

## Additional Info/Resources
A little information on some of the [Celery Magic](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Delivery-Status.md#celery-magic) that happens.

`QueueNames`
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/66ea5591-f92e-4060-a7ca-9bf899f1b15a)

Celery Settings imports
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/df94ba64-72ce-4676-80e3-8f362eae039c)

- When attempting to build a test JSON for testing, use [this as an example](https://github.com/department-of-veterans-affairs/notification-api/blob/master/lambda_functions/pinpoint_callback/pinpoint_callback_lambda.py#L16).

**Comment by mjones-oddball** [comment]
@k-macmillan I added a user story and the applicable epic. PM reviewed and I see @cris-oddball reviewed as well, so I added the sprint to the ticket per your request. FYI @tabinda-syed

**Comment by cris-oddball** [comment]
example of dev queue:![Screen Shot 2023-02-24 at 2.56.36 PM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/7b731862-3844-439e-a62b-ed1c576af34e)

**Comment by cris-oddball** [comment]
@k-macmillan the AC asks for:

- The queue triggers the ECS code (visible output in cloudwatch logs)
- Provide QA a JSON body to test

But what lambda is triggered by this queue? Where would we pass the JSON body?

**Comment by tabinda-syed** [comment]
Please also test in Perf.

**Comment by tabinda-syed** [comment]
Currently blocked by AWS access issue :(

**Comment by cris-oddball** [comment]
![image (5).png](https://images.zenhubusercontent.com/630696b479f5cca51e546872/a077cab6-8cac-4285-b1b2-b14d9fe84cfb)

Deployed to Perf, send the base 64 encoded message through the queue, the above log was displayed in CloudWatch - good job!
