### ISSUE TITLE
endpoint to create an invite has an unused parameter

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1103]
### User Story(ies)
**As a** developer,
**I want** functions only to take parameters they use
**So that** I don't code like a noob.

### Additional Info and Resources

app/invite/rest.py::create_invited_user, for the route /service/<service_id>/invite, does not actually use the service_id.  The preceding TODO states, `TODO - This function takes a "service_id" because it's part of the associated URL, but "service_id" is not used.  This probably indicates that the URL should be different.`.

The existing implementation creates an invite using a service given as part of the app configuration.

If feasible, the route to create an invite, irrespective of any particular service, should be "(POST) /invite".  We could make it "/v2/invite" if the existing route cannot be deleted.

## Engineering Checklist

- [ ] create_invited_user no longer takes "service_id" as a parameter

## Acceptance Criteria
_**Required**_
- e.g. when I send an email using an identifier, we retrieve the user’s email address in VA Profile and successfully deliver the email to that recipient

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by k-macmillan** [comment]
No longer relevant.
