### ISSUE TITLE
TODOs in pytest.ini 

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1104]
**Describe the bug**

pytest.ini has two TODOs related to parameters not found in associated documentation.  Are these values being used?  Does SQLALCHEMY_DATABASE_URI belong in this file?  (It's commented-out.)

We should determine if these values are being used.  Is the file being used for anything useful?

**Expected behavior**

Update the documentation links if the parameters are valid, or delete them.  Also consider deleting the file.

**Comment by cris-oddball** [comment]
This code was removed as part of the work done on #1665 for Poetry. Closing ticket.
