### ISSUE TITLE
Twistlock - Action to Restart

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1108]
## Value Statement

**As** an engineer on VA Notify
**I want** an easy way to restart twistlock  
**So that** restarting it doesn't require logging into the console

## Acceptance Criteria

**GIVEN** Twistlock fails with a 
```
----------ERROR-------
failed to run commands: exit status 1"
```
**THEN** The engineer can easily restart and rerun twistlock to be sure it's not a server issue

## Checklist

-   [ ] create an dispatch action that runs an aws cli command to restart the twistlock ec2
-   [ ] update documentation surrounding twistlock failures and procedure

## Documentation:

-   [ ] Readmes
-   [ ] Project specific
-   [ ] Support
-   [ ] Openapi
-   [ ] ADR
-   [ ] Tech Debt wall

**Comment by mjones-oddball** [comment]
@ldraney can you update the documentation section, it looks like it's from an old template since we don't really do ADRs or Tech Debt wall.

**Comment by cris-oddball** [comment]
We haven't seen this issue since we upgraded that EC2. Closing ticket.
