### ISSUE TITLE
Twistlock - Remove unnecessary snippet

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1109]
## Value Statement

**As** A DevOps Engineer
**I want to** remove irrelevant code
**So that** code is less bloated and easier to read

This was left dangling unintentionally with the change to how Twistlock is ran within our system. We previously required the ref, but now we are passing along the ECR tag via `inputs.image-tag`.

## Checklist

-   [x] remove this snippet from twistlock.yml:
```
         - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
```
- [ ] validate twistlock still works as expected with this removed

## Assumptions

- there's no need to checkout the repo for this action, this action will work regardless

## Additional Information
- Code [location](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/twistlock.yml#L14)

**Comment by mjones-oddball** [comment]
@k-macmillan @cris-oddball for your review

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1109?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by ldraney** [comment]
This snippet is actually necessary.  Without it the workflow fails with:
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/notification-api/notification-api/.github/actions/run-commands-on-ec2'. Did you forget to run actions/checkout before running your local action?
```
 As you can see in [this failed action](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/5321775119), the checkout step grabs this file from our repo, which is then used in the workflow. 

re-adding the snippet and [the workflow now runs sucessfully](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/5321798973).
