### ISSUE TITLE
BUG: Vetext-Incoming-Forwarder-Lambda response triggers error in Twilio

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1111]
**Describe the bug**
The Vetext-Incoming-Forwarder-Lambda works as expected but when it returns a response to Twilio, it returns an object that Twilio considers an error.  

**To Reproduce**
1. Send an inbound SMS to Vetext-Incoming-Forwarder-Lambda endpoint
2. Look at Twilio error logs for the SMS number used to send the message
3. Verify error exists

**Expected behavior**
A success response should be logged in Twilio when processing is successful.  An error response should be logged in Twilio when processing fails.

**Additional context**
The fix for this issue is to update the "[create_twilio_response](https://github.com/department-of-veterans-affairs/notification-api/blob/master/lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py#L64)" method so that the response only contains the "statusCode" key in the response. 

```
def create_twilio_response(status_code: int = 200):
    response = {
        "statusCode": status_code
    }

    return response
```

This change will require changing the associated test suite.  Namely: 
* Remove body assert in **test_request_makes_vetext_call(mocker, all_path_env_param_set, event)** method
* Remove body assert in **test_failed_alb_invocation_call_throws_general_exception_goes_to_dead_letter_sqs** method
* Remove body assert in **test_unexpected_event_received** method

**Comment by mjones-oddball** [comment]
@jakehova do you have a copy of the error message you could add to this ticket?
@cris-oddball @k-macmillan for your review

**Comment by cris-oddball** [comment]
@jakehova please fill in a section for AC, both positive and negative testing. The Expected Behavior is not really sufficient.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1111?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by jakehova** [comment]
I believe this ticket is also related to this issue: https://github.com/department-of-veterans-affairs/notification-api/issues/939

**Comment by jakehova** [comment]
created draft PR with the change: https://github.com/department-of-veterans-affairs/notification-api/pull/1117

I believe this fix may also resolve #939 .  I will confirm during my testing.

**Comment by jakehova** [comment]
I have confirmed that this change resolves the 502 and does not log any errors in twilio.  HOWEVER, it does log a warning for invalid content-type.  I'm going to update the content type to be application/json to see if it resolves the warning as well.

**Comment by jakehova** [comment]
Had to update the response object to follow the [schema provided by Twilio's docs](https://www.twilio.com/docs/voice/twiml#status-callbacks-in-your-response) .  

I updated the response object to match and now there are no errors or warnings.

**Comment by jakehova** [comment]
code scan/dependency scan/unit tests are failing due to something that changed in the repo.  The results of those steps point to files that were not touched in my branch.  I'm not sure any PR will pass testing unless we go through all the results and resolve the issues brought up in the scans.

**Comment by mjones-oddball** [comment]
After the above issue is resolved... @jakehova or @k-macmillan whomever tests this can you please validate that the error is no longer thrown in VEText's twilio account and a screenshot is provided here for confirmation? @cris-oddball if you want to peek over Jacob/Kyle's shoulder while they are in there please coordinate with them. I'll ask VEText if they can add you to the account for future validation.

**Comment by mjones-oddball** [comment]
Asked Paras to add @cris-oddball to the test and enterprise Twilio accounts. Cris, keep an eye on your email and spam folder today/tomorrow. If you don't see anything by then let me know.

**Comment by k-macmillan** [comment]
Reviewed the code associated with my comment on the PR. No changes were necessary. Merged master into the branch and requested review.

**Comment by cris-oddball** [comment]
Code deployed to Perf.

- changed twilio number for +19703005680 to use the Perf webhook at https://sandbox-api.va.gov/vanotify/twoway/vettext
- had to update ALB to accept either public or private IF path is perf-api.va.gov OR sandbox-api.va.gov PTH is twoway/vetext THEN forward to perf-vetext-incoming-tg 1
- twilio logs only showing errors for all the bad tests we sent.
- cloudwatch logs indicate message received and processed, but throw an error, see below

Why are we throwing a cert error and why is it reporting the staging endpoint?
```
START RequestId: 8a8c88d2-c393-4201-bc0c-173688e7c988 Version: $LATEST

[INFO]   2023-03-16T15:01:54.712Z          8a8c88d2-c393-4201-bc0c-173688e7c988   alb invocation

[INFO]   2023-03-16T15:01:54.712Z          8a8c88d2-c393-4201-bc0c-173688e7c988   Successfully processed event to event_bodies

[INFO]   2023-03-16T15:01:54.713Z          8a8c88d2-c393-4201-bc0c-173688e7c988   Retrieved AuthToken from SSM

[INFO]   2023-03-16T15:01:54.713Z          8a8c88d2-c393-4201-bc0c-173688e7c988   Making POST Request to VeText using: https://staging.api.vetext.va.gov/api/vetext/pub/inbound-message/twilio

/opt/python/lib/python3.8/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'staging.api.vetext.va.gov'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings

warnings.warn(

[INFO]   2023-03-16T15:01:55.025Z          8a8c88d2-c393-4201-bc0c-173688e7c988   VeText POST complete

[INFO]   2023-03-16T15:01:55.026Z          8a8c88d2-c393-4201-bc0c-173688e7c988   VeText call complete with response: 200

END RequestId: 8a8c88d2-c393-4201-bc0c-173688e7c988

REPORT RequestId: 8a8c88d2-c393-4201-bc0c-173688e7c988     Duration: 352.05 ms          Billed Duration: 353 ms Memory Size: 128 MB    Max Memory Used: 70 MB   
```

**Comment by cris-oddball** [comment]
**QA PASSES**
