### ISSUE TITLE
BUG: No create route for provider-details

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1115]
**Describe the bug**
route: /provider-details/:provider-detail-id
There currently exists a GET route, an update POST route and a DEL route for provider-detail - there is no Create route
This means that the DEL route cannot effectively be tested, except to manually add a provider directly in the database, which is not recommended.

A create POST route should exist

**Expected behavior**
I should be able to create and then delete a provider-detail using the API.

**Acceptance Criteria**

- [ ] An API POST /provider-details/ exists
- [ ] The Postman collection is updated
- [ ] The Swagger doc is updated
- [ ] Exercising the POST route results in a 201 and a new provider-detail created
- [ ] Exercising the GET ALL and GET BY ID routes display the new provider-detail
- [ ] Exercising the DEL route for the newly created provider results in a 200 (OK) and either null or an empty json object (our routes all handle deletion differently). QAs preference is a message that indicates the object was deleted, but will defer to development.

**Comment by k-macmillan** [comment]
Still relevant.

**Comment by npmartin-oddball** [comment]
Closing, as this work will likely not happen.
