### ISSUE TITLE
Spike: Fargate Deployments Taking Too Long

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1119]
## User Story - Business Need
Deployments take over 20 minutes in dev sometimes. Perf recently took over 20 minutes as well. This is unsustainable for developing features or fixing issues.

### User Story(ies)
**As a** VA Notify engineer
**I want** to deploy as quickly as possible
**So that** I can test my changes in the Dev environment with minimal overhead

### Additional Info and Resources
We only have one task in Dev for the API service (the offending task).
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/fa6c4209-a7ad-4e0d-98bd-3abeac1dfb20)

Dev deploy [example 0](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4327137086)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/ceaba047-1d7b-4f92-bb7f-bce9cb97a45b)

Dev deploy [example 1](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4315879539)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/bb785be4-ca0d-4774-84a2-54a29484d059)

Dev deploy [example 2](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4315879539) - First time, March 2nd
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/1e339cb6-001b-486e-800b-664ad946168a)

The logs for a deploy are likely to give the best insight. 

## Acceptance Criteria & Checklist
- [ ] Difference between our 10 minute runs and these 20+ minute runs is analyzed
- [ ] Learnings have been shared with the team, and decisions have been documented
- [ ] Tickets for next steps have been identified and created

Completed research addresses the problems and/or answers the questions below:  
- Why is this happening?
- How can we fix it?
- It keeps stopping the container/service, why?

## Timebox
2 days

**Comment by cris-oddball** [comment]
Not sure what happened since this ticket was opened, but we have not seen 20 minute deploys in over a year. Closing ticket.
