### ISSUE TITLE
Flask Pre-deployment testing for Push in Staging

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1130]
## User Story - Business Need
When the Flask upgrade is pre-released to staging, the Push route will need to be tested since this feature is not available in Perf. 

### User Story(ies)
**As a** VANotify team member
**I want** to ensure that the push route works in staging
**So that** I can confidently deploy it to Prod

### Additional Info and Resources
- This route cannot be tested in Perf
- This route can only be tested by someone hooked up with the mobile app  @jakehova
- This route must be tested before the Flask upgrade is deployed to Prod.
- We should probably cut the tag from the flask branch, not master.
- https://github.com/department-of-veterans-affairs/vanotify-team/tree/master/Architecture/push-notifications

## Engineering Checklist
_**Required**_

- [x] The Flask code has been validated in Performance, except for this route
- [x] A pre-release has been created and deployed to Staging
- [x] The `{{notification-api-url}}/v2/notifications/push` route is confirmed working in staging
- [x] Push notification is documented and handed off to QA so that @cris-oddball can configure the Perf for push and know how to test it there.

## Acceptance Criteria
_**Required**_
When I send a push notification in staging on the flask upgrade code, the push notification is received.

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by cris-oddball** [comment]
The Flask Upgrade is now in staging, and is ready for testing Push.

**Comment by cris-oddball** [comment]
Worked with Melanie to set up the app on my iPhone with a user from the [spreadsheet](https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-users.csv): `vets.gov.user+36@gmail.com`

Added push to the QA automation service in Staging.

Used this body to send the POST /push request via Postman on staging
```
{
    "mobile_app": "VA_FLAGSHIP_APP",
    "template_id": "1755CD4C33BB0851A416189616441067",
    "recipient_identifier": {
        "id_type": "ICN",
        "id_value": "get from test user spreadsheet"
    },
    "personalisation": {}
}
```

Notifications were received to both my iPhone and Melanie's Android device.

@jakehova If you could please just [update the documentation](url) and check the box in the decription that this is completed. Thanks!

**Comment by jakehova** [comment]
Documentation has been updated: https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Architecture/push-notifications/flagship-mobile-app.md

**Comment by cris-oddball** [comment]
Closing ticket!
