### ISSUE TITLE
BUG: SAWarning messages in logs after Flask upgrade

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1132]
## Description
After the Flask upgrade, the logs contained a number of SAWarning messages (both celery and API logs). Some of these were resolved yet others remain. Low enough priority to release Flask without fixing, but all such warnings should be looked into and resolved.

Examples (noting that these specific ones may have been resolved, others remain)
```
[2023-03-11 09:15:11,752: WARNING/ForkPoolWorker-2] /usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py:1993: SAWarning: Additional column names not matching any column keys in table 'notification_history': 'notification_status'
```

and
```
/app/app/history_meta.py:42: SAWarning: relationship 'ServiceUser.user' will copy column users.id to column user_to_service.user_id, which conflicts with relationship(s): 'Service.users' (copies users.id to user_to_service.user_id), 'User.services' (copies users.id to user_to_service.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="services,users"' to the 'ServiceUser.user' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
```

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

- Log into CloudWatch and open the log group for the notification-api in an environment where Flask is deployed
- Search for "SAWarning"
- Alternatively, just start the app locally.  You will see warnings in your shell.

## Workaround
_Is there something we can do to work around this issue in the meantime? Leave blank if n/a._

## Impact/Urgency

-  Unknown how this impacts the application, considered low risk
- Clutters the logs

## Expected Behavior
**Whoever takes this, if you aren't sure where to start please huddle with Kyle for more context**

- [x]  No SAWarnings appear in the logs for an environment that has Flask deployed to it (not just the examples provided in the description)
- [x] There is a stale branch, "724-warnings," related to this, please be aware of this and resolve as part of this work
- [x] If SAWarnings appear in parts of the code we feel are unused, then identify the applicable endpoint maintenance ticket from this [epic ](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/887) and surface it to the team as work needed so we aren't spending time fixing code we do not use

### Checklist
- [x] Run the docker compose command to bring the app up locally and you'll see the warnings in the output
    - [x] Create a list and track progress in this ticket. Do not exceed a 5.
        - [x] SAWarning: relationship 'ServiceUser.service' will copy column services.id to column user_to_service.service_id, which conflicts with relationship(s): 'Service.users' (copies services.id to user_to_service.service_id), 'User.services' (copies services.id to user_to_service.service_id)
        - [x] SAWarning: relationship 'ServiceUser.user' will copy column users.id to column user_to_service.user_id, which conflicts with relationship(s): 'Service.users' (copies users.id to user_to_service.user_id), 'User.services' (copies users.id to user_to_service.user_id)
        - [x] SAWarning: relationship 'Service.permissions' will copy column services.id to column service_permissions.service_id, which conflicts with relationship(s): 'ServicePermission.service' (copies services.id to service_permissions.service_id).
        - [x] SAWarning: relationship 'ServicePermission.service_permission_types' will copy column services.id to column service_permissions.service_id, which conflicts with relationship(s): 'ServicePermission.service' (copies services.id to service_permissions.service_id).
        - [x] SAWarning: relationship 'ScheduledNotification.notification' will copy column notifications.id to column scheduled_notifications.notification_id, which conflicts with relationship(s): 'Notification.scheduled_notification' (copies notifications.id to scheduled_notifications.notification_id).
        - [x] SAWarning: Column 'ft_notification_status.bst_date' is marked as a member of the primary key for table 'ft_notification_status', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.
        - [x] SAWarning: Column 'ft_notification_status.service_id' is marked as a member of the primary key for table 'ft_notification_status', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.
        - [x] SAWarning: Column 'ft_notification_status.job_id' is marked as a member of the primary key for table 'ft_notification_status', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.
        - [x] SAWarning: Column 'ft_notification_status.notification_type' is marked as a member of the primary key for table 'ft_notification_status', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.
        - [x] SAWarning: Column 'ft_notification_status.key_type' is marked as a member of the primary key for table 'ft_notification_status', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.
        - [x] SAWarning: Column 'ft_notification_status.notification_status' is marked as a member of the primary key for table 'ft_notification_status', but has no Python-side or server-side default generator indicated, nor does it indicate 'autoincrement=True' or 'nullable=True', and no explicit value is passed.
        - [x] SAWarning: Additional column names not matching any column keys in table 'notification_history': 'notification_status' (/app/app/dao/notifications_dao.py:665)
        - [x] SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly (/app/app/dao/notifications_dao.py:625)
        - [x] SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly (/app/app/dao/inbound_sms_dao.py:93)
    - [ ] Any remaining warnings should be put into another ticket

## QA Considerations
- [ ]  Deploy to Staging and let sit for a day
- [ ] QA to verify that no SAWarnings appear in the logs for an environment that has Flask deployed to it

## Additional Info & Resources

Branch "724-warnings", which is stale, contains fixes for many of the warnings.  Most, if not all, of the pertinent changes are in app/models.py and app/model/user.py. Most of the warnings stem from changes in SQLAlchemy regarding relations between models.

https://docs.sqlalchemy.org/en/14/orm/relationships.html

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1132?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by mjones-oddball** [comment]
@kalbfled Add any useful specifics or examples to the ticket from your past research

**Comment by mjones-oddball** [comment]
Holding off on pointing until Dave has cleared up the details in the ticket (related to the stale branch and additional info). When ready Dave should let us know it's ready for refinement again. CC @tabinda-syed

**Comment by mjones-oddball** [comment]
@kalbfled gentle nudge, do you still need to clear up the details in the ticket regarding the stale branch and any other pertinent info you may have from working on the flask upgrade? Don't want too much time to pass and result in lost info. CC @tabinda-syed

**Comment by cris-oddball** [comment]
@kalbfled Can you please update the description of this ticket to match what you wrote in your comment above?

**Comment by kalbfled** [comment]
> @kalbfled Can you please update the description of this ticket to match what you wrote in your comment above?

Done.

**Comment by cris-oddball** [comment]
Just adding more data points here from the Perf logs
```
[2023-06-03 08:15:00,223: WARNING/ForkPoolWorker-4] /app/app/dao/notifications_dao.py:386: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
```

```
[2023-06-03 08:30:00,117: WARNING/ForkPoolWorker-4] /app/app/dao/notifications_dao.py:420: SAWarning: Additional column names not matching any column keys in table 'notification_history': 'notification_status'
```

**Comment by mchlwellman** [comment]
I've identified these warnings currently - 

/Users/michaelwellman/dev/va/notification-api/app/history_meta.py:45: SAWarning: relationship 'ServiceUser.service' will copy column services.id to column user_to_service.service_id, which conflicts with relationship(s): 'Service.users' (copies services.id to user_to_service.service_id), 'User.services' (copies services.id to user_to_service.service_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="services,users"' to the 'ServiceUser.service' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in local_mapper.iterate_properties:
/Users/michaelwellman/dev/va/notification-api/app/history_meta.py:45: SAWarning: relationship 'ServiceUser.user' will copy column users.id to column user_to_service.user_id, which conflicts with relationship(s): 'Service.users' (copies users.id to user_to_service.user_id), 'User.services' (copies users.id to user_to_service.user_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="services,users"' to the 'ServiceUser.user' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in local_mapper.iterate_properties:
/Users/michaelwellman/dev/va/notification-api/app/history_meta.py:45: SAWarning: relationship 'Service.permissions' will copy column services.id to column service_permissions.service_id, which conflicts with relationship(s): 'ServicePermission.service' (copies services.id to service_permissions.service_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="service"' to the 'Service.permissions' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in local_mapper.iterate_properties:
/Users/michaelwellman/dev/va/notification-api/app/history_meta.py:45: SAWarning: relationship 'ServicePermission.service_permission_types' will copy column services.id to column service_permissions.service_id, which conflicts with relationship(s): 'ServicePermission.service' (copies services.id to service_permissions.service_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="service"' to the 'ServicePermission.service_permission_types' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  for prop in local_mapper.iterate_properties:
/Users/michaelwellman/.pyenv/versions/3.10.13/envs/va-notify/lib/python3.10/site-packages/marshmallow_sqlalchemy/convert.py:170: SAWarning: relationship 'ScheduledNotification.notification' will copy column notifications.id to column scheduled_notifications.notification_id, which conflicts with relationship(s): 'Notification.scheduled_notification' (copies notifications.id to scheduled_notifications.notification_id). If this is not the intention, consider if these relationships should be linked with back_populates, or if viewonly=True should be applied to one or more if they are read-only. For the less common case that foreign key constraints are partially overlapping, the orm.foreign() annotation can be used to isolate the columns that should be written towards.   To silence this warning, add the parameter 'overlaps="scheduled_notification"' to the 'ScheduledNotification.notification' relationship. (Background on this error at: https://sqlalche.me/e/14/qzyx)
  prop = model.__mapper__.get_property(property_name)

SQLAlchemy docs on the warning - https://docs.sqlalchemy.org/en/14/errors.html#relationship-x-will-copy-column-q-to-column-p-which-conflicts-with-relationship-s-y

**Comment by mchlwellman** [comment]
All of the tests pass locally and no SA warnings in the docker logs.

**Comment by cris-oddball** [comment]
The current code with the 3 line changes was successfully deployed to Dev and passed regression there. Yay!
```
[2024-02-08 05:30:12,090: WARNING/ForkPoolWorker-1] /app/app/dao/fact_notification_status_dao.py:142:
 SAWarning: Column 'ft_notification_status.bst_date' is marked as a member of the primary key for table 
'ft_notification_status', but has no Python-side or server-side default generator indicated, nor does it indicate 
'autoincrement=True' or 'nullable=True', and no explicit value is passed.  Primary key columns typically may not store
 NULL. Note that as of SQLAlchemy 1.1, 'autoincrement=True' must be indicated explicitly for composite (e.g. 
multicolumn) primary keys if AUTO_INCREMENT/SERIAL/IDENTITY behavior is expected for one of the columns in the
 primary key. CREATE TABLE statements are impacted by this change as well on most backends.
```

Since Michael is ahead of his point value, Kyle cleared him to resolve this one. Ticket is moved back to In Progress for Michael to take a look.

**Comment by cris-oddball** [comment]
Found a few more SAWarning related to the midnight-2AM process. Attaching as a file and provided directly to Michael.
[Addtional SAWarning.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpDQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e19a20217c66f0f235c2dca77bbf750cc1e6c1cc/Addtional%20SAWarning.txt)

**Comment by mchlwellman** [comment]
The next five warnings are all related to the ft_notification_status table composite primary key.  I just need a migration and those will be done. The final entry will require a bit of digging, because the problem is originating in a reference code, not where the warning is reporting.

**Comment by cris-oddball** [comment]
I gave these to Michael after doing an audit of Prod for any other errors. Just these two remain

```
[2024-02-09 06:40:00,089: WARNING/ForkPoolWorker-4] /app/app/dao/inbound_sms_dao.py:93: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly

[2024-02-09 09:15:00,118: WARNING/ForkPoolWorker-4] /app/app/dao/notifications_dao.py:625: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
```

**Comment by cris-oddball** [comment]
This was deployed out to DEV on Friday. In checking the DEV logs for the past two days from Monday, Feb 12, only one SAWarning remains, which is the unchecked one in the description's list above that he did not have time to resolve before deploying. Looking good!

```
[2024-02-12 09:30:00,333: WARNING/ForkPoolWorker-2] /app/app/dao/notifications_dao.py:625: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
```

**Comment by cris-oddball** [comment]
Branch with fix for final warning was deployed to Dev at approx 15:00 MT / 17:00 ET on Feb 12

<img width="1297" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5UQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5dac58d1dadc814c72b5e5d1919268ab4336d179/DeployDev-17.00ET-2024-02-12.png" alt="DeployDev-17.00ET-2024-02-12.png" />

Dev logs checked this morning for the past 24 hours, only one remaining SAWarning, which is on line 93 of `/app/app/dao/inbound_sms_dao.py`. This was seen earlier but only the problem on l625 was transferred to the description. No errors reported for l625 which is the same warning seen on l93:

This error occurred at 23:40 pm MT / 2:40 am ET:

<img width="1379" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13946f3792aedd2e218c1c2518c77e04cae0d27e/SAWarning2024-02-12.png" alt="SAWarning2024-02-12.png" />

@mchlwellman ask another developer if it is possible to test this without it sitting on Dev overnight please.

```
[2024-02-13 06:40:01,720: WARNING/ForkPoolWorker-4] /app/app/dao/inbound_sms_dao.py:93: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
```

**Comment by cris-oddball** [comment]
@mchlwellman please do update your tickets once a day.

My update: after going back and forth, the team landed on using defaults for certain update/inserts, even though they will never be used, to appease SQLALchemy and clear the warnings without needing to rewrite.

However, the last PR pushed up is creating errors on Dev
```
DETAIL:  Failing row contains (2024-02-15, 00000000-0000-0000-0000-000000000000, 00000000-0000-0000-0000-000000000000, 00000000-0000-0000-0000-000000000000, , , created, null, 2024-02-15 18:30:31.349413, null, ).

(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

Possibly related to using a reserved UUID as a default.

Thsi ticket will not be making the release next week, but should be completed by EOD tomorrow.

**Comment by kalbfled** [comment]
With Michael's branch deployed, Cris observed `psycopg2.errors.NotNullViolation` exceptions in the logs when we run the nightly stats query.  (See app/celery/reporting_tasks.py::create_nightly_notification_status.)  After poking around in Datadog, I think this might be a preexisting problem that our unit tests aren't catching.  Here's log output in Dev from February 1st:

![image](https://github.com/department-of-veterans-affairs/notification-api/assets/5375929/9a6381e8-711e-45fb-b39d-1962060834c2)

**Comment by cris-oddball** [comment]
^^^ Thanks for checking earlier logs.  If this is a preexisting issue, then we can proceed with approving this PR and then opening a bug ticket to deal with the psycopg2.errors.NotNullViolation. @kalbfled @mchlwellman

**Comment by cris-oddball** [comment]
PR has been approved and merged. It is sufficient to sit in Perf to see if any SAWarnings persist so will let it sit there overnight. Any issues will be opened on a new ticket. Also, a new bug ticket is forthcoming.

**Comment by cris-oddball** [comment]
also sent the code out to staging, where is more traffic to pick up any errors. will check back on Monday!

**Comment by cris-oddball** [comment]
Reviewed the staging API logs for the past two days, there are exactly zero SAWarning messages! Closing ticket as done.
