### ISSUE TITLE
BUG: requests without timeout

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1134]
## Description

The code scan that occurs for PRs when we push now fails with multiple instances of "request without timeout."

## Steps to Reproduce

Push any code change with a PR, and watch the "code scan" fail.

## Additional Info & Resources

- [Here](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4448093380/jobs/7810436135?pr=1098) are instances of the failure.

- example request with timeout: `r = requests.get('https://example.com/', timeout=5)`

- Requests timeout [documentation](https://docs.python-requests.org/en/latest/user/advanced/#timeouts)

## Workaround

We can manually ignore the failure for other tickets.

## Impact/Urgency

This is **urgent** because it can affect every PR.

## Expected Behavior

- [x] Every request has a timeout parameter of (3.05, 1)
- [x] Code Scan does not report these errors on PRs
- [x] Ensure the lambda function code does not have this problem.  (Would the code scanner catch that?)

Update: Some lambda functions also need updating, and the code scan did not identify this.

## QA Considerations

_For QA to populate. Leave blank if QA is not applicable on this ticket._

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1134?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by kalbfled** [comment]
These changes cleared to code scan failure, but we later discovered that the timeout value often causes user-flows tests to fail.  I increased to timeout value to 5s (read and write) for user-flows as part of the changes for #724.
