### ISSUE TITLE
Alter task definitions for the development environment

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1136]
## Description

We have been seeing long deployment times that often fail with [errors about resource state](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4469464033/jobs/7851728116#step:6:15).  We determined that we need to alter our task definitions to give containers more CPU and memory.

## Steps to Reproduce

Deploy any branch to "dev".

## Workaround

No known workaround.

## Impact/Urgency

Deployments are taking 30+ minutes, which is unacceptable.

## Expected Behavior

- [x] All unit tests pass
- [x] Can deploy the branch successfully

## QA Considerations

_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources

**Comment by kalbfled** [comment]
These upgrades, while appropriate on their own merits, are not fixing the long deployment problem.  After about 5 attempts, I have not been able to deploy the associated code branch without a failure for, "[Resource is not in the state servicesStable](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4451914898/jobs/7837546968#step:6:15)."

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1136?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by kalbfled** [comment]
This was originally a ticket to upgrade Gunicorn and eventlet, but we repurposed it after discovering that we cannot upgrade either of those packages because newer versions cause errors due to [lack of maintenance](https://github.com/benoitc/gunicorn/issues?q=is%3Aissue+is%3Aopen+ALREADY_HANDLED).  We decided that we need to move from Gunicorn to another, more actively maintained WSGI server.

**Comment by mjones-oddball** [comment]
Increasing this from 1 to 2 based off the comment above

**Comment by cris-oddball** [comment]
Master was sent up to Perf without issue during Lucas' testing, so closing this ticket, noting that it is not going out in the deploy this week.
