### ISSUE TITLE
Spike: Investigate scheduling DB backups (DR recovery) 

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1137]
## User Story - Business Goal
To ensure business continuity in case of service failure or data loss, we want to ensure that we can restore the data from a backup using a prescribed method for data recovery. 

This is a "do this on Dev only" ticket, create follow-on tickets for Prod when it is understood and working on Dev.

### User Story(ies)
**As a** VANotify team member  
**I want** To ensure we regularly backup the Postgres DB and are able to recover data missed between backups
**So that** the database is resilient.

### Additional Info and Resources
- [What is AWS Backup](https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html)
- [Using AWS Backup to protect Amazon Aurora databases](https://aws.amazon.com/blogs/storage/using-aws-backup-to-protect-amazon-aurora-databases/)
- [**Overview of backing up and restoring an Aurora DB cluster**](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html) <<< key article
- [Amazon Aurora PostgreSQL backups and long-term data retention methods](https://aws.amazon.com/blogs/database/amazon-aurora-postgresql-backups-and-long-term-data-retention-methods/)
- [Backing up and restoring an Amazon Aurora DB cluster](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/BackupRestoreAurora.html)

## Acceptance Criteria & Checklist
_**Required**_

- [ ] This work is in Dev only
- [x]  Work through the [Aurora backup/restore plan documented](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html) on Dev to validate it works as expected
- [x] Create a BCDR (Business Continuity and Disaster Recovery) plan to ensure that backups are regularly scheduled for the Postgres database  (not using snapshots, but using the Aurora Backup and Recovery as detailed in this [document](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html))
- [x] Forecast associated costs to achieve regularly scheduled backups, storage, and retention so we can budget and gain approval from Beverly
- [x] Technical Documentation has been created specific to our environments and linked in the glossary
- [x] Learnings have been shared with the team, and decisions have been documented
- [x] Tickets for next steps have been identified and created for implementing this on Perf/Staging/Prod.

Completed research addresses the problems and/or answers the questions below:  

- How do we regularly schedule backups?
- How do we recover from an incident with as little data loss (approaching zero) as possible?

## Other Considerations

- Staging and Production are client facing environments, these should have some sort of recovery plan
- Cris mentioned that we may want a version of this set up on Perf for functional parity and validation purposes (even if the retention period is lower)
- Until we know what cost factors are at play we can't predict what to negotiate, so please loop the team in when cost factors are known so we can determine if we need to make adjustments (e.g. if storage creates a huge cost spike we can see what makes sense on each env)

## Timebox
_Leave blank if n/a_

**Comment by nikolai-efimov** [comment]
The follow on work documented here https://github.com/department-of-veterans-affairs/notification-api/issues/1362
