### ISSUE TITLE
Limit who can call notifications/govdelivery endpoint to Granicus IP addresses

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#114]
**As** a VANotify system administrator
**I want** to secure my granicus webhook enpoint
**So that** anyone on the internet is NOT allowed to POST a request to it.

**Context:**
At the moment Granicus does not implement any security in their webhook calls.
As a workaround we should limit who can call our granicus webhook endpoint based on IP address.

**Notes:**
AWS Application Load Balancer allows creation of rules on each of the listeners to handle incoming traffic.
We can create a rule that will look at the path (notifications/govdelivery) and source IP address. If source IP address matches Govdelivery addresses it will forward traffic to our target group.
A second rule will match only path and will return a fixed response 404.
- Discuss during kickoff if the VA Environment is ready, if not we can discuss options to split this story - TW, VA

Govdelivery addresses:
208.42.137.0/24
208.42.190.0/24
209.134.144.0/28
209.134.151.0/24
209.134.158.0/24
69.5.85.128/25
69.5.86.0/24
69.5.87.0/24

**Comment by miabecker** [comment]
Pending ESECC Review.

**Comment by ffafara-tw** [comment]
Configuration to our dev & staging ALB added. 
However Granicus is using IP addresses in staging environment that are not covered by the above list.

Keeping the IP addresses list in sync might be difficult.

**Comment by miabecker** [comment]
Story is cancelled upon consideration as we are concerned about keeping IP address list and blocking in sync which if there is an out of syncness may cause serious issues in production.
