### ISSUE TITLE
BUG: Higher Counts than Message Parts in BigQuery

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1141]
## Description

When looking through BigQuery to validate billing reports we noticed that some fields had higher count values than total message parts, which should NOT be possible. 
1) A direct db query using the same criteria reports different totals and costs than in BigQuery
2) The data in big query is clearly invalid in some cases because count is greater than segment total in some places

## Steps to Reproduce

- See the screenshot below for an example of the data.
- Use this query to get the example data in BigQuery.

```sql
SELECT *
FROM
  `vsp-analytics-and-insights.platform_vanotify.prod-billing`
WHERE
  total_cost IS NOT NULL
  AND total_cost <> 0.0
  AND date = "2023-03-10"
  AND service_name = "BVA"
  AND total_message_parts < count
```

## Workaround
We can still query the Prod db directly. It's not ideal, but it works.

## Impact/Urgency

- As long as this bug exists, a member of the engineering team will have to grab the data from our database directly each month. - This takes engineering time and slows down the billing process on the Product side since they have to wait for someone to grab the data from them.

## Expected Behavior
- The data in BigQuery is complete and correct, especially considering `total_messages` and `total_message_parts` values.

## QA Considerations
Updated: sent sms messages in Perf that will fail (bad recipient id) and some that will succeed. Only the ones that succeed should be in BQ the next day.

## Additional Info & Resources

The query that collects this data from the db each night can be found in the `fetch_nightly_billing_counts` function. 
[Link to code](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/dao/fact_billing_dao.py#L111)

For validating data against the prod db, you can use the queries from [this spreadsheet](https://docs.google.com/spreadsheets/d/12I43Fdrp4CmgkcajtC9OOfwdqOnyKH0fbCL_NlhVBYM/edit#gid=1805892480) and just change the date range.

Example BigQuery Screenshot
![BigQuery_odd_counts 1.png](https://images.zenhubusercontent.com/6261b52f248e574e9270992b/a70a4463-49fc-4d4f-8f5c-df33c4ee7fe0)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1141?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by EvanParish** [comment]
After digging around in the database and doing a lot of number crunching, I believe the numbers we are seeing for message parts and cost are accurate. The count being higher occasionally is coming from the fact that the query to get the nightly billing data is not filtering out notifications that don't have a value for cost. It will just grab the notifications with a failed status that did not get charged and add them to the count. These notification show a zero for message parts, so it's making the count seem off.

**Comment by cris-oddball** [comment]
Based on a better understanding of the work done in this ticket, changed the QA Considerations from validating data between the DB and BQ to sending a few messages that are bound to fail and a few message known to succeed and checking the next morning that only the successful send show up in BQ.

**Comment by cris-oddball** [comment]
Sent two sms to bad recipients, one with and one without a billing code.
Ran the regression prior to and after the deploy, which sends to valid recipients, with and without billing codes. Will check tomorrow morning.
