### ISSUE TITLE
Investigate Endpoints - complaint

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1148]
## User Story - Business Need

In the effort to clean up our code we need to investigate and remove unused endpoints. This ticket is to take a look at the endpoints under `/complaint` and determine if they are useful. Remove these endpoints if it is determined that they are not useful. You can view the table of endpoints [here](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md).

### User Story(ies)
**As an** engineer
**I want** to clean up and reduce our codebase
**So that** it is easier to maintain and upgrade in the future.

### Additional Info and Resources
- [Endpoint Table](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md)
- [Endpoint Spreadsheet](https://docs.google.com/spreadsheets/d/18AfqlEOWlrnigauO57jA0VP3RMHTaP4luknqBxrcbuY/edit#gid=115873237)

## Engineering Checklist

- [ ] Investigate the endpoints starting with `/complaint` to see if they are useful

_Only do the following if it is determined that these endpoints are not useful._
- [ ] _(Optional)_ Remove tests associate with those endpoints
- [ ] _(Optional)_ Remove the code associated with those endpoints (if possible). Make sure not to remove any code used by other parts of the application.

## Acceptance Criteria

- **IF** the designated code and tests have been removed, the application retains full functionality. 

## QA Considerations
- [ ] The QA Regression Suite passes
- [ ] The Cypress regression passes

## Potential Dependencies
- If code removal is necessary, make sure the removal of these endpoints doesn't affect the work Strike is doing.

**Comment by kbelikova-oddball** [comment]
Closing/no longer relevant.
