### ISSUE TITLE
Remove Endpoints - organisation

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1160]
## User Story - Business Need

In the effort to clean up our code we need to investigate and remove unused endpoints. This ticket is to take a look at the endpoints under `/service/<uuid:service_id>/organisation` and remove the ones marked for removal. You can view the table of endpoints [here](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md).

### User Story(ies)
**As an** engineer
**I want** to clean up and reduce our codebase
**So that** it is easier to maintain and upgrade in the future.

### Additional Info and Resources
- [Endpoint Table](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md)
- [Endpoint Spreadsheet](https://docs.google.com/spreadsheets/d/18AfqlEOWlrnigauO57jA0VP3RMHTaP4luknqBxrcbuY/edit#gid=115873237)

## Engineering Checklist

- [ ] Investigate the endpoints starting with `/service/<uuid:service_id>/organisation` to make sure they aren't being used
- [ ] Remove tests associate with those endpoints
- [ ] Remove the code associated with those endpoints (if possible). Make sure not to remove any code used by other parts of the application.

## Acceptance Criteria

- When the designated code and tests have been removed, the application retains full functionality. 

## QA Considerations
- [ ] The QA Regression Suite passes
- [ ] The Cypress regression passes

## Potential Dependencies
- Make sure the removal of these endpoints doesn't affect the work Strike is doing.

**Comment by kbelikova-oddball** [comment]
Closing/no longer relevant.
