### ISSUE TITLE
Access to VA environment 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#117]
This is to track the status of the VA environment and any relevant information regarding the internal VA teams that we are working with

**Comment by anushyaprasad** [comment]
last followed up: 07/21

07/16 follow update: 
the ESCO team is completing and finalizing the VLMF Analysis step on this. We are hoping to have your provision planning meeting by mid next week.

**Comment by marisahoenig** [comment]
Blocker is DVP app code right now

**Comment by QaysarA** [comment]
Account created and onboarding session on Wednesday
