### ISSUE TITLE
Twilio Delivery Status: Callback URL in SMS Message Body

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1182]
## User Story - Business Need
_**Required.** Please note you can have more than one story if applicable. If this is technical work achieving a larger initiative, the user story should represent that piece of the initiative, so it’s clear what problem we are solving._

### User Story (Business)
**As a** Business Line using the Twilio Provider
**I want** to receive updates on the status of my sms notifications
**So that** I can track successes and failures and communicate accordingly to my stakeholders

### User Story (VA Notify)
**As** VA Notfiy
**I want** to be able to send status updates to services
**So that** they  are aware of the status of their messages

### Additional Info and Resources
This is specifically so we can receive status updates from Twilio and has no bearing on the callback code we make to services. This is a change to our Twilio client to specify the endpoint we want to receive status updates. 

- https://support.twilio.com/hc/en-us/articles/360008989454-Tracking-the-Delivery-Status-of-an-Outbound-Twilio-SMS-or-MMS-Message

![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/fed183de-b95b-4ee9-adb0-d445db8cbf4a)

Information on the Twilio Delivery Status Mapping work
https://github.com/department-of-veterans-affairs/notification-api/issues/1073
https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Delivery-Status.md#twilio-delivery-statuses

## Engineering Checklist
- [x] Update `status_callback` in the SMS message request to Twilio when Twilio is the provider in use
- [x] _Twilio_ Callback URL should be populated by env with the desired outcome being like `https://dev-api.va.gov/vanotify/sms/deliverystatus`
  - NOTE: perf's public endpoint doesn't follow the usual pattern because it uses "sandbox" instead of "perf". I'm not sure how that will factor in but we should be aware. https://sandbox-api.va.gov/vanotify
- [x] Setup of the `self.callback_url` is handled in `init_app` rather than every time we send an sms

## Acceptance Criteria
Given I am VA Notify
When I send an SMS message using Twilio
Then I will receive status updates on my message via the callback endpoint we specified in the message request
And I see that callback hitting our lambda

Given I am a client of VA Notify with a valid service and callback setup
When I send an SMS message using Twilio
Then I will receive status updates on my message delivery via the callback
And I see the updated status in the notification status endpoint `{{notification-api-url}}/v2/notifications/{{notification-id}}`

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

Jacob and Melanie set up a Twilio Testing Service, Template, Callback and Sender in Perf. Currently the callback is going to Jacob's test endpoint, QA will likely need their own at some point (maybe not with this ticket for time sake) - but please be aware and plan accordingly.

QA Test Plan
- In the Service created in Perf for testing, use Postman to send an SMS message (this will go through Twilio)
- Validate the following:
- [ ] Lambda logs that the message was processed and sent to the SQS queue
- [ ] ECS logs to verify the delivery status translation
- [ ] DB to ensure the status of the record is updated (use GET v2/notifications/:notification-id )
- [ ] Check the delivery status callback URL for the appropriate body sent to the webhook

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by cris-oddball** [comment]
Update to above: edited the description to add my questions to QA Considerations and asked Jacob for a meeting to discuss.

**Comment by jakehova** [comment]
Directions to create a service callback & Information about the service callback that Melanie and I created in the PERF environment: 

1) Login to perf.notifications.va.gov
2) Create a Service: Click on Admin -> Services -> Add a Service
  a) Created "Twilio Testing Service" with id: "e024930e-a56d-45dc-ba96-7c34929db954"
  b) Set "service-id" field in Postman environment
3) Create an SMS template: Select created service from drop down -> click on "Create Template" -> SMS Template 
  a) The portal defaults to using pinpoint as Provider right now, so need to go to postman to update the template to use the Twilio Provider
  b) created "Twilio Status Testing" with id: "e0db3e86-ba17-40d0-9fc7-4ff9eb33ef72"
4) Get Provider information: Go to Postman, and run /provider-details/get provider details
  a) Get "Twilio" provider id: "0f03d378-796c-4fb8-8c20-c3e99d43e8fd"
  b) Set "provider-detail-id" field in Postman environment
5) Create Phone Number record to send with: /service/sms-sender/create sms sender
  a) this requires having a Twilio phone number to use.   We have access to this one: +19703005680
  b) created sms sender id: "f6979d20-6b2a-4e58-907c-1f007874c86f"
6) Create callback: /service/callback/create service callback
  a) Specify a URL that you have access to verify callback and list out all the delivery statuses: 
  {
    "url": "<your url>",
    "callback_type": "delivery_status",
    "callback_channel": "webhook",
    "bearer_token": "static-bearer-token-used-to-authenticate-request",
    "notification_statuses": ["sent", "delivered", "failed", "technical-failure", "temporary-failure", "permanent-failure", "preferences-declined" ]
  }
  b) Service Callback ID created: "045c9e36-b6de-40b0-9e04-6e20daa767ee"
7) You'll want to update the service callback url to whatever endpoint you are monitoring: /service/callback/update service callback:
  {
    "url": "<url you want to use>"
  }

**Comment by cris-oddball** [comment]
Updated the QA Considerations to include a test plan.

**Comment by jakehova** [comment]
I have deployed this to dev and confirmed that it works.

**Comment by cris-oddball** [comment]
This has been deployed to Perf and will be tested on Friday to allow the previous test messages to possibly clear the queue.

**Comment by cris-oddball** [comment]
Fail - Test 1 on perf, sending an sms to my phone from the Twllio Testing Service in Perf, using Jacob's pipedream endpoint
Fail - Test 2 on perf, sending an sms to my phone from the Twllio Testing Service in Perf, using my pipedream endpoint

- Fail -  Lambda logs that the message was processed and sent to the SQS queue: no messages in the Lambda logs
- Fail - ECS logs to verify the delivery status translation - No celery logs seen for "Processing Notification Delivery Status"
- Pass in that there is a DB entry, but it never reports Delivered, is stuck at Sending - DB to ensure the status of the record is updated (use GET v2/notifications/:notification-id ) 
- Fail - Pipedream endpoint never gets a hit - Check the delivery status callback URL for the appropriate body sent to the webhook

**Comment by cris-oddball** [comment]
**QA PASSES**

Test 4 Post- hotfix and ALB host for Perf change

Sending SMS through Perf's Twilio Testing Service using special template and Twilio as provider:

1. Received text to phone
2. DB to ensure the status of the record is updated (use GET `v2/notifications/:notification-id` )
notification_id is `8be524ee-9e13-47fd-afc2-f14417821a05`
Truncated response showing important properties:
```
{
    "billing_code": "qa-twilio-test",
    "body": "Testing template, no personalisations.",
    "completed_at": "2023-03-31T19:02:01.881371Z",
    "cost_in_millicents": 0.0,
    "created_at": "2023-03-31T19:01:48.843463Z",
    "id": "8be524ee-9e13-47fd-afc2-f14417821a05",
    "phone_number": "+REDACTED",
    "provider_reference": "SMc37ab9aa85e9cb7d26dc8688fd93e487",
    "segments_count": 0,
    "sent_at": "2023-03-31T19:01:49.600908Z",
    "sent_by": "twilio",
    "sms_sender_id": "f6979d20-6b2a-4e58-907c-1f007874c86f",
    "status": "delivered",
    "status_reason": null,
    "template": {
        "id": "e0db3e86-ba17-40d0-9fc7-4ff9eb33ef72",
        "uri": "https://sandbox-api.va.gov/v2/template/e0db3e86-ba17-40d0-9fc7-4ff9eb33ef72/version/2",
        "version": 2
    },
    "type": "sms"
}

```

3. Lambda logs that the message was processed and sent to the SQS queue
```
[INFO]	2023-03-31T19:01:51.847Z	
1ad9cd31-9c4b-4fe9-9fb3-565e8f5e89ca	. . . Completed the SQS push.
[INFO]	2023-03-31T19:01:51.847Z	1ad9cd31-9c4b-4fe9-9fb3-565e8f5e89ca	Processing of request complete
```

4. ECS celery logs to verify the delivery status translation
```
{
    "name": "delivery",
    "levelname": "INFO",
    "message": "Processing Notification Delivery Status. | reference=SMc37ab9aa85e9cb7d26dc8688fd93e487 | notification_status=delivered | number_of_message_parts=1 | price_in_millicents_usd=0.0",
    "pathname": "/app/app/celery/process_delivery_status_result_tasks.py",
    "lineno": 185,
    "time": "2023-03-31T19:02:01",
    "requestId": "no-request-id",
    "application": "delivery",
    "logType": "application"
}
[2023-03-31 19:02:01,858: INFO/ForkPoolWorker-2] Processing Notification Delivery Status. | reference=SMc37ab9aa85e9cb7d26dc8688fd93e487 | notification_status=delivered | number_of_message_parts=1 | price_in_millicents_usd=0.0
```

5. Check the delivery status callback URL for the appropriate body sent to the webhook
```
{
    "id":"8be524ee-9e13-47fd-afc2-f14417821a05",
    "reference":null,"to":"+REDACTED",
   "status":"delivered",
    "created_at":"2023-03-31T19:01:48.843463Z",
    "completed_at":"2023-03-31T19:02:01.881371Z",
    "sent_at":"2023-03-31T19:01:49.600908Z",
    "notification_type":"sms",
    "status_reason":{
        "notification_id":"8be524ee-9e13-47fd-afc2-f14417821a05",
        "notification_client_reference":null,
        "notification_to":"+REDACTED",
        "notification_status":"delivered",
        "notification_created_at":"2023-03-31T19:01:48.843463Z",
        "notification_updated_at":"2023-03-31T19:02:01.881371Z",
        "notification_sent_at":"2023-03-31T19:01:49.600908Z",
        "notification_type":"sms",
        "service_callback_api_url":"https://eoosreag8v79mdd.m.pipedream.net/",
        "service_callback_api_bearer_token":"static-bearer-token-used-to-authenticate-request",
        "provider":"twilio",
        "status_reason":null,
        "provider_payload":{}
    }, 
    "provider":"twilio",
    "provider_payload":{}
}
```

**Comment by cris-oddball** [comment]
[Ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-infra/533) so that we don't lose the correct host in the ALN if we need to deploy Infra.
