### ISSUE TITLE
Spike: Do we overuse the retry queue in Celery tasks?

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1183]
## User Story - Business Goal

Our Celery tasks receive inputs that could raise exceptions when parsed.  For example, invalid stringified JSON could raise a ValueError during a call to json.loads.  In multiple instances, our code responds by putting the input into a retry queue, but is this useful?  Won't it still be broken upon retry?  [Inquiring minds want to know](https://www.youtube.com/watch?v=2r3Xs9sBEVg).

### User Story(ies)
**As a** developer
**I want** to place a Celery task in the retry queue only when it might succeed in the future
**So that** it does not bloat the code and cause superfluous computation.

**As a** product owner
**I want** the highest through-put from our application
**So that** it can handle any expected load with the lowest cost.

### Additional Info and Resources

Here are instances of retrying failed inputs:
```bash
.../notification-api$ grep -rni -E "(task|self)\.retry" app/celery/
app/celery/process_ses_receipts_tasks.py:181:                self.retry(queue=QueueNames.RETRY)
app/celery/process_ses_receipts_tasks.py:239:        self.retry(queue=QueueNames.RETRY)
app/celery/process_ses_receipts_tasks.py:319:        self.retry(queue=QueueNames.RETRY)
app/celery/service_callback_tasks.py:55:            self.retry(queue=QueueNames.RETRY)
app/celery/service_callback_tasks.py:97:            self.retry(queue=QueueNames.RETRY)
app/celery/service_callback_tasks.py:180:            self.retry(queue=QueueNames.RETRY)
app/celery/lookup_va_profile_id_task.py:41:            self.retry(queue=QueueNames.RETRY)
app/celery/letters_pdf_tasks.py:82:            self.retry(queue=QueueNames.RETRY)
app/celery/letters_pdf_tasks.py:336:            self.retry(queue=QueueNames.RETRY)
app/celery/lookup_recipient_communication_permissions_task.py:76:            task.retry(queue=QueueNames.RETRY)
app/celery/provider_tasks.py:55:                self.retry(queue=QueueNames.RETRY, countdown=0)
app/celery/provider_tasks.py:57:                self.retry(queue=QueueNames.RETRY)
app/celery/provider_tasks.py:110:        self.retry(queue=QueueNames.RATE_LIMIT_RETRY, max_retries=None, countdown=retry_time)
app/celery/provider_tasks.py:117:                self.retry(queue=QueueNames.RETRY, max_retries=48, countdown=0)
app/celery/provider_tasks.py:119:                self.retry(queue=QueueNames.RETRY, max_retries=48, countdown=300)
app/celery/provider_tasks.py:156:        self.retry(queue=QueueNames.RETRY, countdown=60)
app/celery/provider_tasks.py:176:            self.retry(queue=QueueNames.RETRY)
app/celery/process_pinpoint_receipt_tasks.py:71:        self.retry(queue=QueueNames.RETRY)
app/celery/process_pinpoint_receipt_tasks.py:85:        self.retry(queue=QueueNames.RETRY)
app/celery/process_pinpoint_receipt_tasks.py:102:            self.retry(queue=QueueNames.RETRY)
app/celery/process_pinpoint_receipt_tasks.py:141:        self.retry(queue=QueueNames.RETRY)
app/celery/contact_information_tasks.py:36:            self.retry(queue=QueueNames.RETRY)
app/celery/tasks.py:396:            task.retry(queue=QueueNames.RETRY, exc=exc)
```

## Acceptance Criteria & Checklist

Either of these conditions is met:

- [ ] We determine that all of the retries are necessary.
- [ ] We identify unhelpful retries and create a ticket to remove them.

Completed research addresses the problems and/or answers the questions below:  

- Do we need all of these retries?

## Timebox

2 hours

**Comment by cris-oddball** [comment]
We probably need to work this sooner than later. @mjones-oddball

**Comment by k-macmillan** [comment]
We know at this point it is overused, now it's more of a matter of, "how do we fix that?"

The safest path forward with this is to devote an engineer for 2ish days strictly to map out `deliver_email()`, `deliver_sms()`, and `deliver_sms_with_rate_limiting()` to track down all _expected retries_. We don't need visuals, just to ensure all branches in the code are checked and we know exactly what can be retried. Each of those involve dozens of method calls. We can then lump all those into an exception group `except (Error1, Error2, Error3) as e` and only retry those, everything else falls into the generic catch and is not retried. We need to duplicate this effort for the other retry paths as well...

Right now we are playing whack-a-mole. I initially hoped to log the retries we were doing so we could avoid the engineer work, but I did not realize the impact non-retryable exceptions would have.

**Comment by k-macmillan** [comment]
Saw a `ConnectionError` due to a `RemoteDisconnect`, we need to retest on that too.

**Comment by k-macmillan** [comment]
Understanding of queues and celery has greatly improved. This is no longer an issue.
