### ISSUE TITLE
Break post_notification Into 2 Methods

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1196]
## User Story - Business Need
The [`post_notification()`](https://github.com/department-of-veterans-affairs/notification-api/blob/v1.5.13/app/v2/notifications/post_notifications.py#L108) route is a flask blueprint route. We want to keep that as-is but break the internal code into a second method. The reason for this is so we do not affect the Flask endpoint but can call the related code from say, a Celery method. By breaking it up we preserve the functionality while allowing reuse of the code. 

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)
**As a** VA Notify
**I want** to reuse code
**So that** our code base does not grow unnecessarily

### Additional Info and Resources
Sample of what the code may look like broken apart:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/f3b290ad-553c-41cd-88ab-d25e0c50612e)

## Engineering Checklist
- [ ] Break apart the method in the way shown (or equivalent)
- [ ] Ensure functionality of email/SMS remains unchanged
- [ ] Update unit tests

## Acceptance Criteria
- [ ] No functionality is lost. 
- [ ] `post_notification` has been split into at least two methods

## QA Considerations
- [ ] POST v2/notifications/sms works as before
- [ ] POST v2/notifications/email works as before
- [ ] Stretch: time the routes before and after the deploy to Perf, just to ensure that an unusual delay hasn't been added.

**Comment by tabinda-syed** [comment]
Kyle at Refinement: "If this takes a week, we should [really figure out what's going on.]"

**Comment by npmartin-oddball** [comment]
Closing/no longer relevant.
