### ISSUE TITLE
Visualize email notification sending flow

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/notification-api#12]
**As** a VANotify developer
**I want** to understand what happens when the system receives request to send a Notification (text/email)
**So that** I can confidently change the system.

**Acceptance criteria:**
- PlantUML sequence diagram showing all internal invocations / steps for SMS for sending and status updating
- *Optional:* PlantUML sequence diagram showing all internal invocations / steps for email (needed only if significantly different)

**Notes:**
- Email notification visual will be done in another story (#96)

**Comment by ffafara-tw** [comment]
Pushed to notification-api/documents/send-email-sequence-diagram.puml

**Comment by philherbert** [comment]
Gonna discuss this at tomorrow's dev sync, to see whether we need additional sessions

**Comment by marisahoenig** [comment]
Looks good overall, @ffafara-tw . I found it interesting that in research mode, it calls a `process_ses_results` method, which would need SES set up as an email client to work. If we're ever going to use research mode, we would need to update this or make SES one of our clients.
Moving to Done!
