### ISSUE TITLE
SPIKE: Poetry Setup

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1202]
## User Story - Business Goal
_**Required.** Please note you can have more than one story if applicable. If this is a technical investigation to achieve a larger initiative, the user story should represent that piece of the initiative._

### User Story(ies)
**As** VA Notify
**I want** to simplify the dependency management of VA Notify
**So that** we can quickly and effectively keep our system up to date with the latest changes

### Additional Info and Resources
- [Poetry docs](https://python-poetry.org/docs/)

## Acceptance Criteria & Checklist
_**Required**_

- [ ] Review of how Poetry works in the QA repository.
- [ ] Determine how Poetry would replace the requirements-app.text, requirements.txt, requirements_for_local.txt, requirements_for_test.txt and the requirements files for the lambdas, which are just used as documentation.
- [ ] Determine what changes would be necessary to build the actions/containers to use poetry instead of pip
- [ ] Technical Documentation has been created and linked in the glossary
- [ ] Learnings have been shared with the team, and decisions have been documented
- [ ] Tickets for next steps have been identified and created

Completed research addresses the problems and/or answers the questions below:  

- How can we best leverage Poetry to replace pip in the notifications-api repo ?

## Timebox
Timebox to 2 days.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1202?planning-poker) with Zenhub @cris-oddball @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by ldraney** [comment]
A chat with Cris about any issues implementing Poetry in the QA repo is a good idea

**Comment by ldraney** [comment]
Poetry should not effect requirements_for_test.txt and the requirements files for the lambdas

**Comment by ldraney** [comment]
A key point is how the dockerfiles are going to be modified in order to get this to work.  In other words, documenting specific links to the poetry documentation on what implementation would look like is the goal of this ticket.

**Comment by kalbfled** [comment]
@tabinda-syed This ticket is a good example of something I would like to discuss in retro.

**Comment by k-macmillan** [comment]
Updated with #1665
