### ISSUE TITLE
Setup ruff Formatter/linter And Run Against Repo

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1204]
## User Story - Business Need
Our code is very inconsistent. We have several styles of code that causes conflict. When one member attempts to format their code it can cause dozens or even hundreds of changes in files unrelated to the work they are doing. Formatting is, in general, good but it is disruptive in the current form. 

We need consistency across the repository so that maintenance is easier and future engineers will receive a consistent code base. Format the entire repository with [ruff](https://pypi.org/project/ruff/).

- [x] discuss with QA

### User Story(ies)
**As an** engineer
**I want** to minimize time spent reviewing PRs and time spent understanding code
**So that** I can work more effectively

### Additional Info and Resources
- [ruff documentation](https://docs.astral.sh/ruff/)

## Engineering Checklist
- [x] Format options discussed with @k-macmillan 
- [x] Entire repository formatted
- [x] `#nosec` comments moved if necessary
- [x] Format shared with all engineers by adding document to the Team repo
- [x] Notification sent to all engineers so they can update their local repositories

## Acceptance Criteria
No functionality is lost. No code is changed aside from formatting. Entire repository has been formatted.

## QA Considerations
QA to double-check things on this one since code changes can introduce issues.
- [ ] regression passes

## Assumptions
- No code has to be changed

**Comment by k-macmillan** [comment]
ruff formatter setup and ran against the repo. Relatively painless other than the CodeQL stuff that was brought up (all valid). Unit tests, deploy, and regression all ran smooth. Added to the pre-commit hook. Validated formatter cause tests to fail in the same manner flake8 did. Removed references to flake8.

**Comment by k-macmillan** [comment]
There were several PRs in-flight so I held off on making this change until everything was about done. Merged master, reformatted function parameters. Unit tests and regression passes. The PR is up for review.

**Comment by cris-oddball** [comment]
@k-macmillan we might have a problem with API master. see my slack thread in our eng channel. just something to consider, since I'm not sure how widespread the problems with the lambdas are and if it's a simple fix or an extensive one.

**Comment by k-macmillan** [comment]
Merged! This issue is now resolved.
