### ISSUE TITLE
Github Tag Trigger failure

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1208]
## Description
When pre-release tags are made, the "deploy to dev" for perf workflow is not triggered, causing the QA engineer to manually deploy to perf. This is against our process and causes a frustrating delay in their work.

## Steps to Reproduce
1. Create a pre-release tag.  If it is successful the first time, simply cut a new tag, and the workflow shouldn't trigger.  Run something similar to:
```
git pull
git tag v1.5.10-pre-release-test
git push origin v1.5.10-pre-release-test
```
3. Observe that the "deploy to dev" workflow for the perf environment is not triggered

## Workaround
Manually deploying via "Deploy to Dev" workflow

## Impact/Urgency
This bug has a high impact on our system and team, as it causes delays and requires a manual step in our process.

## Expected Behavior
When a pre-release tag is created, the "deploy to staging" workflow should be triggered automatically.

- [ ] The "deploy to dev" workflow should run automatically
- [ ] The QA engineer should not have to manually deploy to perf

## QA Considerations
N/A

## Additional Info & Resources
- [Response from Github Enterprise](https://support.github.com/ticket/personal/0/2070090) team: "[Our documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags) notes that quotes are only required when you begin with a * character. Have you tried without quotes? I'm not seeing specific evidence that would impact this, but would be curious about your results. If you could provide additional details about the nature and history of inconsistencies you are seeing and any errors that result, it would help us better troubleshoot this unexpected behavior."

**Comment by cris-oddball** [comment]
Another non-issue now that we have the pipeline.
