### ISSUE TITLE
Pass Decoded Provider Data During Translate Method

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1209]
## User Story - Business Need
We intended to send the provider's payload as-is to services but it was left in the base64 encoding. This is a one-word change to the Translate method. The data is already decoded, we just want to specify _that_ as the payload that is returned, rather than the base64 encoded data.

### User Story(ies)
**As a** service using VA Notify
**I want** the provider's payload as it came to VA Notify
**So that** I can handle the provider's payload as I currently do 

## Engineering Checklist
- [x] url-encoded string returned as the payload
- [x] Unit tests still pass

## Acceptance Criteria
Provider payload that comes through is sent out in the same format it came in as.

## QA Considerations
Due to DB testing in Perf, if the code works in Dev, QA can send the code straight up to Perf/Staging without testing.

**Comment by cris-oddball** [comment]
@jakehova I added the QA label, please just let me know when the code has been tested in Dev and merged to master so that I can send it up the food chain, please.

**Comment by cris-oddball** [comment]
Deploying to Perf via tag.

**Comment by cris-oddball** [comment]
Deploy to perf [failed on running migrations](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/4660022626). Unclear if related to the DB work earlier. Am sending this code straight up to staging.

**Comment by cris-oddball** [comment]
Deploy to staging successful. Jacob to test there.

**Comment by cris-oddball** [comment]
Tests pass in staging.

**Comment by mjones-oddball** [comment]
![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/abb4a1a1-d6a3-48b5-9593-0eb36b17ef8f)

**Comment by mjones-oddball** [comment]
Image above was Jacob's validation in Staging

**Comment by cris-oddball** [comment]
@mjones-oddball @jakehova is that what we expected? I expected a JSON object to be returned. Does this need to be re-opened?

**Comment by k-macmillan** [comment]
@cris-oddball I thought it was a json coming from Twilio but it's a url encoded string. The payload shown is what we receive from Twilio and is the correct thing to send to the service.
