### ISSUE TITLE
Design VA Profile and MPI integration

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#121]
**As** a VANotify developer
**I want** access to technical documentation on VA Profile and MPI integration
**So** the team is aligned on the approach
**And** I have context to confidently work on implementation

**As** VANotify consumer 
**I want** access to OpenApi documentation
**So that** I can easily integrate with VANotify
**And** consume its services

**In scope / Checklist:**
- [x] sequence diagram for sending notification that requires looking up contact information from VA Profile and translating identifier using MPI - https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/contact-info-lookup-sequence-diagram.puml
![Diagram](http://www.plantuml.com/plantuml/png/5OwnTSCm30NxJ94C0B5FfLKG4fJm8W8qy6clRwkwwkxTdk306jVNZrgzLfFl4vZvMqhmQpiKv_fRAL7T88Qj-YXD9WU66CWxFGKIR4dSEsjaCOTshGnr8vvQ1YSaIlEwRYdB7UCAKkjEb_l_cfJoM69Lg2aVmMERzzKkrZvy0m00)
- [x] Open API documentation of the new API that utilizes VA identifiers (happy path and error responses)
- [x] list of changes to data model to support VA Profile and MPI integration:
  - Change the `to` column in the `notifications` table to be nullable
  - Create a new `identifiers` table (name TBC), with the following columns:
    - `id` (`UUID`, not nullable)
    - `notification_id` (`UUID`, foreign key constraint to `notifications.id`, not nullable)
    - `identifier_type` (`String`, enum of `participant_id`, `vet360_id`, not nullable)
    - `identifier_value` (`String`, not nullable)
- [x] list of additional notification states / statuses if applicable -> See ADR. No new statuses.
- [x] documentation of error paths - https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/contact-info-lookup-error-cases.md
- [x] ADR entry for integration design - https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/documents/adr/0004-integration-with-va-profile-and-master-person-index.md

**Comment by marisahoenig** [comment]
Reviewed ADR with devs in discussion today. Moving to Review, but we may be able to just close it?
