### ISSUE TITLE
Story: Refactor CeleryTask - Process Delivery Status 

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1216]
## User Story - Business Need
There is a celery task called `process_delivery_status()` that should be refactored in various areas. It was a copy/paste of another method with pinpoint-specific stuff removed, but was meant to be a replacement eventually.

### User Story(ies)
**As a** developer
**I want**  process_delivery_status() to be refactored
**So that** we reduce complexity while improving structure and implementation

### Additional Info and Resources
TBD

## Engineering Checklist

- [ ] Reduce use of try/catch
- [ ] Remove the need to pass "self"
- [ ] Reduce function called by celery task
- [ ] Increase test case coverage 
- [ ] Better use of mock when testing

## Acceptance Criteria
- [ ] The celery task no longer passes self to called functions for the purpose of self.retry()
- [ ] _get_provider_info() and _get_sqs_message() and _increment_statsd() are moved inside process_delivery_status()

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by npmartin-oddball** [comment]
Will not be worked.
