### ISSUE TITLE
BUG: Callback provider_payload includes the payload when set to false

### ISSUE THREAD

**Issue by justaskdavidb2** [department-of-veterans-affairs/notification-api#1220]
## Description
Provider payload is included even when service did not request for it.

## Steps to Reproduce

We indicate that service wants to have us return them the payload we received from the provider and then examine the payload response.

We then repeat the process except we indicate that the service is to not include the payload. 
We currently observe that the payload is still being included as an empty dictionary.

## Workaround
None

## Impact/Urgency
Can wait until the next Prod deployment though since only vetext has a callback in Prod and they are not using it yet.

## Expected Behavior
The provider's payload should only be present in the callback response when the service explicitly requested to have the payload response. 

- [x] provider payload is not present in response to service when the service has indicated to not include the provider's payload.

- [x] provider payload is present in the response to the service when the service has explicitly requested to include the provider's payload

- [x] At least two unit test must be created: one for when payload should be included and the other for when it should not be included.

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
provider_payload is always there but if it is an empty dictionary it is not to be included.

![image (7).png](https://images.zenhubusercontent.com/630696b479f5cca51e546872/9595418b-fb39-49e9-8b1f-41ff9dec5d9b)

## include_provider_payload is True
Examples of what the callback message should look like.
### Pinpoint
```
"id":"6ba081d5-f3d2-47f0-9d04-99be86abab9c",  
"reference":null,  
"to":"+17039327969",  
"status":"delivered",  
"created_at":"2023-01-10T00:04:25.273410Z",  
"completed_at":"2023-01-10T00:05:33.255911Z",  
"sent_at":"2023-01-10T00:04:25.775363Z",  
"notification_type":"SMS",   
"status_reason": "string", 
"provider":"pinpoint", 
"provider_payload": {}
```

### Twilio
```
"id":"6ba081d5-f3d2-47f0-9d04-99be86abab9c",  
"reference":null,  
"to":"+17039327969",  
"status":"delivered",  
"created_at":"2023-01-10T00:04:25.273410Z",  
"completed_at":"2023-01-10T00:05:33.255911Z",  
"sent_at":"2023-01-10T00:04:25.775363Z",  
"notification_type":"SMS",   
"status_reason": "string", 
"provider":"twilio", 
"provider_payload": "url encoded string"
```
## include_provider_payload is False
Examples of what the callback message should look like.
### Pinpoint
```
"id":"6ba081d5-f3d2-47f0-9d04-99be86abab9c",  
"reference":null,  
"to":"+17039327969",  
"status":"delivered",  
"created_at":"2023-01-10T00:04:25.273410Z",  
"completed_at":"2023-01-10T00:05:33.255911Z",  
"sent_at":"2023-01-10T00:04:25.775363Z",  
"notification_type":"SMS",   
"status_reason": "string", 
"provider":"pinpoint"
```
### Twilio
```
"id":"6ba081d5-f3d2-47f0-9d04-99be86abab9c",  
"reference":null,  
"to":"+17039327969",  
"status":"delivered",  
"created_at":"2023-01-10T00:04:25.273410Z",  
"completed_at":"2023-01-10T00:05:33.255911Z",  
"sent_at":"2023-01-10T00:04:25.775363Z",  
"notification_type":"SMS",   
"status_reason": "string", 
"provider":"twilio"
```

**Comment by tabinda-syed** [comment]
Kyle: This does not need to be in the 4/20 release.

**Comment by cris-oddball** [comment]
This is deployed to Perf and ready for QA validation.

**Comment by cris-oddball** [comment]
QA PASSES

1. callback includes provider_payload when `"include_provider_payload": true` set on the callback.
Response showing string in that property:
```
SmsSid=SM4b753148d640494074db8c84d3de4ea3&SmsStatus=sent&MessageStatus=sent&To=%2B17192445254&MessageSid=SM4b753148d640494074db8c84d3de4ea3&AccountSid=ACb1aa023dff676332332006a775c1f915&From=%2B19703005680&ApiVersion=2010-04-01
```

2. callback does not include the property provider_payload when `"include_provider_payload": false` set on the callback.
Response showing the property is not there:
```
{"id":"d884fbf8-6bd0-49e4-bff6-432bd8ed3d31","reference":null,"to":"+17192445254","status":"delivered","created_at":"2023-04-25T21:17:09.540083Z","completed_at":"2023-04-25T21:17:22.031227Z","sent_at":"2023-04-25T21:17:10.534892Z","notification_type":"sms","status_reason":null,"provider":"twilio"}
```

3. callback does not include the property provider_payload when the message is sent through Pinpoint, regardless of whether `"include_provider_payload"` is true or false
Response showing the property is not there:
```
{"id":"15e9aaa3-8f02-4898-a4a5-abc547e701ee","reference":null,"to":"+17192445254","status":"delivered","created_at":"2023-04-25T21:07:35.923037Z","completed_at":"2023-04-25T21:07:59.862692Z","sent_at":"2023-04-25T21:07:36.519417Z","notification_type":"sms","status_reason":null,"provider":"pinpoint"}
```

**Comment by cris-oddball** [comment]
This needs to be reverted, re-opening the ticket.

**Comment by k-macmillan** [comment]
After discussion it is no longer internally blocked. This can be tested in perf. Label removed.

**Comment by cris-oddball** [comment]
This is ready for PR review and when approved can be merged to master.

Due to issues testing on Dev, the branch `1220-rev` with the fix in it was deployed to Perf for testing. David observed me doing the following tests:

PII and account data is redacted below.

Test 1
Perf - Twilio testing service 
- provider is Twilio
- include_provider_payload on callback is set to false
- provider_payload is included in not the body of the POST response
```
{"id":"8db8eacb-9628-4b36-bc53-e2a3c9e7cd6f","reference":null,"to":"<redacted>","status":"delivered","created_at":"2023-04-28T20:39:36.319202Z","completed_at":"2023-04-28T20:39:49.436079Z","sent_at":"2023-04-28T20:39:37.088432Z","notification_type":"sms","status_reason":null,"provider":"twilio"}
```
Test 2
Perf - Twilio testing service
- provider is Twilio
- include_provider_payload on callback is set to true
- provider_payload is included in the body of the POST response and the value is a string 
```
{"id":"7d68e934-8110-40ac-b167-2b888a0de7c8","reference":null,"to":"<redacted>","status":"delivered","created_at":"2023-04-28T20:42:53.608131Z","completed_at":"2023-04-28T20:43:06.045777Z","sent_at":"2023-04-28T20:42:54.530043Z","notification_type":"sms","status_reason":null,"provider":"twilio","provider_payload":"RawDlrDoneDate=2304282042&SmsSid=SMf79963d50d1e0087c551bef91920eb4d&SmsStatus=delivered&MessageStatus=delivered&To=<redacted>&MessageSid=SMf79963d50d1e0087c551bef91920eb4d&<redacted>&From=%2B19703005680&ApiVersion=2010-04-01"}
```

Test 3
Perf - QA Automation Service
- provider is Pinpoint
- include_provider_payload on callback is set to true
- provider_payload is included in the body of the POST response with an empty JSON object
```
{"id":"77409684-c2b0-4ed1-a014-3d172038d6c9","reference":null,"to":"<redacted>","status":"delivered","created_at":"2023-04-28T20:45:04.971788Z","completed_at":"2023-04-28T20:45:36.180404Z","sent_at":"2023-04-28T20:45:05.665266Z","notification_type":"sms","status_reason":null,"provider":"pinpoint","provider_payload":{}}
```

Test 4
Perf - QA Automation Service 
- provider is Pinpoint
- include_provider_payload on callback is set to false
- provider_payload is not included in the body of the POST response
```
{"id":"9987278e-3d3f-4530-8fd2-3674188bfbe5","reference":null,"to":"<redacted>","status":"delivered","created_at":"2023-04-28T20:47:00.169664Z","completed_at":"2023-04-28T20:47:24.855634Z","sent_at":"2023-04-28T20:47:00.798638Z","notification_type":"sms","status_reason":null,"provider":"pinpoint"}
```

**Comment by cris-oddball** [comment]
Code is merged to master, deploying to Perf. Will probably re-test Monday morning.

**Comment by cris-oddball** [comment]
**QA PASSES**

testing same as above comment:
- when include_provider_payload is set to False, then provider_payload is not included in the POST callback response for any provider
- when include_provider_payload is set to True, then provider_payload is included in the POST callback response for any provider: Twilio will be a url encoded string while Pinpoint is an empty json object.

Closing ticket.
