### ISSUE TITLE
API: PyPDF2 deprecation

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1221]
## User Story - Business Need

`PyPDF2` is deprecated and should be replaced with `pypdf`.  See the note [here](https://pypi.org/project/PyPDF2/).  This change should be made in concert with a [similar change to notification-utils](https://github.com/department-of-veterans-affairs/notification-utils/issues/117), which also depends on PyPDF2.

- [x] Discussed with QA

### User Story(ies)
**As a** stakeholder in VA Notify
**I want** to keep all dependencies up to date
**So that** the application remains secure

### Additional Info and Resources
- PyPDF [changelog regarding PyPDF2](https://pypdf.readthedocs.io/en/latest/meta/CHANGELOG.html#pypdf2-1-x)

## Engineering Checklist
_**Required**_

- [x] In requirements-app.txt (or Poetry), replace the `PyPDF2` requirement with `pypdf`.

## Acceptance Criteria

- [x] Containers build without error using pydf
- [x] All unit tests pass

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [x] regression passes in Perf
- [x] Close [twistlock](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1070) when this is merged to master.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1221?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by cris-oddball** [comment]
Updated to note that the only route using pypdf is `/v2/notifications/<notification_id>/pdf`.
Portal is not using that functionality.
There is a ticket #1178 to remove that route.

There will be no QA needed other than running a regression and closing the QA ticket.

**Comment by cris-oddball** [comment]
Deployed to perf on master, regression passes on Perf.
`132 passed, 2 skipped, 3 xfailed in 148.24s (0:02:28)`
