### ISSUE TITLE
BUG: Improper logging calls

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1222]
## Description

[notification-utils#111](https://github.com/department-of-veterans-affairs/notification-utils/issues/111) and [notification-utils#115](https://github.com/department-of-veterans-affairs/notification-utils/issues/115) exist to address logging errors.  However, the code in that repo seems to be working as intended by catching and logging exceptions caused by logging calls with message+arguments mismatches.

To clear those exceptions, other than not logging them, I made changes in the API code to ensure logging calls are not being made with more or less arguments than the logging string expects.  I will also use this ticket to bump the notification-utils version number for testing.

I will first test by making notification-api depend on the most recent commit of the notification-utils branch "logger-errors".  When that works, I will move to merge "logger-errors" to master and make notification-api depend on the latest notification-utils "master" branch commit (as it does now).

The error messages are of the format `failed to format log message: "'status_code'" not found`, where "status_code" is merely one instance.  Another common message value is "appSid".

## Steps to Reproduce

Search any AWS CloudWatch for any environment for "failed to format log message".

## Workaround
_Is there something we can do to work around this issue in the meantime? Leave blank if n/a._

## Impact/Urgency

This is causing many logging calls to fail and instead output an error.

## Expected Behavior

- [ ] We no longer see this error message in CloudWatch

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
_If applicable, include extra information to assist with troubleshooting, like screenshots, log snippets, links to applicable code files, and/or articles/websites that have relevant info on the issue. Leave blank if n/a._

**Comment by kalbfled** [comment]
Thus far, I have refactored and deleted the offending code in the logging.py file of notification-utils and, under this ticket, I have removed instances in notification-api of the use of the "format" string method in logging calls in files that contain the words "addSid" and "status_code", which are the most common contributors to KeyError exceptions recorded in CloudWatch.

**Comment by kalbfled** [comment]
@k-macmillan @tabinda-syed This ticket is also part of the logging fixes work.

**Comment by kalbfled** [comment]
@mjones-oddball @tabinda-syed I moved this ticket to "TO DO" because it exists to test other tickets already in "TO DO".

**Comment by mjones-oddball** [comment]
After speaking with Dave I added a blocker dependency on this ticket for 111 and 115 because those must be done in order to fully test this ticket.

**Comment by cris-oddball** [comment]
The last error message of this type was seen on Perf at about 12:40 pm MT, so not since the deploy to Perf.

[2023-05-08 18:49:42,333: ERROR/ForkPoolWorker-4] failed to format log message: "'payload'" not found

Going to pass this ticket and hopefully get the code to sit on staging a day prior to deploying to prod this weds as part of the out of cycle release.
