### ISSUE TITLE
BUG: Delivery Status Lambda Timing Out

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1237]
## Description
Single spike of 10 seconds while running the following lambda:

[project-prod-delivery-status-processor-lambda](https://us-gov-west-1.console.amazonaws-us-gov.com/lambda/home?region=us-gov-west-1#/functions/project-prod-delivery-status-processor-lambda?tab=monitoring)

In addition to the delay, the information is "lost" due to the timeout, though we can probably track it down in Twilio.

## Steps to Reproduce
This is the first time this has happened and it is suspected that it is related to AWS Quotas.

## Workaround
The timeout on the prod lambda has been increased to 1 minute because it is suspected to be a quota issue and so we can possibly capture where the issue happened.

## Impact/Urgency
Low urgency. This was a one-off incident. Normally it takes this method around 53 milliseconds to run. The impact is that delivery statuses are not being updated or sent through callbacks when this happens. The workaround should fix that though so we at least capture the failed to enqueue message.

## Expected Behavior
The lambda runs without timing out.

## Additional Info & Resources
04/25/2023 - 10 second delay in lambda - Suspected AWS quota issue.
Target group:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/bdd75cda-2008-477d-a6b4-02c9b30d2c32)

Lambda:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/93dbffac-ec55-43b9-8870-1fe20a965966)

Time of spike:
09:16 Eastern, 13:16 UTC

No additional information from the lambda:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/b73cee65-b894-437c-ab46-b18a7b5a8f99)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1237?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by npmartin-oddball** [comment]
Not needed anymore.
