### ISSUE TITLE
Create API documentation

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#124]
**As** a internal VA developer 
**I want** to access API documentation for VANotify 
**to** enable integration with VANotify 

**In scope:**
Documentation for endpoints currently in postman collection including:

Organization:
- [x] create
- [x] update
- [x] get

User:
- [x] create
- [x] update
- [x] get

Service:
- [x] create
- [x] update
- [x] get

Template:
- [x] create
- [x] update
- [x] get one template
- [x] get all templates

API Key:
- [x] create API Key
- [x] revoke API Key
- [x] get one API Key
- [x] get keys

Other:
- [x] send notification
- [x] get notification status
- [x] how JWT is generated
      - we need to make sure there is a way for consumers to interact with the API without knowing the secret

- [ ] ~Sync with team to consider if all endpoints listed above should be shared externally to other VA devs. "Process" chat seems to be needed.~ -> Discuss this during desk check.

**Notes:**
- format is Open API 
- No automatic updates to documentation
- We have Json Schema definitions for some of the endpoints. Consider using tooling that can convert Json Schema to Open Api

**Out of Scope:** 
- Publishing documentation somewhere where it can be accessed via Open API UI

**Comment by sarahproof** [comment]
Do we know how we want this documentation to be accessed? Would it be deployed with the app?

**Comment by lingtran** [comment]
Looking into resources: 
- https://pypi.org/project/jsonschema-to-openapi/
- https://github.com/openapi-contrib/json-schema-to-openapi-schema
- https://swagger.io/specification/

**Comment by saman-moshafi-va** [comment]
**notification-admin**:
NotifyAdminAPIClient sets service_id and api_key which are both read from the environment or configuration.  So for the majority of the calls from notification-admin to the notification-api use the values from config to generate JWT token.  The notification-admin check the permission of the logged user to ensure user does have permit to execute the command.

**Comment by saman-moshafi-va** [comment]
There is a CORS policy issue with running swagger editor on the web browsers. However, we can use postman to run the APIs.

**Comment by sarahproof** [comment]
- /v2/notifications/{notification_type} being combined instead of separate entries for email and sms makes it a little weird in a viewer
- /v2/notifications/email personalization field information is missing

**Comment by sarahproof** [comment]
- [ ] Response object isn't documented as being wrapped in "data" key
-- [ ] Create user
-- [ ] Update user
-- [ ] Create service
-- [ ] Update service
-- [ ] Create template
-- [ ] Update template
- [ ] Incorrect status code
-- [ ] Create template should be 201, not 200

**Comment by jsmithVA** [comment]
Reviewed the organisations endpoints with @sarahproof . Found issues documented here, with outstanding questions in pink:

https://docs.google.com/document/d/1cjSRUyXej9EKYJez_mdHg35ZOjLeXfD6U1XEPYeM2bw/edit?usp=sharing

**Comment by jsmithVA** [comment]
Reviewed the users endpoints. Found the following issues:

- [ ] for POST create and POST update user, state is listed as a boolean in the response but it is actually a string

- [ ] No error conditions are documented for POST create (ex. malformed request) or POST update (ex. user not found)

- [ ] The documentation says that e-mail address is only required when auth is set to email_auth, but it is required when it is set to sms_auth as well. Mobile number is only required when set to sms_auth.

- [ ] There is no documentation for a GET single user endpoint though it appears to work. It will also need error condition documentation.

- [ ] POST update user lists both email and mobile number as not nullable, but mobile number is nullable as long as auth is set to email_auth.

**Comment by jsmithVA** [comment]
Reviewed the services endpoints. Found the following issues:

- [ ] Need error code documentation (example: duplicate service name on POST create and POST update)

- [ ] GET all services and POST create service list whitelist as  an array with an object of arrays. But it returns as just an array

- [ ] GET single service endpoint exists but is not documented

- [ ] POST update service shows inbound_url as a url format but the API requires a uuid

**Comment by jsmithVA** [comment]
Reviewed template endpoints:

- [ ] Subject is required when type is email
