### ISSUE TITLE
SPIKE: Gunicorn, Celery Workers discovery 

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1240]
## User Story - Business Goal
We had an issue with our ECS services handling load when we added delivery receipt callbacks for the vetext service.  Our temporary solution for this issue was to double celery tasks.  

It's possible that changing how many gunicorn or celery workers are running would be a better solution but the team doesnt know enough about these two things to make the decision.  

This spike would be to discover how gunicorn and celery workers work and provide a "decision tree" for when to use one vs the other or both in combination. Setting up workers is generally considered an art, not science, so make sure this paints a full picture of what we can do.

### User Story(ies)
**As a** notify admin
**I want** know how best to manage gunicorn and celery workers to use for a service
**So that** when we encounter load on our services, we know how to best manage it

## Acceptance Criteria & Checklist
- [x] Technical Documentation has been created and linked in the glossary
- [ ] Learnings have been shared with the team, and decisions have been documented
- [x] Tickets for next steps have been identified and created

Completed research addresses the problems and/or answers the questions below:  
- [ ] When to increase/decrease gunicorn workers
  - [ ] Settings for gunicorn that may be beneficial
- [ ] When to increase/decrease celery workers 
  - [ ] Settings for celery workers that may be beneficial
- [ ] When to increase/decrease celery tasks

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1240?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by jakehova** [comment]
[Spike](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/Celery%20&%20Gunicorn.md)

There are tickets mentioned in the spike.  I will review with Kyle/the team during process improvement on if the tickets make sense or if this is complete.

**Comment by jakehova** [comment]
Created Tickets for next steps: 

https://github.com/department-of-veterans-affairs/notification-api/issues/1272

https://github.com/department-of-veterans-affairs/notification-api/issues/1273

https://github.com/department-of-veterans-affairs/notification-api/issues/1274

**Comment by mjones-oddball** [comment]
@jakehova is scheduling a meeting with the team, closing this ticket knowing that meeting will happen after he returns (OOO tomorrow and weds).

Some checkboxes are unchecked because more research is needed to get conclusive answers to open questions.
