### ISSUE TITLE
Regular Update for Dependencies

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1241]
## User Story - Business Need

We wish to keep dependencies up to date so we do not need such massive overhauls of our system. This will be a recurring ticket that will be done every sprint. We will update all dependencies we are able to. Any conflicts will get a ticket. This is intended to be a day of work at most because this is intended to update with only non-breaking changes.

- [x] Ticket is understood and QA has been contacted

### User Story
**As** VA Notify
**I want** to keep our service up to date
**So that** we are secure and as free of bugs as possible

### Additional Info and Resources
- Relevant section of [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-requirementstxt)

## Engineering Checklist
- [x] Update performed
- [x] Any conflicts removed and tickets created
- [x] Passes all tests locally
- [x] Passes userflows and QA Suite testing against Dev
- [x] Any major changes are investigated (compare existing to new version changes)
  - [x] Any questionable version changes are removed and a ticket is created
- [ ] Tickets created are added to the Epic for tracking purposes

## Acceptance Criteria
Repo dependencies are updated and we have no broken functionality. Tickets created for any updates we could, or should, not do.

## QA Considerations
- [x] Check to see if these updates cancel out any Twistlock issues
- [x] QA Regression tests pass after deploying this code.

**Comment by cris-oddball** [comment]
Please see if you can upgrade Flask to 2.3.2 to clear a Twistlock vulnerability so that I don't need to create a new Twistlock tocket.

**Comment by cris-oddball** [comment]
I ended up creating a [Twistlock ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/993) for Flask upgrade (which can be either 2.3.2 or an easier upgrade to 2.2.5, but would still be nice to get it done on this ticket.

**Comment by cris-oddball** [comment]
Flask was upgraded on June 7, ok to ignore above comment.

**Comment by cris-oddball** [comment]
@justaskdavidb2 As we just discussed, please post the list of the upgrades you plan to install in a comment.

If as you try to upgrade each item, you find any problems, as noted in the description, please open a new ticket for each problem.

**Comment by cris-oddball** [comment]
Code merged to master and deployed to Perf. Extensive testing to follow.

- [ ] Regression in Perf local
- [ ] Regression in Perf hosted
- [ ] Check cloudwatch logs especially for ssl issues
- [ ] Confirm that datadog is receiving data / loading metrics/ functions
- [ ] Confirm BQ is still receiving data as expected

**Comment by cris-oddball** [comment]
Need to let this simmer overnight for BQ.

@justaskdavidb2 did you create any tickets from this PR and add them to the appropriate epic? That checkbox is still unchecked in the description.

**Comment by kalbfled** [comment]
@justaskdavidb2 

PR 1325 is merged, but the issue is not adequately resolved.  I pulled the latest, built the app and test images locally, ran all unit tests, and encountered 5 failures:
```
=========================== short test summary info ============================
FAILED tests/app/oauth/test_rest.py::TestSsoCommon::test_redirects_to_ui_and_sets_token_in_cookie[authorize]
FAILED tests/app/oauth/test_rest.py::TestSsoCommon::test_redirects_to_ui_and_sets_token_in_cookie[callback]
FAILED tests/app/oauth/test_rest.py::TestAuthorizeWhenVaSsoToggleIsOff::test_should_redirect_to_ui_if_user_is_member_of_va_organization
FAILED tests/app/oauth/test_rest.py::TestRedeemToken::test_should_return_cookie_in_body
FAILED tests/app/oauth/test_rest.py::TestLogout::test_should_redirect_to_ui_and_clear_cookies
===== 5 failed, 3462 passed, 147 skipped, 35 xfailed in 160.75s (0:02:40) ======
Unit tests failed
```

Here is an example of the mode of failure:
```
[gw2] linux -- Python 3.8.16 /usr/local/bin/python

 self = <tests.app.oauth.test_rest.TestLogout object at 0x7f580dfbb250>
 client = <FlaskClient <Flask 'test'>>
 notify_db_session = <SQLAlchemy postgresql://postgres:LocalPassword@db:5432/test_notification_api_gw2>
 sample_user = <User 6e507de4-817a-4391-a00f-02513de4d458>
 mocker = <pytest_mock.plugin.MockerFixture object at 0x7f5806458400>

     def test_should_redirect_to_ui_and_clear_cookies(self, client, notify_db_session, sample_user, mocker):
         mocker.patch('app.oauth.rest.retrieve_match_or_create_user', return_value=sample_user)
         client.get('/auth/authorize')

 >       assert any(
             cookie.name == cookie_config['JWT_ACCESS_COOKIE_NAME']
             for cookie in client.cookie_jar
         )

tests/app/oauth/test_rest.py:625: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
.0 = <dict_valueiterator object at 0x7f580789da40>
 >   assert any(
         cookie.name == cookie_config['JWT_ACCESS_COOKIE_NAME']
|         for cookie in client.cookie_jar
|     )
E   AttributeError: 'Cookie' object has no attribute 'name'

tests/app/oauth/test_rest.py:625: AttributeError
```

We earlier identified this AttributeError as caused by upgrading flask-jwt-extended to a version newer than 4.4.4 and attempted to remediate the problem by changing the specification in requirements-app.txt from `flask-jwt-extended>=4.4.4` to `flask-jwt-extended~=4.4.4`.  This seems to have worked as intended, but the "Cookie" class does not seem to be part of that package.

With the app running locally, I ran `docker exec -it ci_app_1 sh`.  Inside the container, I ran `pip show flask-jwt-extended`, and the installed version is 4.4.4.

**Comment by cris-oddball** [comment]
Dave and David to work together tonight to setp-by-step through this on a new branch to determine what exactly is causing those test failures. Plan is to get a new PR up by the cutoff tomorrow (or we revert).

**Comment by cris-oddball** [comment]
PR open to revert the original PR. Dave has a new PR up to follow with the updated changes.

**Comment by cris-oddball** [comment]
Code merged to master and deployed to Perf. Extensive testing to follow.

- [ ] Regression in Perf local
- [ ] Regression in Perf hosted
- [ ] Check cloudwatch logs especially for ssl issues
- [ ] Confirm that datadog is receiving data / loading metrics/ functions
- [ ] Confirm BQ is still receiving data as expected
- [ ] Removed exception for Requests in Twistlock and scan is clean
- [ ] Removed exception for cryptography in Twistlock and scan is clean

**Comment by cris-oddball** [comment]
Looks good! Closing ticket.
