### ISSUE TITLE
BUG: Certificate verification failing for user-flows

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1242]
## Description

- [x] Discuss this with QA.

After updated the certificate for dev.api.notifications.va.gov for [vanotify-infra 536](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/536),  we are getting a lot of SSLError failures in the user-flows code, which causes that step to fail in Actions.  The root cause is that the new certificate has a different CA chain (VA-Internal-ICA11 <-- VA-Internal-RCA2).  The required CA certs are in the certs/ folder, which is why the API still works, but the user-flows lambda is packed with a [separate pem file](https://github.com/department-of-veterans-affairs/notification-api/blob/master/lambda_functions/user_flows/va-internal-cert-chain.pem) that is now outdated.

## Steps to Reproduce

- Deploy any branch, and observe the user-flows failure.

## Workaround

None, although this doesn't prevent testing API changes in Dev because the code still gets deployed to AWS before the user-flows failure.

## Impact/Urgency

This is a hard stop, which is why we have not continued updating certificates beyond the Dev environment.

## Expected Behavior

- [x] Build user-flows with the certificates in certs/.  Discontinue using the separate pem file.
- [x] Deploying a branch succeeds without user-flows failures.
- [x] Update the [documentation about updating certificates](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/updating_certificates.md).

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [ ] Double-check User flows

## Additional Info & Resources
_If applicable, include extra information to assist with troubleshooting, like screenshots, log snippets, links to applicable code files, and/or articles/websites that have relevant info on the issue. Leave blank if n/a._

**Comment by cris-oddball** [comment]
@kalbfled please point this ticket prior to closing, ty!

**Comment by cris-oddball** [comment]
Code for fix to user flows approved and merged to master, deployed to perf.

**Comment by cris-oddball** [comment]
Perf - no regressions
`90 passed, 1 xfailed in 118.74s (0:01:58)`

**Comment by cris-oddball** [comment]
Documentation reviewed - looking good!
