### ISSUE TITLE
[DB] Explicit Logic - Add Default Send Field to Communication Items Table

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1252]
## User Story - Business Need
_**Required.** Please note you can have more than one story if applicable. If this is technical work achieving a larger initiative, the user story should represent that piece of the initiative, so it’s clear what problem we are solving._

### User Story(ies)
**As** the VA Notify platform
**I want** the ability to set the default sending logic for communication items
**So that** we can control whether or not to send by default or require explicit permission to send notifications to a veteran.

### Additional Info and Resources
- This is a follow-up to the Explicit Preferences spike that generated this [document](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/explicit_preference_logic.md). It explains the current permissions flow and should be updated during the completion of this ticket.

## Engineering Checklist
_**Required**_

- [x] Add a boolean type field to the `communication_items` table for "default_send_indicator"  in the appropriate `model` file
    - Model and Migration should show: default send (default_send_indicator = True) should be the default value for communication items
    - NULL is not a valid response, only True/False
- [x] Migration only contains the necessary changes
- [x] Document the process and include in the [Glossary](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/Glossary.md)
    - This should be generic, if you were explaining how to make a change to the database to a peer what are the steps you follow (in order) to complete it successfully, e.g. changes to models.py
- [x] Unit tests have been updated

## Acceptance Criteria
_**Required**_

- [x] The `communication_items` table now contains a new boolean field called "default_send_indicator", default value true
- [x] After the migration, existing communication_items in the database should all have the default value, true
    - [x] Dev
    - [x] Perf
- [x] An engineer could follow the documentation provided for a new database change ticket with minimal questions

## QA Considerations
Just noting that this new column will be validated on [API-1253](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1253)

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1252?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @k-macmillan @kalbfled @ldraney @justaskdavidb2

**Comment by tabinda-syed** [comment]
If unit tests begin to get us past a "3" on this, let's have a team discussion.
Whoever works on this, please pay attention to what goes into the unit tests.

**Comment by kalbfled** [comment]
I merged the changes for this ticket.  I still need to write the prescribed documentation.

**Comment by kalbfled** [comment]
[Here](https://github.com/department-of-veterans-affairs/vanotify-team/pull/974) is the new documentation I created.
