### ISSUE TITLE
Explicit Logic - Communication-Item Route Additions and Postman Collection Updates

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1253]
### User Story(ies)
**As** the VA Notify platform
**I want** the ability to set the default sending logic for communication items
**So that** we can control whether or not to send by default or require explicit permission to send notifications to a veteran.

### Additional Info and Resources
- This is a follow-up to the Explicit Preferences spike that generated this [document](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/explicit_preference_logic.md). It explains the current permissions flow and should be updated during the completion of this ticket.

Fields for communication-items:
- "id": autogenerated uuid
- "name": string, required, minLen 1 (cannot be empty string), not nullable, unique
- "va_profile_item_id": integer, required, min 1 (cannot be 0 or a negative number), not nullable, unique
- "default_send_indicator": bool, default value true, not nullable
---
- [x] Discuss ticket with QA upon picking up and understanding ticket, QA will need to update the automation suite so this communication is critical.

## Engineering Checklist
_**Required**_

Checklist:
- [x] Add new route methods for the following:
    - [x] Read GET communication item BY ID
    - [x] Create POST new communication item
    - [x] Update PATCH an existing communication item BY ID
    - [x] Delete DEL a communication item BY ID
- [x] Add the new `default_send_indicator` field that was added in ticket [#1252](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1252) as output with getting the `/communication-item` endpoint (existing route) --> already completed for #1252 
- [x] Appropriate error cases and messaging are defined for each route
- [x] Appropriate success code and returned response bodies are defined for each route
- [x] Update Postman to add the new routes and update the existing route for communication-item
- [x] Add and update Unit tests

## Acceptance Criteria
_**Required**_

- General Requirements
- Client must have the admin notification-client-secret in order to generate a JWT to exercise the routes    
    - Postman is able to send all methods for the route and obtain responses (see route specifics)
    - Error messages are standard in the same form as POST /service/{service_id}/api-key error responses (see swagger, not the code, since the code for that route is wrong but the swagger is good))

- Create a new communication-item
	- POST {{notification-api-url}}/communication-item
	- "id" is an auto-generated UUID when the object is inserted into the DB
	- payload:	
    	- "name": string, required, minLen 1, not nullable, cannot be a duplicate
    	- "va_profile_item_id": integer, required, min 1, not nullable, cannot be a duplicate
    	- "default_send_indicator": bool, default value true, not nullable, optional
    - 201 response is the object, with all 4 properties visible
   ```
   {
            "id": "df6457be-97c4-4ce3-9413-ebcb68a2dc56",
            "name": "Board of Veterans' Appeals hearing reminder",
            "va_profile_item_id": 1
            "default_send_indicator": true
        }
   ```
   	- Postman contains the route, the required properties, and the pre-request script

- Update an existing communication-item by ID
	- PATCH {{notification-api-url}}/communication-item/{{communication-item-id}}
	- properties that can be updated:	
    	- "name": string, minLength 1, not nullable, cannot be a duplicate
    	- "va_profile_item_id": integer, min 1, not nullable, cannot be a duplicate
    	- "default_send_indicator": bool, not nullable
    - 200 response is either in the form of nested data object or just the updated object, with all 4 fields visible (see Create response)
   	- Postman contains the route, three example properties, and the pre-request script
   	
- Read ALL communication-item  
	- GET  {{notification-api-url}}/communication-item/
	- 200 response is nested list with top-level property "data" as a list
	- each object in the 200 response has all four properties (see Create response)
	- Postman contains the route and the pre-request script

- Read BY ID communication-item
	- GET  {{notification-api-url}}/communication-item/{{communication-item-id}}
	- 200 response is the object containing all four properties (see Create response)
	- Postman contains the route and the pre-request script	

- Delete BY ID communication-item
	- DEL {{notification-api-url}}/communication-item/{{communication-item-id}}
    - object is removed from DB
	- 202 response is an OK
	- Postman contains the route and the pre-request script	
	- GET ALL and GET by ID no longer return this object

## QA Considerations
- [x] tests are added to the GET route to check for the new property `default_send_indicator`
- [x] tests are added for the GET BY ID route
- [x] tests are added for the new POST/PATCH create/update routes
- [x] tests are added for the new DEL route
- [x] verify that Postman update is correct

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1253?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by tabinda-syed** [comment]
Team Expectation: Whoever picks up this ticket, please be in close communication with Cris throughout the course of this ticket. This ticket requires a lot of QA effort.

**Comment by mjones-oddball** [comment]
@cris-oddball can you update the AC section when you get a chance to remove swagger specific stuff since we moved that into a different ticket?

**Comment by cris-oddball** [comment]
@mjones-oddball done, ty!

**Comment by cris-oddball** [comment]
```
{
  "errors": [
    {
      "error": "ValidationError",
      "message": "personalisation [] is not of type object"
    }
  ],
  "status_code": 400
}
```

**Comment by cris-oddball** [comment]
@kalbfled when you get a chance, this [Draft PR's description](https://github.com/department-of-veterans-affairs/notification-api-qa/pull/83) lists the tests that I'll be adding to the QA Suite, let me know if you see any issues (the code is not yet ready for primetime, but the description should be).

**Comment by cris-oddball** [comment]
Testing in DEV.

@kalbfled 
Test Failure for a 404 on delete an invalid communication item ID: API returned a 200 and {}, it should return a 404 and an error to the effect that the requested ID could not be found.

**Comment by cris-oddball** [comment]
@kalbfled 

GET by ID with an invalid communication_item_id should return a 404 and a message that includes that the thing was not found, instead the route returns a 404 and an empty object.

**Comment by kalbfled** [comment]
I made changes to address Cris's feedback and redeployed to Dev.

**Comment by cris-oddball** [comment]
Above issues resolved, one last issue @kalbfled 

The error for deleting an invalid communication item could be more clear. Presently it is:
```
{
    "errors": [
        {
            "error": "NotFound",
            "message": "Communication item 9bec2fbf-c7cc-4ade-97cf-c5ccac874bfb was not deleted."
        }
    ]
}
```

The error implies that there may be other reasons this ID was not deleted.
The error for the GET route seems more clear and could be re-used here
```
{
    "errors": [
        {
            "error": "NotFound",
            "message": "Communication item 836eb1d6-ca9a-44f2-9db2-ff7c2be448f7 does not exist."
        }
    ]
}
```

**Comment by kalbfled** [comment]
I changed the DELETE error message to match the GET error message.

**Comment by cris-oddball** [comment]
Merged to master.
Deployed to Perf
All original tests pass: `91 passed, 32 deselected, 1 xfailed in 110.33s (0:01:50)`
All new tests pass: `32 passed in 15.01s`

QA PASSES - just awaiting another approval on the QA PR and then I can close this ticket.

**Comment by cris-oddball** [comment]
I have two approvals on the QA code, will defer merging them until the code is on staging. Closing ticket.
