### ISSUE TITLE
Implement LGTM to secure VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#126]
As a developer I want to utilize LGTM to identify any security related concerns   

**Acceptance Criteria:**

*1. No security related concerns*
Given I am deploying VANotify 
When I run the pipeline
Then the job successfully completes 

*2. Security related concerns identified*
Given I am deploying VANotify 
When I run the pipeline
Then the job fails along with displaying the security related concern(/s)

**Notes:**
- 

**Assumptions:** 
- This involves completing the work identified after the Spike #99 is complete
- One card will be created for each tool that we add
- Please review the respective ADR for detailed information  
- During Dev Analysis we need to list what specific security function is covered 
- Ling's matrix and recommendations documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1wmWVBbnpzYUcEiNc3lQjwNUhOhxSQtB-WZTc3dDUyKI/edit#gid=0) 
- Discuss where in the pipeline we want to put these security checks, example: is it called from Terraform (this must be finalized in Dev Analysis)
- After Dev Analysis or as a part of the kickoff this card will be estimated 
- Rules used for scanning can be adjusted as part of the implementation 

**Out of Scope:**
- Adding monitoring and alerts for this is not in scope 
- When the tool is successfully implemented, this information must be provided for documentation in the ATO. This will be a separate task not in scope for this card

**Comment by mjones-oddball** [comment]
We'll do a security assessment and create additional tickets as needed.
