### ISSUE TITLE
BUG: Logging Incorrect Item

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1260]
## Description
The logger is logging the object rather than the ID.
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/80db6732-2da1-49ea-b106-b5613eeebe52)

## Steps to Reproduce
Send a notification

## Workaround
This does not require a workaround.

## Impact/Urgency
Has no impact, the notification id is still there and the urgency is Low. 

## Expected Behavior
It just logs the notification id

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
[Code location](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/provider_details/provider_service.py#L59)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/5e8c54bb-fb9e-4a56-ac0b-27f969fc4ae7)

**Comment by npmartin-oddball** [comment]
Closing.
