### ISSUE TITLE
BUG: BigQuery - Unable to Import Module

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1261]
## Description
_**Required.** Describe the problem._
Our BigQuery integration has been failing since 5/5.

Timeline:
- Beverly messaged Melanie on 5/8/23 to ask why Domo was showing 5/3 as the latest date in our statistics dashboard. Please note, this dashboard is client-facing. The date for Domo comes from BigQuery and Google Analytics. This particular data issue stems from BigQuery data.
- Melanie asked Kyle to query the production database to confirm notifications having been sending since 5/3. 
    - Kyle confirmed notifications are sending as expected.
- Upon checking cloudwatch log group "/aws/lambda/project-prod-nightly-stats-bigquery-upload-lambda", Melanie found the following error:
```
[ERROR] Runtime.ImportModuleError: Unable to import module 'nightly_stats_bigquery_upload_lambda': urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2k-fips  26 Jan 2017. See: https://github.com/urllib3/urllib3/issues/2168
Traceback (most recent call last):
```
- Kyle found a link to a similar issue, different library but seemingly the same issue: https://github.com/psf/requests/issues/6432
## Steps to Reproduce
_**Required.** Provide information on what steps you are aware of that produce this undesired outcome.._

- Navigate to VA.gov VANotify KPIs dashboard in Domo https://va-gov.domo.com/page/2040841289
- Note that the end date says 5/3 (by default, this will always show the most recent end date for the data present in Domo)
    - ![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/77e41f19-5803-4731-9c8a-dafe1cbf676f)
- Go to [BigQuery](https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1&ws=!1m0) to check if there's any data present after 5/3 (if there was data present after that time, I would have raised the issue with a platform analytics ticket since they manages Domo)
```sql
SELECT * FROM `vsp-analytics-and-insights.platform_vanotify.prod-statistics`
WHERE date > "2023-05-03";
SELECT * FROM `vsp-analytics-and-insights.platform_vanotify.prod-billing`
WHERE date > "2023-05-03";
```
- See that no data is returned in either table (nightly stats nor billing)
- Query our production database to check the notification data and confirm data actually exists for this time period
    - Confirmed data is present, which means it should have been sent to BigQuery during the nightly import
-  Check [Cloudwatch ](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fproject-prod-nightly-stats-bigquery-upload-lambda/log-events$3Fstart$3D1683172800000$26end$3D1683604799000$26filterPattern$3D$2522ERROR$2522) to look for errors in the nightly process, I went to "/aws/lambda/project-prod-nightly-stats-bigquery-upload-lambda" and looked for the word "ERROR" between 5/4 and 5/8.
-  ![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/cbf9d28e-baf6-4aa3-aade-ccc6524f96d4)

## Workaround
_Is there something we can do to work around this issue in the meantime? Leave blank if n/a._
We offer very basic stats in SSUI (total triggered, successful, failed in last 7 days, 30 days, and alltime) but this doesn't really replicate what clients need and look for in Domo. Otherwise we would need to provide manual stats to clients (which hopefully won't be necessary).

## Impact/Urgency
_**Required.** Describe the impact this bug has on our system, clients, and/or team._

- High impact and urgency. This is a production issue that impacts our clients' ability to manage their notifications and report outcomes to stakeholders. This also impacts our billing data, which must be accurate if we are going to use BigQuery to build monthly reports for Franchise Fund.

## Expected Behavior
_**Required.** Describe the desired outcome if this were functioning as expected. Include a checklist if applicable._

- [x] Analytics data automatically populates nightly for nightly stats and billing data
- [x] Missing data is retroactively corrected
- [x] New incident report has been added to the[ running document](https://github.com/department-of-veterans-affairs/vanotify-team/tree/master/Incidents)
- [x] New ticket(s) have been created to address alerting our team to future issues

Overview of expectations:
- Domo and BigQuery should show all available data up to "yesterday's date" (it's always 1 day behind because it's a nightly process).
    - Domo will automatically refresh data daily, so there shouldn't be any work on that end
    - We need BigQuery to be re-populated from 5/4 on. Please note, our integration code only refreshes the last 4 days each time it runs, so we need to find a way to replace what was missed and is out of that range.
- Our team should be proactively alerted to hard failures like these. Beverly only stumbled upon this data discrepancy by accident and reported it to the team. This ticket doesn't need to solve it, but we should create whatever is needed to do so in a future ticket(s).

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
_If applicable, include extra information to assist with troubleshooting, like screenshots, log snippets, links to applicable code files, and/or articles/websites that have relevant info on the issue. Leave blank if n/a._

Info on the BigQuery integration: https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/BigQuery/Nightly_Stats_Documentation.md

**Comment by k-macmillan** [comment]
Updated the requirements file to use urllib3 1.26.15. 
Tested in the console, no issues.
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/3867508e-ca7b-4b14-a13a-c569c39ab1d3)

**Comment by k-macmillan** [comment]
Dev was not seeing SSL issues. We do not know why. Attempted to redeploy perf to see if perhaps the lambda had been updated in dev because we regularly deploy but perf/staging/prod only rare get deploys. No change, still failing on perf. Deployed urllib3 pin to 1.26.15 in perf and these are the results:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/1bfda3d8-cbf7-4524-9d33-ea405d413019)

This resolves the issue. We should attempt to pull the pin out every time we update big query. PR is up, letting it sit overnight though so we can verify it E2E in perf.

**Comment by k-macmillan** [comment]
Overnight runs (automated) ran without issue last night:
Billing:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/53a1107d-8b1a-4a4f-8c6d-28d8625f2fb4)

Stats:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/97caa264-b12c-4a23-944a-af9bb6f7d4bb)

**Comment by cris-oddball** [comment]
This went to perf for testing, as shown above, Perf has data. Logs are clean.
