### ISSUE TITLE
Explicit Logic - Communication-item API Doc Updates

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1268]
### User Story(ies)
As a business line
I want my recipient to expressly opt in to receive my notifications
So that I'm only notifying those who ask to be notified

As a VA Notify engineer/QA
I want to understand the capabilities and limitations of the API
So that I can manage communication items via the API

### Additional Info and Resources
- https://github.com/department-of-veterans-affairs/notification-api/tree/master/documents/openapi
- Related tickets: #1253, #1252, #1227
---
- [x] Talk to QA when picking up ticket, they may collaborate on this work with you to create a standard example

## Engineering Checklist
_**Required**_

- [x] Update existing communication-item GET {{notification-api-url}}/communication-item
    - [x] Must include new optional, boolean field "default_send_indicator"
    - [x] Should include all response options, 201, 400, 401, 403, 404, 500 with example values for each
- [x] Add new communication-item routes with applicable assets for each
    - [x] Read - GET {{notification-api-url}}/communication-item by id
    - [x] Update - PATCH {{notification-api-url}}/communication-item/{{communication-item-id}}
    - [x] Create - POST {{notification-api-url}}/communication-item
    - [x] Delete - DEL {{notification-api-url}}/communication-item/{{communication-item-id}}

## Acceptance Criteria
_**Required**_

### API Documentation

Within the documentation I can understand how to:
- Create a new communication item
- Update an existing communication item
- Delete an existing communication item
- Read a list of existing communication items
- Read a single existing communication item

Per endpoint:
- Any applicable parameters are documented
- Request body examples are present
- Required fields are indicated
- Response codes are documented for 201, 400, 401, 403, 404, 500 with example values for each

### Endpoint AC details are below for reference

Create a new communication-item

POST {{notification-api-url}}/communication-item
"id" is an auto-generated UUID when the object is inserted into the DB
payload:
"name": string, required, minLen 1, not nullable, cannot be a duplicate
"va_profile_item_id": integer, required, min 1, not nullable, cannot be a duplicate
"default_send_indicator": bool, default value true, not nullable, optional
201 response is the object, with all 4 properties visible
{
         "id": "df6457be-97c4-4ce3-9413-ebcb68a2dc56",
         "name": "Board of Veterans' Appeals hearing reminder",
         "va_profile_item_id": 1
         "default_send_indicator": true
     }
Swagger contains 201, 400, 401, 403, 404, 500 responses
Update an existing communication-item by ID

POST {{notification-api-url}}/communication-item/{{communication-item-id}}
properties that can be updated:
"name": string, minLength 1, not nullable, cannot be a duplicate
"va_profile_item_id": integer, min 1, not nullable, cannot be a duplicate
"default_send_indicator": bool, not nullable
200 response is either in the form of nested data object or just the updated object, with all 4 fields visible (see Create response)
Swagger contains 200, 400, 401, 403, 404, 500 responses
Read ALL communication-item

GET {{notification-api-url}}/communication-item/
200 response is nested list with top-level property "data" as a list
each object in the 200 response has all four properties (see Create response)
Swagger contains 200, 401. 403, 404, 500 (see GET /service/{service_id}/api-keys for examples)
Read BY ID communication-item

GET {{notification-api-url}}/communication-item/{{communication-item-id}}
200 response is the object containing all four properties (see Create response)
Swagger contains 200, 401. 403, 404, 500 (see GET /service/{service_id}/api-keys/{{api_key_id}} for examples)
Delete BY ID communication-item

DEL {{notification-api-url}}/communication-item/{{communication-item-id}}
object is removed from DB
202 response is an OK
Swagger contains 202, 401. 403, 404, 500 response (see POST /service/{service_id}/api-keys/{{api_key_id}} for examples)
GET ALL and GET by ID no longer return this object

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

This may be handled before the endpoints and postman are created/fully functional

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1268?planning-poker) with Zenhub @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by kalbfled** [comment]
Useful:

https://editor-next.swagger.io/

https://spec.openapis.org/oas/latest.html

**Comment by cris-oddball** [comment]
Merged to master, reviewed document in SwaggerEditor and it looks as expected. Closing ticket.
