### ISSUE TITLE
Implement Twistlock to secure VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#127]
As a developer I want to utilize Twistlock to identify any security related concerns   

**Acceptance Criteria:**

*1. No security related concerns*
Given I am deploying VANotify 
When I run the pipeline
Then the job successfully completes 

*2. Security related concerns identified*
Given I am deploying VANotify 
When I run the pipeline
Then the job fails along with displaying the security related concern(/s)

**Checklist:**
- [ ] Kickstart process with Andy Zimmerman (w/AbleVets, a Workspace Admin), can do via Slack or email
    - Slack username: '@Andy Zimmerman'
    - Slack workspace: VA OIT DevOps
    - email: andrew.zimmerman3@va.gov
- [ ] Implement twistcli to scan Docker image for vulnerabilities in pipeline
    - [twistcli](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/tools/twistcli.html)
    - [Scan images with twistcli](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/tools/twistcli_scan_images)
- [ ] Implement Prisma Cloud Github IaC Github app - check if this can scan infra code? <-- is this something we're interested in having?
    - [Use the Prisma Cloud App for Github](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/prisma-cloud-devops-security/use-the-prisma-cloud-app-for-github.html)
- [ ] Share info about Prisma Cloud plugins for IDEs (IntelliJ and Visual Studio Code) with team
- Additional resources listed in comments below

**Assumptions:** 
- This involves completing the work identified after the Spike #99 is complete
- One card will be created for each tool that we add
- Please review the respective ADR for detailed information  
- During Dev Analysis we need to list what specific security function is covered 
- Ling's matrix and recommendations documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1wmWVBbnpzYUcEiNc3lQjwNUhOhxSQtB-WZTc3dDUyKI/edit#gid=0) 
- Discuss where in the pipeline we want to put these security checks, example: is it called from Terraform (this must be finalized in Dev Analysis)
- After Dev Analysis or as a part of the kickoff this card will be estimated 
- Rules used for scanning can be adjusted as part of the implementation 

**Out of Scope:**
- Adding monitoring and alerts for this is not in scope 
- When the tool is successfully implemented, this information must be provided for documentation in the ATO. This will be a separate task not in scope for this card

**Questions:**
-  How to procure licenses? Talk to DOTS (Allison Schulhof)
-  Figure out process for setup
-  Explore if there is a 'trial' we can use
-  Find DOTS resources, including training videos

**Comment by lingtran** [comment]
**Today:**
Reached out to Allison Schulhof for information, who is currently on vacation.

Watching overview and demo video of DOTS DevSecOps (will find link to attach). **Notes:**
- Need to create a Jira ticket with DOTS
- From 17:19 to 19:01 in video, can see what Twistlock instance in pipeline can look like and its produced artifacts (aka image vulnerabilities). Twistlock also offers its own UI that team can access to get the same reported information and more details.
- From 35:50 to 38:50, demos twistcli (Twistlock's cli tool) `twistcli images scan <Docker image id> --address <Twistlock url> --password <Twistlock password> --ci` (returns a json object) to post vulnerabilities scan overview results to Twistlock UI console
- From 38:50 to 39:30, demos Twistlock UI console
- From 39:34 , to look at Twistlock console from Ops perspective. Can create vulnerability rules (including severity, alert and block thresholds, scope, etc).

**Comment by lingtran** [comment]
**From conversation today (9/14/20) with Andy Zimmerman (contractor from AbleVets)**
Overall process first provisioned by DOTS/AbleVets, who in the VAEC create a child console  and assign admin users. Admin users can self-service users management onwards.

Questions to get back to Andy to kickstart the provisioning process:
How many instances we have as that will determine the number of licenses
-- how Docker is being used?
Does team have any appetite to have a footprint in Jenkins?
What to call our namespace?
Who are the admin users to provision for?

Build-time analysis unknown for Github actions
Jenkins plugin

Common use case: native Kubernetes, OpenShift, Rancher(?) - anything that can let you deploy replica sets. So they are not aware of folks using Github actions with Twistlock. It would be great if ThoughtWorks can share snippets of any scripts we write. This also means production may or may not be able to support the Twistlock agent due to Github actions. Not sure how well Twistlock works with Github actions workflow. There is a Jenkins community plugin most folks use, which may or may not be available 

We will definitely have access to twistcli at the very least, which we can use through Github scripts

**Comment by lingtran** [comment]
Github Marketplace app: Prisma Cloud IaC (Infrastructure-as-Code scan):
- https://github.com/marketplace/prisma-cloud
- about IaC with respect to Terraform: https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/prisma-cloud-devops-security/set-up-your-prisma-cloud-configuration-file-for-iac-scan.html#id3fa84acb-db42-46ab-a3bc-d19e7589c47e

Prisma Cloud plugins for Github, Visual Studio Code, IntelliJ:
- https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/prisma-cloud-devops-security/prisma-cloud-plugins.html#idf361c24b-71ca-48f5-bf7d-4b50fc94cb30

**Comment by lingtran** [comment]
Reached out to Andy Zimmerman to kickstart the process on Wednesday, Sept. 16, 2020.

**Comment by lingtran** [comment]
After clarifying conversation with Andy Zimmerman today - verified that we are only operating within the VAEC environment, such as pushing to the ECR there - looks good to go. Andy will be starting work next week on getting our licenses and VANotify team console. Brian Lang will be pulled in to help with the work as well. Overall process should take about a week to complete upon starting.

**Comment by anushyaprasad** [comment]
Stand up update; licenses for twist lock acquired @lingtran

**Comment by lingtran** [comment]
Devs with VA network access should be receiving credentials today, via Slack update from Andy Zimmerman.

**Comment by lingtran** [comment]
confirmed with Andy that we are considered set up. someone with access needs to see (1) if they can add new members, and (2) check if there is any additional documentation available in the console. 

regarding why no SSO at the moment, Andy's response:
```
We have been working with TL for almost a year on a better log in experience.  They actually just released the feature we requested which federates  TL to GitHub.  This should provide something that both partitions sub-projects and provides SSO.
```
