### ISSUE TITLE
Implement Celery Serverhooks

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#1277]
## User Story - Business Need
Celery provides [event hooks](https://docs.celeryq.dev/en/stable/userguide/signals.html) to provide insight into how workers are being used.

We need insight into the lifetime of workers so that we can properly forecast how many workers we actually need to handle X amt of tasks.

Having a better of idea of how the Celery workers are being utilized will help us make the proper decisions with respect to how to scale the number of workers.

To implement this ticket, create an CeleryEvent class that handles implementation of the signals events: 
```
from celery.signals import task_received, task_succeeded, task_failed

class CeleryEventLogger():

    def __init__(self, worker, **options):
        self.worker = worker

    def start(self, worker):
        task_received.connect(self.task_received)
        task_succeeded.connect(self.task_succeeded)
        task_failed.connect(self.task_failed)

    def stop(self, worker):
        task_received.disconnect(self.task_received)
        task_succeeded.disconnect(self.task_succeeded)
        task_failed.disconnect(self.task_failed)

    def task_received(self, sender=None, headers=None, body=None, **kwargs):
        print(f'Celery Task received: {headers["id"]} ({headers["task"]}) ')

    def task_succeeded(self, sender=None, result=None, **kwargs):
        print(f'Celery Task succeeded: {sender.request.id} ({sender.request.task}) ')

    def task_failed(self, sender=None, task_id=None, exception=None, args=None, kwargs=None, traceback=None, einfo=None, **kw):
        print(f'Celery Task failed with an exception.  Task information: {task_id} ({sender.request.task}) Exception: {exception}')

```

Next, update the celery config (app/config.py => Celery_Settings) telling it to use the CeleryEventLogger: 
```
worker_bootsteps = [EventLogger]
```

### User Story(ies)
**As a** Notify Developer
**I want** I want check the cloudwatch logs for when Celery is starting/killing workers
**So that** I know how Celery is handling load

### Additional Info and Resources
- [ ] discuss with QA

## Engineering Checklist
- [ ] Implement task_received celery hook
- [ ] Implement task_succeeded celery hook
- [ ] Implement task_failed celery hook

##  OLD Acceptance Criteria
- verify task_received celery hook logs are present in cloudwatch
- verify task_succeeded celery hook logs are present in cloudwatch
- verify task_failed celery hook logs are present in cloudwatch

##  NEW Acceptance Criteria

- [x] verify "celery task success" including elapsed time in seconds is present in cloudwatch
- [x] verify "celery task failure" including elapsed time in seconds is present in cloudwatch

## QA Considerations
- [x] regression passes
- [x] above AC is verified in Perf

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1277?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by EvanParish** [comment]
Added the suggested code, though I used tags as Kyle suggested in his comment instead of the class suggested by Jacob. I saw messages coming through in the logs. I will get the messages updated to something useful, but here's the proof that they are working.
![image.png](https://images.zenhubusercontent.com/6261b52f248e574e9270992b/bfaf28fd-4bce-4df9-918e-a2c4a8377b04)

**Comment by EvanParish** [comment]
After discussing with Kyle and Jacob, we are just trying to find the time these tasks are taking, which is already included in the logs. I will just be standardizing the format of the output for success and failure, then sharing with the team how to search for these in cloudwatch.

We can now search for "celery task success" or "celery task failure" to find these logs. They also now both include the elapsed time.

**Comment by cris-oddball** [comment]
Deployed to Perf.

**Comment by cris-oddball** [comment]
Perf regression passed 90 passed: 1 xfailed in 114.99s (0:01:54)

New logs are showing up:
```
[2023-05-23 22:27:00,141: INFO/ForkPoolWorker-4] celery task success: check-job-status took 0.0500 seconds
```
and

```
[2023-05-23 22:27:18,625: INFO/ForkPoolWorker-4] celery task success: lookup-contact-info-tasks took 0.5392 seconds
```

Need to discuss testing failures to reproduce the message Evan posted above. I tried VAPROFILEID 123 & 555555, but received this
```
[2023-05-23 22:31:54,987: WARNING/ForkPoolWorker-4] NoContactInfoException - No telephones in response for VA Profile ID 123 with AuditId f180e4aa-f03c-4b50-bb89-699768514f2c: Can't proceed after querying VA Profile for contact information for a8ab1dcc-bae3-4915-96f0-350d37684c50. Stopping execution of following tasks. Notification has been updated to permanent-failure.

[2023-05-23 22:31:54,998: INFO/ForkPoolWorker-4] celery task success: lookup-contact-info-tasks took 0.2771 seconds

[2023-05-23 22:31:54,998: INFO/ForkPoolWorker-4] Task lookup-contact-info-tasks[14150ff9-917c-42ec-9d1f-f892264a334b] succeeded in 0.27713395000000673s: None
```

Seems like duplicate logs there but also need to know how to get the failure message. Will touch base with @EvanParish in the morning.

**Comment by cris-oddball** [comment]
Was able to replicate the celery task failure message by sending the VAPROFILE recipient identifier as a string of letters rather than numbers

```
[2023-05-24 13:08:02,561: ERROR/ForkPoolWorker-4] celery task failure: lookup-contact-info-tasks took 0.2897 seconds
```

This passes the AC, Evan is going to look at the code for the near-duplicate error.

**Comment by cris-oddball** [comment]
The near-duplicate may be coming from celery itself. Not going to investigate any farther.
