### ISSUE TITLE
Implement Dependabot to secure VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#128]
As a developer I want to utilize Dependabot to automatically manage how up-to-date our dependencies are.

# Acceptance Criteria

*1. No security related concerns*
**Given** all dependencies are up-to-date
**Then** Dependabot does **not** create a new pull request

*2. Security related concerns identified*
**Given** a dependency is out of data
**Then** Dependabot creates a pull request to update it

*3. Updating dependencies*
**Given** Dependabot created a pull request
**When** a developer accepts the PR
**Then** the PR merges to master seamlessly
**And** the pipeline still runs successfully

# Checklist
- [x] Configure Dependabot v2 with all checks on weekly basis
- [x] Dependabot checks dependencies (using pip) in all requirements files
- [x] Dependabot checks dependencies for docker (if checking base image version -> yes, this is what it checks)
- [x] Dependabot checks version updates for github actions
- [x] Add to notification-api
- [x] Add to notification-utils
- [x] Add to va-notify-infra
- [x] Slack notifications for Dependabot PRs

# Dependabot Details (from [ADR](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/documents/adr/0005-select-tools-to-secure-VANotify.md))
- Pro: Exists as part of Github, so not much integration required
- Pro: Meets need of dependency scans for vulnerabilities and outdated ones
- Pro: Automated PRs for dependency updates with option to approve and/or add on additional reviewers for approval
- Pro: Configurability for frequency of updates
- Pro: Active maintenance and updates of library itself
- Pro: Open source

# Resources
- All of our dependencies can be found in the github UI [here](https://github.com/department-of-veterans-affairs/notification-api/network/dependencies) (can configure dependabot through the UI or manually in the code)
- This [Enabling and Disabling Version Updates](https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#enabling-version-updates-on-forks) page includes info about version updates on forks
- Documentation for config-file, which includes ability for ignoring updates/dependency locks: https://dependabot.com/docs/config-file/
- Documentation for [Docker in Dependabot](https://dependabot.com/blog/dependabot-now-supports-docker/)

# Assumptions
- Ling's matrix and recommendations documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1wmWVBbnpzYUcEiNc3lQjwNUhOhxSQtB-WZTc3dDUyKI/edit#gid=0) 
- After Dev Analysis or as a part of the kickoff this card will be estimated 

# Out of Scope
- Adding monitoring and alerts for this is not in scope 
- When the tool is successfully implemented, this information must be provided for documentation in the ATO. This will be a separate task not in scope for this card

# Open Questions
- How often do we want Dependabot to check the repo? **Everything configured to weekly**
- Do we need to configure dependabot for utils too since some of the dependencies in notification-api are generate from utils? (does this need to be added to notification-admin as well?) **yes, configure for utils and va-notify-infra**
- Do we want to use version 1 or 2? Version 2 is in beta, but it might be more updated? **Use version 2**
- Do we also want to check github actions for updates? **yes**

**Comment by marisahoenig** [comment]
Reviewed with @jsmithVA, ready for sign off! 🎊
