### ISSUE TITLE
Integrate gunicorn with datadog

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1288]
## User Story - Business Need
We presently do not collect performance metrics about the gunicorn workers. Here is the list of metrics we would like to be able to collect: 

https://www.datadoghq.com/blog/monitor-gunicorn-performance/

### User Story(ies)

**As a** devops engineer
**I want** to integrate datadog with gunicorn
**So that** I can collect performance metrics and logs about gunicorn workers

### Additional Info and Resources
- [datadog blog on gunicorn]( https://www.datadoghq.com/blog/monitor-gunicorn-performance/)

- [steps for gunicorn integration with datadog](https://docs.datadoghq.com/integrations/gunicorn/), which includes guide of troubleshooting and validation.

- [Gunicorn access log command](https://docs.gunicorn.org/en/stable/settings.html#accesslog)

- [Gunicorn error log command](https://docs.gunicorn.org/en/stable/settings.html#errorlog) 

- [Example of Gunicorn metrics that can be collected](https://docs.datadoghq.com/integrations/gunicorn/#metrics)
- Update requirements-app.txt file with setproctitle

## Engineering Checklist

Use the step-by-step guide in the "Additional Info and Resources" section above for additional details.
 
For record keeping -- check off any configuration that has already been done.
And leave notes for any configuration that is deemed unnecessary.

- [ ] Configure notification-api to send metrics to [DogStatsD](https://docs.datadoghq.com/guides/dogstatsd/)
- [ ] Install setproctitle without impact to deployment / celery
- [ ] Collect Gunicorn Metrics:
     - [ ] Update datadog agent file: gunicorn.d/conf.yaml 
     - [ ] Update datadog.yaml to enable logging in the datadog agent
     - [ ] Restart agent

- [ ] Collect Gunicorn access / error logs:
     - [ ] Update datadog.yaml by adding "logs_enabled: true"
     - [ ] Add "--access-logfile <MY_FILE_PATH>" for Gunicorn access logging
     - [ ] Add "--error-logfile FILE, --log-file <MY_FILE_PATH>" Gunicorn error logging
     - [ ] Update gunicorn.d/conf.yaml file to start collecting your Gunicorn logs
     - [ ] Restart Agent

## Acceptance Criteria
- [ ] Setproctitle successfully installed without impact to deployment / celery
- [ ] Datadog captures Gunicorn metric
- [ ] Datadog captures Gunicorn access logs
- [ ] Datadog captures Gunicorn error logs

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
Setproctitle:
https://pypi.python.org/pypi/setproctitle

## Out of Scope:
Creating widgets or graphs in datadog

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1288?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney
