### ISSUE TITLE
SPIKE: Notification Status Enhancement - Onsite Notifications

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1299]
## User Story - Business Need
_**Required.** Please note you can have more than one story if applicable. If this is technical work achieving a larger initiative, the user story should represent that piece of the initiative, so it’s clear what problem we are solving._

### User Story(ies)
**As a** Veteran 
**I want** to see relevant notifications on My VA 
**So that** I can follow through on actionable tasks or refer back to pertinent notices

**As a** QA Engineer 
**I want** to quickly validate the success or failure of onsite notifications
**So that** I can ensure functionality is working as expected and quickly assist partners who need help testing

**Problem to Solve**: The process to trigger and validate onsite notifications is all manual and requires us to check cloudwatch logs to be 100% certain the onsite notification was a success.

**Idea**: As a person executing onsite notification tests, it's already part of the process to check the notification status (get notification in postman) for signs of success. You can be relatively certain onsite notifications were successful based on the IDs returned and overall status of the notification, but technically there's no certainty unless you go into cloudwatch and look for the logs for onsite notifications with a status_code of 200. 

- [ ] Discuss with QA before implementing code

### Additional Info and Resources
- The current testing and validation process is [here](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/Onsite_Testing.md)

## Engineering Checklist
_**Required**_

- [ ] Swagger is update
- [ ] A property is added to the notifications table indicating the onsite notification field
- [ ] Values are determined for said property

## Acceptance Criteria
_**Required**_
- e.g. when I send an email using an identifier, we retrieve the user’s email address in VA Profile and successfully deliver the email to that recipient

GIVEN I am sending an email or sms notification through VA Notify with onsite notifications enabled
AND the onsite notification was sent successfully
WHEN I check the status of the sent notification
THEN I can see the onsite notification call was a success

GIVEN I am sending an email or sms notification through VA Notify with onsite notifications enabled
AND the onsite notification failed
WHEN I check the status of a notification
THEN I can see the onsite notification call failed

## QA Considerations
- [ ] Test onsite with a template using onsite, validate the GET notifications returns a property indicating that the onsite returned success
- [ ] Test onsite with a template using onsite, validate the GET notifications returns a property indicating that the onsite returned failed
- [ ] Spin up a ticket to automate this
Note that how this is tested depends on what property is added and what values are returned

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1299?planning-poker) with Zenhub @cris-oddball

**Comment by ldraney** [comment]
https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-notify/onsite-notifications
^ for those who want to learn what this is

**Comment by mjones-oddball** [comment]
This is likely going to be canceled because onsite notifications are no longer enabled with va.gov. There's currently no plans to re-engage on this feature.

**Comment by npmartin-oddball** [comment]
@kbelikova-oddball can review, but, we don't need this at this time.
