### ISSUE TITLE
BUG: Failed communication_item_id lookup raises exception for valid ID

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1301]
## Description
The Prod logs are filled with the following celery log messages when an exception is raised for failing to lookup a valid communication_item_id that does exist in the database. The two examples found in Prod both related back to this communication item, which clearly does exist in the DB
```
        {
            "id": "07b09b10-c08c-45bf-b598-367af5ccf28f",
            "name": "Board of Veterans' Appeals Status Updates",
            "va_profile_item_id": 6
        },
```
See Additional Info for log messages.

## Steps to Reproduce

- Search prod-notification-api-log-group for 
```
sqlalchemy.exc.NoResultFound: No row was found when one was required
```
- See the logs as shown in Additional Info

It is unknown how to reproduce this and this may be the result of a race condition.

## Workaround
_Is there something we can do to work around this issue in the meantime? Leave blank if n/a._
None

## Impact/Urgency
_**Required.** Describe the impact this bug has on our system, clients, and/or team._

-  Medium - the traceback floods the logs, some question as whether it knocks celery over or not.

## Expected Behavior
_**Required.** Describe the desired outcome if this were functioning as expected. Include a checklist if applicable._

- When the code looks up a communication_item_id, and that communication_item_id exists in the database, then we return the lookup.
- When the code cannot find one, we catch the exception such that celery does not fall over and the logs aren't spammed with the traceback split across multiple lines. 
- Preferably any logging will include the communication_item_id that was not found.
- Unit tests are updated

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [ ] A challenge since it is not clear how to cause this exception to be raised. Can try checking staging after it is deployed there to see if we see any instances of this, especially during times of a heavy load. No events were found on staging for the past 48 hours as of this writing, so we may have to reply on unit tests.
- [ ] Regression passes

## Additional Info & Resources

SQLAlchemy [NoResultFound error info on .one() call](https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.one) documentation.

The code for this is [here](app/dao/communication_item_dao.py). Notice that there is no exception handling.

LOGS:

```
{
    "asctime": "2023-05-31T09:41:30",
    "application": "delivery",
    "name": "delivery",
    "levelname": "ERROR",
    "requestId": "no-request-id",
    "message": "Celery task: lookup-recipient-communication-permissions failed",
    "pathname": "/app/app/celery/celery.py",
    "lineno": 28,
    "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/site-packages/celery/app/trace.py\", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File \"/app/app/celery/celery.py\", line 35, in __call__\n    return super().__call__(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/celery/app/trace.py\", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/notifications_utils/statsd_decorators.py\", line 17, in wrapper\n    raise e\n  File \"/usr/local/lib/python3.8/site-packages/notifications_utils/statsd_decorators.py\", line 14, in wrapper\n    res = func(*args, **kwargs)\n  File \"/app/app/celery/lookup_recipient_communication_permissions_task.py\", line 40, in lookup_recipient_communication_permissions\n    if not recipient_has_given_permission(\n  File \"/app/app/celery/lookup_recipient_communication_permissions_task.py\", line 64, in recipient_has_given_permission\n    communication_item = get_communication_item(communication_item_id)\n  File \"/app/app/dao/communication_item_dao.py\", line 18, in get_communication_item\n    return CommunicationItem.query.filter_by(id=communication_item_id).one()\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py\", line 2870, in one\n    return self._iter().one()\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 1522, in one\n    return self._only_one_row(\n  File \"/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 562, in _only_one_row\n    raise exc.NoResultFound(\nsqlalchemy.exc.NoResultFound: No row was found when one was required"
}
```

```
sqlalchemy.exc.NoResultFound: No row was found when one was required
```

```
[2023-05-31 09:41:30,134: ERROR/ForkPoolWorker-4] Task lookup-recipient-communication-permissions[1f8808d7-d5dd-4f65-a31f-fd2632945d38] raised unexpected: NoResultFound('No row was found when one was required')
```

Screenshot showing the traceback splayed across multiple lines
 ![Screen Shot 2023-05-31 at 3.13.55 PM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/a049d11b-5ad4-4c8d-8296-0c3bf9643df8)

**Comment by npmartin-oddball** [comment]
Keeping.

**Comment by npmartin-oddball** [comment]
@k-macmillan will review.

**Comment by k-macmillan** [comment]
This is no longer appearing in the logs. There has been quite a bit of work on communication items so it is likely this was fixed during one of those PRs.
