### ISSUE TITLE
Update MPI / VA Profile ID Lookup Lambda

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1302]
### User Story(ies)
**As a** VA Notify engineer
**I want** to use the contact information I have collected
**So that** I can send notifications to Veterans

### Additional Info and Resources
-

## Engineering Checklist
- [ ] Place the contact info gathered from MPI in our temporary storage solution (defined in [ticket #964](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/964))
- [ ] Unit tests updated

## Acceptance Criteria
- The info is stored in our temporary storage location

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
Teams #[964](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/964)
Infra #[967](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-infra/567)

## Out of Scope
_Leave blank if n/a_

**Comment by tabinda-syed** [comment]
Cancelling.
