### ISSUE TITLE
Bootstrap Terraform for VA infra 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#131]
# Value Statement:
**As** a developer
**I want to**a consistent way to bootstrap terraform across environments
**So that** I can use terraform to provision all infrastructure

# Acceptance Criteria:
**GIVEN** bootstrapping code
**WHEN** I run it in VAEC environment (dev/staging/prod)
**THEN** it provisions everything necessary to run terraform in that environment

# Checklist:
- [x] role for terraform to manage state in a given environment
- [x] role for terraform to provision resources in a given environment
- [x] role can only be assumed by our service account
- [x] S3 state bucket created with versioning and encryption enabled
- [x] S3 state bucket policy that allows modifications only by terraform state management role
- [x] dynamo db table for lock management
- [x] tags attached to all resources

# Assumptions:
- We are going to use CloudFormation template for bootstrapping terraform

**Comment by ffafara-tw** [comment]
CloudFormation template is ready.
Dev environment is bootsrapped.
