### ISSUE TITLE
BUG: Return Useful Notification Status When User Has Opted-Out

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1319]
## Description
The notification status reason is generic when a user has opted-out. We should update it to be more specific. Please use something useful like, "ERROR: The number you are attempting to reach has opted-out, not retrying"

## Steps to Reproduce
- Send STOP to one of our AWS Pinpoint numbers that has it enabled to opt out 
- Attempt to send a sms message using the number you opted-out of and see the notification status message update to "ERROR: NonRetryableException - permenant failure, not retrying"

## Workaround
No workaround is necessary as this does not impact performance.

## Impact/Urgency

- This has no impact other than the ability to determine why a message didn't sent. This information would be helpful to have in logs and stats reports.

## Expected Behavior

- [ ] new status reason: "ERROR: The number you are attempting to reach has opted-out, not retrying" 

## QA Considerations
N/A

## Additional Info & Resources
The log message when a number has opted-out can be seen here:
```
app.celery.exceptions.NonRetryableException: StatusCode: 400, StatusMessage:Destination phone number opted out
```

This message is returned in two places in the `app/celery/provider_tasks.py` file. 
- In the [deliver_sms function](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/provider_tasks.py#L45)
- In the [deliver_sms_with_rate_limiting function](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/provider_tasks.py#L99)

**Comment by k-macmillan** [comment]
Opt outs have been covered previously, closing.
