### ISSUE TITLE
Bind Unbounded Local Variables

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1320]
## User Story - Business Need
Our application has places with unbounded local variables. An unbounded local variable is a variable that can be used without being initialized to a value. This can produce undesired results and is sometimes undetected able during feature/unit testing. 
The findings have been attached as a pdf (do not use)

Essentially this involves ensuring we are not using variables that may not have been assigned.

- [ ] discuss with QA

### User Story(ies)
**As a** developer  
**I want** to remove unbound references in my application. 
**So that** I have a stable application. 

### Additional Info and Resources
- [Explanation](https://stackoverflow.com/questions/22101836/how-can-a-name-be-unbound-in-python-what-code-can-cause-an-unboundlocalerror)
- [Explanation2](https://www.bhavaniravi.com/python/advanced-python/unbound-variables-in-python)
- Example where the `response` object may not have been set due to an exception being raised:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/4b3c1370-2069-4d2e-8924-593c12dcdf7e)
- [CodeQL](https://github.com/department-of-veterans-affairs/notification-api/security/code-scanning?query=is%3Aopen+branch%3Amaster+uninitialized) is the source of truth for routes to be fixed, not the linked document

Most of these changes should have no bearing on the flow of the code, but there may be some side effects that were misinterpreted as expected behavior.

It is important to understand the intent of the method, expected output and potentially break things down into smaller units.

## Engineering Checklist

- [ ] Do not fix routes from CodeQL list that are scheduled for deletion
- [ ] All unit test pass validation
- [ ] Create or refactor test cases to test for each unbounded local variable

## Acceptance Criteria
- [ ] The findings should no longer be susceptible to unbounded local variable (often times requiring a relocation / assignment value above the line where the code is used)
- [ ] All unit test pass validation

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

- [ ] Regression passes
- [ ] Logs are checked that we don't see exceptions related to this issue

## Out of Scope
Any activity not related to resolving the unbounded local variables found here.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1320?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by cris-oddball** [comment]
@babyjunior56 those are all failing with a known issue (detached instance). Just keep re-running the tests until they pass (they eventually will).

**Comment by mjones-oddball** [comment]
We've canceled the PR and will re-refine based on the latest info.

**Comment by kalbfled** [comment]
The right answer for this ticket is probably to break the long try/except block into multiple, smaller blocks.  That's what is confusing Flake8.

**Comment by cris-oddball** [comment]
Description updated based on refinement conversation.

**Comment by npmartin-oddball** [comment]
We won't be fixing/addressing this.
