### ISSUE TITLE
Remove User Flows from API

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1322]
## User Story - Business Need
Once the QA Suite automation has been running 3x without issues (on deployments, tag pushes, pre-releases), we should remove User Flows as the QA Suite replaces it.

- [x] discuss with QA

### User Story(ies)
**As an** engineer
**I want** to have the QA Suite replace User Flows and remove User Flows
**So that** I have high confidence in the VANotify app and am not wasting resources on redundant services.

### Additional Info and Resources
-

## Engineering Checklist
_**Required**_

- [x] User Flows is removed from all API actions
- [x] All User Flows code is removed from the API repo
- [x] The User Flows service is ~removed~ archived from Dev 

## Acceptance Criteria
_**Required**_

GIVEN you are deploying to Dev
WHEN you trigger the deploy
THEN user flows does not run
AND the code is successfully deployed to Dev

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

- [x] QA to double-check the engineering checklist
- [x] When the code is deployed, User Flows no longer runs.

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1322?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by cris-oddball** [comment]
I spent an hour on this and have a draft PR up in which all unit tests pass.

Tomorrow I will deploy to Dev using the workflow from this branch and ensure that User Flows does not run and that the lambda does not get deployed.

**Comment by cris-oddball** [comment]
[Deployed to Dev using action with the workflow set from my branch](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6720388472). The User Flows was not part of the deployment and the User Flow lambda was not deployed.

There is one final line I need to remove, `.gitignore/user_flows_exit_code.txt`, I wanted to make sure UF did not run prior to removing that line from gitignore. 

Will push up that change, re-deploy, validate and then open the PR.

**Comment by cris-oddball** [comment]
Unrelated to this branch, the API failed to deploy 1 celery and 1 celery beat task, largely because Infra master failed to deploy last night. Lucas is checking into it. Blocker.

**Comment by cris-oddball** [comment]
Infra master was able to be re-deployed to Dev. Deployed this branch to Dev. User Flows did not run at the end of the deployment and was not deployed with the lambdas. Regression passed, opening PR.

**Comment by cris-oddball** [comment]
PR approved and merged. Will deploy to perf for a final test.

Also reached out to Nathan re archiving a service.

**Comment by cris-oddball** [comment]
Nathan says to archive/delete a service, one just needs to click the Delete button in the Portal.

**Comment by cris-oddball** [comment]
Regression [passed](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/6723109813) in Perf, no signs of User Flows in actions.

**Comment by cris-oddball** [comment]
This is what happens when you use the Delete button:
- Archives all the service’s templates
- Removes all the service’s users and their roles
- Sets the service’s active field to false
- Updates the service’s name to indicate that it was archived on the current date


This service is now removed from Dev.
