### ISSUE TITLE
Upgrade the Python requests package in requirements-lambda.txt files

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1329]
### User Story(ies)

**As a** Notify developer
**I want** lambda functions to use the latest version of the Python "requests" package
**So that** we minimize security vulnerabilities.

### Additional Info and Resources

The lambda functions that use the "requests" Python package are:
```
...notification-api/lambda_functions$ grep requests */requirements-lambda.txt
two_way_sms/requirements-lambda.txt:requests ~= 2.28.2
user_flows/requirements-lambda.txt:requests~=2.29.0
vetext_incoming_forwarder_lambda/requirements-lambda.txt:requests ~= 2.28.2
```

Altering these requirements files is for documentation only.  The lambda functions actually use the "requests" lambda layer.  See [vanotify-infra 585](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/585).

## Engineering Checklist

- [ ] The required version of "requests" in all relevant requirements-lambda.txt files matches the version in the "requests" lambda layer.  See [vanotify-infra 585](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/585).

## Acceptance Criteria

- [ ] All lambda functions continue to work as expected.

## QA Considerations
N/A

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1329?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by npmartin-oddball** [comment]
Not needed.
