### ISSUE TITLE
Flask-JWT-Extended upgrade causes > 4.4.4 causes 'Cookie' object has no attribute 'name'

### ISSUE THREAD

**Issue by justaskdavidb2** [department-of-veterans-affairs/notification-api#1330]
## Description

Upgrading version of Flask-JWT-Extended to >= 4.5.0 introduces breaking changes that cause test cases to fail with the error `'Cookie' object has no attribute 'name'`.  

![Screenshot 2023-06-20 at 1.20.51 PM.png](https://images.zenhubusercontent.com/63e53ba48ed98b91995b8293/be91bd2b-cd29-4d3d-88f4-f05893e5a065) 

We need to update the API code to work with newer versions.

## Steps to Reproduce

On your local machine:
- [ ] In requirements-app.txt, upgrade Flask-JWT-Extended to >=4.5.2, which should result in a build with a newer version.
- [ ] Build the application and test Docker images
- [ ] Run all test cases

## Workaround
N/A

## Impact/Urgency
N/A

## Expected Behavior
- [ ] All Unit Test cases pass locally and in Github
- [ ] requirements-app.txt and requirements.txt updated to reflect the newer version in use

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
https://flask-jwt-extended.readthedocs.io/en/3.0.0_release/tokens_in_cookies/

**Comment by kalbfled** [comment]
We misdiagnosed the problem.  Flask-JWT-Extended has been upgraded; it was not the cause of the AttributeError.
