### ISSUE TITLE
BUG: CodeQL check blocks merging

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1336]
## Description

The CodeQL check is not properly implemented for this repository, and that blocks merging even with 2 approvals.  This is a consequence of merging [PR 1304](https://github.com/department-of-veterans-affairs/notification-api/pull/1304).

![checks](https://github.com/department-of-veterans-affairs/notification-api/assets/5375929/1bfb5551-1f04-4506-a564-63444f42cd8e)

See the notification-api-qa repo, among others, for an example of a correct implementation.

## Steps to Reproduce

Create any PR.

## Workaround

@k-macmillan can override the restrictions and merge.

## Impact/Urgency

It's pretty urgent.  We can't merge in this repository without Kyle.

## Expected Behavior

- [ ] CodeQL completes properly and doesn't block merging

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
_If applicable, include extra information to assist with troubleshooting, like screenshots, log snippets, links to applicable code files, and/or articles/websites that have relevant info on the issue. Leave blank if n/a._

**Comment by k-macmillan** [comment]
Issue has been resolved:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/5779308f-bcd5-4612-9d04-0b917ee5939a)

It involved changing the branch protections to point to the new Analyze.
