### ISSUE TITLE
BUG: Remove cookie_jar from unit tests

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1337]
## Description

During work for #1241, we discovered that some unit tests in [tests/app/oauth/test_rest.py](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/oauth/test_rest.py) reference non-public attributes and classes of the Flask or Werkzeug Python packages.  Specifically, tests should not use "cookie_jar" or [Cookie](https://werkzeug.palletsprojects.com/en/2.3.x/test/?highlight=cookie#werkzeug.test.Cookie) because these can change from version to version without notice.

For details, including which tests were failing, read [this comment](https://github.com/department-of-veterans-affairs/notification-api/issues/1241#issuecomment-1601673649).  Most of the offending test code looks like this:

```
assert any(
    cookie.key == cookie_config['JWT_ACCESS_COOKIE_NAME']
    for cookie in client.cookie_jar  # cookie_jar is not intended to be a public interface
)
```

## Steps to Reproduce

The problem is intermittent.  The non-public interface might change at any time and bite us during a future attempt to upgrade.

## Workaround

During development for #1241, we inspected the revised Cookie interface in the interpreter and updated the test code to reflect then-current reality, but this is a moving target.

## Impact/Urgency

This problem could resurface during a future upgrade.

## Expected Behavior

The failing tests all relate to the API interface with notification-ui, which is no longer in use.  One possible solution is to remove all tests specifically for this interface. 

- [ ] Determine whether to remove all tests specifically for this interface or to update the affected tests.
- [ ] Based on above determination either:
  - [ ] Remove all tests specifically for this interface
  - [ ] Affected unit tests read and write cookies using the public [test.Client interface](https://werkzeug.palletsprojects.com/en/2.3.x/test/#werkzeug.test.Client) provided by Werkzeug (via Flask), including `get_cookie` and `set_cookie`

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Additional Info & Resources
_If applicable, include extra information to assist with troubleshooting, like screenshots, log snippets, links to applicable code files, and/or articles/websites that have relevant info on the issue. Leave blank if n/a._

**Comment by mjones-oddball** [comment]
Cookie jar is no longer present in the code. We're conflicted between repurposing this for route removal (cleaning up the code), but are not quite sure if we're still going that route or if the new v3 model will handle cleaning this up as part of that. @k-macmillan need your input.
