### ISSUE TITLE
Point vets-api Dev environment at notification-api Staging environment

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#134]
It would be useful for the VANotify team to have a Development environment that we can feel free to mess around with. Currently, the `vets-api` Development environment points at `notification-api`'s Development environment, so any experimental changes to `notification-api` can break `vets-api`.

We should update the [Development configuration](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/vets-api/dev-settings.local.yml.j2) of `vets-api` to point  at the Staging environment of `notification-api`.

We will require the API key and template ID created in #76, and the URL of the [Staging `fwdproxy`](https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/fwdproxy-vagov-staging.yml).

**Comment by saman-moshafi-va** [comment]
verified it is working. I have attached the web page and email.  The cloudwatch log for staging was:
{"name": "app", "levelname": "INFO", "message": "email 1902f21d-3717-4274-8987-d53b483c4ed9 created at 2020-08-28 17:39:15.463747", "pathname": "/app/app/notifications/process_notifications.py", "lineno": 120, "time": "2020-08-28T17:39:15", "requestId": null, "application": "app", "logType": "application"}
152.133.18.44 - - [28/Aug/2020:17:39:15 +0000] "POST /v2/notifications/email HTTP/1.1" 201 1294 "-" "NOTIFY-API-RUBY-CLIENT/5.1.2"
[vets api dev to notification api staging email.pdf](https://github.com/department-of-veterans-affairs/notification-api/files/5143506/vets.api.dev.to.notification.api.staging.email.pdf)
[vets api dev to notification api staging web page.pdf](https://github.com/department-of-veterans-affairs/notification-api/files/5143507/vets.api.dev.to.notification.api.staging.web.page.pdf)

Which means the notification staging was used to send the email
