### ISSUE TITLE
Freeze all requirements for building the local app Docker image, and document the upgrade process

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1340]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** developer,
**I want** to build my local Docker image with completely frozen requirements
**So that** I am not delayed by unexpected build failures due to unplanned upgrades.

**As a** developer,
**I want** to have documentation for how to upgrade dependencies
**So that** the process is straight-forward, repeatable, and not reliant on tribal knowledge.

### Additional Info and Resources

[requirements-app.txt](https://github.com/department-of-veterans-affairs/notification-api/blob/master/requirements-app.txt) loosely specifies all top level Python dependencies for the Flask application.  Installing Python dependencies with this file uses the latest compatible Python package versions for these top level dependencies and indirectly installs all necessary sub-dependencies.

[requirements.txt](https://github.com/department-of-veterans-affairs/notification-api/blob/master/requirements.txt) freezes all dependencies--top and sub--to specific versions.  Github and AWS create images that [install dependencies from this file](https://github.com/department-of-veterans-affairs/notification-api/blob/master/ci/Dockerfile#L35).

As currently implemented, building the Flask app image locally, as [prescribed in the README](https://github.com/department-of-veterans-affairs/notification-api#local-development-using-docker), uses Dockerfile.local, which [uses requirements-app.txt](https://github.com/department-of-veterans-affairs/notification-api/blob/master/ci/Dockerfile.local#L15).

## Engineering Checklist

- [ ] "requirements-app.txt" changed to "requirements.txt" in Dockerfile.local ([source](https://github.com/department-of-veterans-affairs/notification-api/blob/master/ci/Dockerfile.local#L15))
- [ ] Create  README-dependencies.md that describes the upgrade process, including the need to maintain requirements-app.txt.  The first step should be to build locally using requirements-app.txt.  The last step should be to update requirements.txt as already described [here](https://github.com/department-of-veterans-affairs/notification-api#update-requirementstxt).
- [ ] The README.md mentions and links to README-dependencies.md

## Acceptance Criteria

In addition to the engineering checklist:

- [ ] The README.md table of contents reflects the new revisions, and the hyperlinks work.

**Comment by cris-oddball** [comment]
This is no longer necessary since we use Poetry now for this repo. Closing ticket as will not do.
