### ISSUE TITLE
Datadog StatsD - System Reliability Dashboard

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1343]
## User Story - Business Goal
This ticket is part two of two, with the business goal of enhancing system monitoring and reliability by identifying and categorizing all available statsd metrics. By leading a team discussion to determine the most valuable metrics for alerts and for enhancing the system reliability dashboard, this initiative aims to improve the team's ability to proactively monitor and address system health, performance, and potential issues. This could lead to improved system stability, reduced downtime, and ultimately a better user experience for customers using the system.

This ticket seeks address the following questions:
1. Which of these metrics are the most valuable for creating alerts and enhancing our system reliability dashboard?
2. How can we confirm the usefulness and rate of these selected metrics?

### User Story(ies)
**As a** system reliability engineer
**I want** to identify and categorize all available statsd metrics
**So that** we can choose the most valuable ones for creating alerts and enhancing our system reliability dashboard.

## Acceptance Criteria & Checklist
- [ ] A team discussion has been led on which metrics would be most valuable for metrics and alerts, specifically for sms and email.
- [ ] A demo system reliability dashboard has been created with selected metrics to validate their usefulness and rate
- [ ] Demo dashboard has been shared with the team, and based on feedback new tickets for additional dashboard/metrics/alertshave been created
- [ ] Tickets for next steps (if any) have been identified and created

## Timebox
I propose timebox of one week for this spike. This should be enough time to assess the metrics, initiate team discussions, and create a first draft of a system reliability dashboard.

## Dependencies
This ticket requires #1342 to be completed

## Out of Scope
Creating new/additional statsd metrics is out of scope.

### Additional Info and Resources
First resource should be the list of statsd metrics documented from the previous ticket.  The most frequent metrics related to sms and email should be considered first.
It may also be useful, for sms, to consider the [sms_notifications_flowchart.md](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/sms_notifications_flowchart.md).  At first glance it seems that only send_to_providers.py has statsd implemented, please confirm.

For email, we don't seem to have a similar flowchart.  

If needed, the following resources may provide additional insights and best practices for working with StatsD metrics.  These are not required reading for this ticket, but are primarily to serve as brainstorming for the dashboard and helping the team come to a conclusion about our utilization of available metrics.

1. [StatsD Metric Types](https://github.com/statsd/statsd/blob/master/docs/metric_types.md): This is a documentation page from the official StatsD GitHub repository that explains the different types of metrics that StatsD supports.

2. [Data Types in StatsD](https://statsd.readthedocs.io/en/latest/types.html): This page from the StatsD documentation provides a detailed explanation of the different data types that StatsD uses.

3. [StatsD Metrics Architecture, Metrics Types and Formats](https://sysdig.com/blog/monitoring-statsd-metrics/): This blog post by Mateo Burillo provides an overview of the StatsD metrics architecture, the types of metrics, and their formats.

4. [SRE School: Instrumentation](https://john-millikin.com/sre-school/instrumentation): This blog post by John Millikin provides an overview of instrumentation, which is a key concept in system reliability engineering.

5. [Instrumentation in Prometheus](https://prometheus.io/docs/practices/instrumentation/): This page from the Prometheus documentation provides a detailed explanation of how instrumentation works in Prometheus, which is a popular open-source system monitoring and alerting toolkit. This may/may not be useful in brainstorming our utilization of statsd and potential dashboards.

#### Optional reading on statsd
These resources should provide a good starting point for understanding StatsD metrics and how they can be used to enhance system monitoring and reliability.
1. [StatsD Metrics Documentation](https://statsd-metrics.readthedocs.io/en/latest/): This is the official documentation for StatsD metrics. It provides a comprehensive guide on how to use StatsD metrics (and how we are probably already using them)

2. [StatsD: What is it and how to monitor it](https://www.metricfire.com/blog/statsd-what-is-it-and-how-to-monitor-it/): This blog post by MetricFire provides an overview of StatsD and gives guidance on how to monitor it effectively.

3. [Best Practices for Naming Metrics and Tags](https://docs.datadoghq.com/developers/guide/what-best-practices-are-recommended-for-naming-metrics-and-tags/): This guide from Datadog provides recommended best practices for naming metrics and tags, which can be useful when setting up and organizing your StatsD metrics.

4. [Collecting Metrics Using StatsD: A Standard for Real-Time Monitoring](https://thenewstack.io/collecting-metrics-using-statsd-a-standard-for-real-time-monitoring/): This article from The New Stack provides a detailed explanation of how to collect metrics using StatsD, and why it has become a standard for real-time monitoring.

5. [High Throughput Mode in DogStatsD](https://docs.datadoghq.com/developers/dogstatsd/high_throughput/): This documentation page from Datadog explains how to enable high throughput mode in DogStatsD, which can be useful if you're dealing with a large volume of StatsD metrics.

**Comment by npmartin-oddball** [comment]
Closing.
