### ISSUE TITLE
Implement Caching for API Keys

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1345]
## User Story - Business Need
Our application make calls to SQL database for data that does not change often. dao_fetch_service_by_id_with_api_keys() makes the largest number of queries against our database. We would like to use a caching to reduce the frequency of the SQL queries against our database. 

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   developer 
**I want**  to implement in-memory caching
**So that** we reduce the frequency we query for infrequently changed data.

### Additional Info and Resources
- Previous [Spike](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1035)
- [Cachetools](https://pypi.org/project/cachetools/)
- [types-cachetools](https://pypi.org/project/types-cachetools/)
- [Example of Cachetools](https://www.javatpoint.com/python-cachetools-module)
- Steps to verify:
  - Datadog -> APM -> Select dev env -> click Postgres -> Select postgres.query from the dropdown at the top of the screen -> scroll down to the resources -> click the appropriate query -> observe graph

## Engineering Checklist
- [ ] Add the following to modules: cachetools +  types-cachetools
- [ ] Add TTL decorator for dao_fetch_service_by_id_with_api_keys(): see cachetools documentation
- [ ] Caching time should be set to 1 hour

## Acceptance Criteria
Making multiple requests in a short period of time from the same service does not show more than one request to the Database for the mentioned query.
 

## QA Considerations
This covers how to test dao_fetch_service_by_id_with_api_keys()
- [ ] Test Case 1: should hit the database using a given input
- [ ] Test Case 2: should call the function and hit the database once each
- [ ] Test Case 3: should call the function with two different input and hit the database 2x, not 3x

We discussed the following in refinement:
The concept here is that if you are executing a route that validates api key (auth), then the subsequent requests for the following hour would use the cached the api key validation assuming the api key used has not changed.  It should also be faster than the first request. You should be able to see the caching being used vs the db query via cloudwatch logs. Example route, email notifications. Easiest way to test might be to use postman manually and sending the same request body multiple times.

**Comment by cris-oddball** [comment]
@justaskdavidb2 Please add something to the Acceptance Criteria section.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1345?planning-poker) with Zenhub @cris-oddball @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by cris-oddball** [comment]
DB query is
```
SELECT services.id, services.name, services.created_at, services.updated_at, services.active, services.message_limit, services.restricted, services.research_mode, services.email_from, services.created_by_id, services.prefix_sms, services.organisation_type, services.crown, services.rate_limit, services.contact_link, services.volume_sms, services.volume_email, services.volume_letter, services.consent_to_research, services.count_as_live, services.go_live_user_id, services.go_live_at, services.sending_domain, services.smtp_user, services.email_provider_id, services.sms_provider_id, services.organisation_id, services.version, api_keys_1.secret, api_keys_1.id, api_keys_1.name, api_keys_1.service_id, api_keys_1.key_type, api_keys_1.expiry_date, api_keys_1.created_at, api_keys_1.updated_at, api_keys_1.created_by_id, api_keys_1.version 
FROM services 
    LEFT OUTER JOIN api_keys ON services.id = api_keys_1.service_id 
WHERE services.id = ?
```

**Comment by mjones-oddball** [comment]
This is still not going as expected and is off-track. The method for api keys is not behaving as originally thought. Next step will be looking into docs that Dave suggested and then syncing. CC @tabinda-syed
