### ISSUE TITLE
BUG: Release Trigger Action does not deploy a published release to Prod

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1348]
## Description
The Release Trigger action fails to initiate a deploy to Prod when a Release is Published.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. A Release is made from a tag, the "Set as the latest release" box is checked on that tag, the Publish button is clicked
2. The current [release_trigger.yml ](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/release_trigger.yml) fails to trigger, no deploy happens.

## Workaround
Is there something we can do to work around this issue in the meantime?

We can use the Deploy to Dev to release code to Prod.

## Impact/Urgency

- High as this impacts every deploy cycle, even though we have a workaround it is preferred to have a release trigger.

## Expected Behavior

- [x] When a release is made from a tag, the "Set as the latest release" box is checked on that tag, and the Publish button is clicked, the action to release to Prod is triggered and the code deploys.

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

- [ ] Depending on the solution, this is tested on a release to Prod, but this has its drawbacks in terms of know with certainty what code is up in AWS on a specific version.

## Additional Info & Resources

QA recommends two different actions, one to deploy to Staging based on a Draft pre-release, one to deploy to Prod based on a release.

**Comment by ldraney** [comment]
[Wrote a doc about how I came to a solution](https://docs.google.com/document/d/1GjB-77RT1odUZC8TumpTK0pLKJJ7TxHZJh0vIb3BpFY/edit?usp=sharing).  I now have a branch ready and am opening a PR.

**Comment by cris-oddball** [comment]
Next steps discussed with Lucas:

- Get approvals on PR
- Do not merge to master until Cris is available on Friday, Jun 30.

**Comment by cris-oddball** [comment]
Code merged to master, cut tag and pre-release to staging created.
The pre-release was saved as a Draft and then published.
The trigger executed and the code is going to staging.

**Comment by cris-oddball** [comment]
Code deployed to staging. Lucas and I agreed to close out this ticket now. If any issues pop up on the release to Prod next sprint, a new bug ticket will be opened.
