### ISSUE TITLE
Personalisation Redaction: Remove the TemplateRedacted class

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1354]
## User Story - Business Need

This ticket is a consequence of [vanoity-team 1040](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1040).  Its goal is to eliminate technical debt to facilitate the implementation of redactions in notifications.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,
**I want** not to have extraneous tables in the database
**So that** the implementation is uncluttered and easier to follow.

### Additional Info and Resources

The [TemplateRedacted](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/models.py#L998) class duplicates information in the Template class.  The tables have a 1-to-1 relationship.

## Engineering Checklist
**If deleting this creates a lot of issues and/or we run the regression and we see failures because this code was needed/used then please communicate that to the team and cancel this work.**

- [ ] Verify the template_redacted table is empty before starting
- [ ] Remove the [TemplateRedacted](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/models.py#L998) class from models.py and elsewhere in the app/ and tests/ directories.  You can run `grep -rn TemplateRedacted .` to identify locations.
- [ ] Alter [TemplateBase.template_personalisation](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/models.py#L863) to be a standard boolean column that defaults to False.
- [ ] Create a new migration that drops this table.
- [ ] Modify or delete unit tests as necessary.
- [ ] Create/update template in Portal after making changes to ensure this has no impact

## Acceptance Criteria

- [ ] All unit tests pass
- [ ] The table "templates_redacted" is no longer in the database
- [ ] All references to `TemplateRedacted` and `template_redacted` have been handled and removed
- [ ] Output of a get template query doesn't change

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [ ] determine if this impacts the expected reponses of any routes, update Pydantic models in QA suite if so

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1354?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by kalbfled** [comment]
@k-macmillan @mjones-oddball Nathan says that Strike queries the table associated with the class, which precludes removing it.
