### ISSUE TITLE
Personalisation Redaction: Redact notifications during deserialization

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1357]
## User Story - Business Need

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA service,
**I want** not to see PII when I GET a notification
**So that** everybody remains in compliance with all applicable laws and VA policies.

### Additional Info and Resources

As currently implemented, notification personalization data is [encrypted](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/models.py#L1422) for storage in the database and decrypted during the deserialization process used to GET a notification.

While the TemplateBase class has a boolean [redact_personalisation attribute](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/models.py#L876) that doesn't seem to be used or is not correctly implemented, and we are not going to use it.

**The desired behavior is that the response to notification GET request contain the literal `<redacted>` for all personalization values. **  This should not affect what's actually stored in the database.

NOTE: personalisation can also be added to an email subject. If included in the email subject, we also want to redact it there as well.

## Engineering Checklist
**Off-track awareness - if the engineering work seems like it's going to take more than 3 days, please raise to the team immediately. Our assumption is engineering gets 3 pts and QA gets 2 pts.**

- Write new unit tests first.  The response from the following routes should display "<redacted>" for all personalized values (content and/or subject):
    - [ ] POST v2/notifications/email
    - [ ] POST v2/notifications/sms
    - [x] GET /v2/notifications (for an e-mail notification)
    - [x] GET /v2/notifications (for a SMS notification)
- Implement the behavior codified by the tests.
    - [x] GET /v2/notifications (for an e-mail notification)
    - [x] GET /v2/notifications (for a SMS notification)
- [x] Update the Slide deck with the key win and a demo slide

## Acceptance Criteria
- [x] Manual and unit test verification of all intended redactions.

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

- [ ] Ensure personalizations are redacted.

## Out of Scope

- Only modify v2 routes.  Do not change v1 (in app/notifications/) routes.
- Do not attempt to determine if any particular personalized value is PII.  Redact everything or nothing.
- Do not worry about redacted letters, which is functionality not in use.
- Do not attempt to sanitize the database once a notification reaches a final state.  We will handle that in other tickets.
- Ignore the redact_personalisation property

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1357?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by k-macmillan** [comment]
okay to keep

**Comment by cris-oddball** [comment]
Notes from @mchlwellman and @cris-oddball discussion

- The only way to add the property `redact_personalisation` to a template is via the POST UPDATE route, NOT the POST CREATE Route (or the portal, fyi).
- The POST UPDATE route is built incorrectly - it requires properties from the CREATE route, which is silly.
- The redaction doesn't work (tested with an email)
- Need to resolve whether to fix the POST CREATE and POST UPDATE routes or have Portal add this property to the template creation.
-What is  `template_redacted` field `"template_redacted": "3fa85f64-5717-4562-b3fc-2c963f66afa6",`

**Comment by cris-oddball** [comment]
PR approved and merged, deployed to Perf. Will test on Monday.

**Comment by cris-oddball** [comment]
QA - SENDING BACK TO IN PROGRESS

Looks like we incorrectly removed the content property from the POST response when we reworked the ticket's description. This work needs to be completed for email/sms. I'll still send what we have up to staging/prod but we just need to redact the personalisation from the POST response.

**TC 01** - Sending an sms with personalisation in the content both delivers the sms with the personalisation and redacts that personalisation from the GET response
```
"content": "This is a sample SMS with a ((variable)) in it. Messages longer than 160 characters will be broken up into blocks of 153 characters. Words or variables that straddle the 153 characters limit will be pushed to the next block like this message.\n\nTo begin creating your SMS message delete this text and start typing your message.",
```
POST request 
```
{
    "template_id": "{{sms-template-id}}",
    "phone_number": "+17192445254",
    "personalisation": {
        "variable": "QA note"
    },
    "callback_url": "{{notification-api-url}}/internal/qa-testing-1357"

}
```


POST RESPONSE - note that the response does include content and is not redacted.
```
{
    "billing_code": null,
    "callback_url": "https://sandbox-api.va.gov/vanotify/internal/qa-testing-1357",
    "content": {
        "body": "This is a sample SMS with a QA note in it. Messages longer than 160 characters will be broken up into blocks of 153 characters. Words or variables that straddle the 153 characters limit will be pushed to the next block like this message.\n\nTo begin creating your SMS message delete this text and start typing your message.",
        "from_number": "+16075362872"
    },
    "id": "8af06a29-9fcb-4782-b9e7-db9f8342e2dd",
    "reference": null,
    "scheduled_for": null,
    "template": {
        "id": "684c6afe-a7f7-4314-8752-b371f1bc8440",
        "uri": "https://sandbox-api.va.gov/services/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/templates/684c6afe-a7f7-4314-8752-b371f1bc8440",
        "version": 1
    },
    "uri": "https://sandbox-api.va.gov/v2/notifications/8af06a29-9fcb-4782-b9e7-db9f8342e2dd"
}

```
- received sms with the personalisation
- GET response  'body' property

> "body": "This is a sample SMS with a <redacted> in it. Messages longer than 160 characters will be broken up into blocks of 153 characters. Words or variables that straddle the 153 characters limit will be pushed to the next block like this message.\n\nTo begin creating your SMS message delete this text and start typing your message.",

**Comment by cris-oddball** [comment]
2nd PR for POST responses approved and merged, deploying to perf for validation.

**Comment by cris-oddball** [comment]
**QA PASSED**

- [ ] TC 01 - Sending an sms with personalisation in the content both delivers the sms with the personalisation and redacts that personalisation from the POST and GET responses

Template for the sms includes
```
"content": "This is a sample SMS with a ((variable)) in it. Messages longer than 160 characters will be broken up into blocks of 153 characters. Words or variables that straddle the 153 characters limit will be pushed to the next block like this message.\n\nTo begin creating your SMS message delete this text and start typing your message.",
```
POST request
```
{
    "template_id": "{{sms-template-id}}",
    "phone_number": "<a valid mobile number>",
    "personalisation": {
        "variable": "FOOBAR"
    },
    "callback_url": "{{notification-api-url}}/internal/qa-testing-1357"
}
```
POST RESPONSE for the body property

> "body": "This is a sample SMS with a `<redacted>` in it. Messages longer than 160 characters will be broken up into blocks of 153 characters. Words or variables that straddle the 153 characters limit will be pushed to the next block like this message.\n\nTo begin creating your SMS message delete this text and start typing your message.",

- received sms with the personalisation FOOBAR
- GET response 'body' property
>    "body": "This is a sample SMS with a `<redacted>` in it. Messages longer than 160 characters will be broken up into blocks of 153 characters. Words or variables that straddle the 153 characters limit will be pushed to the next block like this message.\n\nTo begin creating your SMS message delete this text and start typing your message.",

---

- [ ] TC 02 - Sending an email with personalisation in the content and/or subject both delivers the email with the personalisation and redacts that personalisation from the POST and GET responses

Template for the email includes
```
"content": "Hi ((name)),\n\n    ((service name)) is now live on VA Notify.\n\n    You can send up to ((message limit)) messages per day.\n\n    If you have a question, or something goes wrong, please contact us:\n    https://notification.cdssandbox.xyz/support/ask-question-give-feedback\n\n    We’ll reply as soon as possible.\n\n    Thank you from the VA Notify team.\n\n    -\n\n    Salute ((name)),\n\n    ((service name)) est maintenant actif sur VA Notify.\n\n    Vous pouvez envoyer jusqu’à ((message limit)) messages chaque jour.\n\n    Si vous avez une question ou un problème, envoyons-nous un courriel:\n    https://notification.cdssandbox.xyz/support/ask-question-give-feedback\n\n    Nous vous répondrons bientôt.\n\n    Merci,\n    L’équipe de notification.\n    ",

"subject": "((service name)) is now live on VA Notify",
```
POST request
```
{
    "template_id": "{{email-template-id}}",
    "email_address": "<a valid email>",
    "personalisation": {
        "name": "foobar",
        "message limit": "foobar",
        "service name": "foobar"
    }
}
```
POST RESPONSE
>     "content": {
        "body": "Hi `<redacted>`,\n\n    `<redacted>` is now live on VA Notify.\n\n    You can send up to `<redacted>` messages per day.\n\n    If you have a question, or something goes wrong, please contact us:\n    https://notification.cdssandbox.xyz/support/ask-question-give-feedback\n\n    We’ll reply as soon as possible.\n\n    Thank you from the VA Notify team.\n\n    -\n\n    Salute `<redacted>`,\n\n    `<redacted>` est maintenant actif sur VA Notify.\n\n    Vous pouvez envoyer jusqu’à `<redacted> `messages chaque jour.\n\n    Si vous avez une question ou un problème, envoyons-nous un courriel:\n    https://notification.cdssandbox.xyz/support/ask-question-give-feedback\n\n    Nous vous répondrons bientôt.\n\n    Merci,\n    L’équipe de notification.\n    ",
        "subject": "`<redacted> `is now live on VA Notify"
    },
- received email with the personalisation
- GET RESPONSE 'body' and 'subject properties
>  "body": "Hi `<redacted>`,\n\n    <redacted> is now live on Notification.\n\n    You can send up to `<redacted>` messages per day.\n\n    If you have a question, or something goes wrong, please contact us:\n    https://notification.cdssandbox.xyz/support/ask-question-give-feedback\n\n    We’ll reply as soon as possible.\n\n    Thank you from the Notification team.\n\n    -\n\n    Salute `<redacted>`,\n\n    `<redacted>` est maintenant actif sur Notification.\n\n    Vous pouvez envoyer jusqu’à <redacted> messages chaque jour.\n\n    Si vous avez une question ou un problème, envoyons-nous un courriel:\n    https://notification.cdssandbox.xyz/support/ask-question-give-feedback\n\n    Nous vous répondrons bientôt.\n\n    Merci,\n    L’équipe de notification.\n    ",
> "subject": "`<redacted>` is now live on Notification",
