### ISSUE TITLE
Grafana confirmation email monitoring

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/notification-api#136]
# Value Statement
**As** a developer
**I want to** be able to view failures and job statuses in Grafana
**So that** I can make sure VANotify is running successfully.

# Acceptance Criteria
**GIVEN** Grafana dashboards are set up
**WHEN** I navigate to the Job Queue Dashboard
**THEN** I can see the Form526ConfirmationEmailJob in every graph.

**GIVEN** Grafana dashboards are set up
**WHEN** I navigate to the External Service Performance Indicators Dashboard
**THEN** the vanotify availability and latency graphs show data.

**GIVEN** a Form526ConfirmationEmailJob failed
**WHEN** I navigate to the Job Queue Dashboard
**THEN** I see increase in Worker Failure Count

**GIVEN** a Form526ConfirmationEmailJob succeeded
**WHEN** I navigate to the Job Queue Dashboard
**THEN** I see increase in Job Count Total and Jobs Queued

# Checklist
- [x] Check that [Job Queue Dashboard](http://grafana.vfs.va.gov/d/000000013/job-queue) includes Form526ConfirmationEmail in all job graphs
    - [x] Verify that data is accurate and job failures show up

- [x] Check that [External Service Performance Indicators Dashboard](http://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?orgId=1) includes vanotify data (currently, it shows N/A, but Keifer is looking into this) in relevant environments (dev, staging)
    - [x] Verify that data is accurate

# Assumptions
- The two dashboards mentioned already have data for vanotify
    - [PR](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/12314) for VSP team for Job Queue Dashboard should be complete
    - Keifer has already been told about adding this data

# Additional Info/Resources
- Spike finished prior to card: https://github.com/department-of-veterans-affairs/notification-api/issues/78
- [Grafana Overview](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/grafana-overview.pdf)
- [Slack thread with Keifer
](https://dsva.slack.com/archives/C010R6AUPHT/p1597088350189400)
# Out of Scope
-

# Open Questions
-

**Comment by QaysarA** [comment]
Validated the external service performance indicators dashboard 

![Grafana dashboard.png](https://images.zenhubusercontent.com/5ecd57a8ffd816c37838ab46/4b5b72e3-0456-4032-9ba4-3ae370a62050)

**Comment by QaysarA** [comment]
Validated job failure  - 

![Grafana validation.png](https://images.zenhubusercontent.com/5ecd57a8ffd816c37838ab46/72fc30bb-fd02-4bcf-9f53-5cf8a5380db8)

Inconsistent data with job counts in the following -  

![Grafana - Inconsistent data.png](https://images.zenhubusercontent.com/5ecd57a8ffd816c37838ab46/06c8d0fc-d9fc-4f6f-86ef-5a9e4b328ee2)

**Comment by QaysarA** [comment]
Worked with @saman-moshafi-va and noticed that there were inconsistencies in Form526ConfirmationEmailJob 

Since we added 1% traffic: Wed 10/14 - 10-22 18 emails were sent but only 7 were displaying
For the 30 day time period there should at least 7, but only 3 display

Jobs Queued - also did not reflect the numbers that we saw in production (AC#4)

**Comment by ffafara-tw** [comment]
Please consult with @kfrz (@keifer furzland). The numbers might not represent absolute count and might be of rate type (averaged per time frame like second) or averaged per wokrer, etc.

**Comment by saman-moshafi-va** [comment]
I think we can move this to QA or Done.  This is the message from Keifer Furzland: `I'm guessing it's a frequency/impedence mismatch of sorts where the data is sliced in different time-frames`. Here is the [slack link](https://dsva.slack.com/archives/CBU0KDSB1/p1603818739072800).
In summary Grafana is excellent to discover potential issues with Form526ConfirmationEmailJob on the vets-api side, but for statistics we should rely on DataDog.
