### ISSUE TITLE
Spike: AWS Backups for PostgreSQL

### ISSUE THREAD

**Issue by nikolai-efimov** [department-of-veterans-affairs/notification-api#1362]
## User Story - Business Goal

To ensure business continuity in case of database failure.

### User Story(ies)

**As a**    db admin
**I want**  to configure automated backups and be able to restore our Aurora PostgreSQL with lowest RPO possible
**So that** we don't loose any data in case the system goes down

### Additional Info and Resources

Recovery Point Objective (RPO) -  indicates how much data will be lost during downtime
Recovery Time Objective RTO - indicates how long the system is going to be down)

Previous spike [1137](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1137) resulted in the following findings:

1. "Within RDS/Aurora, the limitation is for daily backups. For more granular backups, such as hourly backups, AWS Backups is required" (from support email)
2. We cannot expect low Recovery Point Objective (RPO), which indicates how much data will be lost during downtime. This depends on when the incident is taking place, off/peak hours, etc. 
3. We don't have control over WAL file archives, so we're at the mercy of AWS Backup mechanism. According to AWS support team "All data present at the time the snapshot is taken is restored. Backups have a RPO of 5 minutes via Point In Time Restores. [2] (from support email)"
4. There's PITR, but there's no "backtrack" option in RDS/Aurora PostgreSQL. "It will create a new database cluster rather than using the existing cluster. [3]  (from support email)"

* [Backups for PostgreSQL](https://catalog.us-east-1.prod.workshops.aws/workshops/2a5fc82d-2b5f-4105-83c2-91a1b4d7abfe/en-US/2-foundation/lab4-backup)
* https://docs.aws.amazon.com/aws-backup/latest/devguide/whatisbackup.html
* https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html
* https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-restore-snapshot.html
* https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.BestPractices.html
* https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-restore-snapshot.html
* https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-getting-started.html

## Acceptance Criteria & Checklist

- [x] The following procedure was completed in Dev. [Automated AWS Backups](https://catalog.us-east-1.prod.workshops.aws/workshops/2a5fc82d-2b5f-4105-83c2-91a1b4d7abfe/en-US/2-foundation/lab4-backup)
- [x] Decision on optimal number of backups is reached
- [x] Backups are fully enabled in Dev
- [x] Technical Documentation has been created and linked in the glossary
- [ ] Learnings have been shared with the team, and decisions have been documented
- [x] Tickets for enabling backups in Prod, Perf, and Staging are created

Completed research addresses the problems and/or answers the questions below:  

1. What's expected Recovery Time Objective RTO (indicates how long the system is going to be down) ?
2. Are we able to successfully configure backups by following steps in [Automated AWS Backups](https://catalog.us-east-1.prod.workshops.aws/workshops/2a5fc82d-2b5f-4105-83c2-91a1b4d7abfe/en-US/2-foundation/lab4-backup) or do we need to follow up with the support team.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1362?planning-poker) with Zenhub @cris-oddball @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by tabinda-syed** [comment]
If you pick up this ticket, please reach out to NIkolai to chat about it.

**Comment by nikolai-efimov** [comment]
![image (1).png](https://images.zenhubusercontent.com/647df92fea2b08c16fcd5059/d3ed0de4-042f-43ce-b395-b103bd68a061)![image (2).png](https://images.zenhubusercontent.com/647df92fea2b08c16fcd5059/df08ee15-cecb-4d25-85fe-a7f5bd7fa86b)

**Comment by nikolai-efimov** [comment]
![image (1).png](https://images.zenhubusercontent.com/647df92fea2b08c16fcd5059/d3ed0de4-042f-43ce-b395-b103bd68a061)![image (2).png](https://images.zenhubusercontent.com/647df92fea2b08c16fcd5059/df08ee15-cecb-4d25-85fe-a7f5bd7fa86b)

**Comment by nikolai-efimov** [comment]
![image (3).png](https://images.zenhubusercontent.com/647df92fea2b08c16fcd5059/6a950c46-7a4c-4b74-8b59-51a36b24e22d)

**Comment by nikolai-efimov** [comment]
![image (4).png](https://images.zenhubusercontent.com/647df92fea2b08c16fcd5059/b5911c45-306e-4add-a1c9-26da30431e4c)

**Comment by nikolai-efimov** [comment]
Additional questions sent to AWS support team

1. It's unclear how "Enable continuous backups for point-in-time recovery (PITR)" works together with backup frequency. What would be the difference between setting frequency to hourly (with PITR enabled) and setting backup frequency to daily (with PITR enabled). Could you explain how it works?
2. We found the following in the documentation "You can create two backup rules in the same backup plan: one continuous backup rule to recover the most current resource state and one snapshot backup rule for long-term retention". What is the difference in effect of doing this as separate rules vs doing it as a single rule. This then relates to question #1
3. There is an option to set backup frequency with a cron job. What's a good usecase for using this option?
4. How long does it take to backup ~100GB Aurora cluster? We set "Start within 1 hour Complete within 3 hours", is that appropriate to use those numbers? Is there best practices for these settings?
5. How can we tell current database size? ("volume bytes used" charts are empty under "monitoring", and nothing under configuration/storage)
6. How can we tell how much storage is used by backups?

**Comment by tabinda-syed** [comment]
Nikolai is awaiting a response from the AWS support team (i.e., external blocker). We anticipate this ticket is at risk of not being completed this sprint.

**Comment by nikolai-efimov** [comment]
- continuous backups are only available for single instance PostgreSQL and are not supported in Aurora clusters
-
