### ISSUE TITLE
Dev: Read Kafka schema from a registry

### ISSUE THREAD

**Issue by nikolai-efimov** [department-of-veterans-affairs/notification-api#1363]
## User Story - Business Need

Be able to handle Kafka schema evolution gracefully so that if BIP makes changes over time it does not break our system.

### User Story(ies)

**As a**  Kafka topic consumer
**I want**  to be able not to rely on a hardcoded schema, but instead be able to fetch schema info from a registry
**So that**  we can handle schema evolution

## Engineering Checklist

- [x] receive registry URL from BIP team
- [x] use AvroSerializer instead of the current method
- [x] test locally (optional)
- [x] test in dev env

## Acceptance Criteria
- [x] GIVEN you are consuming from a Kafka topic
WHEN there is a new event added to the topic
THEN the data is deserialized successfully

- [x] GIVEN you are consuming from a Kafka topic
WHEN given an offset in the past
THEN the data is deserialized successfully from that point on

## Potential Dependencies
previous work done for Kafka covered in [Spike 1035](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1035)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1363?planning-poker) with Zenhub @cris-oddball @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by tabinda-syed** [comment]
Team discussed at 7/10 Refinement that we should plan to pick this ticket up early in the sprint given that we expect an external dependency.

**Comment by cris-oddball** [comment]
FYI, verified that we can reach the Confluent SchemaRegistry from the dev-test-instance. Redacting the URL but it's in an email sent to the team and I'll update the team repo with it.
```
sh-4.2$ nc -zv <schemaregistry url> 443
Connection to <schemaregistry url> (<IP>) 443 port [tcp/https] succeeded!
```

**Comment by cris-oddball** [comment]
We are able to access the API endpoint for the SchemaRegistry using curl and pointing to the pem file (we added the new cert information provided by BIP to that file).
```
curl --verbose --cacert certs/<redacted> https://schemaregistry.dev.bip.va.gov/subjects
```
Connection was successful
```
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
```

**Comment by nikolai-efimov** [comment]
To make things work, we had to add ICA11 and RCA2 to VACAcerts.pem and switch to AvroConsumer, which is giving us a deprecation warning, instead of the new AvroDeserializer.
