### ISSUE TITLE
Sentry confirmation email monitoring

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/notification-api#137]
# Value Statement
**As** a VANotify developer
**I want to** be able to view all vets-api exceptions related to vanotify in Sentry
**So that** I have one dashboard for viewing any errors/exceptions.

# Acceptance Criteria
**GIVEN** I have my socks proxy on and a confirmation email job failed
**WHEN** I navigate to [Sentry](http://sentry.vfs.va.gov/)
**THEN** I can view the job failure via my "team view" in Sentry

**GIVEN** I am viewing a logged issue in my team view
**THEN** I expect to see exception stack trace, relevant tags, error message, payload, transaction id, user, request body, and timestamps

**GIVEN** the confirmation email job is successful
**THEN** statsd is incremented

# Checklist
- [x] Create a new sentry team ([instructions here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-configuration.md#creating-a-new-team)) - you will need to reach out to #vfs-platform-support, which is outlined in the instructions
- [x] Add notify members to team
    - http://sentry.vfs.va.gov/settings/vets-gov/teams/vsp-va-notify/projects/
- [x] specify a path/url that we want to “own” if an error happens
    - Paths can be found in the events' stacktrace. [Documentation](https://docs.sentry.io/product/error-monitoring/issue-owners/) on ownership rules
- [x] log errors for the confirmation email job in Sentry
- [x] increment statsd on success (right now, we only increment on failure)

# Assumptions
- Verify if statsd is incremented / can be done so in another more relevant story. Otherwise verify in Grafana here.

# Additional Info/Resources
- Spike completed: https://github.com/department-of-veterans-affairs/notification-api/issues/78

# Out of Scope
- Slack alerts - once sentry10 is available on vets-api, then we can set up alerting to our slack channel. So, having our team already set up will be helpful. Sentry10 updates can be tracked in [this epic](https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/7064).

# Open Questions
- What paths/urls do we want to own/see the errors of? (this requires looking into our stacktrace for confirmation email events)
- Do we want alerts/notifications for errors, via email? (Slack notifications not available until Sentry10 rollout)

**Comment by lingtran** [comment]
Created [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4956)

**Comment by lingtran** [comment]
Merged [PR](https://github.com/department-of-veterans-affairs/vets-api/pull/4956) today. Encountered some issues with Grafana where there doesn't seem to be any EVSS 526 Submissions data in non-prod environments. Awaiting for more info for some testing.

**Comment by lingtran** [comment]
**Sentry testing**
If assign to vsp-va-notify team the following issue: http://sentry.vfs.va.gov/vets-gov/platform-api-staging/issues/217658/?query=is%3Aunresolved, the issue appears in "Assigned to me" view for any person part of the team. 

**StatsD testing**
Tested by checking metrics in Prometheus (staging): http://prometheus-staging.vfs.va.gov:9090/prometheus/graph

Metrics:
worker_form526_confirmation_email_error
worker_form526_confirmation_email_success
api_vanotify_send_email_fail
api_vanotify_send_email_total

**Comment by lingtran** [comment]
Card passed desk check!

Team will create cards for following:
- To verify config when migration to Sentry 10 completes
- set up Sentry alerts
