### ISSUE TITLE
Dockerfile PyYaml and AttributeError

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1375]
## User Story - Business Need
Our build.yml fails (now with a temporary work-around) due to issues with PyYAML and `AttributeError: cython_sources`, potentially related to setuptools. The errors seem to be related to some incompatible versioning among the dependencies, particularly `PyYAML` version `6.x` and `Cython` version `3.x`.

- [ ] The ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Engineer <br>
**I want** the build and deployment processes to succeed without errors due to dependencies  <br>
**So that** we can continue to maintain and improve the application without disruption 

### Additional Info and Resources
Build errors were discussed and documented in the thread from [this team chat](https://oddball.slack.com/archives/C036AE08HA7/p1689612804959229). A temporary fix was proposed to pin `Cython` to a version below `3.0` and `PyYAML` to a version below `6.x`, and is the current state of our ./ci/Dockerfile
- [pyyaml issue #601](https://github.com/yaml/pyyaml/issues/601) - follow and ensure this issue is closed
- [First failed deploy](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/5578361363)
- [Successful Workaround deploy](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/5578612286)

## Engineering Checklist

- [ ] When Pyyaml issue 601 is resolved, add the new dependency chain
- [ ] Remove work-around and comment from our Dockerfile and Dockerfile.local

## Acceptance Criteria

- [ ] The build and deployment processes complete successfully without the work-around
- [ ] The implemented solution does not introduce other build or run-time errors.

## Potential Dependencies
This issue depends on the package maintainers of `PyYAML` and `Cython` resolving compatibility issues, or finding a workaround in our codebase that's compatible with the updates in these packages.

**Comment by cris-oddball** [comment]
@ldraney suggested changes:

The engineering checklist doesn't need an investigation. We need to wait until pyyaml has resolved their issue 601 and do the needful with updating dependencies.

So the checklist can just be

- [ ] when Pyyaml issue 601 is resolved, add the new dependency chain
- [ ] remove the workaround

**Comment by ldraney** [comment]
not to self: be sure that Dockerfile.local is added to the engineer checklist as well

**Comment by ldraney** [comment]
@cris-oddball  I adjusted according to your feedback

**Comment by cris-oddball** [comment]
this is blocked by pyyaml issue 601 (linked in description). Moving to New; keep an eye on it and alert dev team when this can be worked.

**Comment by cris-oddball** [comment]
Closed by a hotfix in Utils and a hotfix in API worked in sprint 58.
