### ISSUE TITLE
Update our Twilio error codes to handle the new 30034, 'blocked due to unregistered campaign'

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1376]
## User Story - Business Need
As of July 5, Twilio now requires that all 10DLC campaigns must be fully registered. Gradual blocking is in place (meaning, a permanent-failure, the sms will never be sent by Twilio) until August 31, 2023, at which time all messages sent through a campaign that is not fully registered will be blocked. Their new ErrorCode for this is 30034. Our code does not check for this ErrorCode, and thanks to a try/catch we do report the status as permanent-failure but do not provide a status_reason.
```
"status": "permanent-failure",
"status_reason": null,
```

Twilio callback response (account redacted) from our CloudWatch shows:
```
2023-07-17T17:27:14 delivery delivery INFO no-request-id "retrieved delivery status: {'payload': 'ErrorCode=30034&SmsSid=SMbeb97038066158ae063d47bb53357dcd&SmsStatus=undelivered&MessageStatus=undelivered&To=%2B14254147755&MessageSid=SMbeb97038066158ae063d47bb53357dcd&AccountSid=REDACTED&From=%2B19703005680&ApiVersion=2010-04-01', 'reference': 'SMbeb97038066158ae063d47bb53357dcd', 'record_status': 'permanent-failure'}" [in /app/app/celery/process_delivery_status_result_tasks.py:236]
```

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** client of the notification-api
**I want**  to understand why my message failed to send by looking at the status_reason in the notifications response
**So that**  I can take the appropriate action in my Twilio account for my campaign.

**As a** VANotify engineer
**I want**  to include a status_reason in the notifications response for any 30034 errors sent back by Twilio
**So that**  I can be assured my clients have the information they need.

### Additional Info and Resources

[Twilio blog](https://support.twilio.com/hc/en-us/articles/14910496447771-Shutdown-of-Unregistered-10DLC-Messaging-FAQ) announcing the change.

## Engineering Checklist

- [x] Twilio ErrorCodes are updated in our app to include the 30034 ErrorCode
- [x] Documentation on Twilio delivery status is updated - https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Delivery-Status.md

## Acceptance Criteria

GIVEN an authorized API user sends an sms notification using a Twilio 10DLC or Toll-free number that is not registered
WHEN the notification fails and a Twilio status is received with a status code of 30034
THEN the notification status is set to permanent-failure
AND the notification is not retried nor delivered

## QA Considerations

- [ ] As long as there are still unregistered campaigns in Dev/Perf (Loma Linda account), send a Twilio message in Postman and see the expected result as in the AC above.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1376?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by EvanParish** [comment]
After reviewing the code it seems that it would be much more complicated than initially anticipated to add a custom `status_reason` for this twilio status code. We are currently just mapping twilio statuses to the ones we use in our platform and that does not include custom `status_reason` messages. I'm still looking into how I might accomplish this, but it might not be as simple as we were hoping. Maybe I'm overlooking a simple solution that will make this easy?

**Comment by cris-oddball** [comment]
Approved, merged and deploying to Perf for testing.
