### ISSUE TITLE
BUG: Twistlock instance stuck at InProgress and failing status checks

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1378]
## Description
The twistlock instance is responding to ssm commands with InProgress and then failing to run the scan. The instance itself also eventually reports that the  'Instance reachability check failed'. Typically this has been resolved by stopping the instance, starting the instance, waiting for the 2 status checks to pass, then re-starting the Twistlock action. 

This morning, the Twistlock instance was restarted twice after a failure last night, the scan rerun performed twice and the result is:
```
Waiter CommandExecuted failed: Max attempts exceeded. Previously accepted state: For expression "Status" we matched expected path: "InProgress"

Waiter CommandExecuted failed: Max attempts exceeded. Previously accepted state: For expression "Status" we matched expected path: "InProgress"

Waiter CommandExecuted failed: Max attempts exceeded. Previously accepted state: For expression "Status" we matched expected path: "InProgress"

Waiter CommandExecuted failed: Max attempts exceeded. Previously accepted state: For expression "Status" we matched expected path: "InProgress"

Waiter CommandExecuted failed: Max attempts exceeded. Previously accepted state: For expression "Status" we matched expected path: "InProgress"
"InProgress"
""
Error: Process completed with exit code 255.
```

Eventually the instance failed its reachability status check. 
![Screen Shot 2023-07-19 at 10.50.37 AM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/20dc9d20-e183-458f-a56e-351002a1292b)

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Stop the utility-twistlock-scanner instance
2. When fully stopped, start the utility-twistlock-scanner instance
3. Wait for the instance to report Running and that the two status checks have passed
4. [Re-run this Twistlock job](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/5590843237/jobs/10242389347)
5. Observe that the action fails with the Waiter CommandExecuted failed: never reaching the expected status and exiting with error code 255 after 5 attempts
6. Wait some period of time and observe that the reachability status_check fails

## Workaround
Is there something we can do to work around this issue in the meantime?
No - there is no workaround at present.

## Impact/Urgency

High - Twistlock scans our app container for security vulnerabilities.

## Expected Behavior

- [x] cron job is running that deletes the `/var/log/messsages ` **daily**
- [x] Increase memory (terraform) - double it.
- [x] When the app is deployed to dev, then the Twistlock scan runs and completes.
- [ ] Follow-on spike ticket created to determine a better path moving forward (see comment below for suggestions

## QA Considerations
- [x] Validate that when the app is deployed to perf, then the Twistlock scan runs and completes.

## Additional Info & Resources
'

There are Cloudwatch logs for the Twistlock EC2 which should be reviewed to find any smoking guns.
From the errors.log:
```
2023-07-19 13:41:15 ERROR [New @ errors.go.59] [ssm-agent-worker] [MessageService] [Association] [EngineProcessor] [OutOfProcExecuter] [43fb267c-f4d1-4f2d-959b-041a43de4339.2023-07-18T14-07-46.567Z] received timedout signal!
2023-07-19 13:41:15 ERROR [messaging @ master.go.131] [ssm-agent-worker] [MessageService] [Association] [EngineProcessor] [OutOfProcExecuter] [43fb267c-f4d1-4f2d-959b-041a43de4339.2023-07-18T14-07-46.567Z] messaging worker encountered error: document worker timed out
```

From the failed action on the Perform Twistlock scan, before it starts printing out the WaiterCommands
```
Run INSTANCE_ID=$(aws ssm get-parameter --name /utility/twistlock/instance | jq '.Parameter.Value' -r)
  INSTANCE_ID=$(aws ssm get-parameter --name /utility/twistlock/instance | jq '.Parameter.Value' -r)
  COMMAND_ID=$(aws ssm send-command \
    --document-name "AWS-RunShellScript" \
    --instance-ids $INSTANCE_ID \
    --parameters '{"commands":[
        "#!/bin/bash",
       <redacted>
1>/dev/null", "exit $STATUS_CODE"
      ]}' \
    --output text --query "Command.CommandId")
  n=0
  until [ "$n" -ge 5 ]
  do
    aws ssm wait command-executed --command-id $COMMAND_ID --instance-id $INSTANCE_ID && break
    n=$((n+1))
  done
  RESULT=$(aws ssm list-command-invocations \
    --command-id $COMMAND_ID \
    --details \
    --query "CommandInvocations[].CommandPlugins[].{Status:Status,StatusDetails:StatusDetails,ResponseCode:ResponseCode,Output:Output}")
  echo `jq '.[].Status' <<< $RESULT`
  printf '%b\n' "$(jq '.[].Output' <<< $RESULT)"
  exit `jq '.[].ResponseCode' <<< $RESULT`
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    <redacted>

```
[AWS Understanding Command Statuses](https://docs.aws.amazon.com/systems-manager/latest/userguide/monitor-commands.html)
[AWS Send Command output](https://docs.aws.amazon.com/cli/latest/reference/ssm/send-command.html#output) - info on timeouts - we never reach a timeout but might be useful
[AWS Troubleshooting SSM Agent](https://docs.aws.amazon.com/systems-manager/latest/userguide/troubleshooting-ssm-agent.html)

**Comment by ldraney** [comment]
From Twistlock system log:

![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/b7a1099d-4428-4be7-aac2-13b4b2cd8385)

**Comment by cris-oddball** [comment]
Yesterday, Lucas terminated the instance and re-deployed (since this EC2 uses terraform).
Instance went into a failed status check today after the GutHub Action successfully ran.
Restarting instance - storage is 36GiB so will look for any logs that can be removed if able to connect.

**Comment by cris-oddball** [comment]
Questions:
- should we put an alarm on this or monitor storage
- if logs are knocking this over, do we need to extend the storage or run a cron that removes logs?
- can we instead run twistlock through a lambda? we would need to put the API container that it scans somewhere, possibly a self-hosted runner?
- can we ditch twistlock in favor of the native AWS container scans?
[AWS Image Scanning](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-scanning.html)
[Container scanning updates in Amazon ECR private registries using Amazon Inspector](https://aws.amazon.com/blogs/containers/container-scanning-updates-in-amazon-ecr-private-registries-using-amazon-inspector/)
> Coverage and pricing

> Now that you have an idea of the new scanning alternatives available for Amazon ECR, let’s address the questions of coverage and costs. At the moment, Amazon ECR provides CVE scanning for OS packages for most common Linux distributions, including Debian, Ubuntu, and Amazon Linux. Please refer to the supported OS and programming languages documentation for an up-to-date listing.

> Basic scanning is available with no additional charge to Amazon ECR customers. Each container image may be scanned once per 24 hours with basic scanning. This limit includes the initial scan on push, if enabled, and any manual scans.

> Enhanced scanning is provided and billed through Amazon Inspector. All accounts new to Amazon Inspector are eligible for a 15-day trial to evaluate the service and estimate its cost. During the trial, all eligible container images pushed to Amazon ECR are continually scanned at no cost.

> Pricing for enhanced scanning has two tiers. The cost for container images scanned initially on-push to Amazon ECR is $0.09 per image scan. Each re-scan for container image in Amazon ECR configured for continuous scanning is $0.01 per image re-scan. Whenever Amazon Inspector adds a new CVE to its database, all eligible containers images in your configured Amazon ECR repositories are automatically re-scanned.

cc @ldraney @mjones-oddball @k-macmillan

**Comment by cris-oddball** [comment]
Twistlock instance came up with 2/2 checks passed.

**Comment by cris-oddball** [comment]
Twistlock scan completed on a deploy to Perf and status checks are still 2/2. Stable for the moment, but we need a plan here.

**Comment by cris-oddball** [comment]
TL fell over again on the next scan. Restarting to find logs and start removing them.

**Comment by cris-oddball** [comment]
Some logs in here that are candidates for deletion, specifically the messages one. 
-rw-------.  1 root   root            5556423 Jul 20 18:22 messages

**Comment by cris-oddball** [comment]
@ldraney with @k-macmillan 's green light, I deleted the /var/logs/messages file.

We need to run a cron job to delete that file once a week until we come up with a LT solution.

Twistlock scanned a few times without falling over, so we are good until this log fills up again.

**Comment by cris-oddball** [comment]
On two twistlock scans today, the server failed a status check (the scans were also run at the same time, in different environments.

Stopping and restarting to see how big the messages log is and to re-run those scans.

**Comment by cris-oddball** [comment]
Messages grew overnight:
```
-rw-------.  1 root   root            4458611 Jul 21 16:45 messages
```

**Comment by cris-oddball** [comment]
[Documentation on AWS CodeScan and Amazon Inspector](https://app.zenhub.com/files/257953872/021be54d-f4d7-4b43-998d-b2ec1441a864/download)

cc @k-macmillan @mjones-oddball @ldraney

**Comment by cris-oddball** [comment]
Twistlock has fallen over again, restarting and deleting the messages file when it comes back up.

**Comment by cris-oddball** [comment]
`-rw-------.  1 root   root            6060854 Jul 21 20:29 messages`

**Comment by k-macmillan** [comment]
That's only 5-6mb. I wouldn't expect issues? Is there anything interesting in there?

**Comment by cris-oddball** [comment]
@k-macmillan the output is all piped to CloudWatch, there are some interesting things in there, and (this is a guess) whatever is writing to that file is trying to open it and struggling to do so to add another line. That is not that big of a file as far as storage is concerned, but memory might be limiting the write operation.... which is why most log files are configured to roll over to a new file at a certain size (say, 1MB).

**Comment by cris-oddball** [comment]
Twistlock failed 1/2 status checks over the weekend. Restarting.

**Comment by ldraney** [comment]
Just waiting for Twistlock to restart:
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/00b517b9-a286-419d-8196-f83cff8f5af7)

**Comment by ldraney** [comment]
Cron job set up to delete twistlock logs every 24 hours:
```
sudo crontab -e
```
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/b781f1e8-53db-47ec-b3ee-6ac64f0ea770)

**Comment by ldraney** [comment]
I tested running twistlock and resource utilization was non-critical.
[Here is a video](https://drive.google.com/file/d/1qkxrJ3kDgcJ3h27v4nA9shQn5Begb-Fk/view?usp=sharing) of running twistlock with `top` open

**Comment by ldraney** [comment]
Twistlock running successfully:
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/938e2410-1fc2-4d1f-9923-5a8ca22e5320)

**Comment by ldraney** [comment]
I'm trying to connect to the instance but the screen is now blank:
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/f37cc060-60f2-4c60-be2f-a8a42e17b125)

**Comment by ldraney** [comment]
I'm stopping the instance to restart and get in and try a:
```
df -h
```
to see how much disk space we are utilizing.

**Comment by ldraney** [comment]
df -h gives us:
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/e6015853-2f57-4121-af7c-7acb4cac8f19)

And I tested twistlock again and saw that memory goes down to 49mb out of 200, (so we are at 75% memory utilization).  It might make the difference to increase the ec2 size at this point.

Also I wonder if there is something with the twistlock.yml action using the CLI to communicate with the ec2 that is somehow overwhelming the EC2... IDK.

**Comment by cris-oddball** [comment]
[Twistlock System Requirements](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/install/system_requirements) (geared toward the main server, which the twistcli connect to, does not specifically speak to what an instance running twistcli should be scoped to)

Twistlock documentation on [twistcli](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/tools/twistcli)

**Comment by ldraney** [comment]
I'm increasing to [t3.medium](https://aws.amazon.com/ec2/instance-types/):
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/494ce681-97e5-4f5f-ae03-a6c5d65ae58c)

**Comment by ldraney** [comment]
Also, since t3 is a burstable instance type that uses credits, it may be that we simply ran out of credits, which would severely limit the twistlock performance.

**Comment by ldraney** [comment]
[Latest video ](https://drive.google.com/file/d/1l2WiwxMy6lLaKpwU8T3_5I-3o8uNR51a/view?usp=drive_link)shows t3.medium at 75% usage

**Comment by ldraney** [comment]
So the cause is likely too small an ec2 for the twistlock:

I gathered the following data in the t3.medium:

1. **Not Under Load**:
    - Total Memory: 3977792 KiB
    - Used Memory: 958796 KiB
    - Total Used Memory = Used Memory + Buffers/Cache = 958796 KiB + 789184 KiB = 1747980 KiB
    - Percentage of memory used = (Total Used Memory / Total Memory) * 100 = (1747980 / 3977792) * 100 ≈ 43.94%

2. **Under Load** / running Twistlock:
    - Total Memory: 3977792 KiB
    - Used Memory: 1134212 KiB
    - Total Used Memory = Used Memory + Buffers/Cache = 1134212 KiB + 1991764 KiB = 3125976 KiB
    - Percentage of memory used = (Total Used Memory / Total Memory) * 100 = (3125976 / 3977792) * 100 ≈ 78.59%

Therefore, the memory utilization when not under load is roughly 43.94%, and under load, it is approximately 78.59%.

**Additional Test - Running Twistlock Twice Simultaneously**
- Total Memory: 3977792 KiB
- Available Memory: 104488 KiB
- Used Memory: 1202640 KiB
- Buffers/Cache: 2670664 KiB
- Percentage of memory used = ((Used Memory + Buffers/Cache) / Total Memory) * 100 = ((1202640 KiB + 2670664 KiB) / 3977792 KiB) * 100 ≈ 97.37%

The test of running Twistlock twice simultaneously shows that memory utilization spikes to approximately 97.37%.

Please, let me know if you need further information or testing.

**Comment by ldraney** [comment]
re-deployed ec2 t3.medium and redid the cronjob:
![image.png](https://images.zenhubusercontent.com/6361638d438b9c8e844e2b23/b02bf1af-15eb-4f87-824c-e395fcd1e4e2)
opening the PR now

**Comment by ldraney** [comment]
I'm not sure what to put on this follow-on spike ticket for twistlock.
Cris started a doc and I added to the end.  It sounds like we'll finish that doc and send it to Mel and Bev. I’m waiting to confirm this course of action with Cris and whoever before closing this ticket. 
Meanwhile, I think the best course of action is to leave Twistlock until our better solution is approved and available.

**Comment by mjones-oddball** [comment]
@ldraney Can you make sure @k-macmillan approves before any plans go to me or Bev to approve? Is it a cost thing that we'll need to approve?

**Comment by ldraney** [comment]
From Kyle:

> Lucas compare the cost of running t3.medium 24/7/365 vs the advanced scan costs. Try and grab how many scans we do per week and multiply it by 52 (a week will be more accurate than a day).
> TBH engineer costs to maintain Twistlock are likely greater than any cost for scanning.

**Comment by cris-oddball** [comment]
[Documentation for replacing Twistlock](https://docs.google.com/document/d/1h29Cuuy4rHFYBISjCe7JRW6H0dK4BLXPdk4U49XVqbo/edit?usp=sharing)

**Comment by cris-oddball** [comment]
@ldraney  to add costs to document and create new ticket, then we can close this one out.

**Comment by cris-oddball** [comment]
Twistlock failed 1/2 status checks again today and failed to run a scan. Stopping, restarting, and logging in to check things.

**Comment by cris-oddball** [comment]
restarted, it came back up, re-tried scan, that worked.

**Comment by cris-oddball** [comment]
From Lucas

> Well in the last fifteen minutes we got 1k errors saying VAEC network is unreachable.  Twistlock is set up on the AMI, and VAEC may have set up their own server
The way Twistlock works is it collects information about the packages and binaries in the container image and sends this data to the Prisma Cloud Console for analysis.  I'm guessing VAEC set up their own server for security reasons.
So, Twistlock may be failing due to reasons outside our control.  Another reason to move away from it, if I'm right.

Logs are now in DD, some patterns note that the failure is on some heartbeat to logstash/
```
Jul 27 HH:mm:ss
 ip-10-247-142-206 *
: yyyy-MM-ddTHH:mm:ss.SSSXXX
#011INFO#011[publisher_pipeline_output]#011pipeline/output.go:145#011Attempting to reconnect to backoff(async(tcp://aws-logstash-west.<redacted>)) with [1-210]
 reconnect attempt(s)

Jul 27 HH:mm:ss
 ip-10-247-142-206 *
: yyyy-MM-ddTHH:mm:ss.SSSXXX
#011ERROR#011[publisher_pipeline_output]#011pipeline/output.go:154#011Failed to connect to backoff(async(tcp://aws-logstash-west.<redacted>)): lookup aws-logstash-west.ecs.vaec.va.gov on 10.247.142.130:53: dial udp 10.247.142.130:53: connect: network is unreachable
```

**Comment by cris-oddball** [comment]
Info on audit logs
https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/audit/logging

Unable to connect to session manager, restarting.

**Comment by cris-oddball** [comment]
Lucas quadrupled the audit_backlog_limit

**Comment by cris-oddball** [comment]
Twistlock fell over again today.

**Comment by cris-oddball** [comment]
[ROI document ](https://docs.google.com/document/d/1PDToXij8woZfB1uzTJbqlQgtfFfprIk0-UUd8SuDH4o/edit?usp=sharing)for switching to AWS Inspector

**Comment by cris-oddball** [comment]
Story created for implementing [AWS Inspector](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1396)

**Comment by cris-oddball** [comment]
Next steps:

- @k-macmillan @mjones-oddball @cris-oddball to review #1396
- @k-macmillan to enable advanced scanning in AWS today to immediately replace Twistlock
- @ldraney to disable twistlock GitHub action from running on deploy today.
