### ISSUE TITLE
Internal DNS entry 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#138]
**As** a VANotify system owner
**I want** VANotify to be accessible on VA network
**So that** VA services can communicate with VANotify.

**Acceptance criteria:**
- [x] dev.api.notifications.va.gov points to our VAEC dev notification api load balancer
- [x] staging.api.notifications.va.gov points to our VAEC staging notification api load balancer
- [x] api.notifications.va.gov points to our VAEC prod notification api load balancer

This story depends on the Infra - need the Load Balancer DSN so that we can create appropriate CNAME records.

**Comment by ffafara-tw** [comment]
Opened up request for DNS change for dev environment in SNOW: CHG0111886

**Comment by ffafara-tw** [comment]
Opened up request for DNS change for staging environment in SNOW: [CHG0113855](https://yourit.va.gov/change_request.do?sys_id=e4ecddb21b72d0501f5e2062f54bcbbd&sysparm_view=&sysparm_domain=null&sysparm_domain_scope=null)

**Comment by ffafara-tw** [comment]
Opened up request for DNS change for staging environment in SNOW: [CHG0113859](https://yourit.va.gov/change_request.do?sys_id=159f9dfe1bf2d0501f5e2062f54bcb6b&sysparm_view=&sysparm_domain=null&sysparm_domain_scope=null)

**Comment by ffafara-tw** [comment]
Screenshot of DNS queries in VA network:

![notifications-domains-screenshot.png](https://images.zenhubusercontent.com/5da0974a66de7b0001e4d835/f16fa20d-7b07-4c66-87cf-ed08f93f6cd0)
