### ISSUE TITLE
Upgrade PyJWT>= 2.8.0 in requirements.txt

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1380]
Encountered a dependency conflict when attempting to update to PyJWT = 2.8.0

- [ ] Ticket is understood and QA has been contacted
### User Story
**As** VA Notify
**I want** to keep our service up to date
**So that** we are secure and as free of bugs as possible

### Additional Info and Resources
- Relevant section of [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-requirementstxt)

## Engineering Checklist
- [ ] Update performed
- [ ] Dependabot issues updated
- [ ] Any conflicts removed and tickets created
- [ ] Passes all tests locally
- [ ] Passes userflows and QA Suite testing against Dev
- [ ] Any major changes are investigated (compare existing to new version changes)
  - [ ] Any questionable version changes are removed and a ticket is created
- [ ] Tickets created are added to the Epic for tracking purposes

## Acceptance Criteria
Repo dependencies are updated and we have no broken functionality. Issues opened by Dependabot are resolved. Tickets created for any updates we could, or should, not do.

## QA Considerations
- [ ] Check to see if these updates cancel out any Twistlock issues
- [ ] QA Regression tests pass after deploying this code.

**Comment by kalbfled** [comment]
@justaskdavidb2 I'm confused about the conflict.  PyJWT 2.8 is consistent with the requirements you pasted.  Where is PyJWT[crypto]==2.7?  Did you upgrade that too?
