### ISSUE TITLE
Dependency Ticket Creation Automation

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1381]
## User Story - Business Need
The business need for this ticket is to automate the creation of dependency update tickets before each sprint planning, which streamlines the development process and ensures seamless, timeboxed updates. This automation aims to enhance efficiency and predictability in managing dependencies each sprint. 

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Development Team<br>
**I want** a GitHub action to automatically create a dependency ticket before Sprint Planning<br>
**So that** we have seamless updated to our dependencies and production application each sprint. 

### Additional Info and Resources

[Current dependency ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1365)

We'll be using the gh cli, but here is a [GitHub Actions example for issue creation](https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation) that may be useful as reference.  

CLI command for issue creation will be similar to (but will be adjusted according to the Github Runner setup):

```
wd qa
gh issue create \
-F /tmp/dependency-ticket-template.md \
--title "Regular update for Dependencies" \
--label Notify \
--label QA \
```

## Engineering Checklist

- [x] Convert current dependency tickets to templates in the api repo
- [x] Automate issue creation through a GitHub workflow that creates tickets using the CLI command provided
- [x] Have that workflow be triggered before the first Sprint Planning bi-weekly (i.e., for a once-a-month).
- [ ] Have a way to notify team that tickets are ready, such as:
     - Have an alert that ticket is created
     - Move the created issue automatically to ToDo

## Acceptance Criteria

- The GitHub action successfully creates a dependency ticket before each Sprint Planning.
- The template used for the ticket is the current dependency ticket.
- Ownership (Assignee) will be decided during Sprint Planning.

**Comment by npmartin-oddball** [comment]
Keeping.

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1381?planning-poker) with Zenhub @coreycarvalho
