### ISSUE TITLE
API: Upgrade mistunes to > 2.0.2

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1383]
**This should be worked sequentially with https://github.com/department-of-veterans-affairs/notification-utils/issues/129.**

Notify API uses version is v0.8.4 of the Python package "mistune", but the [current version](https://pypi.org/project/mistune/) is 3.x.x.  Complete this ticket immediately after the above notification-utils ticket, and merge changes for this ticket only after changes in the notification-utils repo are merged.

- [x] Discussed with QA

## User Story

As a VANotify team member and client,
I want to remove vulnerabilities identified by Twistlock,
So that I am assured that the app is not subject to compromise.

## Engineering Checklist

In requirements.txt:
- [ ] Upgrade [notification-utils](https://github.com/department-of-veterans-affairs/notification-api/blob/master/requirements.txt#L75) to the latest commit in the repo's master branch
- [ ] Upgrade [mistune](https://github.com/department-of-veterans-affairs/notification-api/blob/master/requirements.txt#L71) to the same [version used in notification-utils](https://github.com/department-of-veterans-affairs/notification-utils/blob/master/setup.py#L35)

## Acceptance Criteria

Building the local app image would pull in a bunch of other upgrades we don't want to consider for this ticket, so we will rely on Github to run unit tests.  Github will build a test image using requirements.txt.  Create a PR for the above changes, and . . .

- [ ] All unit tests pass in Github

## QA 
- [ ] Remove exception for rule in twistlock and re-scan to ensure it does not throw the same error.
- [ ] Close existing Twistlock ticket for Mistune

## Additional Info and Resources
- See this [ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/709).
- [Changelog](https://mistune.lepture.com/en/latest/changes.html)
  - NOTE: They do not have a changelog from before 3.x

**Comment by mjones-oddball** [comment]
Mistune is a sub-dependency of utils, so we need to update mistune in utils and then we need to update utils to automatically bring this in.

**Comment by mjones-oddball** [comment]
@kalbfled Can you please update the checklist and AC here to make sense? I understand most of the work will be done in utils.

**Comment by kalbfled** [comment]
After a group discussion, we decided that we need a different plan of action and will open new tickets.

**Comment by mjones-oddball** [comment]
The changes/impacts are so great that we are looking at a rewrite and possible replacement of mistune. This is way larger than the expected scope. We looked at Canada/UK and they stayed at the lower version for the same reasons. We will need to sync with Strike team to come up with the best and safest approach as this impacts formatting of email template previews and sends.
