### ISSUE TITLE
VA Profile integration lambda (opt-in) PyJWT dependency version lags the API testing version

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1386]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,
**I want** the Profile integration lambda's PyJWT version to mirror the version used for testing
**So that** a breaking change in PyJWT doesn't fail unit tests, and the lambda does not have any vulnerabilities.

### Additional Info and Resources

The Profile integration opt-in/out lambda function is [packaged using PyJWT v2.6.0 and cyptography v37.0.4](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/lambda-functions.yml#L114).  These are the versions actually deployed to AWS, but we also need those packages installed as part of the test image to run the lambda's unit tests.  The versions for the test image are newer.

The source of the problem is that PyJWT is a [top level dependency for API](https://github.com/department-of-veterans-affairs/notification-api/blob/master/requirements-app.txt#L52), so the [version used with the test image](https://github.com/department-of-veterans-affairs/notification-api/blob/master/requirements_for_test.txt#L13) must match to avoid a Docker build error.  We're testing the lambda with versions of the packages that are not the version being deployed.  The versions should be interlocked in all relevant files, but we've been overlooking them in lambda-functions.yml.

## Engineering Checklist

- [ ] Modify the [comment in requirements_for_test.txt](https://github.com/department-of-veterans-affairs/notification-api/blob/master/requirements_for_test.txt#L12) to call out the need to change the [versions in lambda-functions.yml](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/lambda-functions.yml#L114) as well.
- [ ] Modify the [comment in requirements-lambda.txt](https://github.com/department-of-veterans-affairs/notification-api/blob/master/lambda_functions/va_profile/requirements-lambda.txt#L5) to call out the need to change the [versions in lambda-functions.yml](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/lambda-functions.yml#L114) as well.
- [ ] Add a [comment for PyJWT in requirements-app.txt]() referencing the need to update that requirement in requirements_for_test.txt, requirements-lambda.txt, and lambda-functions.yml.
- [ ] Update the [PyJWT and cryptography versions in lambda_functions.yml](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/lambda-functions.yml#L114)

## Acceptance Criteria

- [ ] Unit tests pass
- [ ] Manually tested the lambda in Dev

**Comment by npmartin-oddball** [comment]
@cris-oddball will either modify or discard one of these two tickets.

**Comment by cris-oddball** [comment]
No longer needed, Poetry has replaced the requirements files for lambdas.
