### ISSUE TITLE
Add Validation Logging for Request Body

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1389]
It is not possible for us to properly assist clients when they face validation issues. They frequently do not know what they sent if it's in staging/prod. To be more client-centric we should log validation errors with what particular point failed. Redact personalisation fields, but not the entire personalisation.

## User Story - Business Need

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Client
**I want** VA Notify to know why our message failed
**So that** VA Notify can better help us

### Additional Info and Resources

Location of the place to put the log logic (inside the `if` block that starts on line 62)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/c597718b-28dc-47f5-bf3e-9b4e1d45bd6d)

## Engineering Checklist
- [x] Validation failures log the incoming json
- [x] No personalisation fields show their value. e.g. `{"personalisation": {"name": "bob"}}` would log as `{"personalisation": {"name": "<redacted>" }}`

## Acceptance Criteria

Validation failures resulting from the API raising an exception log the request body.
No personalisation details are logged.

## QA Considerations
- [ ] send a bad payload that will raise validation errors and confirm these are seen in the logs
- [ ] send a bad payload that will raise validation errors and confirm the log messages have personalizations redacted

## Out of Scope
This is specific to the request body validation that we're doing in the `validate` method in the API. This is not for the utils error logging such as for

**Comment by cris-oddball** [comment]
PR approved, merged and deploying to Perf for testing.

**Comment by cris-oddball** [comment]
TESTING IN PROGRESS - Perf

**Regression**


**Test One:** 
send sms without required payloads and personalization, ValidationError raised and personalization redacted in logs


Test Two: 
send email without required payloads and personalization, ValidationError raised and personalization redacted in logs

**Comment by ldraney** [comment]
@cris-oddball  Hey, did you get those boxes checked?  Thanks!

**Comment by cris-oddball** [comment]
@ldraney done - thanks for the reminder!
