### ISSUE TITLE
Twistlock to Amazon Inspector

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1396]
## User Story - Business Need
Twistlock is currently responsible for scanning our container images for vulnerabilities. Its drawbacks are that another team manages it, it is currently implemented on an EC2 instance that requires hand-holding, its user interface is not intuitive. AWS Inspector has been identified as a solid replacement. The VAEC has no requirements that we use one or the the specifically, so we are free to replace Twistlock.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify <br>
**I want** to implement Amazon Inspector for vulnerability scanning and replace our current system, Twistlock<br>
**So that** we can increase efficiency and cost-effectiveness while filling existing security gaps in our setup

### Additional Info and Resources

The goal of this ticket is to replace Twistlock with AWS Inspector.  This includes to begin scanning our Lambdas.  Currently, whenever we deploy, we get notified in Actions whether Twistlock passes or failed.  We need another method of getting notified if one of our images or lambdas have vulnerabilities when we deploy.  

Thus, the goal of this ticket is to:
1. Implement AWS Inspector via terraform.
2. Set up a way to automatically notify the team when deploying a new image to dev (preferably in Github Actions). 

A fair bit of knowledge has already been gathered in [this document](https://docs.google.com/document/d/1PDToXij8woZfB1uzTJbqlQgtfFfprIk0-UUd8SuDH4o/edit?usp=sharing), but actual implementation was outside the scope of that research.
Inspector provides real-time vulnerability detection in both OS and programming language packages, and it rescans automatically when there are changes to the workloads.
Switching to Twistlock eliminated three points of failure (Actions, Twistlock, and the EC2 AMI)

Notably, there are some implementation considerations:

1. AWS Inspector should be integrated via terraform to adhere to our IaC standard.
2. Appropriate IAM policies should be in place to permit Amazon Inspector access to the repository and choose the desired scanning settings.
3. The implementation includes both image scanner and lambda functions.
4. Remove Twistlock from our actions and infrastructure.

[Overview Document](https://docs.google.com/document/d/1PDToXij8woZfB1uzTJbqlQgtfFfprIk0-UUd8SuDH4o/edit?usp=sharing)
[Terraform docs on AWS Inspector](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/inspector_assessment_template)
[Medium Blog on Terraform Implementation](https://medium.com/appgambit/terraform-deploy-aws-inspector-a-cloud-based-vulnerability-assessment-tools-a4e2f5987e48)
[Implementation via GUI](https://aws.amazon.com/blogs/security/how-to-scan-your-aws-lambda-functions-with-amazon-inspector/)

## Engineering Checklist

- [ ] Implement the enhanced inspector via terraform
- [ ] Create appropriate IAM policies to enable AWS Inspector (with Terraform)
- [ ] Configure Amazon Inspector for image scanning and lambda scanning.  If setting up lambda scanning proves additionally complex, make a new ticket.
- [ ] Create documentation in team repo
- [ ] Remove Twistlock from our Github Workflows and our infrastructure

## Acceptance Criteria

- Amazon Inspector is successfully implemented and replaces Twistlock.
- All images and lambda functions are being scanned by Amazon Inspector.
- All changes are appropriately documented in the team repo.

## QA Considerations
- [ ] review the implementation to inform us how to manage what it reports

**Comment by npmartin-oddball** [comment]
Closing.
