### ISSUE TITLE
Determine deployment environment within VA

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/notification-api#14]
DSVA vs VAEC (we can't use Cloud.gov)

Are we allowed to just define our own lower environments? 

- [ ] Make cards once we have a decision

**Comment by marisahoenig** [comment]
@anushyaprasad to follow up with Alex

**Comment by kennedycollins** [comment]
We've agreed to use the TW AWS account to build until we're a couple weeks from going to prod; we'll also start applying for a VAEC account.

In a month, we'll revisit this and see if it's worth going into DSVA to get the benefit of whatever we have to deploy.
