### ISSUE TITLE
Implement Caching for API Keys Pt 2

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1404]
## User Story - Business Need
Our application make calls to SQL database for data that does not change often. dao_fetch_service_by_id_with_api_keys() makes the largest number of queries against our database. We would like to use a caching to reduce the frequency of the SQL queries against our database. 

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   developer 
**I want**  to implement in-memory caching
**So that** we reduce the frequency we query for infrequently changed data.

### Additional Info and Resources
- Previous [Spike](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1035)
- [Cachetools](https://pypi.org/project/cachetools/)
- [types-cachetools](https://pypi.org/project/types-cachetools/)
- [Example of Cachetools](https://www.javatpoint.com/python-cachetools-module)
- Steps to verify:
  - Datadog -> APM -> Select dev env -> click Postgres -> Select postgres.query from the dropdown at the top of the screen -> scroll down to the resources -> click the appropriate query -> observe graph

`AuthenticatedServiceInfo` class was created to store information coming out of `dao_fetch_service_by_id_with_api_keys` in an object unrelated to SQLAlchemy's models. Use/expand `__dict__`  method to make serialization work for caching.

## Engineering Checklist
- [ ] Add the following to modules: cachetools +  types-cachetools
- [ ] Add TTL decorator for `dao_fetch_service_by_id_with_api_keys()` see cachetools documentation
- [ ] `def __dict__(self)` of `AuthenticatedServiceInfo` adjusted to work with everything we need in the cache'd object
- [ ] `.deserialize()` method of AuthenticatedServiceInfo can restore objects if/when needed
- [x] verify that data going in cache and out of it identical and no information was lost (this was previously the case)
- [x] Caching time should be set to 10 minutes

## Acceptance Criteria
Making multiple requests in a short period of time from the same service does not show more than one request to the Database for the mentioned query.
 

## QA Considerations
This covers how to test dao_fetch_service_by_id_with_api_keys()
- [x] Test Case 1: should hit the database using a given input
- [x] Test Case 2: should call the function and hit the database once each
- [x] Test Case 3: should call the function with two different input and hit the database 2x, not 3x

We discussed the following in refinement:
The concept here is that if you are executing a route that validates api key (auth), then the subsequent requests for the following minute would use the cached the api key validation assuming the api key used has not changed.  It should also be faster than the first request. You should be able to see the caching being used vs the db query via cloudwatch logs. Example route, email notifications. Easiest way to test might be to use postman manually and sending the same request body multiple times.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1404?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by k-macmillan** [comment]
This ticket appears to have been prepped based on old information. That class does not exist and it is not necessary to go down to the `__dict__` level. 

I have added caching in the appropriate spot and the functionality is exactly as expected. Repeat requests with the same information (internally) result in the `ServiceData` class only being instantiated once every 10 minutes (per worker). Calls with different data result in instantiation of a new `ServiceData` class.

**Comment by cris-oddball** [comment]
Two approvals, merged to master, tagged and sent to Perf. Will test based on the criteria in the PR.

**Comment by cris-oddball** [comment]
Didn't exactly get what Kyle got in Dev, so I will need to wait for him to be in today to ask him about this testing. Sent two 10 email bursts 6 minutes apart and Datadog showed initially 10 database queries on the first burst then 1 db query on the second burst for a total of 11 DB queries.

<img width="1293" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTZXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81c12dbb31df2c564ef002ed9d38203535ce12b1/Screenshot%202024-01-03%20at%208.10.58%E2%80%AFAM.jpg" alt="Screenshot 2024-01-03 at 8.10.58 AM.jpg" />

**Comment by cris-oddball** [comment]
doah I get it, 4 workers per task, 3 tasks in Perf = 12 workers. so I should be sending more bursts.

**Comment by cris-oddball** [comment]
Testing by sending more than the number of workers in Perf, which is 3 tasks * 4 workers max = 12 max calls, so 20 per burst should do, send at least 6 minutes apart.

1st burst of 20 resulted in 16 calls to the DB
<img width="1693" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5beadaf2f3b8810a6cc05d77baa8724d94071e10/Screenshot%202024-01-03%20at%209.58.44%E2%80%AFAM.jpg" alt="Screenshot 2024-01-03 at 9.58.44 AM.jpg" />

a little after 6 minutes later, another burst of 20 emails and DB calls remained at 16?
<img width="1297" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODZXQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b74f937268432d89887249f607a88ed9f95ff7f3/Screenshot%202024-01-03%20at%2010.04.51%E2%80%AFAM.jpg" alt="Screenshot 2024-01-03 at 10.04.51 AM.jpg" />

Not really sure I'm understanding this correctly. @k-macmillan

**Comment by cris-oddball** [comment]
Kyle and I rested, but this time it made 20 calls to the db. also discovered that the failed v3 notification for the bad prefix was still being retried. Kyle cut a branch to kill that by catching the exception. deployed that to perf, which killed the retry, re-deploying master with the code for this ticket in it and will re-test after waiting 20-30 minutes.

**Comment by cris-oddball** [comment]
Retested by sending 20 requests via Postman, which resulted in 8 db calls (indicates not all workers used?), which is great.

<img width="1281" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWVYQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd6f6184589e18619c396cdf468cc9cf8880f544/Screenshot%202024-01-03%20at%2012.22.56%E2%80%AFPM.jpg" alt="Screenshot 2024-01-03 at 12.22.56 PM.jpg" />

Then waited and sent a burst of 50 via the hammer script. This resulted in a total of 13 DB calls, 1 more than expected. Possible race condition, but at the end of the day, the caching is working, but with slightly unexpected but not alarming results.

<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW1YQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67537a17c0d7ea8e4ffd20baafb4c50ee743d9cb/Screenshot%202024-01-03%20at%2012.35.39%E2%80%AFPM.jpg" alt="Screenshot 2024-01-03 at 12.35.39 PM.jpg" />

Passing and closing ticket.
