### ISSUE TITLE
Implement base HTML Email for govDelivery - Accessibility 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#141]
# Value Statement:
**As** a Veteran
**I want to** interact with the 526EZ confirmation email
**So that** I have a seamless experience 

# Acceptance Criteria
1.
**Given** I am using a screen reader on a macOS   
**When** I hear the 526EZ confirmation email 
**Then** the email reads appropriately

2. 
**Given** I am using a screen reader on a Windows 10 
**When** I hear the 526EZ confirmation email 
**Then** the email reads appropriately

3.
**Given** I am using JAWS
**When** I hear the 526EZ confirmation email 
**Then** the email reads appropriately

4.
**Given** I am using my keyboard on Chrome
**When** I interact with the 526EZ confirmation email 
**Then** I can navigate within the email successfully

5. 
**Given** I am using my keyboard on Firefox
**When** I interact with the 526EZ confirmation email 
**Then** I can navigate within the email successfully

6.
**Given** I am using my keyboard on Safari
**When** I interact with the 526EZ confirmation email 
**Then** I can navigate within the email successfully

7.
**Given** I am using my keyboard on Explorer
**When** I interact with the 526EZ confirmation email 
**Then** I can navigate within the email successfully

# Checklist:
- [x] Schedule a meeting with Trevor to understand how we can test accessibility (what to look out for, tools to use, etc)
- [x] Schedule live pairing session with Trevor for 508 compliance review (send Litmus preview link the day before)
- [x] Feedback from Trevor during initial call: ![accessibility-feedback-from-trevor.png](https://images.zenhubusercontent.com/5ecea5442d18e437e3b23d00/57001d56-0b49-487e-8c6d-1d6ac921c6fe)
- [ ] Document setup for rest of the team

# Assumptions:
- #92 (setting up the base HTML email) is complete
- Email clients: Apple Mail, Gmail, Outlook, Yahoo! 

# Additional Info/Resources:
- Voiceover with safari on Mac?
- Nvda with firefox?
- [VSP Accessibility Hub](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/platform/accessibility), pages of interest:
  - [508 Accessibility Best Practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-accessibility-best-practices.md)
  - Also for QA: [508 Checklist](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/508-checklist.md)
  - [Accessibility Dev Review Step-by-Step](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/teams/vsa/accessibility/accessibility-dev-review-step-by-step.md)
- Slack channel: #vetsgov-accessibility

# Out of Scope:
- [ ] 508 Request Form for tools

# Open Questions:
- What does it mean to "navigate within the email successfully"? Does that mean that tabbing works appropriately?
Yes, navigating would mean using tab or keyboard (keys/arrows) and some things I would check - navigating to VA logo, navigating to claim status link to access the claim status page, navigating to the Claim ID number, and no keyboard traps with the email notification
- What tools are we using to test accessibility? Is there a standard one that the VA uses?
We can use - JAWS, ZoomText, VoiceOver (macOS standard), and Windows also has a standard tool. The link to standard tools from the VA are [here] (https://yourit.va.gov/va?id=sc_cat_item&sys_id=30365aa71b0c9c9012979796bc4bcb19) I don't have access but ping me and we can look this up.  
- For each of the browsers mentioned, are there specific email clients we should be testing in?
I have added a note for email clients in Assumptions
- Should we pair with Trevor on this? (find out what tools he finds important)
Yes, I think Trevor would be a great to pair and get insights for this card
- FOLLOWUP ACTION: Figure out how to get tools, including the 508 Request Form

**Comment by QaysarA** [comment]
@marisahoenig sorry for the delay - Added notes for all the open questions, please ping me and we can sync if you have any additional questions. Or we can also discuss at kickoff.

**Comment by lingtran** [comment]
From pairing with Trevor where we went through the HTML template in Litmus yesterday, aside from a tag change (which would not impact styles) there are no blockers other than strong recommendations. Trevor ran our HTML through some automated validations and the axe browser plugin -- everything is in the clear. Next part of testing is manual!

Trevor's recommendations with respect to the HTML:
- For testing, decide baseline devices, including for tablet, wide screen, android and mac phones
- Touch base with Peggy Gannon regarding content, such as alt text (if we haven't done so already)
- Try to get a Plain Text preview (Litmus docs might have details on how to add this)
- Consider dl/dt tags in grey box if accessibility support is available
 
Resulting follow-up action items:
- schedule screen reader training with Trevor (1 hour), prior Trevor + Ling have 20 min trial prior (will schedule next week)
- schedule bug hunting with Trevor and team...need to use GFEs / provide checklist
- try to find way to get plain text preview (Litmus docs) (not a blocking issue)
- confirm with Todd that content approval including for accessibility have been involved in analysis prior

Also received positive feedback on pairing. Trevor acknowledged how his team does not do that often and from yesterday's session expressed desire to push pairing more within his team. :) 

Today: 
Implemented minor change in utils repo with h1 heading (does not impact design styles, it is merely to more accurately assist in screenreader), but working on getting tests to pass and debugging pytest issues

**Comment by lingtran** [comment]
Moving card to blocked until screen reader training with Trevor / bug hunting sessions have been held. TBD until dev huddle chat next week about new time

**Comment by lingtran** [comment]
Added some notes to vanotify-team repo with 'Getting Started with Accessibility' doc. Will update with more overview details as necessary in this process as we meet with Trevor down the line.

**Comment by lingtran** [comment]
From prep sync chat with Trevor today: 
Module 1 session:
_Mac_
VoiceOver (pre-installed)

Module 2 session:
* Team members with GFEs/Windows devices can try to check if they have either or both screen readers installed on machine
_Windows_
- JAWS
- NVDA

TBD in future session:
Accessibility in the Pipeline!

**Comment by lingtran** [comment]
Screen reader training sessions scheduled for Oct 7 and Oct 14.

**Comment by lingtran** [comment]
Screen reader sessions completed. Will upload recordings. Next step is to have a few folks do some bug bashing.

**Comment by lingtran** [comment]
Bug Bash spreadsheet with notes: https://docs.google.com/spreadsheets/d/1C-EtexOLFQnVMpJL_IIt3x6b5GBY7w3GmLMh0qm9eRs/edit?usp=sharing
