### ISSUE TITLE
Consolidate service permission checking into  .has_permissions method

### ISSUE THREAD

**Issue by nikolai-efimov** [department-of-veterans-affairs/notification-api#1410]
## User Story - Business Need

Code maintainability

- [ ] check with QA when ticket is understood

### User Story(ies)

**As a**  developer
**I want**  to have standardized method for checking permission on a service
**So that** we don't have several functions implementing different logic to check permission.

### Additional Info and Resources
Please use .has_permissions of Service and AuthenticatedServiceInfo to handle permission checking

## Engineering Checklist

- [ ] app/notifications/validators.py::service_has_permission 
- [ ] app/notifications/validators.py::check_service_can_schedule_notification
- [ ] app/template/rest.py::create_template

## Acceptance Criteria
- [ ] service_has_permission removed and all related functionality added to .has_permissions
- [ ] check_service_can_schedule_notification removed and all related functionality added to .has_permissions
- [ ] app/template/rest.py::create_template is using .has_permissions
- [ ] unit tests are passing
- [ ] regression tests are passing

## QA Considerations
- [ ] Regression passes
- [ ] Special attention is paid to the templates and schedule notification features (noting that templates is superseded by Portal creating templates and scheduling functionality is not currently in the QA Suite.

**Comment by mjones-oddball** [comment]
@nikolai-efimov for AC... how will we know that this is working as expected after the change is made? What route(s) are using the different method and what is the expected behavior for permission success and failure?
CC @k-macmillan @cris-oddball

**Comment by nikolai-efimov** [comment]
Unit tests and regression passing would be a good indicator. Updated.

**Comment by npmartin-oddball** [comment]
Not getting to this.
