### ISSUE TITLE
Create global cluster & test failover

### ISSUE THREAD

**Issue by nikolai-efimov** [department-of-veterans-affairs/notification-api#1411]
## User Story - Business Need

We want our data to be protected quickly recoverable in case of anything going wrong with a AWS region.

### User Story(ies)

**As a**  business
**I want**  to quickly failover to a standby instance of a database
**So that**  there is minimal data loss and service interruption in case of a disaster in one of the regions 

### Additional Info and Resources

https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/DatabaseDisasterRecovery.md#cost

https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1081

https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1137

## Engineering Checklist

- [ ] Global cluster is created
- [ ] RDS instances are added into the global cluster
- [ ] Backups still work
- [ ] Failover is tested
- [ ] App works as expected when failed over to another region

## Acceptance Criteria
- [ ] global cluster is created
- [ ] failover tested
- [ ] SOP for failover is created

**Comment by npmartin-oddball** [comment]
@coreycarvalho could you poke at the above questions?

**Comment by coreycarvalho** [comment]
This ticket is very unclear and I'm not sure what the original intention here is. Is it to provide an active-active strategy? Active-passive? Is it only meant to address data loss? What's the VA's stance on this? I say we close this ticket in favor of a broader discussion/spike of our failover strategy.

**Comment by npmartin-oddball** [comment]
@coreycarvalho notes that a failover strategy spike ticket would be valuable before implementation and will spin up a new ticket. Closing.
