### ISSUE TITLE
BUG: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1419]
## Description

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

Beginning around 5pm EST on August 10th (yesterday), we observed in Dev that the "send email" queue is overflowing, and our logs are full of tracebacks beginning with `'NoneType' object has no attribute 'replace'`.

![Screen Shot 2023-08-11 at 1 03 14 PM](https://github.com/department-of-veterans-affairs/notification-api/assets/5375929/af579672-442c-4084-adb8-73721a52eb82)

## Steps to Reproduce

Below are 2 POST requests to send e-mail that precipitated the problem.  Each uses a different type of recipient ID (EDIPI vs. Profile) that should refer to the same veteran.
```
{
    "billing_code": null,
    "body": "# QA Default Preference Test\nThis is a QA Test template for default preferences.",
    "completed_at": null,
    "cost_in_millicents": 0.0,
    "created_at": "2023-08-10T16:59:01.549574Z",
    "created_by_name": null,
    "email_address": null,
    "id": "c4f1dc07-5a2b-4160-82b2-652cb5d39f0f",
    "line_1": null,
    "line_2": null,
    "line_3": null,
    "line_4": null,
    "line_5": null,
    "line_6": null,
    "phone_number": null,
    "postage": null,
    "postcode": null,
    "provider_reference": null,
    "recipient_identifiers": [
        {
            "id_type": "VAPROFILEID",
            "id_value": "43627"
        }
    ],
    "reference": null,
    "scheduled_for": null,
    "segments_count": 0,
    "sent_at": null,
    "sent_by": null,
    "sms_sender_id": null,
    "status": "created",
    "status_reason": null,
    "subject": "QA Test Default Preference DEV",
    "template": {
        "id": "581bd747-d048-4f69-a77e-eee1d1a2b282",
        "uri": "https://dev-api.va.gov/v2/template/581bd747-d048-4f69-a77e-eee1d1a2b282/version/4",
        "version": 4
    },
    "type": "email"
}
```
```
{
    "billing_code": "qa-test-002",
    "body": "# Cat Ipsum Generator Info\n\nVisit the [Cat Ipsum Text Generator](http://www.catipsum.com/index.php) for some chunky text.\n\n## Congrats!\n\n__QA__ thanks _you_.",
    "completed_at": null,
    "cost_in_millicents": 0.0,
    "created_at": "2023-08-10T16:59:01.321250Z",
    "created_by_name": null,
    "email_address": null,
    "id": "ae18e88c-14fb-4552-850a-937d99accb41",
    "line_1": null,
    "line_2": null,
    "line_3": null,
    "line_4": null,
    "line_5": null,
    "line_6": null,
    "phone_number": null,
    "postage": null,
    "postcode": null,
    "provider_reference": null,
    "recipient_identifiers": [
        {
            "id_type": "EDIPI",
            "id_value": "1005079124"
        }
    ],
    "reference": "string",
    "scheduled_for": null,
    "segments_count": 0,
    "sent_at": null,
    "sent_by": null,
    "sms_sender_id": null,
    "status": "created",
    "status_reason": null,
    "subject": "A message from QA",
    "template": {
        "id": "52bfd6eb-dc89-4bee-a478-84d50f5af673",
        "uri": "https://dev-api.va.gov/v2/template/52bfd6eb-dc89-4bee-a478-84d50f5af673/version/1",
        "version": 1
    },
    "type": "email"
}
```

## Workaround

This isn't a workaround, but we purged the Dev queue.  We will fix this issue, rerun regressions, and check the logs again.

## Impact/Urgency

If this happens in production, it might crash the application.

## Expected Behavior

- [x] The above requests, which are both part of the regression tests, complete without causing any tracebacks
- [x] All regression tests pass in Dev
- [ ] The traceback no longer appears in the logs after the patch is deployed

## QA Considerations
- [ ] regression in Perf
- [ ] email negative testing (send some recipient identifiers that do not exist)
- [ ] sms negative testing (send some recipient identifiers that do not exist)

**Comment by cris-oddball** [comment]
Open questions:

**Open question #1:** the default visibility was not set for the SQS queue dev-notification-send-email-tasks as it was for the other three queue. Does it need to be set for this SQS given the high number of retries on a AssertionError from utils for validating the email address. **Should default visibility be set for this SQS queue to 3610 in perf, staging and prod**? Multiple workers retried this task.

We had two notifications constantly being retied from 8/10 3:15 PM MT until when Evan purges the queue shortly around the time of writing (8/11 1:45 PM MT) and 135k retries have been made for those two email notifications during that time. `c4f1dc07-5a2b-4160-82b2-652cb5d39f0f `and `ae18e88c-14fb-4552-850a-937d99accb41`

The QA DEV/INT VAPROFILE ID is `43627` and the EDIPI is `1005079124` (same user).
It looks like QuickSubmit added a communication_item for that user for **text** only - this should not have affected the email send. They added item 12 to this user with send allowed. The QA Suite test happens to use email template `581bd747-d048-4f69-a77e-eee1d1a2b282` that has the QuickSubmit Item 12 attached to it with the default_send_indicator True.


**Open question #2**: Given the above, should any retries have been made for this assertion error shown in the description's screenshot?

**Open question #3:** Why did this assertion error happen when that VAProfile ID has the same email address used for every other test send in the Suite: `vanotify.qa@gmail.com`

**Comment by cris-oddball** [comment]
I have searched the logs and at no point can I find that a lookup was made to VAPROFILE for this particular notification.

**Comment by cris-oddball** [comment]
Deployed master (without the 1344 code in it) back to DEV. User Flows failed. Output is truncated for the beginning part of this step. But the error seems to be the same for all tests: `E       KeyError: 'apiKeys'`

```
_______________ ERROR at setup of test_send_email_with_icn[dev] ________________
notification_url = 'https://dev.api.notifications.va.gov'
admin_jwt_token = ********, service_id = '93f39d73-c400-48c2-9b71-47e231a6855c'
user_id = '49db88f2-0712-420d-970f-521c5977e8a1'
@pytest.fixture(scope="session")
def service_test_api_key(notification_url, admin_jwt_token, service_id, user_id) -> str:
>       revoke_service_api_keys(notification_url, admin_jwt_token, service_id)
test_retrieve_everything.py:119: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
notification_url = 'https://dev.api.notifications.va.gov'
admin_jwt_token = ********, service_id = '93f39d73-c400-48c2-9b71-47e231a6855c'
def revoke_service_api_keys(notification_url: str, admin_jwt_token: str, service_id: str) -> None:
existing_api_keys_response = get_authenticated_request(
f"{notification_url}/service/{service_id}/api-keys",
admin_jwt_token
)
>       existing_api_keys = existing_api_keys_response.json()["apiKeys"]
E       KeyError: 'apiKeys'
steps.py:66: KeyError
____________________ ERROR at setup of test_send_text[dev] _____________________
notification_url = 'https://dev.api.notifications.va.gov'
admin_jwt_token = ********, service_id = '93f39d73-c400-48c2-9b71-47e231a6855c'
user_id = '49db88f2-0712-420d-970f-521c5977e8a1'
@pytest.fixture(scope="session")
def service_test_api_key(notification_url, admin_jwt_token, service_id, user_id) -> str:
>       revoke_service_api_keys(notification_url, admin_jwt_token, service_id)
test_retrieve_everything.py:119: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
notification_url = 'https://dev.api.notifications.va.gov'
admin_jwt_token = ********, service_id = '93f39d73-c400-48c2-9b71-47e231a6855c'
def revoke_service_api_keys(notification_url: str, admin_jwt_token: str, service_id: str) -> None:
existing_api_keys_response = get_authenticated_request(
f"{notification_url}/service/{service_id}/api-keys",
admin_jwt_token
)
>       existing_api_keys = existing_api_keys_response.json()["apiKeys"]
E       KeyError: 'apiKeys'
steps.py:66: KeyError
____________ ERROR at setup of test_send_text_with_profile_id[dev] _____________
notification_url = 'https://dev.api.notifications.va.gov'
admin_jwt_token = ********, service_id = '93f39d73-c400-48c2-9b71-47e231a6855c'
user_id = '49db88f2-0712-420d-970f-521c5977e8a1'
@pytest.fixture(scope="session")
def service_test_api_key(notification_url, admin_jwt_token, service_id, user_id) -> str:
>       revoke_service_api_keys(notification_url, admin_jwt_token, service_id)
test_retrieve_everything.py:119: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
notification_url = 'https://dev.api.notifications.va.gov'
admin_jwt_token = ********, service_id = '93f39d73-c400-48c2-9b71-47e231a6855c'
def revoke_service_api_keys(notification_url: str, admin_jwt_token: str, service_id: str) -> None:
existing_api_keys_response = get_authenticated_request(
f"{notification_url}/service/{service_id}/api-keys",
admin_jwt_token
)
>       existing_api_keys = existing_api_keys_response.json()["apiKeys"]
E       KeyError: 'apiKeys'
steps.py:66: KeyError
ERROR test_retrieve_everything.py::test_send_email_with_va_profile_id[dev] - ...
ERROR test_retrieve_everything.py::test_send_email_with_icn[dev] - KeyError: ...
ERROR test_retrieve_everything.py::test_send_text[dev] - KeyError: 'apiKeys'
ERROR test_retrieve_everything.py::test_send_text_with_profile_id[dev] - KeyE...
========================= 6 passed, 4 errors in 43.42s =========================
```


The logs starting at this time are filled with the utils errors as seen in the screenshot in the description.

**Comment by cris-oddball** [comment]
This has already generated hundreds of these AttributeErrors, just from the handful of messages sent via UserFlows

![Screen Shot 2023-08-11 at 3.01.37 PM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/98fdd9c6-b68f-42a9-954f-fbba2ac1bd66)

**Comment by cris-oddball** [comment]
Had to purge both queues to get the madness to stop

- dev-notification-celery
- dev-notification-send-email-tasks

**Comment by mjones-oddball** [comment]
Kyle: hotfix is going out tonight at 5 pm. This has been communicated. https://oddball.slack.com/archives/C03090DGL13/p1692037098009229

**Comment by cris-oddball** [comment]
After a merge to master, sending this up to Perf for testing. Regression today, negative testing tomorrow morning.

**Comment by cris-oddball** [comment]
Perf regression: 132 passed, 2 skipped, 3 xfailed in 137.13s (0:02:17

Negative testing tomorrow morning.

**Comment by cris-oddball** [comment]
**Negative testing**

1. send sms with an invalid VAProfileID, expect no tracebacks or retries, technical-failure
notification ID is f608bba3-cd29-4a4a-9bd8-6412eddb8189, VAPROFILEID is 1111
Logs
```
[2023-08-17 13:40:45,908: INFO/ForkPoolWorker-4] Pinpoint callback return status of technical-failure for notification: f608bba3-cd29-4a4a-9bd8-6412eddb8189
```
Received    
``` 
"status": "technical-failure",
"status_reason": null,
```

I just realized that this is a different negative path than the recipient identifier not having an email or phone associated with it. 

Pausing to think of how to obtain a recipient identifier that has neither an email or a phone.

Also, we really want to test a time-out to vaprofile and mpi, since that is likely what caused this to begin with.

**Comment by cris-oddball** [comment]
Closed because there is no currently viable way to test a timeout to vaprofile. Team agreed that we just wait, watch and see.
