### ISSUE TITLE
Tech debt: Exceptions used for flow control when looking up contact information

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1423]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,
**I want** the code to have explicit flow paths without side effects
**So that** the code is easy to understand, maintain, modify, and expand.

### Additional Info and Resources

- [Python typing](https://docs.python.org/3.8/library/typing.html)

Consider the methods [VAProfileClient.get_email](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/va/va_profile/va_profile_client.py#L44) and [VAProfileClient.get_telephone](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/va/va_profile/va_profile_client.py#L78).  These methods either return a string or raise an exception.  A better solution--one that is Pythonic and free of side effects other than logging--is for these methods to return Tuple[Optional[str], bool] where the boolean indicates to the upstream code if a retry should occur.

Similarly, [VAProfileClient._make_request](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/va/va_profile/va_profile_client.py#L165), which both of the above methods call, should return (Optional[requests.response], bool), where the boolean indicates if a retry should occur.

The Celery task [lookup_contact_info](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/contact_information_tasks.py#L29) calls get_email and get_telephone.  This should be refactored to use the revised return types described above and get ride of all the "try/except" blocks.  Note on [line 50](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/contact_information_tasks.py#L50) where the code explicitly indicates to Celery to discontinue async task chain execution (i.e. don't try to send a message when contact info couldn't be found).  Ensure that still happens where appropriate.  As currently implemented, raising exceptions is the mechanism to interrupt the flow.

Another problem with the current implementation is that is fills up the logs with tracebacks.

![Screen Shot 2023-08-17 at 8 34 47 AM](https://github.com/department-of-veterans-affairs/notification-api/assets/5375929/e9a498c3-c27b-456c-9a30-c04d2409db88)

## Engineering Checklist

- [ ] VAProfile._make_request returns Tuple[Optional[requests.response], bool]
- [ ] VAProfile._get_email returns Tuple[Optional[str], bool]
- [ ] VAProfile._get_telephone returns Tuple[Optional[str], bool]
- [ ] lookup_contact_info refactored as described above
- [ ] All unit tests updated; add new tests if appropriate

## Acceptance Criteria

- [ ] All unit tests pass
- [ ] The logs are not filled with sprawling exceptions about VA Profile
- [ ] All anticipated exceptions in the refactored code are caught at their source

**Comment by npmartin-oddball** [comment]
Closing. Will be adrressed in ep
