### ISSUE TITLE
SPIKE: Analyze and document retryable errors (part2)

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1437]
## User Story - Business Goal
We have gathered the known types of exceptions that are possible  and cataloged them in:
[Engineering/SPIKES/Analysis of Retryable Errors.md](https://github.com/department-of-veterans-affairs/vanotify-team/blob/c1c1ea798ebebf4778ac783c32a9644aaf36dd77/Engineering/SPIKES/Analysis%20of%20Retryable%20Errors.md)

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)
**As a** platform owner
**I want** to identify what exceptions are possible
**So that** the system does not waste time trying to reprocess a notification that requires manual intervention to succeed
<br>
**As a** business line sending notifications
**I want** temporary failures to retry
**So that** my notifications have a higher chance of delivery success
<br>
**As a** business line sending notifications
**I want** hard failures that have no chance for success to fail immediately
**So that** I can react quickly to understand and remediate the issue

### Additional Info and Resources
We have now mapped the know exceptions and which trigger retry and which do not. 
We now must track the "unknown exceptions" which have been logged by our application and have triggered multiple retries. 

The culprit to this investigation is can_retry() and its caller which simply evaluate if an exception has reached the max number of retries. The unknown exception is retried until the the max number of retries have been performed.

`def can_retry(retries: int, max_retries: int, notification_id: str) -> bool:
    """ Facilitates testing - Compares retries vs max retries returns True if retries < max_retries """
    current_app.logger.info("Notification id: %s, max retries: %s, retries: %s", notification_id, max_retries, retries)
    return retries < max_retries`

The above lines can be found by simply searching datadog or aws cloudwatch for the following string "max retries: 2886, retries: 5". 

- One recent error message that can cause us to continually retry a task that we do not want to retry is: InvalidPhoneError which we get when the phone number is invalid. It is believed that this is produced by notification-utils. You can find its occurrences by searching for "InvalidPhoneError" in the logs or notification-utils

- [analysis of know exceptions](https://github.com/department-of-veterans-affairs/vanotify-team/blob/c1c1ea798ebebf4778ac783c32a9644aaf36dd77/Engineering/SPIKES/Analysis%20of%20Retryable%20Errors.md)
- [retry policy] (https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/retry_policy.md)

## Acceptance Criteria & Checklist
- [x] Update SPIKE Documentation [here](https://github.com/department-of-veterans-affairs/vanotify-team/blob/c1c1ea798ebebf4778ac783c32a9644aaf36dd77/Engineering/SPIKES/Analysis%20of%20Retryable%20Errors.md)
- [x] REQUIRED: Schedule a team meeting to review learnings with team and decisions have been documented (Note: Please post summary in the team Slack channel prior to the meeting so that the team is prepared for discussion.)
- [x] Tickets for next steps have been identified and created. Please share in team channel before closing

#### Completed research addresses the problems and/or answers the questions below:  
Focus exclusively on finding those exceptions which are not mapped / known, the ones caught in the generic `except Exception as e ` block.
This time we will focus on only those exceptions that we do not know about - review the "Engineering/SPIKES/Analysis of Retryable Errors.md" to see the exceptions we know about.

1. What errors per method are retrying?
2. Which types of errors, which are currently being retried, do we think should not be retried? (e.g. configuration errors because they will never succeed until someone makes a manual change to correct the issue)

**Comment by mjones-oddball** [comment]
@babyjunior56 can you please post an update here from yesterday?

**Comment by tabinda-syed** [comment]
Posting this as a reminder in all our spike tickets this sprint, as a reminder from our Retro discussion yesterday:
Please be sure to prepare the team for the spike learnings discussion prior to the discussion/meeting itself by posting a summary on our team Slack channel.

**Comment by mjones-oddball** [comment]
@babyjunior56 did you make updates to the spike documentation? https://github.com/department-of-veterans-affairs/vanotify-team/blob/c1c1ea798ebebf4778ac783c32a9644aaf36dd77/Engineering/SPIKES/Analysis%20of%20Retryable%20Errors.md

Also, I didn't see that there was a team meeting. Did you meet with engineering? If so what was the outcome?
CC @EvanParish @tabinda-syed
