### ISSUE TITLE
Reduce Retries when sending emails and sms messages

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1441]
notification_utils.recipients.py can cause retries on celery tasks that require human intervention. An update in notification_api.provider_tasks.py functions will prevent these retries. 

## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)
**As a** platform owner
**I want** to not perform retries on celery tasks that requirement human intervention.  
**So that** the system does not waste time trying to reprocess a notification that requires manual intervention to succeed.

### Additional Info and Resources

We have listed all possible exceptions for these three celery tasks -- both in the notification_api and notification_utils.

- deliver_email
- deliver_sms
- deliver_sms_with_rate_limiting

We would like the following exceptions to be added to the code responsible for raising technical failures so we do not retry them:

- TypeError
- InvalidEmailError <- this exception already exist for deliver_email (so adding it to the other 2 functions is **only** recommended but not required
- InvalidPhoneError

Test cases can be modeled off of the following

```python
def test_should_technical_error_and_not_retry_if_invalid_email(sample_notification, mocker):
    mocker.patch('app.delivery.send_to_providers.send_email_to_provider', side_effect=InvalidEmailError('bad email'))
    mocker.patch.dict(os.environ, {'NOTIFICATION_FAILURE_REASON_ENABLED': 'True'})

    with pytest.raises(Exception) as exc_info:
        deliver_email(sample_notification.id)

    assert exc_info.type is NotificationTechnicalFailureException
    assert sample_notification.status == 'technical-failure'
    assert sample_notification.status_reason == 'Email address is in invalid format'
```

## Engineering Checklist

- [ ] Add test cases that trigger the above mentioned exceptions
- [ ] For each function, Add the above mentioned exceptions to the exception handling found under 
`except (NullValueForNonConditionalPlaceholderException, AttributeError, RuntimeError) as e:`

## Acceptance Criteria

- [ ] Test case are created for checking for the above mentioned exceptions
- [ ] The above mentioned exceptions have been added to the each function to prevent retries
- [ ] Received NotificationTechnicalFailureException when running test with: test_send_one_off_notification_raises_if_invalid_recipient()
Note: This would normally trigger a "InvalidPhoneError", but will no longer do this because "_get_delivery_task()" will no longer raise that exception.

## QA Considerations
Recommend Adding test cases to trigger the above mentioned exceptions. These exceptions should return NotificationTechnicalFailureException

**Comment by npmartin-oddball** [comment]
Closing. Another ticket already in play.
