### ISSUE TITLE
BUG: Pinpoint Successful Status Sent vs Delivered

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1449]
## Description
Amazon provides multiple statuses which equate to delivered. When we receive `event_type=_SMS.SUCCESS` and `record_status=SUCCESSFUL` then we should be mapping to delivered instead of sent. This is affecting our statistics in portal and DOMO and is creating confusion as to why statuses are returned differently with us and clients (callbacks).

According to Amazon:
event_type: `_SMS.SUCCESS – The message was successfully accepted by the carrier/delivered to the recipient.`
record_status: `SUCCESSFUL/DELIVERED – The message was successfully delivered.`

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

It's unclear how to process a successful result from pinpoint vs delivered. It may have to do with carriers or other factors we're unaware of in how pinpoint processes downstream results. However, you can see with the BHL service that the majority of their statuses are sent. Upon tracing back their notifications you see the following:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcytQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5cf1bd48dc44bad62e1562d0b5cf11cae2c803d7/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdEtQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--57d5146b91400faf0af4696a0510acf9fbf5f2d4/image.png)

Compared to Delivered:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaW1RIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--687cfca38f07dc757d5862171a4ab0b2fd3622c4/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdFdQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d4f6e2365a39b8643e0fbcd3244a5ed58d9ecb27/image.png)

## Workaround

None

## Impact/Urgency

This is skewing statistics and creating confusion. Our team has spent a lot of time investigating why things were not in a delivered status to ensure there were no issues. We need to be able to reduce the noise and understand when things are delivered, in an unknown status, or failed.

## Expected Behavior

- [x] When we receive a `SUCCESS` event_type from Pinpoint and the record_status is `DELIVERED `or `SUCCESSFUL`, then we must update the delivery status to `delivered`

- NOTE: Work deferred to #1467 so leaving this box unchecked. [ ] Following this change we should do a data cleanup in our production database and bigquery to update pinpoint sms statuses from sent to delivered. Please use transaction to review your results prior to committing and test in lower env(s) before doing in production.

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- depends on outcome of convo with developer. at the very least, some messages should be sent and logs reviewed to determine what is happening.

## Additional Info & Resources

Searchable log phrases:
To find callback results (pair with a notification id)
"Pinpoint callback status of sent" or "Pinpoint callback status of delivered"

To find pinpoint status results (pair with a provider reference id)
"record_status=SUCCESSFUL" or "record_status=DELIVERED"

Amazon Pinpoint Statuses: https://docs.aws.amazon.com/pinpoint/latest/developerguide/event-streams-data-sms.html

**Comment by EvanParish** [comment]
The code is complete. I need to update the notification statuses from "sent" to "delivered" for pinpoint messages the Dev db, then do so in other environments as the code gets pushed up.

**Comment by EvanParish** [comment]
@cris-oddball this change was [deployed to perf](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/6331522072) and passed QA regression suite

**Comment by cris-oddball** [comment]
Sending code up to Staging for review due to Perf's instability due to new NR subnets

**Comment by cris-oddball** [comment]
And all this time I just thought that the AWS simulated numbers only returned a sent status and not a delivered status. Now the QA suite passes with the sms notifications tests changed to only check for 'delivered', same as email. 

Pushing a PR up for the QA suite.

**Comment by cris-oddball** [comment]
Leaving this up for a few hours and will check logs in staging later today.

**Comment by cris-oddball** [comment]
Post deployment, a review of logs in staging shows the following, indicating this code is working as expected beyond the regression suite.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakRyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d88df9a5e4a10e20e1fcf304b68895207bd21b4e/Screen%20Shot%202023-09-28%20at%2012.54.35%20PM.jpg)
