### ISSUE TITLE
Store assets for VANotify - interim approach

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#145]
# Value Statement:
**As** a VANotify developer 
**I want to** store assets in an environment
**So that** they can be retrieved in production

# Acceptance Criteria
**GIVEN** VANotify sends an email 
**WHEN** the environment is within the VA 
**THEN** the asset displays from the respective interim storage

# Checklist:
- [ ] Checklist item here

# Assumptions:
- This is an interim approach and additional details on this will be documented in #147

# Additional Info/Resources:
- The existing approach for the VA Logo needs to be resolved to work in Production 
- Sync with Filip on options that he has already discussed for the interim solution, and the limitations with the VA  
- Document the interim decision on how/where to store assets
- From Filip Fafara 
 src="https://dev-notifications-va-gov-assets.s3.us-east-2.amazonaws.com/va-logo.png" 
src="https://notifications-va-gov-assets.s3.us-east-2.amazonaws.com/va-logo.png” 

# Out of Scope:
-

# Open Questions:
-

**Comment by ffafara-tw** [comment]
The logo is stored here:
https://prod-va-gov-assets.s3-us-gov-west-1.amazonaws.com/img/vanotify-header-logo.png
