### ISSUE TITLE
Pinpoint Lambda Speedup

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1466]
## User Story - Business Need
The `project-dev-pinpoint-callback-lambda` runs around 300ms per request it processes (every message coming back from pinpoint). This is an unreasonable amount of time given the operations it is doing. 

Move the boto3 resource and queue objects outside of the handler and into the execution environment. 

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** technical lead
**I want** to use our funds efficiently
**So that** we can keep our system from being a burden

### Additional Info and Resources

The bottom of this image shows where we init with the current code, the 4 billed sessions above that are also utilizing the existing code. Then at 12:02:37 the code was changed as suggested in this ticket. The tests after the code change averaged 15x speedup, meaning 15x reduced cost. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0RrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--25488bd07c5b39581d7d0bdce360b71f367e7afb/image.png)

## Engineering Checklist
- [x] sqs and queue set in execution environment
- [x] Code wrapped in try/catch, logging the event along with what the failure was
  - These boto3 `resource` and `queue` classes are just objects, not connections. `queue.send_message` is similar to `requests.post`, but with better context managing. This should never fail but we should still catch and log it.
- [x] Update the Slide deck with the key win and a demo slide

## Acceptance Criteria

- [x] Still able to send sms and receive pinpoint updates (notification updates). 

~Code is placed on staging at least 1 week prior to prod deployment to ensure there are no side-effects.~ (In standup we agreed that this was not necessary)

Current `sqs` and `queue` variables:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2ZrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b7c913cefe2a982fbed278dcd30a74fdbe7386ea/image.png)

New location of `sqs` and `queue` variables:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbERrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6840e259665022be78ef84900db1a994f634fe2a/image.png)

## QA Considerations

- [ ] Perf regression tests pass

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1466?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @MackHalliday @mchlwellman @kalbfled

**Comment by cris-oddball** [comment]
PR approved and merged, deploying to Perf to validate the lambda and callabcks specifically.

**Comment by cris-oddball** [comment]
**QA PASSED**

- delivery works as expected
- callbacks work as expected

Closing ticket and sending to staging/prod
