### ISSUE TITLE
Clean up Pinpoint delivery statuses in Prod post-deploy

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1467]
## User Story - Business Need
Work was done on #1449 such that when we receive a SUCCESS `event_type` from Pinpoint and the `record_status` is DELIVERED or SUCCESSFUL, then we must update the delivery status to delivered such that there is basically not a 'sent' status any longer for Pinpoint (Twilio may still have this status)

We should do a data cleanup in our production database and bigquery to update pinpoint sms statuses from sent to delivered. Please use transaction to review your results prior to committing and test in lower env(s) before doing in production.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want** no Sent statuses in the database for messages sent via Pinpoint
**So that**  the DB conforms to the most recent refactor.

## Engineering Checklist

- [x] Write & test the query in the lower environments prior to the Prod deploy
- [x] Post prod deploy, perform a data cleanup in our production database and bigquery (env-statistics tables) to update pinpoint sms statuses from sent to delivered

## Acceptance Criteria

- [x] Prod no longer has sent statuses in the DB or BQ for Pinpoint messages
- [ ] @mjones-oddball to review BQ prod and Domo customer stats the following day

**Comment by EvanParish** [comment]
@mjones-oddball All updates have been completed. Leaving this ticket open for you to check off the last box for the acceptance criteria.

**Comment by mjones-oddball** [comment]
@EvanParish Looks good. The past 3 days of data was updated last night as expected so the only sent items are from that in the VEText service (twilio data).
