### ISSUE TITLE
[Filip to repurpose] Approach with storing assets for VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#147]
Filip to add details on the options that were discussed. 

*Notes:*
- The existing approach for storing VA assets needs to be resolved to work in Production
- Interim approach for storing assets is in card #145
- Additional card/s will be created once the approach is finalized 
- Sync with Filip on options that he has already discussed for the interim, and the limitations with the VA
- Document the decision on how/where to store assets for VANotify

**Comment by anushyaprasad** [comment]
@ffafara-tw confirming that this story is no longer needed? Is it being handled differently or elsewhere?

**Comment by ffafara-tw** [comment]
Not needed. Please see ADRs for more information about considered apporoaches.
