### ISSUE TITLE
Remove dao code related to letters

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1474]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,
**I want** to remove unused code and other technical debt
**So that** the code base is easier to maintain.

### Additional Info and Resources

Recent tickets removed routes and route tests associated with sending letters and PDFs.  This ticket is to remove dao code that is now unused and to remove tests of that code.

## Engineering Checklist

The following PRs delete a lot of code.  Audit the deleted code for the removal of import statements for dao functions.  If a dao function isn't used elsewhere, delete the dao function, and delete or change affected dao tests.

- [ ] [1457](https://github.com/department-of-veterans-affairs/notification-api/pull/1457/files)
- [ ] [1458](https://github.com/department-of-veterans-affairs/notification-api/pull/1458/files)
- [ ] [1460](https://github.com/department-of-veterans-affairs/notification-api/pull/1460/files)

The Notification model includes a bunch of unused attributes for letters.  For example, "postage".

- [ ] Remove unused letter Notification attributes, and create a migration.

## Acceptance Criteria

- [ ] The code has been deleted, and all unit tests pass.

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [ ] double-check responses for any removed properties and do the needful with the regression suite
- [ ] run regression in perf and ensure things work as expected

## Out of Scope

This does not fully remove letter-related code.  ~~For example, the Notification model has columns like "postage".~~

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1474?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by kalbfled** [comment]
We discussed in Refinement that this should include a migration to remove unused letter fields.  That's currently "out of scope."

**Comment by npmartin-oddball** [comment]
Closing/no longer relevant.
