### ISSUE TITLE
Remove celery task letters_pdf_tasks

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1479]
## User Story - Business Need
In #1178, we removed the routes associated to the routes: 
- /v2/notifications/<notification_id>/pdf
- /v2/notifications/letter

In this ticket, we will be removing the celery task `letters_pdf_tasks` located at `app/celery/letters_pdf_tasks.py.` Please keep in mind that this ticket will produce about 8-10 files that will need to be updated. 

**Impacted scripts**
- app/commands.py
- app/celery/tasks.py
- app/notifications/process_notifications.py
- tests/app/v2/notifications/test_letters_pdf_tasks.py <- will need to be removed
- tests/app/celery/test_tasks.py
- tests/app/notifications/test_process_notifications.py
- tests/app/v2/notifications/test_post_letter_notifications.py 
- app/v2/notifications/post_notifications.py. 

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   engineer
**I want** to clean up and reduce our codebase.
**So that** it is easier to maintain and upgrade in the future.

### Additional Info and Resources

You can use this [#1178](https://github.com/department-of-veterans-affairs/notification-api/pull/1460) PR as an example of what can be used to clean up data. 

## Engineering Checklist

- [x] Removed celery task letters_pdf_tasks.py
- [x] Remove test case test_letters_pdf_tasks.py
- [x] Remove impacted dependencies that used these 2 scripts

## Acceptance Criteria

- [x] All methods called by these removed unless used elsewhere, other than the DAO methods (removed in their own ticket)
- [x] Code deploy to dev without issues
- [x] QA Regression Test Pass

## QA Considerations
- [x] The QA Regression Suite passes

## Potential Dependencies
- [utils 141](https://github.com/department-of-veterans-affairs/notification-utils/issues/141)

## Out of Scope
Do NOT delete any related dao objects related dao  because [#1474](https://github.com/department-of-veterans-affairs/notification-api/issues/1474) will do that. 

Any code that is not required to be modified as a direct result of the removing the celery task and its test case.

**Comment by mchlwellman** [comment]
I have removed the two dependencies, however there are some questions regarding other letter-related code. (See PR)
