### ISSUE TITLE
User Table Queried Excessively

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1480]
## User Story - Business Need
We are making an excessive amount of requests to our read db as a result of the changes to enable our connection to the read db. This was an unintended side-effect of creating new data classes for the service and api key objects. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNllFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36384e0360be533c4efd8e64418e10d583c73243/image.png)

The ORM currently lazy loads the value, but since we replicated the data into a format that could be persisted it led to queries to `users` for every key in the table until it found the match (or lack of match). This results in millions more calls than are necessary (we don't need the `user` most of the time). 

This ticket is to implement a way to lazy load the `created_by` and/or `created_by_id` values into the `ServiceDataApiKey` class so they are not queried unless required. 

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** tech lead for VA Notify
**I want** to query the DB only when necessary
**So that** we are efficiently using our assets

### Additional Info and Resources

- SQL Alchemy [sessions](https://docs.sqlalchemy.org/en/20/orm/session_basics.html#session-basics)
- [Proper query syntax](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-20-query-usage) (use 2.0)
- As of the last time checked, **44** queries are executed for every email notification in Dev for the VA Notify service

Dev queries:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGtGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5365e7e9bdaf70c2e34b3fc53fa5c2e7866ccd70/image.png)
Can be found under APM, change environment to dev (top left) and narrow the time band to when you send the request.

## Engineering Checklist

- [ ] email notification sent in dev does not query the user table unless one or two queries is absolutely necessary
- [ ] `ServiceDataApiKey.created_by` and/or `ServiceDataApiKey.created_by_id` utilize a lazy-load style, where no additional queries are ran unless required
- [ ] Queries written are to the new SQL Alchemy 2.0 syntax linked above
- [ ] New tests written if applicable

## Acceptance Criteria

- [ ] The query linked above is not called when we send an email notification, or is called the minimum number of times required (no more than 2)
- [ ] SQL Alchemy 1.x syntax not used

## QA Considerations

- [ ] All regression tests pass
- [ ] Edge cases discussed with the engineer

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1480?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @nikolai-efimov @ldraney

**Comment by k-macmillan** [comment]
Fumbled for a while trying to understand how to make it not query at all. That was not possible because some tests will trigger the information but regular email/sms/push should not call the `created_by` field.

Got it to pass all tests that were failing for detached instance by executing the query if the field is called. What I found online about detached was basically "query it again". There was one test that used admin auth but was still looking for a user, for that case it failed no matter what was tried. I removed the user from the test since it was not necessary and that fixed the issue.

I will coordinate with @cris-oddball tomorrow regarding edge cases.

**Comment by k-macmillan** [comment]
The PR has been merged. 
Everything is working exactly as expected, including TTL cache (tested, not implemented).

**Comment by cris-oddball** [comment]
QA TESTING

Definitions:
I call this user query "WHERE users.id = ? "
```
SELECT users.identity_provider_user_id, users.id, users.name, users.email_address, users.created_at, users.updated_at, users._password, users.mobile_number, users.password_changed_at, users.logged_in_at, users.failed_login_count, users.state, users.platform_admin, users.current_session_id, users.auth_type, users.blocked, users.additional_information 
FROM users 
WHERE users.id = ?
```

I call this user query "WHERE ? = user_to_service.service_id AND users.id = user_to_service.user_id"
```
SELECT users.identity_provider_user_id, users.id, users.name, users.email_address, users.created_at, users.updated_at, users._password, users.mobile_number, users.password_changed_at, users.logged_in_at, users.failed_login_count, users.state, users.platform_admin, users.current_session_id, users.auth_type, users.blocked, users.additional_information 
FROM users, user_to_service 
WHERE ? = user_to_service.service_id AND users.id = user_to_service.user_id
```

**Regression that ran at 3:15am MT showed the following calls:**
- 490 requests to notification-api and 523 to WHERE users.id = ? clause
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1lUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--455d4c6419c0e244d8afd1958013607328226008/Screen%20Shot%202023-10-06%20at%201.17.18%20PM.jpg)

- 245 requests to notification-api and 245 to WHERE ? = user_to_service.service_id AND users.id = user_to_service.user_id
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2NUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--042cd97a7a2ed4f225876c5baafb979a46137486/Screen%20Shot%202023-10-06%20at%201.17.53%20PM.jpg)


**Regression that ran directly after the deploy showed the following calls:**
- 15 requests to notification-api and 33 to WHERE users.id = ? 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2dUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b03b9f59579a8ab66f55b6353e7b4b138c544072/Screen%20Shot%202023-10-06%20at%201.20.30%20PM.jpg)

- 236 requests to notification-api and 236 requests to WHERE ? = user_to_service.service_id AND users.id = user_to_service.user_id
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca77b529307f4d4b66b11c43c2b82db5908353c1/Screen%20Shot%202023-10-06%20at%201.19.42%20PM.jpg)

**Comment by cris-oddball** [comment]
QA TESTING - PASSES
