### ISSUE TITLE
Remove API associated to app and letter

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-api#1482]
## User Story - Business Need
In #1178, we removed the routes associated to the routes
In #1479, we removed the celery tasks for letter
In this ticket, we remove the associate that notification-api has with the utils' letter and pdf

You are being asked to remove the folders:
- app/letters
- test/app/letters

**Impacted scripts at a minimum**
_Please keep in mind that this ticket will produce about 8+ files that will need to be updated._

- app/__init_.py
- app/dao/notifications_dao.py
- App/letters <- entire directory
- App/service/rest.py
- App/template/rest.py <- careful
- App/v2/notifications/post_notifications.py
- test/app/letters <- entire directory

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   engineer
**I want** to clean up and reduce our codebase.
**So that** it is easier to maintain and upgrade in the future.

### Additional Info and Resources

You can use this [#1178](https://github.com/department-of-veterans-affairs/notification-api/pull/1460) PR as an example of what can be used to clean up data. 

## Engineering Checklist
**Plan of execution: Delete the listed items and immediately raise any issues in engineer chat**
- [ ] Removed app/letters directory
- [ ] Remove test case associated to tests/app/letters directory
- [ ] Remove impacted dependencies that use these these two directories

## Acceptance Criteria

- [ ] QA Regression Test Pass
- [ ] Code deploy to dev without issues

## QA Considerations
- [ ] check QA Suite models for any properties that need to be removed/altered
- [ ] The QA Regression Suite passes

## Potential Dependencies
- [utils 141](https://github.com/department-of-veterans-affairs/notification-utils/issues/141)
- [1479](https://github.com/department-of-veterans-affairs/notification-api/issues/1479)
***Do not recommend that this ticket be touched until after the celery tasks have been removed***

## Out of Scope
- any dao objects because [#1474](https://github.com/department-of-veterans-affairs/notification-api/issues/1474) will do that. 

- Any code that is not required to be modified as a direct result of the removing the these two directories

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1482?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by npmartin-oddball** [comment]
Closing/no longer relevant.
