### ISSUE TITLE
BUG: Twilio delivered messages getting stuck in sent

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1488]
## Description
There are a large number of Twilio SMS messages getting stuck in sent status in our system, which is unusual. I'm seeing about 1000-3000 a day for VEText recently.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1.  Search the prod database for recent twilio notifications where the status is sent
2.  Search the logs with the provider reference id and "Processing Notification Delivery Status" to see all relevant statuses from the provider
3.  Check the order and timing of when statuses came in - if you see a delivered status then that should be what the notification status is set to

Example below. Hypothesis: This could be due to a race condition because the 2 statuses are being processed asyncronously and the timestamps are very close together.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzBaQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c77891740156f360db36a5441f88fc07c997aa42/image.png)

## Workaround

No workaround

## Impact/Urgency

Data integrity issue. This impacts our delivery rates that we report to clients and leads them to believe less messages are being delivered as a result.

## Expected Behavior

**Note - we know that statuses can come in out of order. See related ticket that previously addressed this bug in additional resources.**

- [x] When we receive a delivered status from Twilio, then we should update the notification status in our database and no further status updates should be processed.
- [x] The logic is handled within the DB [query](https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html#orm-queryguide-update-delete-where) (do not use `dao_update_notification` because db.session.add is insufficient)
- [ ] API logic removal ticket created
- [ ] Create a separate ticket for data cleanup in our database and bigquery. This can only be completed after the bugfix is deployed to production.

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

This doesn't happen on all notifications, but seems to happen enough that we should be able to replicate it. You'd want to check the logs and see the order statuses are coming in. You are looking for cases where sent comes in after delivered to ensure that we don't overwrite the delivered state.

## Additional Info & Resources

- This bug was fixed regarding lesser status updates overwriting the final state - https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1294

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1488?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by cris-oddball** [comment]
I was able to reproduce this on the very first try in Perf prior to this fix using the AWS simulated number with "provider_reference": "SMf8cbc3e89f1c37421829c66132347f59", "id": "336b4901-06e8-4b8f-994d-fb250fac792a", - so I have high hopes to be able to validate any fix.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEIzQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a06b180c27b169c9b54e3c9ce76704cdfcf4fd5a/Screenshot%202023-10-26%20105102.png)

**Comment by cris-oddball** [comment]
Branch was deployed to Dev; QA branch to support change used to regress code on Dev - Passed.
Branch was deployed to Perf; QA branch to support change used to regress code on Perf - Passed.

Holding API tag until Monday at Noon ET to support getting this into the deployment next week.

**Comment by cris-oddball** [comment]
Latest commit pushed up to Perf. 
- regression passed
- actually got to see the logs in action
```
[2023-10-30 14:04:45,428: WARNING/ForkPoolWorker-4] An erroneous attempt was made to transition notification id 04dcdb7c-cc94-4289-8ff6-8b7452da4ddc from sent to sending
```
- sent 10 back to back messages to Twilio, all 10 report a delivered status (previously one or more out of ten would be stuck in some earlier state.


Awaiting next PR revision and approvals prior to cutting the API tag.

**Comment by cris-oddball** [comment]
PR approved and merged. Final round of testing on Perf as soon as it is deployed.

**Comment by cris-oddball** [comment]
**PASSED** With updated QA master, ran the [regression](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/6696850158) against Perf. There are two Twlio tests and both should return a value of 'delivered' for the notification status. 

**PASSED** Then, executed ~20 Twilio sends manually in Postman as back-to-back as possible when manually testing. All should return a final delivery status of 'delivered'. (and they did indeed all return delivered as a final status)
```
5e45c069-e044-47df-9c86-a282fa6424e2
4a577d38-5367-4e84-8a4d-dfaf567001a2
b3b08e90-4e9c-4b3f-b4ce-157e9202ce84
196c7871-d1de-4dfb-b66a-45ac9425d51e
21201a82-c7d8-41d6-987e-4f984b6fbadd
b1fbcc14-12fd-406a-98d2-e6048240d82b
24a9ec40-f8dc-490f-9022-1306ad0bd0e9
0859819d-e109-4dfb-8460-6619b1029864
728846e7-0d20-40a0-9525-476181791af6
5068c707-8a7f-4f07-bebc-46cf01b017ee
[2023-10-30 18:07:31,071: WARNING/ForkPoolWorker-4] An erroneous attempt was made to transition notification id 5068c707-8a7f-4f07-bebc-46cf01b017ee from sent to sending

54f30a07-8f31-4edb-92c4-eb786fa361e1
d6d58d47-f859-46b4-a926-99ca9078f316
[2023-10-30 18:07:46,570: WARNING/ForkPoolWorker-4] An erroneous attempt was made to transition notification id d6d58d47-f859-46b4-a926-99ca9078f316 from sent to sending

5817b9fb-18e2-49fa-a50d-5249006c1f70
[2023-10-30 18:07:53,555: WARNING/ForkPoolWorker-4] An erroneous attempt was made to transition notification id 5817b9fb-18e2-49fa-a50d-5249006c1f70 from sent to sending

00318068-ee55-48f1-a74d-ede51bbb5111
833e212c-af4b-45ed-b061-abfa7aff5e41
1f7f61ae-bf7c-40ce-97ad-58d5306b6da5
99d46586-cb68-4b05-98cf-3c3830fcc540
[2023-10-30 18:08:23,566: WARNING/ForkPoolWorker-4] An erroneous attempt was made to transition notification id 99d46586-cb68-4b05-98cf-3c3830fcc540 from sent to sending

c3edaf45-e29e-4e1f-b71a-61015ccf7b47
[2023-10-30 18:08:29,108: WARNING/ForkPoolWorker-4] An erroneous attempt was made to transition notification id c3edaf45-e29e-4e1f-b71a-61015ccf7b47 from sent to sending
3dfd1f30-4f4f-4ded-9d06-d33d4372cce2
e7768189-e290-4af7-8aa0-bd0baa9f3d15
c605f001-3cca-4315-aa38-9807801711dd
```
