### ISSUE TITLE
Spike: v3 invalid template_id

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1493]
## User Story - Business Goal
We need to determine the best way to persist notifications in the notification table(s) when the API request fails due to invalid template scenarios.

- Mismatched template type (email/sms) based on the V3 endpoint used
- Invalid template ID which does not exist in our database

### User Story(ies)

**As a**  VANotify engineer,
**I want** to design a system that does not throw 500 Internal Server Errors
**So that** I understand why an issue happened.

**As a**  VANotify client,
**I want** to know why a given notification failed with a clear error message
**So that** I can rectify the situation.

## Acceptance Criteria & Checklist

- [x] Completed research addresses the problems and/or answers the questions below:  
1. Problems are addressed/resolved at the Celery layer
2. How should we handle nonexistent template IDs?
3. How should we handle a v3 email notification that is sent using an SMS template?
4. Is there any utility or drawbacks in making `template_id` a nullable field (it is presently not nullable)?
5. Do we need to create a GET `v3/notifications/{notification_id}` route to separate the logic from v2? Please be mindful of breaking changes to v2 as this is why we are making a v3.

- [ ] Technical Documentation has been created and linked in the glossary
- [x] Discussion has been scheduled, options/recommendations shared with the team, and decisions have been documented
- [x] Tickets for next steps have been identified and created

## Additional Info and Resources
When creating a new notification, the user's POST request data must specify a template_id for an existing template of the same type as the notification (e-mail, sms, etc.).  Using the route `POST /v2/notifications/*`, template_id validation happens as part of the route handler.  If the template_id is not valid, a Notification instance is not persisted or is persisted and deleted before the user receives a response like this:

```
{
    "errors": [
        {
            "error": "BadRequestError",
            "message": "sms template is not suitable for email notification"
        }
    ],
    "status_code": 400
}
```

Given that the overwhelming majoring of user requests to send a notification are valid (i.e. receive a 201 response with v2), and with the goal of maximizing throughput, we made the decision that v3 route handlers will not make any database queries before passing the request data to Celery.  The v3 route handlers only perform schema and formatting validations (i.e. that template_id is a valid uuid).  The first Celery task in the v3 implementation performs the template_id validation checks that v2 performs in the route handlers.  **If validation fails in Celery, we must persist the notification with a failure status.**  The user will learn of the failure by GETting the notification or via the existing callback mechanism.

This introduces two new corner cases that we need to handle for v3.  Both cases concern the non-nullable attribute Notification.template_id.

### Nonexistent template_id

If the user specifies a nonexistent template_id, the Celery task will encounter IntegrityError when it tries to persist the Notification instance.  As provisionally implemented, this is caught and logged.  The user has no way of knowing about the failure other than to contact the Notify team with a specific notification ID.

Some remedies we should consider:
- Make Notification.template_id nullable
- Create a default template, and use this ID for errors
- (Dave's preference) Call it a feature.  Assume users will get a callback with the error, and don't come up with a way to persist this erroneous notification.
- (Kyle's preference) DynamoDB `<env>-invalid-notification-table` that stores the redacted request (TTL 14 days to help w/troubleshooting) and is checked when an invalid notification id comes our way on a GET request for V3

### Notification.notification_type != Template.template_type

If the user of v3 specifies a template type that does not match the notification type (ex. e-mail template for SMS notification), a Notification is persisted with the expected error status and reason.  The problem occurs **only for e-mail notifications with an SMS template** when the user subsequently makes a request to `GET /v2/notifications/:id `, which will yield this 500 (Internal Server Error) response . . .

```
{
    "message": "Internal server error",
    "result": "error"
}
```

. . . and this traceback:

```
ERROR 2023-10-11 18:45:17,297 /app/app/__init__.py:443: 'SMSMessageTemplate' object has no attribute 'subject'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/ddtrace/contrib/flask/wrappers.py", line 88, in wrapper
    return func(pin, wrapped, instance, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/ddtrace/contrib/flask/patch.py", line 512, in _patched_request
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/ddtrace/contrib/flask/wrappers.py", line 61, in patch_func
    return _wrap_call(
  File "/usr/local/lib/python3.8/site-packages/ddtrace/contrib/flask/wrappers.py", line 52, in _wrap_call
    return wrapped(*args, **kwargs)
  File "/app/app/v2/notifications/get_notifications.py", line 16, in get_notification_by_id
    return jsonify(notification.serialize()), 200
  File "/app/app/models.py", line 1582, in serialize
    "subject": self.subject,
  File "/app/app/models.py", line 1476, in subject
    return template_object.subject
AttributeError: 'SMSMessageTemplate' object has no attribute 'subject'
```
This is not exactly a v3 bug.  If somebody, perhaps using psql, manually creates a Notification with a mismatched template type, the GET request will yield the same error, but we haven't seen this problem before because v2 never persists such a mismatch.

This is part of the desired response, and it reflects the actual Notification data getting stored now for v3:
```
    "status": "permanent-failure",
    "status_reason": "The template type does not match the notification type.",
```

Some remedies we should consider:
- Implement `GET /v3/notifications/:id`
- Fix the quasi-bug directly (more work, but less aggregate code)
- Make Notification.template_id nullable (also useful here)
- (Dave's preference) Call it a feature.  Assume users will get a callback with the error, and don't come up with a way to persist this erroneous notification.

**Comment by kalbfled** [comment]
It occurs to me that we might not need to persist failed notifications at all if we assume callbacks are standard for all services who use v3.  The only reason I see to persist a failed notification is so a user can GET the message later to see that it failed.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1493?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by kalbfled** [comment]
Another idea: We could have a new NotificationV3 table, and V3 routes would only work with this table.  This would be an opportunity to eliminate a lot of confusingly named and unused fields.

**Comment by nikolai-efimov** [comment]
- Consider max throughput on the happy path
- Cache template_id in the app, invalidate if template id info is changed

**Comment by mjones-oddball** [comment]
> Another idea: We could have a new NotificationV3 table, and V3 routes would only work with this table. This would be an opportunity to eliminate a lot of confusingly named and unused fields.

@kalbfled @nikolai-efimov I think the idea above has a bigger impact on all the various things that use this table. HOWEVER your idea sparked a similar one.. What if we only have a new table for validation failures and a V3 GET endpoint would be able to check both notification tables? Is that a thing that's possible? So basically you persist it somewhere but only the really cruddy validation failures go to that bad notification table so we don't screw up our good data in notification/notification history?

**Comment by nikolai-efimov** [comment]
Pausing this ticket till we have a discussion on Monday. The proposal is to do a quick validation using cached template info.

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e46d6f6f89a913279e7667323fb81045b0926ee/Screen%20Shot%202023-10-19%20at%201.29.02%20PM.png

**Comment by nikolai-efimov** [comment]
Further research shows that when there's no incoming messages, .listen() will block, i.e. it won't consume any CPU. Once a message is received, the subsequent logic will consume some CPU cycles, but this is negligible because we don't expect having many of those message in our system.

created branches [1493-no-async](https://github.com/department-of-veterans-affairs/notification-api/tree/1493-no-async) & [1493-no-async-with-cache](https://github.com/department-of-veterans-affairs/notification-api/tree/1493-no-async-with-cache)

**Comment by cris-oddball** [comment]
QA update:
- modified the hammer script to use perf and dot-env
- copy/pasted each file into home/ssm-user/hammer 
- activated h-venv, installed requirements, verified that it indeed sends emails

Next steps:
- Deploy 1493-no-async to Perf (after discussion with @nikolai-efimov and/or @kalbfled )
- Once deployed, increase the # of api tasks to get aas close to prod as possible given IP limitations
- Run emails at a low volume just to make sure I can see what I need to see in DD
- Decide what volume of email to push through and execute the commands for v2 - this will set the benchmark
- modify the send_email.py script to use the v3 route
- Run the same # of emails
- compare with the v2 benchmark
- deploy the 1493-no-async-with-cache after checking with dave/nikolai
- run the same # of emails against v3
- compare with previous v3 run and with v2 benchmark
- share results with team

**Comment by nikolai-efimov** [comment]
Per conversation with @k-macmillan we are not moving forward with API layer validation of templates, all validations will be done at the Celery layer.

**Comment by mjones-oddball** [comment]
Summary from team convo today:

We are moving forward with the architecture plan to include validations that require DB lookups (outside of authorization) in the celery layer instead of the API layer. We now have stats showing the performance boost of doing this in v3: https://docs.google.com/document/d/1-besxhOKU5cDScxJe7qZHkef39cE3o2kgomMEYkhE6E/edit#bookmark=id.731b1yywcmu5
Plan to handle the issues of persisting notifications that fail due to invalid or mismatched template ids so the client can GET the status or receive it via callback:

- New notification validation failure table in our existing postgres DB using JSONB format (TICKET NEEDED)
    - Expiration of 30 days for data
    - This should include the same data points as what we store for v2, just structured differently for efficiency
- New V3 GET notification endpoint by id (TICKET(S) NEEDED)
    - It should be able to return data from notifications (current table) and the new notification validation failure table
   - Postman/swagger updates
- API Code Updates (TICKET NEEDED)
    - Persist these failure types in V3 to the new table in JSONB format, which will include the status and status reason for failure
    - Enhance callback logic to support this new table

@nikolai-efimov @cris-oddball  to work through ticket needs. 
@k-macmillan  if I missed anything or got anything wrong in the summary please revise.

**Comment by mjones-oddball** [comment]
AC Answers:
- Problems are addressed/resolved at the Celery layer
    - Validation errors can be identified in the celery layer and persisted in the new validation error table
- How should we handle nonexistent template IDs?
    - Since there will be a new table, there will be no constraints preventing us from persisting this
- How should we handle a v3 email notification that is sent using an SMS template?
    - New v3 GET endpoint will allow the status data to be surfaced from this table without erroring
- Is there any utility or drawbacks in making template_id a nullable field (it is presently not nullable)?
    - Lots of drawbacks because this has a trickle effect throughout the code that would require a lot of updates and could negatively impact notification functionality 
- Do we need to create a GET v3/notifications/{notification_id} route to separate the logic from v2? Please be mindful of breaking changes to v2 as this is why we are making a v3.
    - Yes, we don't want to risk v2 use. There will be instructions for clients using v3 to use the GET v3 route

**Comment by cris-oddball** [comment]
Created tickets:

- v3: create new notification validation failure table in PostgresSQL #1512
- v3: Modify API code to persist validation failures in new table and return in callbacks #1513
- v3: GET notification endpoint #1514
