### ISSUE TITLE
Update VEText Forwarder Lambda Logging

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1497]
## User Story - Business Need
Update the logging in the vetext forwarder lambda to be in-line with our [logging policy](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/logging_policy.md).

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Engineer
**I want** to log in accordance with our policies
**So that** we are consistent across the platform

### Additional Info and Resources

- [logging policy](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/logging_policy.md)

## Engineering Checklist

- [x] All logging includes string qualifiers (nothing like `logger.info(event)`)
- [x] Proper use of `info`, `warning`, and `error/critical`
- [x] `MessageSid` is recorded in the logs
- [x] `MessagingServiceSid` is recorded in the logs
- [x] `To` (the service's phone number) is recorded in the logs
- [x] `From` and other identifying fields are not recorded outside of `debug` logging

## Acceptance Criteria

- [x] Code not related to logging is not changed at all
- [x] Logging output coincides with the logging policy

## QA Considerations

Logging has no opportunity for new errors

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1497?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by npmartin-oddball** [comment]
@k-macmillan will investigate.
