### ISSUE TITLE
Add Connection Overrides to Twilio Client for Delivery Status

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1498]
## User Story - Business Need
Add the following to Twilio callback URLs: `#ct=3000&rt=1500&rc=5&rp=all`. 

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As** VA Notify
**I want** Twilio to attempt retries and have a longer connection timeout
**So that** fewer callbacks fall through the cracks

### Additional Info and Resources

Twilio documentation on [Connection Overrides](https://www.twilio.com/docs/usage/webhooks/webhooks-connection-overrides)

- `ct` is the connection timeout - set to 3 seconds (default is 5 seconds)
- `rc` is the retry count - set to 5 retries (default is 1)
- `rp` is the retry policy - set to `all` (default is `ct` - connection timeout essentially)
- `rt`  is the read timeout - set to 1.5 seconds which is the default. 

## Engineering Checklist

- [x] `#ct=3000&rt=1500&rc=5&rp=all` is appended to the callback url for all outgoing Twilio requests
- [x] Wherever it is set there is a link to the documentation as a comment, since it is a sequence of characters
- [x] This value is specified as a class variable or instance member and appended to the url
 - **Note**: So it is not buried and forgotten

## Acceptance Criteria

Override added to the callback url for Twilio requests.

GIVEN the provider is Twilio
WHEN and error occurs with Twilio reaching our callback URL for delivery statuses
THEN Twilio will retry based on the criteria we provide

## QA Considerations
- [ ] callbacks still function as expected

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1498?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by cris-oddball** [comment]
PR approved and merged, deployed to Perf.
Sent a test message from the Twilio testing service in Perf and the message was received.
That's about as far as we can go with testing. In the past 30 days, no timeouts on deliverystatus were received in dev or perf (just staging and prod) according to Twilio's error logs. Will close this ticket out and see what happens when it gets to Staging on the next release.
```
{
    "billing_code": null,
    "body": "Testing template, no personalisations.",
    "completed_at": "2023-11-28T21:13:30.288617Z",
    "cost_in_millicents": 0.0,
    "created_at": "2023-11-28T21:13:09.541502Z",
    "created_by_name": null,
    "email_address": null,
    "id": "6c42781b-34b1-4286-85a3-d731801fb912",
    "line_1": null,
    "line_2": null,
    "line_3": null,
    "line_4": null,
    "line_5": null,
    "line_6": null,
    "phone_number": "+1<redacted>",
    "postage": null,
    "postcode": null,
    "provider_reference": "SM98cef61fb0efa94b90166c81171f913b",
    "recipient_identifiers": [],
    "reference": null,
    "scheduled_for": null,
    "segments_count": 0,
    "sent_at": "2023-11-28T21:13:10.597641Z",
    "sent_by": "twilio",
    "sms_sender_id": "f6979d20-6b2a-4e58-907c-1f007874c86f",
    "status": "delivered",
    "status_reason": null,
    "subject": null,
    "template": {
        "id": "e0db3e86-ba17-40d0-9fc7-4ff9eb33ef72",
        "uri": "https://sandbox-api.va.gov/v2/template/e0db3e86-ba17-40d0-9fc7-4ff9eb33ef72/version/2",
        "version": 2
    },
    "type": "sms"
}
```
