### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/notification-api#15]
Additionally
- [ ] Refactor terraform to use variables that can be used across production or dev environments 
- [ ] publish a production terraform state file (vs the one published for dev)

**Comment by ffafara-tw** [comment]
Blocked by db migrations

**Comment by anushyaprasad** [comment]
All relevant documentation has been submitted. Filip has confirmed availability of funding to Murtala Bello. Waiting on James Nichols to confirm next steps.

**Comment by anushyaprasad** [comment]
@ffafara-tw @QaysarA looking at the scope of this card, can we move this back into "ready for dev" state and just track a separate process card the provisioning of an AWS account? Similar to the SSL certi card?

**Comment by QaysarA** [comment]
Sounds good - I will move this to the prioritized backlog

Also will create another process card around the status of the VA environment for us to track
