### ISSUE TITLE
Deploy VANotify to VA environment

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#150]
# Value Statement:
**As** a VANotify system owner
**I want to** deploy my system in VA network
**So that** my consumers can use the system

# Acceptance Criteria
**GIVEN** A new commit is pushed
**AND** CI run passes (build & test)
**THEN** VANotify is automatically deployed to development environment in VAEC
**AND** the application works (can send email)

**GIVEN** A successful deployment to development environment
**THEN** VANotify is automatically deployed to staging environment in VAEC
**AND** the application works (can send email)

**GIVEN** VANotify system owner
**WHEN** they manually trigger a production deployment using prod version tag
**THEN** VANotify is automatically deployed to production environment in VAEC
**AND** the application works (can send email)

# Checklist:

# Assumptions:
The environments are dev, staging or prod.
# Additional Info/Resources:

# Out of Scope:

# Open Questions:

**Comment by saman-moshafi-va** [comment]
The migrations is now running successfully.

**Comment by saman-moshafi-va** [comment]
The VAEC notification API on dev is installed and managed to create organization, user, service, template, api key and send the email.
