### ISSUE TITLE
BUG: v3 POST email does not send the email

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1501]
## Description
After this commit, 4bcb9906e5c685b7849419c33178b8b0f1d248d7, v3 email was able to send email messages and receive a sent status. 
After this commit, 24d866455ec6805e9c3de0d84ecfce7acf9419f5, v3 email still could POST the request, get a 202, create a notification_id but it never sends the message and the GET route returns a 404. The logs really do not show much of anything, other than that the POST request happened.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. In Postman, use the POST v3/notifications/email route with the following payload, making sure that {{email-template-id}} is actually an email template ID that exists on the service.
```
{
    "template_id": "{{email-template-id}}",
    "email_address": "<your known good email address>"

}
```
2. Observe the 202 response and an ID is returned. Save this ID somewhere so that you can search the logs for it.
3. Use the GET v2/notifications/{{notification-id}} route with the above ID
4. Observe the 404 response and the above error message

Using the same payload with the v2 POST v2/notifications/email route, observe the 201 response for the POST and using the GET v2/notifications/{{notification-id}} route observe the 200 response and an eventual 'delivered' status.

## Workaround
Is there something we can do to work around this issue in the meantime?
No.

### Please note - it is critical we finish this work after the new year. Remaining V3 work should not be a code overhaul. Any refactoring requests must be approved by Product and Tech Lead.

High - v3 email cannot be user or automated until this is fixed.

## Expected Behavior

- [ ] POST v3 email returns a 202 and notification ID which can then be used for the GET v2 notification route, returns a 200 and an eventual status of 'sent'

## QA Considerations
- This works as expected (fully vet)

**Comment by kalbfled** [comment]
Cris says that SMS is not affected.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1501?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by k-macmillan** [comment]
Fixed the issue by removing the extra decorator. 

Tests are failing for unrelated reasons. At least two packages underwent major version upgrades and it is breaking tests.

**Comment by k-macmillan** [comment]
Fixed the issue by removing the extra decorator. 

Tests are failing for unrelated reasons. At least two packages underwent major version upgrades and it is breaking tests.

**Comment by cris-oddball** [comment]
PR approved and merged deployed to Perf. Manually testing the route until I can finish the automation.

**Comment by cris-oddball** [comment]
The delivery status in v2 does return a 200 OK, but the delivery status is never updated to Delivered, it is at Sent. I do note this in the Description but am asking a clarifying question of the team before I close this ticket.

**Comment by cris-oddball** [comment]
The delivery status will be handled on #1616.

Closing this ticket.
