### ISSUE TITLE
V3 - Add Email Personalisation Functionality

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1502]
## User Story - Business Need
We want to ensure V3 has feature parity with V2. This ticket should ensure that personalisations sent through the v3 email  endpoint is accurately persisted, validated to be present in the request if found in the template, and populated into template content during delivery.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Client
**I want** to personalize my notifications
**So that** Veterans receive content that is helpful and specific to their needs

### Additional Info and Resources

The v3 code to change is in the [v3_send_email_notification](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/v3/notification_tasks.py#L200) function.

The personalisations happy path might work now in limited circumstances, but error conditions are not checked. If no personalisation data is supplied for a template with personalisation placeholders, the raw template is sent.  The code references "notification.content", but the commented out code above includes additional functionality.  That needs to be fixed first.

### Please note - it is critical we finish this work after the new year. Remaining V3 work should not be a code overhaul. Any refactoring requests must be approved by Product and Tech Lead.

- Unit Tests
  - [ ] Personalisation data must have the same attributes as the template
  - [ ] Personalisation attributes can be the empty string
  - [ ] Personalisation attributes can be URLs
  - [ ] Others . . .
- [ ] Implement or revise substitution logic as necessary
- [ ] Execute functional tests to confirm formatting is visually congruent with v2

### What can you include within personalisations today?
- Empty string
- Words/special characters
- Some html and markdown formatting (Nathan does this in some form emails so you could ask him for an example)
- URLs, this can be an entire URL or part of a URL (beginning, middle, end)

### Givens
At least one personalisation is present in the email template

### Cases

- [ ] Missing personalisation email

1. Send an email request through postman to `/v3/notifications/email`
2. Do not include a personalisation that is present in the template
3. Then you should receive a validation error stating which personalisation is missing

- [ ] Populating personalisations in content for email
    - [ ] Partial URL i.e. placing the personalisation within a url: https://www.google.com/((url))
    - [ ] Full URL
    - [ ] Words
    - [ ] Empty string
    - [ ] Basic formatting (e.g. bold, new line, etc.)

1. Send an email request through postman to `/v3/notifications/email`
2. Include one or more personalisations that are found in the template and satisfy the functional use cases above
3. Confirm that you receive the email and the content is formatted correctly
4. Compare the same examples with an email sent through v2 to be 100% sure there is parity
5. GET the notification via `/v2/notifications/{{notification-id}}` and confirm the `body` appears as expected with the personalisations populated. Note - formatting characters, if used, should also display.

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

You can check with Jake if he has any test rail cases for personalisations. Portal uses v2 endpoints for test sends, so that functionality won't be impacted by v3 until we remove v2.

We don't have a documented list of html and markdown formatting supported by personalisations, but I know Nathan has built some form notification triggers that included formatting so he could give an example.

- There is a separate ticket for file attachments.

**Comment by cris-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1502?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by kalbfled** [comment]
I removed "Implementation utilizes the validate_template() method" from the engineering checklist.  Calling that function is not specific to e-mail, and it should be called upstream.  I'm creating a separate ticket and making this ticket dependent on that new ticket.

**Comment by k-macmillan** [comment]
Will re-address with va-enp-api.
