### ISSUE TITLE
V3 - Add SMS Personalisation Functionality

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1503]
## User Story - Business Need
We want to ensure V3 has feature parity with V2. This ticket should ensure that personalisations sent through the v3 sms endpoint is accurately persisted, validated to be present in the request if found in the template, and populated into template content during delivery.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Client
**I want** to personalize my notifications
**So that** Veterans receive content that is helpful and specific to their needs

### Additional Info and Resources

The personalisations happy path actually works now, but error conditions are not checked.  If no personalisation data is supplied for a template with personalisation placeholders, the raw template is sent.

The v3 code to change is [here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/v3/notification_tasks.py#L206).

### Please note - it is critical we finish this work after the new year. Remaining V3 work should not be a code overhaul. Any refactoring requests must be approved by Product and Tech Lead.

- Unit Tests
  - [ ] Personalisation data must have the same attributes as the template
  - [ ] Personalisation attributes can be the empty string
  - [ ] Personalisation attributes can be URLs
  - [ ] Others . . .
- [ ] Implement or revise substitution logic as necessary.  The existing code references "notification.content", which makes the correct substitutions for the happy path.
- [ ] Execute functional tests to confirm formatting is visually congruent with v2

### What can you include within personalisations today?
- Empty string
- Words/special characters
- URLs, this can be an entire URL or part of a URL (beginning, middle, end)

### Givens
At least one personalisation is present in the sms template

### Cases

- [ ] Missing personalisation sms

1. Send an sms request through postman to `/v3/notifications/sms`
2. Do not include a personalisation name that is present in the template
3. Then you should receive a validation error stating which personalisation is missing

- [ ] Populating personalisations in content for sms
    - [ ] Partial URL i.e. placing the personalisation within a url: https://www.google.com/((url))
    - [ ] Full URL
    - [ ] Words
    - [ ] Empty string

1. Send an sms request through postman to `/v3/notifications/sms`
2. Include one or more personalisations that are found in the template and satisfy the functional use cases above
3. Confirm that you receive the sms and the content is formatted correctly
4. Compare the same examples with an email sent through v2 to be 100% sure there is parity

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

You can check with Jake if he has any test rail cases for personalisations. Portal uses v2 endpoints for test sends, so that functionality won't be impacted by v3 until we remove v2.

**Comment by cris-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1503?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by kalbfled** [comment]
This ticket is about template variable substitution (a.k.a. personalization).  The difference between v3 as currently implemented and v2 is that v3 does not check for missing or extra "personalisation" data.  The observed behavior of v3 when making a request that specifies a template that should require "personalisation" is as follows:

1. Omitting the "personalisation" field sends a message that includes the unsubstituted template variable names and mark-up.
2. Including "personalisation", which is has a JSON object for its value, that assigns values to all expected variables works as expected.
3. Including "personalisation" that assigns the empty string to all expected variables works as expected.

I have not tested excluding a subset of required template variables.

**Comment by kalbfled** [comment]
I removed "Implementation utilizes the validate_template() method" from the engineering checklist. Calling that function is not specific to e-mail, and it should be called upstream. See #1590.

**Comment by k-macmillan** [comment]
Will re-address with va-enp-api.
