### ISSUE TITLE
[SPIKE] Research alerts for VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#151]
# Goal
The purpose of this spike it to research and understand the alerts that need to be setup for VANotify utilizing CloudWatch and the feasibility of implementation  

# Checklist
- [x] Research and recommendations on what alerts should be setup for VANotify
- [ ] ~Discussion needed on what alerts are currently setup by the Canadian team~ -> CA team contacted, cannot get info at this time; but Filip is contacting UK team
- [x] How will the alerts be sent (PagerDuty, Slack, Email, Text) 
- [x] Discuss and document the results with team
- [x] Create recommendations
- [x] Add steps needed for implementation to #152

# Timebox
3 days

# Assumptions
- Implementation of the alerts will be done in a separate card #152

# Additional Info/Resources
- Sync with Filip on the decision that was made on using CloudWatch for VANotify alerts

# Out of Scope
- Setting up the alerts and sending the alerts (PagerDuty, Slack, Email, or Text) will be completed as a part of the implementation card

# Open Questions

**Comment by ffafara-tw** [comment]
Sent email to Bryan Willey from CDS asking if they could share their cloudwatch alerts configuration

**Comment by marisahoenig** [comment]
Alerts research here: https://docs.google.com/document/d/1gwaBA9jC__IYMLcdpQjVPw3UjsKy1GVOjhtQa2nSEY8/edit

Creating an ADR & filling in the implementation card
