### ISSUE TITLE
v3: create new notification validation failure table in PostgresSQL

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1512]
## User Story - Business Need
Because we are validating certain items after returning a 202 Accepted from the v3 POST routes, we need to be able to handle validation failures for certain instances with a new table in PostgreSQL. See #1493 for the backstory.

The two known use cases at this time are a nonexistent template_id and a template type that does not match the notification type (for example, an sms template used to send an email).

The purpose of this ticket is to create a new table in PostgreSQL with two properties:
- id (primary key) whose value is the generated notification UUID from the POST v3 request
- body (or whatever name works) whose value is a JSON representation of what is in the notification table. This field will be a [jsonb](https://www.postgresql.org/docs/15/datatype-json.html) field. It will eventually be augmented with two additional properties: 'status': 'permanent-failure' and 'status_reason': 'some reason' in future work. 
- 
Note this is just clarifying explanation, the ticket simply creates the new table and the new schema for that table with the two properties, as well as expiring entries after 30 days.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VaNotify engineer
**I want** to create a new table with jsonb data that stores validation failures
**So that**  I can retain the existing architecture and extend it for v3

## Engineering Checklist

- [x] Create a new table named appropriately (this is a v3 notification validation failure table)
- [x] Table should have two properties, id (primary key, uuid) and body (jsonb); neither should be nullable; schema is defined in the code as appropriate.
~- [ ] Each entry in the table should have a 30-day expiry after its creation date (left to the engineer working the ticket to decide the best way to do this). One idea is [pg_cron](https://www.citusdata.com/blog/2023/10/26/making-postgres-tick-new-features-in-pg-cron/). There may be others.~
- [x] New table model added to models.py or appropriate location
- [x] New migration to handle the new table

## Acceptance Criteria

- [x] the new table exists as described
~- [ ] entries are expired after 30 days (if this is taking too long bring it up!)~

## Out of Scope
Anything beyond creating the new table, defining its schema, and handling the expiration of data.

**Comment by cris-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1512?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by nikolai-efimov** [comment]
we need to install pg_cron and execute 
```
CREATE EXTENSION pg_cron;
SELECT cron.schedule('0 0 * * *', $$DELETE FROM notification_failures WHERE created_at < NOW() - INTERVAL '30 days'$$);
```

**Comment by k-macmillan** [comment]
We decided to use `pg_cron` to remove the old entries but that [requires a custom parameter group](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_pg_cron.html) for our postgres instances. We will accomplish that work in a separate ticket and then revisit deleting the records.

**Comment by nikolai-efimov** [comment]
per Kyle's comment above, removed TTL from acceptance criteria

**Comment by nikolai-efimov** [comment]
https://github.com/department-of-veterans-affairs/notification-api/pull/1522
