### ISSUE TITLE
v3: Modify API (Celery) code to persist validation failures in new table and return in callbacks

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1513]
## User Story - Business Need
To be able to handle notification validation failures, the v3 API code must be modified to persist these failures in the new table created in #1512 in jsonb format, augmented with a `status`of `permanent-failure` and a `status-reason` of that reason. Callback code also needs to be modified to be able to return entries from the new table.

A new GET v3/notifications/{notification-id} route will be created in #1514

The two known use cases we currently have are for 
- non-existent template_id
- template_id exists, but on a different service
- template_type does not match notification type (i.e., sms template for an email notification)
</br>

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VANotify engineer
**I want**  to persist v3 notification validation failures
**So that** clients can receive or retrieve the status of these failed notifications

## Engineering Checklist

- [x] API code for v3 is modified such that when a validation fails, that notification id and the data are inserted into the new notification validation failure table and augmented with  a `status`of `permanent-failure` and a `status-reason` of that reason (see AC for suggested text).

## Acceptance Criteria

- [x] Email, Invalid Template ID
GIVEN I post to v3 email 
WHEN I include an invalid template id
THEN the notification fails as permanent-failure  and is persisted to notification_failures, including an applicable status_reason "The template does not exist."

</br>

- [x] SMS, Invalid Template ID
GIVEN I post to v3 sms
WHEN I include an invalid template id
THEN the notification fails as permanent-failure and is persisted to notification_failures, including an applicable status_reason "The template does not exist."

</br>

- [x] Email, Mismatched Template ID and Type
GIVEN I post to v3 email 
WHEN I include a valid **sms** template ID within the service
THEN the notification fails as permanent-failure  and is persisted to notification_failures, including an applicable status_reason "The template type does not match the notification type."

</br>

- [x] SMS, Mismatched Template ID and Type
GIVEN I post to v3 sms
WHEN I include a valid **email** template ID within the service
THEN the notification fails as permanent-failure  and is persisted to notification_failures, including an applicable status_reason "The template type does not match the notification type."

</br>

- [x] Email, Valid Template not in Service
GIVEN I post to v3 email 
WHEN I include a valid template id that is not found in the service provided
THEN the notification fails as permanent-failure  and is persisted to notification_failures, including an applicable status_reason "The service does not own the template."

</br>

- [x] SMS, Valid Template not in Service
GIVEN I post to v3 sms
WHEN I include a valid template id that is not found in the service provided
THEN the notification fails as permanent-failure and is persisted to notification_failures, including an applicable status_reason "The service does not own the template."

## QA Considerations
- [x] This must be validated through a database query
- [ ] Regression works as expected

## Out of Scope

- The v3 GET route is to be created in a separate ticket.
- Personalisations are handled in another ticket
- Callbacks are handled in another ticket

**Comment by cris-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1513?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by mjones-oddball** [comment]
@nikolai-efimov I revised the content and expanded the AC, including suggested status reasons
@cris-oddball FYI

**Comment by nikolai-efimov** [comment]
I was able to store a simplified version of Notification, but ran into issues with serializing real Notification object into JSON using .serialize(), which is needed to store a notification in the "body" (JSONB) of NotificationFailures. Many properties are not defined. A parking lot discussion is needed.

First failure occurs in models.py , line 1593
```
def serialize(self):    
        template_dict = {
            'version': self.template.version,
            'id': self.template.id,
            'uri': self.template.get_link()
        }
```

**Comment by mjones-oddball** [comment]
@cris-oddball Nikolai informed me there was another validation use case to cover so I updated the AC. He also showed me the existing status reasons and they looked fine so I updated the AC rather than have us changing text for no reason. New AC use case below:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeE1uQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--274c4bdf049865fc6d5c32ff8e9acb7dc243fd1c/image.png)

**Comment by cris-oddball** [comment]
fails the first test case
```
TC01 Email, Invalid Template ID
GIVEN I post to v3 email
WHEN I include an invalid template id
THEN the notification fails as permanent-failure and is persisted to notification_failures, including an applicable status_reason "The template does not exist." 
```

The response for the v3 email I just sent has the `phone_number `set to the email address. The `email_address` field should have been populated, not phone_number
```
 677c9346-b3b3-4818-8a63-7effb7eb0d05 | 2023-12-04 15:11:51.140472 | {"id": "677c9346-b3b3-4818-8a63-7effb7eb0d05", "type": "email", "status
": "permanent-failure", "template": {"id": "2146af91-4385-4259-a051-baa76ef3e67b", "version": 0}, "reference": null, "created_at": "2023-12-
04T15:11:51.058038Z", "billing_code": null, "completed_at": "2023-12-04T15:11:51.058038Z", "phone_number": "<redacted>", "sms_
sender_id": "None", "status_reason": "The template does not exist.", "personalisation": {}, "notification_type": "email"}
```

**Comment by cris-oddball** [comment]
[Deployed to Dev](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/7093227818)

All 6 test cases pass on Dev

TC01 Email, Invalid Template ID
```
 85314e60-ae9f-4f3d-b935-7a705d20ae03 | 2023-12-04 22:23:50.356123 | {"id": "85314e60-ae9f-4f3d-b935-7a705d20ae03", "type": "email", "status
": "permanent-failure", "template": {"id": "2146af91-4385-4259-a051-baa76ef3e67b", "version": 0}, "reference": null, "created_at": "2023-12-
04T22:23:50.279226Z", "billing_code": null, "completed_at": "2023-12-04T22:23:50.279226Z", "phone_number": null, "email_address": "<redacted>", "sms_sender_id": "None", "status_reason": "The template does not exist.", "personalisation": {}, "notification_type": "ema
il"}
```

TC02  SMS, Invalid Template ID
```
 6cd93f90-df9f-4c4f-b7bd-f73479c78217 | 2023-12-04 22:24:52.778742 | {"id": "6cd93f90-df9f-4c4f-b7bd-f73479c78217", "type": "sms", "status":
 "permanent-failure", "template": {"id": "2146af91-4385-4259-a051-baa76ef3e67b", "version": 0}, "reference": null, "created_at": "2023-12-04
T22:24:52.772703Z", "billing_code": null, "completed_at": "2023-12-04T22:24:52.772703Z", "phone_number": "<redacted>", "email_address": nu
ll, "sms_sender_id": "None", "status_reason": "The template does not exist.", "personalisation": {}, "notification_type": "sms"}
```

TC03  Email, Mismatched Template ID and Type
```
 bffaa122-20e6-4f6c-b865-880652181185 | 2023-12-04 22:26:31.690675 | {"id": "bffaa122-20e6-4f6c-b865-880652181185", "type": "email", "status
": "permanent-failure", "template": {"id": "b442c450-fd43-4a78-9743-8f4dd4f427fc", "version": 2}, "reference": null, "created_at": "2023-12-
04T22:26:31.683403Z", "billing_code": null, "completed_at": "2023-12-04T22:26:31.683403Z", "phone_number": null, "email_address": "<redacted>", "sms_sender_id": "None", "status_reason": "The template type does not match the notification type.", "personalisation": {}
, "notification_type": "email"}
```


TC04 SMS, Mismatched Template ID and Type
```
 19c2c70b-d991-4035-b562-8572de74f401 | 2023-12-04 22:27:32.149089 | {"id": "19c2c70b-d991-4035-b562-8572de74f401", "type": "sms", "status":
 "permanent-failure", "template": {"id": "52bfd6eb-dc89-4bee-a478-84d50f5af673", "version": 1}, "reference": null, "created_at": "2023-12-04
T22:27:32.142821Z", "billing_code": null, "completed_at": "2023-12-04T22:27:32.142821Z", "phone_number": "<redacted>", "email_address": nu
ll, "sms_sender_id": "None", "status_reason": "The template type does not match the notification type.", "personalisation": {}, "notificatio
n_type": "sms"}
```


TC05 Email, Valid Template not in Service
```
 4b45267f-d0a5-4b1a-be7d-587917f3b763 | 2023-12-04 22:28:20.521133 | {"id": "4b45267f-d0a5-4b1a-be7d-587917f3b763", "type": "email", "status
": "permanent-failure", "template": {"id": "aef3658a-1c78-443a-9c74-688ee96f18be", "version": 3}, "reference": null, "created_at": "2023-12-
04T22:28:20.515309Z", "billing_code": null, "completed_at": "2023-12-04T22:28:20.515309Z", "phone_number": null, "email_address": "<redacted>", "sms_sender_id": "None", "status_reason": "The service does not own the template.", "personalisation": {}, "notification_t
ype": "email"}
```

TC06 SMS, Valid Template not in Service
```
 dcbc337e-2dfa-4790-bb83-ff88537411f9 | 2023-12-04 22:29:21.605792 | {"id": "dcbc337e-2dfa-4790-bb83-ff88537411f9", "type": "sms", "status":
 "permanent-failure", "template": {"id": "e98f2fd4-f307-4092-be15-34a8d903deda", "version": 2}, "reference": null, "created_at": "2023-12-04
T22:29:21.599893Z", "billing_code": null, "completed_at": "2023-12-04T22:29:21.599893Z", "phone_number": "<redacted>", "email_address": nu
ll, "sms_sender_id": "None", "status_reason": "The service does not own the template.", "personalisation": {}, "notification_type": "sms"}
```

**Comment by cris-oddball** [comment]
Code was retested on Dev and passed after requested changes were made. Two approvals on PR and PR was merged into master. This code is going up to Perf and will be tested there later today.

**Comment by cris-oddball** [comment]
**PERF TESTING PASSED**

TC01 Email, Invalid Template ID
```
 0261ab0e-1513-4c26-8d38-fd309b14917c | 2023-12-06 18:34:39.770709 | {"id": "0261ab0e-1513-4c26-8d38-fd309b14917c", "type": "email", "status": "permanent-failure", "template": {"id": "21
46af91-4385-4259-a051-baa76ef3e67b", "version": 0}, "reference": null, "created_at": "2023-12-06T18:34:39.710611Z", "billing_code": null, "completed_at": "2023-12-06T18:34:39.710611Z", "
phone_number": null, "email_address": "<redacted>", "sms_sender_id": "None", "status_reason": "The template does not exist.", "personalisation": {}, "notification_type": "e
mail"}
```


TC02  SMS, Invalid Template ID
```
 05188ff8-ce96-434f-90cd-87902f1732f6 | 2023-12-06 18:35:53.744602 | {"id": "05188ff8-ce96-434f-90cd-87902f1732f6", "type": "sms", "status": "permanent-failure", "template": {"id": "2146
af91-4385-4259-a051-baa76ef3e67b", "version": 0}, "reference": null, "created_at": "2023-12-06T18:35:53.672156Z", "billing_code": null, "completed_at": "2023-12-06T18:35:53.672156Z", "ph
one_number": "<redacted>", "email_address": null, "sms_sender_id": "None", "status_reason": "The template does not exist.", "personalisation": {}, "notification_type": "sms"}
```


TC03  Email, Mismatched Template ID and Type
```
 e9d7372c-71e5-4501-9684-21e502439fda | 2023-12-06 18:37:03.38431  | {"id": "e9d7372c-71e5-4501-9684-21e502439fda", "type": "email", "status": "permanent-failure", "template": {"id": "d4
6ee87b-8a71-4c5c-8654-ed766a9599ff", "version": 1}, "reference": null, "created_at": "2023-12-06T18:37:03.379789Z", "billing_code": null, "completed_at": "2023-12-06T18:37:03.379789Z", "
phone_number": null, "email_address": "<redacted>", "sms_sender_id": "None", "status_reason": "The template type does not match the notification type.", "personalisation":
{}, "notification_type": "email"}
```


TC04 SMS, Mismatched Template ID and Type
```
 21fc8b06-0784-49bf-941a-1992a3b83e19 | 2023-12-06 18:38:05.496994 | {"id": "21fc8b06-0784-49bf-941a-1992a3b83e19", "type": "sms", "status": "permanent-failure", "template": {"id": "324a
5b71-8f3e-4617-9ba4-9e0da94bfe30", "version": 1}, "reference": null, "created_at": "2023-12-06T18:38:05.490674Z", "billing_code": null, "completed_at": "2023-12-06T18:38:05.490674Z", "ph
one_number": "<redacted>", "email_address": null, "sms_sender_id": "None", "status_reason": "The template type does not match the notification type.", "personalisation": {}, "notificat
ion_type": "sms"}
```


TC05 Email, Valid Template not in Service
```
 19a1b410-069a-4dcd-90ce-44db2920f24b | 2023-12-06 18:39:05.224276 | {"id": "19a1b410-069a-4dcd-90ce-44db2920f24b", "type": "email", "status": "permanent-failure", "template": {"id": "b9
531b76-2a8a-4b5e-aa2a-ae7659238828", "version": 6}, "reference": null, "created_at": "2023-12-06T18:39:05.217852Z", "billing_code": null, "completed_at": "2023-12-06T18:39:05.217852Z", "
phone_number": null, "email_address": "<redacted>", "sms_sender_id": "None", "status_reason": "The service does not own the template.", "personalisation": {}, "notification
_type": "email"}
```


TC06 SMS, Valid Template not in Service
```
e0b5c816-d34c-4844-869e-65ef5ee967d5 | 2023-12-06 18:42:18.290425 | {"id": "e0b5c816-d34c-4844-869e-65ef5ee967d5", "type": "sms", "status": "permanent-failure", "template": {"id": "9d12
b558-23fd-4b94-a338-9893552c87c2", "version": 1}, "reference": null, "created_at": "2023-12-06T18:42:18.284206Z", "billing_code": null, "completed_at": "2023-12-06T18:42:18.284206Z", "ph
one_number": "<redacted>", "email_address": null, "sms_sender_id": "None", "status_reason": "The service does not own the template.", "personalisation": {}, "notification_type": "sms"}
```

Closing ticket, this PR will be in the next release.
