### ISSUE TITLE
v3: GET notification endpoint

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1514]
## User Story - Business Need
The v3 POST sms/email endpoints require a new v3 GET notification endpoint to properly handle notification validation failures. Work in ticket #1512 create a new table to store notification validation failures; now we want to create a new GET `v3/notifications/{notification-id}` endpoint to retrieve the notifications that succeed (data returned from existing notifications table) and that failed (data returned from new notifications failure table).

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify engineer
**I want**  to create a new v3 GET notification route
**So that** notification failures are properly handled, without returning 500 Internal Server Errors

**As a**  VANotify client
**I want**  the option to use the new v3 GET notification route
**So that** to understand why my notification might failed

## Engineering Checklist

- [ ] create GET `v3/notifications/{notification-id}` endpoint
- [ ] This route should first try to retrieve data from the existing notification table and, if the id is not there, retrieve data from the new notifications failure table
- [ ] The data is returned in the GET route as expected, including a valid status and status_reason
- [ ] Update Swagger
- [ ] Update Postman

## Acceptance Criteria

- [ ] When I send a v3 email or sms with the wrong template type, and I call his new GET route, then I get back all the expected fields with a status of permanent-failure and a reason that informs me I used the wrong template type
- [ ] When I send a v3 email or sms with a non-existent template_id, and I call this new GET route, then I get back all the expected fields with a status of permanent-failure and a reason that informs me that the template id could not be found
- [ ] When I use the v2 route to GET a notification id that has failed validation, I can expect a 404 Not Found instead of a 500 Internal Server Error
- [ ] Fields returned for v3 GET requests should match v2

## QA Considerations
- [ ] Regression passes
- [ ] Manually test the above
- [ ] Postman is accurate
- [ ] Swagger is accurate
- [ ] Either automate or create ticket for automation

**Comment by cris-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1514?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by kalbfled** [comment]
We need first to fix #1501 so we can create e-mail notifications to GET.

**Comment by k-macmillan** [comment]
Will re-address with va-enp-api.
