### ISSUE TITLE
v3 send e-mail formatting

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1518]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,
**I want** sending e-mail notifications with v3 to have the same perceived effect as sending with v2
**So that** users do not have to change their templates.

### Additional Info and Resources

Sending e-mail notifications with v2 uses code from the notification-utils repo to format the output.  v3 was not working with this code, so #1361 finished by simply commenting-out the code that didn't work.  This behavior needs to be restored to achieve feature parity with v2.

Note that the commented out text references notification.reply_to_text, which has not been set.  See #1596, which blocks this ticket.

### Please note - it is critical we finish this work after the new year. Remaining V3 work should not be a code overhaul. Any refactoring requests must be approved by Product and Tech Lead.

- [ ] Uncomment the code in the Celery task [v3_send_email_notification](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/v3/notification_tasks.py#L183), and get it to work.
- [ ] Write appropriate unit tests in tests/app/celery/v3/test_notification_tasks.py.  You should mock the [call to client.send_email](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/v3/notification_tasks.py#L223), and test its call args.

## Acceptance Criteria

- [ ] An e-mail notification sent with v3 looks identical to the same notification sent with v2

## QA Considerations
- [ ] regression passes
- [ ] manually validate the feature
- [ ] see if this can be automated, create ticket if so

**Comment by k-macmillan** [comment]
The checklist and AC are too light. This code is not complete without fixing the logging, docstrings, and having appropriate methods for the code being executed. Database calls will be done in a repeatable manner within functions that log (similar to [this](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/v3/notification_tasks.py#L237C5-L237C35)). Labelled with Changes Requested.

**Comment by kalbfled** [comment]
I reviewed and updated this ticket.

**Comment by kalbfled** [comment]
@cris-oddball A separate ticket will restore the "simulate" functionality of v2, but that behavior isn't really defined in v3 since POST v3 doesn't return 201.  I could write it to persist a notification without actually sending it, and I could note in the status reason that it is a simulated notification.  Then one could GET the notification for testing purposes.

**Comment by cris-oddball** [comment]
@kalbfled I'll need a primer on what email simulation is and how that relates to email formatting.

**Comment by k-macmillan** [comment]
Will re-address with va-enp-api.
