### ISSUE TITLE
Implement SQS alerts for VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#152]
# Value Statement
**As a** developer
**I want to** receive alerts on app metrics via PagerDuty and Slack (when resources costs are high, systems are down, or our api isn't functioning as expected)
**So that** I can respond appropriately

# Acceptance Criteria
**GIVEN** an alert notifies the team about a concern
**WHEN** the developer receives the notification via PagerDuty
**THEN** they are informed enough to act on the notification.

**GIVEN** an alert notifies the team about a concern
**THEN** an alert is sent via Slack.

**GIVEN** an alert needs to be changed
**THEN** a developer can update the code to update the dashboards/alerts

# Checklist
- [ ] Add metrics to Datadog dashboard, [using terraform](https://docs.datadoghq.com/api/v1/dashboards/)
- [ ] Configure alerts (see below)

# Alerts to set up
- SQS:
    - [x] QueueLength reaches a certain size
      - [x] 'send-email-tasks' reaches 50 messages
      - [x] 'send-sms-tasks' reaches 50 messages

# Assumptions
- PagerDuty and Slack alerting integration is complete and a DataDog dashboard exists (#223)
- ~For now, we will set up alerts with CloudWatch and move to DataDog later.~ Since we want to move to DataDog eventually and have the alerts all in one place, we should set them up in DataDog now instead of putting work into CloudWatch first and migrating.
- For thresholds, we will initially set them at low values and alter them once we are getting too many alerts. These thresholds will change as we send more notifications.

# Additional Info/Resources
-  Research from the spike #151 in [Google doc](https://docs.google.com/document/d/1gwaBA9jC__IYMLcdpQjVPw3UjsKy1GVOjhtQa2nSEY8/edit), explaining the reasoning and how to set up each alert.
- Helpful [PagerDuty setup video](https://www.youtube.com/watch?v=eGUjzjkOwSw)
- [DataDog monitor](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/monitor) terraform
- Refer to ADR 6 in `vanotify-team` repo
- [DataDog cloudformation and terraform on guthub](https://github.com/DataDog/cloudformation-template)

# Out of Scope
- On-call procedure for PagerDuty - bigger conversation needs to occur

# Open Questions
-  Which alerts warrant a notification via PagerDuty versus a Slack message? Should a slack message always be sent?
- Do we only want to see metrics/get alerts for all environments?

**Comment by miabecker** [comment]
Broken down this card so this one can be closed.

**Comment by miabecker** [comment]
QA by triggering alerts in dev.

**Comment by jsmithVA** [comment]
Waiting to test with load testing
