### ISSUE TITLE
Setup Backup and Recovery for VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#153]
# Value Statement:
**As a** VANotify developer
**I want to** ensure all the data in VANotify is backed up
**So that** the data can be recovered in the event of an emergency

# Acceptance Criteria
1. 
**GIVEN** I am in VANotify production
**WHEN** any data is stored 
**THEN** the data is backed up

2. 
**GIVEN** I am in VANotify production
**WHEN** data recovery is initiated
**THEN** all data is restored from the specific back up

# Checklist:
- [x] Use aurora snapshot to restore data
- [x] 30 days DB snapshot for production
- [ ] Make sure the Prod Aurora settings comply with VA and/or ATO

# Assumptions:
- The data is backed up 
- For this card we will not delete any data. @QaysarA to followup on this conversation how long data needs to be stored and the applicable laws
- AWS Aurora takes care of creating snapshots which means backup or recovery issues are handled by AWS.

# Additional Info/Resources:
- Sync with Filip on the decision that was made on using standard backup and recovery setup in Aurora
- All team members are able to restore using snapshots

# Out of Scope:
- Implementing a disaster recovery plan

# Open Questions:
- How will the backup and recovery be tested? **To restore the DB form the latest backup.**
- How long is the backup data stored for? **Currently the last 7 days**
- Do we need to treat all of the data the same. Example - Organizations don't need to be backed up too often. But emails will probably require more frequent backups. This will depending on what Aurora has as a functionality. **all the data is stored in DB and since Aurora is distributed, fault-tolerant and self-healing storage system once a day snapshots are sufficient.**
- In addition to Production, this may be required in Staging or other lower environments for testing. **We have set daily snapshots for development and staging environments for up to 7 days** 
- Are there any rules or regulations we have to follow for backup and recovery **It should be in the ATO otherwise VA guidelines**

**Comment by saman-moshafi-va** [comment]
The VaNotify DB is AWS Aurora, setup and configured by [Terraform db module](https://registry.terraform.io/modules/terraform-aws-modules/rds-aurora/aws):
`Amazon Aurora features a distributed, fault-tolerant, self-healing storage system that auto-scales up to 64TB per database instance. It delivers high performance and availability with up to 15 low-latency read replicas, point-in-time recovery, continuous backup to Amazon S3, and replication across three Availability Zones (AZs)`
The outcome of this user story will define the values for the Terraform db module for dev, staging and prod environments.

**Comment by saman-moshafi-va** [comment]
VSP IoC is on department-of-veterans-affairs/devops.  They use 7 as the DB backup retention.  Based on the VSP devops code and assuming they follow the VA standards, we are following the VA standards.
