### ISSUE TITLE
RDS parameter group and pg_cron

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1531]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** database administrator
**I want** a scheduled task that automatically deletes entries older than 30 days from the `notification_failures` table
**So that** we can maintain data hygiene and manage storage effectively without manual intervention.

### Additional Info and Resources
To enable this feature, we'll be using the pg_cron extension, which is compatible with our AWS RDS for PostgreSQL setup. Detailed setup and usage instructions for pg_cron can be found in the [AWS RDS pg_cron documentation](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL_pg_cron.html).
[PostgreSQL extensions](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.PostgreSQL.CommonDBATasks.Extensions.html)

and, to quote [this slack thread](https://oddball.slack.com/archives/C036AE08HA7/p1698867002250589):

> If we can install pg_cron, then it should be as easy as
> ```
> CREATE EXTENSION pg_cron;
> SELECT cron.schedule('0 0 * * *', $$DELETE FROM notification_failures WHERE created_at < NOW() - INTERVAL '30 days'$$);
> ```

## Engineering Checklist

- [ ] Create a custom parameter group for postgres15.
- [ ] Modify the custom parameter group to include pg_cron.
- [ ] Install the pg_cron
- [ ] Create the extension with `CREATE EXTENSION pg_cron;`.
- [ ] Implement a pg_cron job to delete outdated entries.
- [ ] Test to ensure the cron job functions correctly.
- [ ] Document the setup and the cron job details.

## Acceptance Criteria

- Entries older than 30 days in the `notification_failures` table are deleted automatically by the scheduled pg_cron job.

**Comment by k-macmillan** [comment]
At this time we do not _require_ pg_cron nor custom parameter groups. We are going to hold off on this until we have a more specific need.
CC @coreycarvalho
