### ISSUE TITLE
Clean up, refactor and optimize app/celery/v3/notification_tasks.py

### ISSUE THREAD

**Issue by nikolai-efimov** [department-of-veterans-affairs/notification-api#1534]
## User Story - Business Need
We need to refactor code in app/celery/v3/notification_tasks.py to optimize performance, readability, and maintainability of the code.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As an** engineer
**I want** refactor code in app/celery/v3/notification_tasks.py
**So that** we improve performance, readability and maintainability of the code

**As an** engineer
**I want** refactor code in app/celery/v3/notification_tasks.py
**So that** we don't call database more times than absolutely necessary

### Additional Info and Resources

https://github.com/department-of-veterans-affairs/notification-api/pull/1532

## Engineering Checklist

- [ ] organize a discussion with the team about refactoring into functions and document the agreement
- [ ] code refactored into separate functions
- [ ] separate tests for the new functions are added
- [ ] consider changing [this function as described](https://github.com/department-of-veterans-affairs/notification-api/pull/1532#discussion_r1388365515)
- [ ] critical error messages are logged https://github.com/department-of-veterans-affairs/notification-api/pull/1532#discussion_r1388133752
- [ ] addressed [If get_default_sms_sender_id got called, this query is getting the same ServiceSmsSender instance](https://github.com/department-of-veterans-affairs/notification-api/pull/1532#discussion_r1388142323)
- [ ] addressed line 5 TODO - Should I continue using notify_celery?  It has side-effects.
- [ ] addressed line 65 TODO - Error handler for sqlalchemy.exc.IntegrityError.  This happens when a ...
- [ ] addressed line 97 TODO - Catch db connection errors and retry?
- [ ] addressed line 105 TODO - This isn't an option right now because Notification.template_id is non-nullable ...
- [ ] addressed line 109 TODO - Delete logging when the above issue is remedied ...
- [ ] addressed line 129 TODO - Launch a new task to get the contact information from VA Profile using the recipient ID
- [ ] addressed line 146 TODO - Catch db connection errors and retry?

## Acceptance Criteria

- All TODOs are addressed and, if needed, follow up tickets are created
- Code is refactored to avoid unnecessary calls to db
- Code is refactored into functions for better readability, maintainability and reuse
- All functions are covered with unit tests
- All tests pass locally and on Dev
- All tests from [1504](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1504) still pass locally, on Dev, Perf

## QA Considerations
- work with dev regarding any edge cases
- ensure any v3 regression passes

**Comment by kalbfled** [comment]
Re: "separate tests for the new functions are added"

Any function not currently decorated as a task needs unit tests.  This includes get_default_sms_sender_id.

**Comment by kalbfled** [comment]
I'm removing the bullet points already covered by #1505 and #1518.

**Comment by kalbfled** [comment]
@mjones-oddball I don't recommend working on this ticket during the sprint that begin the week of 12/11.  There are higher priorities, and the verbiage in this ticket relates to opinionated decisions that I would appreciate the team not make in my absence next week.
