### ISSUE TITLE
Regular Update for Dependencies - API Core Code

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1552]
## User Story - Business Need

We wish to keep dependencies up to date so we do not need such massive overhauls of our system. This will be a recurring ticket that will be done every sprint. We will update all dependencies we are able to. Any conflicts will get a ticket. This is intended to be a day of work at most because this is intended to update with only non-breaking changes.

- [x] Ticket is understood and QA has been contacted

### User Story
**As** VA Notify
**I want** to keep our service up to date
**So that** we are secure and as free of bugs as possible

### Additional Info and Resources
- Relevant section of [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-requirementstxt)

## Engineering Checklist

- [x] Update performed
- [x] Dependabot issues updated
- [x] Any conflicts removed and tickets created
- [x] Passes all tests locally
- [x] Any major changes are investigated (compare existing to new version changes)
  - [x] Any questionable version changes are removed and a ticket is created
- [x] Tickets created are added to the Epic for tracking purposes

## Acceptance Criteria
Repo dependencies are updated and we have no broken functionality. Issues opened by Dependabot are resolved. Tickets created for any updates we could, or should, not do.

## QA Considerations
- [x] Check to see if these updates cancel out any Twistlock issues
- [x] QA Regression tests pass after deploying this code.

**Comment by edDocMe360** [comment]
https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/7185890153

**Comment by cris-oddball** [comment]
Ed created #1571 to resolve werkzeug upgrade

**Comment by cris-oddball** [comment]
@edDocMe360 please check off the boxes on this ticket that you are able to check off and move the ticket to the QA lane now that you have merged this branch into master. As I explained earlier, this needs to be handled before you start working another ticket so that we can keep things moving along the board.

cc\ @npmartin-oddball @k-macmillan

**Comment by cris-oddball** [comment]
PR approved and merged to master, sent to perf, regression passes.

Need to wait to clear Twistlock until after the Prod deploy tonight else Twistlock will fail on that tag which does not include these changes.

**Comment by cris-oddball** [comment]
This closed four Twistlock tickets (and a handful of dependabot issues
