### ISSUE TITLE
Regular Update for Dependencies - Lambdas

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1553]
## User Story - Business Need

We wish to keep dependencies up to date so we do not need such massive overhauls of our system. This will be a recurring ticket that will be done every sprint. We will update all dependencies we are able to. Any conflicts will get a ticket. This is intended to be a day of work at most because this is intended to update with only non-breaking changes.

- [x] Ticket is understood and QA has been contacted

### User Story
**As** VA Notify
**I want** to keep our service up to date
**So that** we are secure and as free of bugs as possible

### Additional Info and Resources
- Relevant section of [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-requirementstxt)

## Engineering Checklist
**Please note, layers are in infra, so you may need PRs in multiple repos to address updates.**

- [x] Update performed
- [x] Dependabot issues updated - no dependabot issues relating to lambdas
- [ ] Any conflicts removed and tickets created
- [ ] Passes all tests locally - *local tests don't use lambda environment*
- [x] Passes testing in Dev environment
- [x] Lambda layers update and infra PR created
- [ ] Any major changes are investigated (compare existing to new version changes)
  - [ ] Any questionable version changes are removed and a ticket is created
- [ ] Tickets created are added to the Epic for tracking purposes

## Acceptance Criteria
Repo dependencies are updated and we have no broken functionality. Issues opened by Dependabot are resolved. Tickets created for any updates we could, or should, not do.

## QA Considerations
- [x] Check to see if these updates cancel out any Twistlock issues
- [x] QA Regression tests pass after deploying this code.

**Comment by EvanParish** [comment]
Picked this up yesterday afternoon and spoke with Cris about it. I'm working on creating a repeatable lambda layer creation process. Just a note, this will require a PR in both API and Infra.

**Comment by EvanParish** [comment]
I created a bash script that can be used to create a lambda layer. It's still a somewhat manual process, but I feel this script removes some of the really tedious parts in that process. I'll share the script in the glossary in our lambda layers doc. Using this script I updated all of our lambda layers, but I still need to take a closer look at what's going on with the va_profile lambda and its dependencies. 

I ran the QA suite against Dev after updating the layers and everything passed, but I'll need to do some log checking to double check there weren't any errors. Plus, there are several lambdas that will need some manual validation.

**Comment by EvanParish** [comment]
Updated the bash script that creates lambda layers and added it to the kafka repo. I also ran it in the kafka repo and added requirements files for each lambda layer we have. Other than that, I'm still working on manual testing of some of the lambdas.

I'll link the [kafka PR here](https://github.com/department-of-veterans-affairs/notification-kafka/pull/37) since it looks like it's not showing up.

**Comment by EvanParish** [comment]
Performed a lot of lambda testing and they are all looking good so far. I haven't seen any errors that would point to updated dependencies being a problem. Trying to work through the last few, but the PRs are up for review now.

**Comment by cris-oddball** [comment]
Just noting that Evan did most of the testing and I am spot-checking this in staging on the Jan 10 deployment ticket.

**Comment by cris-oddball** [comment]
hotfixes added and verified as working. Now we can close this ticket.
