### ISSUE TITLE
Update ECS Task Definitions for Twilio SSM Parameter Change

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1564]
## User Story - Business Need

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** software engineer<br>
**I want** to update the ECS Task Definitions to reference the new Twilio SSM parameters<br>
**So that** our application can correctly access the updated Twilio secret in SSM for the vetext-forwarder lambda function

### Additional Info and Resources
The Twilio SSM parameters were manually created and have now been updated using Terraform. This change affects the vetext-forwarder lambda function. Our ECS application's Task Definitions need to be updated to align with these new parameter changes. 

## Engineering Checklist

- [ ] Update ECS Task Definitions to use new Twilio SSM parameters.
- [ ] Ensure proper functioning in the staging environment before deployment to production.
- [ ] Delete old Twilio SSM parameters after successful deployment to production.

## Acceptance Criteria
- When deploying, the ECS application should successfully retrieve Twilio secret values from the new SSM parameters.
- Ensure no disruptions in application functionality during and after the update.
- Old Twilio SSM parameters should be removed only after confirming the successful deployment and operation in the production environment.

**Comment by cris-oddball** [comment]
Closing as the forwarder does not have task definitions.
