### ISSUE TITLE
BUG: v3 Catch KeyError and Raise BadRequestError for Invalid phone_info

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1585]
## Description
With the change to the API for a similar issue in v2 on #1525, we now return an error on POST sms with an invalid prefix. v3 however defers validation downstream and so we still get a long stacktrace. This error should be handled better for v3.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. send a POST v3/sms request with the following payload
```
{
    "template_id": "{{sms-template-id}}",
    "phone_number": "+80888888888"
}
```
2. Observe that a 202 and a notification id is returned by the route, but GET v2/notifications/{notification-id} stays stuck at creating
3. Observe the following logs
<img width="928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGFTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08c6c7f5c78ae26434d551bd24e2917b217e82d7/Screenshot%202024-01-02%20at%208.43.00%E2%80%AFAM.jpg" alt="Screenshot 2024-01-02 at 8.43.00 AM.jpg" />

<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGVTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa6d71dee95db66c5f7de69bf35228de7f565f46/Screenshot%202024-01-02%20at%208.43.17%E2%80%AFAM.jpg" alt="Screenshot 2024-01-02 at 8.43.17 AM.jpg" />

## Workaround
Is there something we can do to work around this issue in the meantime?
None

## Impact/Urgency

Poor experience, should be resolved before we release v3.

## Expected Behavior

This is an engineering decision point since we are deferring certain validations. But this should not result in a long stacktrace in the logs and a status of 'creating'.

## QA Considerations
- [ ] add test to regression for this use case

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1585?planning-poker) with Zenhub @cris-oddball @edDocMe360 @EvanParish @k-macmillan @kalbfled
