### ISSUE TITLE
Remove legacy tables no longer used by Strike team

### ISSUE THREAD

**Issue by MarchandMD** [department-of-veterans-affairs/notification-api#1586]
## Description

Strike team has removed 2 tables that are no longer needed

- `user_to_service` table

Requesting these tables be removed from api as well

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify developer
**I want** vestigial tables removed
**So that** our database does have unnecessary things

## Acceptance Criteria

- [ ] schema no longer has `user_to_service` table
- [ ] related models removed as well

**Comment by cris-oddball** [comment]
Moving this back to New since this seems somewhat important, even if no one told us about it.

**Comment by cris-oddball** [comment]
This should be a Story ticket.

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1586?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday

**Comment by cris-oddball** [comment]
Do we use these tables?

**Comment by cris-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1586?planning-poker) with Zenhub @EvanParish

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1586?planning-poker) with Zenhub @k-macmillan @mchlwellman
