### ISSUE TITLE
Update workflows in API based on Dependabot

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1588]
## User Story - Business Need
We want to keep all dependencies up to date. The Dependbot issues for workflows often get overlooked in regular dependency update tickets. This ticket means to resolve outstanding workflow dependabot-raised dependencies.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want** our workflows to be up to date
**So that** we do not fall behind and can also utilize any new features they may include

## Engineering Checklist

At the time of this writing, these are the issues. Check for any additional workflow [Dependabot PRs](https://github.com/department-of-veterans-affairs/notification-api/pulls?q=is%3Apr+is%3Aopen+bump) that may have been created, usually prefaced by `*actions/`
- [ ] [setup-python](https://github.com/department-of-veterans-affairs/notification-api/pull/1567)
- [ ] [amazon-ecr-login](https://github.com/department-of-veterans-affairs/notification-api/pull/1495)

## Acceptance Criteria

There are no open Dependabot PRs for workflows in the notification-api repo

## QA Considerations
- [ ] all dependabot issues for workflow in the notification-api repo have been updated
- [ ] any action updated has been tested to work

## Out of Scope
Any dependabot issue that is not a workflow.

**Comment by ldraney** [comment]
note: important to test any workflow that is affected by these changes.  By testing, run it after checking version warnings or any listed breaking changes (if any).

**Comment by ldraney** [comment]
note: may be wise to just use the dependabot PRs

**Comment by npmartin-oddball** [comment]
Chat with Kyle re: findings/experience working on ticket.

**Comment by k-macmillan** [comment]
No longer relevant
