### ISSUE TITLE
Create a dashboard for statsd metrics in DataDog

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#159]
# Value Statement
**As** VA Notify system owner
**I want to** have quick and easy access to application metrics
**So that** I know if the systems behave correctly

# Acceptance Criteria
**GIVEN** I'm logged in to DataDog
**WHEN** I go to dashboards
**THEN** I can see application metrics dashboard
**WITH** graphs / counters etc. that will give information about statsd metrics

**GIVEN** dashboards for statsd metrics are created
**WHEN** a confirmation email is sent  **successfully**
**THEN** the dashboard shows statsd was incremented for both email success metrics

**GIVEN** dashboards for statsd metrics are created
**WHEN** a confirmation email is **fails** to send
**THEN** the dashboard shows statsd was incremented for both email failure metrics

# Checklist
- [x] Set up Dashboard via the DataDog UI
- [x] Dashboard has graphs that represent the statsd metrics
  - [x] development.notifications.delivery.clients.govdelivery.<status>
  - [x] development.notifications.app.service_id.<service id>.POST.v2_notifications.post_notification.<status>

# Open Questions
- Do we want a different dashboard for each environment? Yes
- ~Are we creating the dashboard via terraform or the UI?~ For now, in the UI. We can port it over to terraform in the future via card #230, but it's not a priority now.

**Comment by saman-moshafi-va** [comment]
* to test 400 errors we can use postman to send wrong number of expected per_**s**_onalisations
* we can place the wrong Granicus secret, send email request, make sure datadog reveals the failure, then change back the secret
