### ISSUE TITLE
v3 - validate template

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1590]
## User Story - Business Need

v2 post_notification, and elsewhere, calls app/notifications/validators.py::validate_template, which contains some checks not in app/celery/v3/notification_tasks.py::v3_process_notification.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,<br>
**I want** v3 behavior to mirror v2 behavior<br>
**So that** users have a consistent experience.

## Engineering Checklist

- [ ] Write unit tests
- [ ] In [v3_process_notifications](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/v3/notification_tasks.py#L68), call [validate_template](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/notifications/validators.py#L146) before passing data to any other task used to send a notification.
- [ ] Catch any exceptions raised by validate_template, and persist the failure with an appropriate status reason.

## Acceptance Criteria

- [ ] Deployed, regressed, and manually verified to mirror v2

**Comment by k-macmillan** [comment]
Will re-address with va-enp-api.
