### ISSUE TITLE
BUG: Can't Connect to MPI in Prod

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1603]
## Description

After the deploy on 2023-01-10 around 7:40 PM Eastern we started seeing thousands of failed requests to MPI. This seems to potentially be related to Python 3.10 updated it's minimum TLS version to 1.2 whereas with Python 3.8 we had TLS versions 1.1 and 1.0 available.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Deployed our API to Prod 
2. Observed issues connecting to MPI related to an SSL error

## Workaround
Is there something we can do to work around this issue in the meantime?

Currently we have redeployed the last revision of our celery service, which seems to have fixed the issue for now, but this is a very short-lived solution.

## Impact/Urgency

**Extremely Urgent**: This impacts the functionality of our app in Production.  Without a fix, we cannot deploy to production and have the application work properly.
## Expected Behavior

- [x] When our application is deployed to prod it can connect to MPI

**Comment by EvanParish** [comment]
I reached out to Danny Reed and IAM Architecture via email. They are looking into the failed requests we saw after our last deploy. They said TLS versions 1.1 and 1.2 are enabled on their end in both Staging(SQA) and Production. 

Doing some testing and running the following commands in staging and prod produced the same results in both environments, which were not helpful. They seemed to point to TLS v1.2 being enabled on both environments, but couldn't connect from the EC2 instances.
curl test
```
curl -iv --tlsv1.2 <env-url>
```

openssl
```
openssl s_client -debug -connect <env-url> -prexit
```

**Comment by EvanParish** [comment]
I heard back from IAM Architecture saying they don't have logs relating to the incident we saw. More specifically it looks like we completely failed to connect to them during that time since the SSL errors prevented us from reaching them, then there was a big spike when we reverted, which was our retries working. 

We might want to try deploying the branch with all the VA certs to Prod to make sure we aren't missing something there. We can just revert again if it doesn't work, and with retries messages won't be lost.

**Comment by mjones-oddball** [comment]
@EvanParish can you please add an update please? I believe you attempted to deploy since your last comment and it didn't work.

**Comment by EvanParish** [comment]
Yes, we did try deploying again to gather some more useful logging. We got a stacktrace of the error, but it didn't end up being very helpful. 

I've been in talks with IAM Architecture team and we now have a meeting scheduled for 2 PM ET tomorrow. They validated that Pre-prod and Prod both have TLS 1.2 enabled and that our certificates are whitelisted on their end. It's still a mystery what exactly is causing this connection problem. Hopefully the meeting will be illuminating. 

Other than that, I'm still doing some research of my own to try and figure out what could cause this error.

**Comment by EvanParish** [comment]
After meeting with MPI and them managing to get some packet captures on their end, it seems there's now a cipher mismatch between their Prod environment and our updated environment. There are more ciphers available in their lower environments, so we can connect there. This seems to be a matter of updating our request to use a cipher that is supported by their Prod environment and we should be able to connect again. 

Things I'm looking into:

**gunicorn**:
I looked into gunicorn and according to the [gunicorn docs on ciphers](https://docs.gunicorn.org/en/20.1.0/settings.html#ciphers) it uses the default ciphers from the python ssl module.

> By default we use the default cipher list from Python’s `ssl` module, which contains ciphers considered strong at the time of each Python release.

After attempting to change that I realized that's probably just the ciphers used to connect to us, not what's used when we reach out. 

**requests / urllib3**
I'm looking into how one might define what ciphers to use when making a request so we can ensure we have some in common when connecting to their Production environment. [This article](https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/) seems to be the go-to when attempting to configure specific ciphers when making an outgoing request. Hopefully using that information I can define the proper ciphers we need and get connected.

**Comment by EvanParish** [comment]
I added an expanded list of ciphers to our mpi request and this seems to have done the trick. The cipher we were using previously must have been lost in the upgrade.

**Comment by cris-oddball** [comment]
I am just going to leave this ticket in QA until the code goes all the way up to Prod without pain. :)

**Comment by cris-oddball** [comment]
This code is sitting on Prod, no logs shown since that deploy with the SSLV3_ALERT_HANDSHAKE_FAILURE error.

Closing ticket!
