### ISSUE TITLE
SPIKE: Notification-api - OIDC Authentication for AWS in GitHub Actions

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1613]
## User Story - Business Need

We are receiving warnings that we need to convert to OIDC auth for AWS. It is recommended to use OIDC, hence this ticket.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)
**As a** DevOps engineer
**I want** to implement OpenID Connect (OIDC) authentication for Amazon Web Services (AWS) within our GitHub Actions workflows in notification-api
**So that** we can enhance security by not storing long-term AWS credentials and comply with best practices for cloud resource access.

### Additional Info and Resources

Documentation for [configuring OIDC in AWS and updating GitHub Actions](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services). This includes detailed steps for adding the identity provider to AWS, updating trust policies in IAM, and modifying GitHub Actions workflows for OIDC authentication.

Example of the workflow adjustment:
```
- name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@latest
  with:
    role-to-assume: <role-arn> # ARN of the role to be assumed
    aws-region: <aws-region> # Your AWS region, e.g., us-east-1
...
permissions:
  id-token: write
  contents: read
```

Below are some items that were thought to be steps in this approach:
- [ ] **Review OIDC and AWS Integration Documentation**: Understand integration specifics for OIDC with AWS.
- [ ] **Coordinate OIDC Provider Setup with VAEC**: Request VAEC to create an OIDC provider in AWS for `notification-api`.
- [ ] **Modify IAM Roles and Policies for OIDC**: Align AWS IAM roles and trust policies with OIDC setup.
- [ ] **Update GitHub Actions Workflows**: Adapt workflows in `notification-api` repository as per OIDC requirements.
- [ ] **Set GitHub Workflow Permissions**: Configure `id-token: write` permissions in GitHub Actions workflows.
- [ ] **Test Updated Workflows and delete long-term AWS credentials**: Validate workflow functionality post-update and remove old AWS credentials.

## Acceptance Criteria

- [ ] Technical Documentation has been created and linked in the glossary
- [ ] Learnings have been shared with the team, and decisions have been documented
- [ ] Tickets for next steps have been identified and created

Completed research addresses the problems and/or answers the questions below:  
- GitHub Actions workflows in notification-api authenticate with AWS using OIDC.
- Functionality of Actions remains unchanged.
- Addresses applicable warnings related to AWS credentials in workflows

## Potential Dependencies

- AWS IAM access and permissions adjustments requiring VAEC coordination. 

## Out of Scope

- Alterations to existing workflow logic beyond authentication method.

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1613?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1613?planning-poker) with Zenhub @kalbfled
