### ISSUE TITLE
Seed the va profile opt in/out cache with our test users - e2e testing

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1619]
## User Story - Business Need

We want to perform e2e testing of the BIP workflow so that we can be assured that the pieces all work together. In this ticket, we seed the Perf va profile optin/out cache with our test users.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   VANotify engineer
**I want**    to configure a testing setup for the kafka integration
**So that**  i can be assured that it works prior to sending real data through the system.

### Additional Info and Resources

- note this ticket depends on having test users. Cris was to reach out to Danny Reed/MPI to obtain these so check with her to see if we have those users.

## Engineering Checklist

- [x] Add test users to the Perf vaprofile cache using [documentation](https://docs.google.com/spreadsheets/d/1YKvcB-V6AzGsSYmcVaTwISA8jWeBvaWnjSFS4zcK9NA/edit?usp=sharing)

## Acceptance Criteria

- Our tests users are documented and found in the Perf vaprofile cache.

## QA Considerations
- Review Perf cache for accuracy

## Potential Dependencies
- Without test users created this issue cannot be worked (see #1619)

## Out of Scope
- Modifying the producer's test events

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1619?planning-poker) with Zenhub @k-macmillan @cris-oddball @EvanParish @kalbfled @ldraney

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1619?planning-poker) with Zenhub @mchlwellman

**Comment by kalbfled** [comment]
I will run this query:
```sql
insert into va_profile_local_cache (va_profile_id, communication_item_id, allowed, communication_channel_id) values
(1550938, 5, true, 1),
(1135366, 5, true, 1),
(1413426, 5, true, 1),
(401615, 5, true, 1),
(1413440, 5, true, 1),
(210935, 5, true, 1),
(1609559, 5, true, 1),
(1609567, 5, true, 1),
(1609561, 5, true, 1),
(269679, 5, true, 1),
(270171, 5, true, 1),
(272109, 5, true, 1),
(272407, 5, true, 1),
(1593113, 5, true, 1),
(1593115, 5, true, 1),
(1593117, 5, true, 1),
(1593119, 5, true, 1),
(1593121, 5, true, 1),
(1593123, 5, true, 1),
(1593325, 5, true, 1),
(1593329, 5, true, 1),
(1593335, 5, true, 1),
(1593339, 5, true, 1),
(1593349, 5, true, 1),
(1593343, 5, true, 1),
(1609691, 5, true, 1),
(1610101, 5, true, 1),
(1610111, 5, true, 1),
(1610167, 5, true, 1),
(1610199, 5, true, 1),
(1610197, 5, true, 1),
(1610215, 5, true, 1),
(1610243, 5, true, 1),
(1610273, 5, true, 1),
(1610275, 5, true, 1);
```

**Comment by cris-oddball** [comment]
**QA PASSES**

- [ ] Cross-referenced the inserted VA Profile IDs with the spreadsheet
- [ ] Ran the Perf ETL lambda and cross-checked the VA Profile IDs it picked up with the spreadsheet
- [ ] Reviewed the new insertions in the Perf DynamoDB table: started with 20, 35 were added, total count is 55
