### ISSUE TITLE
Update `pytest` and `moto` in Test Container

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1624]
## User Story - Business Need
New versions of pytest and moto broke our test environment, as such they were pinned to the non-breaking changes temporarily. The purpose of this ticket is to update pytest and moto to their newest versions and fix the breaking changes. This should only affect our tests and should have no bearing on app code.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify engineer
**I want** current software
**So that** our code runs smooth and we have access to all features

### Additional Info and Resources

- [pytest changelog](https://docs.pytest.org/en/8.0.x/changelog.html)
- [moto changelog](https://github.com/getmoto/moto/blob/master/CHANGELOG.md#500)
- [semver compatibility](https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release)

[Specific to the moto upgrade](https://docs.getmoto.org/en/latest/docs/releases.html):
>   For Moto 5.x:
>         All decorators have been replaced with mock_aws
>         The batch_simple decorator has been replaced with: @mock_aws(config={“batch”: {“use_docker”: False}})
>         The awslambda_simple decorator has been replaced with: @mock_aws(config={“lambda”: {“use_docker”: False}})
>         When starting the MotoServer, the service-argument (i.e.: motoserver s3) is no longer supported. A single MotoServer-instance can be used for all AWS-services.

Test that fail out include

>  tests/app/celery/test_scheduled_tasks.py:9: in <module>
>     from moto import mock_dynamodb
>      from moto import mock_dynamodb
> E   ImportError: cannot import name 'mock_dynamodb' from 'moto'
> 
>  tests/app/letters/test_letter_utils.py:7: in <module>
>     from moto import mock_s3
> from moto import mock_s3
> E   ImportError: cannot import name 'mock_s3' from 'moto'
> 
> tests/lambda_functions/two_way_sms/test_two_way_sms_v2.py:11: in <module>
>     from moto import mock_ssm
> E   ImportError: cannot import name 'mock_ssm' from 'moto'

## Engineering Checklist

- [x] pytest upgraded to 8.x (note: it looks like this was upgraded, double0check to be sure)
- [x] moto upgraded to 5.x
- [x] All dependencies locked to ~= M.m
  - e.g. `pytest ~= 8.0`. No third decimal place ([patch version](https://semver.org/)), and all contain `~=`

## Acceptance Criteria

- pytest and moto upgraded to 8.x and 5.x respectively. 
- After the upgrade, all unit tests pass

## Potential Dependencies
[1436](https://github.com/department-of-veterans-affairs/notification-api/issues/1436) must be finished first.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1624?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @mchlwellman

**Comment by EvanParish** [comment]
I update the dependency and made the necessary changes. There's one test that fails when running locally in a container, but looks like it passes when the tests are run on the PR. I'll continue trying to figure out what's going on with that tomorrow. 

The test failing locally is this one: `test_fetch_notification_status_for_service_for_day`

**Comment by EvanParish** [comment]
PR has been merged
