### ISSUE TITLE
Terraform and AWS Provider Upgrade for App, Base, and Admin

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1625]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As** DevOps 
**I want** to upgrade our Terraform and AWS provider for app, base, and admin
**So that** we can better ensure our infrastructure's security, maintainability, and development efficiency.

### Additional Info and Resources
We have a somewhat complete upgrade of Terraform and AWS provider across app, base, and admin segments, as detailed in [PR #719](https://github.com/department-of-veterans-affairs/vanotify-infra/pull/719/files) and validated by the latest [PR terraform plan](https://github.com/department-of-veterans-affairs/vanotify-infra/actions/runs/7698561967). The PRs current status:

- Still need to address a breaking bug in base infrastructure, related to [issue #279](https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/issues/279), but the fix is related to `source_json and override_json have been removed -- use source_policy_documents and override_policy_documents, respectively, instead.`
- Successful deployment of application-infrastructure
- Successful terraform plan admin, though no issues are anticipated.
- Still need to deploy notification-api on top of dev infra, and then to run regression, to ensure compatibility

## Engineering Checklist

- [ ] Address the known breaking bug in the base infrastructure as part of a separate follow-up ticket.
- [ ] Review and finalize the upgrade in PR #719, ensuring all changes are tested
- [ ] Ensure application-infrastructure is fully deployed and subjected to regression testing.
- [ ] Deploy notification-api on top of dev infra, and then to run regression, to ensure compatibility
- [ ] Update Documentation and Glossary with Upgrade Process
- [ ] Create a ticket to finish automating this upgrade pipeline 
     - [ ] (that ticket should mention [#721](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-infra/721))
     - [ ] This ticket should mention utilizing or deleting the `upgrade.yml`

## Acceptance Criteria

- Terraform and AWS provider upgrade is completed across app, base, and admin segments.
- Documentation is updated to reflect the upgrade process and any changes introduced.
- Follow-up tickets are created/updated for unresolved issues and future automation enhancements.

## Out of Scope

- Direct modifications to infrastructure components not related to the Terraform and AWS provider upgrade.
- Full automation of the Terraform upgrade process is intended for a follow-up ticket.  The current ticket is focusing on the necessary GitHub Action workflow adjustments (manual process with documentation is good enough)

**Comment by cris-oddball** [comment]
Closing because this was recently handled on other tickets.
