### ISSUE TITLE
Use separate ECR repositories to enable usage of lifecycle policies

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#163]
# Value Statement:
**As** a vanotify system owner
**I want to** use ECR repository lifecycle policies
**So that** we control how many docker images keep

# Acceptance Criteria
**GIVEN** development ECR repository
**WHEN** I push a new image
**THEN** repository stores it only for 14 days and removes it afterwards

**GIVEN** staging ECR repository
**WHEN** I push a new image
**THEN** repository keeps only the latest 15 images and removes older images

**GIVEN** production ECR repository
**WHEN** I push a new image
**THEN** repository keeps only the latest 15 images and removes older images

**GIVEN** build pipeline
**WHEN** docker image is successfully built
**THEN** image is pushed to dev repository
**AND** image has git sha tag

**GIVEN** deployment pipeline
**WHEN** development deployment is successful
**THEN** image is pushed (promoted) to staging repository
**AND** image has git sha tag as well as version tag (vx.y.z)

**GIVEN** deployment pipeline
**WHEN** staging deployment is successful
**THEN** image is pushed (promoted) to prod repository
**AND** image has git sha tag as well as version tag (vx.y.z)

# Checklist:
- [ ] terraform code to create ECR repositories in dev/staging/prod
- [ ] terraform code that creates ECR repositories policies
- [ ] pipeline changes to push image to dev repository after image is built (with git sha)
- [ ] pipeline changes to push image to staging repository after successful development deployment (with git sha and version tag)
- [ ] pipeline changes to push image to prod repository after successful staging deployment (with git sha and version tag)

# Open Questions:
- Verify with team lifecycle policies - how many images and for how long do we want to keep?
- Do we want to use the same version tag across all environments? So instead of staging-v1.0.0 use v1.0.0 everywhere, since we would have separation on repository level.

**Comment by k-macmillan** [comment]
Being handled in infra.
