### ISSUE TITLE
provider details logic update and test fixes

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1631]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

#1436 ended with x-failing a number of tests failing when run sequentially and skipping another that leaves artifacts in the database.  This ticket is to completely overhaul `ProviderDetail` and `ProviderDetailHistory` tests. We removed SMS priority swapping in #944 and we have a follow-on to further clean that up with #962 .

### User Story(ies)

**As a**  Notify team member,
**I want** to ensure we have provider logic that makes sense
**So that** we provide the best service.

### Additional Info and Resources

- [Flowchart](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/provider_selection_flowchart.drawio.pdf)

## Engineering Checklist

- [ ] Best/appropriate provider logic is identified and implemented by testing paths of [this flowchart](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/provider_selection_flowchart.drawio.pdf)
- [ ] Remove all xfail decorators related to this ticket.  (grep "TODO 1631" to find them)

## Acceptance Criteria

- [ ] All tests pass and leave no database artifacts
- [ ] Searching the code for `TODO.*1631` shows no results

**Comment by npmartin-oddball** [comment]
Closing/no longer relevant. Will be fixed in enp-api.
