### ISSUE TITLE
BUG: xfailed v3 unit test for sending e-mail

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1634]
## Description

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

The file app/celery/v3/notification_tasks.py contains this snippet around line 191:
```python
    # Persist the notification so related model instances are available to downstream code.
    notification.status = NOTIFICATION_CREATED
    db.session.add(notification)
    # TODO - Is this necessary?  The template isn't being modified.  Refreshing fails.
    db.session.add(template)
    db.session.commit()
```
Not commenting-out `db.session.add(template)` results in the failure of unit test tests/app/celery/v3/test_notification_tasks.py::test_v3_send_email_notification.  However, commenting-out and removing that line results in e-mails not actually sending (as identified by a failing regression test).

This ticket is to resolve this disparity.

## Steps to Reproduce

1. Comment and uncomment as described above.  Run unit and regression tests.

## Impact/Urgency

V3 email is impacted - either the unit test fails or the actual email send fails

## Expected Behavior

- [ ] All unit tests pass without unnecessary or undesired x-fails.
- [ ] v3 send e-mail works (regression suite verifies this)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1634?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman
