### ISSUE TITLE
BUG: NotNullViolation in nightly notification status

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1653]
## Description

While working on SAWarnings in #1132, a pre-existing but unnoticed bug was found in `app/celery/reporting_tasks.py::create_nightly_notification_status` for the nightly stats query. 

The logs report
`psycopg2.errors.NotNullViolation: null value in column "notification_count" of relation "ft_notification_status" violates not-null constraint` whenever the nightly process runs.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Observe the Cloudwatch logs for any environment within an hour of midnight ET to see the following when the nightly process runs:

<img width="1406" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUJwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4da3d8927bb38756bde40cf84f34d5db73d79aa6/305245763-9a6381e8-711e-45fb-b39d-1962060834c2.png" alt="305245763-9a6381e8-711e-45fb-b39d-1962060834c2.png" />

## Impact/Urgency

Unknown

## Expected Behavior

- [ ] The Cloudwatch logs do not report a NotNullViolation when the nightly notification status runs
- [ ] Update the Slide deck with the key win and a demo slide

## QA Considerations
- [ ] verify this is not seen when deployed to Perf/Staging

## Additional Info & Resources

This does not need to wait until night time. The cron can be adjusted to run shortly after a deploy.

[app/dao/fact_notification_status_dao.py L88](https://github.com/department-of-veterans-affairs/notification-api/blob/df1332e2589f3d343969f7a41aa3fba2d694278f/app/dao/fact_notification_status_dao.py#L88)

<img width="721" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUpwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a7cdc8bb277364f91a38cfd45bc4e95196325d6/image%20%2826%29.png" alt="image (26).png" />

We have seen multiple iterations of this failure. For `notification_count`, It's not in the parameter list. Suspect it's being stripped out somewhere.
<img width="1069" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU5wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b9b8cebcede727b6030303a74bdeb6609c9231b/image%20%2827%29.png" alt="image (27).png" />

For `bst_date` it appears the whole row was null
<img width="1555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekYyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--46d4228497d6be9f064f168a83eae64571846f2a/image.png" alt="image.png" />

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1653?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment]
It's gone.
