### ISSUE TITLE
Upgrade dnspython library

### ISSUE THREAD

**Issue by mchlwellman** [department-of-veterans-affairs/notification-api#1660]
## User Story - Business Need

During #1647 (updating dependencies), the upgraded library dnspython caused regression test failures:

`2024-02-22T15:47:54 app app ERROR None "Error -3 connecting to dev-vanotify-redis-rep-group-1.cwa8jx.ng.0001.usgw1.cache.amazonaws.com:6379. Lookup timed out." [in /app/app/status/redis_check.py:12]`

2.6.0 and 2.5.0 both failed during regression testing. A new [release](https://dnspython.readthedocs.io/en/latest/whatsnew.html) is out and has not been tested.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VA Notify developer 
**I want**  to upgrade dnspython
**So that** we minimize vulnerabilities and future upgrade pains

### Additional Info and Resources

[This dnspython issue](https://github.com/rthalley/dnspython/issues/978) might be relevant.
[Changelog](https://www.dnspython.org/)

## Engineering Checklist

 - [ ] Unpin dnspython in requirements-app.txt
 - [ ] Build a new Docker image
 - [ ] Test the app locally
 - [ ] Update requirements.txt as described in README.md
 - [ ] Deploy to Dev, address any bugs so the QA Suite passes and there are no errors related to this library in the logs

## Acceptance Criteria

- [ ] All unit tests pass with the latest versions of dnspython
- [ ] The image successfully deploys
- [ ] Regression Suite passes

## QA Considerations
- [ ] double-check the regression and logs

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1660?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by k-macmillan** [comment]
Covered with Poetry.
