### ISSUE TITLE
Delete skip and xfail tests related to route removal

### ISSUE THREAD

**Issue by MackHalliday** [department-of-veterans-affairs/notification-api#1661]
## User Story - Business Need
Delete 'xfail' and 'skip' tests ONLY related to route removal.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**    VA notify engineer,
**I want**  delete 'skip and 'xfail' tests related to route removal
**So that** that when I work on the code, I will not have to update tests for code that will eventually be removed. 

### Additional Info and Resources

- Not every 'xfail' and 'skip' is related to route removal. See `reason` in 'skip' or 'xfail' tests.
- Ask team: What should we do with 'xfail' and 'skip' NOT related to route removal? Example `tests.app.v2.notifications.test_post_notifications` line 1376 `@pytest.mark.skip(reason='failing in pipeline for some reason')` Do we create a ticket for this?
- [Reference to spreadsheet for route removal](https://docs.google.com/spreadsheets/d/18AfqlEOWlrnigauO57jA0VP3RMHTaP4luknqBxrcbuY/edit#gid=115873237)
- [Update Skip and XfailTest Audit Spreadsheet](https://docs.google.com/spreadsheets/d/1qKlRb_nNfK1nsgvz-dJgbpspJUntVH5cxOs2J4luHAA/edit#gid=533952151)

some queries to search on, there may be others:
`pytest.mark.skip.*removal`
`pytest.mark.xfail.*(1631|not used).*run=false`

<img width="254" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVdIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--697fea0ca5d480296325117a52274a8343819cb9/image%20%2828%29.png" alt="image (28).png" />
<img width="322" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWVIQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee83b9a56a6ff733dc01b13ca2abe5bedb6c7de2/image%20%2829%29.png" alt="image (29).png" />

## Engineering Checklist
- [x] Skipped/xfail tests identified by the two regexes are reviewed to ensure they should be skipped
- [ ] Tests that should not have been skipped, have the skip/xfail decorator removed, and pass unit testing or are marked `xfail` with a new ticket number for us to fix them.
- [x] All 'skip' tests related to route removal are addressed
- [x] All 'xfail' tests related to route removal are addressed
- [x]  Document a list of 'skip' or 'xfail' tests that are not clear if related to route removal
  - [x]  Chat with team to determine best approach: e.g. group into 1 ticket, create multiple, etc.
  - [ ]  Create relevant new tickets

## Acceptance Criteria

- There are no 'skip' or 'xfail' marked tests related to route removal
- All incorrectly marked `skip`/`xfail` tests pass unit testing or are documented in a follow-up ticket

## Out of Scope

- Removing any 'skip' and 'xfail' tests are NOT related to route removal. 
- DO NOT refactor tests, only removal.

**Comment by mjones-oddball** [comment]
Comment from Dave: There are many skipped/xfailed tests.  It will be large as a number of lines deleted but not large in terms of time.  It is a straight-forward deletion.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1661?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @mchlwellman @MackHalliday

**Comment by kalbfled** [comment]
@k-macmillan @mjones-oddball Here are a few skip or xfail reasons that seem like good candidates for deletion even though "removal" is not explicitly declared:
- Failing after Flask upgrade.  Not fixed because not used.
- Letter functionality is not used.  Decline to fix.
- [Not in use](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/celery/test_reporting_tasks.py#L473)
- Letter feature

**Comment by kalbfled** [comment]
The queries in the description include tests associated with #1631, but that ticket's engineering checklist includes deleting those tests.  I think we should do it for that ticket rather than this one.

**Comment by kalbfled** [comment]
Status of tests:
- Parallel: `2848 passed, 26 skipped, 2 xfailed`
- Serial: `139 passed, 3 skipped, 2876 deselected, 13 xfailed`

**Comment by kalbfled** [comment]
@mjones-oddball @npmartin-oddball Kyle discovered that some of the tests annotated as being for "route will be removed" in fact are not for routes that will be removed, or the tests also test other code.  Ergo, Mack and I are going to have to take a second pass through our deletions and audit every deleted test against the route removal spreadsheet in addition to reading through the test to understand exactly what code is tested.

I suggest this ticket should be repointed at least as a 5; maybe 8.

**Comment by npmartin-oddball** [comment]
Could have been/should have been between 5 and 8, given complexity, team member involvement, etc.

**Comment by MackHalliday** [comment]
Pending Kyle and David reviewing https://docs.google.com/spreadsheets/d/1qKlRb_nNfK1nsgvz-dJgbpspJUntVH5cxOs2J4luHAA/edit#gid=533952151

Asked David to review any tests labeled as unsure (53, 7 files). Kyle double checking.

**Comment by MackHalliday** [comment]
Created ticket for test identified as mislabelled but failing 
https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1258
