### ISSUE TITLE
Upgrade ddtrace

### ISSUE THREAD

**Issue by mchlwellman** [department-of-veterans-affairs/notification-api#1662]
## User Story - Business Need

The Datadog dependencies were intentionally left untouched during the last dependencies update (#1647).  This ticket addresses the need to upgrade dd-trace and it's submodules.

As of this writing, ddtrace is pinned in the toml file to v1.18.2
<img width="509" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0I4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3266b2e9f7a8208628f87f8e96cb4f5ef4d5e0fe/Screenshot%202024-06-20%20at%207.47.09%E2%80%AFAM.jpg" alt="Screenshot 2024-06-20 at 7.47.09 AM.jpg" />

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   VA Notify developer
**I want** to upgrade Datadog dependencies
**So that**  we minimize vulnerabilities and future upgrade pains

### Additional Info and Resources

[dd-trace Release Notes](https://github.com/DataDog/dd-trace-py/releases)
Working branch is [ddtrace-update](https://github.com/department-of-veterans-affairs/notification-api/tree/ddtrace-update)
[Current PR](https://github.com/department-of-veterans-affairs/notification-api/pull/1695) for this that [failed on deploy](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/8332345280), but passed unit tests

[Breaking changes from v1 to v2](https://ddtrace.readthedocs.io/en/stable/upgrading.html).
On the branch, I followed our README documentation for updating dependencies with poetry.  Passed local unit tests. 

## Engineering Checklist
**Please alert the team if we're getting toward the end of the estimate and there's still unknowns/difficulties**
- [x] Upgrade the dd-trace package via poetry to the most recent if possible
  - If it doesn't seem possible to go to the latest, please discuss sticking with the latest 1.x version
- [x] Deploy to Dev, observe that the QA Suite passes and there are no errors related to this library in the logs
- [x] Review traces and ensure there are no issues
- [x] Compare error logs pre-upgrade to post-upgrade
- [x] All warnings are collected

## Acceptance Criteria
- [x] Regression tests pass
- [x] Existing APM Traces are still present after the upgrade
- [x] No new errors
- [x] Any new warnings are added into a ticket for future work

**Comment by ldraney** [comment]
The Datadog agent image in ECR should be updated as a part of this, as it hasn't been updated since 2022!
![image](https://github.com/department-of-veterans-affairs/notification-api/assets/107153866/9b4d2a19-a57a-477a-814f-3a80efd8d5de)

use notification-api/.github/workflows/update-datadog-image.yaml to do so, keeping an eye out for unexpected changes.  

This may have a positive impact on profiling and log digestion.

**Comment by ldraney** [comment]
Kyle asked me to make a new ticket, and as I was getting informed I ended up just updating it and it passed.
I added the documentation etc to [my PR](https://github.com/department-of-veterans-affairs/notification-api/pull/1695)

**Comment by ldraney** [comment]
It did not pass deployment.  First step will be to figure out why. 
<img width="1333" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXp0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e220d343856bc29f60a7052240b1ae654080177/image.png" alt="image.png" />

**Comment by ldraney** [comment]
Note from Kyle: updating from v1 to later version of v1 also had deployment problems, so this may be more complex for pointing

**Comment by k-macmillan** [comment]
Agent was updated on March 5th this year. The PR that was associated with this had only changed poetry to use `"*"` and was closed. Consider this a clean-slate ticket.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1662?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman
