### ISSUE TITLE
Lambdas - Regular Update for Dependencies

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1673]
## User Story - Business Need

We wish to keep our lambda dependencies up to date so we do not need such massive overhauls of our system. This will be a recurring ticket. We will update all dependencies we are able to. Any conflicts will get a new ticket. This is intended to be a day of work at most because this is intended to update with only non-breaking changes.

- [x] Ticket is understood and QA has been contacted

### User Story
**As** VA Notify  
**I want** to keep our lambdas up to date  
**So that** we are secure and as free of bugs as possible

### Additional Info and Resources
In the kafka repo there is a script that can be used to update the lambda layers, find it [here](https://github.com/department-of-veterans-affairs/notification-kafka/blob/main/scripts/create-update-lambda-layers.sh) 

## Engineering Checklist
**Please note, layers are in infra, so you may need PRs in multiple repos to address updates.**

- [x] Check Dependabot issues for lambda dependency updates - ensure they will be closed with updates
- [x] Use [this script](https://github.com/department-of-veterans-affairs/notification-kafka/blob/main/scripts/create-update-lambda-layers.sh) in the kafka repo to update lambda layers
	- [x] copy the updated lambda layers to the infra repo and override the existing layers in `cd/application-infrastructure/lambda_layers/` so they can be deployed
	- [x] Update the requirements files in the `lambda_layer_requirements` folder in the kafka repo with updated versions
- [x] Create infra and kafka repo PRs with updated lambda layers
- [x] Any major version changes are investigated (compare version change logs)
	- [ ] Any questionable version changes are removed and a ticket is created
- [x] Test in Dev environment (or staging if required for specific lambdas)

## Acceptance Criteria
- [ ] Lambda dependencies are updated and we have no broken functionality. 
- [x] Issues opened by Dependabot and related to lambdas are resolved. 
- [ ] Tickets created for any updates that interfere with current functionality.
- [ ] In AWS Lambda console, verify that lambdas with updated dependency layers are actually using the newest revisions of the layers.  (This might require a manual change.)
## QA Considerations
- [ ] Check to see if these updates cancel out any Twistlock issues
- [ ] QA Regression tests pass after deploying this code.
- [ ] Any lambdas not tested by the regression are tested with the developer working this ticket

**Comment by EvanParish** [comment]
This ticket being in the api repo is slightly misleading since the changes are actually happening in the kafka (layer requirements / generation) and infra (layer deployment) repos. It's mainly here because most of our lambda code still exists in this repo.

**Comment by cris-oddball** [comment]
Infra and Kafka PRs approved and merged. 

- [ ] Deployed Infra to Perf without issue. 
- [ ] Deployed the kafka lambdas to Perf without issue.
- [ ] Ran regression against Perf - [PASSED](https://github.com/department-of-veterans-affairs/notification-api-qa/actions/runs/8194862193)
- [ ] Tested Lambdas as follows:

| Lambda Name                                | Layers Used               | Tested      |
| ------------------------------------------ | ------------------------- | ----------- |
| bip_kafka_consumer_lambda                  | kafka-consumer            | |
| bip_msg_mpi_lookup_lambda                  | aiohttp                   | |
| bip_vaprofile_id_etl_lambda                | psycopg2-binary           | Not Updated |
| delivery_status_processor_lambda           | twilio                    |   |
| nightly_billing_stats_upload_lambda        | bigquery                  | wait overnight |
| nightly_stats_bigquery_upload_lambda       | bigquery                  | wait overnight  |
| notify_incoming_sms_managed (does nothing) |                           | N/A         |
| pinpoint_callback_lambda                   |                           | N/A         |
| pinpoint_inbound_sms_lambda                |                           | N/A         |
| ses_callback_lambda                        |                           | N/A         |
| two_way_sms_lambda                         |                           | N/A         |
| two_way_sms_v2*                            | psycopg2-binary, requests | - |
| va_profile_opt_in_out_lambda               | psycopg2-binary, pyjwt    | Not Updated |
| va_profile_remove_old_opt_outs_lambda      | psycopg2-binary           | Not Updated |
| vetext_incoming_forwarder_lambda           | twilio                    |  |
* *two_way_sms_v2* = *project-dev-notify-incoming-sms-lambda* 
	* Must be tested in staging using the number from an inbound number that has the `auth_parameter` populated. Like the ones for PeriOptimization, or VEText.

✅

**Comment by cris-oddball** [comment]
Will resume testing tomorrow (Friday)

**Comment by cris-oddball** [comment]
PASSED QA
closing ticket.
