### ISSUE TITLE
Refactor docker compose configuration

### ISSUE THREAD

**Issue by mchlwellman** [department-of-veterans-affairs/notification-api#1679]
## User Story - Business Need

The local development environment has several docker compose configurations that could be merged into one. 

- docker-compose.yml
- docker-compose-local.yml
- docker-compose-test.yml
- docker-compose-local-migrate.yml
- docker-compose-local-readwrite.yml

The docker-compose and docker-compose-local files do essentially the same thing, with the difference being that docker-compose has only the essential services for the api, where docker-compose-local has the celery tasks. We can accomplish the same thing with one docker compose file and Makefile targets.  The same is true with docker-compose-test, where the only difference is the environment variables (mainly the database URI).  The docker-compose-migrate and docker-compose-local-readwrite files can be replaced with Makefile targets. 

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a VA Notify developer**    
**I want a simple docker environment**  
**So that my development workflow is streamlined.** 

## Engineering Checklist

- [ ] Merge docker-compose and docker-compose-local and docker-compose-local-readwrite into one and use the name docker-compose.yml
- [ ] Merge the docker-compose-test environment variables with the pytest.ini file's environment variables
- [ ] Add a Makefile target for creating and applying migrations (make migratations and make upgrade)
- [ ] Add a Makefile target for running tests locally (make test-local)
- [ ] Add a Makefile target for bringing project up clean. (make fresh)
- [ ] Add a Makefile target for bringing project up w/existing data (make up)
- [ ] Add a Makefile target for bringing project up with read/write databases (make readwrite)
- [ ] Add a Makefile target to build project (make)
- [ ] Update documentation

## Acceptance Criteria

The Makefile targets work and there is one docker-compose files, docker-compose.yml.

**Comment by cris-oddball** [comment]
Talked with Michael, after Poetry this change is unneeded, closing as Will Not Do
