### ISSUE TITLE
SMS Sender Enhancements - Endpoints, Postman, and API Docs

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1687]
## User Story - Business Need
We'd like to add new fields to assign a sender to the applicable provider and a description field so we know what use case the sender is used for. See Acceptance Criteria for the two new fields and expected behavior.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).
- [ ] This work is added to the sprint review slide deck (key win bullet point and demo slide)

### User Story(ies)

**As a** VA notify team member
**I want** to add, update, and/or view the associated provider and use case details of my sms senders
**So that** I can support client requests and make updates over time

### Additional Info and Resources

Existing postman routes:
<img width="518" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC9MQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c25c120fa901a72572468c605c34974d187203e9/image.png" alt="image.png" />

Existing sms sender fields:
```
    {
        "archived": true/false,
        "created_at": "<datetime>",
        "id": "<UUID>",
        "inbound_number_id": <UUID>,
        "is_default": true/false,
        "rate_limit": #,
        "rate_limit_interval": #,
        "service_id": "<UUID>",
        "sms_sender": "<Phone Number>",
        "updated_at": "<datetime>",
// Used for Twilio senders
        "sms_sender_specifics": {
            "messaging_service_sid": "<Unique ID>"
        }
    }
```

## Engineering Checklist
**Though they are not required in the database, we want to require these new fields in postman so we don't continue to miss adding these important details moving forward.**

- [x] API Updates
- [x] Postman Updates
- [x] Update openapi.yaml doc for sms sender routes
- [ ] This work is added to the sprint review slide deck (key win bullet point and demo slide)

### Givens
- I'm using postman to get, create or update sms sender(s)
- I have a valid service_id and admin credentials specified in env variables
- New sms sender fields are `provider_id` (UUID) and `description` (string), both of which are required

### Create sms sender
> WHEN you execute CREATE sms sender `{{notification-api-url}}/service/{{service-id}}/sms-sender`
- [x] New fields are included in the sample request body
- [x] Validation is present to ensure new required fields are populated in the request body
- [x] Validation is present to ensure `provider_id` is a valid provider found on file

> WHEN the sms sender is successfully created
- [x] New fields are returned in addition to existing sender fields
- [x] The associated provider `display_name` is also returned

### Update sms sender
> WHEN you execute UPDATE sms sender `{{notification-api-url}}/service/{{service-id}}/sms-sender/{{sms-sender-id}}`
> AND specify the applicable `sms_sender_id` in env variables
- [x] New fields are included in the sample request body
- [x] Validation is present to ensure new required fields are populated in the request body
- [x] Validation is present to ensure `provider_id` is a valid provider found on file

> WHEN the sms sender is successfully updated
- [x] New fields are returned in addition to existing sender fields
- [x] The associated provider `display_name` is also returned

### Get sms senders

> WHEN you execute GET sms senders `{{notification-api-url}}/service/{{service-id}}/sms-sender`
> AND provider_id is specified on at least one sender

- [x] New fields are returned in addition to existing sender fields
- [x] On senders with a provider_id listed, the associated provider `display_name` is also returned

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

- [ ] manually validate create/read/update routes in Postman
- [ ] validate the swagger updates, including the unvalidated updates made for #1685
- [ ] automate as much as possible and/or create ticket for automation

## Out of Scope
_Leave blank if n/a_
- Retroactive provider/description updates
- Simplifed (client facing) postman collection should not be updated because sms sender is an admin function
- Portal isn't impacted because these are not client-facing routes

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1687?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment]
Still useful, especially for enp.

**Comment by EvanParish** [comment]
Yesterday I wrote some new tests for the create sms_sender endpoint, added the appropriate fields to the schema for validation, and updated the dao function to insert the new sms_sender in the db. 

Today I'm planning on doing the same for the update endpoint and fixing any other tests that are now failing. I'll also be working on updating the openAPI docs and postman collection.

**Comment by EvanParish** [comment]
I spoke with Cris yesterday about how this change will affect testing and we noticed that the existing SMS senders have a provider_id value of `"None"` which should never be possible. It's nullable in the database, so it should be `null` or a proper UUID. I'm going to update these values to `null` in the databases of the various environments as part of this work.

**Comment by EvanParish** [comment]
Finished up unit testing yesterday and I've tested the endpoints locally. I'm deploying and testing in dev this morning. 

When testing the endpoints locally I realized the issue Cris and I were looking at was just a serialization problem, not a database one.

**Comment by cris-oddball** [comment]
- PR Approved and Merged, deploying to Perf for validation. 
- There are two QA tickets to automate the create/update/delete routes QA-43 and QA-181
- Pydantic models were already updated for this code in QA-234
- Manual testing to follow

**Comment by cris-oddball** [comment]
**QA TESTING IN PROGRESS**

- [ ] TC01 - Happy Path -  Create with valid provider id and description, returns 201 and provider name in response
- [ ] TC02 - Negative - Attempt to create with no provider id or description, expect 400 and ValidationError
- [ ] TC03 - Negative - Attempt to create with invalid provider id and description, expect 400 and ValidationError
- [ ] TC04 - Happy Path - update with provider id and description, returns 200 and provider name in response
- [ ] TC05 - Negative -  update with invalid provider id and description, expect 400 ValidationError
- [ ] TC06 - Negative -  Attempt to update one of rate limit / interval is still validated properly, expect 400 with specific message
- [ ] TC07 - Negative -  Attempt to update default sender to not default. expect 400 with specific message
- [ ] TC08 - Happy Path GET returns provider name if provider id assigned
- [ ] TC09 - Happy Path GET returns provider name as null if no provider id assigned
- [ ] TC10 - Happy Path GET by ID returns provider name if provider id assigned
- [ ] TC11 - Happy Path GET by ID returns provider name as null if no provider id assigned

**Comment by cris-oddball** [comment]
Sending to Staging/Prod and closing ticket
