### ISSUE TITLE
VEText2 Oracle Health - Lambda - New Twilio Inbound Forwarding Path

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1688]
## User Story - Business Need
VEText1 Vista uses our Twilio Forwarder to receive inbound SMS.

VEText2 Oracle Health (VT2 OH) needs to use this setup to receive inbound SMS from Twilio numbers, but they have a different endpoint in AWS. We need to add a new forwarding rule to support this use case.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VT2 team member
**I want** to receive responses to my OH Twilio phone numbers
**So that** I can process messages and respond to Veterans

### Additional Info and Resources

- https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/SMS-Inbound.md#twilio-process--configuration
- See epic for configuration details https://github.com/department-of-veterans-affairs/vanotify-team/issues/1262
- We do not need to add an inbound number via the API for the twilio forwarder setup

[Deployment ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1238)

## Engineering Checklist

**Staging**
- [x] Coordinate with Lee DeBoom to update message service settings in Twilio for the Staging number
- [x] Update the forwarder lambda to detect the different paths and route them accordingly
- [x] Connection with the VT2 endpoint uses new SSM param

**Prod**
- [x] Update the applicable deployment ticket with instructions on how to manually regress the existing forwarding rule. That is live functionality that we need to ensure continues to work.
- [x] Let Lee know when to expect the deployment to Prod so follow-up testing can be done there

## Acceptance Criteria

- Regression: Confirm the original VEText1 forwarding rule by texting the VT1 number and checking logs to confirm the message sends to the applicable endpoint and returns a 2xx status code.
- New Behavior: Text the staging VT2 number and check logs to confirm the message is sending to the applicable endpoint and returns a 2xx status code.
  - VT2 should also check on their end and validate the message is received

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

- This is enabled in limited environments (Staging/Prod) so it should be sent to Staging and tested there in coordination with the VA Notify engineer and the VEText2 team
- See epic for data points needed for testing

## Out of Scope
_Leave blank if n/a_
- The VT2 endpoint will not use auth at this point. They still need to add basic auth to their endpoints.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1688?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by mchlwellman** [comment]
Yesterday:
- Fixed unit tests that were failing for the lambda (in master)
- Researched why the tests were failing in master locally and not in github
- Removed hardcoded path in the twilio validator and added path to the request bodies for processing later

TODO:
- Fix the current tests issue
- Add tests for the new vetext2 path

**Comment by mchlwellman** [comment]
Unit tests are fixed but need to add a few more. Friday I will start coordinating the deployment(s).

**Comment by cris-oddball** [comment]
DEV Testing negative test case to test bad twilio auth still works (it does). Truncated logs:
```
START RequestId: 5283d537-711f-4458-bc79-328e9275af3d Version: $LATEST
[DEBUG]	2024-03-22T15:10:03.792Z	5283d537-711f-4458-bc79-328e9275af3d	Entrypoint event: {'requestContext': {'<redacted>'}
[INFO]	2024-03-22T15:10:03.792Z	5283d537-711f-4458-bc79-328e9275af3d	alb invocation
[INFO]	2024-03-22T15:10:03.793Z	5283d537-711f-4458-bc79-328e9275af3d	validating twilio vetext forwarder event
[INFO]	2024-03-22T15:10:03.793Z	5283d537-711f-4458-bc79-328e9275af3d	Returning 403 on unauthenticated Twilio request
END RequestId: 5283d537-711f-4458-bc79-328e9275af3d
REPORT RequestId: 5283d537-711f-4458-bc79-328e9275af3d	Duration: 3.52 ms	Billed Duration: 4 ms	Memory Size: 128 MB	Max Memory Used: 73 MB	

```

**Comment by cris-oddball** [comment]
@mchlwellman you cannot close out tickets thathave a QA label on them and that have unchecked boxes in the description. Moving back to QA. Please handlethe unchecked boxes in the description and link to the deployment ticket showing the changes.

**Comment by cris-oddball** [comment]
[Deployment ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1238) updated with testing information (and Michael will be on that deploy).

Testing in staging sufficient to close this ticket.
