### ISSUE TITLE
Refactor Serial Tests pt1

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1690]
## User Story - Business Need
Some tests require serial execution due to the called functions operating on more than what the test has control over. These are usually valuable _integration tests with the database_; we do not want to remove them.

Other tests marked `serial` could be refactored to not be dependent on serial execution. Here are some of the reasons a test may have been marked serial:
- The reusable fixture uses hardcoded references
- Multiple rows being found when one was expected
- Test does not make good use of freezetime

Update all **non-dao** tests that must remain serial with a comment: `# requires serial execution - <method_name>`, where `<method_name>` is the method within the test that requires serial execution. These should only be due to the query, and where freezing time does not work. 

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify engineer
**I want** to limit serial tests
**So that** we can keep as many tests parallel as possible

### Additional Info and Resources

<img width="572" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5uQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f955df1bc9ea624503815653db9045524c11ecf/image.png" alt="image.png" />

## Engineering Checklist
- [ ] Update the serial tests in all folders other than `tests/app/dao/`
- [ ] Any that cannot be updated should be labelled `# requires serial execution - <method_name>` with the method that cannot be ran in parallel

## Acceptance Criteria

- [ ] All serial tests that remain, other than those in `tests/app/dao`, have been labelled `# requires serial execution - <method_name>` or have `@pytset.mark.serial` removed

**Comment by npmartin-oddball** [comment]
We won't be getting to this.
