### ISSUE TITLE
Update Dependency Template

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1692]
## User Story - Business Need
Update dependency template based on Poetry.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify engineer
**I want** to a clear dependency ticket
**So that** dependency updates are clear

## Engineering Checklist

- [x] Template has been updated for updating the API with Poetry

## Acceptance Criteria

- [x] Template makes no reference to requirements files and has a clear procedure for updating dependencies

**Comment by cris-oddball** [comment]
Bringing into sprint, since @k-macmillan is working it. Please add a point value!

**Comment by k-macmillan** [comment]
Updated README.md files and the dependency template. Should have it up for PR in the morning.

**Comment by k-macmillan** [comment]
Merged. Task is complete.
