### ISSUE TITLE
Identify and update VANotify to enable the first use case

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/notification-api#17]
Includes researching and addressing any changes to convert Canada-specific features to VA-specific:
- [x] Examine database migrations in CA notify to see what we need to modify or replace
- [x] organization types
  - migration to remove all types except 'Other' from organisation_types table
  - remove constants/logic relating to `NHS_ORGANISATION_TYPES` etc from `models.py` and `dao_create_service()`
- [x] sending limits
  - set `API_RATE_LIMIT_ENABLED = False` - disabled globally
  - add new flag `API_MESSAGE_LIMIT_ENABLED = False` - disabled globally
- [x] rates per sms / email
  - there is a free SMS limit associated with each organization type. We can look into the pricing logic there for the first SMS use case
- [x] any branding
  - app config file, value for 'NOTIFY_EMAIL_DOMAIN' in different environments
  - app config file, value for `ASSET_UPLOAD_BUCKET_NAME`
  - not updating `CSV_UPLOAD_BUCKET_NAME` since we don't have one yet
  - not updating `PERFORMANCE_PLATFORM_URL` since that's also unknown, but `PERFORMANCE_PLATFORM_ENABLED` is set to `False`
- [x] `app.delivery.send_to_providers.py #get_html_email_options`
  - modify values so that its returns a map of options for correct branding (`govuk_banner: false`, `brand_banner: true`, brand_colour) and points to correct logo
  - rename `govuk_banner` to `default_banner` in both `notification-api` and `notification-utils`
- [x] rename simulated email addresses to have VA domains
- [x] update tests as appropriate

Assumptions - 
The list above does not include all the tasks required

Notes: 
As a part of Dev Analysis - outline what changes need to be implemented
The HTML email template branding will be done in another story (#92)

**Comment by ffafara-tw** [comment]
Some items to check:
- [ ]organisation types
- [ ] sending limits

**Comment by anushyaprasad** [comment]
Is there an estimate for this card?

**Comment by saman-moshafi-va** [comment]
We modified the default value of API_RATE_LIMIT_ENABLED to be false and introduced a new flag, API_MESSAGE_LIMIT_ENABLED with default value as false. When both of these flags are false the Notification API will accept unlimited number of notification requests.
