### ISSUE TITLE
BUG: Twilio Error results in retries when it should not on TwilioRestException

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1703]
## Description

On staging, notification delivery is delayed because of high retries consuming celery resources on a non-retryable error.  This impacts the regression suite, causing to fail since it takes longer for sms to report a delivered state.

The error message:
```
twilio.base.exceptions.TwilioRestException: HTTP 400 error: Unable to create record: The 'From' phone number provided (+12026188901) is not a valid message-capable Twilio phone number for this destination
```

notification id of note that has been retried for at least 24 hours on staging: `4c2d7732-6b27-434e-a489-caf2e06c8894`

It also might be good to know what service is using that Twilio number and ask them to stop using it.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Observe logs for the notification ID above, note the traceback split across multiple lines and the Twilio error message shown above.

## Impact/Urgency

Affects regression and notification delivery status reporting.

## Expected Behavior

- [x] The notification above stops being retried in staging (along with any others that are a problem
- [x] Notifications for `TwilioRestException: HTTP 400 error` are not retried
- [x] The regression passes
- [x] We know what service is trying to use that Twilio number

**Comment by EvanParish** [comment]
After doing some testing it looks like this error is isolated to the Twilio client. We were getting an error back from them that we did not expect. Therefore we retried the messages since that is the default behavior of our API. 

When attempting to send a message using Pinpoint as the provider and a number that doesn't exist, it doesn't retry and shows the error below in the logs.

```
[2024-03-27 20:00:21,570] deliver_sms: Notification: c4f66018-d7b6-4009-bc71-c9fb6e9d70f7 encountered a permanent exception: StatusCode: 400, StatusMessage:The provided number does not exist or does not belong to the account
```

**Comment by EvanParish** [comment]
For the failed sms message mentioned above the callback keeps failing with a 500 error and is retrying.
```
Callback sent to https://staging.api.vetext.va.gov/api/vetext/vanotify/status, response 500, notification_id: c4f66018-d7b6-4009-bc71-c9fb6e9d70f7
```

```
Retrying: send-delivery-status failed for {'notification_id': 'c4f66018-d7b6-4009-bc71-c9fb6e9d70f7'}, url https://staging.api.vetext.va.gov/api/vetext/vanotify/status.
```

**Comment by EvanParish** [comment]
When attempting to send an sms with a number that does exist for a service, an `InvalidProviderException` is raised. The notification status and reason is below.

```
"status": "technical-failure",
"status_reason": "SMS provider configuration invalid"
```

**Comment by cris-oddball** [comment]
PR approved and merged to master, sent up to Perf for testing.

**Comment by cris-oddball** [comment]
**QA PASSED**

- **Regression passed**
- **TC01 PASSED Using Twilio as a Provider but sending with Pinpoint number**

In QA Automation service, use "name": "Twilio Test SMS Template", "id": "438a2240-ea2e-42d0-b0b8-4d63fc172a55", that has the provider configured to use Twilio, send the sms with sms-sender-id as a pinpoint number "id": "fccd9e82-f08f-4764-a49b-be367645d47a", should result in a technical-failure and no retries

`"id": "e2875dd1-ca5e-425b-9e5a-bd8f42b1b927",`

```
    "status": "technical-failure",
    "status_reason": "SMS provider configuration invalid",
```

logs
```
[2024-03-28 16:47:53,947: ERROR/ForkPoolWorker-4] Twilio send SMS request for e2875dd1-ca5e-425b-9e5a-bd8f42b1b927 failed, TwilioRestException - Unable to create record: The 'From' phone number provided (<redacted>) is not a valid message-capable Twilio phone number for this destination
[2024-03-28 16:47:53,952: CRITICAL/ForkPoolWorker-4] deliver_sms: Notification: e2875dd1-ca5e-425b-9e5a-bd8f42b1b927 - Experienced an exception: 
[2024-03-28 16:47:53,966: CRITICAL/ForkPoolWorker-4] Notification e2875dd1-ca5e-425b-9e5a-bd8f42b1b927 encountered a technical exception and has been updated to a technical-failure
```


-**TC02 PASSED Using a template with no provider_id where the default provider_id for the service is Pinpoint but template is sent with a Twilio number**
"name": "Simple Text", "id": "d46ee87b-8a71-4c5c-8654-ed766a9599ff", send the sms send the sms with sms-sender-id as a Twilio number "id": "6db4c815-fe8b-4c34-bea8-536a0976993d", should result in a technical-failure and no retries

`"id": "6397400a-9604-441f-9d69-0e37ae6bbb67",`

```
    "status": "technical-failure",
    "status_reason": "SMS provider configuration invalid",
 ```

logs
```
[2024-03-28 16:53:05,800: CRITICAL/ForkPoolWorker-4] deliver_sms: Notification: 6397400a-9604-441f-9d69-0e37ae6bbb67 - Experienced an exception: StatusCode: 400, StatusMessage:The provided number does not exist or does not belong to the account
[2024-03-28 16:53:05,812: CRITICAL/ForkPoolWorker-4] Notification 6397400a-9604-441f-9d69-0e37ae6bbb67 encountered a technical exception and has been updated to a technical-failure
```

This can be automated creating a QA ticket to automate it before closing ticket.

**Comment by cris-oddball** [comment]
[Automation ticket ](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api-qa/181)to add these tests to suite. Closing ticket.
