### ISSUE TITLE
Log Happy Path (Delivered - Created Time) for SMS/Email

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1710]
## User Story - Business Need
We should log the id, status, and (created - current time), to identify how long any particular notification took to actually make it all the way through our system. We currently do this by running database queries when we want to know the information.

This is technically _not_ all the way through our system because it ignores a few milliseconds of validations, but it is close enough.

This can be an incremental implementation, so we will focus on identifying "delivered" status first.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Tech Lead
**I want** to track deviations in how long it takes to send notifications
**So that** we can write SLIs and identify problems/improvements

### Additional Info and Resources

This should be handled in the processing of delivery statuses (pinpoint, ses, twilio). 

## Engineering Checklist

- [x] Get the diff between `created_at` and `monotonic()` and ensure that is logged when updating an email/sms to "delivered"
- [x] Code is repeatable for other states

## Acceptance Criteria

- [x] When I send a notification there is a log in Datadog/Cloudwatch showing how long it took for that ID to end in a "delivered" state

## QA Considerations
- [x] Inform QA of what logs indicates that this works - QA does not need to validate but will find the information to be useful.

## Out of Scope
Failure paths (permanent/temporary failure).

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1710?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by cris-oddball** [comment]
PR Approved and merged, sent to CI/CD pipeline then will do a log check.

**Comment by k-macmillan** [comment]
Monotonic was not the right fit. It gives the wrong format for what we have in the DB for created_at. Ended up going with a datetime object to get what we desired. Logs are coming through with all relevant info.

**Comment by cris-oddball** [comment]
Logs are a delightful thing of joy in Perf. Closing ticket.
