### ISSUE TITLE
Remove unnecessary secrets from task definitions

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1711]
## User Story - Business Goal

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,
**I want** Fargate task definitions not to include unnecessary secrets
**So that** the application deploys as quickly as possible and has a smaller attack surface.

### Additional Info and Resources

During the implementation of #1689, we identified that the task definitions contain unnecessary environment /secret variables.  For example, the variable [COMP_AND_PEN_MESSAGES_ENABLED](https://github.com/department-of-veterans-affairs/notification-api/blob/master/cd/application-deployment/dev/vaec-celery-task-definition.json#L220C20-L220C49), which is a feature flag used in the Celery task [send_scheduled_comp_and_pen_sms](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/scheduled_tasks.py#L259), only needs to be in the the Celery task definition, but it is also in the Celery Beat and API task definitions in each environment.  Ditto for the other comp&pen related variables in the task definitions.

This task is to identify and delete all task-defined secrets variables that safely can be removed.

_Ignore Celery-Beats containers for now - too complicated to trace code._ 

This ticket has been updated to ONLY focus on secrets. Another ticket will be created to move all environment variables to a share file. 

## Acceptance Criteria & Checklist

- [x] All unit and regression tasks pass in Dev and Perf

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1711?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1711?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by MackHalliday** [comment]
Starting spreadsheet 
https://docs.google.com/spreadsheets/d/1WYtI4Ky_p0ajRszOakhwV94EYzdDYS2XgQNEhX0fLIE/edit?gid=0#gid=0

**Comment by MackHalliday** [comment]
Yesterday 
- Create script to get task definition values 
- Created CSV file 

Today 
- Start going thru CSV file and reviewing each task definition

**Comment by MackHalliday** [comment]
Yesterday 
- Worked with @kalbfled and @k-macmillan to review a user story and different cases for task definition removal 
- Worked thru spreadsheet, currently at 481 of 978. Have not removed any task definitions, just marking tasks for removal or feature flag or no change.

Today 
- Hopefully finish spreadsheet today 
- Need to ask Kyle to review some of the task definitions  - marked in spreadsheet
- Start on removing task definitions today

**Comment by MackHalliday** [comment]
Friday 
- Picked up GFE and spent most of the day setting up computer 
- Started to remove task definitions that are obviously not need

Today 
- Remove more complex task definitions and deploy to dev

**Comment by MackHalliday** [comment]
Monday 
- Still working on removal and figure out what code paths are tested 
- Review QA repo and code coverage for testing 

Tuesday 
- Continue to remove task definitions and review testing

**Comment by MackHalliday** [comment]
cross reference route removal sheet and QA regression tests

**Comment by MackHalliday** [comment]
Yesterday 
- Completed removal and test deploys in DEV
- Created ticket for feature flag removal 
- Cleanup PR and spreadsheet 

Today 
- Need to test the follow tasks 
  - send_va_onsite_notification_task
  - lookup_va_profile_id
  - send_scheduled_comp_and_pen_sms

**Comment by MackHalliday** [comment]
PL 
https://oddball.slack.com/archives/C036AE08HA7/p1723732198142079

**Comment by MackHalliday** [comment]
Yesterday 
- Tested with @mchlwellman 
- Reviewed spreadsheet 
- Was unable to submit PR

Today 
- This morning, tested with @EvanParish 
- Submitted the PR

**Comment by MackHalliday** [comment]
Originally this PR focused on removing BOTH unused secret and environment keys from the task definitions folder. After discussing how to better maintain environment keys in our Pain Points meeting last Friday, it was decided that ONLY unused secret keys will be removed in this user story. And, environment keys will be maintained in a shared environment file. 

Therefore this user story was updated to only remove unused secret keys.
