### ISSUE TITLE
Internal blueprint and generic endpoint

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1713]
## User Story - Business Need
We currently use pipedream.com as a temporary server for modifying requests. This ticket will use our own service as a server to receive test http requests.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,
**I want** the API to include internal endpoints
**So that** we can integrate with Vetext, etc.

### Additional Info and Resources

This ticket is being created along with [infra 775](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/775) to point Dev to these new internal endpoints for vetext forwarding.

## Acceptance Criteria

- [x] New paths use a new [`/internal`](https://flask.palletsprojects.com/en/3.0.x/tutorial/views/) blueprint and route
- [x] `GET` and `POST` requests to `/internal/*` do not require any auth/validation
- [x] Each route logs the Flask [request](https://flask.palletsprojects.com/en/3.0.x/api/#flask.request) object and returns a status code of 200

## QA Considerations
- [ ] work with QA for testing and validation

- These routes do not need OpenAPI or Postman collection entries.

**Comment by cris-oddball** [comment]
@kalbfled this needs to work for both Dev and Perf. Does this ticket need to be updated to account for both environments?

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1713?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
@mchlwellman See the PR for #1853 for an example of how this could work.

**Comment by k-macmillan** [comment]
REVISION:
The route should accept `GET` and `POST` requests. This is a one word change to include in the list of methods accepted by the flask route.

Logging the entire request object ended up not being what we want. After discussion with @mchlwellman we decided on the following important request attributes:

```
    method
    root_path
    path
    query_string
    headers
    url_rule
    _cached_data
    _trace_id
```

Some will be pulled directly from the request object, some make sense to use the request class properties, such as `content` instead of `_cached_data`.

**Comment by cris-oddball** [comment]
PR approved and merged. Will deploy and test after standup.

**Comment by cris-oddball** [comment]
Deploying to Perf

**Comment by cris-oddball** [comment]
**QA PASSED**

- [ ] POST  `https://sandbox-api.va.gov/internal/foobar` with `{"foo": "bar"}` returns a 200 and the request body
- 200 received
```
{
    "foobarbaz": {
        "foo": "bar"
    }
}
```
- [ ] POST  `https://sandbox-api.va.gov/internal/foobar` with `{"foo": "bar", "foobar": "baz"}` returns a 200 and the request body
- 200 received
```
{
    "foobarbaz": {
        "foo": "bar",
        "foobar": "baz"
    }
}
```
- [ ] GET `https://sandbox-api.va.gov/internal/foobarbaz` returns 200 and the request
- 200 received
```
GET request received for endpoint /internal/foobarbaz?
```
- [ ] GET `https://sandbox-api.va.gov/internal/foobarbaz?name=alice&location=colorado&planet=earth` returns 200 and the query parameters
- 200 received
```
GET request received for endpoint /internal/foobarbaz?name=alice&location=colorado&planet=earth
```
- [ ] There is logging for both routes

<img width="1252" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07bef42092ef80d3a11793e9be03080a41af1935/Screenshot%202024-07-25%20at%209.33.35%E2%80%AFAM.jpg" alt="Screenshot 2024-07-25 at 9.33.35 AM.jpg" />

**Comment by cris-oddball** [comment]
will deploy to prod with the utils api PR, closing ticket
