### ISSUE TITLE
Comp and Pen - Revise VA Profile opt in/out Lambda Logging

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1745]
## User Story - Business Need
Logging in our VA Profile opt in/out lambda does not inform us of changes that are happening. This is useful information so we can understand how many more notifications we will be sending as well as helping our partner identify the effectiveness of directing people to this new preference.

This lambda is also hardcoded for `debug` logging and should be revised to take in an environmental variable (small bit of infra work)

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify engineer
**I want** to log preference opt in/out
**So that** we are better informed regarding trends/usage

### Additional Info and Resources

Around like 304 is the first time we look for "allowed" in the bio. That value is what we want to log.

## Engineering Checklist

- [x] Add `info` logging of the `allowed` preference
- [x] Update to allow for env variable to set the logging level
- [x] log level needs to be set with an infra PR

## Acceptance Criteria

- [x] Log level is set by environmental variable
  - [x] No longer hardcoded for `DEBUG`
- [x] Allowed status is logged and qualified with some description e.g. `Preference changed to %s`

## Potential Dependencies
Small Infra PR to add the log level to the environmental variables

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1745?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
During review of the PR for this ticket, @k-macmillan and I discussed an issue with logging that we need to keep in mind when we begin using containers to package lambda functions.  As currently written using `logger.setLevel`, the logging messages we expect end up in CloudWatch.  However, the same code doesn't seem to work locally.  For example, this code, copied and abridged from my PR for this ticket . . .

```python
import logging

logger = logging.getLogger('VAProfileOptInOut')
logger.setLevel(getattr(logging, 'DEBUG'))

bio = {'allowed': 'True'}

logger.info(
    'The request is an opt-%s.',
    'in' if (str(bio['allowed']).lower() == 'true') else 'out',
)
```
. . . does not output anything when run locally.  However, changing `logger.setLevel(getattr(logging, 'DEBUG'))` to `logging.basicConfig(level=getattr(logging, 'DEBUG'))` works as expected.

**Comment by kalbfled** [comment]
@k-macmillan I asked ChatGPT why the above code doesn't log anything, and this was its reply (which I have not tested):

It seems your logging configuration is incomplete. You've set the logger level to DEBUG, but you haven't configured a handler to output the log messages anywhere. In Python's logging module, loggers are attached to handlers which define where log messages should be output. Without a handler, log messages won't go anywhere.

You need to add a handler to your logger, for example:

```python
import logging

# Create a logger
logger = logging.getLogger('VAProfileOptInOut')
logger.setLevel(logging.DEBUG)

# Create a handler
handler = logging.StreamHandler()
handler.setLevel(logging.DEBUG)

# Create a formatter and set it on the handler
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
handler.setFormatter(formatter)

# Add the handler to the logger
logger.addHandler(handler)

bio = {'allowed': 'True'}

logger.info(
    'The request is an opt-%s.',
    'in' if (str(bio['allowed']).lower() == 'true') else 'out',
)
```

This will configure your logger to output log messages to the console (or standard output). Adjust the handler settings (such as output file or logging level) according to your needs.
