### ISSUE TITLE
Comp and Pen - Add Task Def Variable For Perf Testing

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1752]
## User Story - Business Need

We want to test the Comp and Pen scheduled sends in Perf so we can exercise our full process end-to-end. To do this we need a number that can receive messages added as an environment variable in our celery task definition in the Perf environment. The code will need to have checks in place to perform sends specifically in the Perf environment.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Engineer 
**I want** to be able to send messages 
**So that** I can test the full process end-to-end.  

### Additional Info and Resources

It would be beneficial to make use of python's `or` precedence for this task.

## Engineering Checklist

- [x] Add a variable in the Perf celery task definitions [here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/cd/application-deployment/perf/vaec-celery-task-definition.json#L185) for the number to use in Perf
- [x] When collecting the variable for use in the app it defaults to `None` if not present
- [x] Add checks necessary to send scheduled notifications to this number only in the Perf environment
	- This will happen in the `send-scheduled-comp-and-pen-sms` celery task

## Acceptance Criteria

- [x] Variable is not set outside of the Perf celery task definition
- [x] A new environment variable exists in the Perf environment that lets us know which number to send to for testing the scheduled notification sends.
- [x] When we attempt to send a message in the Perf environment from the dynamo cache table the message is sent to a fake deliverable number instead of looking up the identifier provided in MPI/VA Profile

## QA Considerations

- [ ] Check logging with dev to ensure we know when notifications are being sent in Perf

## Out of Scope
_Leave blank if n/a_
This feature flag will circumvent lookups by establishing a simulated number to send to. If we later decide that we need to also test lookups as part of this E2E pipeline we can add another feature flag to provide another testing path.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1752?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by EvanParish** [comment]
Yesterday I added the variable to Perf and the code necessary to check for it. 
Today I'll work on fixing up unit tests and start testing the changes.

**Comment by EvanParish** [comment]
I'm most of the way there. I just want to add a unit test for this change and there's a small refactor I need to do to reduce complexity.

**Comment by EvanParish** [comment]
I broke up the necessary code and added a couple unit tests. Now, I just need to perform testing in dev and perf environments to ensure this works as expected.

**Comment by cris-oddball** [comment]
PR approved and merged. Once deployed to Perf, will test it out.

**Comment by cris-oddball** [comment]
QA TESTING IN PROGRESS

- Infra and Kafka master/main sent to Perf to clear old branches
- API master deployed to Perf: feature flag for Perf is now enabled
- DynamoDB table cleared
- ETL Lambda run to populate the DynamoDB table
- Ran Producer
- Configured Consumer to get local events

Just realized that this cannot be fully tested because the cron job is off, so no notifications will be sent to check the logs for the correct logs.

Also, the lambda trigger errored with this message:
> Last processing result: PROBLEM: Lambda function exited with an error. Error: Unhandled. Please check your function logs.

Possibly related to the EC2 needing to be re-deployed? Giving Evan a chance to take a look.

**Comment by cris-oddball** [comment]
Going to handle trigger inconsistencies separately. Closing ticket since cron is off and staging/prod are behind feature flag.
