### ISSUE TITLE
Perf & Staging: Configure the send email notification delivery status to VA Profile

### ISSUE THREAD

**Issue by MackHalliday** [department-of-veterans-affairs/notification-api#1779]
## User Story - Business Need
We want to improve the management and reliability of email data within the VA system in collaboration with VA Profile by
- Tracking delivered and bounced emails, specifically identifying hard bounces (permanent failures) and soft bounces (temporary issues).
- VA Notify will support VA Profile by providing real-time data on email deliverability.
- Utilizing existing infrastructure and celery tasks to minimize new development efforts.
</br>

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Developer, 
**I want**  properly configure and test new feature to send email notification delivery status to VA Profile in the Staging environment.
**So that** we can ensure the new feature functions as expected in the Staging environment.

### Additional Info and Resources
- See ticket #1770
- See [Implementation Plan](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/email-bounce-tracking.md)
- Feature Flag for this work: `VA_PROFILE_EMAIL_STATUS_ENABLED`

## Engineering Checklist

- [x] Confirm bearer token ssm parameter is populated for both perf/staging
- [x] Enable feature flag in Perf & Staging environments
- [x] Coordinate with VA Profile to conduct integration tests.
    - [x] Verify that POST requests send accurate and complete email delivery status data.
    - [ ] Ensure error handling processes are properly logging and managing errors.
    - [x] Obtain QA approval after successful testing of all scenarios in the Perf & Staging environment.

## Acceptance Criteria

- The new features can send delivery status data on **ALL** email notifications 
- Any errors, whether expected or unexpected, are logged and handled gracefully
- Feature flag (`VA_PROFILE_EMAIL_STATUS_ENABLED`) work is coordinated with IIR team to avoid collisions

## QA Considerations
- [x] Shadow the VAProfile testing

**Comment by cris-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1779?planning-poker) with Zenhub @EvanParish @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by mjones-oddball** [comment]
Tagged as blocked because we are awaiting VA Profile to provide the QA endpoint (est date - 8/13).

**Comment by mjones-oddball** [comment]
@EvanParish looks like Kyle spent ~30 minutes validating and that included reverting. Should we repoint the prod ticket - #1780? It's currently at a 2. CC @npmartin-oddball @kbelikova-oddball

**Comment by cris-oddball** [comment]
PR approved and merged, sending via pipeline. Previously validated in Perf.

**Comment by EvanParish** [comment]
@mjones-oddball Since it's working in all other environments all we need is the token from them to put in AWS SSM and the green light to push this to Prod. I think 1 point should be sufficient for that. I'd recommend re-pointing to a 1.

**Comment by EvanParish** [comment]
It looks like everything is working as expected. The only errors we would expect to see would come from making the request to VA Profile and those are caught and logged. I'm not sure how we would force those to happen, so I haven't checked the box for: `Ensure error handling processes are properly logging and managing errors.`

We use the requests library frequently though, so there's not much uncertanty in the type of errors we would see there.

**Comment by EvanParish** [comment]
Closing since perf / staging look good and this has been deployed to Prod.
