### ISSUE TITLE
Prod: Configure the send email notification delivery status to VA Profile

### ISSUE THREAD

**Issue by MackHalliday** [department-of-veterans-affairs/notification-api#1780]
## User Story - Business Need
We want to improve the management and reliability of email data within the VA system in collaboration with VA Profile by
- Tracking delivered and bounced emails, specifically identifying hard bounces (permanent failures) and soft bounces (temporary issues).
- VA Notify will support VA Profile by providing real-time data on email deliverability.
- Utilizing existing infrastructure and celery tasks to minimize new development efforts.
</br>

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Developer, 
**I want**  properly configure and test new feature to send email notification delivery status to VA Profile in the Production environment.
**So that** we can ensure the new feature functions as expected in the Production environment.

### Additional Info and Resources
- See ticket #1770
- See [Implementation Plan](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/email-bounce-tracking.md)
- Note that everything should be configured for Prod and that we want to manually enable the feature flag, test with VAProfile and then open a PR with code to enable the flag.

## Engineering Checklist

- [x] Confirm bearer token ssm parameter is populated for prod
- [x] Enable feature flag in Production environment
- [x] Coordinate with VA Profile to conduct integration tests
    - [x] Verify that POST requests send accurate and complete email delivery status data.
    - [x] Ensure error handling processes are properly logging and managing errors.
    - [ ] ~Obtain QA approval after successful testing of all scenarios in the Production environment.~ QA not necessary on this ticket.
- [x] Update the Slide deck with the key win and a demo slide

## Acceptance Criteria

- The new features can send delivery status data on **ALL** email notifications 
- Any errors, whether expected or unexpected, are logged and handled gracefully

## QA Considerations
- [ ] Shadow the VAProfile testing

**Comment by cris-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1780?planning-poker) with Zenhub @EvanParish @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by mjones-oddball** [comment]
Marked as blocked because we can't do this ticket until VA Profile creates and provides their prod endpoint. There's also a dependency on finishing the integration in QA (Staging/Perf) first.

**Comment by k-macmillan** [comment]
Okay to keep.

**Comment by kbelikova-oddball** [comment]
VA Profile's Prod launch date is Sept 10

**Comment by mjones-oddball** [comment]
This is no longer blocked. @EvanParish has the info for the prod endpoint.

**Comment by EvanParish** [comment]
Yes. The endpoint is the same and the token has been placed in ssm.

**Comment by EvanParish** [comment]
I think this was accidentally closed on the merge. I will verify with VA Profile that this is working before closing the ticket. The feature flag has been enabled and the code is on it's way through the environments.

**Comment by EvanParish** [comment]
It looks like we are getting a 200 response back from VA Profile, so that's a good sign!
Just waiting on confirmation from Ian on the VA Profile team to confirm everything is looking good to them.

<img width="1629" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFFHQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee66d37db3dfd8a366a13f1bb073e3a15182f73a/image.png" alt="image.png" />

**Comment by EvanParish** [comment]
It looks like everything is good on the VA Profile side as well. Done!
