### ISSUE TITLE
Remove flask-cors Dependency

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1794]
## User Story - Business Need
Flask-Cors was necessary for the [old UI](https://github.com/department-of-veterans-affairs/notification-ui), but is no longer necessary with the SSUI. Remove it and all associated code.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Engineer
**I want** to keep our system lean and free of unused dependencies
**So that** we have less to maintain and fewer vulnerabilities

### Additional Info and Resources

- [Flask-Cors](https://pypi.org/project/Flask-Cors/) pypi page
- It is imported like so: `flask_cors`

## Acceptance Criteria

- [x] Code that used `flask_cors` is removed
- [x] `flask_cors` is not used in our code
- [x] Dependency is removed from Poetry

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1794?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by EvanParish** [comment]
The code is complete and unit tests pass locally. I'll deploy and test on Dev in the morning.
