### ISSUE TITLE
[Spike] Look at vets-api for potential integration point for 526ez confirmation email

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/notification-api#18]
- Research vets-api to find a potential integration point to send notification on successful 526ez form submission
- Research how feature toggles are used in vets-api
- Come up with integration approach
- Validate the approach with vets-api team

**Comment by anushyaprasad** [comment]
FIlip to document findings and add relevant stories

**Comment by ffafara-tw** [comment]
I've talked with developers responsible for disability compensation form 526ez Sarah-Jaine Szekeresh and Anna Carey who were recommended by Andrea.
They suggested to use email address that is part of the from. The email is prepopulated from VA Profile but can be overridden by the user for this particular submission.

Form submission is performed asynchronously in Form526Submission class.
Once submission is successful the class runs a number of ancillary jobs. We can add our notification job to the list if ancillary jobs.

There is another path for submitting 526ez that is used by VSOs (ClaimsApi::V1::Forms::DisabilityCompensationController). Sending confirmation email for that submission is outside of the current scope.
