### ISSUE TITLE
[BUG] When deploying the same notification-api tag, pipeline should not create new version tag

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#180]
# Describe the Bug
Currently our pipeline for notification-api runs tagging workflow after successful deployment.
Tagging workflow will add a new version tag and commit it to git. We thus end up with the same commit having 2 separate version tags. Moreover it will break the tagging for the next build.

# To Reproduce
1. Deploy notification-api version to 'tw-dev' environment that already has been tagged 
2. This version will now have 2 version tags.
3. Push a commit to trigger a new build.
4. See error when pipeline tries to push a tag that already exists.

# Expected Behavior
When deploying a commit that already has a staging version tag (to dev environment) tagging workflow should not be adding new tags.
When deploying a commit that already has a production version tag (to staging environment) tagging workflow should not be adding new tags.

# Actual Behavior 
When deploying a commit that already has a staging version tag (to dev environment) tagging workflow creates a new staging version tag and commits it to git.
When deploying a commit that already has a production version tag (to staging environment) tagging workflow tries to tag docker image again and fails.

**Comment by ffafara-tw** [comment]
A potential fix could be to check if the latest tag is pointing to the commit we are trying to tag.

**Comment by k-macmillan** [comment]
PIpeline has been overhauled, this is no longer applicable.
