### ISSUE TITLE
BUG: CodeQL configuration missing

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1807]
## Description

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

Ticket #1765 removed the workflow for the legacy CodeQL scanner, but it still tries to run every time somebody creates a PR.

![image](https://github.com/department-of-veterans-affairs/notification-api/assets/5375929/34887d44-6144-4225-bf1d-8de7b67792d6)

It doesn't seem to be the case that references to the removed workflow remain in the code base.  This could be an issue in the repository's settings.

## Steps to Reproduce

1. Create a PR.

No workaround is necessary.

## Impact/Urgency

Low impact/not urgent

## Expected Behavior

- [ ] There is no trace of the legacy scan when creating a PR or elsewhere.

**Comment by k-macmillan** [comment]
This is no longer an issue.
Closed PR:
<img width="862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekg3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1e9628e01e8022d686cc245d1fd2ea3a400e405/image.png" alt="image.png" />

Currently open PR:
<img width="845" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekw3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e328ad860d22c9ff057870610827f57a84df4f3/image.png" alt="image.png" />
