### ISSUE TITLE
Create automated pipeline for releasing notification-utils and bumping notification-utils dependency in notification-api

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#181]
# Value Statement:
**As** VANotify developer
**I want to** notification-utils to be released automatically in the pipeline
**And** a pull request to be automatically created in notification-api using new release
**So that** I save time and not have to do these tasks manually

# Acceptance Criteria
**GIVEN** a change notification-utils
**WHEN** notification-utils CI pipeline runs
**THEN** it automatically creates a new release

**GIVEN** a new notification-utils release
**THEN** a PR is automatically opened to notification-api bumping the version (like dependabot)
**AND** tests are run on the PR

# Checklist:
- [ ] To be created during dev analysis

# Open Questions:
- Do we want to create new release on every commit? Or only when we modify version file? Or do we switch to pull request model and always create new releases on master branch (we can prevent direct pushes to master branch)?

**Comment by k-macmillan** [comment]
N/A.
