### ISSUE TITLE
CD Pipeline - infra deploy for perf and staging

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1812]
## User Story - Business Need
QA currently manually deploys vanotify-infra for perf and staging before deploying notification-api.
This needs to happen automatically within our pipeline in the spirit of CD and removing minutia from QA's workflow.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As**  Quality Assurance  
**I want** an automated process for deploying infra in our pipeline 
**So that** I have a smooth workflow and  infra changes are not accidentally overlooked when testing  

### Additional Info and Resources

The changes involved here likely involve:
- adding two new jobs to cd-pipeline.yml -- one that deploys infra to perf and the other to staging
- the jobs that deploy notification-api to perf and staging should `need` the deploy to infra complete and error free
- These jobs will likely be workflow_called from their own files in notification-api, similar to how run-regression.yml is configured and used in the pipeline. 
- vanotify-infra work for adding a workflow_call trigger to the relevant workflow

## Acceptance Criteria

WHEN there is a merge to master in notification-api and QA has approved the deploy to perf
THEN the cd pipeline first deploys to infra to ensure the latest vanotify-infra master is deployed and without error.

## QA Considerations
- QA is the main user - sync with DevOps to ensure final product is in line with optimizing QA work.

**Comment by cris-oddball** [comment]
This should be an independent pipeline in the Infra repo. Significant changes are needed here to review this ticket.

**Comment by k-macmillan** [comment]
Closing. DevOps will review what we have and create a new ticket in our infra repo for implementation.
