### ISSUE TITLE
BUG: Valid Twilio messages failing auth validation

### ISSUE THREAD

**Issue by mchlwellman** [department-of-veterans-affairs/notification-api#1816]
The vetext forwarder is failing some messages with the message - `Returning 403 on unauthenticated Twilio request`. This [datadog log query](https://vanotify.ddog-gov.com/logs?query=%40aws.awslogs.logGroup%3A%22%2Faws%2Flambda%2Fproject-prod-vetext-incoming-forwarder-lambda%22%20%22Returning%20403%20on%20unauthenticated%20Twilio%20request%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1715786625194&to_ts=1716391425194&live=true) shows the offending log messages.

![image](https://github.com/department-of-veterans-affairs/notification-api/assets/2913025/18603e70-8639-4d20-a4d6-e5ba61450fa4)

## Description

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Unknown, investigate incoming messages that have failed to ascertain the cause.

No workaround known.

## Impact/Urgency

Currently some Veterans' replies via Twilio are not being forwarded to VEText for their second account, which we did not have a token for. We are not sure if Twilio was successfully falling back to their other routing mechanism. If the fallback wasn't successful, then messages from Veterans have been dropped/not forwarded to VEText for processing.

We noticed that the messages all seemed to be coming from the Philippines. VEText has a second account specifically for outbound messaging to the Philippines.

## Expected Behavior

- [ ] Valid messages are routed to VEText as expected for both of their Twilio accounts
- [ ] We log enough information from the inbound message to be able to troubleshoot effectively without exposing Veteran data

**Comment by cris-oddball** [comment]
Just noting this started on April 22, affects messages To/From a specific country, whose config is in a different Twilio account.

**Comment by mjones-oddball** [comment]
Blocked externally as we await a new token and the full account sid to be able to validate properly. Kyle is also confirming with them if the fallback URL was effective in this case.

**Comment by mjones-oddball** [comment]
Root cause is likely this ticket where validation was introduced: https://github.com/department-of-veterans-affairs/vanotify-team/issues/1189#issuecomment-1860710883

**Comment by mjones-oddball** [comment]
After talking to Kyle we agreed it was ok to log the message body as long as it was encrypted, so that even if someone managed to access logs, they couldn't decrypted the info without more tools/secrets from our account.

**Comment by k-macmillan** [comment]
Received the new credentials. Added log encryption. Tested locally, good. Deployed to Dev and it's good. Tested in staging, good. Need access to the PH Twilio account so I can validate text to the PH number is not rejected.
