### ISSUE TITLE
Comp and Pen - Add Fields to VA Profile Cache

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1819]
## User Story - Business Need

We want to update our VA Profile cache table to include a `participant_id` and `has_duplicate_mappings` fields so we can make the Comp and Pen pipeline significantly more efficient. 

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** backend engineer    
**I want** add the necessary fields to our VA Profile cache table 
**So that** we have and efficient way of storing and retrieving this data  

## Acceptance Criteria

- [x] The VA Profile Cache table has been updated to include a `participant_id` and a `has_duplicate_mappings` fields

**Comment by cris-oddball** [comment]
Do we want to consider adding in API endpoints for this table so that the lambdas can just use the endpoints instead of making direct db calls and so that we can troubleshoot rows in that cache without having to log into the DB and run queries?

**Comment by cris-oddball** [comment]
PR approved/merged and sent through the pipeline up to Perf/Staging. Need to just jump on the DB and confirm the columns are there.

**Comment by cris-oddball** [comment]
**QA PASSED**

- No migration errors
- Verified that Perf table has_duplicate_mappings exists with  default 'f'
- Verified that Perf table participant_id exists with  default null
