### ISSUE TITLE
BUG: Comp & Pen - Not Processing Table Items

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1823]
## Description
The celery task that processes records from the dynamodb table is not gathering any records during the task. We are seeing the following critical logging error:
```
Exception trying to scan dynamodb table for send_scheduled_comp_and_pen_sms exception_type: 
<class 'botocore.exceptions.ClientError'> - exception_message: 
An error occurred (ValidationException) when calling the Scan operation: 
The provided starting key is invalid: The provided key element does not match the schema
```

All of the lower environments are reporting: `No Comp and Pen messages to send via send_scheduled_comp_and_pen_sms task. Exiting task`, but Prod is reporting the exception. The lower environments have processed records, so it is not surprising to see there are no messages to send.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

1. Trigger the celery beat task
2. Observe failure

## Workaround
None

## Impact/Urgency

High

## Expected Behavior

- [x] All records in the Production dynamodb table end up with `is_processed` being removed from the item
- [x] Coordinate with @k-macmillan - We want to do an out of cycle deployment so we can see celery in action in Prod before the end of the month

## QA Considerations
Retest as per the testing methodology in #1747

## Additional Info & Resources

**Datadog:**
<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzBYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0f1fbaa3b0a7f20d08dfd65c8bf7b5f120d1ebf/image.png" alt="image.png" />

<img width="1142" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEFYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9cb7c5773b6d0f57b1586cc3c6ddf37a91e6d942/image.png" alt="image.png" />
</br>
</br>

**PR info:**
- The original work was tested on #1747
- The original PR that implemented this work is [here](https://github.com/department-of-veterans-affairs/notification-api/pull/1795/files)
- `scheduled_tasks.py` in that commit now has a banner that the commit belongs to no branch.
<img width="1412" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--53e2ace1685e3664cd9cad6978e3782984a85a3a/Screenshot%202024-05-28%20at%207.58.01%E2%80%AFAM.jpg" alt="Screenshot 2024-05-28 at 7.58.01 AM.jpg" />
The code from that PR is not present in master.

**Comment by EvanParish** [comment]
I wasn't able to reproduce this error locally, but my testing in Perf was promising this morning. I believe I found the issue causing this error.

**Comment by EvanParish** [comment]
This was deployed to prod and works as expected!

**Comment by cris-oddball** [comment]
**QA PASSED**

This was tested previously in Perf as shown by these logs

> May 29 09:00:10.424 - perf-notification-api-log-group - sending - item from dynamodb - vaprofile_id: 5060 | participant_id: 5060 | payment_id: 6060
May 29 09:00:10.489 - perf-notification-api-log-group - Notification sent using Perf simulated number +14254147755 instead of vaprofile_id
May 29 09:00:10.490 - perf-notification-api-log-group - sent to queue, updating - item from dynamodb - vaprofile_id: 5060 | participant_id: 5060 | payment_id: 6060

Then deployed on it's own branch cut from the previous API tag directly to Prod and shown that Batch writer takes 10 seconds to update 3,000 records. We're going to make a new ticket to split the dynamo update and celery enqueue/apply async, which separates the updating of the dynamo table from the sending of the notification. 

Deployed via the pipeline thru Perf and Staging.
