### ISSUE TITLE
Comp and Pen - Separate DynamoDB and Persist/Celery Calls

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1826]
## User Story - Business Need
DynamoDB batch writes were timed and found to take about 10 seconds to update 3,000 records. It took about 100 seconds for all of the celery `apply_async` calls. 

We should update all records immediately after scanning the Table, then send the notifications in a separate method.

In the current form, dynamo updates are mixed with apply_async, so if celery/sqs has any hiccups, we are at high risk of sending more than one notification.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Veteran
**I want** only one notification regarding a particular comp/pen event
**So that** there is no confusion regarding what I am receiving

### Additional Info and Resources

This may allow the Celery Beat task to fire off every 20 seconds instead of every 2 minutes (assuming that does not burden the system).

This is within the `send_scheduled_comp_and_pen_sms` method. Currently the `send_notification_bypass_route` is called inside of a `batch_write` context block. That should be in a separate function that is called after all items have been updated.

## Acceptance Criteria

- [x] The items returned from a filtered DynamoDB Table scan are all updated with the `is_processed` attribute being removed prior to any calls to persist notifications.
- [x] `send_notification_bypass_route` is called in a for loop in a new method after all DynamoDB `put_item` requests are processed
- [x] Complexity of the `send_scheduled_comp_and_pen_sms` reduced below 10 and the `noqa` statement is removed

## QA Considerations

- [x] Exactly the expected amount of notifications are sent

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1826?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @ldraney @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1826?planning-poker) with Zenhub @cris-oddball

**Comment by EvanParish** [comment]
The code is pretty much complete. I just need to finish up writing the tests and then deploy and test the functionality.

**Comment by EvanParish** [comment]
The unit testing has been updated per the refactor. Testing has been completed in Dev. I would like to do some more testing in Perf to see how it handles at that scale. I don't expect to see any issues though.

**Comment by cris-oddball** [comment]
PR approved and merged, currently deploying thru pipeline and will send to Prod today because the cron job kicks off on Monday. will perform a short test on Perf to try to avoid the pinpoint 429s from being triggered and then check the stats on Monday in Prod.

**Comment by cris-oddball** [comment]
Perf table is seeded with 7746 records that should be sent on Monday, however I do expect us to see 429s on that since it's more records than I wanted in there.

**Comment by cris-oddball** [comment]
Decided to reset the table and re-run the short 30 event test. DynamoDB table is now populated with 16 items, and we expect 16 to be sent on Monday. Will still validate Prod as well (12,399 items in Prod).

**Comment by cris-oddball** [comment]
16 expected messages were sent via the bypass route for C&P in Perf.
<img width="1498" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemFJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0298908e1321be9800aa447a87d8373ecde59c06/Screenshot%202024-06-24%20at%208.31.20%E2%80%AFAM.jpg" alt="Screenshot 2024-06-24 at 8.31.20 AM.jpg" />

**Comment by cris-oddball** [comment]
**QA PASSED**

Feature Flag is not enabled in Prod, however DynamoDB still gets updated. All 12,399 items in the Prod table no longer have the `is_processed` attribute meaning they would have been queued for sending. That process took 9 minutes.
