### ISSUE TITLE
Upgrade AWS Lambda Python Version to 3.10 - API

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1839]
## User Story - Business Need

Upgrade the Python runtime version for AWS Lambda functions from 3.8 to 3.10 before the end of support in October 2024.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** backend engineer
**I want**  to upgrade the Python runtime version for our AWS Lambda functions to 3.10
**So that** we can take advantage of the latest features, improvements, and security patches in Python 3.10

### Additional Info and Resources

The current AWS Lambda functions are using Python 3.8, as specified in our GitHub Actions workflow. Python 3.10 offers several new features and optimizations that could benefit our Lambdas.
- the github action that needs to be updated: `.github/workflows/lambda-functions.yml`

## Acceptance Criteria

See the comments for explanations of the strikes.

- [ ] ~~All AWS Lambda functions are successfully running on Python 3.10.~~
- [ ] ~~Lambda layers are up-to-date. (See Infra Ticket)~~
- [x] The GitHub Actions workflow is updated to ~~deploy Lambda functions using Python 3.10.~~ remove the use of the set-python action
- [ ] There are no significant issues or performance degradation observed after the upgrade.
- [ ] ~~Relevant readme files and documentation has been updated accordingly.~~

## QA Considerations
- Without shared lambda test events, QA may need to either provide test events or assist with the testing of each lambda.

## Potential Dependencies

The API, Kafka and Infra tickets likely all need to be worked at the same time. (see **Dependencies** below)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1839?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
This ticket doesn't make sense to me.  Updating the Python version in the workflow step that uses the [setup-python action](https://github.com/actions/setup-python) has no effect on the Python version the lambdas actually execute, which is controlled [in infra](https://github.com/department-of-veterans-affairs/vanotify-infra/blob/master/cd/application-infrastructure/variables.tf#L3).

I think having the Python version in the workflow is a legacy of when we had the workflow bundle Python dependencies with the lambda code, but now we use layers.  Achieving the intent of this ticket should involve updating the infrastructure, removing the Python action from the workflow, updating the layers, and testing.

**Comment by kalbfled** [comment]
I discussed this with @EvanParish.  He is working on [infra 842](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/842), which handles the necessary infrastructure changes.  I am going to remove the set-python action for this ticket, and we will test the lambdas still function before closing it.

**Comment by kalbfled** [comment]
I removed the QA label after discussing it with QA.
