### ISSUE TITLE
Comp and Pen: Add US Currency Formatting for Payment Amount

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1858]
## User Story - Business Need

Currently we are not applying currency formatting to the payment amount in our SMS, so the dollar amount is displayed as an integer.
Current SMS content looks like this: “VA Benefits: Your compensation/pension monthly payment of $4321 is being processed. Reply STOP to unsubscribe, HELP for link to access VA payment history.”

This format doesn’t look appealing. We’d like to improve user-friendliness by applying a usual format for US dollar amounts where a decimal point separates dollars and cents, while a comma separates thousands.

Proposed new format: “VA Benefits: Your compensation/pension monthly payment of $4,321.00 is being processed. Reply STOP to unsubscribe, HELP for link to access VA payment history.”

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**        Veteran
**I want**      view the dollar amount of my recurring payment via text
**So that**    I can confirm my deposit is the amount I expect.

### Additional Info and Resources 

- The $ is currently static text in the template, so if it comes along with the conversion we use please ensure the template gets updated in Perf, Staging and Production. We don't want double($$).

The location of this code change is in the `send_comp_and_pen_sms` method of the `CompPenMsgHelper` class. The `payment_amount` that comes in is a decimal that gets changed to a string. It should be formatted with `f'{payment_amount:0,.2f}'`

## Acceptance Criteria

Given we are sending a valid recurring payment comp and pen text message and the payment amount is a personalisation within the template:
- When the payment amount is less than a thousand, we format it with decimal point only ($999.00) 
- When the payment amount is more than a thousand, we format it with decimal point and a comma separator for thousands ($1,999.00)

## QA Considerations

- Will need to confirm that the amount is translated appropriately between what’s in dynamo and the text that is populated/received.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1858?planning-poker) with Zenhub @cris-oddball @k-macmillan @kalbfled @MackHalliday @mchlwellman @EvanParish

**Comment by kalbfled** [comment]
The necessary changes probably belong around [here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/scheduled_tasks.py#L250).

**Comment by k-macmillan** [comment]
Removed the AC regarding paymentAmount -> amount.

**Comment by MackHalliday** [comment]
Tested in PERF with @EvanParish

https://files.slack.com/files-pri/T1ZD0UBMZ-F07EY5LC5GQ/image.png
![image](https://github.com/user-attachments/assets/f1a631c7-d498-4795-9270-3eafb9b31ba7)

**Comment by MackHalliday** [comment]
Friday 
- Submitted PR and made updates 

Today 
- In QA for testing.

**Comment by cris-oddball** [comment]
PR approved and merged, sending up to Prod, then testing.

**Comment by cris-oddball** [comment]
I'm still stuck without AWS access. Asked Michael to go into the Perf DB and update the following participant IDs to set `is_processed` as F so that they will be picked up by the cron job at 11:00 AM MT.
participant_id  vaprofile_id
600043175	134281
600043214	1273674
600075670	1131138

will check api logs after that time.
