### ISSUE TITLE
Fork Ruby Client Library

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#186]
# Value Statement:
**As a** VANotify developer
**I want to** have the ability to make changes to the client library  
**So that** VANotify can be updated for US users

# Acceptance Criteria
1. _Using the client library_
**WHEN** `vets-api` is built 
**THEN** it uses a VA-specific fork of `notifications-ruby-client`

2. _Updates to the client_
**WHEN** branches are merged into master of `department-of-veterans-affairs/notifications-ruby-client`
**THEN** a new version of the client is tested and published

3. _No pushes to master, please_
**WHEN** a developer tries to push to master of `department-of-veterans-affairs/notifications-ruby-client`
**THEN** the push is rejected - use PRs instead!

# Checklist:
- [ ] Fork [the ruby client repo](https://github.com/alphagov/notifications-ruby-client) - see [this issue](https://github.com/department-of-veterans-affairs/github-user-requests/issues/2619) for an example of how to request a fork. But specify Shane as the point of contact!
- [ ] Add a Github Action workflow to run on every push, which:
  - [ ] Runs tests
- [ ] Add Github Actions workflow to run on merges to master, which:
  - [ ] Runs Ruby client unit tests  (using the makefile!)
  - [ ] Installs dependencies (also using the makefile!)
  - [ ] Increments some version
  - [ ] Publishes the package to Github Packages ([like this!](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-rubygems-for-use-with-github-packages#publishing-a-package))
- [ ] In `vets-api`'s `Gemfile`, change `notifications-ruby-client` to reference the new fork from Github Packages ([like this!](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-rubygems-for-use-with-github-packages#installing-a-package))

# Assumptions:
- We will use the same Ruby version

# Additional Info/Resources:
-

# Out of Scope:
- Other client libraries 

# Open Questions:
-

**Comment by miabecker** [comment]
Can the change we are making be supported by the existing library? If yes we don't have to play this story...we also aren't sure this is the best pattern to pursue.

**Comment by k-macmillan** [comment]
@nathanbwright 
Closing this, as it's not part of the API.
