### ISSUE TITLE
BUG: Unhandled Opt-Out is still occurring

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#1865]
## Description
The issue thought to be solved in #1434 is still occurring with the Key Error on OPTED_OUT SMS status from Pinpoint:
<img width="1268" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ade5bf8426d08b404165f4466dee320b5c81db6/image.png" alt="image.png" />

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

It is uncertain what steps can be used to replicate the issue, but we can prevent it by successfully mapping this status. 

## Impact/Urgency

This issue affects prod but appears to occur once every couple days, for now.

## Expected Behavior

- [x] `record_status` of `OPTED_OUT` is handled in `get_notification_status`
- [x] New or updated unit test for this behavior. We should ascertain why we thought unit tests successfully validated this in the last ticket to ensure we're successfully filling the gap.
- [x] Any non-success is logged 100% of the time
- [x] `KeyErros` are caught

## Additional Info & Resources

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3BEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cb0d26472dfa30d1645c097a2dc1caa492f21454/image.png)

`if` should check for `record_status` of `OPTOUT`:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcDVEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d2273291f7391fa48b7cc0a7a948435b2f2af342/image.png)

Should see if the `OPTOUT` or `OPTED_OUT` is in the string, not the specific `_SMS.<thing>`.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1865?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
An example from the logs:
```
twilio callback return status of sent for notification: 2ca83a95-e00f-4efc-92c8-ee2a0cf642c4

Traceback (most recent call last):
File "/app/app/celery/process_pinpoint_receipt_tasks.py", line 106, in process_pinpoint_results
    notification_status = get_notification_status(event_type, record_status, reference)
File "/app/app/celery/process_pinpoint_receipt_tasks.py", line 156, in get_notification_status
    notification_status = _map_record_status_to_notification_status(record_status)
File "/app/app/celery/process_pinpoint_receipt_tasks.py", line 48, in _map_record_status_to_notification_status
    return _record_status_status_mapping[record_status]
KeyError: 'OPTED_OUT'
```

```
[2024-07-23 14:17:40,979: INFO/ForkPoolWorker-4] Processing Pinpoint result. | reference=jn7nb14nvgj61ro4ipje3a05mt2e0hvnra61clo0 | event_type=_SMS.FAILURE | record_status=OPTED_OUT | number_of_message_parts=1 | price_in_millicents_usd=0.0
```
