### ISSUE TITLE
Accept American spelling of "personalization"

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#187]
# Value Statement:
**As a** consumer of VANotify's APIs 
**I want to** be able to use the American spelling of "personalization" in my API requests
**So that** I don't have to remember to use the British spelling

# Acceptance Criteria

1. 🇺🇸🇺🇸🇺🇸 _Send notification, American-style_ 🇺🇸🇺🇸🇺🇸
**GIVEN** a template with personalization has been set up on VANotify
**WHEN** I make a request to send a notification using that template
**AND** I specify the personalized fields with `personalization: { ... }` (note the Z!) 
**THEN** the notification is successfully delivered

2. 🇬🇧🇬🇧🇬🇧 _Send notification, British-style_ 🇬🇧🇬🇧🇬🇧
**GIVEN** a template with personalization has been set up on VANotify
**WHEN** I make a request to send a notification using that template
**AND** I specify the personalized fields with `personalisation: { ... }` (note the S!) 
**THEN** the notification is successfully delivered
_note: this AC is current behaviour that we should make sure still works_

3. _One personalisation at a time please, form an orderly queue_
**GIVEN** a template with personalization has been set up on VANotify
**WHEN** I make a request to send a notification using that template
**AND** I provide a new-fangled all-American `personalization` object
**AND** I also provide an old-fashioned British `personalisation` object
**THEN** the API rejects the request as invalid

4. _OpenAPI documentation_
**WHEN** I view the OpenAPI documentation for `POST /v2/notifications/<sms or email>`
**THEN** the documentation specifies that both `personalization` and `personalisation` are accepted

5. _Postman collection_
**WHEN** I use the Postman collection to send `POST /v2/notifications/<sms or email>` requests
**THEN** the example requests use the American spelling: `personalization`

# Checklist:
- [ ] Update `post_sms_request` and `post_email_request` in `notification_schemas.py` to accept either `personalization` or `personalisation` - not both!
- [ ] Everywhere we read the `personalisation` object from the request, change it to read both `personalisation` and `personalization`, and take whichever is present
  - [ ] In `post_notifications.post_notification`, we validate the template against the personalization object -  `validate_template(..., form.get('personalisation', {}), ... )`
  - [ ] In `post_notifications.process_sms_or_email_notification`, we check if the personalization object contains files - `process_document_uploads(form.get('personalisation')...`
- [ ] Update OpenAPI documentation to note that both `personalization` and `personalisation` are accepted
- [ ] Update Postman collection (`notification-api.postman_collection.json`) to use `personalization` in its example requests

# Assumptions:
- The fork of the Ruby client library is complete
- Backward compatibility for the UK english spelling of Personalization must be maintained 

# Additional Info/Resources:
- Adding the new spelling and leaving the old spelling for backward compatibility

# Out of Scope:
- All other UK english spellings in VANotify are not in scope for this card
- Changes to the Client Library moved to card #186
- Changes to vets-api moved to card #224

# Open Questions:
- ~Does this just include changes to what the API accepts, or does this include other changes to the code (eg variable names)? What about changes to the database schema?~ - just changing what the API accepts. Don't bother renaming every variable and function in the code
- ~Does this include the field `redact_personalisation`, which is part of the Template model and API response?~ - no, since only the platform admins are likely to see that field

**Comment by npmartin-oddball** [comment]
V2 personalization stuck as-is. Closing.
