### ISSUE TITLE
Update Exception Logging

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#1874]
## User Story - Business Need
Logging exceptions has been inconsistent. We recently discovered that simply logging an `logging.exception('Description of what happened')` will include an `exc_info` object in the log stored in DD. This wraps the entire thing inside a single log message, which cleans up our logs significantly and sets the groundwork for us to keep track of these exceptions to better deal with them.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify engineer
**I want** to view concise logs, not spread across multiple logging events
**So that** I can accurately attribute an error to a particular log

### Additional Info and Resources

<img width="727" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDM3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c8c06cb5ed5c56f51afc99f9c1d6950cc48d62a/image.png" alt="image.png" />

Celery `ForkPoolWorker`s do not log `exc_info`! If you search for `"celery task failure"` in DD you can see Pool workers and non-workers report the same error, but Celery does not store the exc_info.

This may not work for all logging without addressing the way Celery workers surface logs.

Examples:
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0g3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd0e37ea833b9b29d2870c7effc19a024119d586/image.png" alt="image.png" />

Celery Worker:
<img width="890" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0w3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--df05c01d3ca227c37e6d0bed04fcaa9551d7e47e/image.png" alt="image.png" />

Non-Pool Worker:
<img width="852" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1Q3QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e487911575e2b7260d891aee41b24f0745230dbb/image.png" alt="image.png" />

## Acceptance Criteria

- [x] A repeatable exception is thrown and documented for before/after verification
- [x] Errors in try/except blocks use exception rather than error/critical
- [x] Updated exceptions do not contain the `e`, `exc`, etc in the log statement (see image in additional info) for API methods
- [x] Celery methods are not updated
- [x] `logger.exception` is not called outside of exception blocks

## QA Considerations

N/A - This is a logging ticket and the devs should test before/after changes

**Comment by kalbfled** [comment]
Critical logging should not be replaced with "exception" logging, which is syntactic sugar for Error level logging.
