### ISSUE TITLE
Remove backward compatibility for Personalization in VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#188]
# Value Statement:
**As a** VANotify developer 
**I want to** remove backward compatibility for Personalization (UK)
**So that** it is efficient to manage one spelling of Personalization (US)

# Acceptance Criteria
1. _US spelling (personalization)_
**GIVEN** VANotify receives a request for a notification
**WHEN** personalization data is sent using the US spelling (personalization)
**THEN** the notification is successfully sent 

2. _UK spelling_
**GIVEN** VANotify receives a request for a notification
**WHEN** personalization data is sent using the UK spelling 
**THEN** the request responds with an error 

3. _Update documentation_
**GIVEN** I access the documentation 
**WHEN** I view the documentation 
**THEN** the documentation specifies the US spelling (personalization)

4. _Update Postman_
**GIVEN** I use Postman 
**WHEN** I send the requests
**THEN** the example requests use the US spelling (personalization)

# Checklist:
- [ ] Checklist item here

# Assumptions:
- Any teams working with VANotify have made the necessary updates in production

# Additional Info/Resources:
-

# Out of Scope:
-

# Open Questions:
- When does this card need to be played? If there are no consumers this should be played immediately so that any teams onboarding don't have to refactor because of VANotify

**Comment by mjones-oddball** [comment]
Not sure that it's worth making people change their code to accept a new spelling. Can we just accept both spellings?

**Comment by npmartin-oddball** [comment]
V2 personalization stuck as-is. Closing.
