### ISSUE TITLE
Upgrade protobuf

### ISSUE THREAD

**Issue by mchlwellman** [department-of-veterans-affairs/notification-api#1886]
## User Story - Business Need

The notification-api container failed to deploy after a dependency upgrade due to issues with protobuf. From the logs it looks like the issue might be with eventlet, but that needs to be investigated.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   VANotify developer   
**I want** the latest version of protobuf    
**So that** we minimize vulnerabilities and future upgrade pains. 

### Additional Info and Resources

- According to pip (see the comment below), protobuf is required by these installed packages: ddtrace, google-api-core, googleapis-common-protos, grpcio-status, proto-plus.  Of these packages, at least ddtrace is a top-level dependency.

![screenshot_cropped](https://github.com/user-attachments/assets/f3030d11-5b26-40eb-8f20-66247f9516fa)

- protobof is not a top level dependency, the toml file should be reviewed to see what packages use it and identify what the conflict is that created the errors. 
- once resolved, the protobuf line can be removed from the toml file.
- Local testing did not reveal this issue, it required a deployment

## Acceptance Criteria

- [x] notification-api deploys successfully with the latest version of protobuf
- [x] Update the Slide deck with the key win and a demo slide

## Potential Dependencies

We should work this in parallel with ddtrace #1662

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1886?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
```
$ pip show protobuf
Name: protobuf
Version: 4.25.4
Summary: 
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: 3-Clause BSD License
Location: /.venv/lib/python3.10/site-packages
Requires: 
Required-by: ddtrace, google-api-core, googleapis-common-protos, grpcio-status, proto-plus
```

**Comment by EvanParish** [comment]
```sh
$ poetry show protobuf 
 name         : protobuf 
 version      : 4.25.4   
 description  :          

required by
 - ddtrace >=3
 - google-api-core >=3.19.5,<3.20.0 || >3.20.0,<3.20.1 || >3.20.1,<4.21.0 || >4.21.0,<4.21.1 || >4.21.1,<4.21.2 || >4.21.2,<4.21.3 || >4.21.3,<4.21.4 || >4.21.4,<4.21.5 || >4.21.5,<6.0.0.dev0
 - googleapis-common-protos >=3.20.2,<4.21.1 || >4.21.1,<4.21.2 || >4.21.2,<4.21.3 || >4.21.3,<4.21.4 || >4.21.4,<4.21.5 || >4.21.5,<6.0.0.dev0
 - grpcio-status >=4.21.6
 - proto-plus >=3.19.0,<6.0.0dev
 ```

**Comment by MackHalliday** [comment]
Picking up ticket - Since I'm out on Monday, I'll be leaving a comment at end of day Friday. @k-macmillan [will be picking up the ticket if not completed. ](https://oddball.slack.com/archives/C034496E4AU/p1728585654832539)

**Comment by MackHalliday** [comment]
Unpinned protobuf - ran poetry update, everything seems OK. Did I miss something?
