### ISSUE TITLE
Spike: Understand CI/CD process and recommend changes

### ISSUE THREAD

**Issue by coreycarvalho** [department-of-veterans-affairs/notification-api#1888]
## User Story - Business Goal

We currently implement CI/CD through Github Actions. It serves its purpose, but was created without much expertise in CI/CD. With the help of a DevOps engineer, we should look at our pipeline to make sure it adheres to industry best practices and attempt to enumerate some of the top problems it faces.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   VA Notify DevOps Engineer <br>
**I want**  to understand the CI/CD process <br>
**So that** I can identify pain points, areas of improvement, and provide recommendations. 

### Additional Info and Resources

- Pipeline: https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/workflows/cd-pipeline.yml
- https://www.atlassian.com/continuous-delivery/principles (some best practices to look at)
- https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions (security best practices)

## Acceptance Criteria & Checklist

- [x] Technical Documentation has been created and linked in the glossary
- [x] Learnings have been shared with the team, and decisions have been documented
- [ ] Tickets for next steps have been identified and created

Completed research addresses the problems and/or answers the questions below:  

1. Discuss VA plans/path related to CI/CD with Jeff Keene
2. At a high level, how does our CI/CD pipeline work?
3. Where are we utilizing industry best practices in our Github Actions? Where are we not?
4. What are the top 3 most important problem areas to tackle with our CI/CD pipeline?

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1888?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by coreycarvalho** [comment]
Drafted an initial spike document, ran it by Evan and Cris for initial feedback. Going to address their feedback and present to the team. Aiming to present Thursday so that I can create the necessary tickets/ADRs before we close out the sprint.

**Comment by coreycarvalho** [comment]
Scheduled spike learnings meeting for tomorrow.

**Comment by coreycarvalho** [comment]
Tickets (API):
https://github.com/department-of-veterans-affairs/notification-api/issues/1968
https://github.com/department-of-veterans-affairs/notification-api/issues/1969
https://github.com/department-of-veterans-affairs/notification-api/issues/1970
https://github.com/department-of-veterans-affairs/notification-api/issues/1971
https://github.com/department-of-veterans-affairs/notification-api/issues/1972
