### ISSUE TITLE
Updates to 526EZ Confirmation Email 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#189]
# Value Statement:
**As a** Veteran 
**I want to** view the 526EZ email
**So that** I have accurate data and updated content 

# Acceptance Criteria
_1. Updated Content_ 
**GIVEN** I receive the 526EZ confirmation email 
**WHEN** I review the email
**THEN** I view the updated content (form 21-526EZ removed from claim details, add last two sentences in email footer, add analytics to the link) 

_2. Updated time and time zone for date submitted_
**GIVEN** I receive the 526EZ confirmation email 
**WHEN** I review the email
**THEN** I view the time and time zone (time in UTC) 

_3. Updated subject line_
**GIVEN** I receive the 526EZ confirmation email 
**WHEN** I review the subject line
**THEN** I view the update subject line (We’ve received your application)

# Checklist:
- [x] Content updated - form 21-526EZ removed from claim details) 
- [x] Content updated - add last two sentences in email footer)
- [x] Content updated - display link - 'https://www.va.gov/claim-or-appeal-status/' embed link - (https://www.va.gov/claim-or-appeal-status/?utm_source=VANotify&utm_medium=email&utm_campaign=526EZ)
- [x] Time and Time zone updated
- [x] Subject line updated (We’ve received your application)

# Assumptions:
-

# Additional Info/Resources:
- Please review mockup for the changes

# Out of Scope:
-

# Open Questions:
- Current template subject is: 'Form 526 submission confirmation". Should it be updated to say 'Disability Compensation Application' instead of 'Form 526' ?- Added AC 3
- Question from Todd on the last sentence not displaying - Added to AC 1
- Question on adding analytics to the link (?utm_source=VANotify&utm_medium=email&utm_campaign=526EZ) - Added to AC 1

# Mockup:
![email-template-9.30.20.jpg](https://images.zenhubusercontent.com/5ecd57a8ffd816c37838ab46/56898953-fad8-4011-8cdd-31645792d14e)

**Comment by QaysarA** [comment]
Reviewed Litmus and the following issues - 
- Apple Mail 12
https://litmus.com/folders/unsorted_emails/emails/1591409/checklist#appmail12

- Apple Mail 13 
https://litmus.com/folders/unsorted_emails/emails/1591409/checklist#appmail13

- ![Screen Shot 2020-10-13 at 10.08.03 AM.png](https://images.zenhubusercontent.com/5ecd57a8ffd816c37838ab46/4b66ec0f-447a-41d2-871a-4566c8650923)Outlook 2016 + Mac OS 10.12
https://litmus.com/folders/unsorted_emails/emails/1591409/checklist#ol2015

**Comment by toddstanich** [comment]
Verified changes in Litmus.
