### ISSUE TITLE
BUG: ProviderService class using DEBUG as default setting for logs

### ISSUE THREAD

**Issue by MackHalliday** [department-of-veterans-affairs/notification-api#1895]
## Description

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

- The ProviderService class shows DEBUG logs for all environments. This should not happen because [a user story was complete to only show DEBUG logs in non-Prod.](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-utils/146) 
- This is happening because the LogLevel is hard coded in the ProviderService and does not use `current_app.logger`. (See file `/notification-api/app/provider_details/provider_service.py`)

### Screenshot of DEBUG Logs
<img width="1123" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9kQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b56adfa6214da9a88c4628e38b8595007f8ea7f8/image.png" alt="image.png" />

## Steps to Reproduce

1. Send an email notification thru postman - any email notification
2. This should hit the ProviderService class
3. View the logs in DataDog and look for DEBUG logs such as `'Returning provider: %s'` or `Found template provider ID`. 

## Impact/Urgency

High - DEBUG log should NOT be showing in the Prod environment 

## Expected Behavior

- [x] When a notification is sent in a Prod environment, no DEBUG logs should be visible. 

## Additional Info & Resources

- Should be fixable by using `current_app.logger.debug` instead of `logger`. Remove the logging setup in lines 12-14 and import `current_app`.

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1895?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman
