### ISSUE TITLE
BUG: the participant_id column throws NumericValueOutOfRange error

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1897]
## Description

While validating the lambda dependency upgrade ticket in Dev and exercising all lambdas, we started seeing catastrophic alerts on the MPI Lookup lambda due to a participant_id that throws a NumericValueOutOfRange error. 

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

The root cause is seen in this log and traceback:

> [DEBUG]	2024-07-30T16:35:48.355Z	893d5bd3-58aa-55ed-964b-04f040ee50c8	Persisting item with participant_id: 9100787210, va_profile_id: 7105

> [ERROR] NumericValueOutOfRange: integer out of range

> Traceback (most recent call last):
  File "./python/lib/python3.10/site-packages/datadog_lambda/wrapper.py", line 232, in __call__
  File "/var/task/bip_msg_mpi_lookup_lambda.py", line 99, in bip_msg_mpi_lookup_handler
    def bip_msg_mpi_lookup_handler(event: dict, context=None) -> dict:
  File "./python/lib/python3.10/site-packages/ddtrace/contrib/aws_lambda/patch.py", line 120, in __call__
  File "/var/task/bip_msg_mpi_lookup_lambda.py", line 128, in bip_msg_mpi_lookup_handler
    return_value = asyncio.run(bip_msg_mpi_lookup_async_handler(records, db_connection))
  File "/var/lang/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/var/lang/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "./python/lib/python3.10/site-packages/ddtrace/contrib/asyncio/patch.py", line 50, in traced_coro
  File "/var/task/bip_msg_mpi_lookup_lambda.py", line 185, in bip_msg_mpi_lookup_async_handler
    persist_row(participant_id, va_profile_id, db_connection)
  File "/var/task/bip_msg_mpi_lookup_lambda.py", line 290, in persist_row
    c.execute(VA_PROFILE_UPDATE_QUERY, (participant_id, va_profile_id))
  File "/opt/python/lib/python3.10/site-packages/ddtrace/contrib/dbapi/__init__.py", line 156, in execute
    return self._trace_method(
  File "./python/lib/python3.10/site-packages/ddtrace/contrib/psycopg/cursor.py", line 14, in _trace_method
  File "/opt/python/lib/python3.10/site-packages/ddtrace/contrib/dbapi/__init__.py", line 125, in _trace_method
    return method(*args, **kwargs)

Additionally, this is apparently being retried, which should not happen.
<img width="1101" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzBkQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81817bdd819d52fb1aa23d1d3473c38ed970300d/Screenshot%202024-07-30%20at%2011.06.27%E2%80%AFAM.jpg" alt="Screenshot 2024-07-30 at 11.06.27 AM.jpg" />

## Steps to Reproduce

1. Run the ETL lambda in Dev, which will trigger the MPI lambda
2. Observe the logs as shown above (the exception and the retries)

## Impact/Urgency

HIGH - we are expected to launch in August and this bug will prevent certain veterans with participant-ids that are out of range from  receiving sms notifications.

## Expected Behavior

- [x] When the ETL lambda is run and triggers the MPI lambda, upon an insert attempt, Postgres will accept the size of the participant_id and not throw an out of range error
- [ ] ~~If an out of range error is thrown, it is properly handled and not retried~~ This will be addressed in [#175](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-kafka/175)

## QA Considerations
- [x]  work with Dev on validating in dev and perf

## Additional Info & Resources

Integer in Postgres is -2147483648 to +2147483647
This column should be a bigint - see [documentation](https://www.postgresql.org/docs/current/datatype-numeric.html)
As should the VA Profile ID

Line where the code should likely be changed is [here](https://github.com/department-of-veterans-affairs/notification-api/blob/dd562dc6ea2587130643dc7dac21daa0b35cea7e/app/models.py#L2184).

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1897?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by MackHalliday** [comment]
elt collects va profile -> gives to MPI looking -> gets back large VA profile id

**Comment by cris-oddball** [comment]
> elt collects va profile -> gives to MPI looking -> gets back large VA profile id

it's  elt collects va profile -> gives to MPI looking -> gets back large participant_id

regardless, both need to be bigint (vaprofile id and participant id)

**Comment by MackHalliday** [comment]
Friday
- Add migration, issues with running migrations local. Seem to be unran migrations 
- Looked at Kafka repo for throwing error for 

Today 
- Put in PR today

**Comment by MackHalliday** [comment]
Rolling over to next sprint 

This was pulled in on Friday. It's rolling over because it's slow to test the migrations and also we decided to delete data if the data is not backwards compatible.

**Comment by MackHalliday** [comment]
Yesterday 
- Worked on downgrade functionality and using the DB Downgrade Github Action 
- Updated documentation on DB Downgrade Github Action 

Today 
- Submitted PR and awaiting PR approvals

**Comment by cris-oddball** [comment]
PR approved and merged.

Will run the MPI Lookup when deployed to Perf just to ensure that no regressions were introduced.

**Comment by cris-oddball** [comment]
Regression passed in Perf and MPI Lookup Lambda functions as expected. Closing ticket and sending to Prod.
