### ISSUE TITLE
Remove Celery self.request.chain hack

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#1914]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Notify developer,
**I want** to halt execution of a chain of Celery tasks the right way according to the documentation
**So that** the code doesn't inadvertently break in the future.

### Additional Info and Resources

A Celery task in a [chain](https://docs.celeryq.dev/en/stable/userguide/canvas.html#chains) only executes when the proceeding task successfully exists.  To terminate the chain early, one should raise a non-retryable exception.  However, our code base contains some sort of undocumented hack that terminates the chain using `self.request.chain = None`.

```
.../notification-api$ grep -rn -E "self\.request\.chain" .
./app/celery/lookup_va_profile_id_task.py:78:        self.request.chain = None
./app/celery/lookup_va_profile_id_task.py:91:        self.request.chain = None
./app/celery/lookup_recipient_communication_permissions_task.py:66:        self.request.chain = None
./app/celery/contact_information_tasks.py:67:        self.request.chain = None
```

## Acceptance Criteria

- [ ] Instances of `self.request.chain = None` removed, non-retryable exceptions raised where appropriate, and all unit tests pass

**Comment by kalbfled** [comment]
I ended up deleting 3 of 4 instances of `self.request.chain` as part of #1800.  Only the occurrence in lookup_recipient_communication_permissions_task.py remains.

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1914?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
I'm working on a revision of #1800, and I ended up removing the last occurrence in lookup_recipient_communication_permissions_task.py.  This ticket is no longer necessary.
