### ISSUE TITLE
BUG: undefined method process_letter_notification method is dead code

### ISSUE THREAD

**Issue by MackHalliday** [department-of-veterans-affairs/notification-api#1915]
## Description

- There is an undefined method `process_letter_notification` in `app/v2/notifications/post_notifications.py`

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

- See file `app/v2/notifications/post_notifications.py` and undefined method `process_letter_notification` around line 107

<img width="1762" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVE1Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c2fc2bde6093985c8ffa73e5e231ec7e003f7d19/Screenshot%202024-08-06%20at%206.58.03%E2%80%AFPM.png" alt="Screenshot 2024-08-06 at 6.58.03 PM.png" />

## Impact/Urgency

Low 

## Expected Behavior

- [ ] Remove dead code and any related tests 
- [ ] No change to functionality of `post_notification` method

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1915?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman
