### ISSUE TITLE
Enable Feature Flag VA_PROFILE_V3_USE_PROFILE_API_V3 in staging/perf environments

### ISSUE THREAD

**Issue by AdamKing0126** [department-of-veterans-affairs/notification-api#1916]
## User Story - Business Need

[PR 1900](https://github.com/department-of-veterans-affairs/notification-api/pull/1900) added new functionality to hit the V3 Profile API endpoint.  This code is currently only enabled in the `dev` environment.  This ticket is to enable the flag in the staging/perf environments for further testing before it's enabled in `prod`

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  software developer working with QA to prove out an API upgrade  
**I want**  to enable the feature flag in production-like environments 
**So that** we can insure that the new functionality works as expected before deploying to production 

## Acceptance Criteria

Existing functionality to send sms and email notifications works as expected - communication permissions settings should also be respected.

## QA Considerations

When the feature flag is enabled, network requests will flow to the new API endpoint, but existing functionality should not be altered in any way.

**Comment by cris-oddball** [comment]
Code is in progress.

**Comment by cris-oddball** [comment]
PR approved, merged and deployed to Perf.
