### ISSUE TITLE
Remove old feature flag: CHECK_RECIPIENT_COMMUNICATION_PERMISSIONS_ENABLED

### ISSUE THREAD

**Issue by AdamKing0126** [department-of-veterans-affairs/notification-api#1919]
## User Story - Business Need
[VA-IIR Issue 893](https://github.com/department-of-veterans-affairs/va-iir/issues/893)

The feature flag, `CHECK_RECIPIENT_COMMUNICATION_PERMISSIONS_ENABLED` was added 3 years ago.  It's time to clean that up.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** software developer working on the Notification API repo
**I want** to remove long-running feature flags 
**So that** the codebase is easy to read and eliminates confusion 

## Acceptance Criteria

[ ] `CHECK_RECIPIENT_COMMUNICATION_PERMISSIONS_ENABLED` feature flag is removed from the codebase and all environments

**Comment by cris-oddball** [comment]
PR approved and merged, deployed to Perf. Holding to bundle with the next ticket to remove the feature flag.

**Comment by cris-oddball** [comment]
Deployed to Prod.
