### ISSUE TITLE
Enable Feature Flag VA_PROFILE_V3_USE_PROFILE_API_V3 in production environment

### ISSUE THREAD

**Issue by AdamKing0126** [department-of-veterans-affairs/notification-api#1920]
## User Story - Business Need

See:
https://github.com/department-of-veterans-affairs/notification-api/pull/1900
https://github.com/department-of-veterans-affairs/notification-api/pull/1917

New functionality is merged but not enabled in the production environment.  Flag is enabled in the lower environments and the code functions as expected

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** software developer working on a feature in the Notification API
**I want**  to enable a feature flag to enable the functionality in the production environment
**So that** the goal of the original ticket, changing API endpoints, can be accomplished.

## Acceptance Criteria

[ ] New functionality is enabled in production and functions which get a user's email address, phone number, and communication preferences still function as expected.

**Comment by cris-oddball** [comment]
PR approved and merged, deployed to Perf. Will bundle with previous commit to go to Prod.

**Comment by cris-oddball** [comment]
Deployed to Prod.

**Comment by AdamKing0126** [comment]
Thanks @cris-oddball
