### ISSUE TITLE
Remove Feature Flag PROFILE_V3_USE_PROFILE_API_V3 and delete old code

### ISSUE THREAD

**Issue by AdamKing0126** [department-of-veterans-affairs/notification-api#1925]
## User Story - Business Need

[Companion Ticket](https://github.com/department-of-veterans-affairs/va-iir/issues/892) from VA-IIR Team

We've enabled the `PROFILE_V3_USE_PROFILE_API_V3` feature flag in production and are observing Datadog for any irregularities.  Once we are satisfied that the new functionality works as expected, we will need to remove the feature flag and the old logic.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** software developer working on the notification api
**I want** to remove feature flags after the new code has been proven
**So that** we retain a concise and easy to read codebase

## Acceptance Criteria

[x] `PROFILE_V3_USE_PROFILE_API_V3` feature flag is removed
[x] Old code which was bypassed by enabling the feature flag is removed
[x] All existing functionality is maintained

## QA Considerations

The code should be functionally identical, with no expected changes in behavior.  Notable Postman collection requests to use:
- send sms with phone_number
- send sms with recipient_id
- send email with email_address
- send email with recipient_id

**Comment by cris-oddball** [comment]
PR is open for reviews.

**Comment by cris-oddball** [comment]
PR approved and merged, will be sent to Prod today.

**Comment by cris-oddball** [comment]
In the pipeline and staged for deployment to Prod. Closing ticket as Done.
