### ISSUE TITLE
Automated User Flow Tests

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#193]
# Value Statement:
**As** 
**I want to** 
**So that**

# Acceptance Criteria
**GIVEN** 
**WHEN** 
**THEN**

# Checklist:
- [ ] Checklist item here

# Assumptions:
-

# Additional Info/Resources:
-

# Out of Scope:
-

# Open Questions:
-

**Comment by miabecker** [comment]
Can be closed as we will be adding user flow tests as apart of each story vs. having a separate story.
