### ISSUE TITLE
Regular Update for Dependencies

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1933]
## User Story - Business Need

We wish to keep dependencies up to date so that we do not need such massive overhauls of our system. This is a recurring task to update all dependencies we are able to update. Any conflicts shall get a dedicated ticket. This task should be a day of work at most because it only updates non-breaking changes.

- [x] Ticket is understood and QA has been contacted

### User Story

**As** VA Notify,
**I want** to keep our service up to date
**So that** we are secure and as free of bugs as possible.

### Additional Info and Resources

- Relevant section of [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-dependencies)
- Troubleshooting tips:
  - When looking at changes in `poetry.lock`, revert major changes, then minor, then patch/security: **never** edit this file manually!

Importtant: gunicorn should be upgraded in this ticket to >=23.x

## Engineering Checklist

- [x] Review "Tech Debt" tickets in backlog to identify packages already known to have breaking changes (**don't try to upgrade these**) 
  - pro-tip: these should be pinned down to a specific version in the pyproject.toml file
 - [x] Remove all Makefile ignores to clear any safety issues, re-add as necessary
- [x] Review [open Dependabot PRs](https://github.com/department-of-veterans-affairs/notification-api/pulls/app%2Fdependabot) to determine where the changes will take place (open them and look at the files touched). 
  -  Do not modify these PRs
- [x] Update performed per the [README.md](https://github.com/department-of-veterans-affairs/notification-api#update-dependencies)
- [x] Passes all tests locally
- [x] Passes QA Suite regression testing against Dev
- [x] If there are any failures, compare the [poetry.lock in master](https://github.com/department-of-veterans-affairs/notification-api/blob/master/poetry.lock) against your local `poetry.lock`. 
  - [x] Identify the discrepancies and lock those versions in `pyproject.toml`, create a ticket, and label it "tech debt"
  - [x] Any non-top level dependencies that have to be locked should have a comment added to `pyproject.toml` and have a checkbox to remove that dependency from `pyproject.toml` in the acceptance criteria
  - [x] Created ticket has the package name in the title

## Acceptance Criteria

Repo dependencies are updated and we have no broken functionality. Issues opened by Dependabot or listed in the Makefile are resolved. Tickets with the "tech debt" label created for any updates we could, or should, not do.

## QA Considerations

- [x] Affected Dependabot PRs are closed after merge (may need to rebase them using dependabot command)
- [x] Check to see if these updates cancel out any Twistlock issues
- [x] QA Regression tests pass after deploying this code.

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1933?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by MackHalliday** [comment]
Notes from QA - 
If pinned, don't upgrade. 
Do not upgrade if tech debt ticket. 
Do not touch the dependent

**Comment by MackHalliday** [comment]
Yesterday 
- Met with QA 

Today
- Complete story and submit PR.
-

**Comment by cris-oddball** [comment]
PR approved and merged, just need to check regression on Perf and clear Dependabot issues.

**Comment by cris-oddball** [comment]
FYI - Looks like the [boto3 dependabot issue](https://github.com/department-of-veterans-affairs/notification-api/pull/1892/files) was missed - the upgrades would be in the requirements file for load testing. When I rebased, it closed that one and [opened a new one.](https://github.com/department-of-veterans-affairs/notification-api/pull/1955) It would be good to clear these even if we are not using them at this time and we're probably a few sprints away from bringing up the new load test stuff.

**Comment by cris-oddball** [comment]
All possible Dependbot issues are closed now.
