### ISSUE TITLE
BUG: incorrect versioning for label ignore-for-release

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1940]
## Description

We use labels in notification-api to determine the tag (version) that will be applied to the API in the pipeline. The label` ignore-for-release` will incorrectly bump the version to a minor. We do not want this. Additionally, other logic in the GHA should be changed,

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

As this cannot be reproduced with merging a PR that has the label ignore-for-release on it, and as that would create a pipeline that would need to be cancelled, this section is relying on the code itself and what was seen in the pipeline to illustrate the bug.

When a merged commit with the label `ignore-for-release` starts the pipeline, the GHA expects to bump the version to Minor:
<img width="647" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHRmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9dcb44244de5e7be2db98383f786132b90ee255a/Screenshot%202024-08-15%20at%2010.13.08%E2%80%AFAM.jpg" alt="Screenshot 2024-08-15 at 10.13.08 AM.jpg" />

This is because the code flow will set it as such:
<img width="537" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDFmQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abbf47e55bed853d45b224eafed41391f2e168ea/image%20%2846%29.png" alt="image (46).png" />

The code in this logic is poorly handled. Minor should be explicitly stated as it is with Major, and the catch all should be Patch, so the if/elif/else block needs to be refactored.

Additionally, the error handling should never return Unknown. We have no way to modify the version via the pipeline. We need to determine how to handle this case (stop the pipeline?)

**NOTE!** A decision needs to be made here: do we want ignore-for-release to not bump the version at all or to bump the version to patch without adding it to the release notes? Probably patch, since there is a difference in versions.

## Workaround
Change the label on the PR before approving the first step.

## Impact/Urgency

High - this impacts the pipeline and we cannot reversion the tag once the pipeline send the code to Perf. 

## Expected Behavior

- [ ] when a PR is labeled 'ignore-for-release' then the version is either not bumped or is bumped to patch and the info is not included in the release notes.

## QA Considerations
- [ ]  verify testing with pipeline and a non-essential PR.

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1940?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment]
Overwritten by future ticket work.
