### ISSUE TITLE
Create VA Profile mock

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#195]
# Value Statement:
**As** 
**I want to** 
**So that**

# Acceptance Criteria
**GIVEN** 
**WHEN** 
**THEN**

# Checklist:
- [ ] Checklist item here

# Assumptions:
-

# Additional Info/Resources:
-

# Out of Scope:
-

# Open Questions:
-

**Comment by miabecker** [comment]
Might be handled in 192 already.
