### ISSUE TITLE
Deploy from main branch instead of release branch

### ISSUE THREAD

**Issue by coreycarvalho** [department-of-veterans-affairs/notification-api#1969]
## User Story - Business Need

Currently, we use the `main` branch to deploy to perf and `release` to deploy to staging and production. This means that the `main` branch isn't serving any purpose other than being a holding ground for perf deploys. In order to facilitate a smoother CI/CD pipeline, we want to deploy everything from main and get rid of the release branch.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**    VA Notify developer
**I want**  to deploy to staging and production from main
**So that** we can streamline our CI/CD process.

## Acceptance Criteria

- [x] Github actions/workflows are updated to deploy from main instead of release
- [x] Github actions/workflows that cut the release branch are removes
- [x] All existing pipeline steps remain the same. (Approvals, for example)
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations
- Verify that things still work as expected (tag is cut on main, main is deployed to higher envs, etc)

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1969?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @mchlwellman
