### ISSUE TITLE
Simplify PR labeling that versions deploys

### ISSUE THREAD

**Issue by coreycarvalho** [department-of-veterans-affairs/notification-api#1970]
## User Story - Business Need

Our CI/CD pipeline uses PR labels to determine how to bump the version of our code. We use semver versioning, which contains 3 parts (major.minor.patch), but we use more than 3 labels that eventually map to the 3 part semver scheme. This is cumbersome for developers.

We'd like to simplify this to use only 3 labels: major, minor, and patch. Those labels will match 1:1 to the semver versioning scheme.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**    VA Notify developer
**I want**  to simplify our PR labeling scheme to align with semver
**So that** I can have a more streamlined development process.

## Acceptance Criteria

- [x] When a PR labeled as `major` is merged, the version of API is bumped a major version
- [x] When a PR labeled as `minor` is merged, the version of API is bumped a minor version
- [x] When a PR labeled as `patch` is merged, the version of API is bumped a patch version
- [x] Documentation (working agreements, among others) updated to reflect new labeling scheme
- [x] Revise the link in PR template to point to updated docs
- [x] Team discussion to confirm that all members on team understand the new working agreement and that this labeling scheme is only for the API.

**Comment by coreycarvalho** [comment]
Updated https://docs.google.com/document/d/1nwZIF_lydPWfvixxZlQLNt4nqy3Qp13pHQnMcYJjTqE/edit with the new labels

**Comment by cris-oddball** [comment]
Ticket is just here to remind me to send the two commits up through the pipeline for 
- updating PR template to include link to new labels document
- updating release notes to not have any subsections

**Comment by cris-oddball** [comment]
Since we are not rolling back the API, these commits will automatically go up to prod on the next API commit for the IIR fix. No need to hold open this ticket.
