### ISSUE TITLE
Deploy the same image to every environment on deploy

### ISSUE THREAD

**Issue by coreycarvalho** [department-of-veterans-affairs/notification-api#1971]
## User Story - Business Need

Our CI/CD pipeline builds a docker image for each environment. This means that there is no guarantee of the exact same image going out to every environment. It also adds unnecessary time to the pipeline.

We should be building the image once and deploying it to every environment.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**    VA Notify developer
**I want**  the CI/CD pipeline to only build an image once
**So that** we can reduce build/deploy times and ensure consistency in our environments

## Acceptance Criteria

- [x] After merging to main, a single docker image is built and used throughout the pipeline
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1971?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by coreycarvalho** [comment]
Putting this down for a little bit while I work with @k-macmillan to look into some database issues.

**Comment by coreycarvalho** [comment]
First PR has been merged to have docker building as an action and not a workflow. Will likely wrap this ticket up today.

**Comment by coreycarvalho** [comment]
Need to make adjustments to the dependency tree of the workflow calls and rename some steps to be a bit more clear. Needed to put this down to address Celery scaling yesterday and a hotfix with the pipeline today.

**Comment by coreycarvalho** [comment]
Worked with @cris-oddball on the ideal ordering of operations for this work. Perf has been taken up for the majority of the day, so I plan on testing this first thing tomorrow.
