### ISSUE TITLE
BUG: Update to Delivered After Other Status is Assigned

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#1977]
## Description

When **sms notifications** are updated to delivered this should override any currently existing status in our system as it means that notification was actually sent.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

## Steps to Reproduce

This would be tricky to manually reproduce since it comes from a timing issue with notification status updates from AWS. See [additional info](#additional-info-&-resources) for more specifics on identifying the issue.

## Impact/Urgency

This bug prevents the correct status from being reported, which can lead to confusion for our customers. It is important for the "Delivered" status to override other statuses, such as the "Preferences Declined" status, to ensure accurate tracking and reporting.

## Expected Behavior

- [x] When a "delivered" status is received for an sms message, it should override any other existing status.
- [x] Nothing should override an sms "delivered" status
- [x] Logic must take place at the DB level since the app is distributed
- [x] Email status rules are not modified
- [x] Update the Slide deck with the key win and a demo slide

## QA Considerations
- Issue discovered during monthly C&P notification sends. Should take a look at expected behavior in Perf.

## Additional Info & Resources

- This will involve changing logic in various places that handle updating notifications, such as: 
  - [check_notification_status](https://github.com/department-of-veterans-affairs/notification-api/blob/va-iir-895-combine-permission-lookup/app/celery/process_pinpoint_receipt_tasks.py#L212) for pinpoint updates
  - [process_ses_results](https://github.com/department-of-veterans-affairs/notification-api/blob/va-iir-895-combine-permission-lookup/app/celery/process_ses_receipts_tasks.py#L157) for ses updates

Example error message:
```
Invalid callback received. Notification id * received a status update to delivered 0:00:23.559814 after being set to preferences-declined. sms sent by pinpoint
```

Which can be found in [app/celery/process_pinpoint_receipt_tasks.py](https://github.com/department-of-veterans-affairs/notification-api/blob/va-iir-895-combine-permission-lookup/app/celery/process_pinpoint_receipt_tasks.py#L233) and [app/celery/process_delivery_status_result_tasks.py](https://github.com/department-of-veterans-affairs/notification-api/blob/va-iir-895-combine-permission-lookup/app/celery/process_delivery_status_result_tasks.py#L156)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1977?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @mchlwellman

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1977?planning-poker) with Zenhub @coreycarvalho

**Comment by EvanParish** [comment]
The checks that happen to determine if the notification should be updated or not have been altered to allow for "delivered" to override other statuses. I still need to make changes at the query level to ensure notifications are being update properly in case another process updated it while the initial checks were happening.

**Comment by EvanParish** [comment]
This ended up being more complex than expected and with juggling various other responsibilities I wasn't able to finish it up within this sprint. It should be finished at the start of next sprint.

**Comment by EvanParish** [comment]
A point of clarification here. Email notifications currently use the same query when updating their statuses as sms. The SES path has checks in place that will update the notification status if a bounce update happens. A bounce will override other statuses for ses. I point this out because this is mainly a problem if a "delivered" status is sent out of order from a bounce for SES updates. A new query would need to be constructed in this instance to handle that situation. That is outside of the scope of this ticket.
