### ISSUE TITLE
Fix timezone tests

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/notification-api#20]
In the code, there are several tests in test_utils that fail due to timezone errors. These should be fixed. Right now, we are skipping the tests.

We think the problem is caused because the timezone is set to Toronto (which is the same as EST) and but their pipeline is running in UTC. So, for the Canadians, the tests pass on their pipeline. But, when run locally, the tests fail.

If you look in the git history, they changed the get_local_timezone_midnight() shortly after daylight savings time.

**Comment by miabecker** [comment]
@ffafara-tw do we still think this is an issue? Just checking in as I go through the backlog with Qaysar.

**Comment by ffafara-tw** [comment]
Yup, still an annoying (at times) issue.

**Comment by miabecker** [comment]
We are going to comment out these tests for not but this still needs to happen.

**Comment by lingtran** [comment]
Potential fix to merge: https://github.com/cds-snc/notification-api/commit/0ede6a61b48289236d1873124965d2bc22a9b27b

**Comment by miabecker** [comment]
Saman and Marissa fixed 2 or 3. But then there is more they found that was buggy.

**Comment by TWs-DevenS** [comment]
Reviewed Story with Saman, verified the timezones fix. The test utilities now see to be fixed with no errors.
