### ISSUE TITLE
Lookup VAProfile ID

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#200]
# Value Statement:
**As** VANotify
**I want to** retrieve the VA Profile ID from MPI
**So that** I can lookup the recipient's contact information

# Acceptance Criteria

_Prerequisites_ 
**GIVEN** the API has received a request to send a notification
** AND** that request specifies a `va_identifier.id_type` that's not `VA_PROFILE_ID`
**AND** a task `lookup_va_profile_id` has been enqueued
_(completed as part of #190)_

- [x] AC1. _Happy path - lookup VA Profile ID_
**WHEN** the task `lookup_va_profile_id` executes for a notification
**THEN** VANotify should make a request to MPI, including that notification's PID or ICN
**AND WHEN** MPI responds with a list of correlation IDs including VA Profile ID
**THEN** the VA Profile ID is stored in Recipient Identifiers table connected to that notification
**AND** the `lookup_contact_info` task is enqueued 

- [x] AC2. _No VA Profile ID 😭_
**GIVEN** VANotify has made a request to MPI, including a PID or ICN
**WHEN** MPI's response does not include a VA Profile ID
**THEN** the notification's status is updated to `TECHNICAL_FAILURE`

- [x] ~AC3. _Feature toggle is enabled_~ -> We decided to instead keep everything under the `ACCEPT_RECIPIENT_IDENTIFIERS_ENABLED` toggle.
**GIVEN** the feature toggle `LOOKUP_VA_PROFILE_ID_ENABLED` is enabled
**WHEN** VANotify receives a request to send a notification
**AND** that request specifies a `va_identifier.id_type` that's not `VA_PROFILE_ID`
**THEN** the API enqueues the `lookup_va_profile_id` task

- [x] ~AC4. _Feature toggle is disabled_~ -> We decided to instead keep everything under the `ACCEPT_RECIPIENT_IDENTIFIERS_ENABLED` toggle.
**GIVEN** the feature toggle `LOOKUP_VA_PROFILE_ID_ENABLED` is disabled
**WHEN** VANotify receives a request to send a notification
**AND** that request specifies a `va_identifier.id_type` that's not `VA_PROFILE_ID`
**THEN** the API responds with `501 NOT IMPLEMENTED` http status

- [x] AC5. _Use our certificate for communication with MPI_
**WHEN** VANotify makes a request to MPI
**THEN** it uses a certificate for the current environment to authenticate itself to MPI

- [x] AC6. _Use correct sender id_
**WHEN** VANotify makes a request to MPI
**THEN** it includes a request parameter `senderId`, with the value `200ENTF`

# Checklist:
- [x] Add a new feature toggle to `notification-api` - `LOOKUP_VA_PROFILE_ID_ENABLED`
- [x] Update User Flows
- [x] Error - MPI returned 404 not found
- [x] Statsd
- [x] Logging (errors)
- [x] Retries
- [ ] Mountebank - look at test scenarios to guide what we want to set up
- [x] Chaining tasks - add a test!
- [x] Handle certificates - if passed in, use them
- [x] make sure all exceptions are correct
- [x] when more than 1 active VA Profile ID > fail notification

# Assumptions:
-

# Additional Info/Resources:
- Add feature toggle for MPI (deploy toggle) 
- Update the status of the notification based on data not available from MPI
- Persist VA identifiers in separate table
- Update User Flows
- API documentation: [https://ps.dev.iam.va.gov/iam/mpi/fhir/r4/index.html#patient-read](https://ps.dev.iam.va.gov/iam/mpi/fhir/r4/index.html#patient-read)

# Out of Scope:
- Large volumes, batch
- Basic validation of the IDs

# Open Questions:
- ~How many unique identifiers would we send to MPI?~ For now we would only accept PID and ICN
- What are the status responses from MPI? (example - identifier not found)
- ~Certain identifier may not have a specific format - this needs to be validated in Dev Analysis~ Out of scope

**Comment by ffafara-tw** [comment]
Some of MPI supported identifiers and their forms:

Fully Qualified IDs
Sample Unique Identifiers:
- ICN Id
```<id root="2.16.840.1.113883.4.349" extension="1008533405V377263^NI^200M^USVHA"/> OR 
<id root="2.16.840.1.113883.4.349" extension="1008533405V377263^NI”/>```

- VA IAM Provisioning Security ID (SecId)
```<id root="2.16.840.1.113883.4.349" extension="1000020007^PN^200PROV^USDVA"/>```

- DoD EDIPI Id
```<id root="2.16.840.1.113883.3.42.10001.100001.12" extension="1234567890^NI^200DOD^USDOD"/>```

- CORP Id
```<id root="2.16.840.1.113883.4.349" extension="123456^PI^200CORP^USVBA "/>```

- BIRLS Id
```<id root="2.16.840.1.113883.4.349" extension="123456^PI^200BRLS^USVBA "/>```

- MHV User Id
```<id root="2.16.840.1.113883.4.349" extension="123456^PI^200MHV^USVHA"/>```

- VHIC Card Id
```<id root="2.16.840.1.113883.4.349" extension="123456^PI^742V1^USVHA"/>```

- VHA correlated systems Id
```<id root="2.16.840.1.113883.4.349" extension="123456^PI^station#OfVHASystem^USVHA"/>```

- PIV Id
```<id root="2.16.840.1.113883.4.349" extension="1234567890^EI^200PIV^USDVA"/>```

- VA AD
```<id root="2.16.840.1.113883.4.349" extension="1234567890^EI^200AD^USDVA"/>```

 - NwHIN ID
```<id root="2.16.840.1.113883.4.349" extension="MC23265000^NI^200NWS^1.2.840.114350.1.13.60.3.7.3.688884.100^A"/>```

 - CP&E Beneficiary ID
```<id root="2.16.840.1.113883.4.349" extension="12345-1^PI^741^USVHA^A"/>```

- CP&E Sponsor ID
```<id root="2.16.840.1.113883.4.349" extension="12345^PI^741^USVHA^A"/>```

- Cerner ID
```<id root="2.16.840.1.113883.4.349" extension="12345^PI^200CRNR^USVHA^A"/>```

- CMS National Provider Index (NPI) ID
```<id root="2.16.840.1.113883.4.6" extension="12345^NI^200ENPI^USDVA^A"/>```

- ID.ME
```<id root="2.16.840.1.113883.4.349" extension="12345^PN^200IDME^USDVA^A"/>```

- USAccess PIV
```<id root="2.16.840.1.113883.4.349" extension="12345^EI^200PUSA^USDVA^A"/>```

- USA Staffing
```<id root="2.16.840.1.113883.4.349" extension="12345^EI^200USTF^USDVA^A"/>```

- VA Salesforce
```<id root="2.16.840.1.113883.4.349" extension="12345^PI^200DSLF^USDVA^A"/>```

**Comment by ffafara-tw** [comment]
Need to take a look at scheduled task replay_created_notifications that runs every 15 minutes and moves notifications with CREATED status to a delivery queue (SEND_SMS, SEND_EMAIL)
