### ISSUE TITLE
Update Swagger and Postman for the new callback property in POST/GET notifications

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#2000]
## User Story - Business Need

As part of the VA's Zero Silent Failure Initiative (see [epic](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/1391)), we need to update the OpenAPI spec and Postman collections to add in a new property to POST v2/notifications/<email|sms>payloads for a callback URL and the GET v2/notifications/:notification_id response so that our clients can be aware of this property.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   business line
**I want** to have documentation as to the new callback payload
**So that** I can make use of it to have zero silent failures.

### Additional Info and Resources

- Callback property name TBD.
- It could be nice to include in swagger a description if a callback URL added to the POST payload, it overrides any service level callback. 

## Acceptance Criteria

- [x] [OpenAPI](https://github.com/department-of-veterans-affairs/notification-api/blob/main/documents/openapi/openapi.yaml) is updated for POST v2/notifications/email to include the new callback property in and that it is an optional string in the schema, examples, and responses. 
- [x] [OpenAPI](https://github.com/department-of-veterans-affairs/notification-api/blob/main/documents/openapi/openapi.yaml) is updated for POST v2/notifications/sms to include the new callback property in and that it is an optional string in the schema, examples, and responses. 
- [x] The two [Postman](https://github.com/department-of-veterans-affairs/notification-api/tree/main/documents/postman) collections (for internal developers and clients) are updated to include the new callback property in the POST v2/notifications/email and v2/notifications/sms payloads
- [ ] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations

- [x] QA to review and approve swagger changes
- [x] QA to use Postman to exercise the routes to ensure they work as expected

## Potential Dependencies

This work has dependencies on other tickets that have not been created at the time of this writing. Tickets will be linked as blockers at that time.

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2000?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by cris-oddball** [comment]
PR is up and in draft mode.

**Comment by cris-oddball** [comment]
This PR is code complete. Waiting for #2104 and #2012 to open the PR.

**Comment by cris-oddball** [comment]
Decided to open the PR now for review. It can be sent up the pipeline later.

**Comment by cris-oddball** [comment]
PR approved and merged.
