### ISSUE TITLE
Method to Generate Signature Based on Params and API Key

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2001]
## User Story - Business Need
We wish to enhance ENP by allowing a callback URL to be specified when a request is made to VA Notify's sms/email paths. We will generate a signature based on the parameters being sent to our client (Service). Adding that signature to the request is part of a separate ticket, this ticket is to create the `generate_callback_signature` method.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Service authorized to send notifications
**I want** to specify a callback url other than the service-level callback
**So that** we have more agency when deciding how to handle callbacks

### Additional Info and Resources

- [Digital Signature Algorithm](https://en.wikipedia.org/wiki/Digital_Signature_Algorithm)
- [Human-readable version](https://www.twilio.com/docs/usage/security#validating-requests)
- [Secure Hash Algorithms](https://en.wikipedia.org/wiki/Secure_Hash_Algorithms)

## Acceptance Criteria

- [x] TDD
- [x] `generate_callback_signature` method takes: ~`notification`~ `api_key_id` and `callback_params`
- [x] Return value of `generate_callback_signature` is a 64 character, url-safe string (use hexdigest, not digest)
- [x] Key of the signature is the actual secret of the API key (based on the `api_key_id` that was passed in)
- [x] signature and params are debug logged
- [x] Signature uses HMAC-SHA256 to support 32-bit systems e.g. `hmac.Hash(b'key', b'data', digestmod=hashlib.sha256)`
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2001?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by k-macmillan** [comment]
Realized that a Notification or notification_id is unnecessary. The signature itself does not care about that, it just takes data and signs it.

**Comment by k-macmillan** [comment]
PR merged. Updated slides.
