### ISSUE TITLE
BUG: C&P reporting: status and status_reason inconsistency

### ISSUE THREAD

**Issue by kbelikova-oddball** [department-of-veterans-affairs/notification-api#2011]
## Description

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

We noticed inconsistent behavior for `status` and `status_reason` in the latest Comp and Pen run (September 22nd). Most delivered messages had cleared previously set `status_reason`, while some kept it. Also failed messaged (`status: temporary_failure`) didn't include `status_reason` which would be beneficial to know. 
This inconsistency affects our reporting of delivered/undelivered notifications.

## Steps to Reproduce

Can't reproduce, but here is what it looks like in **BigQuery**:
 
template_name | status | status_reason | f0_
-- | -- | -- | --
VBA C&P Recurring Payment Notice | delivered |   | 32854
VBA C&P Recurring Payment Notice | _**temporary-failure**_ |   | 1
VBA C&P Recurring Payment Notice | permanent-failure | Phone number is invalid | 15
VBA C&P Recurring Payment Notice | _**delivered**_ | The veteran responded with STOP. | 2
VBA C&P Recurring Payment Notice | permanent-failure | No contact info found from VA Profile | 116
VBA C&P Recurring Payment Notice | permanent-failure | "ERROR: NonRetryableException - permanent failure, not retrying" | 164

## Impact/Urgency
This bug creates confusion on the real numbers of delivered messages by splitting away messages with not cleared status_reasons. It also "hides" the reason of the failed notifications. Need to be addressed for an accurate notification tracking.

## Expected Behavior

- [x]  If status is `delivered`, then clear status_reason
- [x]  If status is `temporary_failure`, then status reason is included when the Notification is updated
- [x]  If status is `permanent_failure`, then status reason is included when the Notification is updated
- [x]  Retroactively update notifications details (status_reason) from previous notification rounds (August and September)

## QA Considerations

- [x] Validate the AC

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2011?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by kalbfled** [comment]
The first thing that leaps out at me is that calls to `dao_update_notification_by_id` do not include a status reason.
```
.../notification-api$ grep -rn dao_update_notification_by_id app/
app/celery/process_delivery_status_result_tasks.py:8:    dao_update_notification_by_id,
app/celery/process_delivery_status_result_tasks.py:203:        dao_update_notification_by_id(
app/celery/process_pinpoint_receipt_tasks.py:15:    dao_update_notification_by_id,
app/celery/process_pinpoint_receipt_tasks.py:138:            dao_update_notification_by_id(
app/dao/notifications_dao.py:268:    return dao_update_notification_by_id(
app/dao/notifications_dao.py:331:def dao_update_notification_by_id(
```

**Comment by mjones-oddball** [comment]
```
SELECT
  template_name,
  status,
  status_reason,
  SUM(count)
FROM
  `vsp-analytics-and-insights.platform_vanotify.prod-statistics`
WHERE
  service_name = "VBA Compensation and Pension Benefits"
  AND date BETWEEN "2024-09-20"
  AND "2024-09-30"
GROUP BY
  template_name,
  status,
  status_reason
```

**Comment by kalbfled** [comment]
I anticipate finishing development work for this ticket today, but QA needs additional time.  For that reason, I marked this ticket as off-track.

**Comment by cris-oddball** [comment]
Some testing notes:
- With the new IIR work, we are not likely going to see "Phone number is invalid" coming back from providers because they will not even be sent, they will be caught by the V# VAProfile work.
- There have been some conditions with temporary-failure in which there is no status_reason. I'm not sure how to replicate them.
- We can test the Delivered having no status_reason by sending an sms via Postman to a mobile device and the recipient then sending STOP back. That 'opted-out' message should not make it back into the status_reason.
- We could hold this on an env overnight to see what BQ picks up, but since the BQ code didn't get modified, it will just report what is already in the notification object - the above test should be sufficient.

**Comment by kalbfled** [comment]
I sent myself SMS notification 8ae00c60-e061-45a4-b213-15c9cf9fcd80 using Dev and verified with Postman that the notification had the status "delivered" with a null status_reason.  Then I replied "STOP" with my phone and verified that the status and status_reason did not change for this notification.

Next, I tried using Postman to send myself a new SMS notification.  This created notification 2b834140-a41e-4f16-903d-e7498d700214, which has status "permanent-failure" and status_reason "ERROR: NonRetryableException - permanent failure, not retrying".

Finally, I replied "START", received an SMS stating that I will resume receiving messages, and used Postman to create SMS notification 277a4061-435d-468a-b7ba-259355675ea0.  I did not receive a new text message, the the notification has the "permanent-failure" status.

**Comment by cris-oddball** [comment]
PR approved and merged to main. Sending up the pipeline to validate on Perf.

**Comment by cris-oddball** [comment]
**QA TESTING IN PROGRESS**

As with every delivery status ticket, we do not have a setup to be able to force delivery status results to come in out of order. At best, I will replicate the test Dave performed above and then try a few temporary and permanent failures to ensure they have a status reason. There is a risk that -- as before -- something will be missed. I'll create a Spike to investigate a way to force out of order statuses.

- [ ] Opting out of a sent sms notification does not further update the 'delivered status'
- [ ] Forcing a permanent failure results in a status_reason being populated
- [ ] Forcing a temporary failure results in a status_reason being update.

**Comment by k-macmillan** [comment]
This issue still exists. 

This is a query checking October 20-23:
<img width="526" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZ4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7cd9a444b8776d3c93cb2f7fc1dbcb71536be54d/image.png" alt="image.png" />

`permanent-failure`, `temporary-failure`, `technical-failure` are still appearing without a `status_reason`.

**Comment by cris-oddball** [comment]
@k-macmillan I will need to know what errors didn't make it into the status_reason so that I can more thoroughly test this.

**Comment by k-macmillan** [comment]
@cris-oddball We're definitely going to need to have a call. I have taken a route similar to the Twilio changes to make it so there is always a status reason, but there was additional nested logic that could invalidate earlier logic.

Ticket update:
I knew what was wrong, but the fix was threading the needle through a plate of spaghetti.

I am rewriting all of it. This is going to take until Monday or Tuesday depending on how much I get pulled away.

**Comment by k-macmillan** [comment]
Made some really good progress on this today. Refactored `process_delivery_status` and `process_pinpoint_results` to be very similar in flow and they call common methods such as `get_notification_platform_status` and `sms_status_update`, using common formats for input/output. 

Was hit with circular imports and decided it should be overhauled too. Our code is getting littered with comments about circular imports. Moved all constants to a single file and that resolved a lot of the import errors. I may run isort before this is closed.

Most tests are passing still other than celery tests. That is expected because I have not remade them for the new code and flow.

**Comment by k-macmillan** [comment]
Refactor complete. Added over 100 tests. PR is ready for review.

**Comment by cris-oddball** [comment]
Received test bodies for a variety of delivery statuses from @mchlwellman to be able to manually validate this when it gets to perf.

**Comment by k-macmillan** [comment]
PR had some changes requested and suggestions. Made all the changes that made sense and commented on the ones that were not going to be changed. All tests passing. Put up for re-review.

**Comment by cris-oddball** [comment]
PR approved and merged, deploying to Perf to validate.

**Comment by cris-oddball** [comment]
**QA TESTING IN PROGRESS**

Dropping various payloads into the lambdas, I should expect corresponding lambda logs and celery logs with status and status_reason

- [ ] Twilio accepted translated to notification status: sending
- [ ] Twilio scheduled translated to notification status: sending
- [ ] Twilio queued translated to notification status: sending
- [ ] Twilio sending translated to notification status: sending
- [ ] Twilio sent translated to notification status: sent
- [ ] Twilio delivered translated to notification status: delivered
- [ ] Twilio undelivered translated to notification status: permanent-failure
- [ ] Twilio failed translated to notification status: technical-failure
- [ ] Twilio cancelled translated to notification status: technical-failure
- [ ] Twilio failed_status_and_error_code_30001 translated to notification status: technical-failure
- [ ] Twilio failed_status_and_error_code_30002 translated to notification status: permanent-failure
- [ ] Twilio failed_status_and_error_code_30003 translated to notification status: permanent-failure
- [ ] Twilio failed_status_and_error_code_30004 translated to notification status: permanent-failure
- [ ] Twilio failed_status_and_error_code_30005 translated to notification status: permanent-failure
- [ ] Twilio failed_status_and_error_code_30006 translated to notification status: permanent-failure
- [ ] Twilio failed_status_and_error_code_30007 translated to notification status: permanent-failure
- [ ] Twilio failed_status_and_error_code_30008 translated to notification status: technical-failure
- [ ] Twilio failed_status_and_error_code_30009 translated to notification status: technical-failure
- [ ] Twilio failed_status_and_error_code_30010 translated to notification status: technical-failure
- [ ] Twilio failed_status_and_invalid_error_code translated to notification status: technical-failure
- [ ] Twilio exception no status
- [ ] Twilio exception invalid status
- [ ] Pinpoint

**Comment by cris-oddball** [comment]
Waiting to talk to Kyle prior to sending to Prod and closing ticket.

**Comment by cris-oddball** [comment]
This has been sent to Prod.
