### ISSUE TITLE
Add Database Field for Callback URL

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2013]
## User Story - Business Need
We want to store the `callback_url` passed in any notification requests. This would be added to the `notifications` table.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Service using VA Notify
**I want** my request to use a particular webhook callback honored
**So that** we can process callbacks in a way that best fits our needs

### Additional Info and Resources

The field should follow [sqlalchemy 2.x format](https://docs.sqlalchemy.org/en/20/orm/declarative_styles.html#orm-explicit-declarative-base) e.g. `callback_url: Mapped[str] .......`

## Acceptance Criteria

- [x] New field is added to the `notifications` table with a field name of: `callback_url`
- [x] New field is nullable
- [x] New field uses 2.x format for declarative styles
- [x] Should accept up to 255 characters
- [x] Ensure downgrade works even if the table has data in the new column
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2013?planning-poker) with Zenhub @coreycarvalho @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by MackHalliday** [comment]
PR in https://github.com/department-of-veterans-affairs/notification-api/pull/2028
