### ISSUE TITLE
RevProxy 502s: Twilio MessageSid Lookup And Update

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2032]
## User Story - Business Need
Given that Twilio is reporting errors when attempting to reach us through the rev proxy we are not guaranteed to update delivery statuses. We should call Twilio's endpoint to update messages that have not been updated recently.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Service using Twilio
**I want** the status of my notification to be current
**So that** I know if my message was delivered or not

### Additional Info and Resources

- Twilio python [quickstart](https://www.twilio.com/docs/messaging/quickstart/python)
- Twilio python [package](https://pypi.org/project/twilio/)
- To retrieve a `MessageInstance` you can use the `fetch` method e.g. `client.messages.get(sid).fetch()`
- Any extra methods are fine, but the three in AC are the minimum
- [Logs with ELB warnings](https://vanotify.ddog-gov.com/logs?query=%40http.url%3A%22https%3A%2F%2Fapi.va.gov%3A443%2Fsms%2Fdeliverystatus%22%20status%3Awarn%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1727976189773&to_ts=1728580989773&live=true) on the `deliverystatus` route

## Acceptance Criteria

- [x] TDD
- [x] Three new methods in the `TwilioSMSClient` class
  - [x] Update a notification by message sid that supersedes any existing status
  - [x] Call Twilio for a particular MessageSid using the Twilio python package, returns a Twilio `MessageInstance` 
  - [x] `translate_delivery_status` broken into two methods - parsing (part of the existing method) and evaluating (new **private** method)
- [x] Data sent to the new evaluating method should be based on the existing translate logic, but simplified so it works for the new update method and the existing translation method (probably just want to pass it the parameters from each rather than a dictionary)
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations

At this time the update notification by message sid code will not be called, so the only QA consideration would be related to the translate method changes, trying to help make sure edge cases in the evaluation are accounted for.

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2032?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by cris-oddball** [comment]
@k-macmillan Do we have some evidence that this is currently happening, can that be added to this ticket.

**Comment by cris-oddball** [comment]
@cris-oddball identify any edge cases not handled by unit tests.
@mchlwellman can use the generic internal endpoint to call your code, fyi.

**Comment by mchlwellman** [comment]
I refactored the translate method first, added stubs for the message retrieving and notification updating, and am currently working on the tests. There's a few that have to be fixed and then new ones.

**Comment by cris-oddball** [comment]
This actually was sent up in the pipeline yesterday due to an error in where the tags are cut. Considering this closed in favor of testing on the next ticket - #2058
