### ISSUE TITLE
Implement Datadog APM for Celery

### ISSUE THREAD

**Issue by coreycarvalho** [department-of-veterans-affairs/notification-api#2041]
## User Story - Business Need

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

We currently have APM implemented for our API service, but not for our Celery service. This makes monitoring our Celery tasks difficult. Right now, we rely on log items with the word "error" in them, but they are categorized as "INFO" by Datadog. We'd like more robust observability here.

### User Story(ies)

**As a**  VA Notify Developer
**I want**  Datadog APM implemented for Celery
**So that** we can better observe and monitor our application.

### Additional Info and Resources

https://ddtrace.readthedocs.io/en/stable/integrations.html#celery

According to the ddtrace docs, we need to patch the datadog agent to look for Celery.

```
import celery
from ddtrace import patch

patch(celery=True)
app = celery.Celery()

@app.task
def my_task():
    pass

class MyTask(app.Task):
    def run(self):
        pass
```

The example above is from their docs, but we probably only need to run `patch(celery=True)` somewhere.

Datadog search to verify workers are shutting down correctly:
```
("Pool worker shutdown" OR "Main process worker graceful stop") -("ForkPoolWorker" OR "MainProcess") 
```
![Image](https://github.com/user-attachments/assets/9f311946-cf80-437a-9be2-6e0e8ae6dcae)

## Acceptance Criteria

- [x] Celery appears as its own service in Datadog's APM 
- [x] Celery workers and main process shut down correctly (see additional info)
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2041?planning-poker) with Zenhub @kalbfled

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2041?planning-poker) with Zenhub @cris-oddball

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2041?planning-poker) with Zenhub @MackHalliday

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2041?planning-poker) with Zenhub @EvanParish

**Comment by npmartin-oddball** [comment]
Still needed. Team to discuss when to pull in.

**Comment by MackHalliday** [comment]
Yesterday 
- Read DD docs and watch a couple Youtube video 
- Make small updates to code to get dd working with celery 
- Deployed and now seeing Celery in APM 

Today 
- Do we need any weeks to logging? 
- Address AC "Celery workers and main process shut down correctly (see additional info)"

**Comment by MackHalliday** [comment]
Relevant notes from @cris-oddball 

Cris Stoddard
  9:46 AM
Hey there, I have no idea if this will be helpful for you, but this is Lucas's PR when he added APM to the API and the [ticket](https://github.com/department-of-veterans-affairs/notification-api/issues/1122). He left copious notes after speaking with Datadog support. He added something to scripts/run_app.sh  - there is a comparable script for run_celery I think. Anyway, I know he encountered problems deploying, not sure if he left any notes in there as to how he overcame them.

Cris Stoddard
  9:50 AM
I also have this link in my notes from that time, https://github.com/DataDog/trace-examples/issues/114

**Comment by MackHalliday** [comment]
There seems to be an issue with the healthcheck script for the Celery ECS service (`scripts/check_celery.py`). 

If I delete this script - [the Celery tasks are captured as expected in DataDog. ](https://vanotify.ddog-gov.com/apm/services/celery/operations/celery.run/resources?dependencyMap=qson%3A%28data%3A%28telemetrySelection%3Aall_sources%29%2Cversion%3A%210%29&deployments=qson%3A%28data%3A%28hits%3A%28selected%3Aversion_count%29%2Cerrors%3A%28selected%3Aversion_count%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3A%215%29%2Cversion%3A%210%29&env=dev&fromUser=true&groupMapByOperation=null&infrastructure=qson%3A%28data%3A%28viewType%3Apods%29%2Cversion%3A%210%29&panels=qson%3A%28data%3A%28%29%2Cversion%3A%210%29&resources=qson%3A%28data%3A%28visible%3A%21t%2Chits%3A%28selected%3Atotal%29%2Cerrors%3A%28selected%3Atotal%29%2Clatency%3A%28selected%3Ap95%29%2CtopN%3Aall%29%2Cversion%3A%211%29&summary=qson%3A%28data%3A%28visible%3A%21t%2Cchanges%3A%28%29%2Cerrors%3A%28selected%3Acount%29%2Chits%3A%28selected%3Acount%29%2Clatency%3A%28selected%3Alatency%2Cslot%3A%28agg%3A95%29%2Cdistribution%3A%28isLogScale%3A%21f%29%2CshowTraceOutliers%3A%21t%29%2Csublayer%3A%28slot%3A%28layers%3Aservice%29%2Cselected%3Apercentage%29%2ClagMetrics%3A%28selectedMetric%3A%21s%2CselectedGroupBy%3A%21s%29%29%2Cversion%3A%211%29&start=1732140846751&end=1732141746751&paused=true). And [the ECS service deploys without issue. ](https://us-gov-west-1.console.amazonaws-us-gov.com/ecs/v2/clusters/dev-notification-cluster/services/dev-notification-celery-service/health?region=us-gov-west-1)


At this time, I do not know why the healthcheck is an issue.


I did have to bump the CPU for the Celery ECS from 1024 to 2048. At 2048 - CPU during deployment hits about 81 percent and memory is currently about 65 percent. 
  ![Image](https://github.com/user-attachments/assets/56ab2ba1-43d3-4515-9924-49f73ee88a59). 


Moving forward - I'll be focusing on the health check issue.

**Comment by MackHalliday** [comment]
## On the healthcheck issue

I think I understand why adding ddtrace fails healthchecks - So ddtrace is called before Celery now. Meaning in the process tree the parent of Celery is now ddtrace. 

During the healthcheck - we need to find the PID for the Celery process. However since we added ddtrace, we are searching in the wrong part of the 'tree'. If we update how we are finding Celery PIDs then the healthcheck might pass.

**Comment by MackHalliday** [comment]
## Notes from talking with Kyle 

1. Spend the end of today working on fixing the Health Check command. If not complete - go ahead and make a ticket. 
2. Go ahead and up the CPU for Celery ECS services in all environments 
3.  **FOCUS ON THIS FIRST** Still need to figure out why we are not seeing shut down commands. [See example of DataDog filters to view logs. ](https://vanotify.ddog-gov.com/logs?query=%28%22Pool%20worker%20shutdown%22%20OR%20%22Main%20process%20worker%20graceful%20stop%22%29%20-%28%22ForkPoolWorker%22%20OR%20%22MainProcess%22%29%20%40aws.awslogs.logGroup%3Adev-notification-api-log-group&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1732188071884&to_ts=1732202471884&live=true). Deploy code back to back - Confirm shutdown logs for first deploy. 
  SIGTERM - workers never receive SIGTERM. Forced celery PID to zero by using `exec`. Do we still need to use `exec`?

**Comment by MackHalliday** [comment]
Yesterday 
- Updated health check
- Deployed and tested ECS build and new health check
- Submitted PR 

Today 
- PR approve and merged. 
- Will be deployed to PROD today and I'll be monitor the ECS Celery service until EOD

**Comment by cris-oddball** [comment]
PR approved, merged and deployed. Hotfix also deployed to Prod to increase memory in Prod for celery tasks to ease the overhead. This will be closed out by EOD.

**Comment by MackHalliday** [comment]
Closing -  check CPU and Memory after deployed to production. 

Memory holding at 46%. CPU high but no high than normal.
