### ISSUE TITLE
Remove feature toggle for MPI

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#206]
# Value Statement:
**As** 
**I want to** 
**So that**

# Acceptance Criteria
**GIVEN** 
**WHEN** 
**THEN**

# Checklist:
- [ ] Checklist item here

# Assumptions:
-

# Additional Info/Resources:
-

# Out of Scope:
-

# Open Questions:
-

**Comment by miabecker** [comment]
No longer need to do this given technical approach.
