### ISSUE TITLE
BUG: Twilio Error Messages Retried

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#2070]
## Description

There are some notifications being sent to Twilio that receive a `TwilioRestException` response and they are being retried. These notifications will never succeed and should not be retried.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## Steps to Reproduce

1. Send a message through the system with >1600 characters
2. Observe retrying notification and "1600 character limit" message in the logs

## Impact/Urgency

We aren't seeing a lot of these messages, but when they do come through they are taking up some resources unnecessarily.

## Expected Behavior

- [x] When we attempt to send a Twilio message and receive an error code of 400, we should be setting that notification to permanent-failure and not retrying it.

## QA Considerations

- Send a message through the system with >1600 characters, expect Twilio to respond with a 400 and the notification status is set to permanent-failure with an appropriate status_reason .

## Additional Info & Resources

The actual error message is below, but the Error / Traceback can be found in the exc_info in Datadog.
```
SMS delivery for notification id: <id> failed
```

```
twilio.base.exceptions.TwilioRestException: HTTP 400 error: Unable to create record: The concatenated message body exceeds the 1600 character limit
```

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2070?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment]
Chris J. to pair with another dev.

**Comment by mchlwellman** [comment]
I have a PR ready to go for this, but it's on hold for a bit while I help sort out the glibc issues, #1337

**Comment by cris-oddball** [comment]
PR approved and merged, deploying to Perf for testing.

**Comment by cris-oddball** [comment]
**QA FAILED** 

The status_reason out of the GET route is 
```
"status": "permanent-failure",
"status_reason": "ERROR: NonRetryableException - permanent failure, not retrying",
```

It should be 'Message too long'.

The sms is correctly not being retried, 

> Notification: b79fa10a-3e45-436f-837b-d992f47cb9d5 has been updated to a permanent-failure with status_reason: ERROR: NonRetryableException - permanent failure, not retrying

So, will go ahead and send this up to Prod as it is, but putting this ticket back into In Progress so that the right status_reason is returned.

**Comment by cris-oddball** [comment]
2nd PR approved and merged, deployed to Perf.

**Comment by cris-oddball** [comment]
**QA PASSED**

- [ ] When sending an sms via Twilio that exceeds their 1600 character limit, the GET response indicates status permanent-failure and the status_reason Message too long, with a corresponding log stream.

GET response
```
    "status": "permanent-failure",
    "status_reason": "Message too long",
```

![Image](https://github.com/user-attachments/assets/493e33c9-6bc5-44c5-b567-68e4a807c1a5)

**Comment by cris-oddball** [comment]
Deploying to Prod and closing ticket.
