### ISSUE TITLE
Update API Documentation to Include Advanced Usage Section for Bulleted List

### ISSUE THREAD

**Issue by kbelikova-oddball** [department-of-veterans-affairs/notification-api#2082]
## User Story - Business Need

Recently we discovered that there is a possibility to provide a bulleted list via the API and to the template. This functionality has been documented on [UK.gov](https://docs.notifications.service.gov.uk/rest-api.html#email-reply-to-id-optional) resource but not in our documentation. We need to add documentation of this functionality and provide example of the usage for our clients.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**    VA Notify developer 
**I want**  have an appropriate documentation for our API   
**So that** our clients are aware of its capabilities

### Additional Info and Resources

Dynamic bulleted lists are done like so:
```
{
    "list_of_forms": ["form a", "form b"]
}
```
## Acceptance Criteria

- [x] openapi.yaml file is updated to include bulleted list functionality described [here](https://docs.notifications.service.gov.uk/rest-api.html#send-an-email-request-body)
- [x] bulleted list functionality example is visible in swagger's example section as "dynamic bulleted list"
- [x] possible location of updated information:
- [x] ![Image](https://github.com/user-attachments/assets/a6805236-7615-4705-91a9-b1cbc7ffa6fd)

- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## Out of Scope
Portal changes will be addressed by Experience team (Strike)

**Comment by MackHalliday** [comment]
### Notes from discussion with @cris-oddball 

- Look for section notification - only email
  - Add another header with explanation
  - Update example
- DO NOT UPDATE SMS EXAMPLES
- Update version 
- Can upload file into editor -  https://editor-next.swagger.io/
- UK Docs  - https://docs.notifications.service.gov.uk/rest-api.html#send-an-email
- Example
```
{
    "template_id": "{{email-template-id}}",
    "email_address": "mack.halliday@docme360.com",
    "personalisation": {
        "name" : "Mack",
        "adjective": ["one bullet", "two bullet", "three bullet"]
    }
}
```

**Comment by MackHalliday** [comment]
Today 
- Talked to Cris 
- Implemented update to swagger 

Tomorrow 
- Get approval from Cris and Ksenia 
- Submit PR

**Comment by MackHalliday** [comment]
![Image](https://github.com/user-attachments/assets/a6d3d99f-c185-46c7-ba19-6bdf2a7890bd)
![Image](https://github.com/user-attachments/assets/e551b6b1-6d24-447d-a869-c444c968cfbe)

**Comment by MackHalliday** [comment]
Updated design based on discussion in standup and submitting PR 
<img width="1025" alt="Image" src="https://github.com/user-attachments/assets/c2f1fbfd-d98b-49be-aca6-56a8286b19cb" />
<img width="1005" alt="Image" src="https://github.com/user-attachments/assets/8f798ed4-b669-4bd0-960c-8a446356703f" />

**Comment by cris-oddball** [comment]
PR approved and merged, QA reviewed the PR, PM reviewed the changes, deploying and closing ticket.
