### ISSUE TITLE
Remove approval to production in CD pipeline

### ISSUE THREAD

**Issue by coreycarvalho** [department-of-veterans-affairs/notification-api#2086]
## User Story - Business Need

With anomaly detection in place and our Docker image only being built once, we are ready to implement the final step in our CI/CD Pipeline Improvements epic. This ticket is calling for the removal of the approve to production step in our CD pipeline.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**    VA Notify developer
**I want**  to remove the approval to production step in our CD pipeline removed
**So that** we have a complete, automated CD pipeline.

### Additional Info and Resources

https://github.com/department-of-veterans-affairs/notification-api/blob/main/.github/workflows/cd-pipeline.yml#L104 -- removal of this block of code.

## Acceptance Criteria

- [ ] After a pipeline is approved to go to staging, it will deploy to staging and then production (sequentially)
- [ ] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by kbelikova-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2086?planning-poker) with Zenhub @coreycarvalho
