### ISSUE TITLE
Assign 10DLC number for iMedConsent (Staging)

### ISSUE THREAD

**Issue by kbelikova-oddball** [department-of-veterans-affairs/notification-api#2123]
## User Story - Business Need
Veterans Health Administration team, iMedConsent wants to collect Veterans consent for a medical treatment or a procedure by sending Veteran an SMS via VA Notify that would contain a link directing Veteran to a medical consent form where Veteran would submit their mobile signature.

To support this, we need to allocate a 10DLC number specifically for this SMS notification. We have 4 existing numbers in AWS, originally provisioned for VEText but currently unused, which should be repurposed for this team. 
This ticket is focused on assigning one of these numbers for use in iMedConsent’s staging environment.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**    iMedConsent  team member
**I want** to send Veterans an SMS when their medical procedure consent forms are ready
**So that** We can collect Veteran's consent/mobile signature for the procedure

**As a**    VA Notify engineer
**I want**  assign +12026188901 to iMedConsent's service  on staging
**So that** iMedConsent can send sms notifications from this dedicated number

### Additional Info and Resources

Ksenia will do the following in AWS Console:
- An opt-out list should be created for iMedConsent's notification, applicable to both staging and production environments.

## Acceptance Criteria

- [x]  is assigned to iMedConsent
- [x] Opt-out list is added to this number 
- [x] Create an SMS sender for +12026188901 number for **iMedConsent** service on staging
- Use the POST  `{{notification-api-url}}/service/{{service-id}}/sms-sender `create route to create the number; check to see what rate limit, if any, should be set in the payload.
- staging payload
```json
{
    "sms_sender": "+12026188901",
    "provider_id": "17c4e05b-25ec-4bac-a8f7-27075b27e23a",
    "description": "<check with @kbelikova-oddball  for what the description should be>",
    "is_default": true
}
```
- Verify with GET `{{notification-api-url}}/service/{{service-id}}/sms-sender` that the number was correctly created/updated
- [x] Since there is no PR for this ticket, validate work with Kyle/Ksenia
- [x] Share sms_sender_id with iMedConsent to use  to use on staging

- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by EvanParish** [comment]
I created the SMS Sender in Staging and will be sending the email to iMed contacts shortly.

For the description field I put `"iMed Primary Sender"`
