### ISSUE TITLE
Implement open rates for 526EZ confirmation

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#221]
# Value Statement:
**As a** VANotify stakeholder
**I want to** understand the open rates for notification emails
**So that** I can measure and evolve the performance of notifications  

# Acceptance Criteria

1.
**GIVEN** an email notification
**WHEN** the email is sent
**THEN** the html body contains a google tracking pixel with parametrized tags

2.
**GIVEN** an email notification has been delivered
**WHEN** the email is opened 
**THEN** the appropriate open rate data is visible in GA dashboard

# Checklist:
- [x] all the changes behind a feature flag
- [x] Image tag is in jinja template
- [x] Image tag has dynamic parameters based on template and notification id
- [x] The image src url should have all the elements mentioned in the comment
- [x] any new email message will contain the google analytics image in the html body
- [x] After opening the google analytics the email open rates should be visible

# Assumptions:
- Coordination and setup will be required with the analytics team

# Additional Info/Resources:
- This is the issue that was raised on [va.gov-team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15208) as directed on the slack channel 
- The decision was made to move forward with Google Pixel for tracking open rates for the 526EZ
- As a part of Dev Analysis we must create a list of tasks we need to coordinate with the analytics team 
- https://developers.google.com/analytics/devguides/collection/protocol/v1/email
- Coordinating with the analytics team to get all the required information for this card to be played/ready will be a part of Dev Analysis 

# Out of Scope:
- Plain text emails

# Open Questions:
- ~Does GDPR apply for this?~ Out of scope for this card
- What values are we using for pixel parameters: Mentioned in the comment also the issue on [va.gov team](https://github.com/department-of-veterans-affairs/va.gov-team/issues/15208)
- should we include campaign at all? Yes, it will help with the GA reports

```
URL Component	Explanation
v=1	Protocol version within Google Analytics
tid=UA-XXXXXX-X	Your Google Analytics Tracking ID
cid=555 for anonymous CLIENT_ID_NUMBER - A systematic tracking ID for the customer.
t=event	Tells Google Analytics this is an Event Hit Type
ec=email	The Event Category helps segment various events
ea=open	The Event Action helps specify exactly what happened
el=recipient_id	Event Label specifies a unique identification for this recipient
cs=newsletter	Campaign Source allows segmentation of campaign types
cm=email	Campaign Medium could segment social vs. email, etc.
cn=Campaign_Name	Campaign Name identifies the campaign to you

example : <img src="https://www.google-analytics.com/collect?v=1&tid=UA-01010-1&cid=555&aip=1&t=event&ec=email&ea=open&dp=%2Fform%2F526ez%2Femail&dt=<email subject>">
example un-scaped: <img src="https://www.google-analytics.com/collect?v=1&tid=UA-01010-1&cid=555&aip=1&t=event&ec=email&ea=open&dp=/vanotify/va.gov/va.gov/Form 526ez template&dt=<email subject>">
```
- We will have to specify different tracking depending on the environment? We will have to work with the analytics team to set this up.

**Comment by saman-moshafi-va** [comment]
These are the GA parameters and their values:
```
v=1
t=event
tid=UA-50123418-16
cid=<notification id>
aip=1
ec=email
ea=open
el=<template name>
dp=/email/vanotify/<organization name>/<service name>/<template name>
dt=<email subject>
cn=<template name>
cs=<notification api provider>
cm=email
ci=<template id>
```
example:
```
v=1
t=event
tid=UA-50123418-16
cid=894de4a5-4be3-441c-8d1c-76e054a7a5ff
aip=1
ec=email
ea=open
el=Form 526ez email confirmation
dp=/email/vanotify/va.gov/va.gov/Form 526ez email confirmation
dt=Weʼve received your application
cn=Form 526ez email confirmation
cs=gov-delivery
cm=email
ci=0c1335fc-ca67-408a-b2ae-08b91ffaceba
```

We need to modify the code so the required values are available.  The next comment will include the required changes.

**Comment by saman-moshafi-va** [comment]
### changes to notification utils:
* jinja template
* HTMLEmailTemplate
### changes to notification API:
* make sure the celery worked have all the required values before using HTMLEmailTemplate

When v2/notifications/email end point code has access to authenticated_service which is the service we need and can be used to get serice name. It also contains organisation_id and possibly organisation.  If organization is not loaded, then the organisation_id should be used to get the organization.
In celery worker the service is available when HTMLEmailTemplate is created.  HTMLEmailTemplate is the notification utils that uses jinja2 template to generate html and plan emails.
* <notification id> is the id of Notification object
* organization, service, template and names should be available form the Service object some DB queriers should fetch them
* <email subject> is already used to generate the email and is available in template object
* <notification api provider name> is available from Provider object which is determined before HTMLEmailTemplate is generated

**Comment by saman-moshafi-va** [comment]
tested on Friday 13, November 2020; tested with gmail, yahoo and outlook
[Analytics All Web Site Data - VA.gov Testing Environments Top Events 20201113-20201113.pdf](https://github.com/department-of-veterans-affairs/notification-api/files/5539155/Analytics.All.Web.Site.Data.-.VA.gov.Testing.Environments.Top.Events.20201113-20201113.pdf)
