### ISSUE TITLE
Implement VA.gov content changes for 526EZ notification

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#222]
# Value Statement:
**As** somebody completing a disability compensation application
**I want to** know to expect a confirmation email
**So that** I understand how my email address will be used
**And so that** I don't unnecessarily print out the confirmation page

# Acceptance Criteria
AC1. _Toggles enabled_
**GIVEN** the feature toggle `form526_confirmation_email` is enabled in `vets-api`
**AND GIVEN** the feature toggle `form526_confirmation_email_show_copy` is enabled in `vets-api`
**WHEN** I fill out a disability compensation application on VA.gov
**THEN** the content informs me that I will receive a confirmation email

AC2. _Toggles disabled_
**GIVEN** the feature toggle `form526_confirmation_email` is disabled in`vets-api`
**OR GIVEN** the feature toggle `form526_confirmation_email_show_copy` is disabled in `vets-api`
**WHEN** I fill out a disability compensation application on VA.gov
**THEN** the original content (which does not mention the confirmation email) is displayed 
 
# Checklist:
- [x] Add a new feature toggle in vets-api - `form526_confirmation_email_show_copy` [as described here](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/#add-feature). Configure it identically to `form526_confirmation_email`.
- [x] Read the feature toggle `form526_confirmation_email` from `vets-api` into `vets-website` - see [this documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/#add-feature), but skip to step 6:
```
6. Add the feature toggle name to vets-website by updating featureFlagNames.js.
```
- [x] If both toggles are enabled, use new copy in `vets-website`:
  - [x] Update the first paragraph of step 4 of 5 (Additional information) to, "This is the contact information we have on file for you. Please review it to make sure the information below is correct. We’ll send any important information about your disability claim to your mailing address. After you submit your claim, we’ll send you a confirmation email to your email address."
  - [x] Update the last paragraph of step 4 of 5 (Additional information) to, "Any updates you make here to your contact information will only apply to this application. If you want to update your contact information for all of your VA accounts, please [go to your profile page](https://www.va.gov/profile).
  - [x] Remove "Go to my profile" link below the text.
  - [x] Update the first line of the confirmation screen to, "**We'll send you an email to confirm that we received your claim. You can also print this page for your records**."
- [x] If either toggle is disabled, use the old copy

# Assumptions:
- We have permission to make changes to the [`vets-website`](https://github.com/department-of-veterans-affairs/vets-website) repository

# Additional Info/Resources:
- See [this documentation](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/platform/tools/feature-toggles/#add-feature) on using feature toggles in `vets-website`
- See attached screenshots ![application.png](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/977950eb-f275-4d15-a300-5cbc3ff0db95) and ![confirmation.png](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/cd125c69-93bb-411c-b7d0-9ac3b38cf9c1)
- Forms Library: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms

# Out of Scope:
-

# Open Questions:
- ~Should content be behind the feature toggle for the 526EZ email?~ - kind of - the toggle `form526_confirmation_email` will be enabled for a subset of users before this story is played, so we can't develop behind it. We should add a new toggle, and show the new copy if `form526_confirmation_email` AND the new toggle are enabled.

**Comment by philherbert** [comment]
Is this dependent on releasing the confirmation email feature to 100% of users? Or should this be behind the same toggle?

**Comment by marisahoenig** [comment]
Update:
- Managed to run `vets-website` and `vets-api` locally. I was running into an issue with logging in, which turned out to be a problem with me overwriting the `saml_ssoe` section in setting.local.yml. This should be removed/commented out so that the `idp_metadata_file` in settings.yml is `config/ssoe_idp_int_metadata_isam.xml`.
- Once I was able to log in with a user, I tried several different accounts, namely 228, 246, 248, 150, and 1. At least 228 definitely has an intent to file, as I tried on dev, but when running it locally, it says there is not enough info on the account to fill out this application. Also tried mocking the data with the `yarn mock-api` command in the `vets-website` readme and no luck.
- Decided to instead try testing by running the cypress tests and stopping them at the `Additional information` page. Even though my toggle is potentially turned on, I don't think I'm passing it in to the component correctly. Going to push that change so it's on the branch. (Branch on both repos, starting with notification-api#22)

**Comment by marisahoenig** [comment]
PRs:
- vets-website: https://github.com/department-of-veterans-affairs/vets-website/pull/14935
- vets-api: https://github.com/department-of-veterans-affairs/vets-api/pull/5220

**Comment by lingtran** [comment]
Status:
+ Add all three copies are added with conditional rendering based on feature toggles value
+ Pushed up to working vets-website branch
+ Note comment in description box regarding disabling linting error for in test file for contactInformation

To do:
+ need test for connected component of ConfirmationPage (had quickly tested the unwrapped component)
+ 3 integrated tests are broken that consume ConfirmationPage (`yarn test:unit` should return those failing tests)
+ please refactor! 

Rant:
- Linter is great, but it takes forever to run and so compounds dev time :(

**Comment by Mottie** [comment]
Hi! I'm from the Benefits and Memorial 1 team. We're responsible for this form. I was wondering if these content changes have been reviewed by any content editors? Our go to person is Peggy Gannon. I'll send her a link to this ticket.

**Comment by marisahoenig** [comment]
Hi @Mottie ! Yes, these changes have been reviewed. @toddstanich has been working with Peggy to approve these copy changes. 
cc @miabecker

**Comment by marisahoenig** [comment]
@toddstanich @miabecker 
Just to confirm, do you want the same copy displayed on the confirmation page regardless of submission status? With the way the copy was already set up, it said to "Please print this page for your records." whether it was successful or not.
<img width="689" alt="Screen Shot 2020-11-20 at 4 09 06 PM" src="https://user-images.githubusercontent.com/13212345/99850417-55629e00-2b4b-11eb-9084-d0dbe54539ab.png">

**Comment by toddstanich** [comment]
@marisahoenig does the email still send eventually in this case? And prior to our changes, did the "Please print this page.." text still display in this scenario?

**Comment by marisahoenig** [comment]
@toddstanich Yes x2, it still sends eventually and always sent the "Please print this page for your records."

**Comment by toddstanich** [comment]
@marisahoenig I think we're good as is then. Thanks!

**Comment by marisahoenig** [comment]
@toddstanich We are looking further at the different error cases that occur, and when an alert says "We’re sorry. Something went wrong when we tried to submit your claim", the email does not get sent because an error occurred but the old copy is rendered regardless of the error status. Do we still want the new copy displayed in this case?

**Comment by toddstanich** [comment]
@marisahoenig Good catch. No, we should not display the content mentioning an email if the email will not be sent.

**Comment by marisahoenig** [comment]
Desk checked & tested/reviewed with @jsmithVA ! Moving to sign off
