### ISSUE TITLE
Deploy vets-api to update Personalization

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#224]
# Value Statement:
**As a** developer working with VANotify  
**I want to** utilize the US spelling for Personalization 
**So that** I have an enhanced developer experience 

# Acceptance Criteria
1. _vets-api_
**GIVEN** I am working with vets-api 
**WHEN** I review the use of Personalization with VANotify
**THEN** I view the updated US spelling for Personalization

# Checklist:
- [ ] Update the necessary changes to the forked ruby client

# Assumptions:
- Update the applicable Unit Tests

# Additional Info/Resources:
-

# Out of Scope:
-

# Open Questions:
-

**Comment by npmartin-oddball** [comment]
V2 personalization stuck as-is. Closing.
