### ISSUE TITLE
Replace "set-env" in Github Actions

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#227]
# Value Statement:
**As** a cool developer on VANotify
**I want to** replace deprecated and uncool Github Actions utilities
**So that** I can avoid security vulnerabilities in my workflows and keep everyone happy and cool

# Acceptance Criteria
**WHEN** each of the VANotify Github Actions workflows run
**THEN** none of those workflows use `set-env` to share variables between jobs/steps

# Checklist:
Replace `set-env` with [Environment Files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files) in the following files :
- [x] `tag_git_dev.sh`
- [x] `tag_git_staging.sh`
- [x] `dev-ci.yaml`
- [x] `daily-email-ci.yaml`

# Additional Info/Resources:
- [Context re: deprecation of `set-env`](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/)

**Comment by ffafara-tw** [comment]
The tagging scripts were refactored to use outputs as part of #150
We refactored daily-email-ci and tw-deployment workflows to use one step instead of multiple, which eliminated the need to set environment variables between steps

**Comment by jsmithVA** [comment]
Successful run of daily email pipeline:(https://github.com/department-of-veterans-affairs/notification-api/actions/runs/368888068)
