### ISSUE TITLE
Run User Flows in VAEC

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/notification-api#228]
# Value Statement
In VAEC, we cannot hit our api endpoints. Instead, we need to call the user flow tests from a different system (Lambda) to make sure our endpoints are healthy.

# Acceptance Criteria
**GIVEN** our api is deployed to VAEC dev
**WHEN** deployment job finishes 
**THEN** the user flow tests run as part of deployment workflow to verify the deployment
**AND** deployment status depends on the test results.

**GIVEN** the user flow tests are triggered
**WHEN** the user flow tests fail
**THEN** the deployment status is failed
**AND** the tagging workflow **is not** executed

**GIVEN** the user flow tests are triggered
**WHEN** the user flow tests succeed
**THEN** the deployment status is success
**AND** the tagging workflow **is** executed

**GIVEN** the user flows code
**WHEN** it changes
**THEN** the Lambda workflow updates the Lambda definition

# Checklist
- [x] separate pipeline to create and update the Lambda - executed based on path (if that code changes) (`push` feature in Github actions)
     - [x] exclude path from rebuilding entire docker image -- not listing this path. Cannot use both paths and paths-ignore for the same event in a workflow
- [x] run the tests after VAEC deployment, calling Lambda with AWS CLI command (fail pipeline if fail, succeed otherwise)
- [x] terraform for lambda function
- [x] automate the zipping (maybe by terraform?)
- [x] Set up the following in the `vanotify-infra` repo - terraform
    - [x] new IAM role
    - [x] new security group
    - [x] set up logs - cloudwatch groups
- [x] pass in secrets referencing param store (pass name of env and then lambda retrieve secret using boto?)

# Assumptions:
-

# Additional Info/Resources
- Refer to spike #179 and branch `179-ecs-lambda-spike` for our test implementation
- Refer to [ADR 7: User Flow Testing in VAEC](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/documents/adr/0007-user-flow-testing-in-vaec.md) for reasoning for choosing Lambda

# Out of Scope
-

# Open Questions
- How do we structure terraform code? (We don't want multiple roles across environments or multiple Lambdas- just one)

**Comment by lingtran** [comment]
Status update EOD: Made progress in deploying dummy user flows lambda function to VAEC via Build Lambda Functions workflow. Want to migrate the code to vanotify-infra repo as part of utility infrastructure stack.

**Comment by lingtran** [comment]
Currently user flows lambda function only gets invoked during the dev env deployment because we are assuming a dev env role for the lambda resource, which has created a circular dependency between dev and staging for when we want to decrypt keys. The way to resolve this is to create a utility role that can be assumed to build the lambda resources. There is capability to create environment specific lambda resources, just currently given the circular dependency only dev env is defined.
