### ISSUE TITLE
Move DataDog Dashboards to Terraform

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/notification-api#230]
# Value Statement
When we created dashboards in #159, we decided to use the DataDog UI. This card includes the work to move the dashboard metrics (statsd for now, but maybe more by the time this card is implemented?) to terraform inside our `notification-api` repo.

# Acceptance Criteria
**GIVEN** 
**WHEN** 
**THEN**

# Checklist
- [ ] Checklist item here

# Assumptions
-

# Additional Info/Resources
- [Terraform DataDog Provider overview](https://registry.terraform.io/providers/DataDog/datadog/latest/docs)

# Out of Scope
-

# Open Questions
-

**Comment by miabecker** [comment]
Duplicate to #134
