### ISSUE TITLE
Utilize Terraform to create or update Datadog dashboards 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#234]
# Value Statement
**As** VANotify developer
**I want to** utilize Terraform for creating dashboards  
**So that** I have insights on my application metrics in Datadog

# Acceptance Criteria
**GIVEN** I am creating a Datadog dashboard
**WHEN** I run Terraform
**THEN** the appropriate dashboard is created

# Checklist
- [ ] Make sure everything that was manually created and we want to keep is here.

# Assumptions
-

# Additional Info/Resources
- The Terraform for Datadog documentation is at https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/dashboard.  
- The fastest method is to use Datadog to export the dashboard and then create the terraform file using the json file.

# Out of Scope
-

# Open Questions
-

**Comment by miabecker** [comment]
@ffafara-tw do we still think this is an issue? Just checking in as I go through the backlog with Qaysar.

**Comment by ffafara-tw** [comment]
Yes it is something we still want to do.
I believe Phil is doing some work around creating DataDog resources (graphs, alerts, dashboard) via terraform as part of his current story. So depending on how far he gets we might cancel this in the future.

**Comment by philherbert** [comment]
Closing this because the work has been done -

[Here is a list](https://app.datadoghq.com/dashboard/lists/manual/157058) of Datadog dashboards created by Terraform
