### ISSUE TITLE
Query API for Recipient Identifiers

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/notification-api#239]
# Value Statement
**As** a VANotify consumer
**I want to** know what VA identifiers are associated with a notification
**So that** I know how the notification was created 

_(is this also so we know the notification's status of querying VA Profile or another system?)_ - _not really - if we want that behaviour, that should probably be expressed through the `status` field_

# Acceptance Criteria

AC1. _Recipient identifiers? Comin' right up!_
**GIVEN** I have made a request to send a notification
**AND GIVEN** I specified a `recipient_identifier`
**WHEN** I make a request to query the status and details of that notification
**THEN** the response includes a `recipient_identifiers` list, containing all identifiers associated with that notification
e.g.
```
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "template": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "uri": "string",
    "version": 0
  },
  "type": "email",
  "recipient_identifiers": [
    {
      "id_type": "PID",
      "id_value": "foo"
    },
    {
      "id_type": "VAPROFILEID",
      "id_value": "bar"
    }
  ]
}
```

AC2. _Recipient identifiers? We're fresh out, I'm afraid_
**GIVEN** I have made a request to send a notification
**AND GIVEN** I did not specify a `recipient_identifier`
**WHEN** I make a request to query the status and details of that notification
**THEN** the response includes an empty `recipient_identifiers` list

```
{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "template": {
    "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
    "uri": "string",
    "version": 0
  },
  "type": "email",
  "recipient_identifiers": []
}
```

# Checklist
- [x] Modify `GET v2/notifications/<id>` endpoint to return `recipient_identifiers` in response:
  - [x] Update `models.Notification.serialize()` to include `recipient_identifiers` if the notification has associated identifiers - see `scheduled_for` for a similar example
- [x] Update OpenAPI documentation
- [ ] ~Add to user flows~ - not doing this, because we currently don't have a user flow test for the recipient identifiers path - we can create one once we have more of a complete flow with VA Profile and MPI

# Assumptions
- API can accept VA Identifiers #190 is complete

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
- ~Do we want to return the `value` for each `recipient_identifier`? Would this be PII?~ - yes, we want to return the value, and it's not PII
- ~Should we return all identifiers associated with this notification?~ - yes, so we can get a full picture of the data used to create and send a notification

**Comment by philherbert** [comment]
Sending a notification with a recipient identifier

<img width="1616" alt="Screenshot 2020-11-09 at 14 33 36" src="https://user-images.githubusercontent.com/9078954/98587937-e195db00-2298-11eb-875f-edfe5fc79ecb.png">

Retrieving its recipient identifiers

<img width="1616" alt="Screenshot 2020-11-09 at 14 33 49" src="https://user-images.githubusercontent.com/9078954/98587968-ef4b6080-2298-11eb-8924-04fedc44c8ab.png">
