### ISSUE TITLE
Remove Feature Toggles for 526EZ 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#248]
# Value Statement
**As a** VANotify admin 
**I want to** remove all the feature toggles for the 526EZ notification
**So that** all the traffic is routed when the 526EZ notification implementation is complete

# Acceptance Criteria
1. _526EZ email toggle_ 
**GIVEN** the 526EZ email toggle is removed
**WHEN** a Veteran submits the 526EZ application
**THEN** the 526EZ notification email is sent 

2. _526EZ email content toggle_ 
**GIVEN** the 526EZ email content toggle is removed
**WHEN** a Veteran is in the process of submitting or has submitted the 526EZ application
**THEN** the respective 526EZ email content displays

# Checklist
- [ ] Checklist item here

# Assumptions
- Changes will apply to Production 
- Team will need to test and monitor changes after the toggle is removed in Prod to confirm the 526EZ notification experience

# Additional Info/Resources
- Toggles: `GOVDELIVERY_EMAIL_CLIENT_ENABLED` and `GOOGLE_ANALYTICS_ENABLED` in `notification_api`, `form526_confirmation_email` and `form526_confirmation_email_copy` in `vets-api` and `vets-website`
- The #222 added the feature toggles 

# Out of Scope
-

# Open Questions
- Decision on when must this card be played must be discussed during kickoff

**Comment by miabecker** [comment]
This is about the capability to remove the feature toggle but not removing it permanently right? @QaysarA

**Comment by miabecker** [comment]
create a new label for post-release activities

**Comment by marisahoenig** [comment]
Note: With the work from #222, if the toggle is removed, we also need to remove its usage in `vets-website` and discuss the use of the `form526_confirmation_email_show_copy` toggle too.

**Comment by lingtran** [comment]
Associated feature toggle card #222: https://app.zenhub.com/workspaces/vanotify-5ea0ae59b51ccc3c83a8b65b/issues/department-of-veterans-affairs/notification-api/222

**Comment by saman-moshafi-va** [comment]
This is the out put after removing the feature toggles, from vets-api and vets-website
![image](https://user-images.githubusercontent.com/56931061/116107588-2a8fef00-a681-11eb-8a19-4628e0fb9c11.png)

**Comment by TWs-DevenS** [comment]
Reviewed the fix, scrn shot has been attached
