### ISSUE TITLE
[SPIKE] Opt Out for pharmacy notification

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#249]
# Goal

Step one is using AWS Opt Out default functionality and get information when opt out happens and passing it back to VEText. 

# Checklist
- [ ] 

**Timebox** - 5 days 

# Assumptions
- Pinpoint is approved and available for utilization
- AWS Opt Out Functionality is account wide i.e. if someone opts out from one number it opts them from all numbers related to the account
- 

# Additional Info/Resources
- The next step would be to not use AWS Opt Out default functionality, process opt outs ourselves and store in VA Profile. 

# Out of Scope
- Implementation with the opt out is covered in a different card #250 
- Sending opt out data to any external systems (example - VA Profile) 

# Open Questions
-

**Comment by miabecker** [comment]
Short term store "opt-outs" in Vettext, long term save into VA Profile.

**Comment by ffafara-tw** [comment]
"When a recipient sends the keyword "STOP" to one of your long codes, Amazon Pinpoint automatically opts that recipient out of all future SMS messages that are sent from this project."

**Comment by ffafara-tw** [comment]
Regarding opt-ins:
https://support.twilio.com/hc/en-us/articles/223134707-Industry-Standards-for-opt-ins-for-US-Short-Codes

Seems that when using short codes, the customer has to explicitly opt-in to the communication.
We have to follow TCPA law and CTIA guidelines. I have uploaded CTIA handbook to our google drive.

**Comment by miabecker** [comment]
Was just reading these guidelines today! Yes agree on opt in... will do a bit more researching too. 


thought with care
written with haste
reading up to you

**Comment by ffafara-tw** [comment]
During opt in process we have to:
- Receive consent before any message can be sent.
- Mention your company name
- Give the coupon or value proposition
- Mention the frequency of messages that will be sent monthly
- Disclose possible carrier costs and fees
- Give an option to ask for help and opt out of future texts
