### ISSUE TITLE
Support Birls ID (FileNumber) as Recipient Identifier

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#253]
# Value Statement

As a DMC / Debt Management Center representative 
I want to identify Veterans using a BIRLS ID (Beneficiary Identification Records Locator System ID AKA File Number)
So that I can send debt notifications to Veterans

# Acceptance Criteria
**GIVEN** 
An email notification request
**WHEN** 
When I use/pass BIRLS ID as a recipient identifier 
**THEN**
 this Veteran's email is extracted from VA Profile
**AND**
An email is sent to them.

# Checklist
- [x] Add BIRLS ID to identifier type enum
- [x] Add FHIR Transformation for BIRLS ID
- [x] Update open api document

# Assumptions

+ BIRLS ID is the primary unique identifier for DMC
+ Veteran has BIRLS ID 
+ Utilizing existing flow of extracting VA Profile ID from MPI and then extracting contact information from VA Profile

# Additional Info/Resources

FHIR Format: 123456^PI^200BRLS^USVBA

# Out of Scope
- Failures such as the below are being covered in MPI and VA Profile Integration work:
+ MPI doesn't have BIRLS ID
+ VA Profile doesn't have contact information

**GIVEN** 
A text notification request
**WHEN** 
When I use/pass BIRLS ID as a recipient identifier
**THEN**
a Veteran's phone number is extracted from VA Profile
**AND**
A text is sent to them.

# Open Questions
- How can we test end to end, which BIRLS ID values can we use on which environment?

**Comment by saman-moshafi-va** [comment]
These values will have BIRL ids in DEV:
1008788718V759106
1008794780V325793
1008710501V455565
1008843368V268268
