### ISSUE TITLE
Terraform Tech Tasks

### ISSUE THREAD

**Issue by marisahoenig** [department-of-veterans-affairs/notification-api#26]
Checklist:
- [x] Refactor main.tf into multiple files that make sense organization-wise
- [x] Make sure all resource names use underscores, not hyphens: https://www.terraform-best-practices.com/naming
- [ ] Possibly implement modules instead of individual resources
- [ ] Add terraform tests to CI pipeline
- [ ] only allow AWS terraform user to run terraform apply
- [x] split terraform apply stage to terraform plan (with plan output), then terraform apply
- [x] standardize naming to "notification"

**Comment by miabecker** [comment]
Closing as most tasks are complete and creating new cards to capture the remaining task: Add terraform tests to CI pipeline @miabecker
