### ISSUE TITLE
Receive delivery statuses back from Pinpoint

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#273]
# Value Statement

**As** a VANotify customer when I use the VANotify platform to send a text message
**I want to** know whether or not my text message was successfully delivered
**So that** I know if the Veteran has received the text message

**As** a VANotify customer when I use the VANotify platform to send a text message 
**I want to** know whether or not my text message was successfully delivered
**So that** I can build and trigger workflows depending on the status

# Acceptance Criteria

**GIVEN** a text message request is made
**WHEN** it is sent via Pinpoint
**THEN** the notification status within VANotify is updated as "sending"

**GIVEN** a text message is sent via Pinpoint 
**WHEN** an SMS event is received 
**THEN** the notification status within VANotify will be updated to the appropriate mapped status

**GIVEN** VANotify receives a status from Pinpoint that VANotify considers to be final
**WHEN** a service has a webhook defined
**THEN** then VANotify calls back the webhook communicating the final status

**Given** a text message is sent via Pinpoint and VANotify receives a status update
**When** -the status type is transient- there is a status type
**Then** we log and count how many of each type are occurring

# Checklist
- [x] Understand Pinpoint statuses
- [x] Map statuses
- [x] StatsD
- [x] Take a look at the Canadian codebase 
- [x] make sure research mode will function as expected
- [x] modify user flows as the final state in happy path should be delivered

#Infra: 

- [x] Set up Kinesis Stream for each Point project (environment) using Terraform 
- [x] set up the lambda code to read from the kinesis stream and places message on SQS

# Assumptions
- Pinpoint uses Kinesis Stream for their events in which are the text message statuses

# Additional Info/Resources
- https://docs.aws.amazon.com/pinpoint/latest/developerguide/event-streams-data-sms.html 
- Diagrams for Pinpoint event types, record statuses, and relationship to our notification statuses: https://app.mural.co/t/thoughtworksclientprojects1205/m/thoughtworksclientprojects1205/1614960868244/f67d1277a121858441e31741a77b64cf7f7054b8

# Out of Scope
- Re-trying on transient Pinpoint statuses i.e. unreachable, carrier unreachable, TTL expired

# Open Questions

-  How do we map to Pinpoint status our statuses? 
-  How will we pass statuses from Kinesis Stream events to VANotify:
     - Lambda to VANotify API endpoint
     - Lambda to SQS (processed by Celery) - this is most likely the solution that makes the most sense.
     - VANotify to use Kinesis SDK to consume stream directly
     - Use Lambda itself to modify the database and update notification status - which would require Lambda having our application context

SUCCESSFUL – The message was accepted by the carrier.
DELIVERED – The message was delivered to the recipient’s device.
SPENDING – The message hasn’t yet been delivered to the recipient’s device.
INVALID – The destination phone number is invalid.
UNREACHABLE – The recipient’s device is currently unreachable or unavailable. For example, the device might be powered off or might be disconnected from the network. You can try to send the message again later.
UNKNOWN – An error occurred that prevented the delivery of the message. This error is usually transient, and you can attempt to send the message again later.
BLOCKED – The recipient’s device is blocking SMS messages from the origination number.
CARRIER_UNREACHABLE – An issue with the mobile network of the recipient prevented the message from being delivered. This error is usually transient, and you can attempt to send the message again later.
SPAM – The recipient’s mobile carrier identified the contents of the message as spam and blocked delivery of the message.
INVALID_MESSAGE – The body of the SMS message is invalid and can’t be delivered.
CARRIER_BLOCKED – The recipient’s carrier has blocked the delivery of this message. This often occurs when the carrier identifies the contents of the message as unsolicited or malicious.
TTL_EXPIRED – The SMS message couldn’t be delivered within a certain time frame. This error is usually transient, and you can attempt to send the message again later.
MAX_PRICE_EXCEEDED – Sending the message would have resulted in a charge that exceeded the monthly SMS spending quota for your account. You can request an increase to this quota by completing the procedure in Requesting increases to your monthly SMS spending quota in the Amazon Pinpoint User Guide.

VANotify Statuses:

NOTIFICATION_STATUS_TYPES_FAILED = [
    NOTIFICATION_TECHNICAL_FAILURE,
    NOTIFICATION_TEMPORARY_FAILURE,
    NOTIFICATION_PERMANENT_FAILURE,
    NOTIFICATION_VALIDATION_FAILED,
    NOTIFICATION_VIRUS_SCAN_FAILED,
    NOTIFICATION_RETURNED_LETTER,
    NOTIFICATION_CONTAINS_PII
]
NOTIFICATION_STATUS_TYPES_COMPLETED = [
    NOTIFICATION_SENT,
    NOTIFICATION_DELIVERED,
    NOTIFICATION_FAILED,
    NOTIFICATION_TECHNICAL_FAILURE,
    NOTIFICATION_TEMPORARY_FAILURE,
    NOTIFICATION_PERMANENT_FAILURE,
    NOTIFICATION_RETURNED_LETTER,
    NOTIFICATION_CANCELLED,
]

**Comment by lingtran** [comment]
Created pinpoint kinesis resource during mob programming on Feb. 22, 2021.

**Comment by philherbert** [comment]
Example of a lambda that processes kinesis events: https://docs.aws.amazon.com/lambda/latest/dg/with-kinesis-create-package.html#with-kinesis-example-deployment-pkg-python

Example of an event from pinpoint: https://docs.aws.amazon.com/pinpoint/latest/developerguide/event-streams-data-sms.html

**Comment by miabecker** [comment]
@TWs-DevenS how else if at all do we want to test this card and move it through QA? Thanks!

**Comment by emilywu-tw** [comment]
Filip and I walked through the ACs and showed Deven the code/tests/graphs that correspond with the AC.

Comments for each AC to follow.

**Comment by emilywu-tw** [comment]
AC1: we showed Deven the code and unit/integration tests that do this. here's a screenshot demonstrating the desired behavior in dev:


https://user-images.githubusercontent.com/34494609/112375780-13449700-8cba-11eb-8895-8936e80ae02d.mov

**Comment by emilywu-tw** [comment]
@TWs-DevenS let me know if there are any other screenshots I need to include!

**Comment by emilywu-tw** [comment]
proof of infra set up

Pinpoint -> Kinesis connection
<img width="1065" alt="Screen Shot 2021-03-24 at 4 11 31 PM" src="https://user-images.githubusercontent.com/34494609/112377222-d7123600-8cbb-11eb-8267-5dff518ce082.png">

Kinesis -> lambda connection
<img width="1480" alt="Screen Shot 2021-03-24 at 4 12 33 PM" src="https://user-images.githubusercontent.com/34494609/112377282-ed1ff680-8cbb-11eb-8c6f-c720dfe2bec9.png">

**Comment by TWs-DevenS** [comment]
Reviewed all acceptance criteria (AC)
The Unit/Integration level tests address AC's sufficiently
(as demonstrated in the Screen shots above)
Moving ticket to SIgnoff

**Comment by miabecker** [comment]
Need to make sure its enabled in prod in sign off @miabecker
