### ISSUE TITLE
Use Case: Capturing COVID Vaccination Interest 

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#279]
# Value Statement
**As** a Veteran
**I want to** receive a confirmation email after I expressed interest in receiving information about the COVID vaccination process at the VA
**So that**I know my interest has been captured by the VA

# Acceptance Criteria
**GIVEN** a veteran is on the VA.gov website
**WHEN** they fill out the "Stay informed and help us prepare" COVID vaccination interest form
**THEN** they will receive a confirmation email letting them know their interest has been captured

# Checklist
- [x] Create a template ID for COVID Vaccination Interest Form Confirmation 
- [x] Share API documentation with Patrick V
- [x] Work with Business Line to Finalize Content
- [x] Prepare our environment for load testing

# Assumptions
- This is apart of VA.gov and VetsAPI
- VeText will be helping drive traffic to form / website

# Additional Info/Resources
- staging.va.gov/health-care/covid-19-vaccine/stay-informed

# Out of Scope
- Two-way communication with Veteran
- Updating Veterans on the VA's COVID response / Vaccine status

# Open Questions
- Finalizing content
- Volume 
- Funding

**Comment by ffafara-tw** [comment]
Creating following template in staging:
```
id: "9fd3fd52-5205-4fd1-bd98-1ddbef54bc44"
name: "Covid registration confirmation"
subject: "Weʼve received your subscription"
content: "Dear Veteran,\n\nThank you for expressing your interest in Covid-19 vaccine.\n\nWe have received your application as of ((date))\n\nThank you for your service,\nVA.gov\n\n---\nYou are receiving this email because you filed a form on VA.gov. Please do not reply to this email. If you need to contact us please visit https://va.gov."
```

**Comment by ffafara-tw** [comment]
Creating following template in staging:
```
id: "5ade0ab3-7ed6-433e-b1cb-54017f1d75bc"
name: "Covid registration confirmation"
subject: "Weʼve received your subscription"
content: "Dear Veteran,\n\nThank you for expressing your interest in Covid-19 vaccine.\n\nWe have received your application as of ((date))\n\nThank you for your service,\nVA.gov\n\n---\nYou are receiving this email because you filed a form on VA.gov. Please do not reply to this email. If you need to contact us please visit https://va.gov."
```

**Comment by ffafara-tw** [comment]
We discovered that the va.gov service in dev environment is being utilized by user flow tests, which revoke all API keys.
We will modify user flows not to use va.gov service, create a new API key and update it in VA.gov credstash.

At the moment integration between dev environment of vets-api and our dev environment is most likely broken.
