### ISSUE TITLE
[SPIKE] Celery Container Health

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#281]
# Goal

Explain the purpose of the spike. E.g. tool selection, research, understanding future state/feasibility
The scope of this spike is to better understand how the health of our celery containers work and how they might be better monitored and measured. Ultimately our goal is to find a way for ECS to understand when celery docker container might need to be restarted.

# Checklist
- [ ]
- [ ] Discuss and document with team
- [ ] Create recommendations

# Timebox
Estimate how long this should take, in days. Typically 3.

# Assumptions
- 

# Additional Info/Resources
-  Relevant thread: https://github.com/celery/celery/issues/4079
- Unfortunately, Flower is not compatible with SQS: https://docs.celeryproject.org/en/stable/userguide/monitoring.html#flower-real-time-celery-web-monitor
- Healthchecks: For SQS, you can specify the pidfile using --pidfile /opt/celery/celery_pid and check that the process is still running using kill -0 $(cat /opt/celery/celery_pid)s
- UK approach: https://github.com/alphagov/notifications-api/blob/master/scripts/run_multi_worker_app_paas.sh

# Out of Scope
-

# Open Questions
-  Can we use this command: `celery -A celeryapp status`? Does it require celery events?
No, because celery workers are based on SQS:
```
bash-5.0$ celery -A run_celery.notify_celery status
2020-12-17T20:22:52 delivery delivery INFO no-request-id "Logging configured" [in /usr/local/lib/python3.6/site-packages/notifications_utils/logging.py:96]
Error: Broadcast not supported by transport 'sqs'
```
`celery inspect stats -A run_celery.notify_celery` and `celery inspect ping -A run_celery.notify_celery` do not work either because of SQS
- Is implementation out of scope?

**Comment by saman-moshafi-va** [comment]
Some observation on my local that might be useful:

1.  docker-compose -f ci/docker-compose-local.yml up --build
2. docker kill localstack
3. docker-compose -f ci/docker-compose-local.yml start localstack
4. the celery container stops
I have attached the trace
[celery container stop trace.txt](https://github.com/department-of-veterans-affairs/notification-api/files/5717713/celery.container.stop.trace.txt)

**Comment by saman-moshafi-va** [comment]
According to [celery 4.4.2 doc](https://docs.celeryproject.org/_/downloads/en/4.4.2/pdf/) `Tip: If you override the task’s __call__ method, then it’s very important that you also call self.run to execute the body of the task. Do not call super().__call__. The __call__ method of the neutral base class
celery.Task is only present for reference. For optimization, this has been unrolled into celery.app.trace.
build_tracer.trace_task which calls run directly on the custom task class if no __call__ method is
defined.`
Perhaps we should revisit the code
