### ISSUE TITLE
VANotify should accept identifiers that are fully qualified

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#282]
# Value Statement

**As** VA Notify platform API
**I want to** accept fully qualified identifiers
**So that** I can process identifier types that might not have unique suffixes

# Acceptance Criteria

AC1. _If they pass it fully-qualified, let's just use that_
**GIVEN** VANotify platform receives a notification request with recipient identifier passed as fully qualified identifier
**WHEN** VANotify makes a request to MPI
**THEN** VANotify passes the fully qualified identifier to MPI

AC2. _Current behaviour_
**GIVEN** VANotify platform receives a notification request with recipient identifier passed as a not-fully-qualified identifier
**WHEN** VANotify makes a request to MPI
**THEN** VANotify tries to fully-qualify that identifier, and passes that to MPI

# Checklist
- [ ] Open API specification 
- [ ] ADR
- [ ] 

# Assumptions
- Provide backward compatibility with the current API for a period of time 

# Additional Info/Resources
- Recently MPI let us know that some systems like Cerner have identifiers with multiple suffixes such as below. We want to be able to accept full identifiers with the multiple suffixes instead of trying to reconcile/accept identifiers that might not be complete. 

Id_type: ICN
Id_value: 123456

123456^suffix_for_ICN

^PI^200CERN^VHA
^EM^200CERN^VHA

12323423^BRLS^200^USDVA

# Out of Scope
-

# Open Questions

- ~Are we adding this feature as an option or are we making it so that we "only" accept fully qualified identifiers?~ - we're gonna accept everything! The consumer can just pass us whatever they've got
- ~How long will we provide backward compatibility if we decide to make the change universal? This is dependent on the above.~ - it's fully backwards compatible - if we decide to make it more strict in the future, we can have that conversation
- ~How do we represent fully qualified identifiers in the database and application models?~ no changes to the database - the `recipient_identifiers.id_value` will just be whatever the consumer gave us, and when we make a request to MPI we should figure out whether to fully-qualify it

**Comment by miabecker** [comment]
FLUP from convo with Shane: As we add other identifiers, address it at the time if its constructable or not - keep the API schema as is, if its an identifier type we can’t construct then the value should be fully qualified

**Comment by philherbert** [comment]
# Option 1: "give us whatever you've got and we'll figure it out"

**API schema changes**: None

Consumers could pass us `id_type` and `id_value`, with the latter being either fully qualified or not fully qualified. We store whatever they give us, and when it comes to make a request to MPI, we:
1. Get `id_value` out of the database
2. Check if it's fully qualified (by counting carets or something)
3. If it is fully qualified, use that
4. If it is not fully qualified, try to make it so

## Pros

* No API schema changes - backwards compatible
* No DB schema changes

## Cons

* Additional logic when making a request to MPI
* Probably also some logic when making a request to VA Profile - ensure we un-fully-qualify the `VAPROFILEID`
* Lack of validation at the API means that consumers could successfully pass us an identifier that _should be fully qualified, but isn't_, and we'd be unable to use it to query MPI

**Comment by philherbert** [comment]
# Option 2: "certain identifiers must be passed to us fully qualified"

**API schema changes**: Structure of the request stays the same, but additional complexity around validating the format of certain identifiers

Consumers could still pass us `id_type` and `id_value`, but for specific `id_type`s that _need_ to be fully qualified, the API could require that `id_value` is fully qualified. We would still need additional logic when making a request to MPI:
1. Get `id_value` out of the database
2. Is the `id_type` one that we have required to be fully qualified?
3. If yes, use the value
4. If no, make the value fully qualified

## Pros

* No DB schema changes
* We can guarantee that if a certain `id_type` needs to have a fully qualified value for MPI, it will be fully qualified, and everything will work

## Cons

* API schema changes - potentially complicated in OpenAPI + JSONSchema to represent the concept "if `id_type` is `CERNER`, then `id_value` must be this format"
* Still additional logic when making a request to MPI, as described above

**Comment by lingtran** [comment]
🧐 Sounds like regardless approach we decide, we must have validations/formatting rules in place to pass fully qualified values in order to successfully query MPI. Can you provide this point of clarification - not all identifier types need to have fully qualified values? Can you provide a use case for this? It would help be better understand the narrative around the options posed.

**Comment by saman-moshafi-va** [comment]
On first cons of option 2: Currently we don't validate the value of an identifier, so can the code just try to use the value and if either VANotify fails to format the FHIR or MPI returns as error, then the notification status becomes failure?

**Comment by marisahoenig** [comment]
My original thought with this card was that passing in **only** the fully qualified identifier would be an option (rather than `id_type` and `id_value`). Is this something we're considering? Are our consumers always able to pass in `id_type` or is it more likely they will only have the fully qualified identifier and not want to separately pass in `id_type`?

**Comment by jsmithVA** [comment]
Test Plan doc (WIP) - https://docs.google.com/document/d/1UH-iJCqz5MO6XN2j4lqXYAPba4WjNQPOCKj2a3ebUqk/edit
