### ISSUE TITLE
Set notification status to appropriate final state in MPI and VAProfile tasks

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#286]
# Value Statement

**As** a VANotify consumer
*I want to** know when notifications fail due to technical reasons
**So that** I know if it's possible to retry them

**As** a VANotify consumer
*I want to** know when notifications fail permanently
**So that** I know there is no point in retrying them

# Acceptance Criteria

*AC1: Retryable Exceptions / Technical Failures*
**GIVEN** VANotify attempts a request to MPI and VA Profile
**WHEN** that request is failing due to technical reasons
**THEN** the notification status will be set to status "technical failure"
**AND** the celery task will be marked as "failed"

*AC2: NonRetryable Exceptions / Permanent Failures*
**GIVEN** VANotify attempts a request to MPI and VA Profile
**WHEN** that request is failing due to reasons that won't be solved by re-trying (i.e. there is no data in MPI or data isn't correct, multiple active VA Profile IDs for one identifier, or no active VA Profile Identifiers)
**THEN** the notification status will be set to "permanent failure"
**AND** the celery task chain would be stopped with the celery task being marked as "complete" (rather than failed)

# Checklist
- [x] Enumerate all of the different failure paths to stress-test if this logic should apply
- [x] Add 502, 503, 504 as retryable exceptions in VA Profile Client (they are in MPI Client already)
- [x] Move the `NonRetryableException` catch blocks to be the last exception in both task blocks (keep as technical failure)
- [x] MPI: UnsupportedIdentifierException, IncorrectNumberOfIdentifiersException > technical failure; the other nonretryable exceptions should be permanent failure
- [x] Permanent failure exception messages should include the exception name
- [x] VA profile: Add catching `RequestException`, like MPI
- [x] All HTTP errors should be technical failure -> Because these will either be retryable or caught in the final nonretryable exception catch block

AC1:
- [x] Retryable errors set to "technical failure" status (once the max retries is reached—this functionality already exists)
- [x] When errors are set to "technical failure," celery chain should fail

AC2:
- [x] Specific nonretryable errors (specified below) set to "permanent failure" status
- [x] When errors are set to "permanent failure," celery chain should be stopped (`self.request.chain = None`), marking it as complete rather than failing from an exception being raised

# Current State
Technical failure scenarios:
- Both: Max retries (from retryable exception), HTTP error (429, 500, 502, 503, 504) which hits max retries
- MPI: UnsupportedIdentifierException, IdentifierNotFound, IncorrectNumberOfIdentifiersException, MultipleActiveVaProfileIdsException, Error from MPI (nonretryable)
- VA Profile: NoContactInfoException, Error from VA Profile (nonretryable)

Permanent failure scenarios:
- MPI: BeneficiaryDeceasedException
- HTTP error that is **not** 429, 500, 502, 503, 504

# State after this story
Technical failure scenarios: (when retried too many times, error specific to Notify like we don't have that Recipient Identifier in our map)
- Max retries (from retryable exception)
- HTTP errors (all)
- MPI: IncorrectNumberOfIdentifiersException, UnsupportedIdentifierException

Permanent failure scenarios:
- MPI: IdentifierNotFound, MultipleActiveVaProfileIdsException, BeneficiaryDeceasedException, Error from MPI (nonretryable)
- VA Profile: NoContactInfoException, Error from VA Profile (nonretryable)

# Additional Info/Resources
- Look at the handling of deceased statuses as an example 

# Open Questions
- What are all of the scenarios that might come up for permanent failure?  -> Refer to "State after this story" above

**Comment by marisahoenig** [comment]
To add:
* Fix logging the exception name when catching (BeneficiaryDeceasedException, IdentifierNotFound, MultipleActiveVaProfileIdsException) in `lookup_va_profile_id_task` (and the same in `contact_information_tasks`
* Add logging message to `BeneficiaryDeceasedException` in `mpi.py`

**Comment by jsmithVA** [comment]
Test plan: https://docs.google.com/document/d/1wikYKxm6F0VBIY6xPv5BMBhjSOv7nyjTeF32S0M0m7Y/edit?usp=sharing

**Comment by philherbert** [comment]
Some new log messages:

1. Deceased
```
 BeneficiaryDeceasedException - Beneficiary deceased for identifier: 664321^PI^200CORP^USVBA: Can't proceed after querying MPI for VA Profile ID for 7c5ea0b6-4768-4517-be46-14c0c551d5c0. Stopping execution of following tasks. Notification has been updated to permanent-failure.
```

2. No active VA Profile ID
```
IdentifierNotFound - No active VA Profile Identifier found for: 222101^PI^200CORP^USVBA: Can't proceed after querying MPI for VA Profile ID for 6ac91205-8244-402f-b732-8f5601029d9e. Stopping execution of following tasks. Notification has been updated to permanent-failure.
```

3. Multiple active VA Profile IDs
```
MultipleActiveVaProfileIdsException - Multiple active VA Profile Identifiers found for: 222002^PI^200CORP^USVBA: Can't proceed after querying MPI for VA Profile ID for c840fe4e-fcdc-4790-809c-4d02708183e0. Stopping execution of following tasks. Notification has been updated to permanent-failure.
```

4. No contact information in VA Profile
```
NoContactInfoException - No email in response for VA Profile ID 2003: Can't proceed after querying VA Profile for contact information for ef420765-62a5-427a-956f-c9458e4eae72. Stopping execution of following tasks. Notification has been updated to permanent-failure.
```
