### ISSUE TITLE
[SPIKE] upgrade celery to 4.4.2 and revisit NotifyCelery and NotifyTask implementations

### ISSUE THREAD

**Issue by saman-moshafi-va** [department-of-veterans-affairs/notification-api#296]
# Goal
Modifying the NotifyTask code will probably avoid duplicate logging and might also improve performance.  The purpose of this spike is to follow the recommended guideline and check the impact.
According to [celery 4.4.2 doc](https://docs.celeryproject.org/_/downloads/en/4.4.2/pdf/) `Tip: If you override the task’s __call__ method, then it’s very important that you also call self.run to execute the body of the task. Do not call super().__call__. The __call__ method of the neutral base class
celery.Task is only present for reference. For optimization, this has been unrolled into celery.app.trace.
build_tracer.trace_task which calls run directly on the custom task class if no __call__ method is
defined.` 

# Checklist
- [ ] plan full regression test
- [ ] Discuss and document with team
- [ ] Create recommended code
- [ ] modify requirements-app.txt
- [ ] See if we should update to 4.4.7 and or 5 - the hypothesis is this change will improve performance

# Timebox
2 days

# Assumptions
- upgrading to celery 4.4.2 is straightforward
- After this spike merge to master and run regression tests

# Additional Info/Resources
-

# Out of Scope
- resolving all the performance issues such as DB access

# Open Questions
- Is implementation out of scope? No

**Comment by miabecker** [comment]
Closed, combined with other Celery Story #431
