### ISSUE TITLE
Retrieve Email Statuses from Amazon SES 

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#300]
Value Statement

**As** a VANotify customer when I use the VANotify platform to send an email message
**I want to** know whether or not my email message was successfully delivered
**So that** I know if the Veteran has received the email message

**As** a VANotify customer when I use the VANotify platform to send an email message 
**I want to** know whether or not my email message was successfully delivered
**So that** I can build and trigger workflows depending on the status

# Acceptance Criteria

_AC1_: **GIVEN** an email message request is made
**WHEN** it is sent via SES
**THEN** the notification status within VANotify is updated as "sending"

_AC2_: **GIVEN** an email message is sent via SES
**WHEN** an email message event is received 
**THEN** the notification status within VANotify will be updated to the appropriate mapped status

_AC3_: **GIVEN** VANotify receives a status from Amazon SES that VANotify considers to be final
**WHEN** a service has a webhook defined
**THEN** then VANotify calls back the webhook communicating the final status

_AC4_: **Given** an email message is sent via SES and VANotify receives a status update
**When** the status type is transient (e.g. "sending", "failed and attempting to re-deliver")
**Then** we log and count how many of each type are occurring

# Checklist
- [x] Check and review CA Team status work 
- [x] StatsD
- [x] Trigger webhook callbacks

Infra: 

- [x] SNS topics
- [x] Set up Lambda

# Assumptions
* The service callback is always HTTPS URL

# Additional Info/Resources

* The API to create or update service callback is added to the postman scripts
* In case of http status 5xx or communication errors such as not valid https certificate or network issues, the celery worker will retry the callback URL for a maximum of 5 times with 300 seconds intervals.

How this will be triggered:

- SNS triggers Lambda
- Lambda creates a message on SQS 
- which represents a  Celery Task 
- and then Celery processes to our database

https://github.community/t/feature-request-due-dates-for-specific-issues-without-needing-a-milestone/1452/6
https://github.com/cds-snc/notification-terraform/blob/main/aws/dns/ses.tf
https://github.com/cds-snc/notification-terraform/blob/main/aws/common/sns.tf
https://github.com/cds-snc/notification-terraform/blob/main/aws/common/lambdas/ses_to_sqs_email_callbacks.py

# Out of Scope
- Re-trying on transient statuses 

# Open Questions

-  Is there a way to split feedback / statuses per an environment (dev, staging and prod)? Short term - configuration sets (which we should always be using). Long term - domains / identities. 
- Which queue should we use for SES callback? queue name is $NOTIFICATION_QUEUE_PREFIX+'delivery-receipts'
### possible states, as returned by API for emails:
```
transients: 'created', 'sending'
final: 'technical-failure', 'permanent-failure', 'delivered'
```

**Comment by miabecker** [comment]
Blocked 1/25/21 - Awaiting completion of #300 to establish pattern to version and promote Lambda code.

**Comment by saman-moshafi-va** [comment]
I modified the code so the celery worker can use both 'notificationType' and 'eventType' in the message.  Here is the documentations I investigated:
* https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-ses/globals.html
* https://docs.aws.amazon.com/sns/latest/dg/sns-dg.pdf
* https://aws.amazon.com/blogs/messaging-and-targeting/analyze-and-improve-email-campaigns-with-amazon-simple-email-service-and-amazon-quicksight/

I am not wiser after reading the documents though since EventType is enum and NotificationType is type aliases.

**Comment by jsmithVA** [comment]
Test plan notes: https://docs.google.com/document/d/1hu40kCsqAXliAcdZp5aEDO8VtkEU9xQSOChndAcdDXE/edit

**Comment by ffafara-tw** [comment]
We are going to handle Reject event type in a followup story.
@miabecker we need to create that story.

**Comment by jsmithVA** [comment]
Test results: https://docs.google.com/document/d/1CLkG5fGESvYVv3RrI5E_W6RCj5cvhg0myOnjMGJvhgU/edit?usp=sharing
