### ISSUE TITLE
Configure "help" and "stop" responses for text long codes

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#313]
# Value Statement

**As** a Veteran when I send "help" or "stop" keyword via text
**I want to** receive an informative user friendly response
**So that** I know what will happen next

# Acceptance Criteria
**GIVEN** a user replies "help" or "stop"
**WHEN** replying to a text message
**THEN** they receive the appropriate configured response

# Checklist
- [x] Research to see if we can do this via Terraform
- [x] Content wording - Todd and Maria to pair

# Assumptions

- This can be found in the AWS Pinpoint Settings

# Additional Info/Resources
Below are the messages to be used for the pharmacy use case.

HELP
VA prescription shipment notifications: Reply STOP to unsubscribe. Call 800-932-6408 Ext 3555 for help. 1msg/shipment. Msg&data rates may apply.

STOP, CANCEL, END, OPT-OUT, OPTOUT, QUIT, REMOVE, TD, UNSUBSCRIBE
VA prescription shipment notifications: You will no longer receive VA prescription shipment notifications. Reply START to resubscribe.

START
VA prescription shipment notifications: You will now receive VA prescription shipment notifications. Reply STOP to unsubscribe.

# Out of Scope
-

# Open Questions

- Does this have to be done for each number separately or one and done for all numbers? 
- Confirm that stop also responds to default in the documentation below? 
- Are there other keywords for "help" such as "info"? See additional documentation for help below. 

This is from the AWS documentation with regard to SMS opt out:
SMS opt out
Where required by local laws and regulations (such as in the US and Canada), SMS recipients can use their devices to opt out by replying to the message with any of the following:

ARRET (French)

CANCEL

END

OPT-OUT

OPTOUT

QUIT

REMOVE

STOP

TD

UNSUBSCRIBE

To opt out, the recipient must reply to the same long code or short code that Amazon Pinpoint used to deliver the message. After opting out, the recipient no longer receives SMS messages from your AWS account.

https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-manage.html#channels-sms-manage-optout

HELP
Used to obtain customer support. The response message must include customer-support contact information, as in the following example:

"For assistance with your account, call 1 (NNN) 555-0199."

**Comment by toddstanich** [comment]
Updated with content for STOP HELP and START commands.

**Comment by ffafara-tw** [comment]
Responses to default keywords have to be setup on each number separately via AWS Console.
Cannot be performed using Terraform.

**Comment by ffafara-tw** [comment]
START command is not handled by default via AWS.
We have to create a lambda to do that: #333

**Comment by jsmithVA** [comment]
Found unexpected behavior where the number (828-678-6800) responds with the HELP message to any text that isn't STOP. E-mailed Ilya to confirm behavior and created a bug to track it.

https://app.zenhub.com/workspaces/vanotify-5ea0ae59b51ccc3c83a8b65b/issues/department-of-veterans-affairs/notification-api/338

**Comment by jsmithVA** [comment]
Response from Ilya is that this is expected behavior. Moving to sign off.
