### ISSUE TITLE
Enhance email styling and accessibility by adding H2 headers

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#315]
# Value Statement
**As** Business Line Customer
**I want to** use an H2 header in my email templates
**So that** my email notifications are more accessible and styled

# Acceptance Criteria
**GIVEN** a template 
**WHEN** uses ## 
**THEN** the line should be wrapped in a H2 HTML tag

# Checklist
- [x] H2 style should be:
• size 24
• bold (same as H1)
• Helvetica, Arial, sans-serif (same as H1)
• color: #323a45 (same as H1)
- [x] H2 plain text should be:
```
self.linebreak() * 2,
text,
self.linebreak(),
'-' * self.COLUMN_WIDTH,
```
(same as H1 with one less line break)

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
- What should we do with a plain text h2 heading? 
- This is what header 1 looks like right now?
some text

Header
--------

**Comment by miabecker** [comment]
@ffafara-tw separating out the plain text portion as a separate story from this because we will need to define plain text overall for SES. cc: @toddstanich

**Comment by ffafara-tw** [comment]
Why would we need to define plain text overall?

**Comment by toddstanich** [comment]
@ffafara-tw when we started with plain text we defined how each element would be rendered in plain text, but I was under the impression we didn't implement that because we went with what granicus translated it to. Is that accurate?

**Comment by ffafara-tw** [comment]
We didn't define it - the UK team did. So plaintext formatting/rendering is already in the codebase.
It's true that it is not being used at all when sending via Granicus. It will be used when sending via SES.
We don't have to define the plain text. We might want to review it to see if there is anything we want to do differently (than UK/Canadian teams)

**Comment by toddstanich** [comment]
Got it, I wasn't aware plain text formatting was already in the codebase. In that case, it makes sense that this ticket include adding the formatting for an H2.

@ffafara-tw can you provide or point me to where the existing plain text formatting is so we can add H2 formatting to it?

**Comment by ffafara-tw** [comment]
https://github.com/department-of-veterans-affairs/notification-utils/blob/78830a318c281ca6108dd8827b52c925894de3a0/notifications_utils/formatters.py#L474

**Comment by lingtran** [comment]
Verified h2 tags are picked up on screenreaders.

**Comment by miabecker** [comment]
Signed off.
