### ISSUE TITLE
Prepare for DMC dark launch

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#318]
# Value Statement
**As** DMC Business Line
**I want to** have a test API key 
**So that** I can try out VA Notify in research mode

# Acceptance Criteria
**GIVEN** 
**WHEN** 
**THEN**

# Checklist
- [x] Create a service in production
- [x] Create template in production (updated content in comments)
- [x] Create test API key i.e. needs to be in research mode

# Assumptions

-Service should be modeled after the one in staging - daily message limit set to 25,000 with permissions only to send emails

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions

- Confirm content one last time with Todd

**Comment by toddstanich** [comment]
Approved content from DMC team

Subject: Important information from the Debt Management Center

Email Content: 
Dear Veteran,

You have new information from the Debt Management Center. Please sign in to https:/va.gov/manage-va-debt/ to view details.

You will also receive a letter from the Debt Management Center with the details of this information.

Thank you, 
VA.gov

Please do not reply to this email. If you need to contact us please visit https://va.gov.

![DMC-email-revised.jpg](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/bdcb0e9f-ea16-4db1-879d-4686a62ed42b)

**Comment by lingtran** [comment]
Testing in staging before creating the entities in prod

**Comment by lingtran** [comment]
Created service with research mode on. Created service api key with type as test. Also observed the message limit and finalized content.
