### ISSUE TITLE
Create pharmacy prescription shipping update template in production

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#319]
# Value Statement
**As** a Veteran
**I want to** receive a text message when my controlled substance pharmacy prescription(s) have shipped
**So that**I can be informed about when my prescription(s) from the VA might arrive and can contact the VA to reschedule if needed

# Acceptance Criteria

**GIVEN** a veteran from the Asheville VA hospital is receiving a shipment of a controlled pharmacy substance
**WHEN** VEText API sends VANotify a request
**THEN** VANotify will send a pharmacy prescription shipment update to the veteran

# Checklist

- [x] Create a template ID in production for pharmacy prescription shipping update template
- [x] Give Template ID to Rob
- [x] Work with Business Line to Finalize Content

# Assumptions
- This is will be associated with the VEText service 
- VEText will be pulling the prescription data from CDW and VISTA
- This is a pilot localized to the Asheville, NC VHA center for now

# Additional Info/Resources

((facility_name)): Your ((prescription)) with RX# ending in ((rx_last4)) has shipped. ((carrier)) tracking number ((tracking_number)).\n\n((tracking_link))

**Examples with datafield objects filled in:**

U.S. Department of Veterans Affairs: Your prescription with RX# ending in 4567 has shipped. USPS tracking number 9400115901094234000042

Multiple prescriptions
U.S. Department of Veterans Affairs: Your prescriptions with RX# ending in 4567, 3567, 7801 have shipped. USPS tracking number 9400115901094234000042

# Out of Scope

# Open Questions

**Comment by saman-moshafi-va** [comment]
sent the template id to Robert Durkin.
