### ISSUE TITLE
Add instructions for using talisman on pre-commit

### ISSUE THREAD

**Issue by punitladtw** [department-of-veterans-affairs/notification-api#32]
Add the ability to check if a commit has a secret within there. 

- [x] Add [pre-commit](https://pre-commit.com/) to Brewfile
- [x] Add pre-commit configuration file (`.pre-commit-config.yaml`)
- [x] Configure pre-commit to point towards Talisman plugin
```
repos:     
    - repo: https://github.com/thoughtworks/talisman       
      rev: 'v1.2.0'       
      hooks:           
         - id: talisman-commit 
```
- [x] following instructions for adding talismans here: https://github.com/thoughtworks/talisman
- [ ] Add note to README about initialising pre-commit stuff

Everyone initialise it:

- [x] @philherbert 
- [x] @ffafara-tw 
- [x] @marisahoenig 
- [x] @saman-moshafi-va 
- [x] @lingtran

**Comment by saman-moshafi-va** [comment]
Do we have to install go as well?

**Comment by ffafara-tw** [comment]
I guess so. I think talisman is using go.
Maybe we should add talisman to Brewfile so that we can use that tool manually and it should also bring in any needed dependencies.

**Comment by saman-moshafi-va** [comment]
I installed go using brew and tested talisman successfully

**Comment by lingtran** [comment]
@philherbert Do we need to specify installing `talisman` after setting up pre-commit in the README? It is mentioned at the beginning of the section as a tool we used but there was no explicit callout to install talisman.

**Comment by philherbert** [comment]
@lingtran As far as I know, installing and configuring pre-commit will use the talisman stuff automatically! I don't think we need to explicitly install talisman.

**Comment by ffafara-tw** [comment]
@lingtran @philherbert you have to have 'go' installed as well as the pre-commit will try to install (build from source) talisman
