### ISSUE TITLE
Choose provider using service and template

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#321]
# Value Statement

**As** VANotify platform admin
**I want to** be able to choose what provider for notifications is used at a service and template level
**So that** cost can be managed and the load balanced across providers

# Acceptance Criteria

_AC1: "Let's send notifications using custom providers"_
**GIVEN** VANotify receives a request to send a notification
**THEN** we choose a provider using the "Summary of Choosing Provider Logic" described in the additional info
**THEN** the notification is sent using that provider

_AC2: "Let's check at delivery that the provider is valid"_
**GIVEN** VANotify processes a notification for delivery
**THEN** we choose a provider using the process "Summary of Choosing Provider Logic" described in the additional info
**BUT IF** that provider is "inactive" 
**THEN** the notification is marked as `technical-failure`

_AC3: "We won't let you configure a service to use an invalid provider for sending emails"_
**GIVEN** VANotify receives a request to update/create a service
**WHEN** the request specifies an `email_provider_id`
**BUT** that provider doesn't exist 
**OR** that provider is "inactive"
**OR** that provider is not an `email` provider
**THEN** the request is rejected as invalid (throw 400 bad request, log error message)

_AC4: "We won't let you configure a service to use an invalid provider for sending SMS"_
**GIVEN** VANotify receives a request to update a service/create a service 
**WHEN** the request specifies an `sms_provider_id`
**BUT** that provider doesn't exist 
**OR** that provider is "inactive" 
**OR** that provider is not an `sms` provider
**THEN** the request is rejected as invalid

_AC5: "We won't let you configure a template to use a invalid provider"_
**GIVEN** VANotify receives a request to update/create a template
**WHEN** the request specifies a `provider_id`
**BUT** that provider doesn't exist 
**OR** that provider is "inactive" 
**OR** the type of the provider (eg `email` / `sms`) does not match the type of the template 
**THEN** the request is rejected as invalid

# Checklist

- [x] Update database schemas and models:
  - [x] Update template to include `provider_id` column, using a foreign key
  - [x] Update service to include `email_provider_id` and `sms_provider_id` columns, using foreign keys
- [x] Update API schemas and documentation:
  - [x] Update template to include `provider_id` field
  - [x] Update service to include `email_provider_id` and `sms_provider_id` fields
- [x] Change the endpoints that create and update templates:
  - [x] Read provider out of database using provided `provider_id`
  - [x] Verify provider exists
  - [x] Verify provider is active
  - [x] Verify `provider.notification_type` matches `template.template_type`
  - [x] Persist `provider_id` to database
- [x] Change the endpoints that create and update services
  - [x] If `email_provider_id` is provided:
    - [x] Read provider out of database using `email_provider_id`
    - [x] Verify provider exists
    - [x] Verify provider is active
    - [x] Verify `provider.notification_type` is `email`
    - [x] Persist `email_provider_id` to database
  - [x] If `sms_provider_id` is provided:
    - [x] Read provider out of database using `sms_provider_id`
    - [x] Verify provider exists 
    - [x] Verify provider is active
    - [x] Verify `provider.notification_type` is `sms`
    - [x] Persist `sms_provider_id` to database
- [x] Change the task that delivers notifications:
  - [x] Choose a provider based on the logic described in additional info
  - [x] Update the notification to `technical-failure` if the above logic fails
  - [x] Deliver the notification using that provider if everything's good
- [x] Test that, if a provider is associated with a template / service, it throws an error when a migration is run that deletes that provider (hopefully we get this for free if we're using foreign keys)
- [x] User flows? Include if possible but if not it's okay to not add them. v1/ notification status (`sent_by` field should be a string with provider name)? Modified the openapi so sent_by has the name of the client
- [x] Update ServiceHistory table/schema to have email/sms_provider_id?
- [x] add a feature flag for the new code

# Assumptions
-  In order for a notification to be sent a provider has to be active
- There can be 1 email and text provider set for each service
- We're gonna use foreign keys, so it should not be possible to have a reference to a provider that doesn't exist

# Additional Info/Resources

Summary of Choosing Provider Logic: 

1. Does the template have a `provider_id`?

_If no, continue to 2a or 2b. If yes, check that the provider is active. If no, throw an exception, if yes, **use that provider!**_

2. 
a. SMS notifications: Does the service have an `sms_provider_id`?
b. Email notifications: Does the service have an `email_provider_id`?

_If no, continue to 3. If yes, check that the provider is active. If no, throw an exception, if yes, **use that provider!**_

3. Choose the provider globally based on priority (current behavior)

# Out of Scope

Removed the following AC, because:
* It would have an impact on performance (additional DB calls)
* This scenario would only occur if a valid provider was added to a template/service, but then later updated to be invalid, which is unlikely
* This would represent an entirely new layer of validation, which would be nice to have, but isn't absolutely necessary

```
"We won't let you request to send a notification using an invalid provider"
GIVEN VANotify receives a request to send a notification
THEN we choose a provider using the "Summary of Choosing Provider Logic" described in the additional info
BUT IF that provider doesn't exist 
OR that provider is "inactive" 
OR the type of the provider (eg `email` / `sms`) does not match the type of the notification 
THEN the request is rejected as invalid
```

# Open Questions
- We have talked about switching between providers, so should service point to a number of providers or just single sms or email providers?

**Comment by philherbert** [comment]
Hi @miabecker and @ffafara-tw - just updated the ACs and checklist, have a read and make any necessary edits

**Comment by miabecker** [comment]
Read and made some small edits @philherbert
