### ISSUE TITLE
Spin up Lighthouse use case 1 in production

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#326]
# Value Statement
**As** a Veteran
**I want to** receive a notification
**when** I disconnect or connect an application (such as Apple Health) to my VA account 
**So that**I know my account is secure and my information is only shared with the applications I want it to be

# Acceptance Criteria
**GIVEN** a veteran connects an application to their account
**THEN** VANotify will send an email to the veteran informing them an application has been connected

**GIVEN** a veteran disconnects an application to their account
**THEN** VANotify will send an email to the veteran informing them an application has been connected

# Checklist

- [x] Create 2 template(s) in production for Lighthouse use case 1
- [x] Create Lighthouse organization in production
- [x] Create service and API key for Lighthouse in a production environment
- [x] Ensure service has permissions only to send email
- [x] Ensure service prefix SMS is changed to false
- [x] Give Template ID(s) and API key to Braden
- [x] Work with Business Line to Finalize Content

# Assumptions

# Additional Info/Resources

connect copy
SUBJECT: 'Your VA profile is connected to ((application)).'
BODY: 'Dear ((first_name)),\nYour VA profile was connected to ((application)) on ((time)).\n You can learn about how this application stores your information by reviewing its [privacy policy](((privacy_policy))).\nIf you did not perform this connection, you may disconnect from the application on our [connected apps](https://www.va.gov/profile/connected-applications) page and [change your password](https://www.va.gov/resources/signing-in-to-vagov/).\n\n\n\nSincerely,\n\nva.gov\n___\nYou are receiving this email because you connected an application from your profile on VA.gov. Please do not reply to this email. If you need to contact us, please visit https://va.gov.'

disconnect copy
SUBJECT: 'Your VA profile is disconnected from ((application)).'
BODY: 'Dear ((first_name)),\nYour VA profile was disconnected from ((application)) on ((time)). This app can't access any new information from your VA.gov profile, but some apps may still store information you've already shared. To learn about how this application stores your information, including what information it stores, if any, and what steps are available to you, review ((application))'s [privacy policy](((privacy_policy))).\nIf you did not perform this disconnection, you may manage your [connected apps](https://www.va.gov/profile/connected-applications) and [change your password](https://www.va.gov/resources/signing-in-to-vagov/).\n\n\n\nSincerely,\n\nva.gov\n___\nYou are receiving this email because you disconnected an application from your profile on VA.gov. Please do not reply to this email. If you need to contact us, please visit https://va.gov.'

# Out of Scope
- Two-way communication with Veteran

# Open Questions
- Which email provider will we use for this use case? 
- Check if URL formatting and using placeholder is possible at the same time i.e. [privacy policy](((privacy_policy)))

**Comment by miabecker** [comment]
Deadline 1/13.

**Comment by ffafara-tw** [comment]
Created following resources:

`production:
    organization:
        name: Ligthouse
        id: d7aa8ca2-e7ad-4ca3-b2c2-1597e4beeab4
    service:
        id: d6244b78-bb94-4a00-923c-1b8181bac561
        name: Ligthouse
        message_limit: 10000 (not enforced without Redis)
        rate_limit: 300
        prefix_sms: false
        permissions: email
    api-key:
        id: 99d28549-a8c6-42f4-b111-e80b91aff074
        key_type: normal
        name: lighthouse-production-key
    template:
        - id: 8a4ff2c3-9adc-46a2-abc1-d0909ddcb2bc
          type: email
          name: On Application Connect
          subject: Your VA profile is connected to ((application)).
          content: "Dear ((first_name)),\n\nYour VA profile was connected to ((application)) on ((time)).\n You can learn about how this application stores your information by reviewing its [privacy policy](((privacy_policy))).\n\nIf you did not perform this connection, you may disconnect from the application on our [connected apps](https://www.va.gov/profile/connected-applications) page and [change your password](https://www.va.gov/resources/signing-in-to-vagov/).\n\n\n\nSincerely,\nva.gov\n___\nYou are receiving this email because you connected an application from your profile on VA.gov. Please do not reply to this email. If you need to contact us, please visit https://va.gov."
        - id: c00f8088-0a31-40e5-b9b0-f8203e13cd5a
          type: email
          name: On Application Disconnect
          subject: "Your VA profile is disconnected from ((application))."
          content: "Dear ((first_name)),\n\nYour VA profile was disconnected from ((application)) on ((time)). This app can't access any new information from your VA.gov profile, but some apps may still store information you've already shared. To learn about how this application stores your information, including what information it stores, if any, and what steps are available to you, review ((application))'s [privacy policy](((privacy_policy))).\n\nIf you did not perform this disconnection, you may manage your [connected apps](https://www.va.gov/profile/connected-applications) and [change your password](https://www.va.gov/resources/signing-in-to-vagov/).\n\n\n\nSincerely,\nva.gov\n___\nYou are receiving this email because you disconnected an application from your profile on VA.gov. Please do not reply to this email. If you need to contact us, please visit https://va.gov."`
