### ISSUE TITLE
Create pull request (PR) to devops repository to change revproxy configuration

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#339]
# Value Statement
**As** a platform admin
**I want to** receive delivery statuses from Granicus
**So that** I know the status of the notifications the VA Notify platform is sending via Granicus

# Acceptance Criteria
**GIVEN** a URL dev-api.va.gov/vanotify/*
**WHEN** a request is made
**THEN** the request is handled by dev VANotify service

# Acceptance Criteria
**GIVEN** a URL staging-api.va.gov/vanotify/*
**WHEN** a request is made
**THEN** the request is handled by staging VANotify service

# Acceptance Criteria
**GIVEN** a URL api.va.gov/vanotify/*
**WHEN** a request is made
**THEN** the request is handled by production VANotify service

# Checklist
- [ ] Pull request with rev proxy confirmation changes

# Assumptions
- This PR will have to be approved by VSP operations team. 

# Additional Info/Resources
- That configuration will allow us to route traffic from api.va.go/vanotify (as an example) to our own load balancer and service, which will in turn allow us to configure webhooks with Granicus.

# Out of Scope
-

# Open Questions
- [ ] Will we need to make any changes to our load balancer?

**Comment by philherbert** [comment]
Blocked while waiting for security review

**Comment by ffafara-tw** [comment]
Dev & Staging:
https://github.com/department-of-veterans-affairs/devops/pull/8465

Production PR:
https://github.com/department-of-veterans-affairs/devops/pull/8643
