### ISSUE TITLE
Storing notification failure reasons 

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#340]
# Value Statement

**As** a VANotify platform admin
**I want to** be able to see detailed statuses on why notifications have failed
**So that** I can better tell my customers why their notifications are failing

**As** a Business Line Customer
**I want to** be able to see detailed statuses on why notifications have failed
**So that** I can resolve and data inconsistencies or issues 

# Acceptance Criteria
**GIVEN** a notification 
**WHEN** it reaches a final failure state
**THEN** a failure reason is stored

# Checklist
- [x] Add a column to notification and notification history (String w/o fixed length, strip whitespace)
- [x] Store the failure reason (all va-profile mpi failures for now, don't do provider stuff right now)
- [x] Expose failure reason in the notification status api endpoint (v2)
- [x] feature flags

# Notes
MPI Exceptions:
`MpiRetryableException`
`MpiNonRetryableException`
`IncorrectNumberOfIdentifiersException`
`IdentifierNotFound`
`MultipleActiveVaProfileIdsException`
`BeneficiaryDeceasedException`

VA Profile Exceptions:
`VAProfileRetryableException`
`VAProfileNonRetryableException`
`NoContactInfoException`

# Out of Scope
- Adding provider-specific failure messages (will be a later story)

**Comment by emilywu-tw** [comment]
MPI exceptions:
- [ ] MpiRetryableException - can’t really replicate, caused during http errors
- [x] MpiNonRetryableException - ICN, “1008843368V268268”
- [ ] IncorrectNumberOfIdentifiersException - don’t have a user set up for this
- [ ] IdentifierNotFound - don’t have a user set up for this
- [x] MultipleActiveVaProfileIdsException - ICN, “1008710501V455565”
- [x] BeneficiaryDeceasedException - ICN, "1008788718V759106"


VA Profile exceptions:
- [ ] VAProfileRetryableException - can’t really replicate, caused during http errors
- [x] VAProfileNonRetryableException - VAPROFILEID, “5963^PI^200VETS^USDVA^A”
- [x] NoContactInfoException - ICN, "1008829506V869586”

**Comment by TWs-DevenS** [comment]
QA Verification:
1. Reviewed successful execution of the Unit tests for MPI and VA Profile exception handling.
2.  Tests executed with known Account data.

**Comment by ffafara-tw** [comment]
Moving back as toggle is not enabled in production.

**Comment by miabecker** [comment]
@emilywu-tw added epics to this card - are these the rights ones?

**Comment by TWs-DevenS** [comment]
this has been reviewed during the Dev Sync and can be closed.

**Comment by emilywu-tw** [comment]
<img width="1253" alt="mpi-http-error" src="https://user-images.githubusercontent.com/34494609/116559099-12f97600-a8ce-11eb-848a-5d8c027792a4.png">
<img width="1254" alt="va-profile-http-error" src="https://user-images.githubusercontent.com/34494609/116559106-14c33980-a8ce-11eb-8473-abd110580386.png">
