### ISSUE TITLE
COVID Communication 4 - v1 and v2

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#348]
# Value Statement

**As** a Veteran
**I want to** receive an informational email after I expressed interest in receiving information about the COVID vaccination process at the VA
**that** is customized to my survey response 
**So** I can be informed about the VA's plans for COVID

# Acceptance Criteria
**GIVEN** a veteran has expressed interest via the COVID Vaccination Interest Form on VA.gov and the VA has information to communicate
**WHEN** VA.gov sends a request to VEText API
**THEN** VANotify will send an informational email to the veteran
**THAT** is customized based on their response to the COVID Interest Survey

# Checklist

- [x] Create template ID(s) in staging for COVID Information Update
- [ ] Create template ID(s) in production for COVID Information Update
- [ ] Give template ID(s) to Rob
- [ ] Give Granicus a heads up

# Assumptions
- This is apart of VA.gov and VetsAPI
- We need to segment the email based on the person's answer to the vaccine plans question. 
- We will have 2 versions of this email:
(1 for "yes, plan to get a vaccine" and 1 for the other answers). 
- In the "other answers" version, we have 1 place where we have dynamic content based on the person's specific answer.

# Additional Info/Resources
- [https://app.zenhub.com/files/257953872/383a462d-4431-446e-990a-e03f4997933b/download](https://app.zenhub.com/files/257953872/383a462d-4431-446e-990a-e03f4997933b/download)
- [https://app.zenhub.com/files/257953872/2a3d8ad6-3adc-46e8-ae73-67eef138d12b/download](https://app.zenhub.com/files/257953872/2a3d8ad6-3adc-46e8-ae73-67eef138d12b/download)

# Out of Scope
- Two-way communication with Veteran

# Open Questions

**Comment by saman-moshafi-va** [comment]
On Staging:
The new template id's are: 17161121-e0eb-48e9-a43a-58296eb308d7 and c81a29d0-aa86-4e83-a8b3-57b340021791
17161121-e0eb-48e9-a43a-58296eb308d7 requires confirmation_id
KMI_email #4_v6c (other plan answers)_02.1.21: c81a29d0-aa86-4e83-a8b3-57b340021791 requires vaccine_preference and confirmation_id

**Comment by lingtran** [comment]
Production template ids:

KMI_email #4_v6c (other plan answers)_02.1.21
  - 2a8ecba1-32ff-4cca-ae9f-3157bcb18457

KMI_email #4_v5a (plan to get a vaccine)_02.1.21
 - 03e92969-8736-4ac5-929a-6440e90a4cb8
