### ISSUE TITLE
Get Amazon SES into production

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#356]
# Value Statement
**As** VANotify platform developer
**I want to** onboard Amazon SES as a provider into production
**So that**I can use it to send emails and begin to "warm up"

# Acceptance Criteria
**GIVEN** a VANotify platform developer 
**WHEN** is viewing email providers in the VANotify platform
**THEN** Amazon SES is an option with which to send emails

# Checklist
- [x] AWS Support request to get dedicated IP addresses
- [x] AWS Support request for sending limits?
- [x] AWS Support request to take us out of sandbox
- [x] Submit forms with main ISPs to clear IP history
- [x] Make sure account suppression list is on

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by anushyaprasad** [comment]
3 emails

**Comment by ffafara-tw** [comment]
SES settings showing account level suppression list:
{
    "DedicatedIpAutoWarmupEnabled": true,
    "EnforcementStatus": "HEALTHY",
    "ProductionAccessEnabled": true,
    "SendQuota": {
        "Max24HourSend": 1500000.0,
        "MaxSendRate": 120.0,
        "SentLast24Hours": 5.0
    },
    "SendingEnabled": true,
    **"SuppressionAttributes": {
        "SuppressedReasons": [
            "BOUNCE",
            "COMPLAINT"
        ]
    },**
    "Details": {
        "MailType": "TRANSACTIONAL",
        "WebsiteURL": "https://www.va.gov",
        "ContactLanguage": "EN",
        "UseCaseDescription": "We represent VANotify - enterprise notification platform for Department of Veteran Affairs. \n\nWe are sending primarily transactional emails on a daily basis such us:\n- confirmation of form submissions on https://va.gov \n- notifications of actions taken by VA on veteran cases (status update, etc)\n- notifications of veteran information/profile updates\n\nIn addition we will be sending informational campaigns such as covid related keep me informed campaign (https://www.va.gov/health-care/covid-19-vaccine/stay-informed).",
        "AdditionalContactEmailAddresses": [
            "vanotify@va.gov"
        ],
        "ReviewDetails": {
            "Status": "GRANTED",
            "CaseId": "8038334481"
        }
    }
}

**Comment by ffafara-tw** [comment]
Created #va.gov-team/issues/22411 to get analytics team guidance on setting up google account for postmaster tool

**Comment by ffafara-tw** [comment]
@ffafara-tw will split setting up postmaster tool from this story

**Comment by miabecker** [comment]
Created a new story to split setting up postmaster #413
