### ISSUE TITLE
Edit Data of 526EZ Disability Application Confirmation Email - First Name vs. First and Last Name

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#357]
# Value Statement
**As** a Veteran
**When** I submit the 526EZ form
**I want to** receive a confirmation email
**That** only contains my first name
**And** is compliant with HIPPA

# Acceptance Criteria
**GIVEN** a 526EZ form
**WHEN** a confirmation email is sent
**THEN** it only contains the first name 

# Checklist
(in order)
- [x] Update `vets-api` to provide `first_name` as a personalisation parameter in `form526_submission.rb`
- [x] Deploy `vets-api` to prod
- [x] Update the form526 confirmation email template on VANotify in all environments to use `((first_name))` in the content
  - [x] dev + associated user flow tests
  - [x] staging
  - [x] prod
- [x] Verify that the submission email job still works
- [x] Update `vets-api` to remove `full_name` from the personalisation parameters
- [x] Deploy `vets-api` to prod

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by emilywu-tw** [comment]
PR: https://github.com/department-of-veterans-affairs/vets-api/pull/6041

**Comment by emilywu-tw** [comment]
we tested that we can in fact successfully pass in personalization parameters that are unused by the template to the send email endpoint.

**Comment by lingtran** [comment]
Set PR ready for review in `vets-api` to push change to prod: https://github.com/department-of-veterans-affairs/vets-api/pull/6041

**Comment by lingtran** [comment]
PR push to introduce first_name was deployed [here, build no. 915](http://jenkins.vfs.va.gov/job/deploys/job/vets-gov-autodeploy-vets-api/), which provided a release link to show the diff that was to be merged to prod. Verified that PR was included as part of it [here](https://github.com/department-of-veterans-affairs/vets-api/compare/vets-api/v0.0.818...848dd18c5e6c45e7a342a66be02724cbdb76131c).

**Comment by lingtran** [comment]
PR to remove `full_name` from personalization parameters: https://github.com/department-of-veterans-affairs/vets-api/pull/6088

**Comment by lingtran** [comment]
Verified change deployed to prod in release v.0.0.821: https://github.com/department-of-veterans-affairs/vets-api/releases/tag/vets-api%2Fv0.0.821
