### ISSUE TITLE
[SPIKE] Explore different ways to optimize our platform

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#362]
# Goal

Run a series of experiments to explore how to improve our performance. Some ideas might be:
- check different sizes of tasks (CPU / RAM)
- check different number of gunicorn threads
- test different types of threading in gunicorn
- cache services and provider lookups when sending notifications
- make database saves asynchronous (delegate saving of notifications to a celery tasks)
- test different database instances sizes
- test with different database connection pool sizes
- explore RDS proxy AWS product

# Checklist
- [ ] Discuss and document with team
- [ ] Create recommendations

# Timebox
TBD

# Assumptions
- 

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
- Is implementation out of scope?

**Comment by ffafara-tw** [comment]
@miabecker We agreed during dev sync that we should make this an EPIC and each use case / experiment should be it's own story

**Comment by miabecker** [comment]
Creating an epic and individual cards to capture.
