### ISSUE TITLE
Decommission TW AWS environment

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#363]
# Value Statement
**As** a VANotify developer
**I want** to not have to maintain two parallel environments 
**So that** my life is simpler and thus happier and thus more productive

**As** a VANotify leadership person
**I want** to not have to pay for a redundant environment
**So that** I have more money to spend on nice things

# Acceptance Criteria
**WHEN** a developer pushes commits to `notification-api`
**THEN** no infrastructure is deployed to the TW AWS environment

**WHEN** a developer logs into the TW AWS console
**THEN** there are no VANotify resources present

# Checklist
- [ ] Delete resources from `notification-api/cd/`:
  - [ ] `base-infrastructure`
  - [ ] `application-infrastructure`
  - [ ] `application-database`
  - don't delete `application-deployment`! we use that!
- [ ] Remove bits of the Github Actions Workflows that deploy to TW environments

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by miabecker** [comment]
Reviewed with Filip can be closed.
