### ISSUE TITLE
Configure 720 area long code for Denver pharmacy prescription pilot

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#365]
# Value Statement
**As** Veteran in Colorado
**I want to** receive prescription notifications from a local number
**So that** I can trust the message

# Checklist
- [x] Create non-default SMS sender id for VEText service & verify SMS is going out with correct number:
  - [x] staging
  - [x] prod 
- [x] Pass sender ids with instructions how to use it to Rob Durkin
- [x] Configure help message

# Additional Info/Resources
Use "Call 1-888-336-8262, option 1" inside help message

# Assumptions

- Default two-way responses will work the same as the Asheville use case

**Comment by ffafara-tw** [comment]
@miabecker verify if we need to add more to the story

**Comment by emilywu-tw** [comment]
<img width="808" alt="Screen Shot 2021-02-12 at 2 10 54 PM" src="https://user-images.githubusercontent.com/34494609/107811494-39caf600-6d3c-11eb-8fe5-5ef4112b9a70.png">
