### ISSUE TITLE
Update No Reply For AWS and Granicus

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#372]
Granicus subject line: You sent a message to a mailbox that isn't monitored.

You have sent a message to a mailbox that isn't monitored.
Please note this mailbox isn’t checked by anyone. Messages sent to this address won’t get a reply. To get in touch with someone please use the following contact information:

If you’re a Veteran in crisis and need immediate help, please call 800-273-8255 and press 1. Or visit www.veteranscrisisline.net 
If you have questions or need more information about your benefits, please visit VA.gov or call us at 844-698-2311 (TTY:711).

1 - Fiip to update with AWS
2 - Maria to email Granicus

**Comment by ffafara-tw** [comment]
Setting for AWS (in VA outlook):
![Screen Shot 2021-03-17 at 4.41.34 PM.png](https://images.zenhubusercontent.com/5da0974a66de7b0001e4d835/4b78adcb-d1dd-4cb8-9789-87cbdcca592f)

**Comment by ffafara-tw** [comment]
Email sent to granicus requesting change.

**Comment by ffafara-tw** [comment]
Granicus autoresponse message:
![Screen Shot 2021-03-30 at 1.30.22 PM.png](https://images.zenhubusercontent.com/5da0974a66de7b0001e4d835/3ee4e633-aade-46e8-a371-29e690c9aad1)

**Comment by ffafara-tw** [comment]
Subject has not been updated. 
@miabecker do we want to reach back to Granicus to request subject change?

**Comment by miabecker** [comment]
I replied back to the support ticket.

**Comment by TWs-DevenS** [comment]
QA Verification:

**sent email to donotreply@messages.va.gov** 
response - You have sent a message to a mailbox that isn't monitored.

Please note this mailbox isn’t checked by anyone. Messages sent to this address won’t get a reply. To get in touch with someone please use the following contact information:
If you’re a Veteran in crisis and need immediate help, please call 800-273-8255 and press 1. Or visit www.veteranscrisisline.net

If you have questions or need more information about your benefits, please visit VA.gov or call us at 844-698-2311 (TTY:711).

**sent email to Vanoreplymessages@va.gov**

Received response:  


![Screen Shot 2021-04-15 at 10.51.55 AM.png](https://images.zenhubusercontent.com/604f66cb300e975b0fa212d7/bc6e7907-62ef-49b4-acfc-6a56a459bd52)

VA No Reply Messages
10:49 AM (0 minutes ago)
to me

You have sent a message to a mailbox that isn't monitored.

Please note this mailbox isn’t checked by anyone. Messages sent to this address won’t get a reply. To get in touch with someone please use the following contact information:

If you’re a Veteran in crisis and need immediate help, please call 800-273-8255 and press 1. Or visit www.veteranscrisisline.net 

If you have questions or need more information about your benefits, please visit VA.gov or call us at 844-698-2311 (TTY:711).

**Comment by TWs-DevenS** [comment]
The msg is just sent the first time you send to an unmonitored email address - that is the suggested behavior.  The functionality seems to be as -is
