### ISSUE TITLE
Create template for COVID Email 5

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#374]
# Value Statement

**As** a Veteran
**I want to** receive an informational email after I expressed interest in receiving information about the COVID vaccination process at the VA
**that** is customized to my survey response 
**So** I can be informed about the VA's plans for COVID

# Acceptance Criteria
**GIVEN** a veteran has expressed interest via the COVID Vaccination Interest Form on VA.gov and the VA has information to communicate
**WHEN** VA.gov sends a request to VEText API
**THEN** VANotify will send an informational email to the veteran
**THAT** is customized based on their response to the COVID Interest Survey

# Checklist

- [x] Create template ID(s) in staging for COVID Information Update
- [x] Create template ID(s) in production for COVID Information Update
- [x] Give template ID(s) to Rob
- [x] Give Granicus a heads up

# Assumptions
- This is apart of VA.gov and VetsAPI

# Additional Info/Resources
- Tag va.gov links with the UTM code `?utm_source=VANotify&utm_medium=email&utm_campaign=covid_19_vaccine`

# Out of Scope
- Two-way communication with Veteran

# Open Questions
[https://app.zenhub.com/files/257953872/d6ada118-f7eb-41cd-8b84-0be9e908f1ad/download](https://app.zenhub.com/files/257953872/d6ada118-f7eb-41cd-8b84-0be9e908f1ad/download)

**Comment by toddstanich** [comment]
Updated Content

[https://app.zenhub.com/files/257953872/c3c8b7a0-ad88-4406-beaa-2a74c2c5aab1/download](https://app.zenhub.com/files/257953872/c3c8b7a0-ad88-4406-beaa-2a74c2c5aab1/download)
