### ISSUE TITLE
Monitor our configuration and external dependencies

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#378]
# Value Statement
**As** a VANotify platform administrator
**I want to** be alerted if the app's configuration is preventing healthy behaviour
**And to** be alerted if an external dependency of the app becomes unavailable
**So that** I can address issues and ensure that we are delivering notifications

# Acceptance Criteria
**GIVEN** an external dependency of the app is unavailable
(eg MPI, VA Profile, Pinpoint?, Govdelivery?
**WHEN** a request is made to `/some_endpoint`
**THEN** we respond with information concerning the unavailable dependency

**GIVEN** the `provider_service` is using a strategy that is not able to return a provider
**WHEN** a request is made to `/some_endpoint`
**THEN** we respond with information concerning the invalid strategy

**GIVEN** Datadog is monitoring our platform in some environment
**THEN** every 5 minutes?, Datadog queries `/some_endpoint` and asserts that the response is good
_(using synthetic tests! [datadog](https://docs.datadoghq.com/synthetics/api_tests/) and [terraform](https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test))_ 
**AND IF** the response indicates that the app is unhealthy
**THEN** an alert is posted in slack

# Checklist
- [ ] Checklist item here

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by mjones-oddball** [comment]
We would probably need to talk more about what this entails and create additional tickets. We'll also have to talk to our partners to get their take on doing a check like this.

**Comment by npmartin-oddball** [comment]
Closing out. Documentation exists.
