### ISSUE TITLE
Set up BIMI for emails coming from VA

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#380]
# Value Statement
**As** Veteran or non-Veteran Beneficiary
**I want to** see the Department of Veterans Affairs Logo (BIMI) on emails are coming from the Department of Veteran's affairs in my inbox
**So that** I have confidence my information is safe

# Acceptance Criteria
**GIVEN** an email from the Department of Veterans Affairs
**WHEN** it is sent from messages.va.gov and notifications.va.gov
**THEN** the end-user will see a BIMI in their inbox on the same row as the email

# Checklist
- [ ]  Implement for both domains: messages.va.gov and notifications.va.gov

# Assumptions
- This will require an ESEC request to modify the DNS Record
-  Will store the image / svg file in the va.gov public s3 bucket

# Additional Info/Resources
- BIMI SVG - ![BIMI.svg](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/4117cf16-29d3-4ea3-8fb5-e846eb08b387)
- What is BIMI?: BIMI is a way to verify your brand and sender information, similar to other email authentication standards you’ve probably heard of like DMARC, DKIM, and SPF. And, just like those others, BIMI is essentially just a text record that lives on your servers. Email clients that support BIMI will check for that record to confirm that your emails are legit.The feature that distinguishes BIMI, though, is that during the verification process, email clients will pull in your brand logo to display alongside your message. 

https://www.litmus.com/blog/how-to-set-up-bimi/

# Out of Scope
-

# Open Questions
-

**Comment by miabecker** [comment]
Is it possible for Granicus?

**Comment by miabecker** [comment]
@toddstanich to add svg file here

**Comment by ffafara-tw** [comment]
https://github.com/department-of-veterans-affairs/vets-website/pull/17162

**Comment by ffafara-tw** [comment]
https://bimigroup.org/bimi-generator/ claims the SVG has some issues:

```
SVG Issues You Need To Fix
 Attribute "Data-Name" Not Allowed Here, At Line Number: 1:170
More Details [+]
 Element "Svg" Missing Required Attributes "BaseProfile" And "Version", At Line Number: 1:170
More Details [+]
 Element "Defs" Not Allowed Yet, At Line Number: 1:176
More Details [+]
 Element "Style" Not Allowed Anywhere, At Line Number: 1:183
More Details [+]
 Element "ClipPath" Not Allowed Anywhere, At Line Number: 1:436
More Details [+]
 Element "ClipPath" Not Allowed Anywhere, At Line Number: 1:515
More Details [+]
```

@toddstanich can you take a look?

**Comment by toddstanich** [comment]
@ffafara-tw ran it through a conversion tool. How can we verify it meets the requirements?

Attached in this zip folder, github won't let me upload the SVG directly.
[bimi.zip](https://github.com/department-of-veterans-affairs/notification-api/files/6533529/bimi.zip)

**Comment by ffafara-tw** [comment]
I think we will need to upload it to S3 bucket and use https://bimigroup.org/bimi-generator/ to verify.

**Comment by ffafara-tw** [comment]
PR to udpate SVG:
https://github.com/department-of-veterans-affairs/vets-website/pull/17317

**Comment by ffafara-tw** [comment]
We might need to add some more DNS entries (SPF, MX) for notifications.va.gov domain.

**Comment by ffafara-tw** [comment]
BIMI verification passes for messages.va.gov however it's not showing up on gmail.
We might need to to obtain a verified mark certificate (VMC)

**Comment by ffafara-tw** [comment]
We should also test it with Verizon Media (Yahoo)

**Comment by miabecker** [comment]
1. Test with yahoo
2. Test sending to yahoo email with both domains
3. If it doesn't work with one of the domains, we may need to correct DNS entries and talk to the email exchange, 

@TWs-DevenS

**Comment by ffafara-tw** [comment]
If it doesn't work for either domain - we have to review what is missing according to https://bimigroup.org/.
If it does not work for notifications.va.gov we will need to:
 - add SPF DNS record
 - add MX DNS record
via ESECC in scope change request.

To add MX DNS record we will need to talk to VA Email (Exchange?) group to get their approval for pointing the domain at VA mail servers.

**Comment by ffafara-tw** [comment]
The BIMI logos are not showing up in yahoo.
It's possible that we are not sending enough emails, as yahoo is only showing BIMI Logo for bulk senders:
https://easydmarc.com/blog/how-to-configure-bimi-record/

**Comment by TWs-DevenS** [comment]
Test Plan for testing BIMi logo
https://docs.google.com/document/d/1n4UvmiAESUSySw0GdwtqbLxNWIsBzUCQRDY4BL-D-Fc/edit

**Comment by miabecker** [comment]
Inputted a ticked to Yahoo support today.

**Comment by miabecker** [comment]
Creating a bug card for yahoo issue.
