### ISSUE TITLE
Shrink database instance in dev environment

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#386]
# Value Statement
**As** a VANotify platform admin/owner
**I want to** use correct instance sizes 
** And** not over provision environments
**So that** we can keep costs down 

# Acceptance Criteria
**GIVEN** VANotify dev environment
**THEN** we use db.*.small instance family

# Checklist
- [ ] Verify that data was not lost 

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by ffafara-tw** [comment]
AWS CLI command to get available instances types:
```
aws rds describe-orderable-db-instance-options --engine aurora-postgresql --db-instance-class db.t3.medium \\
    --query 'OrderableDBInstanceOptions[].[DBInstanceClass,StorageType,Engine,EngineVersion]' \\
    --region us-gov-west-1 --output text

```
One can replace db.t3.medium with other instance family types:
db.r5.large, db.r4.large, db.t3.small, db.t3.medium, db.t3.large, etc.

This information should also be available in AWS UI console when creating a new DB instance.

**Comment by saman-moshafi-va** [comment]
Here is the snapshot of the VAEC RDS Aurora proving db.t3.medium is configured by dev.  During deployment while the new DB instance type was initialized, the DB was not available to VANotify or celery workers.  It took around 4 minutes for the DB to become available.
![userstory386](https://user-images.githubusercontent.com/56931061/112378255-15f4bb80-8cbd-11eb-8887-e897bc713f9b.png)

**Comment by TWs-DevenS** [comment]
Reviewed Acceptance Criteria, it has been satisfied as demonstrated in the Screen shot above.
Testing criteria has been met. Ready for Signoff
