### ISSUE TITLE
Create performance environment

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#387]
# Value Statement

**As** a VANotify developer
**I want to** create an on demand performance environment
**So that** I have dedicated environments to run performance tests

# Acceptance Criteria
* number of celery workers same as prod
* number of api instances the same as prod
* the datadog dashboard for performance can be used when copied from prod?
* the same db size as prod
* when to run performance test? is scheduling part of this user story?

**GIVEN** 
**WHEN** 
**THEN**

# Checklist
- [x] Decrease staging size once complete

# Assumptions
- Same size as production environment
-

# Additional Info/Resources

# Out of Scope
- Scaleingan environment up and down with the click of one button

# Open Questions
Currently we are considering the as is production env specification to built the on-demand performance testing environment.  Do we have some defined user expectations that we have considered while building out the production env?
Would this env have the ability to scale up and down to perform stress tests/load tests?
Have we considered peak level demand when allocating resources to env?
Would this env account for the oncoming UI layer being introduced?

**Comment by saman-moshafi-va** [comment]
an example of successful performance deployment: https://github.com/department-of-veterans-affairs/notification-api/actions/runs/721053202

**Comment by saman-moshafi-va** [comment]
Created #415 to register domains.
We need to identify what it means to halt the performance enviornment.

**Comment by saman-moshafi-va** [comment]
The commands I used to decrease the size of staging Aurora were:

1. I used my GFE so had to setup the AWS using key and secret key by setting AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in the cygwin environment variables using "export AWS_ACCESS_KEY_ID=<key value>"
2. initialize terraform; terraform init -backend-config="../staging-backend.hcl"
3. check existing Aurora cluster and instances; either "terraform show -no-color > show.log" or "terraform state show "module.db.aws_rds_cluster.this[0]" and "terraform state show "module.db.aws_rds_cluster_instance.this[0]"
4. manually create a reader instance, in the same availability zone. I used AWS console by one can use AWS client as well
5. perform failover so reader instance becomes writer
6. delete the old writer (which is now a reader); got one or two bad gateway when running status check using postman
7. rename the new writer to have the same name as the old writer
8. terraform plan -no-color -out=plan.tf -var-file="staging.tfvars";  **Important**: If the plan shows a new cluster instance will be created, then you need to update the terraform state as it has not recognized the new writer instance.
* terraform refresh -no-color -var-file="staging.tfvars"
* terraform state show "module.db.aws_rds_cluster.this[0]" and terraform state show "module.db.aws_rds_cluster_instance.this[0]"
* terraform import module.db.aws_rds_cluster_instance.this[0] staging-notification-api-db-1
* terraform state show "module.db.aws_rds_cluster_instance.this[0]"
