### ISSUE TITLE
COVID KMI Email #6

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#393]
# Value Statement

**As** a Veteran
**I want to** receive an informational email after I expressed interest in receiving information about the COVID vaccination process at the VA
**that** is customized to my survey response 
**So** I can be informed about the VA's plans for COVID

# Acceptance Criteria
**GIVEN** a veteran has expressed interest via the COVID Vaccination Interest Form on VA.gov and the VA has information to communicate
**WHEN** VA.gov sends a request to VEText API
**THEN** VANotify will send an informational email to the veteran
**THAT** is customized based on their response to the COVID Interest Survey

# Checklist

- [X] Create template ID(s) in staging for COVID Information Update
- [X] Create template ID(s) in production for COVID Information Update
- [X] Give template ID(s) to Rob
- [X] Give Granicus a heads up
- [  ] Receive feedback and make edits
- [X]Rob D does testing w/ VEText
- [  ] Go live and monitor

# Assumptions
- This is apart of VA.gov and VetsAPI

# Additional Info/Resources
- Tag va.gov links with the UTM code `?utm_source=VANotify&utm_medium=email&utm_campaign=covid_19_vaccine`
- https://github.com/department-of-veterans-affairs/va.gov-team/issues/20597
- Content - 
[KMI email #6 Janssen vaccine approved FINAL 030221.docx](https://github.com/department-of-veterans-affairs/notification-api/files/6072230/KMI.email.6.Janssen.vaccine.approved.FINAL.030221.docx)

# Out of Scope
- Two-way communication with Veteran

# Open Questions

**Comment by miabecker** [comment]
We can remove the “(Johnson & Johnson)” now from the email subject line. @saman-moshafi-va more feedback coming soon.

**Comment by toddstanich** [comment]
Updated content - https://github.com/department-of-veterans-affairs/notification-api/files/6072230/KMI.email.6.Janssen.vaccine.approved.FINAL.030221.docx
