### ISSUE TITLE
[SPIKE] Explore observability of Celery workers

### ISSUE THREAD

**Issue by lingtran** [department-of-veterans-affairs/notification-api#395]
# Goal
We've experienced a few incidents where messages in queue build up despite having reasonable number of Celery workers. We hypothesize that there may be zombie workers afoot, but currently have no way to monitor individual worker health. This spike aims to explore options for observability of Celery workers.

# Checklist
- Research:
  - [ ] Ways to inspect directly inspect workers
  - [ ] Can we set up a second broker to inspect workers? If so, that's cool and what are the tradeoffs in recommended choice of broker?
- [ ] Explore increasing observability of celery works by utilizing Datadog profiling
  - [ ] Enable celery events in dev environment for more detailed info
- [ ] Discuss and document with team
- [ ] Create recommendations
- [ ] Create ADR

# Timebox
Estimate how long this should take, in days. Typically 3.

# Assumptions/Constraints
- Use of SQS as broker limits ability to write to logs worker info etc. This card helps explore workaround to this constraint.

# Additional Info/Resources
- Recent incidents on March 4, 2021:
  - [PagerDuty - incident 15](https://veterans-affairs.pagerduty.com/incidents/PXP6L0T) <-- had 24 workers, but needed to deploy 6 new ones to get messages out of queue
  - [PagerDuty - incident 16](https://veterans-affairs.pagerduty.com/incidents/P0VS3YN) <-- self-resolved
- [Celery - Monitoring/worker-events](https://docs.celeryproject.org/en/stable/userguide/monitoring.html#worker-events)
- [Celery - Monitoring/task-events](https://docs.celeryproject.org/en/stable/userguide/monitoring.html#task-events)
- [Celery - Workers/inspecting-workers](https://docs.celeryproject.org/en/stable/userguide/workers.html#inspecting-workers)
- [Celery - Worker/configuration](https://docs.celeryproject.org/en/stable/userguide/configuration.html#worker)
- [Celery - Brokers](https://docs.celeryproject.org/en/stable/getting-started/brokers/index.html)

# Out of Scope
- Flower (pronounced 'flow') library -> said to be not reliable for large scale projects. Also not compatible with our choice of broker SQS

# Open Questions
- Is implementation out of scope?

**Comment by lingtran** [comment]
@miabecker

**Comment by lingtran** [comment]
Moving to backlog. Want to wait and see if upgrading to Celery v5 might address this issue.

**Comment by k-macmillan** [comment]
Stale issue. No longer seeing queue buildup.
