### ISSUE TITLE
COVID KMI #7 Email

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/notification-api#397]
# Value Statement

**As** a Veteran
**I want to** receive an informational email after I expressed interest in receiving information about the COVID vaccination process at the VA
**that** is customized to my survey response 
**So** I can be informed about the VA's plans for COVID

# Acceptance Criteria
**GIVEN** a veteran has expressed interest via the COVID Vaccination Interest Form on VA.gov and the VA has information to communicate
**WHEN** VA.gov sends a request to VEText API
**THEN** VANotify will send an informational email to the veteran
**THAT** is customized based on their vaccine status in CDW

# Checklist

- [X] Create template ID(s) in staging 
- [X] Tag va.gov links with the UTM code `?utm_source=VANotify&utm_medium=email&utm_campaign=covid_19_vaccine`
- [X] Copy content and create template ID(s)
- [X] Give template ID(s) to Rob
- [  ] Give Granicus a heads up
- [  ] Receive feedback and make edits
- [  ] Rob D does testing w/ VEText
- [  ] Go live and monitor

# Assumptions
- This is apart of VA.gov and VetsAPI

# Additional Info/Resources
- Draft content attached (10AM 3/18). [https://app.zenhub.com/files/257953872/2ae3114b-f6fb-4dd8-a593-f0713e097b8d/download](https://app.zenhub.com/files/257953872/2ae3114b-f6fb-4dd8-a593-f0713e097b8d/download)
- Github Link: https://github.com/department-of-veterans-affairs/va.gov-team/issues/21098#issuecomment-800230425
Different User Segments: 
- [ ] Segment 1 - not enrolled
- [ ] Segment 2 - Enrolled, but not received vaccine
- [ ] Segment 3 - Received at least 1 dose

# Out of Scope
- Two-way communication with Veteran

# Open Questions
-

**Comment by toddstanich** [comment]
Updated draft content from 4PM 3/15 attached above.

**Comment by ffafara-tw** [comment]
Staging info
```
"id": "1ca96222-fdba-445e-a2a7-cffde26d07ea"
"name": "KMI email #7 - segment 1 - not enrolled"

"id": "87521104-558c-4b3e-8a79-963fa482d8e6",
"name": "KMI email #7 - segment 2 - enrolled no vaccine"

"id": "34a8fa61-9861-418c-9444-52c859c51049",
"name": "KMI email #7 - segment 3 - vaccinated"
```

**Comment by ffafara-tw** [comment]
Production info:

```
"id": "04bc692c-9539-42d2-8f32-ae60a8ed76d4",
"name": "KMI email #7 - segment 1 - not enrolled"

"id": "fc57cfce-86eb-47c8-a046-93368911234a",
"name": "KMI email #7 - segment 2 - enrolled no vaccine"

 "id": "9021cedc-944a-48d5-8f84-b83ebe1b345b",
"name": "KMI email #7 - segment 3 - vaccinated"
```

**Comment by toddstanich** [comment]
Broken link in existing emails:  Get answers to frequently asked questions about connected apps should go to https://www.va.gov/resources/connected-apps-faqs/

**Comment by toddstanich** [comment]
Approved content - https://app.zenhub.com/files/257953872/2ae3114b-f6fb-4dd8-a593-f0713e097b8d/download

**Comment by ffafara-tw** [comment]
KMI email #7 - segment 1 - not enrolled:
  stats:
    - status: delivered
      count: 189137
    - status: failed
      count: 3644
    - status: permanent-failure
      count: 32
    - status: sending
      count: 135
    - status: temporary-failure
      count: 4

KMI email #7 - segment 2 - enrolled no vaccine:
  stats:
    - status: delivered
      count: 75974
    - status: failed
      count: 1437
    - status: permanent-failure
      count: 11
    - status: sending
      count: 44
    - status: temporary-failure
      count: 4

KMI email #7 - segment 3 - vaccinated:
  stats:
    - status: delivered
      count: 400500
    - status: failed
      count: 7545
    - status: permanent-failure
      count: 45
    - status: sending
      count: 237
    - status: temporary-failure
      count: 3
