### ISSUE TITLE
UI Application: Create scaffolding of a project for deployment 

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#398]
# Value Statement
**As** VANotify platform owner
**I want** any change to self service UI to go through CI/CD pipeline
**So that** it goes through all quality checks

# Acceptance Criteria
**GIVEN** a commit is made to the `notification-ui`  repository
**WHEN** all of the unit tests and lint rules pass
**THEN** commit is deployed to dev environment

**GIVEN** a commit is made to the `notification-ui` repository
**WHEN** all or a unit test or lint rule fails
**THEN** the pipeline fails 
**AND** the commit is not deployed to the dev environment

# Checklist

- [x] Create new UI repository (choose a name!)
- [x] Create "Hello World" page
- [x] Continuous integration and deployment pipeline
  - [x] Unit Tests
  - [x] Linting
  - [x] Package build
  - [x] Deployment to dev 
- [x] Pre-commit hook and setup script
- [x] README
- [x] talisman
- [x] look into nvm and node-version

# Assumptions
- 

# Additional Info/Resources

- We will be using React with Typescript and React Testing Library

# Out of Scope

- E2E Tests
- Code Quality / Security Analysis
- Promotion to staging and production

# Open Questions

- Do we build a docker image? Where do we deploy to? Yes. Created multi-state image where JS assets are served by nginx. Deployed to ECR.

**Comment by lingtran** [comment]
As of today, able to define deployment workflow and add needed secrets to trigger appropriate actions. Added Slack notification for UI deployments. Remaining to-do is add notification-ui resources in infrastructure, separate from notification-admin

**Comment by lingtran** [comment]
Deployed to dev: 
![screenshot of it up in the network](https://images.zenhubusercontent.com/5ecea5442d18e437e3b23d00/b61c959b-692b-4c9a-b435-f52c132947a0)

Technical learnings: 
- nginx configuration showed for http port is assigned to 80, not 8080
- when ports were being updated and involved ui service target group updates, there was an issue where a rule set to the listener resource was not able to be destroyed and recreated along with the listener resource. this involved manual deletion of resources. also had to move name of target group to tag (name_prefix attribute has character limit) to avoid name collisions. ooof.

Remaining to do:
- remove old images of admin service in the ui ECR
- clean up some of the shared variables in infra

**Comment by TWs-DevenS** [comment]
Filip has really viewed the steps.  ( Screen shots have been attached)
The checklist with the various components is checked
This tkt can be closed
