### ISSUE TITLE
[BUG] calls to Pinpoint to send an SMS that return a failed response do not call Pinpoint callback

### ISSUE THREAD

**Issue by emilywu-tw** [department-of-veterans-affairs/notification-api#399]
# Describe the Bug
When sending an SMS with Pinpoint to a number that will not receive a text (e.g., opted out), the Pinpoint callback will not be triggered. 

# To Reproduce
1. opt out a phone number
2. make a request to send a text to that phone number
3. verify in the logs/Datadog that the callback has not been triggered

# Expected Behavior
The callback should be triggered

# Actual Behavior 
The callback is not triggered

# Relevant Story
https://github.com/department-of-veterans-affairs/notification-api/issues/273

# Additional Context
The list of statuses from Pinpoint that will fail are in `AwsPinpointClient._validate_response()`: ['DUPLICATE', 'OPT_OUT', 'PERMANENT_FAILURE']. In the`provider_tasks.py`'s `deliver_sms()` method, call the callback in the catch block for `NonRetryableException` to fix this bug.

**Comment by emilywu-tw** [comment]
dev httpreq link: https://httpreq.com/cold-cherry-420zwgsz

**Comment by TWs-DevenS** [comment]
We desk checked this defect. This can be closed.
