### ISSUE TITLE
Create new KMI Confirmation Email for non-Veterans

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#400]
#Value Statement

**As** a non-Veteran
**I want** to receive a confirmation email after I expressed interest in receiving information about the COVID vaccination process at the VA
**So** I can be informed about the VA's plans for COVID

# Acceptance Criteria
**GIVEN** a non-Veteran has expressed interest via the COVID Vaccination Interest Form on VA.gov 
**WHEN** VA.gov sends a request to VEText API
**THEN** VANotify will send an informational email to the non-Veteran

# Checklist
- [ ]  Create template ID in staging and share with VA.gov team
- [ ] Receive feedback and make edits

# Assumptions

- This is apart of VA.gov and VetsAPI
- Non-Veterans will fill out a different form to receive this confirmation email

# Additional Info/Resources

- https://dsva.slack.com/files/UFN410MGF/F01RLHV2GNT/expaned-eligibility-implementation-octo__1_.docx

Congress passed legislation. that significantly expands the number of Veterans and non-Veterans who are eligible to receive a COVID-19 vaccine from VHA.The KMI tool will be updated to allow registration of people who are not currently VHA customers.
We will most likely need to create a second KMI confirmation template.

# Out of Scope
- Two-way communication

# Open Questions
- Review pathway into experience to make sure it makes sense and is clear

**Comment by miabecker** [comment]
[https://app.zenhub.com/files/257953872/da59eb5f-4b8b-426e-8c1a-33f4032d1dee/download](https://app.zenhub.com/files/257953872/da59eb5f-4b8b-426e-8c1a-33f4032d1dee/download)

**Comment by ffafara-tw** [comment]
@miabecker can we verify it is the content for the new confirmation template (for non veterans)?
Because when I read it it kinda looks to me like information for veterans.
In either case I'm creating the templates so that we will have IDs to put in va.gov config.

**Comment by philherbert** [comment]
Created draft templates so that they can have IDs (sorry if I stole your thunder, Filip)

staging: `999edcfa-5b8a-4322-ada7-4ab60baf66d3`
prod: `74db5744-b3b7-4be7-894e-03cd634a552a`

**Comment by miabecker** [comment]
Verifying the content is accurate for people who are non Veterans. The content is very similar with subtle changes @ffafara-tw @philherbert still waiting for the final approved content but this is good to put into staging and production for now.

**Comment by tradle51** [comment]
@philherbert @ffafara-tw @emilywu-tw Please note that the current KMI email has the heading "When can I get a COVID-19 at VA?"

We need to add "Vaccine" or something equivalent to the heading for it to make sense.  Please let the content editors know as you are able.

@TWs-DevenS - please make note of this as acceptance criteria!

**Comment by ffafara-tw** [comment]
Fixed the above.

**Comment by TWs-DevenS** [comment]
I verified that the issues identified were corrected.  All links and content looks good. The email  is good to go .
