### ISSUE TITLE
Update DMC Template with updated content in production

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#407]
# Value Statement
**As** a DMC business line stakeholder
**I want to** my template's content updated in production
**So that** that the template reflects the approved messaging by DMC leadership

# Acceptance Criteria
**GIVEN** the DMC template is sent
**WHEN** it is triggered
**THEN** the correct content is in the template

**GIVEN** user receives DMC notification
**WHEN** they click on the link and go to debt portal
**THEN** Google Analytics attributes that page visit to the email notification

# Checklist
- [x] Update template in production
![DMC-email-33121.jpg](https://images.zenhubusercontent.com/5da0902766de7b0001e4d7f5/928a533b-c4b8-4ed2-8436-c97b895071f4)

**Comment by emilywu-tw** [comment]
Updated template in staging and prod to reflect the desired changes. The Google analytics utm info added to the url is `utm_source=gov-delivery&utm_medium=email&utm_campaign=debt-mgmt`.

staging:
service_id = 9bdc983a-b0e3-4863-b31b-a2b92cfa0339
template_id = f9947b27-df3b-4b09-875c-7f76594d766d

prod:
service_id = b3357476-adf1-4350-be1b-3604034665f9
template_id = 7efc2b8b-e59a-4571-a2ff-0fd70253e973

**Comment by emilywu-tw** [comment]
<img width="936" alt="Screen Shot 2021-04-02 at 2 52 38 PM" src="https://user-images.githubusercontent.com/34494609/113445061-1b3fbd80-93c3-11eb-846c-6f0f98dabc13.png">

**Comment by TWs-DevenS** [comment]
Completed Verification, the acceptance criteria is satisfied.

**Comment by miabecker** [comment]
Attaching a go live checklist [https://app.zenhub.com/files/257953872/7444c0ad-bb93-4c57-9313-026b17e95fa3/download](https://app.zenhub.com/files/257953872/7444c0ad-bb93-4c57-9313-026b17e95fa3/download)

**Comment by ffafara-tw** [comment]
Can we change `utm_source=gov-delivery` to `utm_source=vanotify`

**Comment by emilywu-tw** [comment]
@ffafara-tw yep i'll make that change

**Comment by emilywu-tw** [comment]
updated

**Comment by miabecker** [comment]
@TWs-DevenS can you share more with me about how you QA'd this story? Thank you!

**Comment by TWs-DevenS** [comment]
@miabecker . After change was made,
For Acceptance Criteria 1 -  I reviewed the email received.
 I checked the template change and the content 
For Acceptance criteria 2
I clicked on the link and it took me to the page with access to debt portal.
However we shoulda capture some evidence to verify the last part of. the acceptance criteria
 - Google Analytics attributes that page visit to the email notification

**Comment by miabecker** [comment]
Sounds good thank you! I feel ok to sign off on this now.

**Comment by TWs-DevenS** [comment]
@ffafara-tw How do we verify the acceptance criteria for the following:

THEN Google Analytics a**ttributes that page visit to the email notification**

**Comment by ffafara-tw** [comment]
We click on a link and check Google Analytics (assuming this page has google tracking).
