### ISSUE TITLE
[BUG] Handling of multiple pinpoint callbacks

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#408]
# Describe the Bug
In our current pinpoint callback handling we have following code:
```
 if notification.status not in [NOTIFICATION_SENDING, NOTIFICATION_SENT]:
            log_notification_status_warning(notification, notification_status)
```

When reviewing logs we have a lot of entries like that:
```
prod-notification-api-log-group ecs/notification-celery/67fd834d947646a4bdf48ae3d5e1eb9e {"name": "delivery", "levelname": "WARNING", "message": "Invalid callback received. Notification id 57951b0b-9602-4449-b536-b7fab0386f9c received a status update to sent0:00:15.014581 after being set to temporary-failure. sms sent by pinpoint", "pathname": "/app/app/celery/process_pinpoint_receipt_tasks.py", "lineno": 128, "time": "2021-04-01T15:06:47", "requestId": "no-request-id", "application": "delivery", "logType": "application"}
```

We also have couple of entires were update would not change the status:
```
prod-notification-api-log-group ecs/notification-celery/0f3cc3f7f33e424eae5509afb63fcba2 {"name": "delivery", "levelname": "WARNING", "message": "Invalid callback received. Notification id af12c6e3-8297-4700-9747-dfcc2f1f84a6 received a status update to delivered0:36:29.026855 after being set to delivered. sms sent by pinpoint", "pathname": "/app/app/celery/process_pinpoint_receipt_tasks.py", "lineno": 128, "time": "2021-04-01T15:41:49", "requestId": "no-request-id", "application": "delivery", "logType": "application"}
```

# Expected Behavior
We should allow status to be updated from temporary-failure.

# Actual Behavior 
When status is set to temporary-failure we ignore new status updates from Pinpoint

# Relevant Story
#273

**Comment by emilywu-tw** [comment]
<img width="1323" alt="Screen Shot 2021-04-09 at 4 51 08 PM" src="https://user-images.githubusercontent.com/34494609/114239863-a1747a80-9954-11eb-9f50-481e10bfab32.png">

**Comment by TWs-DevenS** [comment]
QA Verification
Earlier - When status is set to temporary-failure we ignore new status updates from Pinpoint

Now system allows status to be updated from temporary-failure. 

Checks were performed by reviewing them in log files
