### ISSUE TITLE
Prevent unnecessary expanded-eligibility email requests

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#409]
# Value Statement
**As** a developer supporting VANotify and vets-api
**I want to** reduce the number of failed requests between the two systems
**So that** there is less noise when monitoring

# Acceptance Criteria
**GIVEN** somebody submits a KMI registration form for expanded eligibility 
**WHEN** that form does not contain an email address
**THEN** vets-api does not make a request to VANotify to send an email

(these are changes that will have to be made in vets-api)

# Checklist
- [ ] Checklist item here

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by philherbert** [comment]
@miabecker @ffafara-tw - here's a new ticket to capture some work around expanded eligibility!

**Comment by miabecker** [comment]
Interested to learn more about this! @philherbert

**Comment by ffafara-tw** [comment]
It was done as part of department-of-veterans-affairs/va.gov-team#22738

PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/6471#issuecomment-814477199
