### ISSUE TITLE
DMC Go Live - Send Test Emails

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#411]
# Value Statement
**As** a DMC business line
**I want to** receive test emails
**So that**I can see what my notification might look like 

# Checklist
- [x] Receive business line emails from business owner
- [x] Check if they are using test API key or research mode enabled on the service 
- [x] Determine if we need to use a normal API key (if there isn't one generate one) if the service is in research mode disable it
- [x] Send test emails
- [x]  If disabling research mode, enable it post send

# Assumptions
- Send from production
- Manual API key send

# Additional Info/Resources

- [x] Dawn.eggers@va.gov
- [x] Julie.lawrence@va.gov
- [x] Nicole.haselberger@va.gov       
- [x] Melonie.wheeler@va.gov
- [x] jill.anderson3@va.gov
- [x] christopher.viere@va.gov
- [x] satishkumar.harikrishnan@va.gov
- [x] Pavan.Sarangalwar@va.gov
- [x] tj.parro@va.gov
- [x] justin.carver@va.gov
- [x] lkeeler@governmentcio.com
- [x] matthew.self2@va.gov
- [x] beverly.nelson@va.gov
- [x] todd.stanich@thoughtworks.com
- [x] maria.becker@thoughtworks.com

**Comment by emilywu-tw** [comment]
the api key is in our 1password vault under "production dmc api key value"
