### ISSUE TITLE
COVID KMI Communication #8 - 4 Versions

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#412]
# Value Statement

**As** a Veteran and non Veteran apart of expanded eligibility
**I want to** receive an informational email after I expressed interest in receiving information about the COVID vaccination process at the VA
**that** is customized to my current vaccination status 
**as well as** my survey response
**So** I can be informed about the VA's plans for COVID

# Acceptance Criteria
**GIVEN** a Veteran and non Veteran apart of expanded eligibility has expressed interest via the COVID Vaccination Interest Form(s) on VA.gov and the VA has information to communicate
**WHEN** VA.gov sends a request to VEText API
**THEN** VANotify will send an informational email to the Veteran and non Veteran apart of expanded eligibility
**THAT** is customized based on their response and current vaccination status

# Checklist

- [x] Receive draft content
- [x] Create 4 template ID(s) in staging for COVID Information Update
- [x] Create 4 template ID(s) in production for COVID Information Update
- [X] Give the template ID(s) to Rob
- [X] Receive approved content
    - [X] Update templates w/ approved content
- [ ] HOLD FOR NOW - Remove the unsubscribe language/link from Segments 1 and 2.
- [ ] Give Granicus a heads up
- [x] Update Govdelivery weight to 75 and SES to 25 in prod

# Assumptions
- This is apart of VA.gov and VetsAPI
- We need to segment the email per the below:

S1: "The Gap": Folks who signed up between when SLA first started circulating & passed until we had new KMI in place. We want to message them - hey! we need a bit more info from you. This would also include anyone who signed up early on who wasn't a registered veteran.
S2: Welcome! Folks who have signed up since the law passed (MSG: we have your info - your facility will be in touch. nothing you need to do yet!) -- Fairfax county style.
S3: OG KMI (enrolled, eligible veterans who signed up and have not been vaccinated yet)
S4: Folks who have been vaccinated. (We're thinking this is a "last message for now" kidn of thing, so we don't continue to spam them, but if we need to reach out to them in the fall for a booster, we have them.)

# Additional Info/Resources
[https://app.zenhub.com/files/257953872/3a5a6a3f-ffea-48ca-abe3-f38cb8d18d0f/download](https://app.zenhub.com/files/257953872/3a5a6a3f-ffea-48ca-abe3-f38cb8d18d0f/download)

# Out of Scope
- Two-way communication with Veteran

# Open Questions

**Comment by philherbert** [comment]
Staging:
* segment 1 - `a7c0906d-55e3-4012-ba86-f225df049335`
* segment 2 - `b6d2a96c-b29c-49a9-bfaf-c048ba4f0107`
* segment 3 - `05044bf6-8982-47bb-92e9-cb90c3168043`
* segment 4 - `027c1614-ae46-478a-b0fa-cf02150ec8bb`

**Comment by philherbert** [comment]
Production:
* segment 1 - `dd42aa9f-1309-4091-896c-2d1c5a468f59`
* segment 2 - `8f14e772-c5e2-4ae4-b40a-4ac737c06ec4`
* segment 3 - `501e0761-dea0-4eb3-84fe-9153ecf61359`
* segment 4 - `1402bb46-7b30-42e9-b710-a5e4a289a859`

**Comment by emilywu-tw** [comment]
updated all templates

**Comment by miabecker** [comment]
Updated COVID KMI content. [https://app.zenhub.com/files/257953872/b9fa805f-5465-4c1e-9651-526fca4b6938/download](https://app.zenhub.com/files/257953872/b9fa805f-5465-4c1e-9651-526fca4b6938/download)

**Comment by emilywu-tw** [comment]
updated in staging and production

**Comment by miabecker** [comment]
Tips for Veterans: Can we double check if there is an extra space between 2021 and the comma in the first sentence? ![Screen Shot 2021-04-13 at 9.28.05 AM.png](https://images.zenhubusercontent.com/5fa04193ad5a55939b83456b/9028ca68-eb6e-42bd-b6aa-b6d16fc0a7f3)

**Comment by miabecker** [comment]
Need to fix the subject line here![Screen Shot 2021-04-13 at 9.30.23 AM.png](https://images.zenhubusercontent.com/5fa04193ad5a55939b83456b/33f4fa3e-f5e2-4d52-b428-a5f7a15c7d39)

**Comment by emilywu-tw** [comment]
updated subject line for s2

**Comment by miabecker** [comment]
@emilywu-tw updated content for Segments 1 and 3 including info on the J&J vaccine. Let me know if you want to up on to discuss. [https://app.zenhub.com/files/257953872/1b1cf6c6-ceeb-43ef-b275-682b211fc1d6/download](https://app.zenhub.com/files/257953872/1b1cf6c6-ceeb-43ef-b275-682b211fc1d6/download)

**Comment by emilywu-tw** [comment]
templates updated

**Comment by miabecker** [comment]
We sent out segments 1 and 3 on 4/14. But still need to send out 2 and 4. Maria pinged Danielle for information on plans.

**Comment by miabecker** [comment]
Feedback from client on Segment 4 "The bullets on this one look small to me too, so maybe it's just a forwarding thing. The header for the J&J alert needs to be bolded though." Attached screenshots.![Screen Shot 2021-04-16 at 10.30.30 AM.png](https://images.zenhubusercontent.com/5fa04193ad5a55939b83456b/49290528-ef17-4fb5-86cc-18140dcbf73c)![Screen Shot 2021-04-16 at 10.30.37 AM.png](https://images.zenhubusercontent.com/5fa04193ad5a55939b83456b/e6c30ad4-f297-4115-a613-8473c0f94974)

**Comment by ffafara-tw** [comment]
After we fix the header, let's send the emails to them directly.
Because I think the bullet size is indeed a forwarding issue.

**Comment by miabecker** [comment]
Here are the emails to send direct too:
lauren.alexanderson@va.gov
danielle.thierry@va.gov
patrick.bateman@va.go
rhecht@governmentcio.com
maria.becker@thoughtworks.com
todd.stanich@thoughtworks.com

**Comment by emilywu-tw** [comment]
jnj header has been updated and emails sent!
