### ISSUE TITLE
Register to Google Postmaster Tool

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#413]
# Value Statement
**As** a VANotify platform admin
**I want to** see our sender reputation with Gmail
**So that** I can proactively respond to any issues that might prevent us from sending email to gmail

# Acceptance Criteria
**GIVEN** Gmail Postmaster account
**WHEN** I log in
**THEN** I can see statistics for notifications.va.gov domain

**GIVEN** Gmail Postmaster account
**WHEN** I log in
**THEN** I can see statistics for messages.va.gov domain

# Checklist
- [x] Figure out which google account to use
- [x] ESECC request to add DNS entries to authenticate notifications.va.gov domain with postmaster tool
- [x] ESECC request to add DNS entries to authenticate messages.va.gov domain with postmaster tool

# Additional Info/Resources
- Created [ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/22411#issuecomment-811173751) with Analytics team to learn how they created/manage Google account for Google Analytics

**Comment by ffafara-tw** [comment]
Submitted in scope change to RFC-005219 ESECC request.

**Comment by ffafara-tw** [comment]
Created a new google account using our VA vanotify email.

**Comment by ffafara-tw** [comment]
Domains have now be verified and we have access to statistics using the postmaster tool.
