### ISSUE TITLE
Point load tests to performance environment

### ISSUE THREAD

**Issue by saman-moshafi-va** [department-of-veterans-affairs/notification-api#415]
# Value Statement
**As** a VANotify developer
**I want to** point load tests at perf.api.notifications.va.gov 
**So that** I can run load tests in the perf environment

# Acceptance Criteria
**GIVEN** a load test is run
**AND** the load test is configured to point at perf.api.notifications.va.gov 
**THEN** the load tests run on the performance environment

# Checklist
- [x] modify `load-test.yaml` so default environment is `perf`
- [x] add performance environment variables to the postman script, `performance.postman_environment.json`
- [x] create service, template, api key etc. so load test will run
- [x] Add necessary IDs as parameters in AWS SSM
- [x] Add `Performance Dashboard` in Datadog via Terraform

Notes: 

- [x] #522

# Assumptions
- 

# Additional Info/Resources
- the performance environment is available on AWS and can be used while on VA network using its AWS ALB

# Out of Scope

# Open Questions
-

**Comment by ffafara-tw** [comment]
Since I was not able to open standard change ticket due to group assignment issue in SNOW, I created an incident INC17577799
