### ISSUE TITLE
DNS & SSL set up for UI

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#416]
# Value Statement

**As**  
**I want to** 
**So that**

# Acceptance Criteria
**GIVEN** 
**WHEN** 
**THEN**

# Checklist

DNS Entries
- [x] notifications.va.gov
- [x] dev.notifications.va.gov
- [x] staging.notifications.va.gov
- [x] perf.notifications.va.gov

SSL Certificates
- [x] notifications.va.gov
- [x] dev.notifications.va.gov
- [x] staging.notifications.va.gov
- [x] perf.notifications.va.gov

# Assumptions

- For the domains its a Service Now Standard Change but it doesn't work anymore but we tried to create an incident. 
- For SSL, ask someone to Verafi to create a certificate for us or someone from VSP Operations
- Get Karl to get access to Verafi or Filip get his Zero Token back 
- Epass Requests
- Filip needs to do this card

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by miabecker** [comment]
Need to verify where to input these tickets.

**Comment by ffafara-tw** [comment]
Incident for requesting DNS entries: INC17577799

**Comment by ffafara-tw** [comment]
Incidents for SSL:
- [ ] dev: INC17822519
- [ ] staging: INC17822589
- [ ] prod: INC17823886

**Comment by TWs-DevenS** [comment]
This is a task associated with environment provisioning and it has been completed. Request made have ben addressed. No specific QA testing necessary
