### ISSUE TITLE
Ability to utilize dynamic conditional variables

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#427]
# Value Statement
**As** VANotify customer
**I want to** be able to utilize content blocks with dynamic conditional variables
**So that** I can more granularly send content to users i.e. COVID SID unsubscribe link debacle

# Acceptance Criteria
~~**GIVEN** a conditional placeholder in a template~~
~~**WHEN** a request is made without that placeholder~~
~~**THEN** a notification is sent without the conditional content~~

**GIVEN** a conditional placeholder in a template
**WHEN** a request is made with a value for the placeholder
** AND ** Value is string that is not an empty (not just "yes", "y", "true", "t", "1", "include", "show" as it is today)
**THEN** a notification is sent with the conditional content

**GIVEN** a conditional placeholder in a template
**AND** a conditional block is dynamic i.e. uses value of the conditional placeholder
**WHEN** a request is made with a value of the placeholder
**THEN** a notification is sent with the conditional content utilizing the dynamic value
ex:
Given template ((placeholder?? Some text showing {})) 
And personalisation: {"placeholder": "foo"}
Then it renders: "Some text showing foo"

**GIVEN** a conditional placeholder in a template
**AND** a conditional block with a URL specified in markdown `[url](link)`
**WHEN** a request is made with the value of the placeholder 
**THEN** a notification is sent and the link is rendered correctly

# Checklist
- [ ] 

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
- How should we use placeholder inside conditional block. In the example {} was used just for illustration purposes. Something else can be used.

**Comment by ffafara-tw** [comment]
The first AC unfortunately cannot be done at this time.
We need to decouple template preview first, as the code generates preview when placeholder is missing.

**Comment by ffafara-tw** [comment]
The conditional placeholder still needs to be present in the request.
To not render the block it can be empty string or a false boolean, ex:
```
"placeholders":  {
  "conditional": ""
}
```
or 
```
"placeholders":  {
  "conditional": false
}
```

**Comment by ffafara-tw** [comment]
Placeholder names only allow alpha numberic characters, space and dash, now

**Comment by ffafara-tw** [comment]
Tested with following template content:
```
#Let's demo some template features
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Id velit ut tortor pretium viverra. Eget est lorem ipsum dolor sit amet consectetur adipiscing elit. Etiam tempor orci eu lobortis elementum nibh tellus molestie nunc. Euismod quis viverra nibh cras pulvinar mattis nunc. Sit amet est placerat in egestas erat imperdiet sed euismod. Tincidunt lobortis feugiat vivamus at augue.

Elementum curabitur vitae nunc sed velit dignissim. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Vulputate mi sit amet mauris commodo quis imperdiet. Dui faucibus in ornare quam viverra orci sagittis. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce.

* __First item__
Lorem ipsum dolor sit amet consectetur adipiscing elit, dictumst imperdiet vivamus tempor erat lacus cras nascetur, semper tortor pretium sodales fames augue. Eget congue sit lacus penatibus metus ultricies mauris, nam parturient habitasse nisl hendrerit quam, netus fusce neque fringilla platea molestie.
* __Second item__
Lorem ipsum dolor sit amet consectetur adipiscing elit, dictumst imperdiet vivamus tempor erat lacus cras nascetur, semper tortor pretium sodales fames augue. Eget congue sit lacus penatibus metus ultricies mauris, nam parturient habitasse nisl hendrerit quam, netus fusce neque fringilla platea molestie.

	Lorem ipsum dolor sit amet consectetur adipiscing elit, dictumst imperdiet vivamus tempor erat lacus cras nascetur, semper tortor pretium sodales fames augue. Eget congue sit lacus penatibus metus ultricies mauris, nam parturient habitasse nisl hendrerit quam, netus fusce neque fringilla platea molestie.

((url??This whole block will be conditional. It can include url: [Link]({}) ))

^Paragraph spacing also works block quote

^Lacus ut hendrerit commodo ultrices rhoncus aliquam sollicitudin nullam mattis, dui suspendisse massa leo aliquet justo etiam molestie, convallis pulvinar euismod condimentum sapien adipiscing accumsan inceptos. Mauris phasellus placerat ut maecenas felis diam donec faucibus, consectetur platea quis vehicula egestas himenaeos vestibulum aliquam dictum, risus gravida cras tincidunt nascetur hendrerit netus.
```

**Comment by TWs-DevenS** [comment]
All tests have been performed with both Phil and Filip.  
Test Plan 
The following test data was used to test for :True - and :"False" (string)  - Pass conditions
and :False (fail condition)
((url??This whole block will be conditional. It can include url: [Link]({}) )) 


This ticket can be closed
