### ISSUE TITLE
Login using Github and find or create VANotify corresponding user

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#432]
# Value Statement
**As** VANotify user
**I want to** login into VANotify using Github
**And** for the VANotify platform to find or create corresponding user
**So that** my identity and corresponding permissions are authenticated

# Acceptance Criteria
**GIVEN** a  Github user that has not previously logged in to VANotify
**WHEN** they click login with Github
**AND** they authenticate
**THEN** VANotify creates a user account using their Github profile information
**AND** a set of permissions (TBD) is assigned to that user
**AND** their name is visible in the UI

**GIVEN** a Github user that has previously logged in to VANotify
**WHEN** they click login with Github
**AND** they authenticate
**THEN** VANotify loads their user account 
**AND** their associated permissions using their Github profile information
**AND** their name is visible in the UI

**GIVEN** a user clicks login with Github to VANotify
**WHEN** they are not part of the Department of Veterans Affairs Github organization
**THEN** the login attempt is rejected
**AND** the error is surfaced to the user as "Your account was not found."

**GIVEN** a  Github user that has not previously logged in to VANotify
**WHEN** they click login with Github
**AND** they authenticate
**AND** they do not grant OAuth permissions to VANotify app
**THEN** they are presented with a useful message on the UI

**GIVEN** a  Github user that has not previously logged in to VANotify
**WHEN** they click login with Github
**AND** they fail authenticated
**THEN** Github redirects the user ~~back to the login page~~ to a failure page with a message.

# Checklist
- [x] modify user model:
  - don't require password and auth_type, and add optional field `identity_provider_user_id`
  - [x] db schema
  - [x] python model
  - [x] endpoints to create / update users
- [x] update your existing user object to add your github user id 
- [ ] create a github oauth app for each environment and transfer ownership to the `department-of-veterans-affairs` organisation (reach out to Zach Koppert - or other admins)
  - [x] dev - transferred `VANotify (dev)` app
  - [x] staging
  - [ ] perf (PART OF A DIFFERENT STORY NOW)
  - [ ] prod (PART OF A DIFFERENT STORY NOW)
  - FYI, Slack thread regarding transfer of oauth apps to VA and VA's Github org admin info: https://vaoitdevops.slack.com/archives/CKMQBNBPG/p1620053786017700. va-delivery@github.com is the admin group.

~~mock github locally using mountebank - see [here](https://docs.authlib.org/en/latest/client/flask.html#configuration)) for notes on configuring authlib urls~~ (removed from requirements after conversation in dev sync about how this is no longer that valuable)

- [x] on login:
  - [x] use the github api to check that the user is a member of the organisation, fail if not
    - [x] return 401 when getting 404 error
  - [x] lookup user by github's user id, return token for user if there is a matching entry
  - [x] create a user account with github user information if there is no match
- [x] more descriptive logs
- [x] exceptions handling
- [x] cookie settings include samesite = lax, and session_cookie_secure=True
- [x] Review documentation in additional info
- [x] Run error message by Todd

# Assumptions
- The user accounts that are created via API vs. those from Github are different i.e. Github will have no password. This implies we may need to make changes to the database schema.

# Additional Info/Resources
- https://docs.github.com/en/rest/reference/users#get-the-authenticated-user

# Out of Scope
-

# Open Questions
-

**Comment by lingtran** [comment]
When username or password incorrect, Github redirects to login page stating incorrect credentials.
When mfa code incorrect, it stays on the two-factor page and flashes message "Two-factor authentication failed".

When 'cancel' granting access, we currently get 500 error

**Comment by ffafara-tw** [comment]
Let's make sure to have correct settings on the cookies (session during oauth and the one with our access token):
- SameSite: 'Lax'
- HttpOnly
- Secure

**Comment by ffafara-tw** [comment]
Also let's make sure that we handle all exceptions and always return 401 and redirect to a failure page on the UI.

**Comment by lingtran** [comment]
```
curl -v \
  -H "Authorization: token <INSERT TOKENHERE> Accept: application/vnd.github.v3+json" -I \\
  https://api.github.com/orgs/department-of-veterans-affairs/members/<your login>
```

scopes to play with in the registry `user:email,read:user,read:org` (in combo or standalone)

**Comment by philherbert** [comment]
Our OAuth App has been transferred in dev, and we've observed the following behaviour when hitting `/user/memberships/orgs/department-of-veterans-affairs`:

* if the user is part of the organisation, we get a 200 response, as described [here](https://docs.github.com/en/rest/reference/orgs#get-an-organization-membership-for-the-authenticated-user)
* if the user is not part of the organisation (we created a user and put creds in 1pass), we get a 404

**Comment by vikarus-tw** [comment]
Requests for changes to an OAuth app owned by the department-of-veterans-affairs organization must go through the organization owner. They can be reached to facilitate a change either through email at <va-delivery@github.com> or by opening an issue at https://github.com/department-of-veterans-affairs/github-user-requests/ .

**Comment by vikarus-tw** [comment]
Edge case:
Same user has 2 separate accounts
Account 1 is made with email <email-1>, and password, on VANotify
Account 2 is made using github, where their primary email is <email-2>
The user then switches their primary email to <email-1>,
then logs into VANotify.
Which account do we prioritize/preserve? Which do we archive?
Same situation can apply if Accounts 1 and 2 are reversed in order of creation.

**Comment by ffafara-tw** [comment]
We do not archive automatically.
When logging in using Github, we use Github identifier to match the account. Email is irrelevant in the authentication process.
The question is: Do we make sure that our account's email matches the one from Github? (Is email a unique column?)

**Comment by TWs-DevenS** [comment]
Validation Scenarios
**Creating a Login Account for you**
During the Account creation process we see your existing a/c with password authentication, i.e.
We first try to match an account with email. If github email account matches the user account, we then look for a match on Github Id to either create a new account or error out..  
To create a new account  
1. If not matched on **Github Provider id,** to create a new account
we first look for a match on (same) email 
If good and not tied to another Github Provider id
We use it and Update the Github User ID

2. if we find a user account by email, but is tied to Github provider id that is different
We should throw an error

3. if we do not find an existing email or account then we create a new Account.

**Comment by TWs-DevenS** [comment]
All Sequence diagrams associated with this user story have been created.  https://github.com/department-of-veterans-affairs/vanotify-team/tree/master/documents/architecture

**Comment by TWs-DevenS** [comment]
Sequence Diagrams have been updated after confirming with FIlip. 
All scenarios have passed as demonstrated by Phil 
This ticket can be closed

**Comment by TWs-DevenS** [comment]
Attached is the Exploratory TesT Case scenarios to manually test the conditions where a new user would be created.
