### ISSUE TITLE
Add build pipeline to Perf Environment

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#436]
# Value Statement

**As** VANotify Owner

**I want to** be able to deploy API code changes to the perf environment
**that** will not be deployed anywhere else
**So that** I can safely run performance experiments

# Acceptance Criteria
**GIVEN** a branch on notification-api with code changes
**WHEN** I want to build and deploy those changes to perf environment
**THEN**  I can trigger a pipeline that will create a deployment artifact containing those changes 
**AND** deploy it to perf environment

# Checklist
- [x] Separate build pipeline that responds to manual triggers
- [x] Store build artifacts in separate ECR
- [x] Perf deployment pipeline that will be able to use those artifacts
- [x] Must be able to deploy regular artifacts to perf as well

# Assumptions
- Both build and deployments can be triggered manually 

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by lingtran** [comment]
Successfully deployed to PERF!!!!!!!!!
![Screen Shot 2021-06-08 at 5.00.06 PM.png](https://images.zenhubusercontent.com/5ecea5442d18e437e3b23d00/7db65709-48ce-44e2-a982-5f80259cdcb8)

**Comment by miabecker** [comment]
Congrats @lingtran well done!

**Comment by lingtran** [comment]
Pushed to `test-perf` branch a little tweak to the healthcheck endpoint to indicate that this is specific to the latest image pushed to the perf environment. Change is highlighted in the magenta rectangle.

![Screen Shot 2021-06-11 at 1.31.01 PM.png](https://images.zenhubusercontent.com/5ecea5442d18e437e3b23d00/63c37c61-1f42-4057-b7b3-c2264b093699)

**Comment by lingtran** [comment]
- Look into where we create ECR. Ideally create repo via terraform. Want to add lifecycle policy to clear image two weeks from respective creation date (age-based).

**Comment by lingtran** [comment]
Will move to ready for sign off when last item is done

**Comment by lingtran** [comment]
Confirming made changes to create perf aws ecr resource in our base infrastructure stack - includes lifecycle policy to clear images 14 days after their push date. Triggered a perf build and deploy after making the infra changes to verify.
