### ISSUE TITLE
Write Cypress test that you can execute locally 

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#440]
# Value Statement
**As** a VANotify developer
**I want to** execute cypress end to end tests locally
**So that**I can validate the happy path

# Acceptance Criteria
**GIVEN** a notification UI repository
**WHEN** a developer runs the NPM/yarn command
**THEN** Cypress test suite is executed

# Assumptions
- Run against headless chrome
- Run against chrome

**Comment by TWs-DevenS** [comment]
Reviewed the cypress install and ability to invoke the VA Notify UI using cypress commands.
Reviewed test execution on chrome and headless browser mode.

![image.png](https://images.zenhubusercontent.com/604f66cb300e975b0fa212d7/d19d6bce-f5a3-4b2c-a77f-3eaf1683be88)

**Comment by TWs-DevenS** [comment]
Closing ticket as the acceptance criteria has been met.
