### ISSUE TITLE
Adding VA Design system library to the UI application

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#443]
# Value Statement
**As** VANotify Developer
**I want to** add the VA Design system library to the UI application
**So that** I can use approved styling and design systems for page layouts

# Acceptance Criteria
**GIVEN** the notification UI
**WHEN** you navigate to the homepage
**THEN** the UI uses page layout, header and design from the VA.gov design system

**GIVEN** the notification UI
**WHEN** you navigate to the homepage
**THEN** the header has a VANotify logo
**AND** Log In with Github Button

# Additional Info/Resources
- https://design.va.gov/
- https://design.va.gov/documentation/developers
https://design.va.gov/storybook
- Header design - https://www.sketch.com/s/c09aa989-7947-4261-84c6-4a138e77fe28

# Open Questions

- Do we want to use react?

**Comment by TWs-DevenS** [comment]
This issue can be closed
The screen has been reviewed 
All acceptance criteria have been satisfied

(Please add screenshots )

**Comment by emilywu-tw** [comment]
<img width="1338" alt="Screen Shot 2021-05-14 at 4 36 35 PM" src="https://user-images.githubusercontent.com/34494609/118326175-9c19cb00-b4d2-11eb-93f6-14ac56779b23.png">
