### ISSUE TITLE
Push Notifications Phase 1

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#456]
## Goal
Be able to send push notifications

## Scope
We will utilize VEText to send the push notifications with a VA Notify endpoint with the understanding that we will remove VEText from this process in a future phase.

## Limitations
The template will be created/managed in VEText and later replaced by a VA Notify template. This means minor rework will be needed by the business line to replace these IDs if we are unable to replicate them.

**Comment by zlaw** [comment]
@mjones-oddball

**Comment by Eallan919** [comment]
leaving open until Phase 1 is LIVE
