### ISSUE TITLE
Execute Cypress tests in the pipeline

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#464]
# Value Statement
**As** a VANotify owner
**I want to** end to end cypress tests to be automatically executed as apart of CI/CD pipeline
**So that** the critical user journeys are tested for each build

# Acceptance Criteria
**GIVEN** a notification UI repository
**WHEN** a developer pushes a commit
**AND** unit tests have passed
**AND** to deployment to the Dev environment has succeeded
**THEN** Cypress tests are executed as part of CI/CD against the Dev environment
**AND** test results are visible in github action log

# Checklist
- [x] Checklist item here

# Assumptions
- Run against headless chrome

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
- Do we run against mocked API? -> We will run against real notifiation-api, which should have all third parties mocked (SES, Granicus, VAProfile, MPI)
- Do we use Github self-hosted runners or do we launch an EC2 instance/ECS task that can run UI tests?

**Comment by ffafara-tw** [comment]
Discussed during dev sync on 5/4/2021.
We agreed on two-fold approach:
1. Investigate usage of self hosted workers with Github SMEs (Zack Koppert) in terms of security, availability in VA, etc.
2. Start working on the ECS route:
 - [ ] Create a docker image with chrome browser and cypress test code
 - [ ] Test docker image locally and in ECS
 - [ ] Use docker caching/two-stage build to limit the build time
 - [ ] Make action status code corresponds to test outcome (fail pipeline when tests fail)
 - [ ] Figure out how to make test artifacts (logs, screenshot) available in github action log (potentially use S3)
