### ISSUE TITLE
Covid KMI Communication #9

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#465]
# Value Statement

**As** a Veteran, spouse, caregiver, or CHAMPVA recipient 
**I want to** to understand the latest update on the J&J vaccine
**So** I know what it means for me.

# Acceptance Criteria
**GIVEN** a Veteran, spouse, caregiver, or CHAMPVA recipient has expressed interest via the COVID Vaccination Interest Form(s) on VA.gov and the VA has information to communicate
**WHEN** VA.gov sends a request to VEText API
**THEN** VANotify will send an informational email 

# Checklist

- [x] Receive draft content
- [x] Create template ID(s) in staging for COVID Information Update
  - id: `584f6dc7-18ef-4ee9-8e23-73de5baabca2`
  - name: `KMI #9 2021/04/27`
- [x] Create template ID(s) in production for COVID Information Update
  - id: `defd0e54-e1e8-4910-9b9f-b9298eff9646`
  - name: `KMI #9 2021/04/27`
- [x] Give the template ID(s) to Rob
- [x] Receive approved content
- [x] Update templates w/ approved content

# QA Checklist

**Business:**
- [x] Subject Line
- [x] Content
- [x] Spelling
- [x] Punctuation
- [x] Link Destination
- [x] Link Functionality
- [x] Footer
- [x] Contact information i.e. Phone Numbers or Emails

**Business/VANotify:**
- [x] Link Clickable
- [x] Formatting

**VANotify:**
- [x] Personalization is correctly rendered

**VEText:**
- [x] Unsubscribe Functionality
- [x] User Segmentation
- [x] Correct personalization provided

# Assumptions
- This is apart of VA.gov and VetsAPI

# Additional Info/Resources

[https://app.zenhub.com/files/257953872/f28df97e-6cfc-4f11-903d-744ec1085d6a/download](https://app.zenhub.com/files/257953872/f28df97e-6cfc-4f11-903d-744ec1085d6a/download)

Edits Round #2
[https://app.zenhub.com/files/257953872/779f75a6-71c4-4792-9cc2-35f141cf51d6/download](https://app.zenhub.com/files/257953872/779f75a6-71c4-4792-9cc2-35f141cf51d6/download)

# Out of Scope
- Two-way communication with Veteran

# Open Questions

**Comment by miabecker** [comment]
@lingtran Another round of updated content here.

**Comment by miabecker** [comment]
@shanemelliott

**Comment by miabecker** [comment]
@lingtran can we do a test send to these emails: 

lauren.alexanderson@va.gov
danielle.thierry@va.gov
patrick.bateman@va.go
rhecht@governmentcio.com
maria.becker@thoughtworks.com
todd.stanich@thoughtworks.com

**Comment by shanemelliott** [comment]
- [ ] Unsubscribe Functionality - Unsubscribed Patrick. 
- [ ] User Segmentation - Only one Segment. 
- [ ] Correct personalization provided -  Need More detail
- [ ] Links Checked. -

**Comment by miabecker** [comment]
Went through checklist with @Shaneelliott
