### ISSUE TITLE
Configure which notification statuses trigger callbacks

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#468]
# Value Statement

**As**  a VANotify client
**I want to** configure which notification statuses trigger callbacks
**So that** I can only get responses I am interested in e.g. permanent failures

Business use case: VEText is sending KMIs (700k emails), but is not interested in successes. However! They should be interested in permanent failures, because they should remove addresses from their list.

# Acceptance Criteria

**GIVEN** a service with a callback
**WHEN** I configure callback for specific statuses (see assumption for full status list)
**AND** a notification for that service enters one of those specified statuses
**THEN** VANotify will execute the callback

**GIVEN** a service with a callback
**WHEN** I configure callback for specific statuses (see assumption for full status list)
**AND** a notification for that service enters a status that was not specified
**THEN** VANotify will not execute the callback

**GIVEN** a request to create or update a service callback
**WHEN** that request does not contain any statuses
**THEN** that request should be rejected as invalid (400), and should provide a helpful message

# Checklist
- [x] Update service callback DB model to include list of statuses
- [x] Update endpoints to update/create service callbacks
- [x] Add conditional logic to wherever the callback is triggered

# Assumptions

- Notification statuses: sending, sent, technical failure, permanent failure, temporary failure) 

# Additional Info/Resources

`app/service/service_callback_api_schema.py`
`app/service/callback_rest.py`

https://webhook.site/ - a handy site for testing webhooks or https://httpreq.com/fragrant-thunder-5i8ao36t as it doesn't check whether bearer token is valid

Use AWS Email Simulator to test those different statuses?

# Out of Scope
-

# Open Questions
-

**Comment by saman-moshafi-va** [comment]
verified it is working in dev using:
[https://httpreq.com/fragrant-thunder-gi8ao36t](https://httpreq.com/fragrant-thunder-gi8ao36t)
PS: the url in service call back should be [https://httpreq.com/fragrant-thunder-gi8ao36t/record](https://httpreq.com/fragrant-thunder-gi8ao36t/record)

**Comment by TWs-DevenS** [comment]
[https://app.zenhub.com/files/257953872/8b9050b4-41ca-4f5f-baa9-71c71696d751/download]

Manual Exploratory Test Scenarios that were executed are attached. 

All Acceptance Criteria have been met. Closing ticket.
