### ISSUE TITLE
Handle insufficient Github scopes scenario

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#479]
# Value Statement
**As** a VANotify user
**I want to** receive informative error messages during authentication process
**So that** I know how I can correct the problem

# Acceptance Criteria
**GIVEN** a VANotify user
**THAT** has not granted all required OAuth scopes to VANotify
**WHEN** they log in
**THEN** they should be presented with authentication failure screen with information about lack of necessary Github OAuth scope/permissions

# Assumptions
- VANotify needs: `read:user, user:email, read:org` scopes to perform all user validations and retrieval of information. When user is presented with Github Oauth approval screen they can limit the scopes they want to approve.

# Additional Info/Resources
- https://docs.github.com/en/rest/guides/basics-of-authentication#checking-granted-scopes
- Implementation from dotnet that performs scope validation for email that can server as reference:
https://github.com/dotnet/aspnetcore/issues/17905
- [doesn't seem possible to revoke only some scopes](https://github.community/t/edit-scopes-granted-to-an-oauth-app/125119)

# Out of Scope
-

# Open Questions
-

**Comment by ffafara-tw** [comment]
@miabecker @philherbert - please review

**Comment by TWs-DevenS** [comment]
Reviewed Test Approach with Emily. We will be adding a unit /integration level test for the happy path.  Manual exploratory test scenarios will be included to verify the

**Comment by emilywu-tw** [comment]
<img width="1459" alt="Screen Shot 2021-07-21 at 2 13 36 PM" src="https://user-images.githubusercontent.com/34494609/126647219-fb4ce373-2123-4c68-b47f-8ddd9a2d8658.png">
<img width="1316" alt="Screen Shot 2021-07-21 at 2 14 56 PM" src="https://user-images.githubusercontent.com/34494609/126647230-10e9ec00-1fe0-4aec-9314-352df9db54a5.png">
