### ISSUE TITLE
[Spike] Use Ruby client library as part of vets-api integration

### ISSUE THREAD

**Issue by kennedycollins** [department-of-veterans-affairs/notification-api#48]
As a vets-api developer
I want to have access to Notify client library
So that I can send notifications via VA Notify service.

Consider using or forking GDS client library: 
https://docs.notifications.service.gov.uk/ruby.html#send-a-message-2

If using we need to find a way to override url. There might be a pull request from CDS to GDS that has some information about that.

Checklist:
- [x] setup vets-api local development environment
- [x] add notify ruby client gem
- [x] add necessary client configuration

**Comment by ffafara-tw** [comment]
Should we fork this:
https://github.com/ministryofjustice/govuk_notify_rails
to wrap notification-ruby-client in ActionMailer delivery-method?
