### ISSUE TITLE
Enabling Cypress to login to the self-service UI without utilizing Github Oauth 

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#483]
# Value Statement
**As** VANotify platform using cypress to test the self service UI
**I need** Cypress to able to log in to the API with an email address and a password
**So that** Cypress can test login without authenticating via Github Oauth process

**IN DEV AND STAGING!**

# Acceptance Criteria

**GIVEN** a cypress test has been started
**WHEN** cypress is verifying authenticated behavior
**THEN** cypress logs in to the API using an email and password
**AND** tests are then ran using the authenticated cypress user

**GIVEN** a user makes an API request to /login
**WHEN** in a lower environment i.e. dev or staging
**AND** that request contains a valid email address and password for an existing user
**THEN** the api response includes a JWT representing that existing user

**GIVEN** a user makes an API request to /login
**WHEN** in a lower environment i.e. dev or staging
**AND** that request contains an invalid email address and password
**THEN** the api response is a 401 error

# Checklist
- [x] Feature toggles, only in dev and staging
- [x] Add new flask endpoint with no authentication
- [x] Endpoint should take email address and plaintext password
- [x] Lookup user by email address
- [x] Hash password and compare to stored hash!
- [x] Return JWT representing the user if all is well
- [x] Call that endpoint in the cypress tests!

# Assumptions
- User Name and Password are stored in VAEC SSM
- Acknowledge this approach is a slight gap in terms of testing the reality of user behavior re: logging in with Github Oauth, but the work required to test this at this moment outweighs the gap

# Additional Info/Resources
- Please consult ADR for full detail on how to implement this story: https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/documents/adr/0012-authenticating-in-cypress.md

- Reverse proxy configuration has to be updated here:
https://github.com/department-of-veterans-affairs/devops/tree/master/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2#L255

# Out of Scope
- refactoring auth endpoints and proxy changes have been moved to #489 

# Open Questions
-

**Comment by TWs-DevenS** [comment]
Performed testing by
created new user and changed password
you get a 500 status which is not correct

**request** 
{
    "email_address": "deven.satoskar@thoughtworks.com",
    "password": ""
}

**response**
{
    "message": "Internal server error",
    "result": "error"
}

**Comment by saman-moshafi-va** [comment]
the user was in `pending` state which is the reason for the error.  This should be raised as a bug as even verify password which is an existing endpoint was raising the same error and http 500.

**Comment by TWs-DevenS** [comment]
Verified all 3 scenarios,  all meet the acceptance criteria.  For the failed user story scenario, the Failed status received was 401 Unauthorized user and not 403 Forbidden.  The acceptance criteria needs to be updated to reflect 401 and not 403.  Moving the ticket to Signoff
