### ISSUE TITLE
Exclude new auth endpoints from reverse proxy

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#489]
# Value Statement
**As** a VANotify developer
**I want to** protect sensitive endpoints from exposure to the public internet
**So that** our attack surface is reduced

# Acceptance Criteria
**WHEN** a request is made to VANotify using the public reverse proxy (ie `api.va.gov/vanotify`)
**AND** that request is for one of the new auth endpoints ('`/login`, `/authorize`, `/logout`, `/redeem-token`)
**THEN** the request is rejected (`404`)

# Checklist
- [x] Nest all our new auth endpoints under a common path (eg `.../auth/login`)
- [x] Exclude that path from the reverse proxy (https://github.com/department-of-veterans-affairs/devops/blob/master/ansible/deployment/config/revproxy-vagov/templates/nginx_api_server.conf.j2)
- [x] Change the OAuth app to point to the new url (make a request to the github admins by emailing va-delivery@github.com)
- [x] Change the UI to point to the new urls

**THINGS TO TEST!**
- [x] When I make requests to public URLs (eg  `api.va.gov/vanotify`), none of the new endpoints are reachable! (See the AC above) - can test with postman
- [x] Signing in on UI still works, and is using the new endpoints (verify using the chrome network debugger)
- [x] The UI's Cypress tests still work

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by philherbert** [comment]
@miabecker @ffafara-tw a new story for your perusal

**Comment by miabecker** [comment]
@philherbert makes sense to me but we can review it in a story writing session and make sure it gets prioritized appropriately.
