### ISSUE TITLE
Use parameter store for configuration variables and secrets

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#49]
As a notification developer, I want my parameters to be stored outside of task definitions

Acceptance criteria:
**GIVEN** a parameter storage exists
**WHEN** I need to store parameters 
**THEN** they are stored in aws parameter store as a string

**GIVEN** a parameter storage exists
**WHEN** I need to store secrets
**THEN** they are stored in aws parameter store as a secret string

**GIVEN** I have a task defined in fargate
**WHEN** I run the task 
**THEN** the environment variables are pulled from aws parameter store

Checklist:
- [x] Set up a KMS key for encrypting secrets (might not be necessary - there should be a default key)
 - notify-deploy-user should have access to decrypt key
- [x] Store all environment variables defined in `container_definition.json.tpl` in parameter store 
- [x] Any secrets should be stored as SecuredString with the above KMS key for encryption
- [x] In template file (service.tf), replace vars values with values from parameter store
- [x] Pass the `notify_environment` environment variable into terraform in the pipeline

Additional info:
https://www.terraform.io/docs/providers/aws/d/ssm_parameter.html
for more info on KMS: https://aws.amazon.com/kms/getting-started/

**Comment by kennedycollins** [comment]
Desk check - show that params are available in AWS & the values aren't showing up in the container definition.
