### ISSUE TITLE
Update Pharmacy Prescription Template in Production

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#495]
# Value Statement
**As** VEText Business Line Customer
**I want to** update the pharmacy prescription notification template
**So that** it reflects the content I want it too

# Acceptance Criteria
**GIVEN** a pharmacy notification 
**WHEN** triggered by VEText
**THEN** the updated pharmacy template is utilized

# Checklist
- [x] Template id in staging is: d0de2d2d-3eea-49cd-80d8-45694459857d
- [x] Template id in production is: e4fb8ea7-fcf4-4732-ba83-96f7a0cbce2f

# Assumptions
-

# Additional Info/Resources

Current template:
```
((facility_name)): Your ((prescription)) with RX# ending in ((rx_last4)) has shipped.\n\nTrack your shipment:\n((tracking_link))
```

Note: There are no new placeholders, as the tracking_link placeholder is already supported by the existing template.
This may facilitate implementing the conditional logic that Filip mentioned: if tracking_number is a non-false value then use the original template, otherwise if tracking_link is available then use the above new template.
There are no new placeholders, as the current template already includes them.

Link to relevant channel: https://dsva.slack.com/archives/C01D2T36XLL/p1623356949044000?thread_ts=1623080778.033400&cid=C01D2T36XLL

# Out of Scope
-

# Open Questions
-

**Comment by ffafara-tw** [comment]
Updated template to use conditional placeholders to facilitate a smooth transition to messages that include tracking link instead of tracking number.

```
((facility_name)): Your ((prescription)) with RX# ending in ((rx_last4)) has shipped.((carrier?? {} ))((tracking_number??tracking number {}.))\n\n((tracking_link??Track your shipment:))\n((tracking_link??{}))
```

Tested in staging:
Following payload:
```
{
    "template_id": "{{template-id}}",
    "phone_number": "+1xxx",
    "personalisation": {
        "facility_name": "VA facility",
        "prescription": "Some med",
        "rx_last4": "1234",
        "carrier": "",
        "tracking_number": "",
        "tracking_link": "http://test.com"
    }
}
```
Produced:
![with_tracking_url.png](https://images.zenhubusercontent.com/5da0974a66de7b0001e4d835/e084cba3-935b-43cd-9ef6-238dc74adf12)

Following payload:
```
{
    "template_id": "{{template-id}}",
    "phone_number": "+1xxx",
    "personalisation": {
        "facility_name": "VA facility",
        "prescription": "Some med",
        "rx_last4": "1234",
        "carrier": "UPS",
        "tracking_number": "1231231",
        "tracking_link": ""
    }
}
```
produced:
![with_tracking_number.png](https://images.zenhubusercontent.com/5da0974a66de7b0001e4d835/6aa43d62-0bca-4fb0-ae68-78da821fecb9)

**Comment by ffafara-tw** [comment]
Verified in production as well.
