### ISSUE TITLE
Use multilayer docker builds to reduce image size

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#497]
# Value Statement
**As** a VANotify developer
**I want to** reduce the size of `notification-api` docker images
**So that** our images take up less space in AWS ECR, and are pushed/pulled faster

# Acceptance Criteria
**WHEN** `notification-api` is building
**THEN** the build process uses multistage builds
**AND** build-time dependencies are stripped from the final image

# Checklist
- [ ]

# Assumptions
-

# Additional Info/Resources
- Multistage builds: https://docs.docker.com/develop/develop-images/multistage-build/
- One approach, using an `/install` directory: https://blog.realkinetic.com/building-minimal-docker-containers-for-python-applications-37d0272c52f3
- Another approach, using virtualenvs: https://pythonspeed.com/articles/multi-stage-docker-python#solution-2-virtualenv

# Out of Scope
-

# Open Questions
-

**Comment by mjones-oddball** [comment]
@kalbfled Please read the task description. Would you consider this task still needed given the changes we've recently done? Cc @k-macmillan

**Comment by kalbfled** [comment]
@mjones-oddball I think #603 is duplicate.
