### ISSUE TITLE
SPIKE: Track SMS spam rate

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#499]
It's a good idea to track the number of instances our text messages are marked as SPAM by carriers.
Some ideas from our Canadian colleagues:
https://github.com/cds-snc/notification-terraform/commit/5413e2813e7413b3bab7d8929b15783a1d78e65b

Tip: Hard bounce and soft bounces are sprinkled throughout the logs

- [ ] What is the SMS spam limit?
- [ ] Where are we currently at related to that (use support if needed)?
- [ ] How can we better track our spam rate?
- [ ] Document findings

**Comment by ffafara-tw** [comment]
@miabecker @philherbert fyi

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/499?planning-poker) with Zenhub @kalbfled @EvanParish @trevor2718 @k-macmillan

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/499?planning-poker) with Zenhub @ianperera
