### ISSUE TITLE
Merge existing callback implementations

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#503]
# Value Statement

**As** a VANotify developer
**I want to** use the same endpoints and tables to manage both service callback API objects
**AND** service inbound API objects
**So that** duplication is reduced

# Acceptance Criteria
**GIVEN** an api request is made to create a service callback
**WHEN** the `callback_type` is `delivery_status` or `complaint`
**THEN** VANotify stores callback information in the service callback table with the type `delivery_status` or `complaint`

**GIVEN** an api request is made to create a service callback
**WHEN** the `callback_type` is `delivery_status`
**AND** the request contains a list of notification statuses
**THEN** VANotify stores callback information in the service callback table with the type `delivery_status` and notification statuses

**GIVEN** an api request is made to create a service callback
**WHEN** the `callback_type` is `inbound_sms`
**AND** the request contains a list of notification statuses
**THEN** 400 error is returned

**GIVEN** an api request is made to create a service callback
**WHEN** the `callback_type` is `inbound_sms`
**THEN** VANotify stores callback information in the service callback table with the type `inbound_sms`

**GIVEN** a service has a callback configured
**AND** the `callback_type` is `inbound_sms`
**WHEN** VANotify receives an inbound SMS for that service
**THEN** the inbound SMS is sent to the service using the callback

**GIVEN** a service has a callback configured
**AND** the `callback_type` is `delivery_status`
**WHEN** VANotify receives a status update for that service
**THEN** the delivery status is sent to the service using the callback

# Checklist

- [x] Merge `ServiceInboundApi` into `ServiceCallbackApi` by expanding `service_callback_type` to include `inbound_sms`
- [x] Ensure appropriate Data Migrations are in place  - as a separate commit
- [x] Rename `ServiceCallbackApi` to remove reference to API - just `ServiceCallback`?
- [x] Validate that we can create Complaint and Inbound callbacks without specifying `notification_statuses`
  - [x] And if not, make `notification_statuses` nullable when `callback_type` is not `delivery_status` (using check constraints)
- [x] Remove `ServiceInboundApi`-specific endpoints
- [x] Regression test to ensure email still works as intended

# Assumptions
- 400 error means you are trying to add notification statuses to a callback that doesn't require statuses e.g. inbound SMS or complaints

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by TWs-DevenS** [comment]
**Test Approach**
Reviewed Unit Test Case with Vikram. Updated a unit test to address an acceptance criteria for this ticket.  Now all the ACs have corresponding Unit/Integration tests that have all been executed and passed. 
**Regression Test:** All unit tests that support service callback API objects (before change is implemented) were executed as a regression test and they all pass. 
The test coverage to  test the merging of the callback implementation is sufficiently met at the Unit / Integration test.
