### ISSUE TITLE
Provision staging environments

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#51]
**As a** VA Notify developer
**I want to** have a staging environment.

Acceptance criteria:
**WHEN** I push code
**AND** the tests and deployment to development succeed
**THEN** the pipeline provisions the staging environment

Checklist:
- [ ] ~using terraform workspaces -> need to have discussion on use of this (if we use this, we need to change S3 permissions and buckets used per environment)~
- [x] NEW: have a further discussion about workspaces just to make sure everyone is on the same page about not using them, and invite @punitladtw 
- [x] parameterize the resources used in terraform by extracting out variables (into tfvars?) (to have identical resources in staging as we have in development)
- [x] create a new workflow file for staging
  - [x] to trigger it: create a tag at the end of the development pipeline, and listen for new tags in the staging pipeline
  - [x] create staging pipeline
- [x] change name for terraform backend bucket (currently `terraform-notification-test`) and keys (currently things like `notification-api-dev-db.tfstate`) to remove environment names and make them more consistent
- [x] Investigate how to set region in backend by a script (you cannot use variables in backend)
- [x] ~update cidr block calculation based on environment and vpc cidr~ -> we decided that this is not worth doing at this point, as we will be given the ranges when we move to VA. Right now, it is fine to keep them as the same values and reference the subnets via id.

 
Resources:
https://medium.com/capital-one-tech/deploying-multiple-environments-with-terraform-kubernetes-7b7f389e622
https://codurance.com/2020/04/28/terraform-with-multiple-environments/
https://www.terraform.io/docs/cloud/guides/recommended-practices/part1.html

Assumptions: 
* Scope for this story only includes provisioning, the deployment was separated and will be part of #79 

Questions:
- How many days do we want to retain the cloudwatch logs in each environment? (dev, staging, prod)
   - Resource for options for the number of days: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html
- Do we need a new task definition json for each environment? (right now, we are hardcoding "dev" into all the json files) **Yes**, one yml file per environment
- Do we need to parameterize the name of the docker containers? (this is set up in the task definitions) **No**

**Comment by saman-moshafi-va** [comment]
I talked with Filip and creating tag for each deployment to staging is the most feasible action.

**Comment by marisahoenig** [comment]
With git tagging, possible approach:
- https://github.com/actions/github-script

Resource:
- https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by ffafara-tw** [comment]
Why not just use git tag?

**Comment by lingtran** [comment]
[Tagging and CI visual flow](https://app.mural.co/t/thoughtworksveteransaffairs4407/m/thoughtworksveteransaffairs4407/1593186258007/a23b95bf270e242409c46afb78aee0b8212e5ae9)

**Comment by lingtran** [comment]
Pair: @sarahproof / @lingtran 

We successfully tested staging, all except for actually sending an email due to bug that seems to be related to `email-from` value (a request requirement).

**Comment by sarahproof** [comment]
There seems to be a problem with the queue in staging preventing emails from being sent. We get a lot of errors in the log like 
<Message>Can only include alphanumeric
characters, hyphens, or underscores. 1 to 80 in
length</Message><Detail/></Error>
and mentioning invalid Sender

**Comment by ffafara-tw** [comment]
Celery creates a queue for each celery node. The queue is named using formula: queue-prefix + hostname, ex: dev-notification-celery_ip-10-0-0-103-us-east-2-compute-internal-celery-pidbox

In staging environment the queue name exceeds the allowed length of 80 characters.
There are 2 options to solve that issue:

1. Set CELERY_ENABLE_REMOTE_CONTROL to False
This will disable remote management of workers for which the pidbox queue is used.

2. Change the hostname value for celery when starting using -n flag
`celery -A proj worker --concurrency=4 -n worker1@%h`
From https://docs.celeryproject.org/en/stable/userguide/workers.html:
The hostname argument can expand the following variables:
- %h: Hostname, including domain name (worker1@george.example.com)
- %n: Hostname only (worker1@george)
- %d: Domain name only (worker1@example.com)
Since currently we are using hostname only we would have to provide a custom variable that would be shorter but unique at a given time - IP address might be a good example.

For now I'm going to do option 1 as we are not performing remote management of workers.
