### ISSUE TITLE
Assign communication item to a template

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#516]
# Value Statement
**As** As a VANotify business line user
**I want to** be able to select communication item for my templates
**So that** my recipients can control preferences for these communications

# Acceptance Criteria

**GIVEN** a service
**AND**  a dictionary of communication items
**WHEN** I create a template for this service
**THEN** I am able to select a communication item for the template

**GIVEN** a template 
**AND** a dictionary of communication items
**WHEN** editing that template
**THEN** I am able to select or change a communication item

**GIVEN** a dictionary of communication items 
**WHEN** a platform admin edits the list of communication items
**THEN** the dictionary is updated

~~**GIVEN** a dictionary of communication items 
**WHEN** a platform admin attempts to remove a communication item from the dictionary 
**AND** the communication item is currently assigned to a template
**THEN** the user will recieve an error message that it is not possible to remove the item as it is currently associated with a template~~

# Checklist
- [x] Get list of communication items from VA Profile to populate our dictionary (reach out to VA Profile Team or see if we can get that list using their API) with identifiers
- [x] Create new model and database table for `CommunicationItem` with attributes
  - `id` (like an ID local to VA Notify)
  - `va_profile_id`?? (like the ID that can be used to query for this item on VA Profile)
  - `name`?? or description or something? whatever it's called in VA Profile
- [ ] ~~Create endpoints to create/update/get `CommunicationItem` objects~~
- [x] Add migration to populate `CommunicationItem` table with communication items retrieved from VA Profile
- [x] Update `Template` model/schema to add `communication_item` attribute
- [x] Open API specifications for the new endpoints for communication item dictionary
- [ ] 

# Assumptions
- there is a dictionary of communication items
- there are communication items in VA Profile

# Additional Info/Resources
- communication item: business use case that allows for preferences i.e. text (yes/no), email (yes/no) that is being surfaced on VA.gov which is housed/lives in VA Profile
- working spreadsheet: https://drive.google.com/file/d/1vmHm1tf5ADv1WvbpaQ4DoelXRcWaRlJv/view
- Signed ICD with VA Profile: https://drive.google.com/drive/u/0/folders/1THg4TEzegqwQ7ZK9NkLApjoBnWuCGj-J
- https://int.vaprofile.va.gov:7005/communication-hub/
-https://preview.uxpin.com/51ca6ecd7ddaf2ceaf75f94e2b2ccbed2a193f6d#/pages/140375964/simulate/sitemap?mode=i

# Out of Scope
- Layering on permissions

# Open Questions
- [ ] What do we need to store on our end? Do we want to store our on identifiers (probably not) but maybe some friendly name or descriptions?
- [ ] Do we care about groups? For now we won't care.

**Comment by miabecker** [comment]
@philherbert can you take a peek?

**Comment by anitadewitt-va** [comment]
- GET `all /communication-item` was added 
- POST `/service/{{service-id}}/template` was updated for creating a template with a valid communication item
- POST `/service/{{service-id}}/template/{{template-id}}` was updated for updating a template with a valid communication item

**Comment by TWs-DevenS** [comment]
![image.png](https://images.zenhubusercontent.com/604f66cb300e975b0fa212d7/3c5b4cd0-eebd-49ea-b647-b00a46713f12)
:
Reviewed the following
1. Create a template with a communication item
2. Update the existing template with valid communication item
3. Dictionary of communication items, if admin edit the list of communication items, the dictionary gets updated.

This story  can be closed.
