### ISSUE TITLE
53941 - Short Code Configuration

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#521]
# Value Statement
**As** business line customer
**I want to** be able to send SMS(s) to users using a short code
**So that** I have a new number from which to engage users

# Acceptance Criteria
**GIVEN** the 53941 shortcode 
**WHEN** VEText is sending notification requests
**THEN** they can use the shortcode to send SMS to end-users

**GIVEN** 53941 shortcode 
**WHEN** the user replies
**THEN**the message will be put on the callback queue for VEText

# Checklist

Note: all of these steps should be tested in staging with VEText with a different non-short code number

- [x] Add shortcode to VANotify Inbound numbers
- [x] Create SMS sender for VEText Service with that shortcode referencing inbound number 
- [x] AWS Configuration 
        - [ ]  Configure short code to use "pinpoint-inbound-sms-lambda" 
        - [ ]  Select "Enable self-managed opt-outs" option for short code number 
- [x] Configure inbound SMS callback using queue for VEText
- [ ] ~~Create a template to use for "HELP" response~~

# Assumptions
-

# Additional Info/Resources
- Inbound SMS to a given number can only be sent to one service via callbacks

# Out of Scope
-

# Open Questions
-

**Comment by anitadewitt-va** [comment]
Test for: START, STOP, JOIN, HELP, OTHER, URGENT, DECEASED, WRONG_NUMBER

**Comment by TWs-DevenS** [comment]
Test plan for User Story - https://docs.google.com/document/d/103mmWMwitcPq3ZDwCkEOCheTP3HDjw2L/edit
