### ISSUE TITLE
Update email provider load balancing weight

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#528]
# Value Statement

**As** platform admin
**I want to** update my email provider load balance weight
**So that**I am adhering to contract changes

# Checklist
- [x] Update load balancing weighting to 100% Amazon SES, 0 % Gov Delivery
- [x] Ensure Granicus is not pinned as a provider to any use cases

# Assumptions
-

# Additional Info/Resources
- The client let us know today that our Granicus contract expired as of July and we should not use Granicus until they direct us we can moving forward

# Out of Scope
-

# Open Questions
-

**Comment by miabecker** [comment]
@lingtran We had a production task come in today and you are on call. Please reach out to @philherbert or @ffafara-tw if you have any questions.

**Comment by lingtran** [comment]
I found a couple service templates that pointed to GovDelivery as provider. In those instances I switched them to AWS SES as provider instead.
