### ISSUE TITLE
[BUG] Bearer Token expires and or token is not present at all and a 500 internal server error is returned

### ISSUE THREAD

**Issue by lingtran** [department-of-veterans-affairs/notification-api#529]
# Describe the Bug
When bearer token expires or doesn't exist, an unhelpful 500 internal server error is thrown

# To Reproduce
1. Get a bearer token for Authorization type `Bearer Token` via UI or POST `auth/login`
2. Let token expire (such as through inactivity)
3. Make GET `/service/<service-id>/callback` request
4. See 500 internal server error

# Expected Behavior
It should throw meaningful exception.

# Actual Behavior 
It throws nebulous 500 internal server error.

# Relevant Story
If applicable, link the related story here.

# Additional Context
- Use Postman.
- Bug was discovered while working on #504

**Comment by lingtran** [comment]
@miabecker

**Comment by ffafara-tw** [comment]
The library jwt_flask_extended registers appropriate app error handlers when initialized with flask app.
We do it in `__init__.py:L194`.

The reason why these error handlers might not be executed is that we define local error hanlders for each blueprint which contain catch all error handling for `Exception`.

We could try removing:
```
@blueprint.errorhandler(Exception)
    def internal_server_error(error):
        current_app.logger.exception(error)
        return jsonify(status_code=500,
                       errors=[{"error": error.__class__.__name__, "message": 'Internal server error'}]), 500
```
from `app/errors.py` and `app/v2/errors.py`. The hypothesis is that exception not handled by local blueprint error handlers will be handled by global app error handlers.

**Comment by philherbert** [comment]
This can be closed! Had some difficulties making its way through the pipeline, with twistlock failures and a defect found by the user flow tests, but now all fixed and good to close.
