### ISSUE TITLE
Update Terraform Github Action

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#53]
According to [Hashicorp](https://www.terraform.io/docs/github-actions/index.html), the current action we use for running Terraform commands ([hashicorp/terraform-github-actions](https://github.com/hashicorp/terraform-github-actions/)) is now deprecated.

Instead, we should use [hashicorp/setup-terraform](https://github.com/hashicorp/setup-terraform).

**Comment by miabecker** [comment]
This has been done for the VAEC stuff. Not for TW but we will be deprecating TW environment so shouldn't spend time on this.
