### ISSUE TITLE
 Extend the timeout time for logout from the UI

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#530]
# Value Statement
**As** a business user 
**I want to** stay in the UI for an hour
**So that**I am not logged out until an hour passes

# Checklist
- [ ] Checklist item here

# Cross Functional Checklist

Testing:
  - [ ] ~integration for API~
  - [ ] ~Cypress (e2e) for UI~
  - [ ] unit tests to check expiration time???

Monitoring:
  - [ ] ~statsd and datadog~

Security:
  - [ ] ~auth permissions~
  - [ ] ~JsonSchema~

Marshmallow
- [ ] ~Model serialization / deserialization~

Documentation:
  - [ ] ~Readmes~
  - [ ] ~Project specific~
  - [ ] ~Support~ 
  - [ ] ~Openapi~
  - [ ] ~ADR~
  - [ ] ~Tech Debt wall~

Mountebank
- [ ]  ~Mock~

Accessibility
- [ ] ~E2E & Testrail~

Postman
- [ ] ~Update collection~

# Assumptions
-

# Additional Info/Resources
- Current time is 10 minutes, which is not enough to edit notification

# Out of Scope
-

# Open Questions
-

**Comment by philherbert** [comment]
## Current behaviour

<img width="1225" alt="Screenshot 2021-08-19 at 09 53 04" src="https://user-images.githubusercontent.com/9078954/130080899-81c8061d-43c2-4f77-8e49-9242f7a25cc6.png">

`iat` (issued at): `1629380995` -> `Thu Aug 19 2021 09:49:55 GMT-0400 (Eastern Daylight Time)`
`exp` (expiration time): `1629381895` - `Thu Aug 19 2021 10:04:55 GMT-0400 (Eastern Daylight Time)`

Expiration time is 15 minutes

**Comment by philherbert** [comment]
## New behaviour

<img width="1226" alt="Screenshot 2021-08-19 at 10 33 36" src="https://user-images.githubusercontent.com/9078954/130087630-3520cfbd-30b4-4747-8e88-f0934e5898f8.png">

`iat` (issued at): `1629383581` -> `Thu Aug 19 2021 10:33:01 GMT-0400 (Eastern Daylight Time)`
`exp` (expiration time): `1629387181` - `Thu Aug 19 2021 11:33:01 GMT-0400 (Eastern Daylight Time)`

Expiration time is one hour

**Comment by TWs-DevenS** [comment]
This ticket has been reviewed and can be closed.  The timeout was verified manually as well as identifying the Expiration  time in jwt token.
