### ISSUE TITLE
[SPIKE] Getting data into Big Query

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#536]
# Goal
Explain the purpose of the spike. E.g. tool selection, research, understanding future state/feasibility

# Checklist
- [ ] <item here>
- [ ] Discuss and document with team
- [ ] Create recommendations

# Timebox
Estimate how long this should take, in days. Typically 3.

# Assumptions
- 

# Additional Info/Resources
https://github.com/department-of-veterans-affairs/va.gov-team/issues/28356#issuecomment-898569969
-

# Out of Scope
-

# Open Questions
- Is implementation out of scope?

**Comment by miabecker** [comment]
Call with Analytics Team today. Discussed the "normal process is to provide a Google Cloud Storage bucket to your team. When you upload a data file (usually a CSV), we would then validate and ingest that into BigQuery." Next steps from Analytics Team are to determine how to Table, Volume, Frequency. Preaggrated statistics or raw data and with what frequency. Will be looking for credentials.

**Comment by miabecker** [comment]
Wrote 1/3 tickets needed for this. Need to write 2 more 1) on querying data and 2) pushing data to cloud storage.

**Comment by ffafara-tw** [comment]
Pushed ADR.
@miabecker @philherbert can you review?

**Comment by miabecker** [comment]
Yes! Reviewed and it is really good. Just wanted to add a 3rd option to capture the "going through the TIC" option. Not sure its fully captured but just got some sentences down around it.

**Comment by ffafara-tw** [comment]
It's not really a 3rd option. Any option will require traversing TIC.

**Comment by philherbert** [comment]
Read the ADR and I think it contains the right level of detail!
