### ISSUE TITLE
Create Notification Templates For Office Of Connected Care Mental Health Care Use Case - Part 1

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#542]
# Value Statement
**As** Office of Connected Care business line user
**I want to** notifications to be sent to providers when a PHQ-9 score requires action
**So that**I can help prevent Veteran suicide

# Checklist
- [x] Create new service in staging for Office of Connected Care
- [x] Create templates in staging
- [x] Update ticket with template IDs relevant to each content: https://app.zenhub.com/workspaces/vanotify-business-intake-board-606cc5c49392c900162c3971/issues/department-of-veterans-affairs/va.gov-team/28516
- [x] Update ticket with template IDs relevant to each content
- [x] Share API keys to staging to Matthew.Smith15a1a7@va.gov and comment on: https://app.zenhub.com/workspaces/vanotify-business-intake-board-606cc5c49392c900162c3971/issues/department-of-veterans-affairs/va.gov-team/28516 

# Cross Functional Checklist

Testing:
  - [ ] integration for API
  - [ ] Cypress (e2e) for UI

Monitoring:
  - [ ] statsd and datadog

Security:
  - [ ] auth permissions
  - [ ] JsonSchema

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support 
  - [ ] Openapi
  - [ ] ADR
  - [ ] Tech Debt wall

Mountebank
- [ ] UI - create mocks for any API calls
- [ ] API - create mocks for any external services calls

Accessibility
- [ ] E2E & Testrail

Postman
- [ ] Update collection whenever we change our API

# Assumptions
-

# Additional Info/Resources

`VCL_EMAIL_SUBJECT: 'VCL OUTREACH'

VCL_EMAIL_BODY: 'VCL, please follow up. {{n}} This email is being sent as a notification that a Veteran has completed a PHQ-9 assessment answering question 9 in a manner that indicates he/she is having thoughts of being better off dead or of harming him/herself. Please contact the Veteran as soon as possible. Contact information is provided in the secure link below. {{n}} {{event-page}}'

____________

PROVIDER_EMAIL_SUBJECT: 'MH Checkup Patient has indicated suicidality'

PROVIDER_EMAIL_BODY: 'This email is being sent as a notification that a Veteran has completed a PHQ-9 assessment answering question 9 in a manner that indicates he/she is having thoughts of being better off dead or of harming him/herself. The Veterans Crisis Line has been notified and should be contacting the patient as soon as possible. If you would like to contact the Veteran directly, contact information is provided in the secure link below. {{n}} {{event-page}} {{n}} The assessment details can be retrieved from the alerts tab in MH Checkup or directly at the link below: {{n}} {{assessment-page}}'

___________

PROVIDER_VCL_EMAIL_SUBJECT: 'MH Checkup Patient has indicated suicidality'

PROVIDER_VCL_EMAIL_BODY: 'This email is being sent as a notification that a Veteran has completed a PHQ-9 assessment answering question 9 in a manner that indicates he/she is having thoughts of being better off dead or of harming him/herself. The Veterans Crisis Line has been notified and should be contacting the patient as soon as possible. If you would like to contact the Veteran directly, contact information is provided in the secure link below. {{n}} {{event-page}} {{n}} The assessment details can be retrieved from the alerts tab in MH Checkup or directly at the link below: {{n}} {{assessment-page}}'

____________

PROVIDER_COMPLETED_EMAIL_SUBJECT: 'An assigned assessment was completed'

PROVIDER_COMPLETED_EMAIL_BODY: 'An assessment you have assigned was completed by the Veteran. It was due on {{due-date}}. Please log in at https://staff.apps.va.gov/mhc-provider/ to review completed assessments

__________

# Out of Scope
-

# Open Questions
- What should the footer look like for internal-facing emails?

**Comment by ffafara-tw** [comment]
Created service in staging:
```
"id": "9f0cad58-0499-4715-8348-37e3eb84fd77",
"name": "Office of Connected Care",
"message_limit": 300,
"rate_limit": 300,
"permissions": [
            "email"
        ]
```

**Comment by ffafara-tw** [comment]
Created VCL Outreach templated:
```
 "id": "5011690e-6687-4234-b386-3f413e767079",
"name": "VCL Outreach",
```

**Comment by ffafara-tw** [comment]
Created MH Checkup Patient has indicated suicidality template:
```
 "id": "568fb2df-6859-43cb-9f9b-9179acdb7c17",
 "name": "MH Checkup Patient suicidality",
 "subject": "MH Checkup Patient has indicated suicidality",
```

**Comment by ffafara-tw** [comment]
Created An assigned assessment was completed template:
```
 "id": "1fbec063-c092-47a1-8d5b-8bdc3ea89e9f",
 "name": "Provider assessment completed",
 "subject": "An assigned assessment was completed",
```

**Comment by ffafara-tw** [comment]
Created an VET_FEEDBACK_EMAIL template:
```
 "id": "1bfff777-ea36-483c-91ce-11bc4e259927",
 "name": "VET Feedback Email",
 "subject": "You provider has provided feedback on one of your assessments",
```

**Comment by ffafara-tw** [comment]
Created VCL MH Checkup Patient suicidality template:
```
 "id": "c5fdc047-9a21-41bd-b62f-f6ef3a07f811",
 "name": "VCL MH Checkup Patient suicidality",
 "subject": "MH Checkup Patient has indicated suicidality",
```

**Comment by ffafara-tw** [comment]
We should get confirmation from Office of Connected Care team that they can use these templates and that they are good to go.

**Comment by miabecker** [comment]
Checked in with Ryan and they said they didn't need anything else after we gave them access to the UI. Waiting to hear from them when they are ready to move into prod.
