### ISSUE TITLE
Add support for VA identifiers to vanotify-java-client

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#553]
# Value Statement
**As** VANotify customer that uses the java client
**I want to** to send notification requests using supported VA identifiers
**So that** I can take advantage of communication preferences and contact lookups.

# Acceptance Criteria
**GIVEN** vanotify-java-client
**WHEN** new notification request is made with supported VA identifier instead of email address or phone number
**THEN** the request is accepted and processed by VANotify API
**AND** contact lookup works as expected
**AND** communication preferences checks work as expected

**GIVEN** vanotify-java-client
**WHEN** new notification request is made with supported VA identifier in addition to email address or phone number
**THEN** the request is accepted and processed by VANotify API
**AND** contact lookup works as expected
**AND** communication preferences checks work as expected

# Checklist
- [ ] Checklist item here

# Cross Functional Checklist

Testing:
  - [ ] integration for API
  - [ ] Cypress (e2e) for UI

Monitoring:
  - [ ] statsd and datadog

Security:
  - [ ] auth permissions
  - [ ] JsonSchema

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support 
  - [ ] Openapi
  - [ ] ADR
  - [ ] Tech Debt wall

Mountebank
- [ ] UI - create mocks for any API calls
- [ ] API - create mocks for any external services calls

Accessibility
- [ ] E2E & Testrail

Postman
- [ ] Update collection whenever we change our API

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by miabecker** [comment]
Closing for now - VEText is not planning on sending identifiers anytime soon to test this but we will monitor when we go live with someone sending us VA Identifiers.
