### ISSUE TITLE
Update SMS sender rate limit algorithm

### ISSUE THREAD

**Issue by emilywu-tw** [department-of-veterans-affairs/notification-api#564]
We currently use Redis to determine if the rate limit (60 seconds) has been exceeded. We add a new timestamp entry to the Redis cache using the SMS sender as the cache key, and determine how many entries have a timestamp within a minute.

This could cause problems if we send a ton of messages in a small amount of time; for example, if we have a rate limit of 300, our algorithm would let someone attempt to send all 300 within the first second. Our providers would probably not be able to handle that; we should not be sending more than 1 message per second.

# Value Statement

AS A user who wants to send rate-limited SMSes
I WANT TO be able to specify the rate limit per any number of second interval
SO THAT our requests don’t send out too quickly and are sent at a regulated rate

# Acceptance Criteria

GIVEN an SMS sender
WHEN  the platform admin wants to define a rate limit 
THEN they can configure a rate limit number and interval (int, number of seconds)
AND the SMS will be sent at approximately that defined rate

# Checklist

- [x] Migration to add rate limiting interval (integer representing number of seconds) to SMS sender model. Existing SMS senders with rate limits configured should have their intervals set to 60 seconds.
- [x] In `notification-utils`, create a method in `redis_client.py` that implements the rate limiting algorithm as a Lua scripts. 
- [x] In `notification-api`, call the appropriate method on the Redis client.

Documentation:
- [x] Update README around Redis logic in `notification-api`'s app/README
- [ ] Tech Debt wall

# Cross Functional Checklist

~~Testing:~~
~~- [ ] integration for API~~
~~- [ ] Cypress (e2e) for UI~~

~~Monitoring:~~
~~- [ ] statsd and datadog~~

~~Security:~~
~~- [ ] auth permissions~~
~~- [ ] JsonSchema~~

~~Transform requests to business models in our API~~
~~- [ ] Marshmallow model serialization / deserialization~~

# Additional Information

- We are going to try to implement this in a flexible way however it if is too challenging – we can revert to a less challenging solution. 

# Open Questions
~~- Should we be limiting to a minute and trying to space messages out as evenly as possible? For example, if we have a rate limit of 2, should we just send one message for each of the first two seconds or send one message every 30 seconds?~~

**Comment by vikarus-tw** [comment]
Rate limiting was toggled on in production environment on 10/25/2021
