### ISSUE TITLE
Send emails with attachments using SES

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#574]
# Value Statement

**As a** business line customer 
I want to send attachments via email 
So that I can provide information to my end-users

**As a** platform owner 
**I want** the files that are sent as attachments to be stored in S3 buckets
**So that** we can continue using asynchronous processing when sending notifications.
**Which** will maintain the platform’s ability to handle large volumes of notifications.

# Acceptance Criteria

_1. Validate Mimetype / extension_

**Given** the API receives a request to send a notification 
**And** the payload contains a value for that placeholder, with filename and file data
**Then** that file’s Mimetype will be determined
**And** the request will be rejected if the file’s Mimetype is not in the configured allowed list of mimetypes

_2. Validate file size_
**Given** the API receives a request to send a notification
**And** the payload contains file data that is over the configured size limit  (1024KB??)
**Then** the request will be rejected with “413 Payload Too Large” http status code

_3. Validate service permissions_
**Given** the API receives a request to send a notification
**And** the payload contains file data
**When** the service does not have UPLOAD_DOCUMENTS permission
**Then** The request will be rejected with 403 Forbidden status code and message ‘Service is not allowed to send attachments’.

_4. Upload file to a specific S3 bucket_
**Given** the API receives a request to send a notification, containing file name and file data
**When** that file passes Mimetype and size validations
**Then** the file is uploaded to S3 in the “/tmp” directory and is encrypted using a new unique key

_5. File is removed after 7 days from S3 bucket_
**Given** a file has been uploaded to S3 in the “/tmp” directory
**When** 7 days have elapsed since the file was uploaded
**Then** the file is deleted from the S3 bucket

_6. S3 bucket is created in Infra as code_
**Given** platform infrastructure as code 
**When** the pipeline runs
**Then** S3 bucket for storing attachments is created
**And** it has correct permissions and lifecycle policy

_7. Attachment is sent in email_
**Given** the API has received a request to send a notification, containing file name and file data
**And** that file has been uploaded to S3
**When** the delivery task is executed for that notification
**Then** the file is downloaded from S3
**And** the file is sent to SES as an attachment with the notification
**And** the file is correctly sent 
**And** can be processed by HTML and text-based email clients 

# Checklist
  - [x] Warning logs for failure paths (validation failures)
  - [x] Modify personalisation data so that we store s3 location / url instead of file data

# Additional Info/Resources
We can reuse code from https://github.com/cds-snc/notification-document-download-api

Example of personalisation with a file:
```
personalisations: {
  "application_file": {
    "file": "file as base64 encoded string",
    "filename": "your_custom_filename.ics"
  }
}
```

- - Incorporate email mime type fixes from: https://github.com/cds-snc/notification-api/pull/1260

# Assumptions
- If you send a file and you don’t specify the sending method then it is assumed that it is an attachment
- For each file S3 will generate a new unique encryption key 
- We will have a list of approved mime types in our config.py

# Cross Functional Checklist

Testing:
  - [ ] integration test for API

Monitoring:
  - [x] statsd metrics
  - [ ] datadog graphs
  - [ ] datadog alterts

Security:
  - [ ] ~auth permissions~
  - [ ] ~JsonSchema~

Transform requests to business models in our API
- [ ] ~Marshmallow model serialization / deserialization~

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support
  - [ ] Openapi
  - [x] ADR - https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/documents/adr/0014-sending-email-attachments.md
  - [ ] ~Tech Debt wall~

Mountebank
- [ ] ~API - create mocks for any external services calls~

Postman
- [ ] Update collection whenever we change our API

# Out of Scope
- 

# Open Questions
-

**Comment by geekyflamingo-tw** [comment]
@miabecker @philherbert this story has been looked at by @JolisaBrownThoughtworks and me. Only thing that was found was that if the filename was an extension other than ics, gmail would display the event as that extension rather than use the data in the actual file.
<img width="1005" alt="Screen Shot 2021-12-29 at 10 01 54 AM" src="https://user-images.githubusercontent.com/81782114/147686277-8d978682-2409-4c37-ac9e-5f5b463f0c31.png">
<img width="1019" alt="Screen Shot 2021-12-29 at 10 02 08 AM" src="https://user-images.githubusercontent.com/81782114/147686279-675c463b-a458-47e4-bbb0-6db51e7663a2.png">

**Comment by miabecker** [comment]
Ok to move this card on for now but might need to look into more validation for file name.

**Comment by miabecker** [comment]
@philherbert to verify it works in staging and prod.

**Comment by miabecker** [comment]
@philherbert enabled in prod and now just needs to trigger a deployment to turn it on.

**Comment by philherbert** [comment]
Have deployed to prod, happy to close this card
