### ISSUE TITLE
Query and upload notification stats to S3

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#576]
# Value Statement
**As** VANotify business line customer
**I want to** be able to view my notification statistics in DOMO
**So that** I can build reports and views based on my needs

# Acceptance Criteria

**WHEN** every day after the "create nightly notification status" job run
**THEN** a task is executed exporting daily stats as CSV file to S3

# Checklist
- [x] Reuse query (and if not possible to reuse may have to write) to generate a report on notification statuses and status reasons by template and service
- [x] Create a bucket in S3 using Terraform 
- [x] Automate query in Celery Task to run per established cadence 
- [x] Scripts to generate task JSON and apply to SQS to execute generic task without arguments

# Cross Functional Checklist

Testing:
  - [ ] integration test for API

Monitoring:
  - [ ] statsd metrics
  - [ ] datadog graphs
  - [ ] datadog alterts

Security:
  - [ ] auth permissions
  - [ ] JsonSchema

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support
  - [ ] Openapi
  - [ ] ADR
  - [ ] Tech Debt wall

Mountebank
- [ ] API - create mocks for any external services calls

Postman
- [ ] Update collection whenever we change our API

# Assumptions

- Notification stats will recalculate for past 4 days

# Additional Info/Resources
- Schema for CSV file: service id | service name | template id | template name | status | count
- The existing ticket with the analytics team: https://github.com/department-of-veterans-affairs/va.gov-team/issues/28356
- Analytics Team has weekly office hours and a slack channel here #vfs-analytics

# Out of Scope
- Uploading to Big Query
- Status reason - won't populate that column yet

# Open Questions
- Should we chain the celery tasks or manually adjust the scheduling (i.e. so that one runs after the other)?
- Where will we educate the user on this? Landing page, GitHub etc?

**Comment by miabecker** [comment]
QAing for this would look like sending a bunch of notifications in different statuses and checking that the uploaded statistics are accurate @geekyflamingo-tw @vikarus-tw

**Comment by miabecker** [comment]
@philherbert enabled in prod and just needs to trigger a deployment.

**Comment by philherbert** [comment]
Have deployed to prod
