### ISSUE TITLE
Celery worker to process to pull from S3 and modify SES to send as an attachment

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#577]
# Value Statement

**As a** business line customer 
**I want** to send attachments via email 
**So** that I can provide information to my end-users

**As a** platform owner 
**I want** pull the files stored in S3 buckets
**and** modify SES
**So that** I can send notifications with attachments

# Acceptance Criteria

_1. Download attachment file from S3_

**Given** the API has received a request to send a notification, containing file name and file data
**And** that file has been uploaded to S3
**When** the delivery task is executed for that notification
**Then** the file is downloaded from S3
**And** the file is sent to SES as an attachment with the notification
**And** the file is correctly sent 
**And** can be processed by HTML and text-based email clients 

# Checklist
- [ ] 

# Cross Functional Checklist

Testing:
  - [ ] integration test for API

Monitoring:
  - [ ] statsd metrics
  - [ ] datadog graphs
  - [ ] datadog alterts

Security:
  - [ ] auth permissions
  - [ ] JsonSchema

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support
  - [ ] Openapi
  - [ ] ADR
  - [ ] Tech Debt wall

Mountebank
- [ ] API - create mocks for any external services calls

Postman
- [ ] Update collection whenever we change our API

# Assumptions
-

# Additional Info/Resources
- Incorporate email mime type fixes from: https://github.com/cds-snc/notification-api/pull/1260

# Out of Scope
-

# Open Questions
-

**Comment by philherbert** [comment]
Closing as this has been incorporated into #574
