### ISSUE TITLE
Allow users to manage service whitelists

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#578]
# Value Statement
**As** technical consumer of VANotify platform
**I want to** configure whitelist for my service
**So that** I can control who can we send test notifications to.

# Acceptance Criteria
**GIVEN** a service
**AND** a user with `manage settings` permission for that service
**WHEN** the user makes a GET API request to /service/<uuid:service_id>/whitelist
**AND** the request contains valid user JWT token
**THEN** a response with current whitelist is returned

**GIVEN** a service
**AND** a user with `manage settings` permission for that service
**WHEN** the user makes a PUT API request to /service/<uuid:service_id>/whitelist
**AND** the request contains valid user JWT token
**AND** request contains valid body
**THEN** a 204 response is returned with no content

**GIVEN** a service
**AND** a user with `platform_admin` permission
**WHEN** the user makes a GET API request to /service/<uuid:service_id>/whitelist
**AND** the request contains valid user JWT token
**THEN** a response with current whitelist is returned

**GIVEN** a service
**AND** a user with `platform_admin` permission
**WHEN** the user makes a PUT API request to /service/<uuid:service_id>/whitelist
**AND** the request contains valid user JWT token
**AND** request contains valid body
**THEN** a 204 response is returned with no content

**GIVEN** a service
**AND** a user **without** `manage settings` permission for that service
**WHEN** the user makes a GET API request to /service/<uuid:service_id>/whitelist
**AND** the request contains valid user JWT token
**THEN** a 403 Forbidden response is returned

**GIVEN** a service
**AND** a user **without** `manage settings` permission for that service
**WHEN** the user makes a PUT API request to /service/<uuid:service_id>/whitelist
**AND** the request contains valid user JWT token
**AND** request contains valid body
**THEN** a 403 Forbidden response is returned

**GIVEN** a service
**AND** a user who is not part of that service
**WHEN** the user makes a PUT API request to /service/<uuid:service_id>/whitelist
**AND** the request contains valid user JWT token
**AND** request contains valid body
**THEN** a 403 Forbidden response is returned

**GIVEN** a service
**AND** a user who is not part of that service
**WHEN** the user makes a GET API request to /service/<uuid:service_id>/whitelist
**AND** the request contains valid user JWT token
**THEN** a 403 Forbidden response is returned

# Checklist
- [ ] Checklist item here

# Cross Functional Checklist

Testing:
  - [ ] integration test for API

Monitoring:
  - [ ] statsd metrics
  - [ ] datadog graphs
  - [ ] datadog alterts

Security:
  - [x] auth permissions
  - [x] JsonSchema

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support
  - [ ] Openapi
  - [ ] ADR
  - [ ] Tech Debt wall

Mountebank
- [ ] API - create mocks for any external services calls

Postman
- [x] Update collection whenever we change our API

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by philherbert** [comment]
Tested and looks good to me!
