### ISSUE TITLE
[BUG] Unable to login with Github user without name

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#584]
# Describe the Bug

When logging in with Github, the API throws a 500 error if the Github profile does not have a name.

![Screen Shot 2021-11-17 at 5.59.43 PM.png](https://images.zenhubusercontent.com/5dd579a833bf7f0001b95dfb/16de23c7-2ad7-4082-9a18-edbd111c4496)

![Screenshot 2021-11-18 at 09.46.20.png](https://images.zenhubusercontent.com/5dd579a833bf7f0001b95dfb/841df875-94a7-4751-bf8a-61c0be721d98)

**Comment by philherbert** [comment]
Moving to blocked while we hear back from the reporter of this bug

**Comment by miabecker** [comment]
@philherbert to fill out details but it looks like this bug is fixed!

**Comment by philherbert** [comment]
The reported of this bug has been able to log in to prod, so all good!
