### ISSUE TITLE
Send push notifications synchronously using VEText

### ISSUE THREAD

**Issue by miabecker** [department-of-veterans-affairs/notification-api#585]
# Value Statement
**As a** business line customer 
**I want** to send push notifications
**So that** I can provide information to end-users who have the VA app installed

# Acceptance Criteria

## 1. Gotta have permissions

**GIVEN** a request to send a push notification 
**WHEN** the specified service does not have `push` permissions
**THEN** the request is rejected as invalid - 401 or 403?

## 2. Required fields

**GIVEN** a request to send a push notification
**WHEN** the request does not contain a recipient identifier with `id_type` of `ICN`
**OR** the request does not contain a `template_id`
**THEN** the request is rejected as invalid

## 3. A valid request

**GIVEN** a request to send a push notification
**WHEN** the request contains:
* a recipient identifier with `id_type` of `ICN`
* a template ID that matches VEText's format (eg `0EF7C8C9390847D7B3B521426EFF5814`)
* personalisation

**THEN** our system makes an API request to VEText to send a push notification to that ICN, using that template, personalisation, and the default application ID (TBD)
**AND** we respond synchronously indicating success

## 3. Optional `application` field

**GIVEN** a request to send a push notification
**WHEN** the request contains:
* the aforementioned contents
* a field `application` with a valid application name (e.g. `VA_FLAGSHIP_APP`)

**THEN** our system makes an API request to VEText to send a push notification using the VEText application ID corresponding to the specified application
**AND** we respond synchronously indicating success

## 4. VEText errors

**GIVEN** a request to send a push notification
**WHEN** the request is valid, as described above
**THEN** our system makes an API request to VEText to send a push notification
**AND WHEN** VEText responds with an error
**THEN** we respond synchronously with details of the error, in VANotify's v2 error structure

# Checklist
- [x] Create new endpoint for "Push"
- [x] Validate that push request contains ICN 
- [x] Accept VEText Template IDs
- [x] Accept optional enum for application (eg VA_FLAGSHIP_APP)
- [x] Get VEText credentials and put in parameter store
- [x] Create VEText client
- [x] Translate personalizations to VEText format
- [x] Use VEText client to make push notification request 
- [x] Wrap VEText errors in our V2 error messages
- [x] Track stats in datadog

# Cross Functional Checklist

Testing:
  - [x] integration test for API

Monitoring:
  - [x] **statsd metrics**
  - [x] **datadog graphs**
  - [ ] **datadog alerts for VEText errors**

Security:
  - [x] **auth permissions**
  - [x] **JsonSchema**

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support
  - [x] **Openapi**
  - [ ] ADR
  - [ ] Tech Debt wall

**Mountebank**
- [x] API - **create mocks for calls to VEText**

Postman
- [x] **Update collection whenever we change our API**

# Assumptions
- Sending push notification will not create a Notification Object in VANotify
- Almost definitely gonna be easier to just create an entirely new endpoint in our controller, rather than trying to extend existing ones. At this point, there won't be much (if any) overlap in code to handle these notifications

# Additional Info/Resources
- https://dvagov.sharepoint.com/sites/vhavetext/SitePages/VEText-Push-Notifications-API.aspx
- https://github.com/department-of-veterans-affairs/vetext

# Out of Scope
- Won't be validating personalization - just passing through whatever we get to VEText
- 

# Open Questions
- Names of application enum?
- Get values from VEText for application ID mapping
- How will we wire up environments w/ VEText? Potentially point our dev and perf to their staging? 
- What's VEText's template ID format?
- How do we respond when a service has insufficient permissions?
- `POST /v2/notifications/push`? v2 or no v2

**Comment by miabecker** [comment]
@ffafara-tw to hand off story to @philherbert while he is OOO.

**Comment by ffafara-tw** [comment]
- [ ] Translate personalizations to VEText format
- [ ] App config for vetext
- [ ] Extract push notifications controller to separate file
- [ ] Add Mobile App model
- [ ] Add Mobile App controller ?
- [ ] Retries for requests in Vetext client
- [ ] Mountebank
- [ ] Integration test ?
- [ ] Flow test ?
- [ ] OpenApi

**Comment by ffafara-tw** [comment]
Still to be done:
- [ ] datadog alerts for VEText errors
- [ ] ADR

**Comment by miabecker** [comment]
Integration test is the last milestone for this card. Need to complete that and move to QA.

**Comment by geekyflamingo-tw** [comment]
QA done! @philherbert agrees!

**Comment by miabecker** [comment]
Trying to test this today with the mobile app team.

**Comment by ffafara-tw** [comment]
Everything has been enabled and verified in production.
