### ISSUE TITLE
Add status reasons to S3 notification stats

### ISSUE THREAD

**Issue by vikarus-tw** [department-of-veterans-affairs/notification-api#591]
# Value Statement
**As** a VANotify business line customer
**I want to** be able to view my notification stats in DOMO
**So that** I can build reports and views based on my needs

# Acceptance Criteria
**WHEN** every day after the “create nightly notification status” job is run
**THEN** a task is executed that exports daily stats as a CSV file to S3
**AND** notifications are seperated by service, template, status and status reason

# Checklist
- [x] Add status reasons column to `fact_notification` table
- [x] Update existing `fact_notification_dao` methods to group by status reason
- [x] Update CSV generator in `reporting_tasks` to include status reasons column

# Assumptions
- Notification stats will recalculate for past 4 days

# Additional Info/Resources
- Schema for CSV file: `service id | service name | template id | template name | status | reason | count`
- If there is no status reason, then leave blank(?)

# Out of Scope
- Uploading to Big Query

# Open Questions
-

**Comment by miabecker** [comment]
QA testing will be done to ensure the CSV files reflect changes in status.

**Comment by vikarus-tw** [comment]
Testing for status reasons can be done in the development environment with identifiers located in this file: https://docs.google.com/spreadsheets/d/1KdjgA-8ZvoUQyQtBZfk8HEzSkvMNX7-rJ5zQMr6RiUE/edit#gid=0

**Comment by TWs-DevenS** [comment]
This story has been verified, 
Unit test coverage for the change has been verified - verified new column exists and population with the status reason when there is a valid one
handling of no status reason when is there is none - csv is generated with blank status reason. 
The csv file generated displays the status reasons field as expected.
The validation of the count displayed previously during desk check.
The generation of csv files based on daily execution of report was verified.

see csv file attached above.

**Comment by miabecker** [comment]
Will need to deploy to get into production.

**Comment by philherbert** [comment]
Deployed to production
