### ISSUE TITLE
Add VA IAM as OAuth provider

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#593]
# Value Statement
**As** a VANotify user
**I want to** login to VANotify using PIV card
**So that** all my credentials are centralized

# Acceptance Criteria

## New user - happy path
**GIVEN** a new user
**WHEN** they go to vanotify ui
**AND** click `login with PIV` button
**AND** they successfully authenticate with IAM SSOi
**THEN** vanotify will create a new user account for them
**AND** store `SEC_ID` as identity provider id
**AND** they are successfully logged in to vanotify ui

## Returning user - happy path
**GIVEN** a user that already has an account in VANotify
**WHEN** they go to vanotify ui
**AND** click `login with PIV` button
**AND** they successfully authenticate with IAM SSOi
**THEN** vanotify will load their user profile by matching `SEC_ID`
**AND** they are successfully logged in to vanotify ui

## Existing user linking their PIV for the first time
**GIVEN** a user that has an account in VANotify
**AND** that user account does not have any `SEC_ID` correlated
**WHEN** they go to vanotify ui
**AND** click `login with PIV` button
**AND** they successfully authenticate with IAM SSOi
**THEN** vanotify will try load their user profile by matching `SEC_ID`
**AND** will fail
**THEN** vanotify will load user profile by matching `email_address`
**AND** will save the `SEC_ID` in user_profile
**AND** user is successfully logged in to vanotify ui

# Checklist
- [x] define new oauth client in oauth/registry
- [x] try to extract user model to it's own file
- [x] modify user model so that identity_provider_user_id points to a separate table and can support multiple ids
- [x] db migration to copy data to the new table
- [x] dao method to load user by identity provider id and type/name
- [x] modify `/oauth/login` endpoint to accept `idp` query param
- [x] choose oauth client to authorize with depending on `idp` query param or use github by deafult
- [x] `Login with PIV` button in the UI

# Cross Functional Checklist

Testing:
  - [ ] integration test for API

Monitoring:
  - [ ] statsd metrics
  - [ ] datadog graphs
  - [ ] datadog alterts

Security:
  - [ ] auth permissions
  - [ ] JsonSchema

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support
  - [ ] Openapi
  - [ ] ADR
  - [ ] Tech Debt wall

Mountebank
- [ ] API - create mocks for any external services calls

Postman
- [ ] Update collection whenever we change our API

# Assumptions
- We will support both Github and VA SSOi
- Github will remain default IdP for now to preserve backwards compatibility

# Additional Info/Resources
- There is a spike branch with a lot of code already written:
`oauth-sso-spike`

- Intergration Agreement:
https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/documents/integrations/IAM%20SSOi/VA_Notify_SSOi_IA.docx

- Additional technical information can be found in the SSOi Oauth Playbook: https://dvagov.sharepoint.com/sites/OITEPMOIAM/playbooks/Pages/Oauth/Oauth.aspx
 
TESTING INFORMATION:
> VA NOTIFY Access to Test Lower Environments
> - VA NOTIFY members create individual accounts in IAM database
>  - [Self-Service SSOi Account for partners](https://vaww.oed.portal.va.gov/sites/vrm/IAM/playbooks/Pages/SSOi/SSOi%20Setup.aspx)
>      Hint: Right click and open in a new window
>     Use the instructions from the first page to help you complete the registration
>   - Must create individual accounts in each IAM lower environment
>    - Takes no more than 10 minutes for all 3 environments
>     - VA NETWORK Access is REQUIRED
>     - Reason: Enter “Testing for SR 706 VA NOTIFY SSOi Oauth”

# Out of Scope

# Open Questions
- Check in with Natasha for final designs regarding login buttons

**Comment by ffafara-tw** [comment]
VA_SSO toggle is enabled in DEV and the integration works.
It will need to be tested by IAM team before it can be enabled in staging (IAM SQA environment).
Once it's tested and approved by IAM they will provide SQA credentials.

I messaged Jeffrey Kemple  but he is out of office.
Please reach out to him to schedule a testing session.

**Comment by Eallan919** [comment]
Meet with Jeffrey when he returns- 
Bev intro with our team for IAM
Nathan run point (pair to get others up to speed)

**Comment by mjones-oddball** [comment]
@k-macmillan can you please sync with @nathanbwright to get up to speed on this next week so we can move this forward?

**Comment by mjones-oddball** [comment]
@k-macmillan Would you mind tracking updates here as we test so we'll have an audit trail later if needed?

**Comment by zlaw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/593?planning-poker) with ZenHub @Eallan919 @hubgitian @ianperera @jakehova @jessecanderson @k-macmillan @mjones-oddball

**Comment by mjones-oddball** [comment]
Update: Dev was tested successfully, Staging is in progress. @k-macmillan Guessing perf environment will be next. We should probably get a head start on that so it's ready when they are done Staging.

**Comment by mjones-oddball** [comment]
Tagged as blocker external because we are coordinating with another group of people who execute testing on each environment. We need info from them to prep each environment and then they take a couple days to test. We have 2 environments left: perf and prod

**Comment by k-macmillan** [comment]
This is no longer externally blocked. We have received the necessary information from the SSOi team. 
The perf environment is currently being prepared for testing on our end.

**Comment by k-macmillan** [comment]
Perf environment setup was expediently taken care of by @jessecanderson . Passed baton back to SSOi team for pre-prod testing. Now awaiting any potential issues with perf as well as a prod id and secret. Task is likely to be blocked until early April due to a VA-wide Production Deployment Blackout.

**Comment by mjones-oddball** [comment]
@k-macmillan After pre-prod is done please close this. I'll make another ticket and link to this in the description. To your point earlier, had I known what the process would be like I would have split it up sooner. @zlaw

**Comment by mjones-oddball** [comment]
From Jeff 3/10: "Hi Kyle – the SSOi Oauth integration information has been delivered to our Access Management Business Owner Team who will now perform pre-production testing.  The due date for completion is on or before March 24."

**Comment by mjones-oddball** [comment]
I'm going to close this. If any issues arise from the SSOi team I'll create a new ticket to capture the work needed. Each time this process happened the environment passed with no additional effort after it passed our team's review.
