### ISSUE TITLE
Use templates for push notifications

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#594]
# Value Statement
**As** a member of the Mobile App team
**I want to** manage templates for push notifications
**So that** I can create and edit content for notifications

# Acceptance Criteria

## 1. Gotta provide the necessary stuff
**GIVEN** an API request `POST /service/{{service_id}}/template`
**WHEN** the request body contains `"template_type": "push"`
**THEN** the request should be validated to include the existing required fields
(`["name", "template_type", "content", "service", "created_by"]`)
**AND** the request should be rejected if any of those fields are not provided

## 2. You can also provide a field for data to be sent in the push
**GIVEN** an API request `POST /service/{{service_id}}/template`
**WHEN** the request body contains `"template_type": "push"`
**THEN** the request can optionally contain a new field, `push_data`, which should be a JSON object

## 3. Creation
**GIVEN** an API request `POST /service/{{service_id}}/template`
**WHEN** the request body contains `"template_type": "push"`
**THEN** the template is created
**AND** the ID returned can be used to query for that template's details

## 4. Validating request when sending notifications
**GIVEN** an API request `POST /notifications/push`
**THEN** the request body field `"template_id": "<some-uuid>"` should be validated to be a UUID
**AND** that ID should be validated to exist in the database as a push template
**AND** that template's placeholders (in the `subject`, `content`, and `push_data` fields) should be used to validate the personalisation in the request
**AND** the request should be rejected if any of the above conditions are not met

## 5. Using a template to send push notifications
**GIVEN** an API request `POST /notifications/push`
**WHEN** everything is valid (as described above)
**THEN** a JSON object should be constructed, by replacing placeholders in the template's `subject`, `content`, and `push_data` fields with values from the request's `personalisation`, and then by assembling those rendered fields into an object that [looks like this multi-platform example from AWS](https://docs.aws.amazon.com/sns/latest/dg/sns-send-custom-platform-specific-payloads-mobile-devices.html#mobile-push-send-multiplatform)
**AND** that object should be sent in the request to VEText to send a notification

# Checklist
- [ ] Update `Template` models and schemas to:
  - include new value for `template_type` enum = `push`
  - include new column `push_data`
- [ ] Add new JSONSchema for push templates - `["name", "template_type", "content", "service", "created_by"]` are required, and `subject` & `push_data` are optional
- [ ] In `send_push_notification` endpoint, validate the template
  - try to adapt and reuse existing `validate_template`, `create_content_for_notification`, and `check_placeholders` functions, but see if we can do all of this without having to touch `notification-utils`
- [ ] make sure the rendering of placeholders works with preview mode
- [ ] ensure template history works

# Cross Functional Checklist

Testing:
  - [ ] integration test for API

Monitoring:
  - [ ] statsd metrics
  - [ ] datadog graphs
  - [ ] datadog alterts

Security:
  - [ ] auth permissions
  - [ ] JsonSchema

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support
  - [ ] Openapi
  - [ ] ADR
  - [ ] Tech Debt wall

Mountebank
- [ ] API - create mocks for any external services calls

Postman
- [ ] Update collection whenever we change our API

# Assumptions
-

# Additional Info/Resources
- [Documentation on expected payload when sending notification to multiple platforms](https://docs.aws.amazon.com/sns/latest/dg/sns-send-custom-platform-specific-payloads-mobile-devices.html#mobile-push-send-multiplatform)
- An edited-for-clarity example of the object that VEText constructs when sending push notifications:

```
{
  "default": "Appointment Reminder Default",
  "APNS": {
    "aps": {
      "alert": {
        "title": "New Secure Message",
        "body": "Review your messages in the health care section of the VA app"
      }
    },
    "msgUrl": "%MSGURL%"
  },
  "APNS_SANDBOX": {
    "aps": {
      "alert": {
        "title": "New Secure Message",
        "body": "Review your messages in the health care section of the VA app"
      }
    },
    "msgUrl": "%MSGURL%"
  },
  "GCM": {
    "notification": {
      "title": "New Secure Message",
      "body": "Review your messages in the health care section of the VA app"
    },
    "data": {
      "msgUrl": "%MSGURL%"
    }
  }
}
```

The above example has been formatted for clarity - AWS actually expects each platform's block to be ["formatted as JSON key-value pair strings, with the quotation marks escaped"](https://docs.aws.amazon.com/sns/latest/dg/sns-send-custom-platform-specific-payloads-mobile-devices.html#mobile-push-send-json). You'll probably need to use `json.dumps(dict)` to serialise stuff - and you might need to do that serialisation multiple times on the nested blocks!.

# Out of Scope
-

# Open Questions
-

**Comment by npmartin-oddball** [comment]
To be discussed later.
