### ISSUE TITLE
Docker Container Upgrade - 3.6-alpine EOL

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#598]
# Observed Behavior
Docker is building with an image that hit EOL. Tested the smallest incremental version update and it made it through the [test, code scan, and dependency scan](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/1925183630).

# Desired Result
Container is updated with the latest stable release.

# Additional Info/Resources
- https://www.python.org/dev/peps/pep-0494/#lifespan
- https://devguide.python.org/#status-of-python-branches

## Cross Functional Checklist

Testing:

-   [ ] integration tests for API
-   [ ] Cypress (e2e) for UI

Monitoring:

-   [ ] statsd metrics
-   [ ] datadog graphs
-   [ ] datadog alterts

Security:

-   [ ] auth permissions and roles
-   [ ] Move API enpdoints to new user token auth

Marshmallow

-   [ ] Model serialization / deserialization

Documentation:

-   [ ] Readmes
-   [ ] Project specific
-   [ ] Support
-   [ ] Openapi
-   [ ] ADR
-   [ ] Tech Debt wall

Mountebank

-   [ ] Mock API enpoints including error scenarios

Accessibility

-   [ ] E2E & Testrail

Security:

-   [ ] auth permissions
-   [ ] JsonSchema

Postman

-   [ ] Update collection

**Comment by zlaw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/598?planning-poker) with ZenHub @ianperera @jakehova @jessecanderson @k-macmillan @mjones-oddball

**Comment by kalbfled** [comment]
I have all tests passing with Python 3.8 and Alpine 3.15.  I will create a code review as soon as I figure out how to resolve this little surprise:

```
.../notification-api$ git status
On branch 598_docker_container_upgrade
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   app/models.py
	modified:   ci/Dockerfile
	modified:   ci/Dockerfile.local
	modified:   ci/Dockerfile.test
	modified:   ci/Dockerfile.userflow
	modified:   requirements.txt
	modified:   requirements_for_test.txt

.../notification-api$ git commit
`pre-commit` not found.  Did you forget to activate your virtualenv?
```

I'm using the containers; not a virtual environment.
