### ISSUE TITLE
Improvement to Dockerfile.local to facilitate faster development

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#601]
# Expected Behavior
When I save changes to local source code, the development server should automatically restart to pick up the changes.  This is what happens when developing locally in a virtual environment.

# Actual Behavior
The container defined in Dockerfile.local is identical to the production Dockerfile in that it uses the COPY directive to move all source code from the build host to the container.  If I want to update the code on the Dockerfile.local container, I have to rebuild the container or manually copy it using `docker copy`.  This slows development.

A better approach is to use a [bind mount](https://docs.docker.com/storage/#good-use-cases-for-bind-mounts) to mount the local environment's source files to the container.  Additionally, Dockerfile.local should use the ENV directive to set [FLASK_ENV=development](https://flask.palletsprojects.com/en/1.1.x/cli/#environments).  This change will make the Flask dev server automatically restart upon changes and yield additional debug output.

# Additional

This task should include updating the README file.

# Ref

- https://docs.docker.com/get-started/06_bind_mounts/

**Comment by mjones-oddball** [comment]
@kalbfled Thank you for the ticket! I added our team label: Notify. We will discuss this more with the team in refinement :). In the future, do you mind @ing me and @zlaw on new tickets? Will help us to find them and alert me to prioritize them in our list.

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/601?planning-poker) with ZenHub @kalbfled
