### ISSUE TITLE
Reduce Docker images sizes by uninstalling build dependencies

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#603]
# Expected Behavior
Docker images should not have any unnecessary packages installed in order to minimize their size.

# Actual Behavior
The Dockerfiles install build dependencies, such as g++ and make, that are superfluous once a container is running.  We can uninstall those dependencies after they are used.  The Dockerfiles in notifications-api uninstall some packages now, but there's room for improvement.

@mjones-oddball @zlaw

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/603?planning-poker) with ZenHub @jakehova @ianperera @jessecanderson @kalbfled @k-macmillan

**Comment by kalbfled** [comment]
Reverted and reopened due to an error in Github Actions when trying to deploy the new containers to the dev environment.
