### ISSUE TITLE
VAProfile - JSON parse implementation

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#613]
# Value Statement
Preferences will be stored in the <name_tbd> table. The preferences from VA Profile will be stored in a json format. We need a way to get the correct preferences and return a boolean true/false if the method we plan on sending has been opted in. An opt-in represents a need to call VA Profile's API for more data.

# Acceptance Criteria
A method exists to take in an ICN and preference key and returns a true if the user is opted in.

# Checklist
- [ ] Method is written
- [ ] Tests are written

# Cross Functional Checklist

Testing:
  - [ ] integration test for API

Monitoring:
  - [ ] statsd metrics
  - [ ] datadog graphs
  - [ ] datadog alterts

Security:
  - [ ] auth permissions
  - [ ] JsonSchema

Transform requests to business models in our API
- [ ] Marshmallow model serialization / deserialization

Documentation:
  - [ ] Readmes
  - [ ] Project specific
  - [ ] Support
  - [ ] Openapi
  - [ ] ADR
  - [ ] Tech Debt wall

Mountebank
- [ ] API - create mocks for any external services calls

Postman
- [ ] Update collection whenever we change our API

# Assumptions
-

# Additional Info/Resources
-

# Out of Scope
-

# Open Questions
-

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/613?planning-poker) with ZenHub @k-macmillan @jakehova @ianperera @kalbfled

**Comment by mjones-oddball** [comment]
Determined not to be needed as we are not going to store a json string of preferences. We will only store the preference for this payment notification.
