### ISSUE TITLE
[Spike] Run one off task with Celery 4.x to test if it can use ECS assigned execution role

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#62]
As a notification developer, I want to use the most recent celery version so that we can verify updating celery is required to use the existing deploy/task execution role

Acceptance criteria:
**WHEN** sample celery fargate task is run
**AND** notification_ecs_task_execution role is used
**THEN** new sample SQS queue is created

Checklist:
- [x] create or use docker image to include the latest celery - the image should have a simple code so it creates one new SQS queue
- [x] create new task definition to use the image
- [x] run the task and confirm the queue is made

Additional info:
- can use the AmazonSQSFullAccess policy
- #30 is related to this user story

**Comment by saman-moshafi-va** [comment]
We created a task definition called `celery-test` and activated it.  The task was not able to create SQS but showed the error message `[2020-05-27 18:22:52,163: CRITICAL/MainProcess] Unrecoverable error: ClientError('An error occurred (AccessDenied) when calling the GetQueueAttributes operation: Access to the resource https://us-east-2.queue.amazonaws.com/ is denied.',)`.
This proves that upgrading to the latest celery allows a task to authenticate using the AWS metadata.

**Comment by saman-moshafi-va** [comment]
Used another role and the task created the SQS queue. So we should upgrade celery.

**Comment by saman-moshafi-va** [comment]
Dockerfile:
```
FROM python:3.6-alpine

ARG DEBIAN_FRONTEND=noninteractive
ENV PYTHONIOENCODING UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
RUN apk add --no-cache bash build-base git gcc musl-dev g++ make libffi-dev libmagic curl-dev libressl-dev && rm -rf /var/cache/apk/*
RUN python -m pip install wheel
RUN set -ex && mkdir /app

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

COPY . /app

CMD ["sh", "-c", "celery -A celery_run worker --loglevel=info"]
```
celery_run.py:
```
from celery import Celery

app = Celery('tasks', broker='sqs://')
app.conf.task_serializer = 'json'

@app.task
def consume(msg):
    print(msg)
```
requirements.txt:
`celery[sqs]==4.3.0`
