### ISSUE TITLE
Update email and sms template variables in Postman collection

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#620]
# Describe the Bug
In the Postman collection defined by notification-api.postman_collection.json, URLs for SMS and e-mail are reversed.

![api](https://user-images.githubusercontent.com/5375929/161609624-c6757359-85da-452a-a965-f4b81f38bb66.png)

Similarly, "get sms template" has e-mail in the URL.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/620?planning-poker) with ZenHub @k-macmillan @jakehova @ianperera @jessecanderson @kalbfled
