### ISSUE TITLE
Public Endpoint Enhancement for VEText Incoming Messages from Twilio

### ISSUE THREAD

**Issue by zlaw** [department-of-veterans-affairs/notification-api#622]
VEText may have a need for us to replace their public endpoint product, [pusher](http://pusher.com/), which allows them to receive messages from Twilio (i.e. 2 way messaging). Recently pusher has been unreliable. Downtime prevents VEText from receiving messages. In may they are launching the check-in solution.

- [x] Confirm we do in fact have a public endpoint (http://api.va.gov/vanotify/)
- [x]  Build a listener redirect rule on Notify ALB to receive and redirect incoming vettext requests 
- [x]  Update TWILIO webhook to call reverse proxy endpoint with /twoway/vettext route
- [x]  Confirm receipt and redirect of TWILIO webhook request
- [x]  Create Calling Lambda receiving point
- [x]  Create SQS for failed send requests
- [x]  Add code to Lambda to call VetText endpoint and drop to SQS if send fails
- [ ]  Create Scheduled Lambda that occasionally wakes up and drains the SQS
- [ ]  Document

Testing: 
- Texting (970) 300-5680 will go to our endpoint: https://api.va.gov/vanotify/. Need to update the endpoint once we do so for VEText. 
- To get to configuration of that number:
Log in to Twilio (VA Loma Linda SMS Development) -> Choose Phone Numbers product -> Go to Active Numbers -> Lookup 970-300-5680 ->  Go down to Messaging Section and update Webhook going to Notify endpoint
- [pull request for reverse proxy](https://github.com/department-of-veterans-affairs/devops/pull/8465/files/6de54fe399434598e098a1996b95fbfdaff7a2cf)

**Comment by jakehova** [comment]
Shane provided this sample endpoint for where we would forward incoming messages to: 

```
curl --request POST \
  --url https://staging.api.vetext.va.gov/api/vetext/pub/inbound-message/twilio \
  --header 'Authorization: Basic OEZCMTRGN0I1NjE0NERDMEE2RUFCMzI5NDU4NUE4OEE6YW43ZnFCTW92a0NXeStLL29NTnZXZz09' \
  --header 'Content-Type: application/json' \
  --data '{
  "accountSid": "adg5b3d2-bcd8-550d-b82e-33a727f5b646",
  "messageSid": "abcde1",
	"messagingServiceSid": "",
	"to": "53079",
	"from": "[+19095032925](tel:+19095032925)",
	"messageStatus": "",
  "body": "here"
}'
```

**Comment by jakehova** [comment]
ReverseProxy has been tested with Twilio and we have confirmed that incoming messages from Twilio can be received into AWS and redirected to Vetext.  

We are currently finalizing communication with the VeTeext endpoint in Staging.

**Comment by mjones-oddball** [comment]
We had issues connecting to VETexts endpoints for the following reasons (which were resolved):

1. The lambda wasn't connected to the right VPC
2. We were trying to validate the vetext endpoint cert, but their engineer (Rob) told us to bypass that

**Comment by jakehova** [comment]
We have confirmed communication flow from Twilio to Vetext.  We have also confirmed that when a message gets to us and we are unable to send it to the VeText endpoint, the message will drop into our failover queue to be tried again at a later time.  

I am writing up documentation of the process and the current solution today.
