### ISSUE TITLE
Onsite Notifications Code Changes

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#624]
## Value Statement

As a veteran
I want to see an alert in My VA when I have a new debt
So that I can navigate right where I need to go to manage it

We need to trigger a request to va.gov's API for onsite notifications when the following is true:
- [x] Template has onsite notifications enabled
- [x] Notification request contains an identifier that allows us to retrieve the VA Profile ID
- [x] VA Profile ID is found in MPI or provided by the business line in the request
- [x] Veteran is not deceased

The request should include va profile id and the template id.

Staging endpoint: https://staging-api.va.gov/v0/onsite_notifications
Production endpoint: https://api.va.gov/v0/onsite_notifications (need to validate this)

- **Onsite notifications will be sent regardless of communication preference and message status.**
- **Callback info specifically for onsite notifications will not be provided.**
- **If an error occurs with sending the onsite notification, it should not impact the other part of the notification (email, sms).**

## Acceptance Criteria

**GIVEN** a notification is sent to VA Notify
**WHEN** a template is enabled for onsite notifications
**AND** the veteran is not deceased
**AND** the va profile ID is found or present
**THEN** send a request to /v0/onsite_notifications via the applicable environment endpoint
**AND** continue with the normal notification evaluation and send process

**GIVEN** a notification is sent to VA Notify
**WHEN** a template is not enabled for onsite notifications
**THEN** continue with the normal notification evaluation and send process

## Checklist

- [x] notification workflow is updated
- [x] testing (integrated testing with AE team will come later)

## Assumptions

-

## Additional Info/Resources

-

## Out of Scope

-

## Open Questions

- What does AE team expect us to do if an error occurs? Should we be retrying?

## Cross Functional Checklist

Testing:

-   [ ] integration tests for API
-   [ ] Cypress (e2e) for UI

Monitoring:

-   [ ] statsd metrics
-   [ ] datadog graphs
-   [ ] datadog alterts

Security:

-   [ ] auth permissions and roles
-   [ ] Move API enpdoints to new user token auth

Marshmallow

-   [ ] Model serialization / deserialization

Documentation:

-   [ ] Readmes
-   [ ] Project specific
-   [ ] Support
-   [ ] Openapi
-   [ ] ADR
-   [ ] Tech Debt wall

Mountebank

-   [ ] Mock API enpoints including error scenarios

Accessibility

-   [ ] E2E & Testrail

Security:

-   [ ] auth permissions
-   [ ] JsonSchema

Postman

-   [ ] Update collection

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/624?planning-poker) with ZenHub @kalbfled @ianperera @jessecanderson @jakehova @k-macmillan

**Comment by EvanParish** [comment]
I've been working on getting the app running locally, but seem to be running into issues with the database. I got the notification-API running locally, but it's giving errors when trying to connect to the app through Postman. With Jesse's help, the issue was traced down to not having the database set up. Still a work in progress.

I've also been trying to identify the form of the data that I need to check in order to return the correct result. It would greatly help my efforts if I could get the application to run locally so I can check what data is going through the method I am trying to create and the one that calls it.

**Comment by EvanParish** [comment]
Met with Kyle and got put back on the right track. Currently I'm trying to retrieve the `va_profile_id` when it's being obtained and put into the celery task queue. I'll need some testing to make sure that this works as expected. 

I'm currently building out the requests for reaching the endpoints mentioned above.

**Comment by EvanParish** [comment]
I was asking about testing and David brought up unit testing. I'm starting to write unit tests for the new functionality now.

**Comment by EvanParish** [comment]
We received word that the changes necessary to connect to the onsite_notifications endpoint has been completed! Now we just need perform testing on our end to make sure it works.

**Comment by EvanParish** [comment]
After working on testing some more, some bugs were fixed in the code. The ICN issue was blocking doing testing in the AWS Dev environment. I should be able to make sure things are mostly working today.

**Comment by EvanParish** [comment]
I made some good progress on getting unit tests working for the new code, but we can't connect to the Onsite API outside of the VA network. I haven't been able to see what the actual responses will be to our HTTP requests. It makes testing with realistic responses very difficult for now.

**Comment by EvanParish** [comment]
I was able to get the Onsite code changes deployed to Dev and performed some initial testing. It looks like the method for retrieving the VA Profile ID needs to be from within the Celery tasks. This means some of the code needs to be reworked to fit into Celery tasks instead of being called externally. Currently working on the changes.

**Comment by EvanParish** [comment]
Changed the code to use a Celery task to send the Onsite notifications.

**Comment by k-macmillan** [comment]
Worked with Evan a bit on resolving some unit test issues. The onsite method needs to be inserted into the [mocked part of the unit tests](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/notifications/test_process_notifications.py#L355) that checks the chain. The unit tests mock the chain method by using the [patch](https://docs.python.org/3/library/unittest.mock.html#patch) method. Essentially this just verifies that each of those methods end up in the chain list.

**Comment by k-macmillan** [comment]
Worked with Evan some more to resolve some additional issues that came up after the last ones were resolved. @EvanParish Successfully deployed to the dev environment with his changes. We should `POST` to onsite's endpoint by EOD tomorrow.

**Comment by EvanParish** [comment]
Successfully connected to Onsite from our Dev environment after working through the last obstacles with Kyle and consulting with Tom Harrison! We had been missing part of the data that was supposed to be sent to Onsite. 
The correct format is:
```
{
  "onsite_notification": 
    {
      "template_id": "some_template_id", 
      "va_profile_id": "some_va_profile_id"
    }
}
```

**Comment by EvanParish** [comment]
The code changes are currently in a pull request awaiting approval. I have been responding to comments and making necessary changes.
