### ISSUE TITLE
Verify DEV environment against Twilio account

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#63]
As a notification developer, I want to automate the authorization and sending of requests so that I can verify that I can send texts/emails in the dev environment.

Acceptance criteria:
**GIVEN** Twilio account exists, notification-api is running, and celery workers are running,
**WHEN** we use postman to send a text message request with notification-api
**THEN** text message is received.

**WHEN** Postman post request is sent to notification-api
**THEN** response shows 200.

Checklist:
- [x] Research provisioning admin account
- [x] Create shared postman collection to automate auth and sending
- [x] Provision organization and test service for this use case (live mode)
- [x] Add API key + Twilio credentials to AWS parameters store
- [x] Receive successful response when text is sent
- [x] Check in postman collection to the repository

**Comment by saman-moshafi-va** [comment]
* to communicate with the server the config values are used to generate token.  To use the `create_jwt_token('<config value for key>', '<config value >')`. These values should be added to the secrets. To run the code on local computer we had to install ntp as jwt relies on clock syns. 
* The CDS-SNC product manager confirmed that users are manually promoted by running DB scripts, a flag in the user record.

**Comment by lingtran** [comment]
- Created user, organisation and service, along with pre-request script to generate auth token
- Added to created Postman collection, which will be shared soon. Contains env vars.

Remaining to do's: 
- Create a template so that message can be sent.
- Create directory with README for Postman collection in repo.

**Comment by philherbert** [comment]
<img width="1407" alt="Screen Shot 2020-06-03 at 16 14 36" src="https://user-images.githubusercontent.com/9078954/83686828-e99a7200-a5b8-11ea-8ce2-cdc82ab86c0a.png">

**Comment by saman-moshafi-va** [comment]
Sent SMS message, received the text and as expected this was logged in api cloudwatch log:
```
2020-06-03T17:52:21.743-04:00 | 54.204.224.176 - - [03/Jun/2020:21:52:21 +0000] "POST /notifications/sms/twilio/3e6cf02b-3c6a-4433-bfce-414c31652ae1 HTTP/1.1" 200 125 "-" "TwilioProxy/1.1"
-- | --
```
Twilio should call a URL, /notifications/sms/twilio/<notification-id> each time a message is sent.

**Comment by anushyaprasad** [comment]
Filip to take a look and close
