### ISSUE TITLE
Refactor models.py

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#631]
## User Story - Business Need

models.py is monolithic--it contains all of the data class and is over 2100 lines.  A more easily manageable implementation might be to decompose this file into separate model files in the respective folder.  For example, move app/models.py::Service to app/service/models.py, which doesn't currently exist.

### User Story(ies)

**As a** developer
**I want** a predictable layout and manageable file sizes
**So that** code is modular, easier to test, and easier for new team members to understand.

### Additional Info and Resources

The structure I have in mind would be similar to the [structure imposed by Django](https://docs.djangoproject.com/en/4.0/intro/tutorial01/).

## Engineering Checklist

- [ ] app/models.py decomposed into separate models.py files in their respective folders
- [ ] All import statements updated (a.k.a. no ImportErrors when running the app)

## Acceptance Criteria

- [ ] All unit tests continue to pass
- [ ] app/models.py deleted

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies

It might make sense to create linked tickets to perform this refactoring on a per-model basis.

## Out of Scope
_Leave blank if n/a_

**Comment by zlaw** [comment]
This should be dependent on a spike to determine refactored structure.

**Comment by k-macmillan** [comment]
Not planned for the existing database.
