### ISSUE TITLE
VA Profile Sync - Opt-in and Opt-out Stored Procedures

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#633]
## Value Statement

**As** VA Notify
**I want to** update our local copy of comp and pen preferences based on opt in changes
**So that** our data is always accurate

## Outcomes

- [ ] Create one stored procedure for opt-ins (insert new record)
- [ ] Create one stored procedure for opt-outs (delete existing record)

## Acceptance Criteria

**GIVEN** VA Profile sends us a transaction
**WHEN** allowed = true
**AND** the va profile id does not exist in our table with that communication item ID and channel type
**THEN** insert a new record

**GIVEN** VA Profile sends us a transaction
**WHEN** allowed = true
**AND** the va profile id already exists in our table with that communication item ID and channel type
**THEN** make no change

**GIVEN** VA Profile sends us a transaction
**WHEN** allowed = false
**AND** the va profile id exists in our table with that communication item ID and channel type
**THEN** delete the matching record

**GIVEN** VA Profile sends us a transaction
**WHEN** allowed = false
**AND** the va profile id does not exist in our table with that communication item ID and channel type
**THEN** make no change

## Checklist

-   [ ] Checklist item here

## Assumptions

-

## Additional Info/Resources

-

## Out of Scope

-

## Open Questions

-

## Cross Functional Checklist

Testing:

-   [ ] integration tests for API
-   [ ] Cypress (e2e) for UI

Monitoring:

-   [ ] statsd metrics
-   [ ] datadog graphs
-   [ ] datadog alterts

Security:

-   [ ] auth permissions and roles
-   [ ] Move API enpdoints to new user token auth

Marshmallow

-   [ ] Model serialization / deserialization

Documentation:

-   [ ] Readmes
-   [ ] Project specific
-   [ ] Support
-   [ ] Openapi
-   [ ] ADR
-   [ ] Tech Debt wall

Mountebank

-   [ ] Mock API enpoints including error scenarios

Accessibility

-   [ ] E2E & Testrail

Security:

-   [ ] auth permissions
-   [ ] JsonSchema

Postman

-   [ ] Update collection

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/633?planning-poker) with ZenHub @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by kalbfled** [comment]
Postgres Upsert: https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-upsert/

**Comment by kalbfled** [comment]
@mjones-oddball @k-macmillan I'm thinking that the lambdas for VA Profile opt-in/out are going to have to run directly the queries that stored procedures would execute.  I can get stored procedures onto the db container for local development, but I don't see a way to create them in RDS because all the Postgres instances are in virtual private clouds (VPCs).  Unless I'm missing something, I have no way to run a query on RDS.

**Comment by mjones-oddball** [comment]
@kalbfled Can you provide a summary here about the resolution?

**Comment by kalbfled** [comment]
@mjones-oddball I discovered (after a helpful suggestion from @k-macmillan) that I can create stored functions (not procedures) via migrations, which run locally and on AWS.

This ticket ended up being an 8, rather than a 3.  I went through three revisions to find a workable process.
