### ISSUE TITLE
VA Profile Sync - Lambda

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#635]
## Request

- [x] Create a lambda that will determine whether opt-in or opt-out is needed and call the applicable SP
- [ ] Deployment activities
- [ ] Testing

## Cross Functional Checklist

Testing:

-   [ ] integration tests for API
-   [ ] Cypress (e2e) for UI

Monitoring:

-   [ ] statsd metrics
-   [ ] datadog graphs
-   [ ] datadog alterts

Security:

-   [ ] auth permissions and roles
-   [ ] Move API enpdoints to new user token auth

Marshmallow

-   [ ] Model serialization / deserialization

Documentation:

-   [ ] Readmes
-   [ ] Project specific
-   [ ] Support
-   [ ] Openapi
-   [ ] ADR
-   [ ] Tech Debt wall

Mountebank

-   [ ] Mock API enpoints including error scenarios

Accessibility

-   [ ] E2E & Testrail

Security:

-   [ ] auth permissions
-   [ ] JsonSchema

Postman

-   [ ] Update collection

**Comment by mjones-oddball** [comment]
@kalbfled Can we add a filter to the lambda so that we're only accepting certain communication ids (actual id TBD). If it doesn't match the communication id(s) we're expecting then we shouldn't call the stored functions and should send back the appropriate response to VAPRO (COMPLETED_NOOP).

**Comment by mjones-oddball** [comment]
@kalbfled a new task was created to address the PUT to VAPRO at the end of processing the transaction, so that item was removed from this ticket.

**Comment by mjones-oddball** [comment]
@kalbfled not sure where to track this, but VA Profile said comp & pen preference ID will be 5. Do you need a new ticket to update that or is this one fine?

**Comment by kalbfled** [comment]
@mjones-oddball New ticket, please.

**Comment by mjones-oddball** [comment]
@kalbfled is this complete? Please close issue if so.

**Comment by kalbfled** [comment]
@mjones-oddball The coding is complete, and the changes are on the dev branch for testing.  I haven't closed the ticket because I haven't merged to master.  An issue probably not related to my changes is causing a "user-flows" test failure.  (See the Actions output.)
