### ISSUE TITLE
BUG: New Github Login Error - No Account Found

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#639]
## Note - this is high priority as it is blocking a business line from onboarding
**Describe the bug**
Shankara Subramanian, shankara@switchlane.com, attempted to login to staging with his github account. This was a new login. He received the following error message upon authenticating successfully and being redirected:

![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/3990d5d0-6453-4531-9e7b-2cf70c1794c9)

**To Reproduce**
1. Go to https://staging.notification.va.gov while on the VA Network
2. Click on Sign in with Github
3. Log in with an account that has not yet logged into Staging
4. See error: Your account was not found.

**Expected behavior**
You should see the message: You are not assigned to any services (paraphrasing) and the new account should be created in the database.

**Screenshots**
See above

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mjones-oddball** [comment]
@ianperera Future PeriOptimization user was unable to login to Staging with Github. @jessecanderson took a quick look and thinks it may be related to the recent changes made for having users assigned to > 10 services. Can you please focus on this with urgency? If you're working on anything else for Strike or Notify that you feel is urgent or could block others let me know and I'll coordinate. FYI @zlaw

**Comment by jakehova** [comment]
Does this only occur with people that havent logged in using github before?

**Comment by ianperera** [comment]
When I tried on local with a new github user, it worked well.  Not sure how to replicate the issue

**Comment by ianperera** [comment]
From the codebase, the issue raised when user has already registered with an email and then trying to sign up with github user which is authorized with same email.

**Comment by ianperera** [comment]
@mjones-oddball Only github account who are a member  of `department-of-veterans-affairs` can signup using the github

**Comment by mjones-oddball** [comment]
**Root cause analysis:** A new user without access to department-of-veterans-affairs org in github attempted to log into staging. The user was authorized, but failed that additional check and thus was redirected to the error page. Since github won't be used after PIV is fully implemented we will not pursue enhancements to the error page for this specific case. However, in the future we will need to provide this guidance during onboarding and if the error recurs, ask this before escalating.

**Comment by mjones-oddball** [comment]
This has been deemed, working as expected, and has been closed. The user was sent instructions to gain access to the va org.
