### ISSUE TITLE
Create Product outline 

### ISSUE THREAD

**Issue by anushyaprasad** [department-of-veterans-affairs/notification-api#64]
https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/product-management/product-outline-template.md

**Comment by anushyaprasad** [comment]
Megan Kelly to confirm location by EOD 06/12

**Comment by philherbert** [comment]
Moving to done because the only thing remaining is figuring out where to put it - @anushyaprasad to make a card for that
