### ISSUE TITLE
Revisions to VA Profile Sync Schema and Stored Functions

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#649]
We've decided to reach out to MPI each time we're processing a comp and pen notification instead of storing pid:va profile id links and having to keep those up to date. MPI has not indicated any issue in receiving millions of calls unless it's all within a short people of time (minutes).

Additionally, VA Profile has let us know that they will send us all transactions and cannot guarantee the order in which we receive them. So we will need to assess source date compared to our table to ensure we aren't processing an older update after a more recent update. (i.e., person opts out and then immediately opts back in would result in 2 transactions that we are receiving asynchronously)

Changes needed:

- [x] Update the VAProfileLocalCache data model in models.py:
    - [x] Remove participant id column
    - [x] Add source date column
    - [x] Update the channel name column to channel type id (update from current data type to INT)
    - [x] Remove the MPI ICN column
- [x] Opt-outs (deletes) should utilize pg_sleep for 1 minute to minimize the risk of adding an old opt-in back into the table after an opt-out was processed.
- [x] Update the Stored Procedures for opt-in and opt-out
    - [x] Reduce the 2 stored functions to 1 (Dave will discuss this with Maham)
    - [x] No longer use participant id
    - [x] Add source date to insert
    - [x] Compare VA Profile's transaction source date to the source date stored in our database before inserting or deleting. If the source date is not more recent than our source date we should not proceed with the update.
    - [ ] Return a value at the end of the stored function to indicate if a change to our database occurred (e.g. insert, update, etc.) -- this will be used by the lambda to PUT a status back to VAPRO
- [ ] testing

## Reference

Sample from VA profile

```
               {
  "txAuditId": "aea19e1e-7889-4011-97b9-b797c4339746",
  "identities": [
    "32434792^PI^200CORP^USVBA",
    "1200024851V688668^NI^200M^USVHA",
    "94953^PI^200VETS^USDVA"
  ],
  "bios": [
    {
      "createDate": "2022-04-27T17:01:37Z",
      "updateDate": "2022-04-27T17:01:37Z",
      "txAuditId": "aea19e1e-7889-4011-97b9-b797c4339746",
      "sourceSystem": "VAPROFILE-TEST-PARTNER",
      "sourceDate": "2022-04-27T16:57:16Z",
      "originatingSourceSystem": "string",
      "sourceSystemUser": "string",
      "communicationPermissionId": 9188,
      "vaProfileId": 94953,
      "communicationChannelId": 1,
      "communicationItemId": 1,
      "communicationChannelName": "Text",
      "communicationItemCommonName": "Board of Veterans' Appeals hearing reminder",
      "allowed": true
    }
  ]
}
 
```

**Comment by mjones-oddball** [comment]
Dave will pair with someone else to KT and then they can do the work and testing

**Comment by kalbfled** [comment]
@mjones-oddball @k-macmillan @maham360 @jakehova 

We discussed that the time delay implementation is unsatisfactory because the lambda function that calls the Postgres stored functions would have to run for at least a minute, thereby significantly increasing the AWS bill.  One could implement a more complicated AWS setup in which API calls from VA Profile put a task on SQS that delays for a minute and then calls a lambda that would call a stored function which no build-in delay, but the developers prefer a more simple implementation.

We could have opt-in/out status be a boolean column, and opting-out would become setting this boolean to False rather than deleting the row.  The table would still need the time stamp column already required by this ticket.  The stored functions would run an UPDATE query that applies WHERE the time stamp of the current request is newer than the time stamp in the database.

If we are concerned about storage space, we can run a nightly cron job to delete all opted-out rows older than a day.

**Comment by mjones-oddball** [comment]
Hi @maham360 - @kalbfled, @k-macmillan and I met to discuss the va profile sync process as a whole and determined we need a couple more changes. 

1. To your question "Compare VA Profile's transaction source date to the source date stored in our database before inserting or deleting. If the source date is not more recent than our source date we should not proceed with the update.
Are you saying if the VA profile's source date is older than our source date we already have, then don't update?"
**Correct. If the source date in the transaction we're processing is older than a record that exists in our database for the same person/communication item/channel, we would not update because the transaction is out of date.**
2. Because we are no longer deleting opt-outs via an opt-out function there's no need to have 2 stored functions. We will condense to 1 so we don't have duplicate code to maintain. (new checkbox in task)
3. In the va_profile_local_cache table we need to update the following in addition to the changes you've already made (new checkboxes in task):
- Update the channel name column to channel type id (update from current data type to INT)
- Remove the MPI ICN column
4. We need a status returned at the end of the stored function so we know if a change was made to the database or not. This will be used to send a PUT request back to VA Profile so they know what we did with the veteran's data. (new checkbox added to task)

**Comment by mjones-oddball** [comment]
@maham360 When you have the finalized column names for va_profile_local_cache can you let me know? Will be helpful for QA. CC @Jake-Uhteg

**Comment by maham360** [comment]
using select count(*) to return a value at the end of the stored function to indicate if a change to our database occurred

**Comment by mjones-oddball** [comment]
@maham360 If an update instead of an insert happens won't the count be unchanged?

**Comment by maham360** [comment]
Yes. Instead of doing select count(*) I am doing Select exists for where “allowed” is true or false

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by maham360** [comment]
rewriting code to branch WITH EXISTING for an option to opt in or opt out

**Comment by maham360** [comment]
current code:

```
va_profile_opt_in_out = PGFunction(
  schema="public",
  signature="va_profile_opt_in_out(_va_profile_id integer, _communication_item_id integer, _communication_channel_id integer, _allowed Boolean, _source_datetime timestamp)",
  definition="""\
RETURNS boolean
LANGUAGE sql AS $$
    INSERT INTO va_profile_local_cache(va_profile_id, communication_item_id, communication_channel_name, source_datetime)
    VALUES(_va_profile_id, _communication_item_id, _communication_channel_name, _source_datetime)
    WITH matching_id AS(
        SELECT *
        FROM va_profile_local_cache
        WHERE va_profile_id = _va_profile_id 
        AND communication_item_id = _communication_item_id 
        AND communication_channel_id = _communication_channel_id
    )
    CASE WHEN allowed='True' THEN
        CASE matching_id 
            WITH newer as _source_datetime > source_datetime
        CASE newer THEN UPDATE va_profile_local_cache
```

working on returning TRUE and FALSE for allowed

**Comment by mjones-oddball** [comment]
@maham360 This might already be on your radar, but just in case - communication_channel_name instances should be updated to communiciation_channel_id right? I see it's in your select, but not the insert section.

**Comment by maham360** [comment]
yes you're right, i must have missed that

**Comment by mjones-oddball** [comment]
@maham360 I think you're missing a SET row for source datetime and the opt in columns after the DO UPDATE. Also didn't see the opt in column in your INSERT VALUES list. CC @k-macmillan (pls correct me if I'm wrong)

**Comment by maham360** [comment]
va_profile_opt_in_out = PGFunction(
  schema="public",
  signature="va_profile_opt_in_out(_va_profile_id integer, _communication_item_id integer, _communication_channel_id integer, _allowed Boolean, _source_datetime timestamp)",
  definition="""\
RETURNS boolean
LANGUAGE sql AS $$
    INSERT INTO va_profile_local_cache(va_profile_id, communication_item_id, communication_channel_id, source_datetime)
    VALUES(_va_profile_id, _communication_item_id, _communication_channel_id, _source_datetime)
    ON CONFLICT ON CONSTRAINT va_profile_local_cache_pkey
    DO UPDATE va_profile_local_cache
    SET source_datetime = CURRENT_TIMESTAMP
    WHERE _source_datetime > source_datetime
    AND va_profile_id = _va_profile_id 
    AND communication_item_id = _communication_item_id 
    AND communication_channel_id = _communication_channel_id
$$;"""
)

Return rows affected by update query using RETURNING??

**Comment by maham360** [comment]
returning va_profileID to get row count, currently troubleshooting

```
va_profile_opt_in_out = PGFunction(
  schema="public",
  signature="va_profile_opt_in_out(_va_profile_id integer, _communication_item_id integer, _communication_channel_id integer, _allowed Boolean, _source_datetime timestamp)",
  definition="""\
RETURNS SETOF integer
LANGUAGE sql AS $$
    INSERT INTO va_profile_local_cache(va_profile_id, communication_item_id, communication_channel_id, source_datetime)
    VALUES(_va_profile_id, _communication_item_id, _communication_channel_id, _source_datetime)
    ON CONFLICT ON CONSTRAINT va_profile_local_cache_pkey
    DO UPDATE
    SET source_datetime = CURRENT_TIMESTAMP
    WHERE _source_datetime > source_datetime
    AND va_profile_id = _va_profile_id 
    AND communication_item_id = _communication_item_id 
    AND communication_channel_id = _communication_channel_id
    RETURNING va_profile_id
$$;"""
)
```

**Comment by kalbfled** [comment]
The changes to the local cache table and stored function have been included in branch 679.  The outstanding changes will be made as part of #691.
