### ISSUE TITLE
Staging - Configure the reply-to email for VBA Education

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#654]
VBA education is ready to test their new no-reply mailbox with their email 33 notifications. Please update the reply-to email address and let @mjones-oddball know when it's ready for testing. If you can trigger a test email to yourself as a mini-validation please do so.

Set the reply-to email to VBAATGDoNotReply@va.gov on Staging for the following templates:

- [x] Email33 opt in, Template ID: `6e6c1602-049d-455c-a9fb-d97912b8624a`
- [x] Email33 attendance verify, Template ID: `ba3f35d2-f8d9-4fd5-9cce-160bf6c69efc`
- [x] Email33 attendance verify follow up, Template ID: `b52aec34-6043-4104-b8f0-a34d855e3bb0`

**Comment by jessecanderson** [comment]
Do we have the specific template that we need updated with the `reply-to` address in staging?

**Comment by mjones-oddball** [comment]
Got my access and pulled the template ids

**Comment by EvanParish** [comment]
Updated the "reply_to_email" address on the listed templates.

**Comment by EvanParish** [comment]
Could not validate with my oddball email address since I don't have a valid API key for these services.

**Comment by EvanParish** [comment]
@mjones-oddball 
Unable to verify that the "reply_to_email" is set. 

When looking at the template we can verify that that email is set correctly.
`"reply_to_email": "VBAATGDoNotReply@va.gov"`

```
{
    "errors": [
        {
            "error": "BadRequestError",
            "message": "Can’t send to this recipient when service is in trial mode – see https://www.notifications.service.gov.uk/trial-mode"
        }
    ],
    "status_code": 400
}
```

**Comment by mjones-oddball** [comment]
Hi @EvanParish! Thanks for the update. We need to ensure the business line will be able to test successfully so I'm glad we tried and are encountering this now as opposed to having the business line tell us there is a problem. Please work with @k-macmillan to understand what is needed to get this service in the right state.

**Comment by EvanParish** [comment]
Kyle was able to disable the restricted mode for testing. We have successfully sent emails and received them. 
@mjones-oddball would we now call this complete?

Here's the details block from the email with the updated "reply-to" email address:
```
     from: 	U.S. Department of Veterans Affairs <staging-do-not-reply@notifications.va.gov>
 reply-to:	vbaatgdonotreply@va.gov
       to:	evan.parish@oddball.io
     date:	May 5, 2022, 11:31 AM
  subject:	Confirmation: You’ve been enrolled into VA’s Email Verification!
mailed-by:	ses.notifications.va.gov
```
