### ISSUE TITLE
SPIKE: Templating for task definition JSONs

### ISSUE THREAD

**Issue by philherbert** [department-of-veterans-affairs/notification-api#66]
We currently use three JSON files to render and deploy task definitions for running the API, Celery, and Celery beat:

- `dev-api-task-definition.json`
- `dev-celery-beat-task-definition.json`
- `dev-celery-task-definition.json`

These are all _pretty much_ the same - all the environment variables are identical, and we don't want to have those duplicated in three places. One of the only differences is `containerDefinitions[0].command`, which we execute inside the container.

The field `containerDefinitions[0].image` is replaced by Github Actions - is there a way of doing arbitrary templating, so we can have **one** JSON file, and replace the command?

**Comment by mjones-oddball** [comment]
Things have changed since this ticket was created. No longer needed.
