### ISSUE TITLE
remove unused dependency for lambda two_way_sms

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#662]
## Issue

The file [lambda_functions/two_way_sms/requirements-lambda.txt](https://github.com/department-of-veterans-affairs/notification-api/blob/master/lambda_functions/two_way_sms/requirements-lambda.txt) contains a single dependency that is not used in the associated two_way_sms_lambda.py.

## Resolution

Delete requirements-lambda.txt.

@mjones-oddball

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/662?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by kalbfled** [comment]
Fixed for #736.
