### ISSUE TITLE
Spike: Upgrade SQLAlchemy from 1.3 to 1.4 Review

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#665]
## Goal

Determine and document what direct benefits we would get from an upgrade. What problems would we solve if we upgraded.

## Checklist

-   [ ] Review of changelog between 1.3 and current 1.4 release
-   [ ] Document **problems resolved** as a potential result of an upgrade
-   [ ] Document breaking changes (dependencies, API changes, etc.)

## Timebox

2 days

# Additional Info/Resources

- https://docs.sqlalchemy.org/en/14/index.html
- https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html
- https://docs.sqlalchemy.org/en/14/changelog/migration_14.html

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/665?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by mjones-oddball** [comment]
Determined this is not needed. Handling the upgrade on https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1068
