### ISSUE TITLE
Add JWT Expiration Code Check to API

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#666]
## Value Statement

**As** VA Notify
**I want to** Ensure services don't have enough rope to hang themselves
**So that** Services appreciate our product

A check for never-expiring JWTs was not found in our API. I tested by removing the `exp` field from JWT generation and sent myself a text using our API, the text went through. 

This ticket is to add the checker method to the code, without calling it (for now). It would be called after the JWT is verified:

- [Here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/authentication/auth.py#L84). 
- [Here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/authentication/auth.py#L167)
- [Here](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/authentication/auth.py#L205).

## Checklist

- [ ] Checker method implemented behind a feature flag
- [ ] Test method setup similar to [this one](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/authentication/test_authentication.py#L72).
- [ ] document the feature flag process (steps to add one)

## Additional Info/Resources

- Example showing collection of `exp` without the need for a key:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/7f8e48ab-1589-49d5-b3ee-81085bbb9727)

## Out of Scope

- Enabling this feature (unless okay'd by Bev & Melanie)

## Cross Functional Checklist

Testing:

-   [ ] integration tests for API
-   [ ] Cypress (e2e) for UI

Monitoring:

-   [ ] statsd metrics
-   [ ] datadog graphs
-   [ ] datadog alterts

Security:

-   [ ] auth permissions and roles
-   [ ] Move API enpdoints to new user token auth

Marshmallow

-   [ ] Model serialization / deserialization

Documentation:

-   [ ] Readmes
-   [ ] Project specific
-   [ ] Support
-   [ ] Openapi
-   [ ] ADR
-   [ ] Tech Debt wall

Mountebank

-   [ ] Mock API enpoints including error scenarios

Accessibility

-   [ ] E2E & Testrail

Security:

-   [ ] auth permissions
-   [ ] JsonSchema

Postman

-   [ ] Update collection

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/666?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by k-macmillan** [comment]
Part of a larger discussion. This is not moving forward.
