### ISSUE TITLE
Removal of "going live" email

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#667]
## Acceptance Criteria

**GIVEN** A service is taken out of trial mode
**WHEN** Service is changed from `restricted: True` to `restricted: False`
**THEN** No email is sent

## Checklist

-   [ ] Send is disabled
- [ ] Testing

## Additional Info/Resources

- Golive [template](https://github.com/department-of-veterans-affairs/notification-api/blob/master/migrations/versions/0301c_update_golive_template.py) ID: `618185c6-3636-49cd-b7d2-6f6f5eb3bdde`

## Cross Functional Checklist

Testing:

-   [ ] integration tests for API
-   [ ] Cypress (e2e) for UI

Monitoring:

-   [ ] statsd metrics
-   [ ] datadog graphs
-   [ ] datadog alterts

Security:

-   [ ] auth permissions and roles
-   [ ] Move API enpdoints to new user token auth

Marshmallow

-   [ ] Model serialization / deserialization

Documentation:

-   [ ] Readmes
-   [ ] Project specific
-   [ ] Support
-   [ ] Openapi
-   [ ] ADR
-   [ ] Tech Debt wall

Mountebank

-   [ ] Mock API enpoints including error scenarios

Accessibility

-   [ ] E2E & Testrail

Security:

-   [ ] auth permissions
-   [ ] JsonSchema

Postman

-   [ ] Update collection

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/667?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360
