### ISSUE TITLE
Spike: Investigate Rate Limit

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#669]
## Goal

Services have a `rate_limit` field. Document what this is and how it affects the service.

## Checklist

- [x] Document 
- [x] Discuss findings with team

## Timebox

0.5 days

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/669?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by maham360** [comment]
The READme contained the information we were looking for minus the specific rate_limit we have which I included.

**Comment by maham360** [comment]
merged .md file into teams repo
