### ISSUE TITLE
restore directions for developing in a local environment

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#676]
#644 removed instruction for development using a local environment, but some team members indicated that they are running notification-api locally rather than using the containers.

- Add instructions to README.md
- Restore and update requirements_for_local.txt

**Comment by ianperera** [comment]
@jessecanderson, made a branch #676.
- currently, python 3.6.10 is not compatible with latest MacOS, (Apple Silicon, Monterey), will need to update python. working on making a plan.
- also, wanted to get portal and api work with in sync.

**Comment by jessecanderson** [comment]
@ianperera The `3.6.10` is the old version of python that I had pulled from the old instructions and we wanted to be up to at least `3.8.10` for macOS and whatever it needs to be equivalent for Windows installations.

**Comment by ianperera** [comment]
@jessecanderson, awesome thanks for your input.

**Comment by ianperera** [comment]
PR created [#848](https://github.com/department-of-veterans-affairs/notification-api/pull/848) - Completed
