### ISSUE TITLE
VA Profile Sync - Lambda - PUT request to VAPRO

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#679]
At the end of processing the preference transaction from VA Profile, we should send the appropriate status back via a PUT request.

- [x] Add PUT request to the lambda
- [x] Incorporate mTLS authentication (moved to a different ticket)

Joshua explained they only care about 3 status returns:

COMPLETED_NOOP
We received the data and decided not to act on it
COMPLETED_SUCCESS
We decided to modify our cache and did it
COMPLETED_FAILURE
Systematic issue that stopped entry into the database

![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/1ab2732c-9870-4c17-af2f-96f707d8c47c)

**Comment by mjones-oddball** [comment]
We need the status to be returned via the stored function to send the applicable PUT.

**Comment by k-macmillan** [comment]
Meeting with Joshua Lindsey today to ensure we understand what status they are expecting with given scenarios.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/679?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by k-macmillan** [comment]
Joshua explained they only care about 3 status returns:
- `COMPLETED_NOOP`
  - We received the data and decided not to act on it
- `COMPLETED_SUCCESS`
  - We decided to modify our cache
- `COMPLETED_FAILURE`
  - Systematic issue that stopped entry into the database
@kalbfled @mjones-oddball

**Comment by mjones-oddball** [comment]
Hi @EvanParish I'm not sure. Kyle was working with Josh prior to leaving, but I'm not sure if anything specific was decided. We already integrate with VA Profile though so I'm curious if we already know based on our existing code. If there's any question as to what algorithm will be used you or @kalbfled can reach out to Joshua Lindsey via email or DSVA slack to confirm.

**Comment by kalbfled** [comment]
@mjones-oddball I made a note about mTLS on #634.  I think that is the correct ticket to address that.  I'm still working on it.

**Comment by mjones-oddball** [comment]
@kalbfled ok then I'll adjust the description and close this.

**Comment by kalbfled** [comment]
Correction: I need to read the Notify cert and include that in my PUT request to Profile.
https://docs.python.org/3.8/library/http.client.html#http.client.HTTPSConnection
