### ISSUE TITLE
VA Profile Sync - Add Lambda Unit Tests

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#680]
https://github.com/department-of-veterans-affairs/notification-api/tree/master/tests/lambda_functions

- [ ] Add unit tests for our new preference lambda

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/680?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by mjones-oddball** [comment]
@kalbfled I saw you moved this to in progress so I've assigned you. If that's incorrect please update the ticket!

**Comment by kalbfled** [comment]
Changes for this ticket will not implement testing the lambda function's PUT requests because the lambda is going to change again.  See #704.
