### ISSUE TITLE
QA Assessment of VA Notify - Continued 

### ISSUE THREAD

**Issue by Jake-Uhteg** [department-of-veterans-affairs/notification-api#682]
- Review with product and Bev (i.e., establish SOPs, increase automated testing in X area, create test cases for SSUI, etc.)" 
- Determine platforms/apps that will need regression. Once those are determine, I will learn them and build a regression plan. Plan can be documented in Test Rails.
- Finalize ticketing process with PM and Engineering team. (QA in DEV ticket, separate ticket, etc.)

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/682?planning-poker) with ZenHub @Jake-Uhteg

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/682?planning-poker) with ZenHub @mjones-oddball

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/682?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by Jake-Uhteg** [comment]
QA Plan:

Before Start of Sprint
QA will review tickets before they are scheduled into a sprint for development and begin to determine testing steps. Test steps will be entered into Test Rails. 

At Start of Sprint
QA will meet with PMs and Bev to review test cases for accuracy of scope.
If it is determined that any additional development work will be necessary to complete testing, those conversations can take place during priority and/or refinement meetings with the engineers. 

During Sprint
A ‘QA’ tag can be added to engineering tickets that will require QA. Tickets can be worked by engineering from the appropriate lane. Once the ticket is moved to the ‘Testing’ lane, functional 
functional testing will occur on the front-end of the platform/application that is being updated. Regression will take place if/when determined necessary by QA and Engineers. Testing progress will be tracked in real time using Test Rails. 

Sprint End
When QA is completed, the ticket will be moved to the ‘Done’ lane. If QA is not completed by the end of a sprint, the ticket can be moved to the next sprint, or a new ticket for only the QA portion can be created and added into the next sprint cycle.
