### ISSUE TITLE
VA Profile Sync - Update Lambda with the Comp & Pen Id Filter

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#684]
VAPRO let us know that the Comp & Pen Id will be 5. Please ensure that our lambda filters to only accept this Id. If a communication item id that is not 5 is detected we should not call our function and skip to the end where we PUT "COMPLETED_NOOP".

- [x] Lambda filter is updated
- [x] PUT is updated
- [ ] Unit tests?

**Comment by maham360** [comment]
updated lamba filter to accpet 5 for Id, will update PUT

**Comment by maham360** [comment]
Added: 

```
        if record.get("communicationItemId", '') != 5:
            put_record["status"] = "COMPLETED_NOOP" 
```

will work on unit testing
