### ISSUE TITLE
Staging SSOi error - unauthorized

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#687]
Please look into the error below and help us understand why login failed so we can resolve.

Bev tried to log in with PIV on Staging between 3 & 4 pm on 5/24/22. She has a Sec Id in SQA.

Upon entering her PIV credentials she was redirected to our site with this error page:
 ![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/474e5944-465d-42ac-a3d8-396678420516)

**Comment by mjones-oddball** [comment]
From Jesse's initial glance. Would need to look into logs.
```
except Exception as e:
        current_app.logger.exception(e)
        statsd_client.incr('oauth.authorization.failure')
        response = make_response({'error': 'Unauthorized', 'description': 'Authentication failure'}, 401)
        return response
```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/687?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by ianperera** [comment]
I got direction from Jesse, I couldn't reproduce that error, but got another one. I am working on the suggestions from Jesse.

**Comment by ianperera** [comment]
more than likely our SSOI integration is intact but the issue is on their side, however, due to staging being portal, we need to implement the SSOI logic, not sure if there is already a ticket for this.

**Comment by mjones-oddball** [comment]
@ianperera Hey Ian! I see this is closed, but it sounds like we still don't know what caused the error Bev is experiencing. Does this need to go back to to-do until Staging is updated with the new SSOi redirect URI?
