### ISSUE TITLE
BUG: Stored function does not return correct values

### ISSUE THREAD

**Issue by maham360** [department-of-veterans-affairs/notification-api#692]
**Describe the bug**
#649 
VA Profile stored function returns table with one row displaying boolean value. The function correctly works to INSERT/UPDATE the table where VA Profile source_datetime is greater than what's in the database.

**To Reproduce**
1. Copy SQL query to ci_db_1 container then run `ci_db_1` container
2. Run `psql -U postgres -d notification_api` to access psql command line, then run \i <filename> to run SQL query
3. Run `select va_profile_opt_in_out(0,0,0,true,'2022-04-27T16:57:16Z'`or any combination of integer, boolean, datetime to update the table
4. Run `select va_profile_opt_in_out(0,0,0,true,'2022-04-27T16:57:17Z' or any combination of integer, boolean, as long as datetime is later than before.
5. Step 3 will return "true" and step 4 will return "false" for the "allowed" column.

**Expected behavior**
We expect the stored function to return the correct values which are the status codes used for the lamba function.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/692?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by maham360** [comment]
fixed bug to return correct values, submitted PR, approved
