### ISSUE TITLE
Bug: ICN unit test failure

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#693]
**Describe what's happening:**
The unit test that sends an email by ICN is failing. We are receiving an invalid status response from the endpoint.

**Additional info:** 
This seems to have been working before last week. 

- [ ] Determine what's needed to resolve this. This user flow failing could potentially cause production impacts if not resolved. 

If coordination with another team is needed and you're not sure who to talk to please discuss with Jacob or Jesse. We can reach out to Charley Stran who is a technical expert at Oddball for guidance if needed.

**Comment by jessecanderson** [comment]
I have a ticket open with the identity group to see if we can troubleshoot this more. Right now, this is effecting dev and staging environments for emails sent by ICN.

**Comment by k-macmillan** [comment]
Been working with @jessecanderson  on this. Hope to have a resolution by end of day. We have identified the core problem is related to certificates.
