### ISSUE TITLE
Grant eBenefits Users Staging Access

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#696]
**Environment:** Staging
**Request:** Please assign the following users access to the eBenefits service:

- [x] Melissa Rebstock - melissa.rebstock@va.gov
- [x] Fitsum Solomon - fitsum.solomon@va.gov
- [x] Laurie Baker - laurie.baker@va.gov

---
- [x] Let Melanie know when complete

**Comment by mjones-oddball** [comment]
Laurie signed in successfully, Fitsum and Melissa need to get access to the VA org and log in still. @bevnobev or @zlaw if Fitsum and Melissa respond while I'm out next week here is the ticket to grant access.

**Comment by ianperera** [comment]
@mjones-oddball, completed

**Comment by mjones-oddball** [comment]
validated access via postman
