### ISSUE TITLE
Grant VA Insurance Users Staging Access

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#697]
Environment: Staging
Please assign the following users access to the VA Insurance service:

- [x] Donna Wagner - donna.wagner@va.gov
- [x] Sandeep Bagga - sandeep.bagga@va.gov
- [x] Franklin Ramirez - franklin.ramirez@va.gov
- [x] Dusca Fichtel - dusca.fichtel@va.gov
---
- [x] Alert Melanie when this is done

**Comment by mjones-oddball** [comment]
Currently awaiting login from all their users.

**Comment by ianperera** [comment]
@mjones-oddball - completed

**Comment by mjones-oddball** [comment]
Validated access via postman
