### ISSUE TITLE
Analysis and Content - Receipt Confirmation Email 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#70]
- [x] Analyze existing content from va.gov and the physical letter sent 
- [x] Initiate the VSP Collaboration Cycle 
~~- [ ] Finalize Receipt Confirmation Email Template - Content, Design, Accessibility (and address any  recommendations)~~ Separating out design and content to separate cards, see #81 & #82

**Comment by toddstanich** [comment]
#81 and #82 created to track content and design independently.
