### ISSUE TITLE
Send SMS via VEText's Twilio Account

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#714]
As part of the VEText Use Case Transition to VA Notify we will need an interim step of sending messages to Twilio if specified. See [Multiple Provider Configuration](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/Multiple-Provider.md) for more information on how providers as set.

- [ ] Update the notification template settings to use Twilio
- [ ] Confirm we can send SMS through VA Notify using Twilio

Out of Scope:

- Configuring:
    - inbound messages from Twilio
    - STOP messages
    - Message statuses

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/714?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by zlaw** [comment]
- additional ticket to get Twilio account info into AWS

**Comment by mjones-oddball** [comment]
@jakehova You mentioned using the dev account/number and setting up the webhook. Can you add some of those details to this ticket?

**Comment by jakehova** [comment]
- [ ] add twilio account info to aws parameter store as secure string 
- [ ] confirm service id for twilio exists 
- [ ] confirm twilio provider is up to date and available to run
**testing: **
- [ ] change Twilio LomaLinda dev number webbhook to point to reverse proxy notify endpoint
- [ ] setup notify Twilio configuration to use Twilio LomaLinda number for send
- [ ] create test template that is tied to Twilio service id
- [ ] send message through notify using that test template id
- [ ] verify that reverse proxy endpoint received webhook call to confirm message was sent to twilio and rever se prox y
