### ISSUE TITLE
Onsite Notification Flag Update API

### ISSUE THREAD

**Issue by zlaw** [department-of-veterans-affairs/notification-api#715]
When setting the onsite flag value through the update template method, it returns the onsite flag value as though it changed, but does not stick.

-  [ ] Ensure templates are retained via changes to update API.

**Comment by zlaw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/715?planning-poker) with ZenHub @ianperera @jakehova @jessecanderson @k-macmillan @mjones-oddball

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/715?planning-poker) with ZenHub @Jake-Uhteg

**Comment by jessecanderson** [comment]
Inside `app/template/rest.py` there is a method called `_template_has_not_changed`  online 294 which checks for specific values to see if the template has been updated. 

```python
def _template_has_not_changed(current_data, updated_template):
    return all(
        current_data[key] == updated_template[key]
        for key in (
            'name', 'content', 'subject', 'archived', 'process_type', 'postage', 'provider_id',
            'communication_item_id', 'reply_to_email'
        )
    )
```

Adding the notification flag to this method will flag it as a changed template and save it accordingly.

**Comment by EvanParish** [comment]
Added "onsite_notification" to the function indicated above and the template now seems to be properly updating the "onsite_notification" value. 
Branch name: bugfix/715
