### ISSUE TITLE
VA Profile Sync - remove old opt-outs Infra

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#719]
Update Terraform files to complete the Delete Cron Job task
- [ ] Create Lambda function with hello world code
- [x] Create cloud watch Event that runs on CRON  timer that executes every day at 11pm
- [x] Use the Cloudwatch event as a trigger for the lambda

@mjones-oddball - here is the infra ticket.  tagging you for awareness

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/719?planning-poker) with ZenHub @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled @maham360 @EvanParish

**Comment by EvanParish** [comment]
Worked with Dave to get the infrastructure in place to put the lambda up in AWS. It currently will not be triggered. When @jakehova gets back I'll need to ask him how to go about triggering this lambda with the cron job so the opt-outs are removed with the new lambda function.

**Comment by EvanParish** [comment]
After doing some research I used terraform to create a cloudwatch event rule and target, as well as a lambda permission, to allow the rule to execute the lambda that was previously deployed. I talked to Jacob and we decided to go ahead and try to deploy to Dev, where it's now running into a problem, saying `Parameter ScheduleExpression is not valid.`

**Comment by EvanParish** [comment]
Jacob pointed out the issue was just the cron being malformed. It has been successfully deployed to the Dev environment

**Comment by EvanParish** [comment]
It looks like the trigger for the new lambda worked, but the lambda was timing out. We are still looking into the issue.

**Comment by EvanParish** [comment]
It seems that the AWS Security Group was missing ingress and egress rules allowing it to use the proper ports for running the lambda. A potential fix has been added. I will test and make sure the lambda runs.

**Comment by EvanParish** [comment]
After going through some testing steps today and having some trouble getting the lambda to trigger properly, it looks like it's still timing out. Hoping to have it fixed soon, so we can proceed.

**Comment by EvanParish** [comment]
After working with the team this issue is still not completely resolved. Kyle mentioned, "This is going to prevent us from fully deploying to prod because the lambda deployment fails. While it technically can go live with a failure, we should be green across the board." 

@mjones-oddball I wanted to make sure you see this comment. 

I'm hoping to have it resolved by noon today (8/3), but I'm not sure if it'll happen. If we go ahead and merge it in, the lambda is currently just timing out, so we would just need to add another follow-up ticket to get that issue taken care of.
