### ISSUE TITLE
Staging: Update VBA Edu Custom Reply-to in UAT services

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#725]
**Environment:** Staging
**Request:** Please set the custom reply-to email address to: vbaatgdonotreply@va.gov

VBA Education - UAT002 Email templates:

- [x] Email33 Enrollment Verification Opt In Confirmation : `636f391c-a1c4-4aa6-88bb-f432b27405d6`
- [x] Email33 Enrollment Verification Monthly Attendance Verify: `fef79fe4-676f-45f0-b2a5-a9b23473db57`
- [x] Email33 Enrollment Verification Monthly Attendance Verification Follow Up: `205177e3-b4fc-41a9-848a-19941951271f`

 
VBA Education - UAT001 Email templates:

- [x] Email33 Enrollment Verification Opt In Confirmation : `04c2502e-9e33-4afa-9146-a5e89a5a4089`
- [x] Email33 Enrollment Verification Monthly Attendance Verify: `630881a0-edc8-4556-a0cd-63bc52b8b64d`
- [x] Email33 Enrollment Verification Monthly Attendance Verification Follow Up: `66d30dfd-cf3e-4241-9868-833695b321f7`   

---
- [x] Let Melanie know when this is complete

**Comment by ianperera** [comment]
@mjones-oddball - Completed
