### ISSUE TITLE
VA Profile Sync: Implement JWT Auth for POST endpoint

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#728]
## Overview

Discussion with VAPRO led to an agreement to use asymmetric JWT.

This task is to modify the VAPRO lambda to utilize JWT validation. VAPRO will encode with their private key, we will decode with their public. A separate ticket will be made to handle the PUT.

## Checklist

- [ ] Public cert put in AWS - [Terraform ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/vanotify-infra/384)
- [ ] Lambda layer added for PyJWT or equivalent
- [x] JWT decode/validation setup
- [x] Updated tests for JWT authentication

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/728?planning-poker) with ZenHub @ianperera

**Comment by kalbfled** [comment]
Invoking the lambda from the AWS Lambda console works.  I have the public pem certification used for unit testing in SSM as placeholder data, but we still need a production public certificate from the Profile team.

Unit tests pass for the POST functionality with JWTs.  The PUT functionality will be unit tested as part of #704 and perhaps also as part of this ticket.  I need to modify the lambda code to use the correct certificates for mTLS.
