### ISSUE TITLE
Workflow for lambda deployment does not properly package Python dependencies

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#736]
Trying to test the va-profile-opt-in-out lambda in the AWS Lambda console results in an error that the psycopg2 module cannot be imported.  This is because the lambda-functions.yaml workflow does not correctly package the dependencies.  I will fix this and also:

- Remove the two-way-sms lambda requirements file, which is also not properly packaged but is unused anyways.
- Include a step for the remove-old-opt-outs lambda, which should have been part of #681.

**Comment by kalbfled** [comment]
@k-macmillan @mjones-oddball This needs to happen during the current sprint because it blocks testing the VA Profile integration.  It is "in progress."

**Comment by kalbfled** [comment]
@jakehova I cannot deploy with Maham's new lambda until the associated infrastructure exists.  I have that commented out now.
#719

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/736?planning-poker) with ZenHub @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @maham360

**Comment by kalbfled** [comment]
I successfully deployed lambda functions from branch bugfix/736 (associated with this ticket) after working to @EvanParish deploy a partial implementation of Maham's lambda function.  See Evan's comment on #719.
