### ISSUE TITLE
Onboarding Request: BVA Users - Dev, Staging, & Prod

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#742]
The BVA & Caseflow teams will be testing in our Dev environment first. We've already partially onboarded them in Staging and Production. Please complete the following onboarding steps in the various environments and let @mjones-oddball know when finished.

**User Details**
- Jeremy Shields, jeremy.shields@va.gov
- Lowell Lewis, lowell.lewis@va.gov

### Dev Environment Requests
- [x] Create service named "BVA"
- [x] Create an Api Key in that service and send it to the users listed above via an encrypted va.gov email
- [x] Add the Users to the BVA service

### Staging Environment Request
- [x] Add the BVA service to Lowell
- [x] Remove the BVA service from Kevin Ross, kevin.ross2@va.gov who is no longer on the team

### Production Environment Request
- [x] Add the BVA service to Lowell
- [x] Remove the BVA service from Kevin Ross, kevin.ross2@va.gov who is no longer on the team

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/742?planning-poker) with ZenHub @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @maham360 @jakehova

**Comment by mjones-oddball** [comment]
Posting an update here: Maham noticed that BVA was already in Dev with an api key. The created user is Elissa so I'm guessing that was for testing. Maham will reach out to Elissa and make sure we can safely use that service with the business line and create a new api key to share with BVA users.

**Comment by mjones-oddball** [comment]
@maham360 Can you post an update prior to closing please?

**Comment by maham360** [comment]
Created new service "BVA" in dev (Kyle deactivated the old BVA service), added both users to the BVA service in the Dev environment, added Lowell to BVA in staging and prod, removed Kevin Ross from BVA in staging and prod, emailed the API key to both users Lowell and Jeremy, and created & uploaded email template on github here:

https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/API_Key_Email_Template.md
