### ISSUE TITLE
Update DNS for Perf Public Endpoints

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#743]
Currently you can only access the perf API internally. We need to update DNS so it's externally available also.

- [ ] API is externally available for Perf
- [ ] Document relevant steps in case we need it for the future
- [ ] Pull Jake in to get set up in Postman so he can validate/utilize this in the future for QA

**Comment by mjones-oddball** [comment]
@jessecanderson Think you said you were working on this, if so please assign yourself! @Jake-Uhteg FYI you'll have some work as part of this

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/743?planning-poker) with ZenHub @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @maham360 @jakehova

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/743?planning-poker) with ZenHub @Jake-Uhteg

**Comment by jessecanderson** [comment]
I've created a SNOW ticket to address the DNS issue listed here, and I also have an invitation to the network teams office hours on Thursday (July 14) to discuss the DNS entries and requirements around them.

**Comment by mjones-oddball** [comment]
@jessecanderson Can you post an update here when you get a chance?

**Comment by jessecanderson** [comment]
The original SNOW ticket was closed as that group did not handle DNS, so I opened a ticket with a second group that was suppose to handle DNS entries and found out they only handle internal DNS requests. They referred me to the [ESECC](​pdf iconhttps://dvagov.sharepoint.com/sites/OITSE/Enterprise Security Change Control Board/Forms/AllItems.aspx?id=%2Fsites%2FOITSE%2FEnterprise+Security+Change+Control+Board%2FESECC+Documents%2FESECC+Training%2FESECC+Process+Overview+Training.pdf&parent=%2Fsites%2FOITSE%2FEnterprise+Security+Change+Control+Board%2FESECC+Documents%2FESECC+Training&OR=Teams-HL&CT=1646743564564&params=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMjAyMDcwMTgxMCJ9) process which has us open a VIPER ticket to request external access. This needs to then go through the ESECC council for approval as referenced in the powerpoint included. 

I need to get with @k-macmillan and @Eallan919 to see how best to take this forward as the ESECC process is a little confusing to me and the VIPER workflow has you opening tickets in different areas based on requirements.

**Comment by mjones-oddball** [comment]
@jessecanderson I think this one has been in the ether for a while. Would you be able to sync up with Charley for some advice on the best way to get these DNS requests handled? Maybe he has some tricks we could try to get those tickets in. Open to other suggestions! CC @k-macmillan

**Comment by jessecanderson** [comment]
I pretty much handed this over to @k-macmillan to finish tracking down. I can reach out to Charley and ask if I need to though. He was the one who gave me the first SNOW ticket to open which then lead me to the second SNOW ticket in another system/group which then lead to this VIPER ticket and the ESECC process to get a new external DNS entry.

**Comment by jessecanderson** [comment]
Ok, the PR was approved and merged in. Jeremy Britt was nice enough to go ahead and deploy it since it was to `sandbox` and I validated that it works. 

External access to perf is now through `https://sandbox-api.va.gov` and can be added to Postman.

**Comment by jessecanderson** [comment]
This one had been sitting for a while and I ran through a bunch of hoops to get to where I was so I updated the weight of this ticket to a 5 at least. Just with all the research that was done and opening/closing of tickets in all these other systems it maybe higher. 

But, it is working now. :D
