### ISSUE TITLE
VEText Migration: Test sending SMS with VEText's Twilio Account

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#744]
Now that we're set up with the Twilio Provider in Dev we need to test to understand any intricacies in using Twilio as a provider.

- [ ] Establish a phone number for testing:
- [ ] Set up a test template and assign the Twilio Provider
- [ ] Configure the test phone number as an sms sender
- [ ] Send an SMS request through
- [ ] Document this process

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/744?planning-poker) with ZenHub @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @maham360 @jakehova

**Comment by k-macmillan** [comment]
Blocked due to the Twilio provider logic (internal).
Blocked due to need for Message Service and phone numbers from VEText so we can setup the `sms_senders`.

**Comment by mjones-oddball** [comment]
This was already validated in another ticket where we updated the code.
