### ISSUE TITLE
VBA Edu: Update Whitelist

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#745]
## Issue
Since the new Portal launched, VBA edu is unable to get the token via the UI to update their own whitelist. They have additional users to add.

## Checklist
- [ ] ~~Update the Staging whitelist for the services Won Choi specifies~~
- [x] Update the Staging whitelist for the service `ff6ab40d-a3b9-4327-b90d-690a13e2a904 -main service for Govdelivery`
- [x] Document the process in our support folder in Github

## Users
- [x] remya.l.amma@accenturefederal.com
- [x] walker.d.adams@accenturefederal.com
- [x] shaheed.mahmud@accenturefederal.com
- [x] rohan.pasreeja@accenturefederal.com
- [x] keerthi.somaraju@accenturefederal.com
- [x] md.al.mamun@accenturefederal.com
- [x] sultana.tarafder@accenturefederal.com
- [x] s.tadakara@accenturefederal.com
- [x] ravi.a.jha@accenturefederal.com
- [x] kotesh.kommanaboyina@accenturefederal.com

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/745?planning-poker) with ZenHub @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @maham360 @jakehova

**Comment by mjones-oddball** [comment]
I escalated this concern with Nathan, Megan, Kyle, and Ian - we have been unable to generate the JWT needed to complete the whitelist update through the API. Kyle and Nathan synced to look into updating the database directly as a short term workaround.

**Comment by ianperera** [comment]
after investigating this, the whitelist endpoints require JWT from UI, which is no longer in service. as I had indicated to @k-macmillan, these two endpoints need to be re-written to utilize the existing Pre-request Script.  I'm in the process of understanding the logic behind the endpoints to make the changes so we can move away from UI JWT Token

**Comment by ianperera** [comment]
@mjones-oddball, @k-macmillan there are a couple of endpoints that utilize the JWT token from the old UI, and all are not working. We may need to create a separate ticket to fix this.

**Comment by k-macmillan** [comment]
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/5e34f380-adea-4974-9984-c2ea0f738148)

Documentation:
https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/whitelist_additions.md

**Comment by ianperera** [comment]
@mjones-oddball @k-macmillan , I found the solution. I'll write up a how-to
![Screen Shot 2022-07-28 at 9.41.53 PM.png](https://images.zenhubusercontent.com/62033095e969da059f934439/4e9aa7e5-84eb-4ce5-9f5b-218ec14f6566)

**Comment by ianperera** [comment]
https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/whitelist_additions.md
