### ISSUE TITLE
VEText Migration - PostgreSQL DB update to support message service id

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#746]
In order to utilize the Twilio Messaging Service as VEText is doing today, we will need to support creating Twilio notification requests with a sender phone number OR message service id. We currently capture the sender phone number via the field sms_sender.

- [x] Add a new column to capture a provider service id (try to keep this generic as it may be useful for other providers besides Twilio)
- [x] Update models.py
- [ ] Unit tests

**Comment by EvanParish** [comment]
Added the new column `sms_sender_service_id` to the `service_sms_senders` table as you can see in the picture below. This was taken during local testing.

![image](https://user-images.githubusercontent.com/104009494/180299247-e180d972-f22f-450f-844c-53e15995ea43.png)

**Comment by EvanParish** [comment]
Changed the column name to `ssm_sender_specifics` and added a comment to reduce confusion about what the value should be.
