### ISSUE TITLE
Onsite Notifications - Prod key for VA.gov

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#752]
- [x] Create key pair and share public key with Tom Harrison (he can be found in DSVA slack)
- [ ] Confirm connectivity and validate our env variable for the production URL
We should be able to test the connection via postman with invalid ids. If Tom is aware of test users we can do a more realistic test, but I wouldn't count on it.

## Reference
Previous ticket for Staging - https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/vanotify-team/237

> After discussing with Kyle and Tom Harrison, we decided to include the iat and exp fields in the JWT so that it's not a static token.
> 
> I generated a new public/private key pair that will work with ES256 and provided Tom with the public key. He will whitelist it and do the work on his end to read the new format of the JWT.

**Comment by mjones-oddball** [comment]
@EvanParish I was going to ask that you take this one since you know what to do. If you wanted to get started on it early, feel free.

**Comment by EvanParish** [comment]
@mjones-oddball I can take this one. I believe the key pair has already been generated and can be found in our parameter store. I'll double check though. So we should just have to pass the key along to Tom and do testing once he says it's complete on his end.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/752?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @maham360

**Comment by EvanParish** [comment]
The key pair is in our AWS parameter store and the public key has been passed to Tom. We will need to wait to hear back from him before testing the connection.

**Comment by EvanParish** [comment]
After passing the key off to Tom, he said the ticket would be a high priority for his sprint that started Jul 27. He is hoping to be done by Aug 1.

**Comment by EvanParish** [comment]
Tom reported the work has been completed on his end. I tested the connection in Production with the results below. It looks like it connected, but the response is reporting `template-id - is not included in the list` so I may need to double check to make sure we know what template id is expected. 

```
--- Sent in Prod Environment ---
[2022-08-01 14:10:36,470: INFO/ForkPoolWorker-4] Sending this data with POST request to onsite_notifications: {'onsite_notification': {'template_id': '7efc2b8b-e59a-4571-a2ff-0fd70253e973', 'va_profile_id': 'abcd_test'}}
```

```
--- Response when sending Onsite in Prod ---
[2022-08-01 14:10:36,756: INFO/ForkPoolWorker-4] onsite_notifications POST response: status_code=422, json={'errors': [{'title': 'Template is not included in the list', 'detail': 'template-id - is not included in the list', 'code': '100', 'source': {'pointer': 'data/attributes/template-id'}, 'status': '422'}]} 
```

**Comment by EvanParish** [comment]
I asked Tom about the issue, and found out he had the Staging email template id in Production. I provided the Production email template id and he said he'd get it in, and it should be active after their next deployment. (8/3 2-3pm)

**Comment by mjones-oddball** [comment]
@EvanParish Great catch! Thanks for sticking with this and validating.

**Comment by EvanParish** [comment]
The Onsite connection was still giving me the `template-id - is not included in the list` error. I reached out to Tom and he's taking another look at the configuration in the Prod environment.

**Comment by EvanParish** [comment]
The template has been updated in Production on Tom's side of things. I have completed a successful connection test in Production!
