### ISSUE TITLE
Access Request for VEText

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#754]
Ari Hicks will be managing templates for VEText. To support this we need the following:

User: Ari Hicks, username: ahicksfearless 

- [x] Create a service called VEText in Dev if one doesn't already exist 
- [x] Assign Ari the VEText service in:
    - [x] Dev
    - [x] Staging
    - [x] Prod

**Comment by EvanParish** [comment]
@mjones-oddball I have created a service called `VEText` in the Dev environment, and added Ari Hicks to `VEText` services in Dev, Staging, and Prod.

**Comment by mjones-oddball** [comment]
@EvanParish Thanks! Ari confirmed everything looks good.
