### ISSUE TITLE
Deploy Onsite Notifications to Production

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#757]
In preparation for go-live we need to push the latest onsite notification code to Production. The new template field for onsite notifications should NOT be enabled yet on the debt notification. That configuration will be handled when VA.gov tells me they are rolling out their feature flag.

- [ ] Schedule/communicate with the team in a va-notifications-va-gov-program thread
    - [ ] We will need to understand what repos will be pushed and what other work will be released as part of the deployment
- [ ] Deploy feature to production
- [ ] Regression testing (where possible)

**Comment by k-macmillan** [comment]
@jessecanderson  is taking lead on this. The deploy is happening tomorrow at 8pm. @EvanParish will be assisting. 
Deployment will be Infra -> API -> Lambda

There's one [issue](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/719) holding back the deploy but it should be put in PR status today.

**Comment by mjones-oddball** [comment]
@jessecanderson @EvanParish Here's the ticket for the onsite deployment you both are on tonight

**Comment by Jake-Uhteg** [comment]
SSUi smoke test documented at https://dsvavsp.testrail.io/index.php?/runs/view/3474&group_by=cases:section_id&group_order=asc
