### ISSUE TITLE
remove unnecessary os_environ fixture from test code

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#759]
## User Story - Business Need

tests/conftest.py provides the os_environ fixture to mock environment variables in test code.  This fixture is only used in a couple of tests, and it is redundant to the [monkeypatch](https://docs.pytest.org/en/7.1.x/how-to/monkeypatch.html) feature Pytest provides.  It could be removed with minor changes to existing tests.

### User Story(ies)
**As a** developer
**I want** to eliminate unnecessary code, including redundant fixtures,
**So that** the code base is easier to maintain.

### Additional Info and Resources

```
.../notification-api$ grep -r os_environ tests/
tests/app/test_cloudfoundry_config.py:@pytest.mark.usefixtures('os_environ', 'cloudfoundry_environ')
tests/app/test_cloudfoundry_config.py:@pytest.mark.usefixtures('os_environ', 'cloudfoundry_environ')
tests/conftest.py:def os_environ():
```

## Engineering Checklist

- [ ] All instances of tests/conftest.py::os_environ have been replaced with a monkeypatch

## Acceptance Criteria

- [ ] Unit tests continue to patch

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/759?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled
