### ISSUE TITLE
Add configuration for VANotify in Vets API Staging environment 

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#76]
- [x] Create "va.gov" organisation in staging
  - Done: `5d456f6c-d474-42dc-b6f8-43153b0bf636`
- [x] Create "vets-api" service in staging
  - Kind of, using existing service because `email_from` has to be unique (until #123) is played. Id: `ebda987e-78e2-4987-b33b-47ab94a51bf6`
- [x] Template
  - [x] Create "form526 submission" template in staging
    - Done: `12676880-db0d-4f47-9fb0-8a543ab980d9`
  - [x] ~Update department-of-veterans-affairs/devops#7192 to include new template ID~ - make a PR to update the template ID
    - Done: department-of-veterans-affairs/devops#7380
- [x] API key
  - [x] Create secret key in staging
  - [x] Make a new API key based on the structure defined [here](https://docs.notifications.service.gov.uk/rest-api.html#authorisation-header)
  - [x] Coordinate with Ops to update value of `vets_api.staging.vanotify_api_key` in Credstash
    - Done, also had to update staging settings to indicate version of secret: department-of-veterans-affairs/devops#7381
> That secret key forms a part of your API key, which follows the format {key_name}-{iss-uuid}-{secret-key-uuid}.
>
>For example, if your API key is my_test_key-26785a09-ab16-4eb0-8407-a37497a57506-3d844edf-8d35-48ac-975b-e847b4f122b0:
>
>- your API key name is my_test_key
>- your iss (your service id) is 26785a09-ab16-4eb0-8407-a37497a57506
>- your secret key is 3d844edf-8d35-48ac-975b-e847b4f122b0
- [x] URL
   - [x] Update `vanotify` fwdproxy to set `host` and `services_addresses.primary` to URL of notification-api in staging (see [this file](https://github.com/department-of-veterans-affairs/devops/commit/d06ba206a5ca48c69d1b4f78c7cfd3910db9952c#diff-45061ff0376bab06d8fe0cc92ef8335c))
     - Done: department-of-veterans-affairs/devops#7380
   - [x] Kindly ask Ops people to redeploy fwdproxy
- [ ] Mark service live

# Important note
Making the configuration changes described above will almost certainly break Form526 submission on vets-api in Staging, since the URL/API key/Template ID won't be in sync.
If we're desperate to avoid this, we should disable the `form526_confirmation_email` toggle before making configuration changes, and enable it afterwards.

Assumption: 
We have a VA Staging Environment up and running. Store our PI key and Secret Key Name in Vets-Apis config Template ID and URL. Will include config for the Development. TW AWS Environment 

Notes: 
- Toggles for Feature is out of scope for this story
- We'll also need operations people to configure the fwdproxy.

**Comment by QaysarA** [comment]
- [ ] Configure service 
- [ ] Configure template 
- [ ] Configure API key  
- [ ] Mark service live

**Comment by philherbert** [comment]
This is a PR for doing this in dev/review - we should raise a very similar PR for staging. https://github.com/department-of-veterans-affairs/devops/pull/7145

We'll also need operations people to configure the fwdproxy.

**Comment by marisahoenig** [comment]
Submitting the pull request to set this up for staging, except for now, the API key for staging in vets-api will point to dev of notification-api, until our staging environment is configured. This is to allow us to test sending an email for #45 in staging without needing a review instance (dev uses mocked responses, which caused errors when we tried to submit an application and the claimId already existed).

**Comment by philherbert** [comment]
Just submitted Form 526 with user 227 on Staging, and we received the call in our Staging environment, meaning that the configuration works.

<img width="1467" alt="Screen Shot 2020-08-11 at 09 48 09" src="https://user-images.githubusercontent.com/9078954/89905249-eecafd00-dbb7-11ea-8a5b-e8d165fa8136.png">
