### ISSUE TITLE
Create monitor for VA Profile integration

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#766]
Development for #704 codified that POST requests from VA Profile are expected to contain a JSON body with a "bios" attribute that is a list with a single element.  The implementation logs a warning if "bios" contains multiple elements and only processes the first element.

Create a monitor to alert us if these warnings occur.  This could be in CloudWatch, etc.  No particular solution is prescribed.

Note: We think this is an edge case, but without a monitor won't know how frequently it happens.

**Comment by kalbfled** [comment]
@k-macmillan @mjones-oddball

**Comment by mjones-oddball** [comment]
@k-macmillan Should we be managing all monitors and alerts through DataDog if possible?

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/766?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled
