### ISSUE TITLE
Spike: VA Profile integration sync

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#767]
## Goal

The implementation of VA Profile integration has occurred in stages, and the requirements have shifted since the beginning.  This ticket is a prompt for the stakeholders to synchronize.

**Comment by kalbfled** [comment]
@k-macmillan @mjones-oddball

**Comment by mjones-oddball** [comment]
@kalbfled Can you provide more detail about the desired outcome of this ticket?

**Comment by kalbfled** [comment]
I think we're good here.
