### ISSUE TITLE
Daily limit warning not sufficient and incorrect format

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#768]
## Value Statement
Every message sent in staging triggers the warning because it was hard-coded to trigger when they had less than 100 notifications left. The daily limit warning should trigger when a service has come within some percent of the daily limit.

Format of the content is incorrect. Without type casting it sometimes makes the value binary, sometimes int. Type cast so it is always an integer in the log.

Recommendation: Warn when over 75%.

## Checklist

- [ ] Code changed to a percent of the limit
- [ ] Logger message updated to reflect percent
- [ ] Binary representation of the number removed
- [ ] Follow on ticket made to set up an alert

## Additional Info/Resources

- [Code](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/notifications/validators.py#L52)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/c85dc9f8-42a3-42f2-a43b-5232fcdafc57)

Type casting issue:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/25742c0c-9671-400e-a0de-83cd45b77d4a)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/768?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled
