### ISSUE TITLE
CARMA (1010CG) Onboarding to VA.gov Service in Staging and Prod

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#769]
- [x] Please assign the VA.gov service to the following people in Staging and Prod. Staging is the priority to begin testing.
- [x] Create an API key in Staging under the VA.gov service with "1010CG-Carma" in the API key name for visibility purposes and send it via encrypted va.gov email to Milagros.Ridoutt@va.gov
- [x] Coordinate with Carma team via email/slack as needed (we're working on getting them DSVA access to our public channel
    - [x] They are hoping to schedule a technical meeting next week (8/1 week). Please send the questions & answers back tomorrow, 7/29, which may reduce the need/length of the meeting. You can work that out with them.

*Ramesh is on vacation so he may not have logged in yet, skip him if you can't find him. If you can find him please note it so we're aware there's none remaining.

|Names|GITHUB User Names|Staging|Prod
|-|-|-|-|
|Caitlin Reyna|starofaragon2010|x|x|
|Ramesh Dugar|rdugarSFDC|||
|Ruman Khan|rumankhanSFDC|x|x|
|Bhagat Bisht|bbishtSFDC|x|x|
|Raj Ramamoorthy|raj-ramamoorthySFDC|x|x|
|Waleed Jaffar|wjaffarSFDC|x|x|
|Hugh Richardson|HRichardsonSFDC|x|x|
|Mili Ridoutt|mridouttSFDC|x|x|

**Comment by mjones-oddball** [comment]
@EvanParish @k-macmillan @zlaw new onboarding ticket. Kyle let me know Evan volunteered to help with this one. Thank you! Kyle will loop you into the email thread tomorrow so you can reply with answers to their technical questions. This ticket will get them what they need to begin their work next week. They're hoping to do a basic test through postman next week.

**Comment by k-macmillan** [comment]
Sent Evan the details of what and who to email.

**Comment by EvanParish** [comment]
I contacted the CARMA team via email and included the answers to their questions. 
The users that were in the Staging and Prod environments have been added and the table in the description has been updated to reflect that. 
An API key for staging has been generated and sent to Milagros.Ridoutt@va.gov via encrypted government email.

**Comment by EvanParish** [comment]
A meeting has been scheduled for 8/2 to do a basic connection test through Postman.

**Comment by EvanParish** [comment]
The "Hello World" test was successful with CARMA using Postman to connect to staging and send an email. 
Questions: 
- They were concerned about load testing.
What environment would they be able to use for load testing since Staging has a 100 messages per day limit? (Prod?)
  - the limit is per service, right? Not per user.

**Comment by mjones-oddball** [comment]
@EvanParish Why are they trying to load test our API?

**Comment by EvanParish** [comment]
@mjones-oddball I'm not sure. I can reach out and get more details on their plans and why they might want to do load testing.

**Comment by EvanParish** [comment]
I have reached out to the CARMA team, and asked for more details about their planned load testing. David Wald got back to me and provided these additional details on their reasoning behind the load testing they would like to perform. 

> We plan to do load test with 18000 applications in a day so this may trigger 18000 emails. We think if email fails it doesn’t really matter since the actual load test is for Mule API.
> 
> This volume was chosen to simulate the numbers we may expect to see in Production once we go live.

**Comment by mjones-oddball** [comment]
@EvanParish That limit is for the entire service and CARMA is on va.gov, so they could impact others. I would like Kyle to be involved in the discussion next week when he's back. You can let your contact know we need to discuss with our tech lead next week and ask if this is a scheduled test that will happen once or twice vs something that will recur.

My thoughts for when we discuss:

- Is this test is a one-off thing or a repeat occurrence? I'm trying to gauge if this is something we can coordinate together on a single day (if it's ok for all those emails to go out). 
- What recipients are they going to use for the 18000 requests? We have to be cautious not to hurt our email reputation and spam rates. 
- Can they load test their API without hitting us 18000 times? Or if they do hit us can they mock it out so the request to us fails? 
- Can we have them use a test API key and whitelist for this so that the emails don't actually go out to others?

CC @k-macmillan

**Comment by EvanParish** [comment]
Asked David Wald from CARMA about how many times they would want to do load testing and let him know we need to discuss it with our tech lead. This is his reply.

> It will be a one time test event that we are tentatively planning to schedule on 9/23 following the CARMA Release to Prod on 9/22.
> 
> Yes, sounds good. We can discuss further next week and will not move forward until we have consensus among the teams.

**Comment by mjones-oddball** [comment]
Reached out to ask when Ramesh would be back in the office so we could wrap up this ticket.

**Comment by EvanParish** [comment]
@mjones-oddball It looks like `Ramesh Dugar` is still not in the system. Should this ticket be closed and open a new one for when he is in the system?

**Comment by mjones-oddball** [comment]
@EvanParish Good call. I'll make a new ticket.
