### ISSUE TITLE
Add configuration for VA Notify in Vets API Production environment

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#77]
# Acceptance Criteria
**GIVEN** I login to Vets-API DEV
**WHEN** I successfully submit form 526ez
**THEN** I receive the expected email
**AND** email is sent from VANotify dev in VAEC

**GIVEN** I login to Vets-API staging
**WHEN** I successfully submit form 526ez
**THEN** I receive the expected email
**AND** email is sent from VANotify staging in VAEC

**GIVEN** I use Postman pointing to VaNotify prod
**WHEN** I send email notification with template id and API key
**THEN** I receive the expected email
**AND** email is sent from VANotify prod in VAEC

**Comment by QaysarA** [comment]
- [ ] Configure service 
- [ ] Configure template 
- [ ] Configure API key  
- [ ] Mark service live

**Comment by saman-moshafi-va** [comment]
Here are the names for organization, user, service, template and api key:
### dev
organization: va.gov
user: VA Service User
service: main service for Govdelivery
template: Form 526ez template
api key: vagovapikey

### staging
organization: va.gov
user: VA Service User
service: main service for Govdelivery
template: Form 526ez template
api key: vagovapikey
### prod
organization: va.gov
user: Test User
service: main service for Govdelivery
template: Form 526ez template
api key: vagovapikey
