### ISSUE TITLE
AWS Dev Test Instance Intermittent Connection

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#771]
## Issue
Connection to the [dev-test-instance](https://console.amazonaws-us-gov.com/ec2/home?region=us-gov-west-1#Instances:v=3) is intermittent at best (fails more often than not for me). Connecting to the instance allows us to ensure the expected changes are happening in RDS (databases) in Dev before moving to staging.

## Checklist

- [ ] Connection happens every time with multiple users, no issues

## Additional Info/Resources

The [commands](https://console.amazonaws-us-gov.com/systems-manager/run-command/complete-commands?region=us-gov-west-1) are failing to execute. It may be wise to start over duplicate a working one (staging).

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/771?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled

**Comment by jessecanderson** [comment]
I created a new EC2 instanced called `dev-bastion-host` and validated it can connect to the dev DB instance. @k-macmillan also validated he can access the console through the AWS portal and connect to the dev DB as well. 

We will leave the older `dev-test-instance` in there until we are sure nothing will accidentally remove this new one.
