### ISSUE TITLE
VA Profile integration: Update SSM parameter path for getting the VA root certificate

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#772]
vanotify-infra issue 401 will consolidate SSM parameters for our various deployment environments into a single parameter.  After that change, update the SSM path value in lambda_functions/va_profile/va_profile_opt_in_out_lambda.py.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/772?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled

**Comment by mjones-oddball** [comment]
Cancelling, moved content into a different ticket

**Comment by mjones-oddball** [comment]
@kalbfled Should this be added into the sprint now that the linked infra ticket is done? 
@zlaw can you update the ticket depending on Dave's answer please?

CC @k-macmillan

**Comment by kalbfled** [comment]
Superseded by other changes.
