### ISSUE TITLE
BUG: VA Profile Sync - Infra - Fix lambda timeout issue. 

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#777]
Check #719 for the original ticket. This is a follow-up to that effort.

When the trigger was added to execute the remove old opt outs lambda, it would time out whenever the lambda code tried to run. The issue may be tied to security group or other permissions not being set correctly.

**Comment by zlaw** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/777?planning-poker) with ZenHub @ianperera @jakehova @jessecanderson @k-macmillan @mjones-oddball

**Comment by k-macmillan** [comment]
Verified all settings were in-line with equivalent lambdas. Dug through a bunch of suggestions and followed an AWS blog about timeouts when trying to connect to RDS. Opened up rules on the RDS security group for the lambda's security group, no dice. Modified the roles to have another policy and tinkered with the settings, no help. Created an AWS support ticket.

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/777?planning-poker) with ZenHub @EvanParish

**Comment by k-macmillan** [comment]
Issue ended up being infra-related. The port was not correct. It is possible that the port is incorrect for the other VA profile lambda. Used this task to add logging and ensure the connection gets closed. There is a [PR](https://github.com/department-of-veterans-affairs/notification-api/pull/792) up.

**Comment by k-macmillan** [comment]
Merged. Tested `master` in Dev. 

![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/1f85644f-d44b-48f1-a993-3b3ce2e749a3)
