### ISSUE TITLE
SPIKE Monitoring strategy for Confirmation email in vets-api

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#78]
# Goal
Figure out what we want to measure/monitor/alert and how to use the available tool to achieve that for the confirmation email in vets-api.

# Checklist
- [x] Consult with the vets-api team to understand what could be used for Monitoring —> refer to notes from meeting with Keifer
- [x] Discuss and document strategy and approach within our team
- [x] Possibly review Prometheus, Grafana, Sentry, statsd
- [x] Alerts - should we be alerted, when and where
- [x] Errors from notification-api are logged in Sentry
- [x] Get stats to be picked up in Grafana (or be added to dashboard(s))
- [x] Document how to write insights queries in CloudWatch

# Timebox
3 days

# Assumptions
* Implementation of the monitoring will be done in a different card (#74)
* Datadog will most likely be used for notification-api. However, this card is to understand the existing monitoring strategy of vets-api and how it fits into our work.

**Comment by ffafara-tw** [comment]
Some useful resources:
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/grafana-overview.pdf
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-configuration.md
- https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-tagging-standards.md

**Comment by ffafara-tw** [comment]
Some information provided by John Paul:
- right now, there’s no automatic alerting in sentry outside of the slack channel which is effectively a firehose
- the sentry10 rollout, which continues to be imminent, among other things, should allow us to notify teams about their errors (based on tags for example) through slack
- the current monitoring solution remains prometheus/grafana
- pagerduty is managed by OI&T with a pretty hard limit on users. I think we might be able to temporarily get you a few folks in during launch, but the links between the various tools require OIT admins and occasionally dsva admins which can make it complicated. As a rule we haven’t been incorporating pagerduty outside of support but i don’t have a strong objection.
- most of the prom/grafana is for internal tracking (eg SLOs). @Keifer [VSP/BE Tools] is likely the best person on be-tools to talk to and he’s on vacation this week
but the soon solution is going to be app perf monitoring with DataDog, and I believe ops is still planning to move to DataDog over prometheus as part of new infrastructure.
- you should be able to get to grafana. @kam on the VAOS team shared a custom dashboard as they get ready to launch just yesteday http://grafana.vfs.va.gov/d/EmC4pa6Wz/vaos-alerts?orgId=1&from=now-3d&to=now

**Comment by ffafara-tw** [comment]
Session with @Keifer scheduled for Wednesday 7/15/2020 at 2:30 PM EDT

**Comment by ffafara-tw** [comment]
Let's make sure that VA Notify is part of External Services - SLO Report:
http://grafana.vfs.va.gov/d/pEgVdRlZk/external-service-performance-indicators?orgId=1

**Comment by marisahoenig** [comment]
Notes: https://docs.google.com/document/d/1K-VdJbGFBbTBsv8J9X2exhV2lMPJz3QwR4MynsgnK5I/edit#

Recommendations:

Grafana
1. Add Form526ConfirmationEmailJob to Job Queue Dashboard - Asked Keifer
2. Investigate vanotify data showing N/A on External Service Performance Indicators Dashboard -> Asked Keifer
3. Make dashboard for vanotify: Calls to govdelivery (later: other services), Calls from vets-api, Errors/failures, availability of service. - Requires sending a request in the #vfs-platform-support channel and they will create the dashboard for us

Sentry
1. Create a new sentry team ([instructions here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/engineering/sentry-configuration.md#creating-a-new-team)) - can specify a path/url that we want to “own” if an error happens
2. Future - once sentry10 is available on vets-api, set up alerting to our slack channel
