### ISSUE TITLE
BUG: Deployment Alert Missing in Slack

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#787]
## User Story
As a VA Notify team member
I want to see an alert in Slack when deployments are complete
So that I can get an accurate feed of automated updates

## Problem
On 8/8 Jacob deployed the API using the new deployment process. This never updated our slack channel when complete.

## Request

- [ ] Restore Slack integration in API

## Additional Info

Jesse and Kyle think they tracked down the slack integration: https://github.com/department-of-veterans-affairs/notification-api/settings/hooks/203980541?tab=deliveries
Connects to: https://vajira.max.gov/

Typically in [va-notify-automatic-alerts](https://dsva.slack.com/archives/G015QSLR4BU) we see a slack message when a deployment fails or completes successfully.

![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/ed385ebe-af67-4f1a-b86d-d95798661d22)

The last time I saw this working for the api repo was 8/3 https://dsva.slack.com/archives/G015QSLR4BU/p1659572763060919

**Comment by mjones-oddball** [comment]
@jessecanderson Not sure if this broke with the new deployment process or because of something else. Just want to make you aware of the issue and the ticket I opened given the work you're doing.

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/787?planning-poker) with ZenHub @EvanParish

**Comment by jessecanderson** [comment]
There is a branch `deployment_update_status` that should actually fix this. Just haven't tested/validated it yet.

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/787?planning-poker) with Zenhub @kalbfled
