### ISSUE TITLE
Spike: Investigate gunicorn workers

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#789]
## Goal

gunicorn workers [critically abort](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logsV2:log-groups/log-group/dev-notification-api-log-group/log-events$3Fstart$3D1660078921000$26filterPattern$3D). Find out what they do, why they're breaking, and brief the team so we can determine if further work is needed (probably replace gunicorn) or if this is debt that needs cleaned up.

This was spotted in prod, affects all envs.

Output doesn't really tell us what's wrong. May be beneficial to branch, change the logging, and then push to dev while looking into the workers further.

## Checklist

- [ ] Purpose of workers documented
- [ ] Reason for aborts documented
- [ ] Team briefed
- [ ] Additional ticket made (to fix or clean)

## Timebox

Timeboxed at 1 day.

# Additional Info/Resources

- Code for [worker_abort()](https://github.com/department-of-veterans-affairs/notification-api/blob/master/gunicorn_config.py#L16).

Example failure:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/c1c0b4a3-b8b6-4ae2-a36c-7aaa6992c52a)

Not so useful worker output.
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/36f5fb81-ca16-44da-9a95-0684ca990a13)

# Out of Scope

- Fixing the critical failures

**Comment by mjones-oddball** [comment]
@k-macmillan Any insight on the urgency of this?

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/789?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled

**Comment by mjones-oddball** [comment]
@k-macmillan Is there an update on this?

**Comment by cris-oddball** [comment]
Whatever was happening here is no longer happening in Prod or any env. Closing.
