### ISSUE TITLE
Resolve VETEXT_SID issue

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#790]
## Value Statement

Every time a push notification is sent we check if the task definition has set the mobile app registry sids (`VETEXT_SID` and `VA_FLAGSHIP_APP_SID`). Add the VeText prod appSid to our task definitions and optimize out the work with [MobileAppRegistry](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/mobile_app/mobile_app_registry.py#L7) and [MobileApp](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/mobile_app/mobile_app.py#L5).

## Acceptance Criteria
1) Add the task definition for `VETEXT_SID` in prod
2) Clean up `MobileAppRegistry`, it should not need to be initialized

## Checklist

- [ ] Acquire a prod appSid from VETEXT
- [ ] Add prod appSid to task definition
- [ ] Remove excessive environment calls
- [ ] Remove unnecessary instantiation
- [ ] Update tests

## Additional Info/Resources

- Init of `MobileAppRegistry` probably doesn't need to be instanced.
- [Push notification area to clean up](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/v2/notifications/rest_push.py#L32).

Should have a default return instead of logic within the push notification to get the default:
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/dee0024d-cfe7-4612-9079-ec3863f52ae1)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/790?planning-poker) with ZenHub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled

**Comment by cris-oddball** [comment]
@kalbfled FYI - let's be sure to not do this in ENP for Push.

**Comment by npmartin-oddball** [comment]
@cris-oddball Can you revise/spin up a new ticket? Thank you!
