### ISSUE TITLE
Grant User Access to VBA Services in Staging

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#791]
Charles is a new engineer working with the VBA edu team. They need him to be a backup for Umer. Please provision his service access in Staging.

Environment: Staging

- [ ] Please grant CHARLES LANDERGOTT the same service access as Umer Hashimi

```
            "services": [
                "ff6ab40d-a3b9-4327-b90d-690a13e2a904",
                "da5fbe25-468c-4226-b26d-7bcaf72f642d",
                "f87f7493-ceb8-43de-a838-0b36ac29b7b9",
                "a3330dc2-7f40-417e-97b2-9550ca379166",
                "113bba63-90c4-419b-a77a-60aa18b55ad5",
                "a190be7f-2dcb-48ee-9b68-54d8b3924e45",
                "09ae062e-773c-4531-9067-eff0b129e8a7",
                "254cacf7-515a-4fe4-916c-5cb4a571172b"
            ],
```

**Comment by Jake-Uhteg** [comment]
Requested services added in staging ![Screen Shot 2022-08-10 at 10.13.38 AM.png](https://images.zenhubusercontent.com/6243636a4b4b2542fb866b9a/a900ecaa-bea9-40f9-9e58-e8811db1d6a5)

**Comment by mjones-oddball** [comment]
@Jake-Uhteg Thank you! I let the customer know. :)
