### ISSUE TITLE
Correct Canada URLs

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#805]
## Value Statement

When Canada forked from the UK they updated the `templates` and `templates_history` `content` and `name` fields with Canada-specifics. We should replace the Canada changes since we forked from them.

## Checklist

- [x] Migration or equivalent created to update things
- [x] Updates as expected in lower environments with no side effects

## Additional Info/Resources
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/f631b3e8-4330-4045-bd1d-5c0b8213b17e)
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/52a297e0-d74e-437f-8a51-a22821fadf59)

**Comment by mjones-oddball** [comment]
@bevnobev Kyle mentioned you brought up the issue of these URLs recently, but for the life of me I can't remember the context. Do you recall where these URLs were presenting themselves in SSUI or elsewhere to users?

**Comment by bevnobev** [comment]
@mjones-oddball There are a couple of templates under the "VA Notify" service that have references to Canada.  Let me see if I can find those

**Comment by mjones-oddball** [comment]
@bevnobev That's good enough thank you I can look :)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/805?planning-poker) with Zenhub @EvanParish @jakehova @ianperera @k-macmillan

**Comment by MackHalliday** [comment]
# before upgrade

<img width="1432" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODh4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b5b301a9f13e3c656e84e58c927b059e0412e9e/Screenshot%202024-10-08%20at%205.08.50%E2%80%AFPM.png" alt="Screenshot 2024-10-08 at 5.08.50 PM.png" />

**Comment by MackHalliday** [comment]
Created PR - https://github.com/department-of-veterans-affairs/notification-api/pull/2039
Already tested in DEV, waiting for reviews.

**Comment by MackHalliday** [comment]
PR is blocked. 

Waiting on response from @mjones-oddball or @kbelikova-oddball 

https://oddball.slack.com/archives/C034496E4AU/p1728484826161349

**Comment by MackHalliday** [comment]
Will be removing URL completely.
