### ISSUE TITLE
VA Profile integration: Update lambda to read SSM Parameter Store for Profile's JWT signing certificate

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#808]
This ticket supersedes [vanotify-team 544](https://github.com/department-of-veterans-affairs/vanotify-team/issues/544).

The Terraform code in va_profile.tf is supposed to read VA Profile's public JWT signing certificate from S3 and make the certificate available to the VA Profile integration lambda as an environment variable. That wasn't working, so instead we decided to [make the certificate available via SSM Parameter Store](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/406).

The lambda function now needs to be modified to get the certificate in that manner.

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/808?planning-poker) with Zenhub @EvanParish

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/808?planning-poker) with Zenhub @kalbfled
