### ISSUE TITLE
Content for Confirmation Email for Disability Form

### ISSUE THREAD

**Issue by toddstanich** [department-of-veterans-affairs/notification-api#81]
Create content for email sent on submission of 526EZ form on va.gov

**Comment by peggygannon** [comment]
Hi, @toddstanich here is the content ticket I created for this work: 

https://app.zenhub.com/workspaces/vsp-5cedc9cce6e3335dc5a49fc4/issues/department-of-veterans-affairs/va.gov-team/10328
