### ISSUE TITLE
Update VeText Incoming Forwarder Lambda to resolve 502 errors

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#812]
Right now we are getting stalled connections to VeText that result in our lambda running for a longer time than it needs to.  But explicitly setting the VeText connection to timeout at 6 seconds, we can ensure that the lambda doesn't run for longer than it needs to.  When the connection times out, it will be placed on the failed queue and retried at a later time.  

- [x] set explicit timeout for connection to VeText to 6 seconds
- [x] update code to return 200 when we have received the message and have successfully enqueued it or processed it

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/812?planning-poker) with Zenhub @EvanParish @ianperera @jakehova @jessecanderson @k-macmillan @kalbfled

**Comment by k-macmillan** [comment]
This worked happened over two PRs. We investigated the timeout further after the expected fix failed and specified a connection timeout of 3.05 seconds and a byte-read timeout of 1 second. VeText responses are on the order of a few hundred milliseconds so this restrictive timeout should not cause issues. Failures will push the message to SQS for a retry and a 200 is returned to Twilio.
