### ISSUE TITLE
VEText Forwarder Lambda Unit Test and Twilio Response Fix

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#822]
During the deployment on 9/1, messages were going into the deadletter queue unexpectedly.

>All failures are going to go to the dead letter queue right now in prod. We're getting an exception because
`return response.content if response.ok else None`
If the response failed to generate we're referencing a variable not set.

 Kyle applied a fix and redeployed, however, he had to comment out some code due to the urgency.

Failures that go to the deadletter queue currently send a 200 response (success) to Twilio, which means those messages won't be caught and sent by the backup (pusher). Deadletter queue messages aren't retried because they are meant to be issues that will never succeed without manual intervention. We should still send an error code to Twilio so there's no interruption of service.

- [x] Resolve the issue that was causing unit tests to fail (in the commented out section)
- [x] Update the response returned to Twilio to 5xx in the case of exceptions that are sent to the deadletter queue

**Comment by ianperera** [comment]
Working on the unit test issue.

**Comment by ianperera** [comment]
[PR #845](https://github.com/department-of-veterans-affairs/notification-api/pull/845) created

**Comment by ianperera** [comment]
[PR #845](https://github.com/department-of-veterans-affairs/notification-api/pull/845) approved and merged to dev
