### ISSUE TITLE
VEText - Error Monitoring and ALB Testing

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#824]
After discovering errors within the VEText integrations (Twilio message forwarder, push notifications, etc.) we determined that many of these errors were due to VEText taking too long to process requests. Out of that, we agreed to try a new ALB in our AWS account which will balance requests across VEText's infrastructure to see if we can easily increase performance and decrease timeouts. If this doesn't work, VEText would have to do significant work to their infrastructure to attempt to fix the issue.

https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/vanotify-infra/408

- [x] Work with VEText to use the new ALB to balance forwarder and push notification requests to VEText
- [x] Monitor the errors specific to VEText daily
- [x] Add a short support document to github

**Comment by k-macmillan** [comment]
The target group IP addresses were pointing to different IP addresses than what Rob was expecting. We tested this last week and saw good results, though not enough testing to identify if this would resolve the 09:40 to 11:30 UTC issues.

Shane would like us to move `push` notifications to that ALB to see if it fixes the 502s. That's just a configuration change but requires redeployment.

**Comment by mjones-oddball** [comment]
@k-macmillan before closing this can you please right a short doc to put in the support folder about how this works, the new URLs used, and where they are controlled (parameter store and...)

**Comment by mjones-oddball** [comment]
Jacob's support doc: https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/VeText_ALB%20to%20AWS%20ALB%20fix.md
