### ISSUE TITLE
VA Insurance 2 Way SNS Infrastructure Changes

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#833]
- [x] Create Terraform to generate SNS topic
- [x] Create access policy for SNS topic to SQS queue
- [x] Attach SNS Topic to campaign phone numbers: 
  - [x] Staging: +12183220243
  - [x] Production: +18148852937 
- [x] Staging: Add +12183220243 as an SMS sender and inbound number configuration to the VA Insurance Service via VA Notify API
- [x] Production: Add +18148852937 as an SMS sender and inbound number configuration to the VA Insurance Service via VA Notify API
- [x] Validate 2 way setup in staging

**Comment by jakehova** [comment]
Access Policy Template: 
```
 {
      "Sid": "TEST-VANotify-10DLC-TwoWay",
      "Effect": "Allow",
      "Action": "sns:Subscribe",
      "Principal": {
        "AWS": "arn:aws-us-gov:iam::<Their SQS Account Number>:root"
      },
      "Resource": "arn:aws-us-gov:sns:us-gov-west-1:171875617347:TEST-10DLC-TwoWay"
    }
```

**Comment by jakehova** [comment]
Terraform is completed.  

For now, instead of the SQS arn that they create, I'm giving their AWS account permission to subscribe to events off the topic.  

Update the "vainsurance_account_root_arn" in the corresponding environment tfvars file to generate the SNS topic and respective access policy for their AWS accounts access.

Once we confirm that things are working as expected, we can limit this to just the SQS ARN for the respective environment's queue.  

The development.tfvars is currently giving access to my personal gov cloud AWS account.

**Comment by mjones-oddball** [comment]
@k-macmillan from the client:
LIPAS Account ID:               049181275565

LIPAS Account Alias:           vaec-lipas

Q’s:

Prod SQS-Q:          arn:aws-us-gov:sqs:us-gov-west-1:049181275565:project-lipas-prod-vanotify-sqs.fifo
Prod SQS-DLQ:     arn:aws-us-gov:sqs:us-gov-west-1:049181275565:project-lipas-prod-vanotify-DLQ.fifo
PPD SQS-Q:           arn:aws-us-gov:sqs:us-gov-west-1:049181275565:project-lipas-ppd-vanotify-sqs.fifo
PPD SQS-DLQ:      arn:aws-us-gov:sqs:us-gov-west-1:049181275565:project-lipas-ppd-vanotify-sqs-DLQ.fifo
QP’s:

Current AP for initial testing:
{

    "Version": "2008-10-17",

    "Id": "__{SQS_Q}",

    "Statement": [

        {

            "Sid": "{SQS_Q}_Access_Policy_Anonymous",

            "Effect": "Allow",

            "Principal": "*",

            "Action": "SQS:*",

            "Resource": "{SQS-Q-ARN}"

        }

    ]

}

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/833?planning-poker) with Zenhub @trevor2718 @EvanParish @k-macmillan @ianperera @jessecanderson @cris-oddball @kalbfled

**Comment by jakehova** [comment]
Updated VA Insurance queue ARNs: 

PPD SQS-Q (standard):          arn:aws-us-gov:sqs:us-gov-west-1:049181275565:project-lipas-ppd-vanotify-sqs
PPD SQS-DLQ (standard):     arn:aws-us-gov:sqs:us-gov-west-1:049181275565:project-lipas-ppd-vanotify-sqs-dlq

**Comment by mjones-oddball** [comment]
Production work covered in https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/vanotify-infra/447
