### ISSUE TITLE
Certificates Expiring 9/26

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#838]
We got a warning that these certs will be expiring soon. They are labelled as SSOi related in Venafi (which Nathan has access to). 

- [x] Confirm whether these certs are used
- [x] If they are used, coordinate with Nathan to renew them and update where applicable

![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/c3c78949-decb-4e27-a51e-c217f352edfa)

![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/0aaa9af7-a456-48a2-bb22-351166dbf1c2)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/838?planning-poker) with Zenhub @trevor2718 @EvanParish @k-macmillan @ianperera @jessecanderson @cris-oddball @kalbfled

**Comment by zlaw** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/838?planning-poker) with Zenhub @nathanbwright

**Comment by nathanbwright** [comment]
I think that we should retire the lower env cert (and remove it from the AWS param store) and verify that SSOi still works correctly - just to be doubly sure about this.

**Comment by nathanbwright** [comment]
I removed `/dev/notification-api/cert/vanotify-ssoi-cert` and `/dev/notification-api/cert/vanotify-ssoi-key` from AWS param store and then deployed `notification-api`, `infra`, and `notification-portal` (all in dev) and everything deployed successfully and SSOi still works as it should.

I believe this confirms that these certs are not needed.

**Comment by nathanbwright** [comment]
After talking with @k-macmillan we decided to remove the certs in AWS for `perf` and `staging` now and wait until Tuesday (9/27) to remove `prod`'s cert.

**Comment by nathanbwright** [comment]
Tested SSOi login in prod today and then removed the expired prod cert and retested SSOi login and everything is still working correctly. I removed the (now expired) cert for prod from AWS param store.

**Comment by zlaw** [comment]
Thanks, Nathan!
