### ISSUE TITLE
Create tickets for FIXME and TODO comments in the code

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#840]
There are "FIXME" and "TODO" messages throughout the code that could use tickets associated with them. This ticket would be to go through the codebase, find all of these messages, and add tickets for them if they don't already have one.

Include in Ticket:

- What is the comment of the fixme/todo
- Relevant file name(s)
- Relevant code snippets
- Add Notify Label

- [ ] Create tickets
- [ ] Once you're done please ping Kyle and Melanie so we can review tickets

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/840?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @trevor2718 @jakehova

**Comment by mjones-oddball** [comment]
If any of the fixme's are so simple that it takes less time to fix than create the ticket I would be ok with that just please note that and push up changes in small bundles so it's easy to review and complete. @k-macmillan agree?

**Comment by mjones-oddball** [comment]
If you use VSCode this is helpful for listing out all the TODOs https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree

**Comment by trevor2718** [comment]
I completed creating tickets for TODO and FIXME on Zenhub: 873, 874, 875, 878 - 901. Feel free to make comments if you guys have any questions.

**Comment by mjones-oddball** [comment]
@k-macmillan I created an epic and assigned these issues to the epic so we could more easily identify them in the future: https://github.com/department-of-veterans-affairs/notification-api/issues/903. You can filter by this in Zenhub.

Can you review and confirm this ticket is ready to be marked as complete?
