### ISSUE TITLE
Missing Notification Status Reasons

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#844]
While reviewing stats in domo and bigquery I noticed there are failure reasons missing. [Here is a sample set of data](https://drive.google.com/file/d/1AkREOBwdA95RFWiqt1aQWcglDBvPEMFC/view?usp=sharing) from August 1 2022 to Sept 26 2022 where the status was permanent or temporary failure, but the reason was null (missing). We should have status reasons for all failures so we can learn and improve.

- [ ] Identify where we're missing status reasons
- [ ] Add applicable reason text (review with Kyle as this is client-facing)

Query I used to pull status data in bigquery. You can update the status_reason where clause to see the failure reasons that do come through.
```
SELECT
  stat.date,
  CONCAT(stat.service_name," - ",stat.template_name) AS notification_template,
  STRING_AGG(status,",") AS statuses,
  STRING_AGG(status_reason,",") AS reasons,
  SUM(stat.count) AS total_successfully_sent
FROM
  `vsp-analytics-and-insights.platform_vanotify.prod-statistics` AS stat
WHERE
  stat.status NOT IN ("sent",
    "delivered")
  AND status_reason IS NULL
  AND stat.date BETWEEN "2022-08-01"
  AND CURRENT_DATE()
GROUP BY
  stat.date,
  notification_template
ORDER BY
  stat.date,
  notification_template;
```

**Comment by mjones-oddball** [comment]
@k-macmillan I was looking at CARMA's launch stats and noticed there were failures but no reasons in domo for these cases. I created a bug ticket to address the lack of status reasons.
cc @zlaw @bevnobev

**Comment by trevor2718** [comment]
I have some questions:
- How can I replicate this issue?
- When I have a suspicion about the code, how can I verify the bug exists there?

**Comment by mjones-oddball** [comment]
@bevnobev FYI this is the issue you brought up in slack to Megan and I RE Carma

**Comment by mjones-oddball** [comment]
Kyle asked what env this was for. Just posting here that ideally it will be in all environments but the data I'm looking at is production. Business lines who have launched can't see some or all of their failure reasons because they are missing.

**Comment by bevnobev** [comment]
Adding that it's not just happening for Carma but also for several other templates under the va.gov service

**Comment by mjones-oddball** [comment]
@trevor2718 When you're back, can you please add progress comments to this ticket? CC @k-macmillan

**Comment by EvanParish** [comment]
Trevor seems to have identified most of the places where the messages should be set. I've been working on testing and making sure they are triggering as intended. There seems to be a lot of checks in place to prevent notifications from getting to where most of theses error messages would be triggered. Once the new messages were put in place there seems to be some unit tests that are failing now. I'm looking into what's happening with those.

**Comment by EvanParish** [comment]
I'm still having problems with a couple unit tests failing for reasons that are not obvious. It also seems the table that can be checked using BigQuery is only updated once per day, so checking for new messages in the database that way is delayed.

**Comment by EvanParish** [comment]
The unit tests are passing when the code is push to a PR. The test failures are only happening in my local environment, and are not related to the code changes in this branch. The code is ready for merging.
