### ISSUE TITLE
Security: Github Scrub Sensitive Data from History

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#849]
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

Recently we had a security breech where Vetext related secrets were stored in code. We need to scrub these from history.

**Whoever takes this ticket, please reach out to Jacob to ask what data we're scrubbing. He will send through keybase**

- [x] API Repo history has been scrubbed
- [x] Document any learnings in case we need to do it again
- [ ] Any ideas for how we can prevent making this mistake in the future?
- [x] Coordinate and schedule all engineers re-cloning the repo

**Comment by jakehova** [comment]
Refer to [this](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) for the recommended process to handle removing secrets from commit history.

This [BFG Repo-Cleaner tool](https://rtyley.github.io/bfg-repo-cleaner/ ) seems to be the recommended way to do this properly.  

@EvanParish talked with the security team yesterday and they said they found our leaks using "DART".  I want to look that up and see if it's a tool or group and find a way to incorporate that into our commit process.

**Comment by jakehova** [comment]
Refer to [this](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository) for the recommended process to handle removing secrets from commit history.

This [BFG Repo-Cleaner tool](https://rtyley.github.io/bfg-repo-cleaner/ ) seems to be the recommended way to do this properly.  

@EvanParish talked with the security team yesterday and they said they found our leaks using "DART".  I want to look that up and see if it's a tool or group and find a way to incorporate that into our commit process.

**Comment by mjones-oddball** [comment]
@kalbfled I was thinking you could take this and ask Jacob if  you need any help. Thoughts?

**Comment by jakehova** [comment]
When you are ready to scrub, I will provide the strings to look for via secure messaging (i.e. KeyBase)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/849?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jessecanderson @k-macmillan @kalbfled @trevor2718 @jakehova

**Comment by EvanParish** [comment]
I created a test repo to try out the BFG Repo-Cleaner tool and it seems to work in a fairly straightforward manner. I then pulled a copy of our repo and tested it with the values provided by Jacob and it seems to have removed them when I check the history. 
A time has been scheduled for everyone to have their code in a good state so we can get the secrets removed and have everyone pull down a new copy of the repo.

**Comment by EvanParish** [comment]
This morning I tried to push the local, cleaned, copy of the repo up to the remote. This resulted in errors you can see below. It seems that elevated permissions are required to use the `git push --force` command on this repo. After speaking with Jacob it seems that we may need to contact GitHub support and have them remove some of our PRs from history as well to make sure all traces of the secrets are gone.

```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Cannot force-push to this protected branch At least 2 approving reviews are required by reviewers with write access.
To https://github.com/department-of-veterans-affairs/notification-api.git
 ! [remote rejected]     master -> master (protected branch hook declined)
 ! [remote rejected]     refs/pull/1/head -> refs/pull/1/head (deny updating a hidden ref)
 ! [remote rejected]     refs/pull/110/head -> refs/pull/110/head (deny updating a hidden ref)
 ! [remote rejected]     refs/pull/129/head -> refs/pull/129/head (deny updating a hidden ref)
 ! [remote rejected]     refs/pull/135/head -> refs/pull/135/head (deny updating a hidden ref)
... a bunch of errors like this ...
 ! [remote rejected]     refs/pull/91/head -> refs/pull/91/head (deny updating a hidden ref)
 ! [remote rejected]     refs/pull/97/head -> refs/pull/97/head (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/department-of-veterans-affairs/notification-api.git'
```

**Comment by EvanParish** [comment]
I confirmed the releases do not contain git history, so they should be safe.

**Comment by EvanParish** [comment]
I created a [glossary doc](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/git_repo_cleanup_instructions.md) explaining how to go about cleaning the git history. 

I also wrote a script to check the contents of the diffs for all of our PRs using the [GitHub CLI](https://cli.github.com/manual/) so I could find any PRs that contain sensitive data.

**Comment by EvanParish** [comment]
Met with Kyle to finish removing secrets from the repo.
