### ISSUE TITLE
Remove psycopg2-binary as a build dependency for VA Profile lambdas

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#855]
## Value Statement

**As** developer
**I want to** standardize lambda creation
**So that** it is easily repeatable and maintainable

We are moving all lambda environments to lambda layers for a consistent process (we have three ways they're made at the moment). The end-goal is that we have zero to five lambda layers per lambda and no virtual environments created. 

This task is specific to removing the Python package psycopg2-binary from the build/deploy packages for the two VA Profile lambdas created with Github Actions because these lambda functions now have access to this common dependency via a lambda layer. See [vanotify-infra 438](https://github.com/department-of-veterans-affairs/vanotify-infra/issues/438).

Future tasks will come depending on the outcome.

## Checklist

- [ ] venv creation removed from the packaging of va_profile_remove_old_opt_outs_lambda
- [ ] Functionality of lambda intact

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/855?planning-poker) with Zenhub @kalbfled @EvanParish @trevor2718 @k-macmillan

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/855?planning-poker) with Zenhub @ianperera

**Comment by kalbfled** [comment]
I cannot test my changes for this ticket until #931 is resolved.

**Comment by kalbfled** [comment]
I changed the title and content of this ticket after discussing it with @k-macmillan.

**Comment by k-macmillan** [comment]
Additionally, instead of `runs-on: ubuntu-latest` we should probably use AWS's lambda environment if we can.
