### ISSUE TITLE
Update API Docs: Push Notification Endpoint

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#859]
/v2/notifications/push

We want to ensure this accurately describes the capabilities and supported fields.

- [ ] Review for accuracy and make necessary updates
- [ ] Ensure that all possible fields are called out
- [ ] Validate required fields are clearly indicated
- [ ] Include additional example bodies to accurately reflect options if applicable

**Comment by trevor2718** [comment]
Need to set up testing app via instructions from Patrick Swanson.

**Comment by npmartin-oddball** [comment]
@cris-oddball can you spin up a new ticket?
