### ISSUE TITLE
Handle notifications errors when sending 526 confirmation email

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#86]
As a vets-api operator 
When system is sending confirmation email via VA Notify
I want the system to handle errors appropriately (log, etc.)
And not retry non-transient errors

Checklist:
_notification-api errors_
- [ ] Handle BadRequestError with Missing personalisation error message. Want to retry the job, but no more than within a day.
- [ ] Handle if necessary / consider TooManyRequestsError
- [ ] Handle if necessary / consider RateLimitError. Want to retry the job, but no more than within a day.
- [ ] Handle if necessary / consider AuthError
- [ ] Handle gateway timeout; retry
- [ ] Handle template does not exists error (sentry)
- [ ] Specify log errors with Sentry helper method `log_exception_to_sentry` (defined in [sentry_logging.rb](https://github.com/department-of-veterans-affairs/vets-api/blob/master/lib/sentry_logging.rb)). 
- Differentiate notification-api errors by both `e.message` and `e.code`. Ruby client raises Notifications::Client::RequestError (or a subclass). See comment below for list of errors want to cover for.
- multiple rescues are allowed

_sidekiq errors_
- [ ] Handle/configure Sidekiq options for failed jobs - `sidekiq_options retry: #,  dead: boolean`. After hitting ceiling, unsuccessful job will be added to Dead Job queue. The default can be set to 0 retry but want to log the error.
- [ ]  Handle dead jobs by adding `sidekiq_retires_exhausted` hook, which will be called before job gets moved to Dead Job queue. Add log entry with Sentry helper method. [Example hook usage in vets-api](https://github.com/department-of-veterans-affairs/vets-api/blob/26b2b569e55e107458d761e9886398565eaacf77/app/workers/evss/disability_compensation_form/submit_form526.rb#L15), though this block can't be tested due to limitations of `Sidekiq::Testing.fake!`. 

- [resource for Sidekiq error handling best practices](https://github.com/mperham/sidekiq/wiki/Error-Handling)
- we need to mock the notification API in DEV to test some of the behaviors

**Comment by lingtran** [comment]
Examples of module SentryLogging#log_exception_to_sentry:
- [https://github.com/department-of-veterans-affairs/vets-api/blob/e62f66d2c1e6c59dc720d977b502821192ea641b/app/controllers/v0/coronavirus_chatbot/tokens_controller.rb#L65)
- [another example in different worker](https://github.com/department-of-veterans-affairs/vets-api/blob/1a5334fa00053c7215f575b42d114f270e2419ee/app/workers/facilities/pssg_download.rb#L41)
 
There is some refactoring happening for this helper method, convo here: https://github.com/department-of-veterans-affairs/vets-api/pull/4375#discussion_r437682292

**Comment by lingtran** [comment]
For Sidekiq config for this worker, how many retries? Do we want the job to be added to the Dead Job queue or let it disappear?

**Comment by lingtran** [comment]
Ruby client error codes for email: 

Error codes
If the request is not successful, the client raises a Notifications::Client::RequestError exception (or a subclass), which contains a code:

- 400 | BadRequestError: Can't send to this recipient using a team-only API key
- 400 | BadRequestError: Can't send to this recipient when service is in trial mode - see https://www.notifications.service.gov.uk/trial-mode
- 400 | BadRequestError: Unsupported file type '(FILE TYPE)'. Supported types are: '(ALLOWED TYPES)'
- 400 | BadRequestError: File did not pass the virus scan
- 400 | BadRequestError: Send files by email has not been set up - add contact details for your service at https://www.notifications.service.gov.uk/services/(SERVICE ID)/service-settings/send-files-by-email
- 403 | AuthError: Error: Your system clock must be accurate to within 30 seconds
- 403 | AuthError: Invalid token: API key not found
- 429 | RateLimitError: Exceeded rate limit for key type TEAM/TEST/LIVE of 3000 requests per 60 seconds
- 429 | TooManyRequestsError: Exceeded send limits (LIMIT NUMBER) for today
- 500 | Exception: Internal server error	ServerError

* more detail regarding error class and how to fix in docs [here](https://docs.notifications.service.gov.uk/ruby.html#ruby-client-documentation)

**Comment by ffafara-tw** [comment]
TooManyRequestsError - see if we can retry after 24h - alert above some threshold
RateLimitError - retry - alert above some threshold
Missing personalisation - do not retry, raise alert (sentry / pagerduty)
template does not exists error - do not retry, raise alert (sentry / pagerduty)
auth error - do not retry, raise alert (sentry / pagerduty)
Exception: Internal server error ServerError - retry - alert above some threshold

400 | BadRequestError: Can't send to this recipient using a team-only API key - do not retry - raise alert
400 | BadRequestError: Can't send to this recipient when service is in trial mode - do not retry - raise alert

**Comment by anushyaprasad** [comment]
This story is in progress but the icon on the story says it's blocked by a spike in dev analysis! Can this please up updated if no longer true?

**Comment by marisahoenig** [comment]
Remaining To Dos:
- [ ] Create PR for vets-api
- [ ] Create PR for mockdata repo
- [ ] Discuss with team...do we want to mock the api in dev (change in devops repo of mocks to true)? If changed, when we're on dev, emails would not be sent, only mocked. If not, we can only use betamocks locally.

**Comment by marisahoenig** [comment]
Update: The issue with EVSS is fixed, but now the submission is not going through (see screenshot) and thus, we aren't receiving the email. Unsure of the issue but looking into it.
![Screen Shot 2020-08-31 at 4 56 27 PM](https://user-images.githubusercontent.com/13212345/91769386-4b18af80-ebad-11ea-9ead-a497a12f3809.png)

**Comment by marisahoenig** [comment]
Awaiting [PR Approval](https://github.com/department-of-veterans-affairs/vets-api/pull/4795)

[Relevant Slack Thread](https://dsva.slack.com/archives/CBU0KDSB1/p1599065974200600)

**Comment by jsmithVA** [comment]
Desk check today
