### ISSUE TITLE
BigQuery Update: New Column for Channel Type

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#867]
As a Business
I want to see my Email and SMS metrics in DOMO
So that I can track applicable progress on my notifications

Problem
Currently, we are unable to distinguish emails from SMS in our DOMO dashboard because our dataset in BigQuery doesn't contain an identifier for channel type. The analytics team told us that we could add a column to the existing dataset without their help.

- [x] Add a new column for channel_type
- [ ] Run an update statement in BigQuery to populate existing data with email or SMS. Currently, we can distinguish this by VEText = sms and everything else (minus VA Notify and vanotify_team services) is email. I think we should give Analytics a heads up before we do this to make sure they don't have any concerns, but they said it should be pretty easy/possible.
- [x] Add the new data column to our nightly file that updates BigQuery so we populate channel type as part of the data set

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/867?planning-poker) with Zenhub @kalbfled @EvanParish @trevor2718 @k-macmillan

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/867?planning-poker) with Zenhub @ianperera

**Comment by EvanParish** [comment]
It seems like I don't have permissions to run a query to update a table using BigQuery. I'm seeing the following message when trying to create a query.


>Access Denied: Project vsp-analytics-and-insights: User does not have bigquery.jobs.create permission in project vsp-analytics-and-insights.  
You seem to be missing permissions on the billing project. The billing project can be changed using the project picker at the top of the page. If the project is correct then please talk to your administrator. You cannot contact your administrator using the "feedback" button.  
Request ID: 5904541545111851592

**Comment by mjones-oddball** [comment]
@EvanParish Please coordinate with Michelle and Chloe in https://dsva.slack.com/archives/C1Q4294JJ (Analytics team). Chloe told us the update would be possible but maybe she meant they would have to run it but it would be easy. Not sure if they need us to submit a ticket or what (she didn't mention that before). She did seem to think we could add the column ourselves though. Loop in Kyle for backup while I'm out! Bev is also a good backup for support, she was there for the conversation with analytics as well.

**Comment by mjones-oddball** [comment]
Evan and I met to discuss this. His permissions are different from mine. Plan is as follows:

- [ ] Code the file change and test the data updates in the lower envs to ensure channel_type is updated as we expect
- [ ] Discuss with Kyle what day next week we can do the push to prod. It will need to be on a day where Evan and I can add the new column in BigQuery and run the update statements so the nightly update doesn't fail and so we don't mess with new data added.
- [ ] Next week Evan and I will add the new column per above and run the update statements. I've already validated I have access.

cc @k-macmillan

**Comment by EvanParish** [comment]
The API code is ready for testing, but it may require a renaming of the `channel_type` column to `template_type`. If that can't be done I may need to change the code to match `channel_type` instead of using `template_type`

**Comment by EvanParish** [comment]
After managing to successfully deploy the api / lambda changes to Dev, when the code ran for 11-03 it looks like the `channel_type` data was coming through, but the header wasn't changed. I think I've found where it needs to be updated, but I'll have to check the data the next time it runs to make sure the header has been updated. 

Example data:
```
date,service id,service name,template id,template name,status,status reason,count
2022-11-03,dev_service_id,VA Notify,dev_template_id,SMS Test,delivered,,1,sms
2022-11-03,dev_service_id,User Flows Test Service,dev_template_id,form 526ez confirmation,permanent-failure,,2,email
```

**Comment by mjones-oddball** [comment]
Cancelled joint meeting for this afternoon as we need more time to work through this ticket. @EvanParish please let me know when you've tested successfully so we can coordinate the deployment/updates. CC @k-macmillan

**Comment by EvanParish** [comment]
After letting the query run overnight, we can see the `channel_type` being populated in BigQuery:

![image](https://user-images.githubusercontent.com/104009494/201723693-3706b37c-18ca-4b86-be4c-b5d88a11d8f1.png)
