### ISSUE TITLE
VA Profile Sync: Plan Seeding Production

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#868]
As VA Notify
I want to populate existing opt-in selections in Production
So that our local cache is accurate

Briefly, the Comp and Pen preference was turned on in Production. About 16,000 selections were made before it was disabled behind a feature flag.

The file will be in the existing BIO JSON format and will be sent via encrypted VA.gov email to Kyle/Dave. See example format in the[ VA Profile Sync Technical Doc](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Integrations/VAProfile/VA%20Profile%20Syncronization.pdf).

- [ ] Determine and document the method of loading the data into our production local cache table
- [ ] Update the work ticket: https://github.com/department-of-veterans-affairs/notification-api/issues/869

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/868?planning-poker) with Zenhub @kalbfled @EvanParish @trevor2718 @k-macmillan

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/868?planning-poker) with Zenhub @ianperera

**Comment by kalbfled** [comment]
Here are a couple of options:
1. [Importing data from Amazon S3 into an Aurora PostgreSQL DB cluster](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/USER_PostgreSQL.S3Import.html)
2. [psql \copy command](https://www.postgresql.org/docs/11/app-psql.html) (search for "\copy")

Either approach probably requires me to write a short script to put the data in CSV format.  The data, as provided by VA Profile, is a JSON export.

**Comment by k-macmillan** [comment]
Just so it's stated here too. The s3 extension is not an option without thorough testing in dev first. We would need to deploy a migration, downgrade, and push Terraform to ensure no issues within the extension being in the DB. We would also have to be able to remove it without issue.

**Comment by kalbfled** [comment]
I used the \copy method.
