### ISSUE TITLE
VA Profile Sync: Seed the Production Local Cache

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#869]
As VA Notify
I want to populate existing opt-in selections in Production
So that our local cache is accurate

Briefly, the Comp and Pen preference was turned on in Production. About 16,000 selections were made before it was disabled behind a feature flag.

The file will be in the existing BIO JSON format and will be sent via encrypted VA.gov email to Kyle/Dave. See example format in the[ VA Profile Sync Technical Doc](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Integrations/VAProfile/VA%20Profile%20Syncronization.pdf).

- [ ] Implement solution and seed database, steps TBD by #868

**Comment by kalbfled** [comment]
I used the \copy method to put the data directly into the production database.  The CSV files I created for this purpose are in the /home/ssm-user directory of the EC2 "prod" access container.
