### ISSUE TITLE
FIXME: POST requests to /v2/notifications/letter

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#873]
[FIXME](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/v2/notifications/post_notifications.py#L67): POST requests to /v2/notifications/letter match this route and the route hooked to the post_notification function below.  
Proper execution seems to depend on the order of the code (top-to-bottom route matching).
``` python
 @v2_notification_blueprint.route('/{}'.format(LETTER_TYPE), methods=['POST'])
def post_precompiled_letter_notification():
    if 'content' not in (request.get_json() or {}):
        return post_notification(LETTER_TYPE)

    form = validate(request.get_json(), post_precompiled_letter_request)

    # Check permission to send letters
    check_service_has_permission(LETTER_TYPE, authenticated_service.permissions)

    check_rate_limiting(authenticated_service, api_user)

    template = get_precompiled_letter_template(authenticated_service.id)

    form['personalisation'] = {
        'address_line_1': form['reference']
    }

    reply_to = get_reply_to_text(LETTER_TYPE, form, template)

    notification = process_letter_notification(
        letter_data=form,
        api_key=api_user,
        template=template,
        reply_to_text=reply_to,
        precompiled=True
    )

    resp = {
        'id': notification.id,
        'reference': notification.client_reference,
        'postage': notification.postage
    }

    return jsonify(resp), 201
 ```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/873?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by zlaw** [comment]
Not utilizing letter functionality at this time.  Will keep at the bottom of the backlog until it's needed.  Lowest of low priority.

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/873?planning-poker) with Zenhub @justaskdavidb2
