### ISSUE TITLE
Remove the code once CYPS updates their template to not cross over the margins

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#874]
Seems to be related to letters pdf tasks

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/letters_pdf_tasks.py#L237): Remove this once CYSP update their template to not cross over the margins
```
if notification.service_id == UUID('fe44178f-3b45-4625-9f85-2264a36dd9ec'):  # CYSP
# Check your state pension submit letters with good addresses and notify tags, 
# so just use their supplied pdf
new_pdf = old_pdf
```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/874?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Related to letters, will defer pointing to a time when this functionality is relevant

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/874?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
Letters is being removed from the code base. @mjones-oddball should we just close this ticket as will not do?
