### ISSUE TITLE
Not supported between instances of NoneType and datetime_datetime

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#878]
- [ ] Add try catch for this

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/scheduled_tasks.py#L109): If no provider changes the below lines throws error:
```
    #   TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'
    if current_provider.updated_at > datetime.utcnow() - timedelta(minutes=10):
        current_app.logger.info("Slow delivery notifications provider switched less than 10 minutes ago.")
        return
```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/878?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by kalbfled** [comment]
The code should first check `if current.provider.updated_at is None:`, and we should have a new unit test for this case.

**Comment by trevor2718** [comment]
@kalbfled `updated_at` property of `provider_details` model can be nullable, `updated_at = db.Column(db.DateTime, nullable=True, onupdate=datetime.datetime.utcnow)`, in which case It can be `null`? Like, when the provider is the first one and never been updated?

**Comment by trevor2718** [comment]
Sorry please scratch that. I could figure it out.

**Comment by kalbfled** [comment]
@mjones-oddball @zlaw Multiple people ended up working on this, and I spent a while getting the database migration to work.  I would re-point as a 3.

**Comment by mjones-oddball** [comment]
Updated from 2 to 3 story pts
