### ISSUE TITLE
Remove Todo Code Comment: Phone Number Formatting

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#879]
## User Story - Business Need

The code base is littered with TODOs that should either be removed or worked as needed. This particular TODO should be removed based on PM decision

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/celery/service_callback_tasks.py#L217): In `send_inbound_sms_to_service` method, payload includes `source_number`. 

```
payload = {
        "id": str(inbound_sms.id),
        # TODO: should we be validating and formatting the phone number here?
        "source_number": inbound_sms.user_number,
        "destination_number": inbound_sms.notify_number,
        "message": inbound_sms.content,
        "date_received": inbound_sms.provider_date.strftime(DATETIME_FORMAT),
        "sms_sender_id": str(sms_sender.id) if sms_sender else None
    }
```

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   VANotify
**I want**   to keep a clean and tidy repo
**So that**   development is straightforward and tech debt is addressed

### Additional Info and Resources

:zap: Decision: We are not going to validate or format the phone number because we want to keep the data as an audit trail. We are going to remove the TODO comment.

Helpful links:
https://developers.omnisend.com/guides/e164-phone-number-formatting
https://www.twilio.com/docs/glossary/what-e164

## Engineering Checklist

- [ ] Remove todo comment from code

## Acceptance Criteria

- The code does not contain this todo comment

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/879?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by kalbfled** [comment]
This might be useful: https://stackoverflow.com/questions/59686863/flask-sqlalchemy-phonenumber-type

**Comment by mjones-oddball** [comment]
We want to keep the database accurate as an audit trail so I don't want to not track a phone number that has sent an inbound message successfully (e.g. if somehow a short code texted us).

**Comment by jakehova** [comment]
We are not going to validate or format the phone number because we want to keep the data as an audit trail.

**Comment by mjones-oddball** [comment]
This is only open to remove the todo from the code

**Comment by cris-oddball** [comment]
TODO still exists in Main, we could keep the ticket to remove the TODO.

**Comment by k-macmillan** [comment]
Inbound sms will be refactored. Closing.
