### ISSUE TITLE
Error when `notification_status` is not `created`

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#882]
[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/delivery/send_to_providers.py#L112): There is no `else` block, when `notification_status` is not `created`, It raises error.
```
    if notification.status == 'created':
        provider = provider_to_use(notification)
```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/882?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/882?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
This code was changed and the TODO comment removed. 
Closing ticket as Done
