### ISSUE TITLE
Change hard-coded `postage` value

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#889]
[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/service/send_notification.py#L161): stop hard-coding postage as 'second' once we get postage from the admin
```python
    notification = persist_notification(
        notification_id=post_data['file_id'],
        template_id=template.id,
        template_version=template.version,
        template_postage=template.postage,
        recipient=post_data['filename'],
        service=service,
        personalisation=personalisation,
        notification_type=LETTER_TYPE,
        api_key_id=None,
        key_type=KEY_TYPE_NORMAL,
        reference=create_one_off_reference(LETTER_TYPE),
        client_reference=post_data['filename'],
        created_by_id=post_data['created_by'],
        billable_units=billable_units,
        postage='second',
    )
```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/889?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/889?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
This code is part of Letters and will be removed once those routes are removed in [1163](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-api/1163). Closing as WND.
