### ISSUE TITLE
Add retries in RequestException

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#895]
[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/va/vetext/client.py#L65): Add retries in RequestException
```python
except requests.RequestException as e:
    self.logger.exception(e)
    self.statsd.incr(f"{self.STATSD_KEY}.error.request_exception")
    raise VETextRetryableException from e
    # TODO: add retries?
else:
    self.statsd.incr(f"{self.STATSD_KEY}.success")
finally:
    elapsed_time = monotonic() - start_time
    self.statsd.timing(f"{self.STATSD_KEY}.request_time", elapsed_time)
```

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/895?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/895?planning-poker) with Zenhub @justaskdavidb2

**Comment by k-macmillan** [comment]
This ticket is no longer applicable. We will be discussing a revamp to how PUSH notifications work within our system.
