### ISSUE TITLE
TODO and FIXME in API Code

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#903]
There were a series of todo and fixme notes buried in the api code. We went through these and translated them into tickets so they wouldn't get lost.

We need to review these, determine their priority, and validate the need.

**Comment by mjones-oddball** [comment]
@k-macmillan is this still needed? The previous todo tickets were deleted. If not, please close. CC @kbelikova-oddball

**Comment by k-macmillan** [comment]
Given the shift towards va-enp-api I do not believe there is a lot of value in this. The team has begun to evaluate unrefined tickets to determined relevance and there are many opportunities to identify TODOs that should be worked.

New repo [isn't going to allow TODO](https://docs.astral.sh/ruff/rules/line-contains-todo/)s through linting (meaning you will not be able to merge code that has a TODO in it). The existing TODOs in notification-api can provide understanding when executing the new design pattern, but we do not need to rack and stack them.

Closing the issue.
