### ISSUE TITLE
VEText Phase 1 Configurations: Templates

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#910]
VEText created 2 additional templates for long codes assigned to Veterans per short code use case. They need multiple templates so they can migrate these use cases at different times.

**Please update these templates with the Twilio provider**

**Environment:** Staging

- [ ] VEText Outreach Long Code Messages: template-id - `a0c02547-e731-4aa6-be02-72bbad6b6878`
- [ ] VEText One-Way Long Code Messages: template-id - `8b0b9e19-f935-4fbb-98c0-89a028091cc0`

**Comment by mjones-oddball** [comment]
@ianperera when you're done please tell @k-macmillan so he can tell VEText

**Comment by ianperera** [comment]
Completed
