### ISSUE TITLE
Spike: Abnormal Redis Usage Investigation

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#916]
## Goal
At 5:15 am Eastern Redis CPU usage shot up to 86% for a brief moment. It was at 2%, then we lost data for a short time, and then it spiked to 86%. Determine what is sending data to Redis and what may have caused this spike. Document findings as a new .md file e.g. redis_usage.md in our team repo.

## Checklist

- [ ] Identified cause of spike
- [ ] Identified if the missing data is normal
  - [ ] If abnormal, document why 
- [ ] Discuss and document with team
- [ ] Create recommendations

## Timebox

2 days

# Additional Info/Resources

- [AWS Redis link](https://console.amazonaws-us-gov.com/elasticache/home?region=us-gov-west-1#/redis/prod-vanotify-redis-rep-group-1)
- Datadog alert that [triggered](https://vanotify.ddog-gov.com/monitors/89231?q=cacheclusterid%3Aprod-vanotify-redis-rep-group-1-002&from_ts=1666774691000&to_ts=1666775891000&eval_ts=1666775891000)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/916?planning-poker) with Zenhub @cris-oddball @EvanParish @jakehova @k-macmillan @kalbfled @trevor2718 @ianperera

**Comment by npmartin-oddball** [comment]
Hasn't been discussed in some time. If this issue surfaces again, a bug ticket will be opened.
