### ISSUE TITLE
Two-Way SMS Infrastructure

### ISSUE THREAD

**Issue by jakehova** [department-of-veterans-affairs/notification-api#922]
Need to create infrastructure to handle two-way SMS generic handling.  

Logic: 
Pinpoint -> SNS -> SQS -> Lambda (DB Retrieval of 10DLC <-> URL, ServiceId, SelfManagedTF) -> HTTP Request

This ticket requires: 
- [x] SNS Topic
- [x] Lambda
- [x] Feeder SQS
- [x] Dead Letter SQS
- [x] DB Model (10DLC Phone number, URL Endpoint, ServiceId, SelfManaged)
- [x] Datadog Monitor for Dead Letter SQS

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/922?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @trevor2718

**Comment by mjones-oddball** [comment]
@jakehova Can you please update this ticket?

**Comment by jakehova** [comment]
infra has been deployed to dev and looks good for staging.  waiting on pr reviews

**Comment by cris-oddball** [comment]
Infra exists on Perf and Staging, lambda is triggered by an event, logs are written to Cloudwatch for lamba actions.
