### ISSUE TITLE
BUG: Github Action "Deploy Lambdas to Dev" does not use the correct branch

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#931]
**Describe the bug**

I attempted to deploy the lambda function va_profile_remove_old_opt_outs_lambda using the [packaging process on branch 855_va_profile_lambda_packaging](https://github.com/department-of-veterans-affairs/notification-api/blob/855_va_profile_lambda_packaging/.github/workflows/lambda-functions.yml#L168).  The Github Action [seems to be checking out the branch](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3371384132/jobs/5593535863#step:2:472), but the Github Action executes [a different packaging process](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/3371384132/jobs/5593535863#step:10:2) (probably from master).

**To Reproduce**

1. Run the Github Action "Deploy Lambdas to Dev" to deploy either "ProfileRemoveOldOptOuts" or "All".  Both have the same outcome.
2. Inspect the Action logs to see what actually runs.
3. In AWS Lambda console, observe that the code has not changed for the lambda.

**Expected behavior**

The lambda should deploy using the recipe from the given branch.

**Comment by ldraney** [comment]
gh cli with the following command solves the issue: 
`gh workflow run -r 855_va_profile_lambda_packaging`
Then, the terminal will give you options.  Select: 
choice: ProfileRemoveOldOptOuts
ref: 855_va_profile_lambda_packaging

It will then run the test.   You can confirm by: 
`gh run list --workflow=deploy_lambda_dev.yml`
