### ISSUE TITLE
Certificate Updates

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#933]
![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/a8f7b0d1-7482-43ca-ae01-71e4f9baf1e7)

We have 3 expiring certs that need to be updated.

- [x] Update Dev certs
- [x] Update Staging certs
- [x] Update Prod certs
- [x] Coordinate with Pavan.Sarangalwar@va.gov and satishkumar.harikrishnan@va.gov so they can update in their system

**Comment by mjones-oddball** [comment]
@k-macmillan can you add some updates to the ticket when you get a chance please?

**Comment by k-macmillan** [comment]
Dev was updated Friday, November 4th. Staging was updated today. Prod will be updated tomorrow around 7pm Eastern. Emailed Pavan and Satishkumar with the dates/times.
