### ISSUE TITLE
Missing Status Reasons - DOMO updates

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#935]
We need to ensure reporting (DOMO) gets updated to properly show error reasons for email and SMS.

- [x] Provide a list of new status reasons that were added in https://github.com/department-of-veterans-affairs/notification-api/issues/844 with the exact text that will be returned
- [x] Review the hard/soft bounce use case for emails to ensure status reasons are being returned (if not add)
- [x] (moved this task to #969) Provide recommendations for query adjustments that can be sent to the Analytics team for the new status reasons

You will be able to see the status reason text by invoking the notification endpoint on an email or sms request that failed due to the applicable status reason.

API doc: https://github.com/department-of-veterans-affairs/notification-api/blob/master/documents/openapi/openapi.yaml

Endpoint: /v2/notifications/{notification_id}

```sql

DECLARE STARTDATE DATE;
DECLARE ENDDATE DATE;
DECLARE SERVICENAME STRING;

SET STARTDATE =  '2022-05-09';
SET ENDDATE = '2022-05-13';
SET SERVICENAME = 'dmc';


select FORMAT_DATE('%A, %b %d', results.date) as Date, results.Requests, results.NotFoundInMPI, results.MarkedAsDeceasedInMPI, results.NoVAProfileIDInMPI, results.NoEmailVaProfile, results.NotFoundInVAProfile,
results.Requests - (results.NotFoundInMPI + results.MarkedAsDeceasedInMPI + results.NoVAProfileIDInMPI + results.NoEmailVaProfile + results.NotFoundInVAProfile) as SuccessfulEmailAddressRetrieval,
CASE WHEN (results.Requests - (results.NotFoundInMPI + results.MarkedAsDeceasedInMPI + results.NoVAProfileIDInMPI + results.NoEmailVaProfile + results.NotFoundInVAProfile)) = 0 THEN "0%" 
ELSE Concat(
    cast(
        round(
        (results.Requests - 
            (results.NotFoundInMPI + results.MarkedAsDeceasedInMPI + results.NoVAProfileIDInMPI + results.NoEmailVaProfile + results.NotFoundInVAProfile)
        ) / results.Requests * 100, 2) 
        as string), 
    '%') 
END as SuccessfulEmailAddressRetrievalRate,
results.Delivered as SuccessfulEmailDelivery,
CASE WHEN (results.Requests - (results.NotFoundInMPI + results.MarkedAsDeceasedInMPI + results.NoVAProfileIDInMPI + results.NoEmailVaProfile + results.NotFoundInVAProfile)) = 0 THEN "0%" 
ELSE Concat(
    cast(
        round(
            results.Delivered / (results.Requests - (results.NotFoundInMPI + results.MarkedAsDeceasedInMPI + results.NoVAProfileIDInMPI + results.NoEmailVaProfile + results.NotFoundInVAProfile)) * 100, 2) 
        as string), 
    '%') 
END as SuccessEmailDeliveryRate
FROM (SELECT 
date, 
SUM(count) as Requests,
SUM(CASE WHEN status_reason = 'Mpi Profile not found for this identifier' THEN count ELSE 0 END) as NotFoundInMPI,
SUM(CASE WHEN status_reason = 'Beneficiary has deceased status in MPI' THEN count ELSE 0 END) as MarkedAsDeceasedInMPI,
SUM(CASE WHEN status_reason = 'Requested identifier not found in MPI correlation database' THEN count ELSE 0 END) as NoVAProfileIDInMPI,
SUM(CASE WHEN status_reason = 'No contact info found from VA Profile' THEN count ELSE 0 END) as NoEmailVaProfile,
SUM(CASE WHEN status_reason = 'Received Forbidden HTTP error (403) while making a request to obtain info from VA Profile' THEN count ELSE 0 END) as NotFoundInVAProfile,
SUM(CASE WHEN status = 'delivered' THEN count ELSE 0 END) as Delivered
FROM `vsp-analytics-and-insights.platform_vanotify.prod-statistics` where service_name=SERVICENAME and (date >= STARTDATE and date <= ENDDATE) 
group by date
order by date) as results;
```

**Comment by EvanParish** [comment]
These are the status reasons added previously. Some of them include the notification_id which might affect the query changes that need to be made.
  - "ERROR: MaxRetriesExceededError - 48 retries attempted but still failed to send"
  - "ERROR: BotoClientError - Error uploading letter to live pdf bucket for notification-id: {notification.id}"
  - "ERROR: BotoClientError - Error when moving letter with notification-id {notification.id} to invalid PDF bucket"
  - "ERROR: InvalidProviderException - could not resolve provider"
  - "ERROR: NonRetryableException - permenant failure, not retrying"
  - "ERROR: InvalidEmailError - Email notification-id {notification_id} failed"
  - "ERROR: InvalidProviderException - Invalid provider for notification-id {notification_id}"

**Comment by mjones-oddball** [comment]
@EvanParish In the new status reason labels, are you saying you included the actual notification id (dynamically populated?

**Comment by EvanParish** [comment]
@mjones-oddball Yes, they include dynamically populated notification id values. I thought it might help us identify issues down the road. Those could be removed to make it easier to aggregate for monitoring though.

The "NonRetryableException" means that something has happened to indicate the message isn't going to be delivered and it's not going to retry sending. It might mean that the intended receiver has opted-out and therefore the message won't be delivered, or something else. I don't know if there's a way to tell exactly what a useful error message would be at that point in the code.

**Comment by mjones-oddball** [comment]
@EvanParish I'm going to set time next week for you, me, and @k-macmillan  to review these, translate, and come up with more generic labels (in a new ticket). The status reasons are something that are visible to clients so I want to make them a little easier to understand whether you're a technical or business role. Apologies that wasn't clearer in the original ticket! At least the hard part of identifying where they are and what they are is done.

For the hard and soft bounces I would expect a status reason like: "Failed to deliver email due to hard bounce"

To your point, these kinds of details should be in the logs - if they aren't and that's something we can improve perhaps we can make additional tickets to help us better troubleshoot.

**Comment by EvanParish** [comment]
The other new status reasons being added in this ticket are below. I've added them to the table in #969 for review.
- "Temporarily failed to deliver email due to soft bounce"
- "Failed to deliver email due to hard bounce"

**Comment by EvanParish** [comment]
I was able to trigger a hard and soft bounce with the help of Cris and Kyle. It looks like the notification status reason is updating appropriately.

[This link](https://docs.aws.amazon.com/ses/latest/dg/send-an-email-from-console.html) is a good resource for testing bounces.

To trigger a hard bounce you can send an email to: `bounce@simulator.amazonses.com`
To trigger a soft bounce you can send an email to: `ooto@simulator.amazonses.com`

Example hard bounce notification status:
```json
{
  "status": "permanent-failure",
  "status_reason": "Failed to deliver email due to hard bounce"
}
```
Example soft bounce notification status:
```json
{
  "status": "delivered", 
  "status_reason": "Temporarily failed to deliver email due to soft bounce"
}
```

**Comment by EvanParish** [comment]
I think the last task on this ticket (query update) would be better handled once the status reasons have been updated on #969. I can go ahead and pick that one up and add this task to it.

**Comment by cris-oddball** [comment]
On Perf, this also works as expected:

sent to  `ooto@simulator.amazonses.com`
received 
```
    "status": "delivered",
    "status_reason": "Temporarily failed to deliver email due to soft bounce",
```

sent to  `bounce@simulator.amazonses.com`
received
```
    "status": "permanent-failure",
    "status_reason": "Failed to deliver email due to hard bounce",
```
