### ISSUE TITLE
Refactor load balancer configuration to use SSL certs (TW AWS)

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#94]
**AC:** 
- [ ] Notifications app load balance should expose https listener

**Assumption:** 
- There is a separate card for work once in the va.gov 

**Notes:**
- We should do this via Terraform
- Generate a certificate
- Use the generated certificate to create a listener within application load balancer

**Comment by ffafara-tw** [comment]
We already have a domain: twnotify.com that has a hosted zone in route53.
In application stack:
- [ ] import route 53 zone using data resource
- [ ] create a route53 record for [env].api.twnotify.com (for prod just api.twnotify.com) with type ALIAS (https://www.terraform.io/docs/providers/aws/r/route53_record.html)
- [ ] create a new certificate for [env].api.twnotify.com in ACM with DNS validation method
- [ ] create a dns CNAME record for validation
- [ ] create ALB https listener using created certificate. Please use TLS-1-2-2017-01 security policy to only support TLS 1.2 and strong ciphers

Most of the steps are outlined here:
https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html
DNS Validation with Route 53 example

**Comment by philherbert** [comment]
Blocked while waiting for @ffafara-tw 's change to be approved, which classifies the `dev.api.twnotify.com` domain in TIC

**Comment by ffafara-tw** [comment]
INC11724032 - http://yourit.va.gov/incident.do?sys_id=370853091b92dc100647a8eae54bcb6c&sysparm_stack=incident_list.do?sysparm_query=active=true

**Comment by QaysarA** [comment]
Filip to add notes and closing this card
