### ISSUE TITLE
Spike: Create Flowchart for Provider Priority

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#942]
## Goal

Provider priority is a bit confusing. Create a flowchart to describe the paths that can be taken when determining priority (both in what Provider to use and what priorities to set).

## Checklist
- [x] Discuss and document with team

## Timebox

1 day

**Comment by EvanParish** [comment]
I have created a flowchart to show how the provider is chosen initially and the conditions for switching the provider. The flowchart starts from the `app/celery/provider_tasks.py::deliver_sms()` function. A simple flowchart of getting to that point was already created [here](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Support/sms_notifications_flowchart.md). 

Attached are the PDF and zipped html files with the flowcharts created to detail the provider selection process. The html file can be used to view / edit the flowcharts on [draw.io](https://app.diagrams.net/).
[provider_selection.drawio.pdf](https://github.com/department-of-veterans-affairs/notification-api/files/9965442/provider_selection.drawio.pdf)
[provider_selection-html_file.zip](https://github.com/department-of-veterans-affairs/notification-api/files/9965451/provider_selection-html_file.zip)

**Comment by mjones-oddball** [comment]
@EvanParish Can you store the PDF in github? If you need to discuss with team before closing you can take 5-10 minutes on refinement today!

**Comment by EvanParish** [comment]
It should probably be converted to a mermaid flowchart at some point, that way it would be consistent with all the md files, but I could put the PDF in the SPIKES folder for now. I could go ahead and share it at refinement today.

**Comment by EvanParish** [comment]
Link to the flowchart in the spikes folder: 
https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/provider_selection_flowchart.drawio.pdf
