### ISSUE TITLE
Update Service with Email Provider Id

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#945]
## User Story

Not all Services that have email permissions have an `email_provider_id`. This is an issue because we are reliant on the template or service to yield the `provider_id`. In the event a template does not have a `provider_id`, the code grabs the service's `email_provider_id`. If the service does not have either it raises `InvalidProviderException`. So it's great that we catch the exception, but it honestly should not happen. 

At present there is one service that does not have `email_provider_id` but does have email permissions: VA Flagship Mobile App. Update that service to utilize the AWS SES provider's ID.

As a VANotify
I want to make sure all services that have email permissions also have an email_provider_id
To ensure consistency throughout the application

## Acceptance Criteria

- [x] VA Flagship Mobile App has an `email_provider_id`
- [ ] When complete, this is added to the slide deck for key wins and as a demo slide.

**Comment by npmartin-oddball** [comment]
Only VA Flagship Mobile App needs to be updated.

**Comment by MackHalliday** [comment]
@EvanParish sat on call with me as we updated the email_provider_id - Confirmed that email_provider_id set to correct value for  VA Flagship Mobile App
