### ISSUE TITLE
Github Actions - set-output deprecation

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#947]
## Value Statement

**As** a DevOps Engineer
**I want to** ensure Github Actions run Smoothly
**So that** the CI/CD pipeline is not broken or hindering developers

## Acceptance Criteria

**GIVEN** we intentionally run an action
**WHEN** the action runs
**THEN** without deprecated warnings or errors

## Checklist

-   [ ] Deprecation warnings for set-output are resolved

## Assumptions

- this is a configuration change

## Additional Info/Resources

- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/947?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @trevor2718 @ldraney

**Comment by ldraney** [comment]
this has already been covered in issue 198.  I verified that all the errors come from third-party repos (e.g. aws actions).  Unlike the recently resolved node16 update, there seems to be no offered remedy for this output clutter at the moment.  Most of the errors are coming from deployment.yml, which is using the aws-actions repo.  IN aws-actions, PR 205 will be solving this deprecation, and as of today is one check away from being merged to master
