### ISSUE TITLE
Lambda Layer Update

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#954]
## Value Statement
Add lambda layers for each lambda. Reuse layers when able (e.g. pscyopg2). Clean up github actions that are creating virtual environments and zipping that up to push to the lambdas. 

There is an associated infra ticket to get the environments into AWS.

## Checklist

- [ ] Layers created that cover all lambdas
- [ ] Actions cleaned up

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/954?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @trevor2718 @ldraney

**Comment by npmartin-oddball** [comment]
We do this now.
