### ISSUE TITLE
catch RuntimeError upstream of _get_delivery_task

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#956]
## User Story - Business Need

Changes for #944 modified the function app/notifications/process_notifications.py::_get_delivery_task to raise RuntimeError.  Ensure this exception is handled upstream from every location that calls the function.

### User Story(ies)

**As a** developer
**I want** raising RuntimeError does not crash the app
**So that** we have maximum reliability and throughput for requests.

### Additional Info and Resources

The expected behavior might vary with the context.  At a minimum, uncaught exceptions should be logged.

## Engineering Checklist

- [ ] Two functions in process_notifications.py call _get_delivery_task.  Ensure the upstream paths from those functions catch RuntimeError.
- [ ] Add new unit tests, if necessary.

## Acceptance Criteria

- [ ] All unit tests continue to pass

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by npmartin-oddball** [comment]
No longer an issue.
