### ISSUE TITLE
_get_template_or_service_provider_id TODOs

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#957]
## User Story - Business Need

The function [_get_template_or_service_provider_id](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/provider_details/provider_service.py#L93) contains 2 TODO statements:

```
# The template provider_id is nullable foreign key (UUID).
# TODO #957 - The field is nullable, but what does SQLAlchemy return?  An empty string?
# Testing for None broke a user flows test.
if notification.template.provider_id:
    logger.debug("Found template provider ID %s", notification.template.provider_id)
    return notification.template.provider_id
```

```
# A template provider_id is not available.  Try using a service provider_id, which might also be None.
if notification.notification_type == NotificationType.EMAIL.value:
    ...
elif notification.notification_type == NotificationType.SMS.value:
    ...

# TODO #957 - What about letters?  That is the 3rd enumerated value in NotificationType
# and Notification.notification_type.
```

### User Story(ies)
**As a** developer,
**I want** to address or eliminate TODOs in the code base
**So that** there are no loose ends.

### Additional Info and Resources

For the, "What about letters?" comment, the answer might be as simple as changing it to a declarative statement.  i.e. "Letters functionality is not in use."  However, that begs the question, "Should we eliminate all references to letters in the code base?" 

Note added 9-12-23: Letters is being removed from the code base under a series of tickets.

## Engineering Checklist
_**Required**_

- [ ] 

## Acceptance Criteria
_**Required**_
- e.g. when I send an email using an identifier, we retrieve the user’s email address in VA Profile and successfully deliver the email to that recipient

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by kalbfled** [comment]
#944 is not yet merged, so linking to the code here doesn't make sense yet.

**Comment by cris-oddball** [comment]
@kalbfled Can you please add something about what is expected to happen on this ticket? Only the TODOs are listed with no sense of the work to be accomplished. Please fill out the Engineering and Acceptance Criteria checklists.

**Comment by npmartin-oddball** [comment]
Not doing this.
