### ISSUE TITLE
BUG: VEText Twilio Forwarder Infinite Loop

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#961]
I was reviewing code with Dave, trying to find a hole in it as to why the 502 errors are happening and we found nothing, but he did identify a potential infinite loop for the vetext forwarder. I shelved it because it was mentioned in passing while we were diving deep into it. After the issues vetext saw this weekend I wanted to ensure we were all shored-up. Turns out we have seen messages in that infinite loop. They then drop off after 4 days due to the retention policy. I have manually turned on the deadletter queue through the console to try and capture these.

[Location](https://github.com/department-of-veterans-affairs/notification-api/blob/master/lambda_functions/vetext_incoming_forwarder_lambda/vetext_incoming_forwarder_lambda.py#L218): Lines 218 through 236. 

![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/98c8db59-1034-42e8-adae-fc67a7b07b82)

Any exceptions will return `None` which pushes it to the retry queue. 

We need to obtain some of the records that are getting stuck so we can narrow down the problem.

**Comment by jakehova** [comment]
I would think that we want this "infinite" loop for all but the general exception?  We could probably put a "raise" in the general exception so that it dumps that request in the dead letter instead of going to the retry.  For the others, I would assume that we want to continually re-submit until VeText is back up.

**Comment by mjones-oddball** [comment]
@cris-oddball @k-macmillan When this is done i just want you all to chat about what the issue and resolution was so we have an  understanding, but don't recommend we spend time on building regression tests and the like because twilio forwarder is a temporary phase 1 solution.

**Comment by jakehova** [comment]
This isnt a bug.  It's meant to repeatedly attempt a send.  

My suggestion was to attach the dead letter queue to the feeder queue so that if anything were to happen (that hasn't happened yet), the message would get dropped to the dead letter queue instead of being dropped from the system.

**Comment by mjones-oddball** [comment]
@k-macmillan Is this ticket still relevant?

**Comment by npmartin-oddball** [comment]
Non-issue.
