### ISSUE TITLE
Remove Unused SMS Provider Code

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/notification-api#962]
## Value Statement

**As** a developer working on the notification-api repo.
**I want to** remove the unused code that has been made obsolete by #944, sms provider selection changes.
**So that** it's not confusing in the future when looking through the code.

- [ ] discuss with QA when understood

## Checklist

-   [ ] Make sure the functions marked with TODOs and this ticket's number are no longer being used.
-   [ ] Remove the unused code, or the comment if the code is still being used.
-   [ ] Remove the unit tests associated with the unused code

## Assumptions

- The code marked with "sms provider swap code" should be investigated and delete if it's no longer being used.

## Additional Info/Resources

- [This flowchart](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/provider_selection_flowchart.drawio.pdf) can be referenced to determine what sections of the code might need to be deleted.
- You can search to code for this ticket's number to find places where TODO comments have been placed.

## Acceptance Criteria

Testing:

-   [ ] All unit tests pass.

GIVEN the provider specified for a template or service is pinpoint
WHEN I send a valid request to `{{notification-api-url}}/v2/notifications/sms`
THEN the message will be sent using pinpoint

GIVEN the provider specified for a template or service is twilio
WHEN I send a valid request to `{{notification-api-url}}/v2/notifications/sms`
THEN the message will be sent using twilio

Documentation:

- [ ] [This flowchart](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/provider_selection_flowchart.drawio.pdf) should be updated. The code no longer works like this.
- The draw.io file can be downloaded here if you want to use that for updates: 
[https://app.zenhub.com/files/257953872/456b674e-c48e-4e96-adbe-509c87b2374e/download](https://app.zenhub.com/files/257953872/456b674e-c48e-4e96-adbe-509c87b2374e/download)

## QA Considerations
-   [ ] a regression passes (this covers the two use cases listed under testing, above
-   [ ] Check logs for any anomalies

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/962?planning-poker) with Zenhub @babyjunior56 @cris-oddball @EvanParish @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by npmartin-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/962?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @MackHalliday @mchlwellman

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/962?planning-poker) with Zenhub @kalbfled

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/962?planning-poker) with Zenhub @k-macmillan

**Comment by kalbfled** [comment]
```
.../notification-api$ grep -rni TODO | grep 962
grep: .git/objects/pack/pack-dabca01fa53fc6afa4ae334458d6c65f6cbd587e.pack: binary file matches
app/dao/provider_details_dao.py:29:# TODO #962 - Should this be deleted? sms provider swap code
app/dao/provider_details_dao.py:73:# TODO #962 - Should this be deleted? sms provider swap code
app/dao/provider_details_dao.py:83:# TODO #962 - Should this be deleted? sms provider swap code
app/dao/provider_details_dao.py:157:# TODO #962 - Should this be deleted? sms provider swap code
app/provider_details/switch_providers.py:28:# TODO #962 - Should this be deleted?
```

**Comment by npmartin-oddball** [comment]
Canning this. We're not updating this logic for the api as we're transitioning to enp-api.
