### ISSUE TITLE
Spike Audit OpenAPI spec

### ISSUE THREAD

**Issue by kalbfled** [department-of-veterans-affairs/notification-api#965]
### User Story(ies)

**As a** VA Notify engineer
**I want** to scope the work that it will take to update the OpenAPI specs
**So that** we know how much work it will be to get the specs up to date

### Additional Info and Resources

- The repository contains an [openapi yaml file](https://github.com/department-of-veterans-affairs/notification-api/tree/that is largely out of sync with the code
  - https://learn.openapis.org/#advantages-of-using-openapi
- [Endpoint Table](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/SPIKES/VA%20Notify%20Endpoints.md)
- [Endpoint Spreadsheet](https://docs.google.com/spreadsheets/d/18AfqlEOWlrnigauO57jA0VP3RMHTaP4luknqBxrcbuY/edit#gid=115873237)

## Engineering Checklist

- [ ] Check the endpoints in the `openapi.yaml` file to see which ones need to be updated (of the endpoints we are keeping) - aask QA if there are any questions.
- [ ] Check the backlog when creating new tickets to avoid duplicates being created
  -  *For example, we probably don't need to make more tickets for the endpoints we are planning on removing.*
- [ ] Create tickets to update the swaggers endpoints that need to be updated.

## Acceptance Criteria
_**Required**_
- [ ] Endpoints have been checked and ones that need updated documentation have been identified
- [ ] Tickets have been created to update the endpoints we are keeping

## QA Considerations
- [ ] works with developer to answer any questions they may have about a well defined openapi spec.

## Potential Dependencies
_Leave blank if n/a_

## Out of Scope
_Leave blank if n/a_

**Comment by kalbfled** [comment]
#1021 added the sms_sender_id attribute to the Notification and NotificationHistory models.  This attribute is required but can be null.  The specs don't reflect this.

**Comment by cris-oddball** [comment]
@EvanParish this ticket can be repurposed to update the routes we just audited.

**Comment by EvanParish** [comment]
@EvanParish Note: The VA Notify Endpoints Audit spreadsheet has all the routes highlighted that we are keeping. We need to ensure that they are all properly documented in our OpenAPI doc and the appropriate routes are included in our Postman collection. (This spreadsheet will be added to GitHub in our teams repo)

**Comment by mjones-oddball** [comment]
@EvanParish Is the intention to repurpose this ticket to simply audit the openapi doc for those flagged as keep in your spreadsheet and create tickets to make those updates? If so... can you update the title/description? CC @tabinda-syed

**Comment by EvanParish** [comment]
@mjones-oddball I believe we wanted to use this to update the OpenAPI spec and Postman, but it would make sense to use it to identify the scope of that work and what tickets would be necessary to get those in order. It might be too much to all be in one ticket. I'll get this ticket updated appropriately.

**Comment by cris-oddball** [comment]
@cris-oddball to rewrite to be more complete/sensible

**Comment by npmartin-oddball** [comment]
Not doing as we're moving to enp.
