### ISSUE TITLE
Load Testing: Measurements - Celery - process_pinpoint_results

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#967]
## Additional Info and Resources
We do not currently know how long "[process_pinpoint_results](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/celery/process_pinpoint_receipt_tasks.py#L59)" takes to complete. Without knowing how long it takes to complete we are unable to identify abnormalities or expected throughput for our system. 

Find and implement a way to measure how long the method takes to process so we can create metrics. This could take many forms, but the key is to identify the time difference between when the method was called and when the method responds.

Datadog is preferred but if there's another method that you want to suggest, please discuss with @k-macmillan 

## Engineering Checklist
- [ ] Measurement of time for each call to the method is stored somewhere
  - [ ] Preferable to know if the method ran clean or if it hit an error (but not necessary for MVP)
- [ ] Add this to Datadog

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/967?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney @trevor2718

**Comment by Eallan919** [comment]
Lucas to share EOD/tomorrow feelings around this

**Comment by tabinda-syed** [comment]
I see that this ticket was added and pointed back in November. Tagging @ldraney to ask if there is any more information that we could add to the description (if any sections don't apply, then please remove their headings when you review).

**Comment by tabinda-syed** [comment]
^ Removed that blocker because it is already in closed.

**Comment by ldraney** [comment]
I need more datadog experience before I can refine it.  I told Tabinda I'd help on it, but I'll have more insight once we actually get this kind of relevant information for our sms endpoint.  Then I can hopefully do the same with pinpoint.

**Comment by mjones-oddball** [comment]
@ldraney @k-macmillan Is this ticket still valid/needed?

**Comment by cris-oddball** [comment]
This ticket is in a now-deprecated epic. It looks like it is still needed, so I'll add it to the new Performance testing epic until we decide what to do with it.

@k-macmillan ^ do we still need this?

**Comment by npmartin-oddball** [comment]
Closing.
