### ISSUE TITLE
Load Testing: Increase Locust Instance

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#968]
## Issue
Our Locust instance is currently underpowered for Load Testing (t3.micro). Pricing is only based on usage and load testing is a finite task, so we can control the cost by turning it on and off within the GH action to ensure it's only on for the duration of the test itself.

Initial load test with the t3.micro saw API calls taking roughly 490ms, and up to 2300ms. Looking through cloudwatch these should be running in 0.1 seconds or less (on average). Upgrade to something several times more powerful so the limiting factor is not the computational power of the tester.

Created a new instance unintentionally by pushing up the changes without reverting the manual test that was done to ensure it could be done. Remove the old instance.

## Checklist
- [x] See if we can increase the Locust instance type and specify size and cost
- [x] Update Infra to accommodate new locust instance type
- [ ] Remove old instance

**Comment by mjones-oddball** [comment]
Kyle increased the instance to t3.xlarge and the estimated cost is $1.17 monthly

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/968?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney @trevor2718

**Comment by mjones-oddball** [comment]
Removed "Locust appears to be running python 3.6 (it slipped our radar due to being named "python36"). Ensure locust is running the most current version we can. The [locust-init.cfg](https://github.com/department-of-veterans-affairs/vanotify-infra/blob/master/cd/utility-infrastructure/locust-init.cfg) within the Infra repo also appears to dump to log streams which may be useful." to be handled in future load testing work.

**Comment by k-macmillan** [comment]
The old instance remains. This was a result of manually changing it to a `t3.xlarge`, leaving that change, then pushing up terraform again. The manual change was done because I was not sure it could be done, but it should have been put back. Good to know for the future. 

Attempted terminate the dangling instance but it gave a warning regarding volumes. I needed to look into it further before confirming, so that is what's left for this task.

**Comment by kalbfled** [comment]
See [vanotify-infra PR 489](https://github.com/department-of-veterans-affairs/vanotify-infra/pull/489).  I made a change in Terraform and did not see any dangling instance before or after deploying the change to infra dev.

**Comment by cris-oddball** [comment]
This work was already completed a couple of sprints ago (the instance has been at t3.xlarge for some time now) and there is no dangling instance.Moving this ticket to Done and removing the high priority tag.
