### ISSUE TITLE
Billing: BigQuery - New daily file upload

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#971]
## User Story
As the Franchise Fund/VA Notify
I want a monthly billing report per SMS use case and billing code
So that I can bill clients for notifications

## Overview
In https://github.com/department-of-veterans-affairs/vanotify-team/issues/672 we created a new table in BigQuery (dev only for now) called dev-billing to house the following data. Now we must update that data daily like we do for statistics.

- Date
- Service Name
- Service ID
- Channel Type
- Template Name
- Template ID
- Sender
- Sender ID
- Billing Code
- Count (this is the total outbound messages for the month)

## Request
Billing data should be grouped and counts aggregated by day, template id, sender, and billing code because some business lines (like VEText) are tracking different groups which need to be billed within a use case. Franchise fund requires that we break it down by use case rather than just by service.

- [x] Research the existing file upload process that we're doing for statistics and replicate that for this new billing import
- [x] Create a new nightly csv upload on S3 for billing data - please specify what time this will occur and confirm with product
- [x] Validate over the course of a few days that this is working as expected by querying the data in bigquery
- [x] Document this technical process to integrate with BigQuery and save in Github - https://github.com/department-of-veterans-affairs/vanotify-team/tree/master/Engineering/BigQuery
- [x] QA evaluation - testing steps required

## A/C

- [x] CSV goes to S3 nightly at 12:15 am and is uploaded to BigQuery from there via the lambda
- [x] Data is formatted as follows:
    - [x] Notification counts should be grouped by: day, template_id, sender, billing_code
    - [x] Data is filtered to "sms" channel_type
    - [x] Data for sender_id and sender should be null. More work is needed to get these data points populated.

Sample Dataset

Raw
| date | service_id | service | template_id | template | billing_code | channel_type | sender_id | sender |
|---|---|---|---|---|---|---|---|---|
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e5` | VEText | `ba85e3ae-3872-4062-b1eb-a05166fa0106` | VEText SMS API Template | Station 1 | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e5` | VEText | `ba85e3ae-3872-4062-b1eb-a05166fa0106` | VEText SMS API Template | Station 1 | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e6` | VEText | `ba85e3ae-3872-4062-b1eb-a05166fa0107` | VEText SMS API Template | Station 2 | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e7` | VEText | `ba85e3ae-3872-4062-b1eb-a05166fa0108` | VEText SMS API Template |  | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e8` | VEText | `c6a4340a-a5c1-4d4a-a7be-6b019388a2e1` | BVA Virtual Hearing Reminders | VHA | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e8` | VEText | `c6a4340a-a5c1-4d4a-a7be-6b019388a2e1` | BVA Virtual Hearing Reminders | VHA | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e8` | VEText | `c6a4340a-a5c1-4d4a-a7be-6b019388a2e1` | BVA Virtual Hearing Reminders | VHA | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e8` | VEText | `c6a4340a-a5c1-4d4a-a7be-6b019388a2e1` | BVA Virtual Hearing Reminders | VHA | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e8` | VEText | `c6a4340a-a5c1-4d4a-a7be-6b019388a2e1` | BVA Virtual Hearing Reminders | VHA | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e9` | VEText | `f3ce9f0e-6698-4577-9f2f-f5c6979e882d` | BVA In-Person Hearing Reminder |  | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e10` | VEText | `f3ce9f0e-6698-4577-9f2f-f5c6979e882d` | BVA In-Person Hearing Reminder |  | sms |  | 
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e10` | VEText | `f3ce9f0e-6698-4577-9f2f-f5c6979e882d` | BVA In-Person Hearing Reminder |  | sms |  | 

Aggregated
| date | service_id | service | template_id | template | billing_code | channel_type | sender_id | sender | count |
|---|---|---|---|---|---|---|---|---|---|
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e5` | VEText | `ba85e3ae-3872-4062-b1eb-a05166fa0106` | VEText SMS API Template | Station 1 | sms |  |  | 2 |
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e6` | VEText | `ba85e3ae-3872-4062-b1eb-a05166fa0107` | VEText SMS API Template | Station 2 | sms |  |  | 1 |
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e7` | VEText | `ba85e3ae-3872-4062-b1eb-a05166fa0108` | VEText SMS API Template |  | sms |  |  | 1 |
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e8` | VEText | `c6a4340a-a5c1-4d4a-a7be-6b019388a2e1` | BVA Virtual Hearing Reminders | VHA | sms |  |  | 5 |
| 2022-12-01 | `22016c3a-7fa4-4156-b27d-7aec9fa6c1e9` | VEText | `f3ce9f0e-6698-4577-9f2f-f5c6979e882d` | BVA In-Person Hearing Reminder |  | sms |  |  | 3 |

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/971?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney @trevor2718

**Comment by kalbfled** [comment]
The process we are using for statistics is one way to do this.

**Comment by ianperera** [comment]
@mjones-oddball, spoke to @trevor2718 since he had the ticket to create the table, he will pick this one up.

**Comment by trevor2718** [comment]
Finished query, working on Celery task.

**Comment by mjones-oddball** [comment]
@trevor2718 If you understand the process you need to implement/how this works now might be a good time to summarize that here and @ Cris so she can be aware for testing purposes.

**Comment by trevor2718** [comment]
@mjones-oddball I think it should be done like this :

1. aggregate the dev-bill table data from other tables
2. update the dev-bill table with the aggregated data
3. generate a monthly csv report
4. update the csv report to S3 (need to confirm what time this should occur)

Please let me know your thoughts

**Comment by mjones-oddball** [comment]
@trevor2718 I'm kind of confused by your summary, you mention updating the dev-billing table in step 2 before step 4 which I believe is how the table gets updated in big query. Also generating a monthly csv report is out of the scope of this ticket. We're putting the data in big query so we can develop a query that will do that part. The purpose of this ticket is to put the billing data into big query following the same method we use for statistics data. 

For your question on time - please let me know when the statistics data is happening and we can talk. Is it possible to use the same timing as that?

**Comment by cris-oddball** [comment]
@mjones-oddball I will need some guidance on validating this.

@trevor2718 I do not see that the documentation has been created for this; please do so (see the checkboxes in description for the link.

**Comment by trevor2718** [comment]
@cris-oddball I have some questions:

1. Is there a template or guidance on how to create the related document?
2. I couldn't find when `generate_daily_notification_status_csv_report` task is scheduled to run from the code. (It uploads the csv report to S3, and we need to know when this happens)
3. I think the Lambda function `nightly_stats_bigquery_upload_lambda` trigger time needs to be checked from CloudWatch.

**Comment by mjones-oddball** [comment]
Moving some updates from slack into here:
1) Evan will be pairing up with Trevor to help surge on this since it's high priority
2) @EvanParish can you help look into the timing of the run? We need to lock that down and document it.
3) @trevor2718 In addition to confirming the lambda file upload process is working, you'll need to also validate that the data is aggregated as expected and present in big query. Keep in mind that means you'll need to send notifications in dev before the daily data is uploaded to S3. If you don't know how to do that in postman now is the time to learn. Evan knows how and can work through that with you. You can send yourself emails and SMS.

Reminder that we are aggregating and grouping by day, template id, and billing code so keep that in mind as you're creating your test data.

**Comment by mjones-oddball** [comment]
@cris-oddball Info for using BigQuery. Let me know if you need any help accessing or querying. It's a pretty simple UI and uses google's simplified version of SQL. 

- BigQuery (you should have access): https://console.cloud.google.com/bigquery?project=vsp-analytics-and-insights&pli=1
![image.png](https://images.zenhubusercontent.com/62041308731c2b2cdc47288b/f5fd7177-ff9d-4835-9122-d9890160a6e2)

**Comment by EvanParish** [comment]
To answer Trevor's questions and share knowledge here. 

`create_nightly_billing` runs at 12:15AM and `create_nightly_notification_status` runs at 12:30AM (Easter Time) 

Piecing things together, we see that:
- `create_nightly_notification_status` runs `generate_daily_notification_status_csv_report` as one of it's tasks when it gets executed. 
- `generate_daily_notification_status_csv_report` writes data to the s3 bucket
- This lambda gets involved at some point to read the info from the s3 bucket and put it in bigquery. Is it triggered when the file is created in s3? A question for @trevor2718 and I to figure out.
  - `lambda_functions/nightly_stats_bigquery_upload/nightly_stats_bigquery_upload_lambda.py`

**Comment by mjones-oddball** [comment]
Evan and I spoke about the following:

- This ticket made it unclear, but the original intention was to pull in multiple channel types (email/sms). Currently the work Evan/Trevor did is filtered by SMS. I am updating the requirements for this to be filtered by SMS for now given the urgent need is SMS and the data structure would support adding email data in the future if desired.
- Evan was unable to find a link between sender and the notification history data. We assumed that this data was already in place, but it appears that it isn't. Additional work will have to be scheduled to capture sender as part of the notification data.

**Comment by EvanParish** [comment]
**dev-billing NOW HAS DATA!!!** It looks like the last test I ran last night was completely successful! The data in the csv files uploaded to s3 and are in the proper format (finally). The query also seems to be working properly. During testing yesterday (12-16) I sent the data below. Looking at the table entries for 12-16 we see the proper numbers sent for that template with and without a `billing_code`, plus an additional one that must have been sent by someone else with a different template.

## Testing Data
2022-12-16 
service name "VA Notify"
template: 
- id: 0b5ad0e8-2639-4cb1-88c5-174e2d43299a
- name: 123

sent 2 messages with `billing_code`: "test_code"
send 5 message with no `billing_code`

![image](https://user-images.githubusercontent.com/104009494/208250605-ca26e858-ceb8-442f-89e8-bc8e3e884204.png)

**Comment by EvanParish** [comment]
In my testing, I managed to print the query being run. I've passed it to @mjones-oddball  for thoughts, but thought others might be interested in taking a look as well.
cc @cris-oddball 

```sql
SELECT 
  services.name AS service_name, 
  notifications.service_id AS service_id, 
  templates.name AS template_name, 
  notifications.template_id AS template_id, 
  notifications.billing_code AS billing_code, 
  count(*) AS count, 
  notifications.notification_type AS channel_type 
FROM 
  notifications 
  JOIN services ON notifications.service_id = services.id 
  JOIN templates ON notifications.template_id = templates.id 
WHERE 
  notifications.notification_status IN -- is this check necessary?
    ('sending', 
    'sent', 
    'delivered', 
    'failed', 
    'temporary-failure', 
    /* should 'technical-failure' be included here? */
    'permanent-failure', 
    'returned-letter')
  AND notifications.key_type != 'test'
  -- date format when printed: 2018-04-01 04:00:00
  AND notifications.created_at >= '2022-12-17 00:15:00'
  AND notifications.created_at < '2022-12-18 00:15:00'
  AND notifications.notification_type = 'sms' 
GROUP BY 
  services.name, 
  notifications.service_id, 
  templates.name, 
  notifications.template_id, 
  notifications.billing_code, 
  notifications.notification_type
```

**Comment by mjones-oddball** [comment]
I reviewed the query and overall agreed with it. I will create a new task to dig into how we should be filtering on status so that we're only pulling in billable events. For now this is good.

@cris-oddball As discussed I put a sample set of data and how it would be aggregated at the bottom of the task description. Let me know if you have any questions.

**Comment by cris-oddball** [comment]
Deployed to perf and staging. Will run Monday, midnight. Going to send and record sms messages throughout the day to validate against BQ on Tuesday.

**Comment by cris-oddball** [comment]
On Monday, 12/19, sent [test sms messages](https://docs.google.com/spreadsheets/d/1wR0LwC7c3gQMeseokjMaU8bTbCxf2k_H5e7aKxmSVNU/edit?usp=sharing) in staging using different service IDs, sms template IDs, and billing codes.

On Tuesday, 12/20, validated that BQ had the data (it also had data from 12/16 and 12/17) and [grouped the data correctly.](https://docs.google.com/spreadsheets/d/1EiG0_TMrDR8ukUOdpH5tauUR8RORWYrMqngw9pnu2uw/edit?usp=sharing)

Also validated that the S3 bucket had yesterdays' data [as described.](https://docs.google.com/spreadsheets/d/1vRCUMu4EWmkJcUacK43eduxkjVXOxy8xNwPduiFuSk4/edit?usp=sharing)

Sending more test messages today for review Tuesday, 12/21, to ensure that data is correctly deleted and recreated based on the 4 day fetch.

@mjones-oddball

**Comment by cris-oddball** [comment]
Example celery messages for creating a nightly billing task
```
[2022-12-20 05:15:00,095: INFO/MainProcess] Received task: create-nightly-billing[ea52935c-aad9-4c63-8d17-3beb88c94632]  
{
    "name": "delivery",
    "levelname": "INFO",
    "message": "create-nightly-billing took 0.1581",
    "pathname": "/app/app/celery/celery.py",
    "lineno": 20,
    "time": "2022-12-20T05:15:00",
    "requestId": "no-request-id",
    "application": "delivery",
    "logType": "application"
}
[2022-12-20 05:15:00,261: INFO/ForkPoolWorker-4] create-nightly-billing took 0.1581
```

Example Lambda logs
```
START RequestId: a56bde28-cbb7-44d5-b530-806f7e9f3eb0 Version: $LATEST
END RequestId: a56bde28-cbb7-44d5-b530-806f7e9f3eb0
```

**Comment by cris-oddball** [comment]
For tonight's test: Part of the grouping is by billing code. So sending some messages with the same template, but different billing codes would give you a more complete test.

**Comment by cris-oddball** [comment]
**PASSES QA**

Validated that the nightly run delivered the data grouped as expected for last night and that the previous night's run is also accurate.
See above [link](https://docs.google.com/spreadsheets/d/1wR0LwC7c3gQMeseokjMaU8bTbCxf2k_H5e7aKxmSVNU/edit?usp=sharing) to the Google spreadsheet for data.
