### ISSUE TITLE
New Communication Items for BVA and Comp & Pen

### ISSUE THREAD

**Issue by mjones-oddball** [department-of-veterans-affairs/notification-api#976]
We have two new communication items (notification preferences in VA Profile) that we need to add to our database. It doesn't appear that this is available for creation/update through the API at this time, however, once it exists it can be added to templates via the API.

| Item Name | VA Profile Item ID |
|---|---|
| Comp and Pen Payment Notifications | 5 |
| Board of Veterans' Appeals Status Updates | 6 |

Dev
- [x] Add the new notification preferences to the communication_items table

Staging
- [x] Add the new notification preferences to the communication_items table
- [x] Update all SMS templates in the BVA service with the applicable communication_item_id for Board of Veterans' Appeals Status Updates (available for update via the API)

Perf
- [x] Add the new notification preferences to the communication_items table

Production
- [x] Add the new notification preferences to the communication_items table
- [x] Update all SMS templates in the BVA service with the applicable communication_item_id for Board of Veterans' Appeals Status Updates (available for update via the API)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/976?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @k-macmillan @kalbfled @ldraney @trevor2718

**Comment by kalbfled** [comment]
@mjones-oddball This is ready for verification.

**Comment by mjones-oddball** [comment]
@kalbfled Scope change. I checked Dev and see that all the communication items up to 4 exist, so I'm going to add an item to this ticket to add 5 and 6 to Dev so it's not out of date. Apologies I didn't realize they would have been added there.

**Comment by mjones-oddball** [comment]
Verifications Passed:
- Staging had 11 sms templates, all with item 6 assigned for communication_item_id.
- Communication items 5 and 6 found in perf, staging, and prod. 
- Prod had 11 sms templates, all with item 6 assigned for communication_item_id.

**Comment by kalbfled** [comment]
@mjones-oddball I added the items in dev.

**Comment by mjones-oddball** [comment]
@kalbfled Thank you! Excellent work. Validated dev.
