### ISSUE TITLE
Select tools to use to secure VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#99]
The purpose of this spike would be to research and document any security concerns that must be addressed for VANotify prior to going into production

- [x] Consult with VA/VSP teams to understand and evaluate what tools are currently used for security/vulnerability scanning (Fortify, Sonar, Snyk, sastscan, hawkeye, bandit, dependabot, pyup, codeclimate, Twistlock)
  - [Fortify](https://www.microfocus.com/en-us/products/static-code-analysis-sast/overview) - may need a licence, and what do we do with the uploaded results?
  - [Sonar](https://github.com/SonarSource/sonarcloud-github-action) - nice github action, free for open source projects
  - [Snyk](https://support.snyk.io/hc/en-us/articles/360004699377-Snyk-for-Python) - dependency scanning, [nice github action](https://github.com/snyk/actions/tree/master/python), pricing unclear
  - [Hawkeye](https://github.com/hawkeyesec/scanner-cli#python) - dependency scanning (out-of-date and vulnerabilities), security issues (using **bandit**)
  - [Bandit](https://pypi.org/project/bandit/) - security issues scanning, installed as python dependency
  - [Dependabot](https://github.com/department-of-veterans-affairs/notification-api/settings/security_analysis) - dependency scanning and updates, build into github
  - [PyUp](https://pyup.io/) - dependency scanning, can make PRs or run as a github check
  - [CodeClimate](https://codeclimate.com/quality/) - not really security, more of a code quality tool
  - Twistlock
- [x] Document options that need to be added
  ~~- [ ] Do we need to add a [Security policy](https://docs.github.com/en/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository), as recommended by github?~~
- [x] Discuss and document the results within our team
- [x] Create ADR
  - [ADR 0005](https://github.com/department-of-veterans-affairs/vanotify-team/blob/638757ff3234221257cc1011fbf28b3b7794b85e/documents/adr/0005-select-tools-to-secure-VANotify.md)
 
Timebox - 3 Days

**Security Toolbox Needs:**
- Static code analysis
- Dependency checks
- Docker container vulnerability checks 
- Scanning of committed Secrets
- Scanning for PII is out of scope for this story 

**Other guiding principles**
- ease of implementation
- maintenance
- documentation
- potential learning curve
- for open source options: activity of maintainers, adoption rate

**Notes:** 
- As a part of the implementation story (#104) and the subsequent stories that are added, the tools that we implement must be provided for documentation in the ATO

**Assumption:**
- Implementation of the options for remediation will be done in a different card (#104). One card will be created for each tool that we add.

**Comment by ffafara-tw** [comment]
Tools that might be of interest that are offered by DOTS (DevOps Tool Suite) team:
- Codacy
- code.scan
- Twistlock

**Comment by ffafara-tw** [comment]
Should ADR be part of this or implementation story?

**Comment by ffafara-tw** [comment]
Tooling used by VSP:
- Brakeman (scanning ruby dependency tree for known security vulns)
- plus being responsive to github security alerts in the repos
- static code analysis I think is mostly rubocop / eslint at this point

**Comment by ffafara-tw** [comment]
Another tool to review:
https://github.com/marketplace/actions/sast-scan

**Comment by ffafara-tw** [comment]
https://github.com/sonarsource/sonarcloud-github-action

**Comment by ffafara-tw** [comment]
https://lgtm.com/
It was bought by GitHub and seems well integrated with GitHub.
Free for opensource.

**Comment by lingtran** [comment]
Matrix and recommendations documented in [this spreadsheet](https://docs.google.com/spreadsheets/d/1wmWVBbnpzYUcEiNc3lQjwNUhOhxSQtB-WZTc3dDUyKI/edit#gid=0)

**Comment by lingtran** [comment]
After following up with team at dev sync this morning, took some follow-up actions and have these recommendations:

**Recommend: Bandit / Hawkeye**
- Meets our needs (minus image scanning), but no dashboard

**Recommend: lgtm**
- Provides dashboard view that bandit/hawkeye don't provide, so it will be complimentary to them. Also does code reviews.

**Recommend: dependabot**
- More actively maintained and now within the Github ecosystem, so easier integration. Also being used by other orgs like gov.uk, Mozilla, and PyPi. Has flexibility of adding reviewer to dependency update if necessary.

It depends how we feel between the two below, recommendation is:
_Based on price estimates comparisons, Twistlock is more expensive than Snyk, though Twistlock is a more robust tool with more application lifecycle management coverage (including runtime monitoring). We can try using Snyk free version as a stopgap until we are ready to consider more whole lifecycle management needs and/or to see if Snyk's free version's constraints impede our productivity. 

If we need a tool like Twistlock/Prisma Cloud anyway for runtime support, we should opt for it over Snyk, especially see if the low-end $9k business edition meets all our needs._

**Twistlock**
- meets all of our needs include image scanning and provides runtime monitoring
already in VA ecosystem, used by DOTS
pricing: https://aws.amazon.com/marketplace/pp/Palo-Alto-Networks-Prisma-Cloud-Enterprise-Edition/B07QDBGS6L
based on ^^ estimates, low-end $9000 (business edition) to $18000 (enterprise edition) per year.

**Snyk**
- big pros: can scan terraform and has github actions, and more or less free, other than need license for container scanning. 
- con: there is free version for both Snyk OpenSource and Snyk Container licenses. Snyk's value-add is container scanning and terraform scanning. Free version is limited to 100 container scan tests per month / 200 vulnerability scans per month. For up to 10 devs, standard edition is $708 per month (approx $8,496 per year). hawkeye/lgtm meets all our needs except for image scanning. If we are going to pay for this tool, we might as well go for Twistlock which also provides runtime monitoring.

**Comment by lingtran** [comment]
Noting a conversation has been scheduled with Sara Diaz from InfoSec for next week.
