### ISSUE TITLE
BUG: Celery logs reporting errors on unregistered task, STG and PRD

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#991]
**Describe the bug**
In both the staging and production environments, the ecs/notification-celery/ logs are showing a high number of errors such as 
`[2022-12-06 20:21:00,086: ERROR/MainProcess] Received unregistered task of type 'switch-current-sms-provider-on-slow-delivery'.`

**To Reproduce**
1. Go to Cloudwatch > Log Groups
2. Click on either staging-notification-api-log-group or prod-notification-api-log-group
3. Click the most recent ecs/notification-celery/ log
4. Search for "ERROR" and scroll until you find a series of logs starting with:
`[2022-12-07 12:51:30,417: ERROR/MainProcess] Received unregistered task of type 'switch-current-sms-provider-on-slow-delivery'.`
There will a number of line entries for this error. The last log entry should be something like
`KeyError: 'switch-current-sms-provider-on-slow-delivery'`

**Expected behavior**
There should be zero log entries complaining about switch-current-sms-provider-on-slow-delivery since we stopped using it.
Note from Kyle:` Looked over this. If the old queues are polled we will almost certainly find switch-current-sms-provider-on-slow-delivery defined in the json. This should just be a simple housekeeping thing to clean it out.`

Note: Go in the AWS Console for SQS Queues to poll/remove

- [ ] Remove those message from the queues for Dev
- [ ] Verify it's no longer coming up in logs for Dev

- [ ] Remove those message from the queues for Perf
- [ ] Verify it's no longer coming up in logs for Perf

- [ ] Remove those message from the queues for Staging
- [ ] Verify it's no longer coming up in logs for Staging

- [ ] Remove those message from the queues for Prod
- [ ] Verify it's no longer coming up in logs for Prod

**Screenshots**
Screenshot of log sequence
![Screen Shot 2022-12-07 at 3.30.40 PM.jpg](https://images.zenhubusercontent.com/630696b479f5cca51e546872/c1112e8f-ba03-4d6e-844d-6391586e2f09)

**Additional context**
Note that our version of celery is pretty far out of date and that we recently removed the switch provider on slow delivery stuff.

A common theme for this error on stackoverflow and other places (see links below) is to restart the workers. That may not be possible for us, as Jesse explains:

> The celery workers should redeploy every time the API is deployed as well. During that process, it will bring up new celery/api tasks and then bleed the old tasks connections and kill off the previous tasks. There isn't really a way to "reboot" tasks in Fargate, but you have to deploy them over again... it should have spun up new tasks during whenever the most recent deployment happened.

- [Celery info on tasks](https://docs.celeryq.dev/en/latest/userguide/tasks.html)
- [KeyError could be a red herring](https://groups.google.com/g/celery-users/c/IAG1lBXiPq8/m/NKgRw9WyQbgJ) and most likely that NotRegistered is the issue (since we don't have that method anymore?)
- [Stackoverflow](https://stackoverflow.com/questions/9769496/celery-received-unregistered-task-of-type-run-example?page=1&tab=votes#tab-top) about restarting workers and other possibkle solutions
- [Blog](https://www.oscaralsing.com/resolving-celery-received-unregistered-task-of-type-error/) for possible solution
- search Google for `python celery "Received unregistered task of type"` for a whole lot more.

**Comment by cris-oddball** [comment]
Possibly related....
![image.png](https://images.zenhubusercontent.com/630696b479f5cca51e546872/48fc321d-0d25-4f93-abaf-4e72ffc7f973)

> For some reason we ALWAYS have 5 things sitting in those queues (all envs, didn't grab staging in the screenshot). When they hit retention they somehow magically re-appear

**Comment by k-macmillan** [comment]
Looked over this. If the old queues are polled we will almost certainly find `switch-current-sms-provider-on-slow-delivery` defined in the json. This should just be a simple housekeeping ticket to clean it out.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/991?planning-poker) with Zenhub @cris-oddball @EvanParish @ianperera @jakehova @justaskdavidb2 @k-macmillan @kalbfled @ldraney

**Comment by kalbfled** [comment]
Per our group discussion, modifying the queues happens through the AWS SQS console.

**Comment by tabinda-syed** [comment]
Whoever picks this up, please plan on pairing with another engineer (who doesn't know how to do it; e.g., Dave, Baldwin) and show them how to do this.

**Comment by k-macmillan** [comment]
This appears to have resolved itself. No mention of it in prod in the last week. 
![image.png](https://images.zenhubusercontent.com/620be841701e64d34dd34065/74772c02-37a0-4d77-a9f5-2cf64ff80f10)

Searched staging for a day, had no references to it. Closing this.
